### ISSUE TITLE
Ads visible on https://www.abclinuxu.cz

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1000]
### Describe the issue

Ads visible. Blocked in uBlock Origin by Peter Lowe's list:
`
||bbelements.com^`

### One or more specific URLs where the issue occurs

https://www.abclinuxu.cz
https://www.root.cz

### Your settings

- OS/version: OS X 10.10.5
- Browser/version: 57.0.2987.133 (64-bit)
- AdNauseam version: 3.3.33 (dev)
- Other extensions you have installed: none

### Screenshot in which the issue can be seen

![image](https://cloud.githubusercontent.com/assets/737638/25312817/f41a289a-2854-11e7-8241-6efc27bed65d.png)

**Comment by cqx931** [comment]
Fixed https://github.com/dhowe/uAssets/pull/45/commits/024fa7cb7262a56ff0e581cb434b62b8d6be2d1f

**Comment by cqx931** [comment]
For abclinuxu, I don't see the ad in the middle.
Ads on https://www.root.cz/ are all already hidden for me, though not collected.

**Comment by dhowe** [comment]
yes, this is probably a location issue -- in any case, please create a ticket for the collection issue
