### ISSUE TITLE
Bug: can't set any other clicking frequency then "Click ALL Ads"

### ISSUE THREAD

**Issue by dumblob** [dhowe/AdNauseam#1001]
### Describe the issue

For some reason when I change the frequency of clicking (as the only change to default settings), it's not saved and thus not working.

### One or more specific URLs where the issue occurs

N/A

### Screenshot in which the issue can be seen

N/A

### Steps for anyone to reproduce the issue

1. install recent AdNauseam and run it
1. set *hide ads*, set *click ads*, set *block malicious ads*, **un**set *make exceptions for non-tracking Ads* (otherwise leave everything with default settings)
1. switch to tab "SETTINGS" of AdNauseam and click any other clicking frequency/amount setting then the default "Click ALL Ads"
1. close the settings page or just switch to another AdNauseam settings tab
1. the frequency settings got lost :open_mouth:

### Your settings

- OS/version: Arch Linux 4.9.23-lts
- Browser/version: Chromium 58.0.x
- AdNauseam version: 3.3.32
- Other extensions you have installed: cVim, Privacy Badger, Stylish, appear.in, Font Rendering Enhancer, Lazarus: Form Recovery, Violentmonkey, The Great Suspender

**Comment by dhowe** [comment]
Verified

**Comment by cqx931** [comment]
When user changes clicking frequency, the property in background is correctly changed, but the interface was not correctly updated.
Here is the fix for the issue:
https://github.com/dhowe/AdNauseam/pull/1004
