### ISSUE TITLE
Ads on https://www.root.cz/ and https://www.abclinuxu.cz are not collected.

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1008]

**Comment by greysonevins** [comment]
@dhowe I cannot duplicate ads for the website, however, the user who made the original ticket (#999) did comment on another website he was having issues with and displayed photos of the ads: https://www.abclinuxu.cz. 

I am going to switch the ticket to needs verification and change the name to include abclinuxu.cz

**Comment by cqx931** [comment]
I have already fixed the ads on https://www.abclinuxu.cz, they should be both hidden and collected by now. 
For www.root.cz I can reproduce the ads reported by the user, but they are now already hidden but not all collected on my computer. 
It could be that those ads on root.cz are location specific, you can try to see whether you can see the ads by using an VPN outside the states.

**Comment by greysonevins** [comment]
https://github.com/dhowe/uAssets/pull/46

**Comment by greysonevins** [comment]
@dhowe completed?
