### ISSUE TITLE
Slider goes back to the default position after observing ad details

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1031]
To reproduce:
1.Open the vault
2.Change the slider
3.Click an ad to observe the detail
4.Back to the vault window, the slider is in full range again

**Comment by greysonevins** [comment]
@cqx931 I think I noted this somewhere.. I can't find where. It doesn't change the filter itself, but the static slider position. I will have to look into this one more.

**Comment by greysonevins** [comment]
@cqx931 made a hot-fix above, plus a fix to something I didn't notice in the original slider fix.

**Comment by cqx931** [comment]
fixed
