### ISSUE TITLE
First-run page problems on web-ext

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1032]
![image](https://cloud.githubusercontent.com/assets/3056154/25602762/03c57a12-2f29-11e7-96b9-1eff4e9c8730.png)

**Comment by greysonevins** [comment]
http://stackoverflow.com/a/12314823

It seems that it works still with the extension in the extension store for FF, but not with the web-ext version. All that I could find that could fix this issue is changing the about:config settings 
`dom.allow_scripts_to_close_windows` to true.

**Comment by greysonevins** [comment]
There is another issue though with this page. Firefox is not compatible with registering undefined properties of objects. So there needs to be a correction with testing `hasOwnProperty()`

@cqx931 I will add a commit in a second for this issue

https://airbrake.io/blog/javascript-error-handling/referenceerror-reference-to-undefined-property-x

**Comment by greysonevins** [comment]
Also brodcast reference error needs to be changed from `details.broadcast === true` to `details.broadcast`.

**Comment by cqx931** [comment]
The latest commit is breaking the firstrun page, please check and fix.
![image](https://cloud.githubusercontent.com/assets/3056154/25982480/6e0e34ca-370f-11e7-8866-5c53322670bb.png)

**Comment by dhowe** [comment]
We need to make sure such errors are caught *before* being merged

**Comment by greysonevins** [comment]
![image](https://cloud.githubusercontent.com/assets/11656811/26003500/d547b300-3700-11e7-8a92-18007927ebc4.png)

I am not getting the same issue with Firefox or Chrome.

**Comment by cqx931** [comment]
The issue is for webExt. I don't get this issue with Firefox or Chrome as well.

Also it doesn't happen to me consistently.
Sometimes in web-ext, if firstrun page pops up as expected, the texts are missing.
However, sometimes, if firstrun page doesn't pop up and I go to the page by typing in the address bar, the page renders normally.

**Comment by cqx931** [comment]
Some more findings.
1. The issue about 'Let's Go' button remains.
`window.open(location, '_self').close();` This used to work in firefox without changing the setting in about:config, but it doesn't seem to work in web-ext.

2.The performance of first-run page is not very stable from my testing. So far I have seen three different situations without changing the code:

- First-run page renders as expected
- First-run page doesn't show up
- First-run page pops up for one second and disappears.

**Comment by cqx931** [comment]
Interestingly, if I test `window.open(location, '_self').close(); ` in a simple web page, it works well in chrome/opera but not in firefox. Not sure how it works in the current firefox version.

**Comment by dhowe** [comment]
I can recreate any of these issues in Firefox 54.0a2 (2017-03-10) (64-bit) with web-extensions

**Comment by dhowe** [comment]
This should be fixed in 'firstrun' branch, though I get some kind of new warning (see below). In any case, @cqx93, please verify...

**Comment by cqx931** [comment]
'let's go' button works well, but I the firstrun page still close itself automatically if I load the extension with run-webext.sh. It works fine if I load the file from folder after running make-artifacts.sh.
It also works fine in chrome.

**Comment by dhowe** [comment]
strange -- works for me with run-webext.sh

**Comment by cqx931** [comment]
yes, I'm on 'firstrun' branch for sure.

**Comment by dhowe** [comment]
commit 4b674a82b2f0ad ?

**Comment by cqx931** [comment]
Exactly...

**Comment by dhowe** [comment]
Hmmm, I just got it to fail once. It seems to work correctly about 90% of the time for me :/

In any case, I think you can go ahead and fix the errors in #1073, then we can come back to this...

**Comment by cqx931** [comment]
sounds good, so far it fails 100% of the time for me (with run-webext.sh)...

**Comment by greysonevins** [comment]
Still getting, on every run,`Scripts may not close windows that were not opened by script.` on firstrun page with the page not closing after "Let's Go!". Some runs, the firstrun page is closing before the page is used.

**Comment by dhowe** [comment]
Is anyone checking the console(s), or using the debugger?

The message I see in the console whenever it auto-closes is:

```
[firefox/remote.js][debug] Received message from client: {"from":"root","type":"addonListChanged"}
Last extension reload: 01:06:06 GMT+0800 (HKT)[firefox/remote.js][debug] 
```

**Comment by cqx931** [comment]
I don't see this in the console but I can reproduce this in the terminal.

**Comment by dhowe** [comment]
Lets see if we can verify that the message only appears when the page auto-closes...

**Comment by cqx931** [comment]
I tried a few times, but I also see this message if firstrun page loads or when it doesn't show up at all.

**Comment by dhowe** [comment]
We should try to add a breakpoint to the source in vault.js so that we can access the debugger before the page closes

**Comment by cqx931** [comment]
You mean `firstrun.js` here? Not sure how to add a breakpoint before the browser/extension loads

Just tried adding `--no-reload` to run-webext.sh and the auto-close issue seems to be solved when loaded from run-webext.sh.
`web-ext run -v --no-reload --firefox-profile="${1:-default}"`

**Comment by dhowe** [comment]
excellent -- my theory was that it was reloading and then the first-run page didn't run (on the 2nd launch)... but I wasn't sure how to resolve... good work
