### ISSUE TITLE
 [WebExt] No reaction when clicking 'Export' button in vault

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1033]
![image](https://cloud.githubusercontent.com/assets/3056154/25603273/d418f9a2-2f2c-11e7-8e00-32724902c97c.png)

**Comment by greysonevins** [comment]
https://github.com/dhowe/AdNauseam/issues/1039

**Comment by greysonevins** [comment]
https://github.com/dhowe/AdNauseam/pull/1049

**Comment by cqx931** [comment]
verified and close

**Comment by cqx931** [comment]
It works for firefox but not for web extension now.

**Comment by cqx931** [comment]
Things work fine until here: https://github.com/dhowe/AdNauseam/blob/merged1.12.2/platform/firefox/vapi-common.js#L73

**Comment by cqx931** [comment]
uBlock fixed the back up button in web-ext here:
https://github.com/gorhill/uBlock/commit/510eba6bc4a6c2714704ce597d388e97de3796af

The Export button in AdNauseam is using exportTofile function in core.js instead, need to intergrate the changes manually there.

**Comment by cqx931** [comment]
fixed here https://github.com/dhowe/AdNauseam/pull/1065/commits/e9e1a2d3cb5286f740f3e403aba574d5adbc4092

**Comment by cqx931** [comment]
The 'export button' in dashboard is fixed, but the one in AdVault is still problematic.

**Comment by cqx931** [comment]
preventDefault is called when the anchor is clicked in AdVault in web-Ext

**Comment by cqx931** [comment]
If I click "Export Ads" in options.html instead of  dashboard.html#options.html, the same error occurs. But the same method works in uBlock if I click the button from settings.html

**Comment by cqx931** [comment]
The error message after json file has been successfully downloaded in dashboard.html#options.html
![image](https://user-images.githubusercontent.com/3056154/26976555-d9ac4890-4d56-11e7-8607-888b8e128937.png)

**Comment by cqx931** [comment]
To recreate:
1.Pull the latest changes from branch newnew1.12.0
2.Switch to branch 'newnew1.12.0' and run it as web-ext
2.Open advault, click 'export ads'
3.After the click the AdVault page got refreshed and the page hangs there, no download is happening.

**Comment by greysonevins** [comment]
I am having the same issue as @cqx931. It looks like the changes worked for the setting's page, but the advault now freezes.  It looks like the page messes up when executing this on shared.js
```var exportToFile = function ()```

**Comment by dhowe** [comment]
Has anyone checked whether this works in normal firefox (or whether its a problem with newer firefox versions) ? Has anyone traced the issue in the debugger to see where it actually fails?

**Comment by cqx931** [comment]
For web extension, aren't we already testing it with normal Firefox instead of developer edition?(tools/run-webext.sh) 
I also don't think it is related to Firefox versions, it is related to a fix made by uBlock in merged1.12.0 (please see my comments above), their fix works for the export button in settings page but not for vault.html.

I have traced the issue up to here, but not sure what happens afterwards.
https://github.com/dhowe/AdNauseam/blob/master/platform/chromium/vapi-common.js#L65

**Comment by dhowe** [comment]
I have recreated this on  merged1.13.0 / Firefox 56.0b6

![image](https://user-images.githubusercontent.com/737638/29924825-45c1c2ba-8e2c-11e7-99dd-d12466c917c5.png)

![image](https://user-images.githubusercontent.com/737638/29924828-47a08b70-8e2c-11e7-84a6-b9bd9a9dd69d.png)

**Comment by cqx931** [comment]
I can't recreate this with merged1.13.0 Firefox 56.0b6...

**Comment by dhowe** [comment]
@greysonevins pls give a try...

**Comment by greysonevins** [comment]
Same issue but no error message...
<img width="1072" alt="screen shot 2017-08-31 at 12 22 22 pm" src="https://user-images.githubusercontent.com/11656811/29933838-116d5fea-8e47-11e7-8bf7-db5c129783d6.png">

**Comment by dhowe** [comment]
That doesn't look like my firefox ...

**Comment by dhowe** [comment]
I'm a bit stumped by this one.. same code (https://github.com/gorhill/uBlock/blob/master/platform/chromium/vapi-common.js#L56),  running when export is clicked from settings or from vault (the former works, the latter hangs)

**Comment by greysonevins** [comment]
@dhowe export for me on ff works now

**Comment by dhowe** [comment]
fixed, pls verify

**Comment by cqx931** [comment]
verified, close
