### ISSUE TITLE
[WebExt] No warning message for other ad blockers

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1035]

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/issues/801
Management.getAll() is not implemented yet in the web extension API.
Shall we mark this as 'on hold' until uBlock officially lunch their web extension version? If it is still not implemented then, we can try to detect other extensions in a different way.

**Comment by dhowe** [comment]
Management.getAll() is now implemented for Firefox >= 55 (see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/management#Browser_compatibility)

So we need to check the FF version, and if >= 55, then do the check, otherwise ignore...

**Comment by dhowe** [comment]
fixed pls verify in chrome/webext

**Comment by cqx931** [comment]
verified, close
