### ISSUE TITLE
[merged1.12.2] DNT header is not sent

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1036]
onBeforeSendHeaders() is not called while browsing.
This still works with 1.11.4, but not after merged with 1.12.2

**Comment by cqx931** [comment]
I am not sure whether it is the code here that caused this issue:
Somehow there were code that marked as `//ADN `that got deleted in vapi-background.js for chrome, and I didn't get noticed for a conflict when I did the merge.
When I review the code, the changes seem to be very confusing for me and I am not sure where I should add back the code.
Could you please take a look at this? @dhowe

https://github.com/cqx931/AdNauseam/commit/0b32afbd001431a32c7a766a8f6ef203e6f0418c#diff-d04c15ee6bff6a6269c6aee25a7c7522L1109

**Comment by dhowe** [comment]
can, but may take a while...

**Comment by cqx931** [comment]
platform/chromium/vapi-background.js

**Comment by cqx931** [comment]
fixed in newnew-1.12.0
