### ISSUE TITLE
Ads visible on batmanstream.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1039]
### Describe the issue

Ads visible on batmanstream.com (TW)

### One or more specific URLs where the issue occurs
https://www.batmanstream.com/

### Screenshot in which the issue can be seen

![image](https://cloud.githubusercontent.com/assets/737638/25659992/cc434488-303c-11e7-8e23-12b78d8cd339.png)

Chromium

**Comment by greysonevins** [comment]
@cqx931 @dhowe  closed?
