### ISSUE TITLE
[FAQ] add new entry: 'What do purple entries in the logger represent ?'

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1048]

**Comment by greysonevins** [comment]
@dhowe Just to clarify, when you say purple entries, are you talking about the object elements like id or attempts that come up purple in the developer console and background.html?

**Comment by dhowe** [comment]
This refers to the 'logger', not the (browser) console or inspector, which you can access [this way](https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#how-do-i-use-the-logger-and-what-are-the-different-types-of-entries-it-shows). Purple entries represent the requests that would normally be blocked by a list but are instead allowed by adn, as they may result in visible ads.

**Comment by greysonevins** [comment]
https://github.com/dhowe/AdNauseam/wiki/FAQ#what-do-purple-entries-in-the-logger-represent
@dhowe

**Comment by dhowe** [comment]
pls fix font size

![image](https://cloud.githubusercontent.com/assets/737638/25982404/cc13c34c-370e-11e7-9111-ceda38ffd408.png)

**Comment by greysonevins** [comment]
@dhowe fixed
