### ISSUE TITLE
Soundcloud still playing audio ads

### ISSUE THREAD

**Issue by DragoonX6** [dhowe/AdNauseam#1051]
### Describe the issue
Soundcloud still plays (Dutch) audio ads, such as the tele2 ad.
Vanilla uBlock Origin does block the ads, so I suspect it's a missing filter.

### One or more specific URLs where the issue occurs
Not a specific URL I can give, you're most likely to encounter ads on popular channels/tracks.

### Your settings
- OS/version: Windows 7 x64 Ultimate
- Browser/version: Firefox Developer Edition 54.0a2
- AdNauseam version: AdNauseam v3.3.331 uBlock Originv1.11.0

**Comment by greysonevins** [comment]
Currently, I do not see any missing filters between uBlock and AdNauseam. But I am trying to see if I can trigger one. I will have to get back to you on this. @DragoonX6

**Comment by dhowe** [comment]
@greyonevins use the logger to make a list of any requests that are blocked in ublock and allowed in adn. we will likely need to recreate one of those blockings, either in adnauseam.txt, or in core.js::allowAnyBlockOnDomains

**Comment by greysonevins** [comment]
@cqx931 @dhowe was able to reproduce the ad and find a fix to the SoundCloud Ad.

**Comment by cqx931** [comment]
@greysonevins  Thanks! 
@DragoonX6  To verify, please update the adnauseam filter in your settings page and check whether it fixes the issue.

**Comment by dhowe** [comment]
closing pending verification from @DragoonX6
