### ISSUE TITLE
Font problem in current release

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1054]
![image](https://cloud.githubusercontent.com/assets/737638/26296620/1715d088-3f02-11e7-8990-3fb77f1da4bb.png)

**Comment by cqx931** [comment]
This is fixed in the current master branch, are we going to fix it for the release as well?

**Comment by dhowe** [comment]
No, if its only this minor aesthetic issue, then its OK... Are there other font problems in the UI?

**Comment by cqx931** [comment]
Also in other buttons in dashboard other than settings.(Also fixed now.)
![image](https://cloud.githubusercontent.com/assets/3056154/26299684/48482fc8-3f0e-11e7-9bfa-df62ff6dd1fa.png)

**Comment by dhowe** [comment]
ok, fine for now
