### ISSUE TITLE
Broken testcase caused by server migration

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1061]
[The test case: cookie-setting-ad](http://lab-lamp.scm.cityu.edu.hk/adntest/cookie-setting-ad.html) is broken caused by server migration.
http://rednoise.org/adntest/cookie.php

**Comment by dhowe** [comment]
also waiting on @shadoof for server restart

**Comment by dhowe** [comment]
please recheck

**Comment by cqx931** [comment]
verified.
