### ISSUE TITLE
Use web-ext v1.9.1 or later for Firefox web-extensions

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1070]
to check:
`$ web-ext --version
`

to update:
`$ npm install -g web-ext`

**Comment by greysonevins** [comment]
@dhowe it looks like I was using v1.9.1, but I reinstalled it to be sure. I'll let you know if it helps.

**Comment by dhowe** [comment]
welcome back -- are you having some problem with webext?

**Comment by greysonevins** [comment]
Still same issues of first run page closing and export button not working.
