### ISSUE TITLE
FAQ: How do I run the browser's debugger on different parts of the extension?

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1080]
Please add a DevFAQ entry (for the various platforms) for this question.

Then check for other 'pending' entries in the DevFAQ  and see what you can answer

**Comment by cqx931** [comment]
Entries added for:
[How do I run the browser's debugger on different parts of the extension?](https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#how-do-i-run-the-browsers-debugger-on-different-parts-of-the-extension)
[How do I debug a text-ad that is being hidden, but not collected?](https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#how-do-i-debug-a-text-ad-that-is-being-hidden-but-not-collected)
