### ISSUE TITLE
Vault display with a large collection of ads

### ISSUE THREAD

**Issue by greysonevins** [dhowe/AdNauseam#1081]
### Describe the issue
For some reason, the ad vault slider only chooses a smaller number of ads when there are a bulk amount of ads to display (not sure what the limit that causes it is but happens on Opera, Chrome, and FireFox.
### Screenshot in which the issue can be seen
This is the what the vault loads as.
![image](https://user-images.githubusercontent.com/11656811/27346419-275f79ec-55bb-11e7-9605-9ba1a7e6835f.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version:
- Browser/version:
- AdNauseam version:
- Other extensions you have installed:

**Comment by dhowe** [comment]
This is intended behaviors so that the user does not load thousands of ads without realizing how long it might take.

It is also shown in the display text on the left.

If you feel this is not clear enough, please a) add an FAQ item, and b) propose a design fix, and/or open a design ticket

**Comment by dhowe** [comment]
Some design ideas proposed by @greysonevins below -- thoughts?

![27348409-f1b97e80-55c1-11e7-828e-e78893dbd32b](https://user-images.githubusercontent.com/737638/27365691-04c070c6-5674-11e7-9f39-ff886ef63e19.png)
![27351986-2087f376-55cd-11e7-90bf-b1acd4c89663](https://user-images.githubusercontent.com/737638/27365693-04c7b2e6-5674-11e7-935a-adc8cac2f2b3.png)
![27351978-18938a2c-55cd-11e7-9cef-9acafa7524a7](https://user-images.githubusercontent.com/737638/27365692-04c56040-5674-11e7-9819-95a33cf7eb68.png)

**Comment by dhowe** [comment]
@greysonevins , pls do PR for FAQ entries as well, as otherwise they go live immediately

**Comment by greysonevins** [comment]
@dhowe (y) I will make sure to do that going forward--thank you.

**Comment by mushon** [comment]
@greysonevins I pushed a quick fix (https://github.com/dhowe/AdNauseam/commit/774018883642be415d175517541bcbbdc5a3d8ee) to make the ``?`` mark default to our link blue. To use it with green you will need to add the ``cost`` class to it.

**Comment by cqx931** [comment]
![image](https://user-images.githubusercontent.com/3056154/27504625-358fa52a-58c0-11e7-8897-b2aeb9b610e1.png)
Shouldn't it only show the help link when `(* SHOWING)` is visible?

**Comment by dhowe** [comment]
Indeed

**Comment by greysonevins** [comment]
thanks @mushon and @cqx931 for the help. Let me know if the updates work.

**Comment by cqx931** [comment]
verified
