### ISSUE TITLE
One click "off-line" installer suggestion

### ISSUE THREAD

**Issue by baybal** [dhowe/AdNauseam#1092]
How about making an installer that does activate the developer mode and edits chrome's "registry" in offline to speedup the deployment?

**Comment by baybal** [comment]
Also, what about adding some code polymorphism features into such an installer to prevent it being picked up by chrome statistics/telemetry?

**Comment by dhowe** [comment]
that sounds great -- is this something you might be able to help with?

**Comment by baybal** [comment]
I'm trying to figure out how to kill the annoying popup without having to repeatedly edit browser libs. Ideally, I want to have the setup being persistent without killing the autoupdate.

One solution I came on is to prevent the browser from loading the blacklist. It is possible to do with OS standard filtering functionality or /etc/hosts, but I think it is better to sabotage the blacklist loading from the extension itself. There is at least one way to do so, but it is likely that goog will "fix" their extension API the moment they see it. I will try to find a more durable method for that.

**Comment by dhowe** [comment]
> kill the annoying popup without having to repeatedly edit browser libs. 
> One solution I came on is to prevent the browser from loading the blacklist

Which specific popup are you talking about,  and which blacklist ?

**Comment by baybal** [comment]
>which specific popup

The one that says "disable developer mode extensions" if they are installed in dev mode. The blacklist is the one that is used to blacklist "harmful" extensions using their key

**Comment by dhowe** [comment]
got it

**Comment by baybal** [comment]
Indeed, but the blacklist is checksum checked, altering it means that we have to mess with the checksum too. The way to mess with the checksum exists, but it is not a durable solution - it will be most likely patched the moment they see their flaw.

**Comment by dhowe** [comment]
Understood

**Comment by mneunomne** [comment]
Inactive, closing
