### ISSUE TITLE
[Firefox Linux] Specific URL not working

### ISSUE THREAD

**Issue by ntmlod** [dhowe/AdNauseam#1094]
### Describe the issue
I installed the add-on recently with no modification on the settings in replace of uBlock Origin, it has been working for every page I browsed until the next URL.

### One or more specific URLs where the issue occurs
http://slideplayer.com/slide/3921940/

### Screenshot in which the issue can be seen
https://postimg.org/image/tkm0ui1qz

### Steps for anyone to reproduce the issue
Nothing to add

### Your settings

- OS/version: SL6.9 (RHEL6)
- Browser/version: Firefox 52.2.0 (64 bits),
- AdNauseam version: 3.3.331
- Other extensions you have installed: NoScript, uMatrix, Privacy Badger, Random Agent Spoofer, Self-Destructing Cookies, HTTPS Everywhere, TrackMeNot, Disconnect, Decentraleyes

No issue on Chromium with AdNauseam last stable ( 3.3.403) and some other same add-ons as Firefox.

Comment : uBO not working also...

**Comment by dhowe** [comment]
What is the exact issue (the screenshot is too small to read) ? Is it the problem that one or more ads are visible? 

If this is also not working on uBO then it is not an AdNauseam-specific issue... have you also filed an issue on uBO ?

**Comment by ntmlod** [comment]
I uploaded a bigger picture, the ads circling the slideshow are not hidden.
[![AdNauseam_bug.jpg](https://s23.postimg.org/ejhiu1wez/Ad_Nauseam_bug.jpg)](https://postimg.org/image/yquymctw7/)
Sorry for disturbance, I forgot to test it first with uBO. I will raise a ticket on the right spot.
