### ISSUE TITLE
Empty page on messenger.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1095]
Please check the following report (from Mozilla reviews). First see if you can recreate the problem, then, if so, check that it is not a uBlock problem. If it is not, then fix.

```
A user has left a review for your add-on, AdNauseam.

Rating:
5 out of 5 stars

Review:
Thank you for your support,
I just found that one of third-party RUS: filters caused messenger.com web page to look line an empty page.


```

**Comment by dhowe** [comment]
perhaps related to this: https://github.com/gorhill/uBlock/issues/2770#issuecomment-313921867

**Comment by greysonevins** [comment]
@dhowe the edits made to gorhill/ublock have been made already to the new branches of ADN. The issue seemed to be with [easylist](https://forums.lanik.us/viewtopic.php?f=64&t=37415&p=120637&hilit=messenger#p120637) and the [fixes were made here](https://github.com/easylist/easylist/commit/49e2a5f88da780a892112076feb25c280ba56132).
