### ISSUE TITLE
Legacy addon - not working in FF55

### ISSUE THREAD

**Issue by Silur** [dhowe/AdNauseam#1096]
### Describe the issue
Not working in Firefox 55, all ads get past, settings menu buttons have no text, firefox considers it as legacy (since all browsers use a common extension language now)

### One or more specific URLs where the issue occurs
Any Url

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version: ArchLinux x86_64
- Browser/version: FIrefox 55
- AdNauseam version: 3.3.331

**Comment by greysonevins** [comment]
I am getting the issue as well. AdNauseam works with ff 54 but not with 55.0b it looks like.
![image](https://user-images.githubusercontent.com/11656811/28330227-c4a882d8-6bba-11e7-9074-f3311ddb3149.png)


[Label reads](https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u&utm_source=inproduct)

**Comment by greysonevins** [comment]
It looks like FF is transitioning to a web-extension API that uBO has addressed with "The webext version of uBO is a hybrid, a webext wrapped into a thin layer legacy one, necessary for a seamless transition." See gorhill's comment on gorhill/uBlock/issues/2576 @dhowe 

See also gorhill/uBlock/issues/2728 and gorhill/uBlock/issues/622 and [Mozilla blog response on transition](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/). 

With the current dev tools on the master branch "run-webext" does not come as legacy and run-ff works but says legacy. It may be that we solved the issue with merging with uBlock a while back but will need verification @dhowe @cqx931.

Currently, the store version v3.3.331 is not compatible with beyond ff 54. We will need to work on this further @Silur. Thank you for your patience. For now, you can build ADN from source or use a past version of Firefox like v54. [See the documentation here](https://github.com/dhowe/AdNauseam/wiki/Building-AdNauseam-from-source-(for-developers)).

**Comment by dhowe** [comment]
![image](https://user-images.githubusercontent.com/737638/28349847-da4e9cea-6c77-11e7-9ca8-01345abffb85.png)

**Comment by dhowe** [comment]
'Legacy' should only be a warning, until FF57. 
See this [note](https://github.com/gorhill/uBlock/issues/2794), and follow the links...

**Comment by greysonevins** [comment]
@dhowe I got a false positive too when I tried, but if you update to ff 55.0b and then reinstall ADN from the store, it doesn't work properly. Let me know if you get the same result.

**Comment by greysonevins** [comment]
@dhowe you were right. In setting up a Firefox, the problem resolved itself. I'm not able to duplicate the issue now.

**Comment by dhowe** [comment]
Is your note above incorrect then?

> 
Currently, the store version v3.3.331 is not compatible with beyond ff 54. We will need to work on this further @Silur. Thank you for your patience. For now, you can build ADN from source or use a past version of Firefox like v54.

**Comment by greysonevins** [comment]
@dhowe edits made to the comment.

**Comment by dhowe** [comment]
closing as unverifiable
