### ISSUE TITLE
Text ads in Google Maps

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1097]
![image](https://user-images.githubusercontent.com/737638/28362141-f225ff1c-6cad-11e7-9a05-f7bb3b416071.png)

**Comment by greysonevins** [comment]
@dhowe PR made

**Comment by cqx931** [comment]
Not sure why, but I can't reproduce these text ads when I search in google maps.

**Comment by greysonevins** [comment]
@cqx931 try https://www.google.com/search?q=tshirts+near+me&npsic=0&rflfq=1&rlha=0&rllag=40695703,-73948291,1703&tbm=lcl&ved=0ahUKEwiP2Luf-ZjVAhVKdz4KHdN-DZIQjGoIZw&tbs=lrf:!2m4!1e17!4m2!17m1!1e2!2m1!1e2!2m1!1e3!3sEAE,lf:1,lf_ui:10&rldoc=1

**Comment by cqx931** [comment]
Thanks for the link! But no...I still don't see any ad
![image](https://user-images.githubusercontent.com/3056154/28442121-9069c39a-6da6-11e7-91ea-ce67931047a8.png)

**Comment by greysonevins** [comment]
@cqx931 could you try a different location like new york?

**Comment by cqx931** [comment]
Thanks @greysonevins , verified and close.
