### ISSUE TITLE
 Fails to Click ad on fmovies.is (self.Adblock)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1099]
submitted 1 day ago * by Mr__Democracy

> I want AdNauseam to click the ad's on fmovies.is for me, but the ad's on the page sometimes don't have a domain extension (rederects to proper url after you click it), which confuses AdNauseam and causes the Ad-Click to fail.
> http://i.imgur.com/5pousyx.png
> I am able to block them however, but I can't support fmovies.is when AdNauseam won't do it's job.

**Comment by MrDemocracy** [comment]
Can't this be implemented? Many sites use these "smart ads" now. 
[Mgid](https://www.mgid.com/advertisers) is the company responsible for these ads.

All the real links can be found in a javascript([from this url](http://servicer.mgid.com/)) that you get on page load. In the javascript you can see, the same "teaser"-ID's used for the html elements, listed along with the real urls. 

# Example

**The ad's classes:**
`mgline teaser-2338995 type-w` 

**Snippet from the javascript:**
```javascript
["quantomcoding.com", "2338995", "1", "It's Time To Zero-Extend Your Monthly Income", "", "0", "", " ", " ", "KWd_0uh9coEBGCLLWn-lgaYpcrzUCL-6W3_IhJpHnqy00QqIxDG4xxvkxtPkGuQc", {
    "i": "http://imgg-cdn.mgid.com/2338/2338995_492x328.jpg",
    "l": "//www.mgid.com/ghits/2338995/i/40172/0/pp/4/2?h=KWd_0uh9coEBGCLLWn-lgaYpcrzUCL-6W3_IhJpHnqy00QqIxDG4xxvkxtPkGuQc&tt=Direct",
    "adc": [],
    "sdl": 1,
    "dl": "",
    "type": "w",
    "clicktrackers": []
}],
```
**What the ad looks like:**
<img width="193" src="https://user-images.githubusercontent.com/23060864/30503562-02292aca-9a6b-11e7-86d4-f25dd171ff77.png">

Another thing...

Please make it so this isn't displayed to the ad vault, it messes up the symmetry:
![mgid_logo_mini_43x20](https://user-images.githubusercontent.com/23060864/30503900-5b840468-9a6c-11e7-95ac-679d626e1003.png)
