### ISSUE TITLE
Visible ad on securityaffairs.co

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1101]
http://securityaffairs.co/wordpress/60798/terrorism/darkweb-terrorism.html

![image](https://user-images.githubusercontent.com/737638/28499012-6b846ed8-6fde-11e7-87f5-62cb23cab6fa.png)

**Comment by greysonevins** [comment]
https://github.com/dhowe/uAssets/pull/53

@dhowe
