### ISSUE TITLE
Not working in Firefox 54

### ISSUE THREAD

**Issue by bad-and-ugly** [dhowe/AdNauseam#1102]
Hi everyone, this is my first time using github so sorry if I'm not giving enough details or not submitting to the right place.

### Describe the issue
Noticed yesterday that no ads are being blocked on Firefox 54.0.1 (32-bit) on Windows 10 64-bit. The purple button is there on the toolbar but clicking on it just opens a white, blank rectangle instead of the menu.

### One or more specific URLs where the issue occurs
Everywhere, I think. YouTube and OKCupid for sure =P

### Screenshot in which the issue can be seen
![untitled](https://user-images.githubusercontent.com/17955441/28500648-3da5104e-6fa2-11e7-8353-46a0130861f2.png)

### Steps for anyone to reproduce the issue
I just noticed it all of a sudden, so I don't really know. But give it a try on YouTube with Firefox 54.

### Your settings

- OS/version: Windows 10 64-bit
- Browser/version: Firefox 54.0.1 (32-bit)
- AdNauseam version: 3.3.403
- Other extensions you have installed:
---- TrackMeNot
---- GBBD Caixa Economica Federal 3.5.2 (disabled)

**Comment by greysonevins** [comment]
@bad-and-ugly I can't seem to reproduce this one
<img width="953" alt="screen shot 2017-07-24 at 6 40 43 pm" src="https://user-images.githubusercontent.com/11656811/28550078-94a9d9dc-70ac-11e7-9ad2-c2431fb9c1df.png">

**Comment by greysonevins** [comment]
@bad-and-ugly I can't seem to reproduce this one.
<img width="956" alt="screen shot 2017-07-24 at 8 15 33 pm" src="https://user-images.githubusercontent.com/11656811/28550120-e0bf0f22-70ac-11e7-9098-88c0d7e7ad95.png">

**Comment by dhowe** [comment]
this issue should be fixed in the current version, 3.4: https://addons.mozilla.org/en-US/firefox/addon/adnauseam/

can you give it a try and report back? thanks

**Comment by mneunomne** [comment]
Outdated, closing
