### ISSUE TITLE
The AdNauseam Filter blocks Google Logo

### ISSUE THREAD

**Issue by MrDemocracy** [dhowe/AdNauseam#1103]
### Describe the issue
When I'm logged in and goto [photos.google.com](https://photos.google.com/), the [Google logo](https://www.gstatic.com/images/branding/googlelogo/svg/googlelogo_clr_74x24px.svg) in the top left corner, is nowhere to be seen.

This is the reason:
||gstatic.com/images/branding/googlelogo^$important
under "# Ad Tag"
in the AdNauseam Filter list.

Why is this filter even there?

### One or more specific URLs where the issue occurs
[photos.google.com](https://photos.google.com/)

### Screenshot in which the issue can be seen
<img width="316" src="https://user-images.githubusercontent.com/23060864/28676675-88986208-72eb-11e7-986f-6131b1b1028e.png">

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
Have AdNauseam Filter Enabled
Login to your Google account.
Goto https://photos.google.com/

### Your settings

- OS/version: macOS Sierra 10.12.6
- Browser/version: Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- AdNauseam version: v3.3.404
- Other extensions you have installed: Please don't make me go through that again.

**Comment by dhowe** [comment]
@cqx931 this line was added in 89b90fb -- do you recall its intended purpose?

**Comment by cqx931** [comment]
That was intended to block the "google logo" from google ads. But if that brings trouble to google logo display in other cases, we can remove it from the adnauseam filter

**Comment by cqx931** [comment]
Please verify the fix above by updating your AdNauseam filters:

1. Go to AdNauseam Settings, then open the 3rd-party-filters panel
2. Click 'update' button for AdNauseam filters
3. Reload the page on which you saw the problem

**Comment by MrDemocracy** [comment]
@cqx931 The filter is gone now, the Google logo is back. Thank you 😊
