### ISSUE TITLE
Easylist Warning with Ultimate Merged List

### ISSUE THREAD

**Issue by bgiesing** [dhowe/AdNauseam#1112]
### Describe the issue
The warning that Easylist is disabled shows up when you you have it disabled and Fanboy's Ultimate Merged List enabled. Since the UML includes EasyList, AdNauseam shouldn't show the warning with it enabled.

### One or more specific URLs where the issue occurs
Settings page

### Screenshot in which the issue can be seen
N/A

### Steps for anyone to reproduce the issue
1. Disable Easylist, EasyPrivacy, Fanboy’s Annoyance List, and Fanboy’s Enhanced Tracking Lists (only Easylist is technically needed but the UML covers all 4 so if you use it, you likely have the other 3 also disabled)
2. Enable Fanboy+Easylist-Merged Ultimate List under Other
3. Warning will appear even though Easylist is technically there, just under a different subscription.

### Your settings

- OS/version: Windows 10 Pro Insider Preview Build 16257.rs_prerelease.170728-1630 (64 bit)
- Browser/version: Vivaldi Snapshot 1.11.917.22
- AdNauseam version: 3.3.403 
- Other extensions you have installed:
  - Tampermonkey
  - Enpass
  - Vanilla Cookie Manager
  - Distill Web Monitor
  - Qmee
  - User Agent Switcher
  - Poper Blocker
  - Smile Always

**Comment by dhowe** [comment]
thanks @bgiesing , will look into it

**Comment by cqx931** [comment]
fixed in merge1.13.8 https://github.com/dhowe/AdNauseam/pull/1182/commits/594afdc75091f1ab1fb4ae66bfe3d621d7760da3

**Comment by dhowe** [comment]
please verify and close
