### ISSUE TITLE
User Email Concern: Twitch + YouTube

### ISSUE THREAD

**Issue by greysonevins** [dhowe/AdNauseam#1113]
"I have noticed that ads on these platforms (in video) don’t get clicked, but on youtube, there is a pause when an ad is supposed to play, also on Twitch, ads simply still show."

**Comment by greysonevins** [comment]
![image](https://user-images.githubusercontent.com/11656811/29338362-d5c8d296-81e2-11e7-84d3-7bd77516ee79.png)

Video ad shown here by the user.

**Comment by cqx931** [comment]
I found that by adding this dynamic filtering rule, I was able to block many visual ad:
`www.twitch.tv https://pubads.g.doubleclick.net/gampad/ads xmlhttprequest block`
However, when I try to add one in static rules, it doesn't work any more, not sure why yet.
`||pubads.g.doubleclick.net/gampad/ads?$xmlhttprequest,domain=twitch.tv`

![image](https://user-images.githubusercontent.com/3056154/29883426-47a6686e-8d7e-11e7-968e-9194266429b4.png)

**Comment by cqx931** [comment]
Please try this and verify: `||pubads.g.doubleclick.net/gampad/ads$important,xmlhttprequest`

**Comment by cqx931** [comment]
verified and close
