### ISSUE TITLE
Merge uBlock releases up to v1.13.8

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1115]
Merge releases, one-by-one, until reaching v1.14 -- ping me with any questions as you go.

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/tree/merged1.12.4
@dhowe  As this is not a major release, I would suggest that we only go through the basic test cases for AdNauseam, and it everything works, I would merge this to master and go ahead to merge 1.13.0, which needs a full run of release testing.

**Comment by dhowe** [comment]
That sounds reasonable -- the most important part of the current uBlock work is moving toward a a Firefox version built on WebExtensions. We need to get a 'hybrid' web-extensions version up on the Dev channel as soon as possible.

See https://github.com/gorhill/uBlock/releases/tag/1.13.10 and https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/tree/merged1.13.0
existing issue with master branch:https://github.com/dhowe/AdNauseam/issues/1137
Do we still need to test fire-fox version for this?

**Comment by dhowe** [comment]
I'm not clear on what that issue refers to ... ? We still need a JPM version until the WebExt version is live in the store...

**Comment by cqx931** [comment]
I see, will test for the old JPM version as well.
