### ISSUE TITLE
Block all requests to functionalclam.com in adnauseam.txt

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1116]
background: https://www.techdirt.com/articles/20170813/00092137987/how-dmcas-digital-locks-provision-allowed-company-to-delete-url-adblock-lists.shtml

**Comment by hfn1** [comment]
I think I follow. Does it directly affect AdNauseam (via Privacy Badger?), i.e. can trick us into whitelisting?

Helen Nissenbaum, Professor
NYU + Cornell Tech
http://www.nyu.edu/projects/nissenbaum/

**Comment by dhowe** [comment]
The issue is that DMCA is being used to remove a site from one of the publicly maintained lists (of ad-related sites that the browser should avoid). This is a very problematic precedent, and one that we should be proactive against -- an easy first step is to add the same rule to our own list, and see if we also get served with a DMCA takedown

**Comment by cqx931** [comment]
https://github.com/dhowe/uAssets/pull/60 Let's see...

**Comment by cqx931** [comment]
can this be closed? @dhowe
