### ISSUE TITLE
Broken in Firefox 56.0b3

### ISSUE THREAD

**Issue by simbalion** [dhowe/AdNauseam#1117]
### Describe the issue
Doesn't work

### One or more specific URLs where the issue occurs
wowinterface.com

**Comment by dhowe** [comment]
Please fill in the requested information re: OS, version, etc.

**Comment by greysonevins** [comment]
@simbalion can you give more details?

**Comment by simbalion** [comment]
Afraid not! It seems to be working now? I used ublock for a few days and I didn't think to check what version of AdNauseum I was using so I don't know if this is a new version or what, but since re-installing it from the website I haven't seen any ads.
