### ISSUE TITLE
Add support for ad click and watching on YouTube for selected YouTubers

### ISSUE THREAD

**Issue by MrDemocracy** [dhowe/AdNauseam#1118]
### Describe the issue
I'm trying to use [this](https://greasyfork.org/en/scripts/13226-youtube-whitelist-channels-in-ublock-origin) script to whitelist certain channels on YouTube, but it doesn't seem to work with.
　　　　　  　  Ꙟ 
　　　　　　　 　└─────────────────┐
_Edit: Turns out there was something wrong with the **script**, [here](https://greasyfork.org/en/scripts/22308-youtube-whitelist-channels-in-ublock-origin) is a working version._ 
<br>
Could you add a way to whitelist channels you want to support on YouTube? Or maybe add support for video ads to AdNauseam, and make it work on all channels?
<br>
_Edit: Could [this](https://greasyfork.org/en/scripts/22308-youtube-whitelist-channels-in-ublock-origin) script be used to make AdNauseam click and watch ads on selected YouTubers channels?_

### Your settings

- OS/version: macOS 10.12.6
- Browser/version: Google Chrome 61.0.3163.100 (Official Build) (64-bit)
- AdNauseam version: v3.4.103

**Comment by dhowe** [comment]
@greysonevins pls look into what is required here

**Comment by Atavic** [comment]
[Author](https://greasyfork.org/nb/users/17102-gorhill) of the script isn't @gorhill that says:

>I can't vouch for the scripts, you will have to find out yourself whether they work.

See: [Wiki](https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site#a-youtube-channel)

**Comment by MrDemocracy** [comment]
It doesn't have to be that exact script, I would just like a way to whitelist YouTube channels. 
It would have been much better if AdNauseam could watch and click the ad for me. 
But I just want to be able to help out my favourite YouTubers with ad revenue, so whitelist would be okay too...

**Comment by greysonevins** [comment]
@MrDemocracy unfortunately, there is nothing unique within a video URL that can differentiate youtube channels. So your only option is to disable ADN when on a channel that you don't want ADN to block ads for.

**Comment by MrDemocracy** [comment]
@greysonevins found a [working version](https://greasyfork.org/en/scripts/22308-youtube-whitelist-channels-in-ublock-origin) of the scrip I mentioned earlier, couldn't this be used?

**Comment by greysonevins** [comment]
@dhowe what do you think about this one?

**Comment by Atavic** [comment]
Does it make sense? By whitelisting a user/channel you're temporarily whitelisting youtube as a whole. Is like trying to defeat Ad Nauseam purpose from inside Ad Nauseam itself.

You can use another browser for that.

**Comment by MrDemocracy** [comment]
@Atavic Yes, or just change to incognito mode where extensions are disabled by default (at least in Google Chrome). I've edited my post to make things a bit clearer.

**Comment by mneunomne** [comment]
As mentioned above, it is not possible to have certain youtube channels "allowed" since each video url doesn't contain any information on the channel from that video, making it therefore not within the scope of our extension to do so automatically.

I'll be closing this issue.
