### ISSUE TITLE
Settings are unavaliable, some ads not "clicked" in Firefox 55.0.2

### ISSUE THREAD

**Issue by ghost** [dhowe/AdNauseam#1119]
### Describe the issue
Pressing "Settings" or "Ad Vault" button in popup window doesn't do anything. No ads on YouTube are being shown or "clicked". 

### One or more specific URLs where the issue occurs
Any of YouTube videos really. 

### Steps for anyone to reproduce the issue
1. Press AdNauseam button in firefox toolbar. 
2. Press "Settings" or "Ad Vault" button. 

For youtube videos, any of the youtube pages will have ads blocked but not "clicked"
### Your settings

OS Manjaro Linux x86_64 Kernel: 4.9.44-1-MANJARO 
Browser 	Firefox
Version 	55.0.2
AdNauseam	3.3.403
Extensions:
NoScript	5.0.9 (set to allow all on page during test)
Privacy Badger	2017.7.24
StyleRRR - Barebones Userstyle Injector	0.1.4

**Comment by greysonevins** [comment]
@ArcFutahito Are you talking about the video ads by chance?

**Comment by ArcFutahito** [comment]
@greysonevins any ads at all, but yes, video ads too. It's honestly not as much of a problem (I see it being a little bit finicky with just blocking but not clicking most of advertisements) as the fact that buttons in addon don't work.

**Comment by Klowner666** [comment]
I have the problem of the vault or the setting not doing anything when clicked as well. 

Going on the AdNauseam firefox toolbar and clicking "view ad vault" or "settings" does not do anything. 
To access the settings I need to go in firefox "addons" -> "extensions" -> "AdNauseam options" -> "Show Dashboard"
Only then do I have access to the settings. I tried to disable firefox popup prevention and firefox block dangerous content but I get the same results, it seems like it blocks the requests of accessing the vault or the settings from the toolbar add on.

**Comment by Klowner666** [comment]
Found a workaround not to the problem but if you want to at least have access to your options and vault, just copy paste these in your address bar: 
you can access your vault here:  chrome://adnauseam/content/vault.html
and your settings/dashboard here: chrome://adnauseam/content/dashboard.html

It seems that on some versions of firefox the links don't open (if you click on the supposed button that opens them), but when pasted directly in the URL bar they work fine.

**Comment by dhowe** [comment]
strange - any errors in the console (hit control/command-J to view) ?

**Comment by Klowner666** [comment]
On the Browser console after clicking view ad vault and nothing happening I get : 
" TypeError: browser is null[Learn More] vapi-background.js:987:1 "

And when I expand it I get: 
" vAPI.tabs.open chrome://adnauseam/content/js/vapi-background.js:987:1
	µBlock.openNewTab chrome://adnauseam/content/js/utils.js:262:5
	onMessage chrome://adnauseam/content/js/messaging.js:153:9
	vAPI.messaging.onMessage chrome://adnauseam/content/js/vapi-background.js:1764:13 "

**Comment by dhowe** [comment]
Can you re-test this using the most recent webextensions release (now [available on AMO](https://addons.mozilla.org/en-US/firefox/addon/adnauseam/)) ?

**Comment by Klowner666** [comment]
It works perfectly for me now, the previous AdNauseam extension had "Legacy" written by it in the firefox extensions, now it doesn't. 
I can access the vault and the options directly, all issues have been resolved. Thank you for your work.

**Comment by dhowe** [comment]
thank you for helping us test...
