### ISSUE TITLE
Not loading in Chromium

### ISSUE THREAD

**Issue by Ryu945** [dhowe/AdNauseam#1120]
### Describe the issue
It errors out when I load it in Chromium

{
  "manifest_version": 2,
  "name": "AdNauseam",
  "version": "3.3.404",
  "default_locale": "en",
  "description": "__MSG_extShortDesc__",
  "icons": {
    "16": "img/icon_16.png",
    "128": "img/icon_128.png"
  },
  "browser_action": {
    "default_icon": {
      "19": "img/browsericons/icon19.png",
      "38": "img/browsericons/icon38.png"
    },
    "default_title": "AdNauseam",
    "default_popup": "menu.html"
  },
  "author": "Daniel C. Howe",
  "background": {
    "page": "background.html"
  },
  "content_scripts": [{
    "matches": ["http://*/*", "https://*/*"],
    "js": ["js/vapi-client.js", "js/adn/textads.js", "js/adn/parser.js", "js/contentscript.js"],
    "run_at": "document_start",
    "all_frames": true
  }, {
    "matches": ["http://*/*", "https://*/*"],
    "js": ["js/scriptlets/subscriber.js"],
    "run_at": "document_idle",
    "all_frames": false
  }],
  "incognito": "split",
  "minimum_chrome_version": "22.0",
  "options_page": "dashboard.html",
  "options_ui": {
    "page": "options_ui.html"
  },
  "permissions": [
    "activeTab",
    "contextMenus",
    "privacy",
    "storage",
    "tabs",
    "unlimitedStorage",
    "webNavigation",
    "webRequest",
    "webRequestBlocking",
    "management",
    "http://*/*",
    "https://*/*",
    "downloads"
  ],
  "short_name": "AdNauseam",
  "storage": {
    "managed_schema": "managed_storage.json"
  }
} 

### Your settings

- OS/version: Windows 7
- Browser/version:  Chromium  49.0.2588.0 (64-bit)
- AdNauseam version: 3.3.404

**Comment by dhowe** [comment]
any error or other message?

**Comment by rjy7wb** [comment]
getting this error also

**Comment by dhowe** [comment]
Are you following [these instructions](https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission)?

**Comment by 2garyt** [comment]
Same problem.
yes following instructions
error message
Failed to load extension from: ~\xxxx\AdNauseam-master
Could not load background page 'background.html'.

**Comment by Ryu945** [comment]
It has been fixed for awhile.  I assume some update fixed it.
