### ISSUE TITLE
FAQ question

### ISSUE THREAD

**Issue by lol768** [dhowe/AdNauseam#1123]
FAQ states:

> AdNauseam 'clicks' Ads by issuing an HTTP request to the URL to which they lead. In current versions the is done via an XMLHttpRequest (or AJAX request) issued in a background process. 

My questions:

* Won't this send a `x-requested-by`?
* Presumably the fact it's in the background script means it can bypass the SOP?
* If the response is just discarded, surely the advertisers can see that a user agent failed to fetch any resources associated with the document after clicking?

**Comment by dhowe** [comment]
thanks for the excellent questions -- response inline below...

> Won't this send a x-requested-by?

no

> Presumably the fact it's in the background script means it can bypass the SOP?

yes

> If the response is just discarded, surely the advertisers can see that a user agent failed to fetch any resources associated with the document after clicking?

please see our [paper](http://ceur-ws.org/Vol-1873/IWPE17_paper_23.pdf) where we address this
