### ISSUE TITLE
Toolbar icon not optimised for high-DPI screens

### ISSUE THREAD

**Issue by danpalmer** [dhowe/AdNauseam#1124]
### Describe the issue

Many computers now have high-DPI screens, AdNauseam should take advantage of these where possible so that it blends in with the rest of the browser, rather than sticking out.

### One or more specific URLs where the issue occurs

N/A

### Screenshot in which the issue can be seen

Note: this image is not artificially zoomed, it is taken at the native 2x resolution of my machine.

<img alt="screenshot 2017-08-27 13 54 29" src="https://user-images.githubusercontent.com/202400/29750017-baeae8fa-8b2f-11e7-8944-a708a94bdcec.png">

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

Install in Firefox on a machine with a high-DPI screen.

### Your settings

- OS/version: macOS 10.13 Beta
- Browser/version: Firefox 54.01
- AdNauseam version: AdNauseam v3.3.403 uBlock Originv1.12.2 
- Other extensions you have installed: Lastpass.

**Comment by mushon** [comment]
reopening and reassigning as this doesn't close the issue until we pack the icons and test that it works.

**Comment by dhowe** [comment]
what does this require?

**Comment by mushon** [comment]
@dhowe, I'm not sure, maybe you need to set it via code, like here:
https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#iconURL

**Comment by cqx931** [comment]
On high-DPI screens, he icon size is correct for chrome browsers and Firefox webExt
![image](https://user-images.githubusercontent.com/3056154/30434895-659ce6cc-9936-11e7-8169-ec7e293b4059.png)

This is only an issue in current Firefox addon version
![image](https://user-images.githubusercontent.com/3056154/30435027-bbdec9ba-9936-11e7-946f-dfa70d03b592.png)
If we still want to fix that, I can update the css and image files in `platform/firefox`
https://github.com/dhowe/AdNauseam/blob/master/platform/firefox/css/legacy-toolbar-button.css#L1
https://github.com/dhowe/AdNauseam/tree/master/platform/firefox/img/browsericons
