### ISSUE TITLE
Third-party morals

### ISSUE THREAD

**Issue by Ivanca** [dhowe/AdNauseam#1126]
>@wongarsu: AdNauseam has a clear definition of "good" ad networks [1]: with default settings it allows ads that obey do-not-track headers, as tracked by the EFF.
Of course in theory they could become some kind of evil authoritarian censor board. But that would cause a lot of users to jump to the next best extension. It's not really a big threat

> @ivanca After installed this extension silently attacks networks, and you think people is gonna care enough to jump to the next best one... because you think they are constantly reading about the moral basis of the blacklisted ad networks? ...right? You are more delusional than expected and I hope ad networks start pouring money into permanently banning users of this extension from all major websites.

**Comment by nukeop** [comment]
All ad networks are immoral, so I disabled this whitelist. This way I'm avoiding giving the AdNauseam team any authority or control over my blocking. What a lifehack!

**Comment by Ivanca** [comment]
If you don't like a product you just don't go to their store to buy it (meaning, don't go to their website), you don't go to the their publishing agency and throw rocks at their windows just because you don't agree with their profiting methods; it's really simple.

But if you do start throwing rocks be aware that you gonna get some rocks thrown at you as well; because it counts at self-defense under most jurisdictions.

**Comment by nukeop** [comment]
Can't make an omelette without cracking a few eggs.

Toppling or at least hurting advertising giants is a worthy cause. Sabotaging everything they own and discouraging people from working for them is just one of many things we're obliged to do, if we value freedom. Especially given recent events.
