### ISSUE TITLE
Whitepaper is missing on about page.

### ISSUE THREAD

**Issue by EntranceJew** [dhowe/AdNauseam#1129]
### Describe the issue
The link to [TMN-Howe-Niss08-ch23.pdf](http://rednoise.org/~dhowe/pubs/TMN-Howe-Niss08-ch23.pdf) is broken.

### One or more specific URLs where the issue occurs
https://github.com/dhowe/AdNauseam/wiki/About-AdNauseum
http://rednoise.org/~dhowe/pubs/TMN-Howe-Niss08-ch23.pdf

### Screenshot in which the issue can be seen
![here you go](https://i.imgur.com/uSLLKS6.png)

### Steps for anyone to reproduce the issue
1) visit [about wiki page](https://github.com/dhowe/AdNauseam/wiki/About-AdNauseum)
2) click on the [whitepaper link](http://rednoise.org/~dhowe/pubs/TMN-Howe-Niss08-ch23.pdf)

### Your settings

- OS/version: N/A
- Browser/version: N/A
- AdNauseam version: N/A
- Other extensions you have installed: N/A

**Comment by dhowe** [comment]
thanks @EntranceJew
