### ISSUE TITLE
Compatibility with Iridium Browser?

### ISSUE THREAD

**Issue by HairyMilkshakes** [dhowe/AdNauseam#1132]
### Describe the issue
Hello, I've been using AdNauseum for about 30 minutes now but the counter is still at 0. Is this supposed to be happening? All of the general settings are on regarding ad blocking and clicking.

I am using the latest Google Chrome release as well as the latest Iridium Browser release on 4/27.

**Comment by greysonevins** [comment]
@HairyMilkshakes are you using the suggested setup of ADN? I was able to set up Iridium and collect ads on v58.0 and v3.3.404 of ADN.

When you say the latest release, where are you finding the release? ADN is not currently supported in the Chrome extension store and it looks like--I may be wrong--that iridium uses the chrome extension store as well. 

<img width="958" alt="screen shot 2017-08-31 at 11 52 18 am" src="https://user-images.githubusercontent.com/11656811/29932722-1160354e-8e43-11e7-872b-11ce2ead7b71.png">
