### ISSUE TITLE
Some ads not blocked on 4archive.org

### ISSUE THREAD

**Issue by ZedPea** [dhowe/AdNauseam#1133]
### Describe the issue
On 4archive.org, an ad appears which is successfully blocked on ublock origin. It does block some ads on this page. Also, when clicking anywhere on the page, occasionally pop ups will be opened, some of which are closed automatically, unsure if by the extension or by firefox.

I reinstalled ublock to check that it blocked this ad, so they shouldn't have been interfering. The installed ublock was from the firefox store, and is version 1.13.10.

### One or more specific URLs where the issue occurs
https://4archive.org/board/r9k/thread/27415355

### Screenshot in which the issue can be seen
https://imgur.com/a/3iLWJ (Bottom right corner)

### Steps for anyone to reproduce the issue
Open linked page
Wait a few seconds (ad disappears and reappears in bottom right corner)

### Your settings

- OS/version: Arch Linux 4.12.8-2
- Browser/version: Firefox 55.0.3 (64-bit)
- AdNauseam version: AdNauseam v3.3.403, uBlock Origin v1.12.2 
- Other extensions you have installed: Classic Theme Restorer, Dark Youtube Theme, Duplicate In Tab Context Menu, Greasemonkey, HTTPS Everywhere, Undo Closed Tabs Button

**Comment by greysonevins** [comment]
@ZedPea I can't duplicate the visible ad you showed, but I found the culprit for the injected spam links.

**Comment by ZedPea** [comment]
Ok, I'm not sure if it's relevant, but on my linux firefox I don't get any ads shown in the ad-vault, despite it appearing to block nearly all ads, wheras on my windows firefox I've got a few stored. I imagine I have an older version of firefox on windows.

**Comment by greysonevins** [comment]
@ZedPea we updated uAssets. Could you verify the changes work for you?

**Comment by ZedPea** [comment]
@greysonevins 
It appears to have worked, the ad in the bottom right corner no longer appears, and the pop up links appear to have gone. 

The page also seems to take an age to load, and in that time the pop up links can be clicked by clicking on the page, but I imagine there's nothing that can be done about that.

Thanks!

**Comment by greysonevins** [comment]
@ZedPea the load time is fine on my end. Not sure what that would be.
