### ISSUE TITLE
webExt - can't open vault or settings page from menu 

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1137]
master branch, Firefox web extension

To reproduce:
1. click on adnauseam icon to open menu
2. click on 'settings' or 'view ad vault', the popup menu closes itself, but no page is opened.

**Comment by cqx931** [comment]
Went through the debugger, but I don't see any performance difference between AdNauseam and current uBlock. The warning messages I got for AdNauseam also happens for uBlock.

**Comment by dhowe** [comment]
can you include a screenshot?

**Comment by cqx931** [comment]
I have added some steps to reproduce the issues above

**Comment by dhowe** [comment]
This is what I see after clicking 'Lets Go', then the toolbar icon ?

![image](https://user-images.githubusercontent.com/737638/29903530-568ba0b6-8dd2-11e7-85bc-080f8c586b3d.png)

**Comment by dhowe** [comment]
Fixed

**Comment by cqx931** [comment]
The issue you mentioned in the screenshot is fixed, but this is not what I'm talking about in this ticket.

**Comment by dhowe** [comment]
cannot recreate with  merged1.13.0 on Firefox 56.0b6

**Comment by greysonevins** [comment]
I can't reproduce the issue either @cqx931

**Comment by dhowe** [comment]
closing for now, will re-open if occurs again
