### ISSUE TITLE
AdNauseam fails to block ads on convert2mp3.net

### ISSUE THREAD

**Issue by nov3mb3r** [dhowe/AdNauseam#1143]
### Describe the issue
After disabling uBlock origin, AdNauseam fails to block adds. when restarting browser and removing uBlock origin, problem persists. When i installed and enabled again adds removed but AdNauseam still fails to show any add it clicked

### One or more specific URLs where the issue occurs
http://convert2mp3.net/en/index.php?p=complete&id=youtube_RAoKcM54Q1Y&key=S5PJ3GLA49YO

### Screenshot in which the issue can be seen
![screenshot_20170831_204040](https://user-images.githubusercontent.com/10418973/29937300-c458c144-8e8d-11e7-8392-2e7d2e9b8e80.png)

### Steps for anyone to reproduce the issue
I installed the plugin, chose the options and that's it.I then disabled and completely removed uBlock origin and restarted the browser

### Your settings

- OS/version: openSUSE Leap 42.3
- Browser/version: Firefox 52.3.0
- AdNauseam version: 3.3.403
- Other extensions you have installed:
https everywhere, privacy badger, tampermonkey

**Comment by dhowe** [comment]
Can you try again with Privacy Badger disabled ?

**Comment by nmantas** [comment]
I tried again but still adds are not blocked
![screenshot_20170902_183016](https://user-images.githubusercontent.com/10418973/29996761-16f97a4e-900d-11e7-97a2-f0332d32b918.png)

**Comment by dhowe** [comment]
Can you give one more try with the most [current version](https://addons.mozilla.org/en-US/firefox/addon/adnauseam/) ? thanks

**Comment by greysonevins** [comment]
@nmantas I had the same issue. @dhowe I created a PR to fix this issue.
