### ISSUE TITLE
[WebExt] merged1.13.0 - the vault opens new tab instead of refresh the current one

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1144]
To reproduce:
1.go to any site with ads
2.open vault
3.Clear all ads
4.A new tab is opened and the ads are gone, while the current tab remains unchanged.

Or

1.open vault
2.Import new ads from file
3.A new tab window is opened and the ads are loaded, the current tab remains unchanged.

Note: I can't reproduce this consistently, sometimes it works, sometimes not.

**Comment by dhowe** [comment]
After clear-ads in the vault, the vault page should either close or show zero ads

**Comment by greysonevins** [comment]
@cqx931 I cannot reproduce with 1.13.8

**Comment by dhowe** [comment]
Cannot recreate
