### ISSUE TITLE
Merged1.13.0 - All ad visits failed

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1146]
ad visits worked for merged1.12.4, this issue is for all browsers.
![image](https://user-images.githubusercontent.com/3056154/29938094-9b72b998-8e55-11e7-88c9-467c7cb96848.png)

![image](https://user-images.githubusercontent.com/3056154/29938246-2500c362-8e56-11e7-838c-62b2cea577e2.png)

**Comment by greysonevins** [comment]
Same on Chrome and Opera. Images collected, but don't show up on menu too..
<img width="364" alt="screen shot 2017-08-31 at 4 24 39 pm" src="https://user-images.githubusercontent.com/11656811/29943834-0a4d7930-8e69-11e7-8b6e-eed146125d8d.png">

**Comment by dhowe** [comment]
I can't recreate this on Chromium with merged1.13.0

![screen shot 2017-09-01 at 2 55 50 pm](https://user-images.githubusercontent.com/737638/29958527-26bf4ef6-8ec1-11e7-88eb-9e02ea985e07.png)

**Comment by cqx931** [comment]
not with me...
![image](https://user-images.githubusercontent.com/3056154/29968538-126cbbfe-8eea-11e7-9055-9b759dd6a4cb.png)

**Comment by cqx931** [comment]
fixed in https://github.com/cqx931/AdNauseam/tree/newMerged1.13.0, close
