### ISSUE TITLE
[WebExt] No notification generated after disabling a core function

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1147]
Already happens in master branch
![image](https://user-images.githubusercontent.com/3056154/29939474-fb643bde-8e59-11e7-8a88-0cc88d78bcdb.png)

**Comment by cqx931** [comment]
Could you please check this one? @dhowe

**Comment by dhowe** [comment]
I believe this is caused by passing notifications back and forth with functions as properties, which is disallowed according to the [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)

**Comment by dhowe** [comment]
fixed with 4316fe0ed
