### ISSUE TITLE
[WebExt] Content from 3rd party filters disappears

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1149]
happens in master branch

To reproduce:
1.Open settings page
2.Disable any main function: Hide/Block/Click
3.Go to 3p-filters
4.The content is gone, refresh doesn't help

The content for all 3rd party filters are back again if the function is enabled again.

![image](https://user-images.githubusercontent.com/3056154/29940971-e3045a9c-8e5e-11e7-836b-99a8f1c64963.png)

**Comment by dhowe** [comment]
please recreate

**Comment by cqx931** [comment]
This should be fixed now in master branch.
