### ISSUE TITLE
[WebExt] Content missing from uBlock popup (or incorrectly sized)

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1150]
All browsers

![image](https://user-images.githubusercontent.com/3056154/29942906-6c1bca3a-8e65-11e7-8489-d02f98ccd977.png)

It looks like this in uBlock

![image](https://user-images.githubusercontent.com/3056154/29942969-a939799e-8e65-11e7-995e-7ff1a33f5f30.png)

**Comment by greysonevins** [comment]
same for Opera and Chrome @cqx931

**Comment by greysonevins** [comment]
It looks like the new uBlock v1.13.8 has a different layout. I don't see the element picker either on it.
<img width="162" alt="screen shot 2017-08-31 at 4 13 50 pm" src="https://user-images.githubusercontent.com/11656811/29943414-6591e4cc-8e67-11e7-8589-0a6b11f10b01.png">

**Comment by cqx931** [comment]
This is how 1.13.8 looks like with me, I think you need to be on a valid web page to see the picker and zapper:
![image](https://user-images.githubusercontent.com/3056154/29943571-f10bf6f0-8e67-11e7-9db8-e7ca5b4c24f6.png)

**Comment by greysonevins** [comment]
@cqx931 realized that right after I posted.

**Comment by cqx931** [comment]
fixed in https://github.com/cqx931/AdNauseam/tree/newMerged1.13.0
![image](https://user-images.githubusercontent.com/3056154/29991212-5e5a5f1e-8f51-11e7-989c-95d4ce7970d4.png)

**Comment by greysonevins** [comment]
same for new merge issues/1138
<img width="134" alt="screen shot 2017-09-09 at 3 36 56 pm" src="https://user-images.githubusercontent.com/11656811/30243315-bdca005c-9574-11e7-99c5-fbf91edecfb7.png">

**Comment by dhowe** [comment]
please verify

**Comment by greysonevins** [comment]
@dhowe verified

**Comment by greysonevins** [comment]
However, for WebExt I get this
<img width="801" alt="screen shot 2017-09-10 at 5 45 07 pm" src="https://user-images.githubusercontent.com/11656811/30253276-e7363f60-964f-11e7-8643-58be77092523.png">

**Comment by dhowe** [comment]
@cqx931 please verify

**Comment by cqx931** [comment]
I can't reproduce the bug above in webExt

**Comment by cqx931** [comment]
verified, close

**Comment by dhowe** [comment]
how did this get fixed (I don't see a commit) ?

**Comment by dhowe** [comment]
Ok, now pls verify and close

**Comment by cqx931** [comment]
verified and close. (Accidentally closed the wrong ticket before)
