### ISSUE TITLE
[WebExt] newMerged1.13.0 ads collected from DNT sites don't get displayed

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1151]
Example:https://duckduckgo.com/?q=credit+cards&t=h_&ia=web
In Menu:
In DNT sites, the badge number is correct, but the data doesn't end up in menu
![image](https://user-images.githubusercontent.com/3056154/29951171-d22b036c-8e8e-11e7-9dea-f56f00038b9a.png)
In Ad vault:
After collected any ad from DNT sites, the vault keeps showing the loading animation and no ad is displayed.

**Comment by dhowe** [comment]
fixed

![image](https://user-images.githubusercontent.com/737638/30239906-d9408d10-9533-11e7-80e0-435813df5fe9.png)
