### ISSUE TITLE
Merged1.13.0 - network error when updating the lists

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1152]
All browsers, could be related to https://github.com/dhowe/AdNauseam/issues/1146
![image](https://user-images.githubusercontent.com/3056154/29951336-09b9cf2e-8e90-11e7-9372-aee80873caa8.png)

All requests are blocked by AdNauseam itself
![image](https://user-images.githubusercontent.com/3056154/29951618-dcaa7658-8e91-11e7-85fb-cfa8a0704864.png)

**Comment by cqx931** [comment]
onBeforeBehindTheSceneRequest() in traffic.js

**Comment by dhowe** [comment]
what rule is causing this block ?

**Comment by cqx931** [comment]
fixed in https://github.com/cqx931/AdNauseam/tree/newMerged1.13.0, close
