### ISSUE TITLE
Broken EFF image on press page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1153]
https://adnauseam.io/press.html

![screen shot 2017-09-01 at 1 54 07 pm](https://user-images.githubusercontent.com/737638/29956945-90443a2a-8eb8-11e7-8ef2-cdf29ad25576.png)

**Comment by greysonevins** [comment]
@dhowe added the missing file to both branches

**Comment by dhowe** [comment]
also mashable:
![image](https://user-images.githubusercontent.com/737638/29973761-a2f66058-8efe-11e7-87cf-95057442234e.png)
