### ISSUE TITLE
Ad Vault view always zooms to the center of the diagram

### ISSUE THREAD

**Issue by 4of92000** [dhowe/AdNauseam#1158]
### Describe the issue

While browsing the Ad Vault, the zoom always zooms to the center of the diagram, not the center of the screen or the cursor, so if (for example) the view is centered to the left of the diagram's center, the camera pans right instead of zooming straight in.

This isn't that big a deal, but it is somewhat annoying.

### Steps for anyone to reproduce the issue

0. Open the Ad Vault.
0. Pan the view of the Vault in any direction. (The farther the distance panned, the easier to see.)
0. Zoom in using the buttons or the scroll wheel.

### Your settings

- OS/version: Debian 9.0
- Browser/version: Chromium 59.0.3071.86 (Developer Build)
- AdNauseam version: v3.3.404
- Other extensions you have installed: Stylish, Minimalist Markdown Editor, Tampermonkey

**Comment by greysonevins** [comment]
@4of92000 I will look into this. Sorry for the delay.

**Comment by mneunomne** [comment]
This has been implemented since some time in the vault. Closing
