### ISSUE TITLE
Ads visible on hollaforums.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1159]
hidden in ublock
http://hollaforums.com/thread/2043638/activism/if-i-was-google-i-would-actually-invest-in.html

![screen shot 2017-09-04 at 10 58 30 am](https://user-images.githubusercontent.com/737638/30010104-77e5472c-90fb-11e7-82e6-a29fb4967f63.png)

**Comment by greysonevins** [comment]
@dhowe can't duplicate

**Comment by cqx931** [comment]
I can't duplicate this as well
