### ISSUE TITLE
[WebExt] Cookies are not blocked

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1160]
Cookies are blocked in chrome, but not in Firefox, both for webExt and older version.
The screenshot is from webExt.
No [Cookies] logging messages for older version
![image](https://user-images.githubusercontent.com/3056154/30032930-505a3850-9166-11e7-8413-1c6b73a1890a.png)

For the following two cases:
http://lab-lamp.scm.cityu.edu.hk/adntest/incomingCookies.html
http://lab-lamp.scm.cityu.edu.hk/adntest/cookie-setting-ad.html

**Comment by dhowe** [comment]
I can't recreate this with either link:

<img width="1185" alt="screen shot 2017-09-14 at 4 20 20 pm" src="https://user-images.githubusercontent.com/737638/30419341-ff7de4ea-9903-11e7-99ad-2d7fe6331813.png">

**Comment by cqx931** [comment]
I can still see cookies in the latest master branch
![image](https://user-images.githubusercontent.com/3056154/30435762-937f59d8-9938-11e7-85f9-a587d9201720.png)

**Comment by cqx931** [comment]
http://lab-lamp.scm.cityu.edu.hk/adntest/cookie-setting-ad.html
This one seems to be fixed, but for incoming cookies I still see the same result as the screenshot above.(Cookies detected, but still ended up in the browser)

**Comment by dhowe** [comment]
I still can't recreate this on WebExt (see below)... What are your cookie settings?

And what are the exact steps you do to test ? 

![image](https://user-images.githubusercontent.com/737638/30441424-6595cdea-9947-11e7-8fad-900101c0ac91.png)

**Comment by cqx931** [comment]
the cookie above is not related to the test here, close
