### ISSUE TITLE
Settings will not open correctly if clicked while firstrun page is open

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1162]
To recreate:
1. open a new version to see the firstrun page
2. before clicking anything, open menu and click 'settings'

**Comment by cqx931** [comment]
I got empty settings page if any of the major functions is disabled.(Also applies to the case :before clicking anything on firstrun page)
![image](https://user-images.githubusercontent.com/3056154/30065004-8aeaf87c-9221-11e7-9781-701a2cef1160.png)

**Comment by dhowe** [comment]
Yes, I see the same.

**Comment by dhowe** [comment]
fixed with 4316fe0ed
