### ISSUE TITLE
Chrome silently uninstalls AdNauseam on shutdown

### ISSUE THREAD

**Issue by bhartvigsen** [dhowe/AdNauseam#1164]
### Describe the issue
After installing the current release of AdNauseam under chrome://extensions and then exiting Chrome, the extension is silently removed completely.

### Steps for anyone to reproduce the issue
Use Chrome
Install AdNauseam
Exit
Restart Chrome. AdNauseam is gone

### Your settings

- OSX 10.12.3
- Browser/version: Chrome Version 60.0.3112.113 (Official Build) (64-bit)
- AdNauseam version: Latest available release: adnauseam-3.3.403.chromium.zip
- Other extensions you have installed: Google Docs, uBlock Origin (disabled)

**Comment by dhowe** [comment]
Are you using 'developer mode' ?

**Comment by bhartvigsen** [comment]
Is that in reference to the Chrome web dev tools? No, otherwise also no.

**Comment by dhowe** [comment]
Because Google has blocked AdNauseam on Chrome, you need to follow these instructions: https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission

**Comment by bhartvigsen** [comment]
Oops, helps if you read the instructions!

**Comment by bhartvigsen** [comment]
Reopening this. The plugin has now vanished from Chrome again. I clicked the icon and it showed a 'missing content' placeholder on the dropdown and so I restarted Chrome. AdNauseam is totally removed from Chrome now and the developer checkbox in chrome://extensions has been checked this entire time. There's definitely something in Chrome that is removing this plugin automatically. Is nobody else having this issue?

**Comment by dhowe** [comment]
Question: did you delete the downloaded AdNauseam folder?

**Comment by bhartvigsen** [comment]
Yes I did, I installed it from my downloads and then cleared the folder, per habit.

I think this is the cause, closing again, thanks. Might be a good idea to add some verbiage to the instructions telling people they need to retain the folder.

**Comment by dhowe** [comment]
agreed
@greyson, please update the instructions to say that you cannot delete the downloaded extension folder

**Comment by greysonevins** [comment]
@dhowe see above commit

**Comment by dhowe** [comment]
@greysonevins be careful to pull the current version first
