### ISSUE TITLE
Custom rule not applied

### ISSUE THREAD

**Issue by obama** [dhowe/AdNauseam#1166]
### Describe the issue
i added a static .jpg image as a rule because i dont want to see it. its removed after adding the rule.
upon reload of the page its shown again.
in the custom rules section i have already 10x this rule and it doesnt work.

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version: WIndows 10
- Browser/version: Chrome 60
- AdNauseam version: AdNauseam v3.3.403 uBlock Originv1.12.2
- Other extensions you have installed:

**Comment by dhowe** [comment]
@greysonevins pls recreate this...

**Comment by greysonevins** [comment]
@obama hi can you give more context for this? Is there a website and a jpg you can link me to?

I tested this out by going to imgur and it worked and blocking one jpg. Also, having uBlock and AdNauseam working at the same time can mess up ADN.

For example, I tried to create a block on uBlock and when I refreshed it with ADN and uBlock enabled the block rule went away.

Make sure you save your block rule to your "My Filters settings" here:

<img width="539" alt="screen shot 2017-09-21 at 5 57 11 pm" src="https://user-images.githubusercontent.com/11656811/30720665-787ff048-9ef6-11e7-8baf-925a6b7bdbd7.png">
<img width="539" alt="screen shot 2017-09-21 at 5 57 11 pm" src="https://user-images.githubusercontent.com/11656811/30720670-7b86e51c-9ef6-11e7-896c-8b25077fe304.png">

**Comment by obama** [comment]
ok now i found the reason:
the clicky-pointy rule creator adds $image after the rule. if i remove $image than it works.
