### ISSUE TITLE
usbank.com "system" unavailable

### ISSUE THREAD

**Issue by ZenMasta** [dhowe/AdNauseam#1167]
### Describe the issue
Logging in presents an error at usbank.

### One or more specific URLs where the issue occurs
www.usbank.com

### Screenshot in which the issue can be seen
https://imgur.com/a/3J7Ua

### Steps for anyone to reproduce the issue
I tried logging in with an account that I had previously logged in with prior to installing.
Since this pc was "recognized" it didn't ask for the security question. When I login, it appears successful, in that there is no login error. But it's mostly a white page that says "The system is currently unavailable".

If I login to a secondary account (first time on this pc) it will ask the security question. And after typing the correct answer it will say "Sorry our system is unavailable, please try again later".

This doesn't happen if I use incognito mode since addons are disabled. And I have logged into both accounts with a different browser immediately after so it's definitely not a "system outage" as their message indicates. 

Disabling on "this page" is ineffective.

Prior to installing AdNauseam, I used to use uBlock Origin and never had any issues at this website. 

### Your settings

- OS: Windwos 10
- Browser: Vivaldi 1.10.867.38
- AdNauseam version: 3.3.403
- Other extensions you have installed: Fullpage Screen Capture

**Comment by dhowe** [comment]
This will be difficult to test/recreate without an account. Can you try disabling the adnauseam.txt list and see if the problem still happens (@greyson, perhaps you can help with this) ?

**Comment by ZenMasta** [comment]
Long story short, I attempted to clear private data. Deleted everything except history and saved passwords. This seems to have solve the problem. But what's odd is it didn't appear to work for me the first time I deleted just cache by itself or cookies by themselves.

Long version...
The only other extension I am using is full page screen capture. 

I tried some things.
Create new windows user and installed adnauseam.
I was able to login just fine.

Went back to original user. Disabled every extension. Still could not login (same errors as origionally reported).

I enabled AdNauseam for incognito. I was able to login just fine. 

Somehow I feel installing this extension caused issue with my cache or something this website. I haven't installed any other win32 apps within any reasonable time prior or after installing this extension. I never experienced this problem before installing AdNauseam. And I was using ublock origin previously.

**Comment by ZenMasta** [comment]
This continues to happen to me on this website, about every few days. And while clearing cache will fix it. It would be nice to have a more permanent solution. Especially because unlike firefox, chrome doesn't have a way to delete cache/cookies for a single website.

**Comment by dhowe** [comment]
@ZenMasta there a few things we might try: the first is to start up AdNauseam (perhaps a fresh install),  go to Settings and check 'Activate debugging mode'. Then you can open the the chrome://extensions URL in the browser and click on 'background.html' under AdNauseam, which will open the developer tools, in which our debugging messages will be shown in the 'console' window. 

Then the next time the problem happens, you can copy the log data in that console, and either post it here, or send it to adnauseam_at_rednoise_org, where we can inspect it to see whats going on

**Comment by greysonevins** [comment]
@dhowe Unfortunately, I don't have a usbank account. @ZenMasta The other question would be if the fullpage screen capture may cause the issue as well.

**Comment by ZenMasta** [comment]
I've been using FPSC extension for over a year, along with ublock origin previously.  But the next time this issue occurs, I'll certainly try removing it to see if that has any affect.   I had not experienced this issue at all until I installed AdNauseam.

**Comment by dhowe** [comment]
I don't think FPSC has anything to do with it. But it would be great, when it happens again, to be able to see the logs, as described above...

**Comment by mneunomne** [comment]
The website at hand changed interface a lot since this issue was created. Closing for now.
