### ISSUE TITLE
[WebExt] Storage-used not shown in Settings

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1171]
![screen shot 2017-09-09 at 6 14 09 pm](https://user-images.githubusercontent.com/737638/30239241-21d2c2fe-9526-11e7-8e87-0e4cfbe2d096.png)

**Comment by cqx931** [comment]
This also doesn't work with uBlock in webExt.
Firefox doesn't support this 'StorageArea.getBytesInUse()' yet:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/StorageArea/getBytesInUse

**Comment by dhowe** [comment]
ok, good for now then
