### ISSUE TITLE
[Merge 1.13.4] Firstrun: DNT exception is not applied to settings

### ISSUE THREAD

**Issue by greysonevins** [dhowe/AdNauseam#1173]
If you unclick the make exception rule on the first run page. It doesn't seem to apply in the settings and still creates the exception in the settings. 

#1138

<img width="474" alt="screen shot 2017-09-09 at 3 24 13 pm" src="https://user-images.githubusercontent.com/11656811/30243215-fb5668b8-9572-11e7-9d07-e4cf233256a4.png">
<img width="447" alt="screen shot 2017-09-09 at 3 24 19 pm" src="https://user-images.githubusercontent.com/11656811/30243216-fb56e02c-9572-11e7-9226-651d155cedb9.png">

**Comment by dhowe** [comment]
fixed in 86c2ea4
please verify

**Comment by greysonevins** [comment]
@dhowe That worked!
