### ISSUE TITLE
Settings button overlaps text in menu for DNT sites 

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1178]
branch: merge1.13.5
![image](https://user-images.githubusercontent.com/737638/30248218-a23334ee-95f1-11e7-895f-3d58eb2c72b4.png)

**Comment by mushon** [comment]
I see this happening only on hover. Is this really a bug?
![ng6705gbcf](https://user-images.githubusercontent.com/27123/30419353-b6bbe58c-993e-11e7-9c08-7f2cd40ebada.gif)

**Comment by dhowe** [comment]
Correct -- your call...
