### ISSUE TITLE
adnausium download for chrome is gone

### ISSUE THREAD

**Issue by cerberii** [dhowe/AdNauseam#1179]
### Describe the issue
click releases, download for adnausium for chrome is gone

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version:
- Browser/version:
- AdNauseam version:
- Other extensions you have installed:

**Comment by cqx931** [comment]
Hi cerberii,

The latest release for chrome should be the first link under "Downloads":
![image](https://user-images.githubusercontent.com/3056154/30251787-a6bec440-9634-11e7-8b46-81189099749c.png)


And please follow the instructions here to install AdNauseam on Chrome
https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission
