### ISSUE TITLE
AdNauseam FAQ needed for AAK

### ISSUE THREAD

**Issue by cerberii** [dhowe/AdNauseam#1180]
not listed or no writeups for how to work with Anti Adblock Killer (AAK)

Learn to use AAK in adnaseum

**Comment by cqx931** [comment]
AdNauseam should work with AAK, you can do that simply by clicking "Subscribe" on their website:
![image](https://user-images.githubusercontent.com/3056154/30251857-2e423fd6-9636-11e7-995b-79da5eaa11b2.png)

And it should end up in your custom 3p-filters automatically.
![image](https://user-images.githubusercontent.com/3056154/30251874-8a4c3642-9636-11e7-9aa3-0501b8b9cd4e.png)

**Comment by dhowe** [comment]
@greysonevins please add to FAQ
