### ISSUE TITLE
[WebExt] Cannot programmatically open about:addons in Firefox

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1184]
![image](https://user-images.githubusercontent.com/737638/30282055-26098ec6-96e2-11e7-9188-572fbc04d612.png)

See: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create

Temp workaround: remove 'disable' button from notification on FF only

**Comment by cqx931** [comment]
Can we still keep the 'disable' button in Firefox old addon version?

**Comment by dhowe** [comment]
Any reason to continue supporting the old version of FF ?
