### ISSUE TITLE
Filter for PInterest nag screen

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1186]
for example: https://www.pinterest.com/pin/89368373829164874/

![image](https://user-images.githubusercontent.com/737638/30412436-83161a26-98e5-11e7-91a0-0e0eb3876d69.png)

**Comment by dhowe** [comment]
please check and close if ok (go to pinterest w'out logging in, then scroll down the page)

**Comment by cqx931** [comment]
The issue with the basic page is fixed. uBlock also shows the login overlay for subpage, so it should be ok.
