### ISSUE TITLE
Chrome Installation Error: "Default locale was specified, but _locales subtree is missing."

### ISSUE THREAD

**Issue by ForcedtoPickAUsername** [dhowe/AdNauseam#1191]
Trying to install this on Chrome but I cannot for the reason listed above.
"Default locale was specified, but _locales subtree is missing."

**Comment by dhowe** [comment]
Version of AdNauseam and Chrome?

**Comment by ForcedtoPickAUsername** [comment]
Version 61.0.3163.91 (Official Build) (64-bit) - Chrome
The Version of AdNauseam I'm downloading is the one that first appears on on the download page.

**Comment by dhowe** [comment]
I cannot recreate --  what locale are you using?

**Comment by ForcedtoPickAUsername** [comment]
It gives this big box of text when it fails to load https://pastebin.com/KWvg4N1Z Hopefully there it should contain what causes the problem for me. And if my understanding of Locale is correct, then it should be English.

**Comment by dhowe** [comment]
Can you retry this with the current version of AdNauseam (v3.4.103) ?

**Comment by ForcedtoPickAUsername** [comment]
Unfortunately I'm having the same problem. https://pastebin.com/eW3q1DgM

**Comment by dhowe** [comment]
I'd like to see the default locale for your computer and for your current user. For OS X you can get this with the following two terminal commands:

  $ defaults read -g AppleLanguages
  $ osascript -e 'user locale of (get system info)'

On my system, I get "en" and "en_HK" ...

**Comment by ForcedtoPickAUsername** [comment]
Okay, so I just decided to install it on Firefox rather then continuing to make it work on Chrome.
