### ISSUE TITLE
'Delete this ad' causes date-slider to reset

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1192]
### Steps for anyone to reproduce the issue
1. Open the vault with more than 300 ads
1. Slide the date slider to the left to show more than 300 ads
1. Right-click and select 'delete this ad'
1. Notice that the date-slider has reset

- OS/version: OS X
- Browser/version: Chrome
- AdNauseam version: v3.4.100

**Comment by cqx931** [comment]
I can't reproduce the exact same issue, but the counter is not correct after I delete one ad
(instead of "301 SHOWING" it should be "299 SHOWING" )
![image](https://user-images.githubusercontent.com/3056154/30514607-a9330676-9ae6-11e7-85ec-0929456bc655.png)

**Comment by cqx931** [comment]
The slider is recreated after 'delete this ad'. A proper solution would be to recreate the slider but trying to keep the current position. 
https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/vault.js#L1241

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/AdNauseam/pull/1278/commits/dbd4167b2406a63812d91f6b60ec62a1aec5e18b
