### ISSUE TITLE
[WebExt] Menu should show disabled on Firefox "New Tab" pages, icon should be gray

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1196]
To reproduce:
1.Open a new tab in Firefox, open the menu
2. The icon color is still purple and the "resume" button should be disabled in this case.

![image](https://user-images.githubusercontent.com/3056154/30513285-d06d28b0-9ace-11e7-8429-572363fd0d76.png)

**Comment by dhowe** [comment]
I've fixed the first part of this (buttons are now disabled), but its not clear at moment how to consistently call a handler for new tabs... 

Creating a new issue for it
