### ISSUE TITLE
[WebExt] Menu icon should be gray when on 'new-tab' page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1199]
To reproduce:
1. Open a new tab in Firefox, open the menu
2. The icon color is still purple but should be gray

![image](https://user-images.githubusercontent.com/3056154/30513285-d06d28b0-9ace-11e7-8429-572363fd0d76.png)

**Comment by cqx931** [comment]
This seems to be fixed in Firefox 58.0b7
