### ISSUE TITLE
Visible ads on wired.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1202]
https://www.wired.com/story/google-new-america-open-markets/amp
v3.4 / chromium

![image](https://user-images.githubusercontent.com/737638/30517883-ebd2defc-9b9f-11e7-9666-9f4c3ced03d1.png)

**Comment by dhowe** [comment]
We are also not collecting ads on normal wired.com pages: https://www.wired.com/story/google-new-america-open-markets

![screen shot 2017-09-18 at 3 12 10 pm](https://user-images.githubusercontent.com/737638/30532062-b6449222-9c84-11e7-8699-4749ede00e6e.png)

**Comment by thomasklash** [comment]
It's working here, `3.4.103` 
![image](https://user-images.githubusercontent.com/14216632/30543554-ed5be39a-9cc6-11e7-96b7-e405d3606ec9.png)
![image](https://user-images.githubusercontent.com/14216632/30543563-f2ecc144-9cc6-11e7-81d2-2e6542b04584.png)

**Comment by dhowe** [comment]
@greysonevins please recheck this with current release

**Comment by greysonevins** [comment]
@dhowe confirmed
