### ISSUE TITLE
Can't access AdVault, or Settings from AdNauseam toolbar icon.

### ISSUE THREAD

**Issue by Starasp** [dhowe/AdNauseam#1203]
### Describe the issue
When I click on the AdNauseam toolbar icon I get the popup but all i can do is disable the addon, when I try to access AdVault or Settings the window closes and nothing happens.

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version: Win 7 Ultimate SP 1
- Browser/version: Firefox 55.0.3 32-bit
- AdNauseam version: 3.3.403
- Other extensions you have installed: TrackMeNot, Edit Cookies

**Comment by greysonevins** [comment]
@Starasp so I set it up with your same settings but without Edit Cookies and it worked but then by adding Edit Cookies, ADN was not working like you said. I'm not sure why necessarily just yet @dhowe @cqx931 any thoughts?

**Comment by greysonevins** [comment]
@Starasp after a second attempt I just updated the FF version of ADN to the latest v3.4.103 and it works now. Can you update yours and see if it works for you?

**Comment by Starasp** [comment]
@greysonevins works fine now, thank you!
