### ISSUE TITLE
Duplicate "Block element" in context menu in Firefox 55

### ISSUE THREAD

**Issue by adambowles** [dhowe/AdNauseam#1207]
### Describe the issue
"Block element" appears twice

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/10128574/30739088-1e9ac98e-9f84-11e7-8346-d8d18804238a.png)

### Your settings

- OS/version: macOS 10.12
- Browser/version: Firefox 55
- AdNauseam version: 1.13.8
- Other extensions you have installed:
![image](https://user-images.githubusercontent.com/10128574/30739141-47fe92f6-9f84-11e7-8529-bd9af8eb1ab9.png)

**Comment by dhowe** [comment]
Interesting
@greysonevins, pls see if you can recreate this.

Note: Ghostery and AdNauseam will likely compete, causing neither to work correctly -- better to use one or the other

**Comment by cqx931** [comment]
I can't reproduce this with the settings above
