### ISSUE TITLE
Element Blocker creates incorrect rules

### ISSUE THREAD

**Issue by obama** [dhowe/AdNauseam#1208]
when creating a custom rule with the clicker thing for an image it adds "$image" to the rule, which renders it not working. removing "$image" makes the rule work though

**Comment by dhowe** [comment]
see #1166

**Comment by obama** [comment]
in ublock origin only it works even with the $image suffix

**Comment by dhowe** [comment]
so ublock does add the $image suffix, but the rule still works, is that correct?

**Comment by obama** [comment]
yes

**Comment by dhowe** [comment]
please include the specific rule and the page you are testing it on here...

**Comment by obama** [comment]
hmm odd now it works also with $image..
