### ISSUE TITLE
Mechanism for automatic update in chrome

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1209]
Any want to take this on or have any ideas about how it could best be done?

(for users who have installed the addon manually, and thus don't get updates)

**Comment by MrDemocracy** [comment]
https://developer.chrome.com/extensions/autoupdate#update_manifest

**Comment by dhowe** [comment]
This should be working now. Please verify...

**Comment by MrDemocracy** [comment]
The auto-update feature doesn't seem to be working. 
It's been around 30 minutes since the new v3.4.205 release, but I'm still on 3.4.202.

**Comment by dhowe** [comment]
This is only a pre-release, so wouldn't trigger the update...

**Comment by MrDemocracy** [comment]
Do you manually add the latest version to the "[updates.xml](https://rednoise.org/adnauseam/updates.xml)"? 
It still says 3.4.202 is the latest version. Shouldn't it be 3.4.202 now?

**Comment by MrDemocracy** [comment]
Right now [the xml](https://rednoise.org/adnauseam/updates.xml) doesn't have version 3.4.402 in it, so there wouldn't be any point in waiting for chrome to update the extension.

```xml
<gupdate xmlns="http://www.google.com/update2/response" protocol="2.0">
<app appid="pnjfhlmmeapfclcplcihceboadiigekg">
<updatecheck codebase="https://github.com/dhowe/AdNauseam/releases/download/v3.4.202/adnauseam-3.4.202.chrome.crx" version="3.4.202"/>
</app>
</gupdate>
```

Chrome checks for extension updates every 5 hours, which can be seen [here](https://cs.chromium.org/chromium/src/extensions/common/constants.cc?q=kDefaultUpdateFrequencySeconds&dr=CSs&l=45): 
```C++
// If auto-updates are turned on, default to running every 5 hours.
const int kDefaultUpdateFrequencySeconds = 60 * 60 * 5;
```

**Comment by dhowe** [comment]
maybe clear your browser cache? the file contents are:

    <?xml version='1.0' encoding='UTF-8'?>
    <gupdate xmlns='http://www.google.com/update2/response' protocol='2.0'>
      <app appid='pnjfhlmmeapfclcplcihceboadiigekg'>
        <updatecheck codebase='https://github.com/dhowe/AdNauseam/releases/download/v3.4.402/adnauseam-3.4.402.chromium.crx' version='3.4.402' />
      </app>
    </gupdate>

**Comment by MrDemocracy** [comment]
It didn't have the new version last time I checked, but it has now.
I can verify that auto-update now works on Chrome.
It just seems like it takes a few hours before the [updates.xml](https://rednoise.org/adnauseam/updates.xml) refreshes with the new version.
