### ISSUE TITLE
Number of ads found in vault misleading when filtered by date

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#121]
In such cases, text in vault should read: 10 ADS CLICKED OF THE 400 **DISPLAYED**

![748afbca-ff3f-11e5-9ae1-dc984f54fe98](https://cloud.githubusercontent.com/assets/737638/14409565/ba9ddbd2-ff49-11e5-98c3-d43496c2e12e.PNG)

**Comment by CyrusSUEN** [comment]
So we fix this by changing the text to "10 ADS CLICKED OF THE 400 **DISPLAYED**"?

**Comment by dhowe** [comment]
Actually just change to "SHOWN"

**Comment by CyrusSUEN** [comment]
Updated locale files and Crowdin: https://github.com/dhowe/AdNauseam/pull/205
