### ISSUE TITLE
google.ru/yandex.ru adwords not detected as clickable ad

### ISSUE THREAD

**Issue by iperov** [dhowe/AdNauseam#1213]
### Describe the issue
I disabled all filters.
Then we can see adwords at right of page. https://i.imgur.com/ttZJcj5.png - clickable ad url is yandex.ru
Then I enable for example "EasyList",
and yandex.ru-adwords dissappeared, but AdNauseam didnt detected clickable ad.
https://i.imgur.com/Tz5w7al.png

### One or more specific URLs where the issue occurs
http://pikabu.ru

### Your settings

- OS/version: Windows 7
- Browser/version: Chrome 61.0.3163.100
- AdNauseam version: AdNauseam v3.4.103 uBlock Originv1.13.8
- Other extensions you have installed: AdBlock Plus disabled.

**Comment by dhowe** [comment]
Can you include the filter lists that you have enabled (from 3rd-party filters) ?

**Comment by iperov** [comment]
https://i.imgur.com/hKVoI3v.png

**Comment by dhowe** [comment]
I'm having trouble recreating this (I see only internally-linked images in the right-hand column) from Hong Kong, Romania, and the UK. I have seen a single google ad pop up, but only once.
What geographic location are you accessing the page from?

**Comment by iperov** [comment]
from Russia.

**Comment by dhowe** [comment]
Any Russian proxy or VPN we can access for testing ?

**Comment by iperov** [comment]
cyberdain2.ddns.net 23128
auth dhowe:dhowe

**Comment by dhowe** [comment]
is this a web proxy, or ... ?

**Comment by iperov** [comment]
http proxy

**Comment by iperov** [comment]
if you want, I can organize clean windows 7 vmware with teamviewer access from my location

**Comment by dhowe** [comment]
http proxy is fine, but i don't seem able to connect -- i can telnet to the port, but no access from browser

**Comment by iperov** [comment]
I disabled auth temporally, now check

**Comment by dhowe** [comment]
good now, checking

**Comment by dhowe** [comment]
interesting, I still see only internally-linked images (do you see ads in the image below):

![screen shot 2017-09-25 at 11 09 34 pm](https://user-images.githubusercontent.com/737638/30815762-b0ea0cb8-a246-11e7-8ebc-621835c0d509.png)


![screen shot 2017-09-25 at 11 10 41 pm](https://user-images.githubusercontent.com/737638/30815795-c772590e-a246-11e7-868d-c9054d5374c3.png)

**Comment by iperov** [comment]
scroll down
![palzuxc 1](https://user-images.githubusercontent.com/8076202/30819205-10ad71fc-a22f-11e7-8ba6-6e9792fa2c96.png)

**Comment by iperov** [comment]
yandex ad block
![gsv67es 1](https://user-images.githubusercontent.com/8076202/30819345-78532658-a22f-11e7-90cf-9aaacb4b962a.png)

**Comment by iperov** [comment]
ad frame loaded from here 
http://s.pikabu.ru/external/ads/yieldbird_240x400_2017.html

![pofmcvq 1](https://user-images.githubusercontent.com/8076202/30819498-e5e043fe-a22f-11e7-822d-2cf268f5bff1.png)

**Comment by dhowe** [comment]
@greysonevins can you try to recreate this? I have not been able to

**Comment by iperov** [comment]
@dhowe ok let I install win7 on vmware with teamviewer access tomorrow ?

**Comment by greysonevins** [comment]
@dhowe @iperov I was able to recreate... I'm not sure if we can collect this ad for clicking because it is a dynamically generated one (  ```src="https://tpc.googlesyndication.com/```).

In the past for Wired with the same ad, all we could do was block it.

**Comment by dhowe** [comment]
sure. @greysonevins can you follow up on this?

**Comment by greysonevins** [comment]
@iperov @dhowe I think I found the filter that is causing the problem. See dhowe/uAssets/pull/67

**Comment by iperov** [comment]
@greysonevins I checked your new file, not works :(

**Comment by iperov** [comment]
@greysonevins but interesting behaviour. When I disabled adnauseam, then reload pikabu.ru, I got 2 banners. Then enabled adnauseam without reload pikabu.ru page with 2 banners. Adnauseam cutted 2 banners and detected clickable ad. 
![wwwwwbo 1](https://user-images.githubusercontent.com/8076202/30843813-b0a83350-a29c-11e7-9875-c39865ffd849.png)

**Comment by iperov** [comment]
I think problem is adnauseam not detected ads that was dynamically loaded after page loaded.
Can you fix it ?

**Comment by greysonevins** [comment]
@iperov the issue is that EasyPrivacy has a filter that blocks a js call that loads the ad. The fix I provided worked every time for me. Can you test it by adding the ```@@||an.yandex.ru^$third-party,domain=pikabu.ru```? The one thing I noticed is that the ad takes a bit to load, so give it a moment before ADN can collect it. That could explain your issue with it showing the banner after the fact.

**Comment by iperov** [comment]
@greysonevins I added it.
But no effect. Again no banners at right down but no collected ad.
![c178qqg 1](https://user-images.githubusercontent.com/8076202/30868103-c536221c-a2ee-11e7-9760-07eb6e434a8f.png)

**Comment by greysonevins** [comment]
@iperov can you delete your vault and test again. It's working for me.

**Comment by iperov** [comment]
nothing works.
I enabled option only click to ad.
![amwfxfu 1](https://user-images.githubusercontent.com/8076202/30896838-16eaa2c0-a364-11e7-8dd5-e6727994cc95.png)

**Comment by iperov** [comment]
firefox - better, but not all ads collected
![spr6giw 1](https://user-images.githubusercontent.com/8076202/30897158-cd9d9d5a-a365-11e7-88f9-2e0ae5021050.png)

**Comment by greysonevins** [comment]
@cqx931 @dhowe can someone else verify this one because with my change the ads are collected on my end..

**Comment by iperov** [comment]
may be you got googlead block ?
they collected got.
But yandex.ru blocks not collected

**Comment by dhowe** [comment]
from asia, i don't see the ads in the first place... @cqx931 ?

**Comment by iperov** [comment]
and in generally most of ads not collected in Russian internet

**Comment by cqx931** [comment]
I also can't reproduce the case. The ads that get generated on my computer are all background ad images.
