### ISSUE TITLE
can you create AdNauseam Lite ?

### ISSUE THREAD

**Issue by iperov** [dhowe/AdNauseam#1215]
just background ad clicker without ad remover and without "do not track"
that will 100% works on my own rules

**Comment by dhowe** [comment]
you should be able to create a version that only clicks by disabling ad-hiding and ad-blocking... is that what you mean?

**Comment by iperov** [comment]
ah nevermind, close

**Comment by greysonevins** [comment]
@iperov also if you only want your rules you can turn off the 3rd party filters that we base our blocking on too and leave _my filters_ on

**Comment by iperov** [comment]
I trying to create simple adclicker,
but got error

```
VM26332:45 Mixed Content: The page at 'https://pikabu.ru/story/pokazatel_kachestva_5373490' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://46.0.13.129:81/'. This request has been blocked; the content must be served over HTTPS.
