### ISSUE TITLE
Ad is shown despite "Hide ads" being enabled from settings

### ISSUE THREAD

**Issue by antanst** [dhowe/AdNauseam#1216]
### Describe the issue

Ad on the bottom right is shown despite "Hide ads" being enabled from settings

### One or more specific URLs where the issue occurs
https://coinmarketcap.com/

### Screenshot in which the issue can be seen
<img width="1226" alt="screen shot 2017-09-27 at 15 40 11" src="https://user-images.githubusercontent.com/966892/30913830-341f8e2e-a39a-11e7-8cc4-8135b4116021.png">

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version: macOS El Capitan
- Browser/version: Nightly 58.0a1 (2017-09-27) (64-bit)
- AdNauseam version: 3.4.103
- Other extensions you have installed: No other ad blockers.

**Comment by cqx931** [comment]
https://github.com/dhowe/uAssets/pull/68/files
The issue should be fixed now.
@antanst Please following the steps below to verify:

1.Go to AdNauseam Settings, then open the 3rd-party-filters panel
1.Click 'update' button for AdNauseam filters
1.Reload the page on which you saw the problem

**Comment by cqx931** [comment]
@antanst 
Please verify the fix above by updating your AdNauseam filters:

1. Go to AdNauseam Settings, then open the 3rd-party-filters panel
1. Click 'update' button for AdNauseam filters
1. Reload the page on which you saw the problem

**Comment by antanst** [comment]
Verified, the ad is hidden now. Thank you for your great work.
