### ISSUE TITLE
Vault zoom (with scroll-wheel) should be smooth, rather than use specific intervals

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#122]
Currently we specify each zoom-level (as below), with a corresponding to CSS class. This is quite awkward -- instead we should use a continuous transition...

`    Zooms = [100, 75, 50, 25, 12.5, 6.25],`

![screen shot 2016-04-13 at 3 55 24 pm](https://cloud.githubusercontent.com/assets/737638/14486557/2f1743ac-0190-11e6-87e9-0fc63f555ac5.png)

**Comment by CyrusSUEN** [comment]
Should we only to get rid of the hard coded part in https://github.com/dhowe/AdNauseam/blob/9aceebb71fa57eeeded29a2975372d5caca3c0a7/src/css/vault.css#L198-L226 or make the zoom value dynamic?

We still need this for computeZoom()
``Zooms = [100, 75, 50, 25, 12.5, 6.25],``

And what about the value of zooming in and out buttons on the upper left of the Vault page?

**Comment by dhowe** [comment]
Zoom buttons should go to fixed intervals (as above). Scroll wheel should dynamically zoom as in Google maps.

**Comment by CyrusSUEN** [comment]
> Scroll wheel should dynamically zoom as in Google maps.

Please verify: https://github.com/dhowe/AdNauseam/pull/197

The most notable feature is that If we scroll so faster on the Mac trackpad it will zoom in / out faster. 
If we do it on a mouse with a detent mouse wheel (means a fixed discrete scrolling), the mouse zooming is also fixed.

**Comment by CyrusSUEN** [comment]
Fixed 2 bugs after adding dynamic zooming: https://github.com/dhowe/AdNauseam/pull/204

One is to restore zooming after exiting light box mode (because we now have dynamic zooming scale in addition to the values from zoomIdx[])
Another is adjusting the zooming speed on mice with fixed discrete step.

**Comment by dhowe** [comment]
Any reason not to allow zooming-in (perhaps to a 200% magnification) ?

**Comment by CyrusSUEN** [comment]
> Any reason not to allow zooming-in (perhaps to a 200% magnification) ?

Text will still be sharp over 100%. But we will notice some image noise:
![capture](https://cloud.githubusercontent.com/assets/2461812/15803750/89b5806c-2b20-11e6-9c6c-f72fe6fbc668.PNG)

We now have 2 scale:
Zooms = [100, 75, 50, 25, 12.5, 6.25]
userZoomScale 100% - 5%

**Comment by dhowe** [comment]
thats OK, lets try:

Zooms = [200, 150, 100, 75, 50, 25, 12.5, 6.25]
userZoomScale 200% - 5%

**Comment by CyrusSUEN** [comment]
> lets try:

Please try: https://github.com/dhowe/AdNauseam/pull/211

**Comment by dhowe** [comment]
@mushon, please test this for usability

**Comment by mushon** [comment]
joining this discussion unfashionably late, but I don't understand why should we go beyond 100% zoom, especially when we're using userZoomScale, I think the user would prefer having an easy way to get to 100%. I would vote for going up to 100%.

**Comment by dhowe** [comment]
For very small ads, it is difficult to inspect the text or image without zooming beyond 100%. The default layout should be a max of 100%, but the user should be allowed to scroll up to 150% at least...

**Comment by mushon** [comment]
I really think we’ll be losing more than gaining by going beyond 100%. If a user wants to zoom into an image beyond its original size they can use the same tools they would use any other place on the web. If you’re convinced we need this we’ll do it, but if you ask me I think we shouldn’t.



For very small ads, it is difficult to inspect the text or image without zooming beyond 100%. The default layout should be a max of 100%, but the user should be allowed to scroll up to 150% at least...

**Comment by dhowe** [comment]
What would we be losing?

**Comment by mushon** [comment]
We would be losing the %100 marker as a max bar

**Comment by dhowe** [comment]
I'm fine either way, though I'm not sure this is much of a priority (there are bigger fish to fry). I occasionally found myself wanting to zoom into ads beyond 100% to better see and/or print them, but I am not the average user... We should probably hear from @CyrusSUEN as to how much time it would take to revert to 100% max, and let that guide the decision

**Comment by CyrusSUEN** [comment]
> how much time this would take and then think about the priority

I think this can be done in an hour but it requires an all-rounded testing.
We will be removing the values beyond 100% scale from `Zooms` array but will need to spend most time verifying the changes.

**Comment by dhowe** [comment]
reconsider when rewriting the vault
