### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by thomasklash** [dhowe/AdNauseam#1220]
### Describe the issue
Regarding versioning - with every new release is the version number increasing?
Regarding updates on Chromium/Chrome - do we have to manually update?

I ask because I noticed the new release is only a day old, and is 3.4.103, but I have had that version for a while.

### Your settings

- OS/version: Windows 7 SP1 x64
- Browser/version: CentBrowser Version 2.8.5.75 (Official Build) (64-bit) (Chromium 60.0.3112.113)
- AdNauseam version: 3.4.103

**Comment by dhowe** [comment]
> Regarding versioning - with every new release is the version number increasing?

Yes. I think the data may have changed on that release b/c one binary was subsequently added

> Regarding updates on Chromium/Chrome - do we have to manually update?

At the moment, yes. However we are working on an auto-update (see #1209)
