### ISSUE TITLE
Ads visible on last.fm

### ISSUE THREAD

**Issue by ZedPea** [dhowe/AdNauseam#1221]
### Describe the issue
Ads visible on last.fm with firefox 57, but are not visible with ublock origin

### One or more specific URLs where the issue occurs
https://www.last.fm/events, in the related searches part of the page

### Screenshot in which the issue can be seen
![selection_001](https://user-images.githubusercontent.com/22151537/31045783-d5d7a188-a5da-11e7-906e-34f28addab93.jpg)

### Steps for anyone to reproduce the issue
Load url
Observe ads

Disable adnauseum, enable ublock origin
Load url
No ads should be visible

### Your settings

- OS/version: Arch Linux 4.13.3-1
- Browser/version: Firefox Quantum, 57.0b4 (64-bit)
- AdNauseam version: AdNauseam v3.4.103, uBlock Origin v1.13.8 
- Other extensions you have installed: uBlock Origin 1.14.10 (disabled when using adnauseum of course, just to check if ads are blocked in ublock)

**Comment by cqx931** [comment]
https://github.com/dhowe/uAssets/commit/0d0520421a26fb11909aad451baaff06a6febed7 fixed.
@ZedPea Please verify the issue by updating your AdNauseam filters. Thanks!

**Comment by ZedPea** [comment]
Yup, that worked, thanks!
