### ISSUE TITLE
Ads not clicked on fmovies.is

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1222]
From: https://www.reddit.com/r/Adblock/comments/6ofdy7/adnauseam_fails_to_click_ad_on_fmoviesis/

>I want AdNauseam to click the ad's on fmovies.is for me, but the ad's on the page sometimes don't have a domain extension (redirects to proper url after you click it), which confuses AdNauseam and causes the click to fail.

>I am able to block them however, but I can't support fmovies.is when AdNauseam won't do it's job.

![image](https://user-images.githubusercontent.com/737638/31048066-49f0d52c-a648-11e7-94af-6818e2dbf3f5.png)

**Comment by greysonevins** [comment]
@dhowe This was what I fixed in the last issue we had with fmovie... Still works fine for me.

**Comment by greysonevins** [comment]
also, @dhowe this is what we fixed with the regex that just dismisses the ads with bad urls. I think the user has not yet updated ADN possibly.

**Comment by MrDemocracy** [comment]
@greysonevins The real urls can be found in a .js that's loaded when the mgid ads load. (See #1193) 
I have updated to the newest version, and the bad links are dismissed, but I would rather want them to be clicked. Very often all of the ads on the page, have fake urls. If they're all dismissed, AdNauseam is just bending the knee for this kind of ads. Isn't the point of AdNauseam to be one step ahead of the data trackers, and click all ads?

**Comment by greysonevins** [comment]
@MrDemocracy If the url's are fake, there is no sense in collecting them and they clog the process of clicking on the ads. Collection is ultimately futile as the url is never resolved. Please see the past communication (#1099 #1100 #963) with this issue so that you can see that we resolved this with ignoring the urls, I don't think there is a reason to undo this...@dhowe any other thoughts?

**Comment by MrDemocracy** [comment]
@greysonevins Did you read the first part of my message? See #1193, where I explain it more in depth. 
I don't want AdNauseam to click the fake url's, I want it to notice that an url is fake, and then find the real one.

**Comment by MrDemocracy** [comment]
@greysonevins 
<img width="1280" src="https://user-images.githubusercontent.com/23060864/31134861-9ed9eb24-a863-11e7-871c-0f8a290918a0.png">
<br>
<img width="1280" src="https://user-images.githubusercontent.com/23060864/31134865-a412e1ea-a863-11e7-9e5f-022a03174893.png">

**Comment by cqx931** [comment]
I'm closing this because we have another ticket for mgid now: https://github.com/dhowe/AdNauseam/issues/1193
