### ISSUE TITLE
Adding a lot of friend's profile pictures to the advault

### ISSUE THREAD

**Issue by MrDemocracy** [dhowe/AdNauseam#1223]
### Describe the issue
AdNauseam is adding a lot of my friend's profile pictures to the advault, when a Facebook Group page is recommended to me on Facebook.

Could you make it so AdNauseam doesn't add image links with "&hc_location=group", "/groups/", "/profile.php" or "?ref=unknown" in it, to the advault?
And also make it so images from Facebook smaller than 100x100 isn't added to the advault.

### One or more specific URLs where the issue occurs
Everywhere on Facebook. 

### Screenshot in which the issue can be seen
<img width="1280"  src="https://user-images.githubusercontent.com/23060864/31119656-f2557930-a831-11e7-8bc9-676a279fe28d.png">

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version: macOS 10.13 (17A365)
- Browser/version: Google Chrome 61.0.3163.100 (Official Build) (64-bit)
- AdNauseam version: v3.4.103

**Comment by dhowe** [comment]
@cqx931 we should probably fully review our facebook functionality at this point

**Comment by MrDemocracy** [comment]
`https://scontent-bru2-1.xx.fbcdn.net/v/t1.0-1/p148x148/21740666_102070320539115_1358002038712265959_n.jpg?oh=8dd1166152c8972ebe0e2fd5f2f3e275&oe=5A7F27C8`

`https://scontent-bru2-1.xx.fbcdn.net/v/t1.0-1/c29.0.100.100/p100x100/1379841_10150004552801901_469209496895221757_n.jpg?oh=0ada5030fc4fb85e00ee97e0f0b1f8df&oe=5A7F2324`

`https://scontent-bru2-1.xx.fbcdn.net/v/t1.0-1/p64x64/13932782_1089271304498833_3095251739322268456_n.jpg?oh=abd3091eff286459b13e1496c3052a1c&oe=5A771C99`

`https://scontent-bru2-1.xx.fbcdn.net/v/t1.0-0/s600x600/10653293_10153073855108040_5843224593357860663_n.jpg?oh=84c1cc2e8ca1835d8d0f3df394c969d7&oe=5A7FF0B3`

**Comment by cqx931** [comment]
Thanks! @MrDemocracy 
I just made the changes so that AdNauseam will ignore images smaller than 150px from `scontent` `fbcdn`
https://github.com/dhowe/AdNauseam/pull/1226

**Comment by MrDemocracy** [comment]
@cqx931 But `https://scontent-bru2-1.xx.fbcdn.net/v/t1.0-0/s600x600/10653293_10153073855108040_5843224593357860663_n.jpg?oh=84c1cc2e8ca1835d8d0f3df394c969d7&oe=5A7FF0B3` is larger than 150px, and its not an ad.

**Comment by cqx931** [comment]
It should be the image from the facebook group. 
@dhowe Do we consider group recommendation as an ad? Is this one example of the hybrid ad case(https://github.com/dhowe/AdNauseam/issues/860)?

**Comment by dhowe** [comment]
screenshot?

**Comment by cqx931** [comment]
The apartment image is the image from the facebook group:
<img src="https://user-images.githubusercontent.com/3056154/31230427-fcbf153a-a9b1-11e7-96db-b2ac19473811.png" width="300"/>

**Comment by dhowe** [comment]
My feeling is that since that is internal Facebook content, it should not be treated as an ad.
Which means that our 150px rule is correct, though I really do not like having such a special case in the code.
Is there no way to test css attributes like width/height in a ublock/abp rule?

**Comment by cqx931** [comment]
They do have css width/height in a ublock/abp rule. 
But ublock/adp rules are for hiding(collecting) and blocking.
But what we are trying to do here is not collecting them. Or do you mean to use ublock/adp format for all ignored ads? It would also be nice if we could update them in adnauseam filter instead of in the code.

**Comment by cqx931** [comment]
@dhowe Any feedback on this?

**Comment by dhowe** [comment]
Are you suggesting adding a new _type_ of rule to adnauseam filters?

**Comment by cqx931** [comment]
A hiding exception rule won't solve this. Because we are not hiding the image tag here but the entire recommendation(the outer div). This includes many images, both the profile pics and the ad/group banner. 

Yes,  in this case I think we need a new type of exception rule that serves for ad collecting.
Also, because the attribute selector doesn't support [width<150px], we will need several rules that specify all the possible image width we want to ignore here.

**Comment by dhowe** [comment]
so what would such a rule look like?

**Comment by cqx931** [comment]
Something like `$@$img[src*="fbcdn.net"][width="148px"][height="148px"]` ?

**Comment by dhowe** [comment]
how many rules would we need to do each of the possible widths?

**Comment by dhowe** [comment]
status?

**Comment by cqx931** [comment]
I think this can be closed.
Implemented for now with inline code in parser.js:
https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/parser.js#L212
