### ISSUE TITLE
DEV-FAQ entry for 'How do I create a custom filter for a text or text-hybrid ad?'

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1224]
Placeholder already there, please fill in after doing mgid ads ( #1193 )

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#how-do-i-create-a-custom-filter-for-a-text-or-text-hybrid-ad

**Comment by dhowe** [comment]
excellent
