### ISSUE TITLE
Ads on Pandora

### ISSUE THREAD

**Issue by LtPatterson** [dhowe/AdNauseam#1228]
# Describe the issue
Self explanatory. Banners and audio.

### One or more specific URLs where the issue occurs
pandora.com

### Screenshot in which the issue can be seen
https://i.imgur.com/PLucheI.png

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version: Win 7 x64
- Browser/version: FF 56
- AdNauseam version: 3.4.103
- Other extensions you have installed:

**Comment by greysonevins** [comment]
@LtPatterson can you test in your settings with the commit I made above and let me know if it works?

**Comment by LtPatterson** [comment]
@greysonevins confirming commit cf3aab1 fixes the issue. Got a banner on initial page load, ad nauseam did its thing and it was taken care of. Able to use site as normal.

**Comment by dhowe** [comment]
@greysonevins this broke parts of the github site -- you need to be _very_ careful when using wildcard-matching or regular expressions in rules without a domain (almost always better to specify an explicit domain)

@cqx931

**Comment by dhowe** [comment]
@greysonevins: please confirm my comment above, then close

**Comment by LtPatterson** [comment]
Resolved. Closed.
