### ISSUE TITLE
No longer able to right-click to block ads

### ISSUE THREAD

**Issue by MrDemocracy** [dhowe/AdNauseam#1231]
### Describe the issue
Usually when I want to block an ad, I quickly just right-click and block the ad. I'm no longer able to do this. It first happened after I installed v3.4.109, from the master branch (which I have since removed, and replaced with the latest pre-release).

### One or more specific URLs where the issue occurs
Everywhere.

### Screenshot in which the issue can be seen
<img width="1280" src="https://user-images.githubusercontent.com/23060864/31353363-95af7b1c-ad32-11e7-9be0-3ace04eeea18.png">

### Steps for anyone to reproduce the issue
Not sure.

### Your settings

- OS/version: macOS 10.13 (17A405)
- Browser/version: Google Chrome 61.0.3163.100 (Official Build) (64-bit)
- AdNauseam version: v3.4.201

**Comment by dhowe** [comment]
Confirmed -- @cqx931 can you take a look at this ASAP

**Comment by dhowe** [comment]
This should be fixed in the [newest release](https://github.com/dhowe/AdNauseam/releases/download/v3.4.202/adnauseam-3.4.202.chrome.crx)
@MrDemocracy can you give it a try?

**Comment by MrDemocracy** [comment]
"Block element" is back now. Thanks @cqx931  and @dhowe.
