### ISSUE TITLE
Empty dashboard and nothing functional

### ISSUE THREAD

**Issue by wwp** [dhowe/AdNauseam#1233]
### Describe the issue
Dashboard shows empty pages for every single tab, actions performed in toolbar item's menu do nothing, no ad get filtered out. IOW, it doesn't work at all.
This is only specific to 2 users on this machine, it works fine for other users. The two users for whom it doesn't work, are using ffx w/ a lot of add-ons (it doesn't work even w/ all add-ons disabled and ffx restarted). Maybe something in firefox config?

### One or more specific URLs where the issue occurs
Any.

### Screenshot in which the issue can be seen
-

### Steps for anyone to reproduce the issue
Install AdNauseam on Firefox 52.4.0 (64-bit) on a CentOS7 (up-to-date), open the dashboard, click on the AdNauseam toolbar button, open a web page.

### Your settings

- OS/version: CentOS 7, up-to-date.
- Browser/version: Firefox 52.4.0 (64-bit)
- AdNauseam version: 3.4.202
- Other extensions you have installed: many ones, but I disabled them all and restart Ffx, same issue.

**Comment by dhowe** [comment]
Are all users using the same version of Firefox (v52.4.0?)

**Comment by wwp** [comment]
Yes they are. For now I couldn't figure out what's wrong for the 2 users where it doesn't work. Amongst all the users on this system, it's not the amount of enabled add-ons that indicates a risk of failure or not. They all use either {ublock-origin (removed to replace w/ adnauseam), noscript, .. }, but nothing indicative I could find.

**Comment by dhowe** [comment]
Quite strange -- would be good to get to the bottom of this, as we have other similar reports of AdNauseam occasionally not working correctly on specific machines/setups. Question: for how many users is it working correctly?

**Comment by wwp** [comment]
5 users configured on this system, all the same firefox version. 2 works, 3 don't.

**Comment by dhowe** [comment]
Any updates? I'm not sure what to suggest in terms of testing/debugging other than uninstalling and re-installing...

**Comment by mneunomne** [comment]
This should be closed, sounds like to do with FF profile. should be really outdated by now.
