### ISSUE TITLE
Facebook isn't working with any of adnauseam releases

### ISSUE THREAD

**Issue by makcim392** [dhowe/AdNauseam#1234]
### Describe the issue
Recently I tried to enter facebook.com and isn't showing anything
It's not working neither on chrome nor vivaldi. I'm on release 3.4.202.chromium

### One or more specific URLs where the issue occurs
facebook.com

### Screenshot in which the issue can be seen

![asdsad](https://user-images.githubusercontent.com/1855188/31450492-f50239a8-ae7f-11e7-8917-4936b580aa79.PNG)

![asdasdsaddasd](https://user-images.githubusercontent.com/1855188/31450546-1b7aa6ba-ae80-11e7-9b85-f5e0dfc5eb8a.PNG)

### Steps for anyone to reproduce the issue
just run facebook on any of the browsers mentioned

### Your settings

- OS/version: Windows 10 (Both Aniversary Update and Creators Update)
- Browser/version: Chrome 61.0.3163.100 (latest) and Vivaldi 1.12.955.38 (latest)
--

(Latest)
- AdNauseam version:  3.4.202
- Other extensions you have installed: Toby, Umatrix (disabled), Lastpass, getPocket, download for facebook [Chrome]
-Umatrix (disabled) [Vivaldi]

**Comment by dhowe** [comment]
Can't recreate.

![image](https://user-images.githubusercontent.com/737638/31467492-ba96c530-af0c-11e7-9424-07f86567cba0.png)

**Comment by makcim392** [comment]
So wierd! now it's working again. I tried today on Edge and it was working. I went out for couple of hours and now it's working again. Definitely it was not me or my computer/s.
