### ISSUE TITLE
Ads are not clicking?

### ISSUE THREAD

**Issue by siennk** [dhowe/AdNauseam#1235]
Every site I go on, none of the ads that collect through AdNauseum seem to be clicking. They constantly show up as "failed". I don't know what I did wrong. I disabled all ad blocking-like extensions before downloading AdNauseum.

I am using Firefox and I had uninstalled AdUltimate and disabled uBlock Origin and NoScript before I got AdNauseum.

**Comment by dhowe** [comment]
Can you post your version infos here, for AdNauseam, Firefox, and OS?

**Comment by siennk** [comment]
AdNauseum: 3.4.201
Firefox: 55.0.3 (64-bit)
OS: Mac Sierra 10.12.6 (16G29)

**Comment by dhowe** [comment]
Thanks. Can you try the following: 
- Go to chrome://extensions/, find AdNauseam, and click 'background.html' to open the console
- Leave this window open, and then click 'options', again under AdNauseam, to open the 'settings' page
- Now enable  'Activate debugging mode' at the bottom of the settings
- You should begin to see output in the console window you opened previously
- Now go to any page, like this [test page](https://rednoise.org/adntest/simple.html), that has ads
- Wait a few moments, then copy/paste the debug output below
