### ISSUE TITLE
Change 'AdNauseam Filter' update button function

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1236]
It is not always clear why the AdNauseam list 'update' button is active and or not; also, why one sometimes has to  to 'purge-caches' sometimes; and finally, whether the list has actually updated or not

Assuming everything is in fact working, we need some better visual clues as to what is happening and why (possibly a FAQ entry as well)

Please verify that:
-- button functions correctly
-- it is clear to user when the update starts [design]
-- it is clear to user when the update completes  [design]
-- it is clear to user if the update fails (disable internet during test)  [design]
-- it is clear whether the list has actually changed  [design]

**Comment by cqx931** [comment]
All the update buttons function correctly.
One confusing issue I have noticed is that if you hover over the clock icon, you can force an update according to the hint. However, if I click the icon, the icon turns to "!"(out of date) while the filter itself remains unchanged. The user need to then click the 'update' button to update the list. The performance is the same in ublock.
![image](https://user-images.githubusercontent.com/3056154/31502631-a8548d1a-af3b-11e7-8cc8-eef55383efd0.png)


The current uBlock design
- When the update starts, the icon changes to  "updating"<img src="https://user-images.githubusercontent.com/3056154/31503422-9b8b21f0-af3d-11e7-831d-db69f1e10c9f.png" width="40px"> (the icon doesn't change to "updating" if the filter is short and the update happens very fast, ex: AdNauseam filters)
- When the update completes, the icon changes to a clock , indicating that the filter is up to date.
- When there is an network error, the icon should change to red broken link <img src="https://user-images.githubusercontent.com/3056154/31503493-cbdec5fa-af3d-11e7-9b50-1a519df9365c.png" width="40px"> (Is there any other failing case?)
- Whether the list has actually changed: now you can see that in the interface by the number of entries, or by opening the list. When hovering the clock icon, it shows "Last Update: x minutes ago".

**Comment by dhowe** [comment]
And what about enabled/disabled state of the adnauseam 'update' button, and how this relates to 'purge caches'?  

For example, when I check now, I see the last update to the adnauseam list was a day ago, yet both the  'update' button (and the general 'update now' button) is disabled. The only option is 'purge caches', the meaning of which is not at all clear...

What if we make the adnauseam 'update' button permanently enabled, and give it the same functionality as 'force-update' ? I think this, together with a hover explanation for 'purge caches', would clear things up a lot

**Comment by cqx931** [comment]
For the case you mentioned above, the 'update' button is disabled because when AdNauseam tried to do automatic update last time, the cache is already up to date with the latest version. (but there could be some delay I suppose.)
'Purge caches' is quite confusing, I agree...

**Comment by dhowe** [comment]
>>For the case you mentioned above, the 'update' button is disabled because when AdNauseam tried to do automatic update last time, the cache is already up to date with the latest version. (but there could be some delay I suppose.)

Yes, but what if we make the adnauseam 'update' button permanently enabled, and give it the same functionality as 'force-update'  ? 

>> 'Purge caches' is quite confusing, I agree...

Does uBlock have a description of this somewhere button ( 'revert to originally installed lists' ) ?

**Comment by cqx931** [comment]
> Yes, but what if we make the adnauseam 'update' button permanently enabled, and give it the same functionality as 'force-update' ? This seems clearer and more consistent to me. Worst case is that we waste a download occasionally (the file is not big anyhow)...

Agree

> Does uBlock have a decent description of this button somewhere ( 'revert to originally installed lists' ) ?

This one?
https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#purge-all-caches

**Comment by dhowe** [comment]
>> Yes, but what if we make the adnauseam 'update' button permanently enabled, and give it the same functionality as 'force-update' ? This seems clearer and more consistent to me. Worst case is that we waste a download occasionally (the file is not big anyhow)...

> Agree

Ok. Lets try to get these updates into 3.5

**Comment by Atavic** [comment]
@cqx931 asks [here](https://github.com/dhowe/AdNauseam/issues/1236#issuecomment-336171194)

>Is there any other failing case?

Icon stays on updating forever, due to unresponsive requests (I got this with strict firewall rules).

**Comment by dhowe** [comment]
You mean that instead of changing to a read broken link, it shows the updating icon forever ?

**Comment by Atavic** [comment]
I had it in FF 52, because my firewall was blocking some update.

**Comment by Atavic** [comment]
Yes.
I had it in FF 52, because my firewall was blocking some uBo update.

**Comment by dhowe** [comment]
Have you created a [uBlock issue](https://github.com/gorhill/uBlock/issues) ?

**Comment by dhowe** [comment]
@cqx931 to reiterate, this ticket is waiting on making the adnauseam 'update' button permanently enabled, and give it the same functionality as 'force-update'

**Comment by Atavic** [comment]
I didn't, as I assumed it was my fault.

**Comment by cqx931** [comment]
Please check https://github.com/dhowe/AdNauseam/pull/1261
@dhowe
