### ISSUE TITLE
AdNauseam filters rule breaks random folders on Github

### ISSUE THREAD

**Issue by laino** [dhowe/AdNauseam#1240]
### Describe the issue

Folder name being missing (just an icon there).

### One or more specific URLs where the issue occurs

https://github.com/laino/final-pm/tree/634a19e03ac537830d0d08c171720ce385f20c3c

### Screenshot in which the issue can be seen

<img src="https://i.imgur.com/Gqg9LkE.png"></img>

### Steps for anyone to reproduce the issue

Enable the "AdNauseam filters" essentials filter.

**Comment by dhowe** [comment]
Thanks. 
Matched the following rule, which was defined too broadly:  ##*[id*="ad1"] 

<a href="/laino/final-pm/tree/634a19e03ac537830d0d08c171720ce385f20c3c/lib" class="js-navigation-open" id="e8acc63b1e238f3255c900eed37254b8-61dedecb53b5094ac3f2f4_ad1_a51d146a00fb266" rel="nofollow" title="lib">lib</a>

**Comment by dhowe** [comment]
Please check and close if also fixed for you

**Comment by dhowe** [comment]
Looks ok to me now -- if you see this problem again, pls reopen...

![image](https://user-images.githubusercontent.com/737638/31584423-e2fae9c6-b1e0-11e7-88e8-865ddb05c29e.png)
