### ISSUE TITLE
Broken URL parsing in branch

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1242]
@cqx931 see if you can recreate... (this was originally spotted in 1.14.12)

<pre>
core.js:860 Invalid domain: http://https://www.lowes.com
warn @ core.js:860
core.js:860 Invalid domain: https://undefined/aclk?sa=l&ai=Cqd08zWyDWaD5HonjBZT_qLgD8smyl0qxl8zNzALhtuDi1AUQASD2t8QgYMn27IiEpIARoAGf5rDaA8gBAqgDAcgDyQSqBMgBT9BK-KXcM4dNHHa9iAhpv_hjkzMZNa0gJ7KNOL9IwDtZM7PcCjwy9B8vib3YpPITz2OmQwRRgBbrulZhfK4-Oo172YPZxskKqq_mSDn4ryrJGFx8YELGwikyg10DUbNG3ruwT_5B72iJOic7-_YX_rceNAQRl8y3cbimLrPHOfsU5wXCJoPEvqwxJOKUijFOBpWrdgkkP4rCmUAU_RK3zMHNFKI76Dg1gdUmSl2Hfi0SXbOPGp15rC7c7e8OK_TYMvqXdnUK0i-gBgKAB8mZzyWoB6_KG6gH3cobqAemvhvYBwHSCAcIgGEQARgCsQmse5TeQgEqr9gTAw&num=1&sig=AOD64_3Eaxh5Ney7wfh1xGvPikNhx5m_2A&client=ca-pub-8820663070911865&adurl=http://us.misumi-ec.com/
warn @ core.js:860
core.js:860 Invalid domain: https://undefined/aclk?sa=l&ai=CiGm6ePKMWfT_LtT0-QPNlIWwCob7v-xK0YSCyuoFg8GI1KoJEAEg-qDTF2DJhoCA7CSgAcqd_8gDyAECqAMByAPJBKoEwAFP0D2CWiW1yBoVeecx8V8j0X7zOGm3U-Anune-9lGFyG_uHN0hxxmdS1BJ46ekgmjyFXQCoWYTTDZjafJAa7_41qUYWJDPsgsChVxPUDqPbZCMmCDvRu_1MTWRupxJeJDU-Nxp95e0raV_nzAmDEdMwlM_VGg0VQeWG9G_KpcLJUA1O0KFF_A2ZHUd6jf_WgEonwcgXne1-eltj3xEJ-5gTkNxQSfZ0BSGEKjEhrDKKZdaIYZU2lF4r9is_HRNZnygBgKAB57igDeoB6_KG6gH3cobqAemvhvYBwHSCAcIgGEQARgCsQmN0wlH1mTGMNgTDA&num=1&sig=AOD64_1hVT5-eebnU9FPlNHMb7LGqOvtIw&client=ca-pub-4467999923702997&adurl=https://www.joinhoney.com/r/gdnUamazonIM%3Furl%3Dhttps://www.joinhoney.com/r/GDN_US_Broad_None_18-65_All_Amazon_AmazonCreative_NA_InlineAmazon%253Furl%253Dhttps%25253A%25252F%25252Fwww.joinhoney.com%25252Fg%25252Farticle%25252Fhow-to-save-on-amazon
warn @ core.js:860
core.js:860 Invalid domain: https://undefined/aclk?sa=l&ai=Csmv6_QdOWa_aOITR2QT104aQBcXL9c5JpIe68YwFlL2OvdUHEAEgktn-BGDZAqABoP2n4QPIAQKpAq4eI4wCNYE-qAMByAPIBKoEpgFP0FHlfUcl_EDD1ZvdewcezNEI_cRUVFKKE--geZ2g9CgbtcHFCJGVY537iO8Cj4DIO8Ff1yRSOGuI2UXgH4GYN_lYqzjYmbDCyX03UxZrnBrH09jFaoJs2FG1sRqNC8HQj6BaIAbLNKhcZ_kcGb_imPBOQ7Ddj85BVzJLEjQwou90nGGdjJdTDAsZ1mYJE9JZPNbQ-Yy0DDPDDUE8ecZDC6e4zP_NoAYCgAfIgtgeqAevyhuoB6a-G9gHAdIIBQiAYRABsQlF2msjRWTzz9gTCg&num=1&sig=AOD64_1qusd2v_3ziti0VGRg1DFT-TKj3w&client=ca-pub-3283898153228679&adurl=http://www.mydress.com/brand/all_0623%3Futm_source%3Dgoogle%26utm_medium%3Dcpc
warn @ core.js:860
core.js:860 Invalid domain: https://undefined/aclk?sa=l&ai=CGZj1fI8uWY3HEYaeqAGVxJvwBJ-8gt5E-oXsg6MDyNWJ50cQASC5zaU0YNkCoAGFt4nIA8gBAqgDAcgDyQSqBMgBT9BOCNm9mozwjnaVOnJ2iDVHs--yasIkmz6IsdwX-XSp0OEL6fQh4_lshs9mEZoK3sP50ueUfqbJ_AU75ijDGBUFjtcpjULXteyCsLopDDecD0i5HRHaALXhea0LzzysqoydHk0Mlp8bZV7LHV6d9UbzWZtnaiyixREciA3BT8_iS7fQGcIEFpkGRfgeCJemU6m6FHNZf15ufZjjvpZqSfHN_RHabiMeBwbXagqsJE8WYVPnYB-bxZXOBSA6-T7AvEKTzIXmOKGgBgKAB6qfyzmoB6a-G9gHAdIIBQiAYRABsQlSsPnNGA-H_dgTAg&num=1&sig=AOD64_24qBTHqmTWmSfATuFCDHBzsKmbcw&client=ca-pub-9361698158806173&adurl=http://www.wondershare.net/ad/data-recovery-mac.html
warn @ core.js:860

**Comment by cqx931** [comment]
When did you see this? What are the steps to recreate?

**Comment by cqx931** [comment]
@dhowe

**Comment by dhowe** [comment]
I'm not sure... lets close for now, but please keep an eye out for this in the addon console
