### ISSUE TITLE
Outline not always green for DNT items in menu

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1246]
Not sure how to recreate this consistently, but it does seem to happen. If you see it, please try to debug. 

Note: closing and opening the menu seems to fix this...

![screen shot 2017-10-15 at 6 20 34 pm](https://user-images.githubusercontent.com/737638/31583888-a14aaa44-b1d5-11e7-87e8-03ebf08660f2.png)

**Comment by cqx931** [comment]
Close fpr #1168
