### ISSUE TITLE
Error: 'No matching message handler for the given recipient'

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1252]
Not sure if this is causing any problem...

![screen shot 2017-10-15 at 8 03 22 pm](https://user-images.githubusercontent.com/737638/31584599-e500fbd6-b1e3-11e7-8b1e-7b43ca367ef3.png)

**Comment by mneunomne** [comment]
Was not able to reproduce as of 2023 with 3.16.1b3 FF 108.0.1 (64-bit). Probably outdated.
