### ISSUE TITLE
"Waiting for extension AdNauseam"

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1256]
Saw this while waiting for a long page load. Anyone else?

**Comment by idibuseba** [comment]
Yes, happening quite often for me (at least couple of times a day) - when the issue occurs, it never affects a single page, instead all pages with AdNauseam enabled don't load during that period, with the same message. Sometimes takes up to a minute!

The message appears in the lower corner of Chrome, like any other "Waiting for..." info:
![image](https://user-images.githubusercontent.com/2776439/31914494-2b323cce-b84b-11e7-99d7-d907025b2eed.png)

Seems to be happening mostly (though not exclusively) on various news websites.

**Comment by dhowe** [comment]
Versions for OS/browser/AdNauseam ? Thanks...

**Comment by idibuseba** [comment]
Win 10 Home 64-bit, version 1703, build 15063.674
Chrome Version 61.0.3163.100 (Official Build) (64-bit)
AdNauseam v3.3.403 uBlock Originv1.12.2

I cleared the Ad Vault completely - will see if this helps in any way.

**Comment by dhowe** [comment]
Are you using AdNauseam _and_  uBlock together? This is very much not recommended...

**Comment by idibuseba** [comment]
No, sorry - I simply mean this:
![image](https://user-images.githubusercontent.com/2776439/31939679-98b082fe-b8bb-11e7-86e0-7a1089d76685.png)
I guess it always shows, as AdNauseam is built atop uBlock? I don't have any separate instances of uBlock (or any other blocker for that matter) used or installed in the browser.

**Comment by dhowe** [comment]
Ah I see -- that is correct then. It shows the version of uBlock on which it was built...

**Comment by idibuseba** [comment]
It appears that the issue completely stopped occuring after cleaning the Ad Valult :)

**Comment by dhowe** [comment]
That is interesting -- this is just clearing the vault, without disabling/enabling the addon, or restarting the browser?

Question: did you have the vault open while the problem was occurring (perhaps in a non-active tab)?
(b/c if the vault is not open, it should have no effect whatsoever on the addons function)

**Comment by idibuseba** [comment]
Nope, I never keep the vault open. When I went to clean it, it was probably the first time I ever opened it.

I didn't disable/enable the addon; can't really comment if the issue stopped after only cleaning the vault or cleaning the vault + restarting the browser... don't remember, sorry :( Especially that the issue never occured "all the time", so I needed a couple of days to confirm it being gone completely.

**Comment by dhowe** [comment]
Thanks -- restarting the browser should definitely fix the issue, but I am curious if just clearing the vault does as well..

**Comment by gschukin** [comment]
This happens to me if vault has more that 4k ads. Clearing vault fixing the issue.

**Comment by dhowe** [comment]
Interesting -- can you verify the version you are using?

**Comment by gschukin** [comment]
Unfortunately I don't remember but no issues after updating to 3.5.101
