### ISSUE TITLE
[pre-release 3.4.205] No network entry in ublock logger - Firefox webExt

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1259]
only cosmetic blocking entries
![image](https://user-images.githubusercontent.com/3056154/31857885-22c6c144-b6b7-11e7-8e75-70ffc6c9d436.png)

**Comment by dhowe** [comment]
I see a range of entries when visiting, for example, the NYtimes:

![screen shot 2017-10-22 at 12 28 53 pm](https://user-images.githubusercontent.com/737638/31858210-a86638a8-b724-11e7-92f5-da6ce31b3425.png)

**Comment by cqx931** [comment]
This is pretty strange, I can still only see cosmetic hiding entries. 
No error log in background.html or in the logger.

**Comment by dhowe** [comment]
checking the logger window console ?

**Comment by cqx931** [comment]
I still see the same issue with firefox 57 as well
Now in background.html:
![image](https://user-images.githubusercontent.com/3056154/31862717-9f5ad926-b710-11e7-9a8b-597fe6ad69a0.png)

**Comment by cqx931** [comment]
I was on commit 4ec802b, but this is fixed in latest master branch
