### ISSUE TITLE
Inspector: Verify that DNT ads still show visit info when DNT-ads are being clicked

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1260]
Verify that DNT ads still show visit info when DNT-ads are being clicked (due to user settings). They should NOT have the inspector message below (and should not even be green?)...

![image](https://user-images.githubusercontent.com/737638/31860990-76d4ad06-b756-11e7-8240-e88b4ebab3c4.png)

**Comment by dhowe** [comment]
![image](https://user-images.githubusercontent.com/737638/31860990-76d4ad06-b756-11e7-8240-e88b4ebab3c4.png)

**Comment by mushon** [comment]
yet another reason to separate ad classification from software action

**Comment by dhowe** [comment]
see comments on #1168
