### ISSUE TITLE
Auto-playing audio ads on www.inc.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1262]
https://www.inc.com/wanda-thibodeaux/take-a-shower-today-science-says-that-might-have-been-a-mistake.html

![image](https://user-images.githubusercontent.com/737638/32101772-28abd0d8-bb4c-11e7-88f2-e2a0b7010550.png)

**Comment by greysonevins** [comment]
Can't seem to duplicate it @dhowe 

![image](https://user-images.githubusercontent.com/11656811/32102651-3593f8ac-bb15-11e7-8e4e-15869b632839.png)

**Comment by dhowe** [comment]
fixed: https://github.com/dhowe/uAssets/commit/123bcb75988ebc42d30cda983308aeb6c491bdb7
