### ISSUE TITLE
Hovering of adn 'update' button, should show date of file

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1264]
do we have date info for whatever version was the last downloaded ?

alternatively we could put a time-stamp or version # in a comment in the adnauseam.txt file itself

**Comment by cqx931** [comment]
The only information we have is this last update info when hovering the clock icon.
Yes, we should put a " Last updated" time info in the adnauseam.txt file.

<img width="485" alt="screen shot 2017-10-28 at 2 05 34 pm" src="https://user-images.githubusercontent.com/3056154/32137239-f5a08b40-bbe9-11e7-8b21-e3ee235efd06.png">

**Comment by mneunomne** [comment]
@dhowe is this the last time that the adnauseam.txt was edited or downloaded?

**Comment by dhowe** [comment]
edited I believe -- basically so that we can see the date or git version of the file (when it was last committed) in the UI
then we can, for example, know if a user actually has the newest version when debugging

**Comment by mneunomne** [comment]
Reviewing this now. I was able to get the date when the `filters/adnauseam.txt` was last modified. The thing is that we need to know that information from the incoming online file, so indeed we need to append this information to the txt file itself.

What I am wondering now is: how can I append a "last_modified_date" to the file, when I need to commit that information to that same file. This would cause a loop of git changes:

file updated -> commit -> update last_modified_date -> commit -> file updated update last_modified_date -> etc...

Maybe there is a way to do this automatically through .gitattributes or something...

**Comment by dhowe** [comment]
I don't think we want to append this info to the file. Perhaps there is a way to query the git repo for the last commit time/date for that file/blob ? If not, then we should probably just show the last time it was downloaded by the extension instead.

**Comment by mneunomne** [comment]
It's possible to fetch the last day modified of the `filters/adnauseam.txt` with the following request on the github.api:

```sh
curl -s "https://api.github.com/repos/dhowe/AdNauseam/commits?path=filters%2Fadnauseam.txt" | \ jq -r '.[0].commit.committer.date'
```

but is it worth it to implement? I think it is quite reasonable to have the last date the file was downloaded instead.

**Comment by dhowe** [comment]
I think that is ok for now

**Comment by mneunomne** [comment]
Cool, so I suggest we should close this, other options don't seem worthwhile I think.
