### ISSUE TITLE
Ads not collected on markdown2pdf.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1266]
### Describe the issue
Ads not collected on markdown2pdf.com with firefox 57 and chrome

### One or more specific URLs where the issue occurs
http://markdown2pdf.com/, on either side of the page

### Steps for anyone to reproduce the issue
Load url
Observe ads hidden, but not collected

### Your settings

- OS/version: Windows 7 SP1
- Browser/version: Firefox Quantum, 57.0b9 (64-bit)
- AdNauseam version: AdNauseam v3.4.202 uBlock Originv1.13.8 
- Other extensions you have installed: uBlock Origin 1.14.16 (disabled when using adnauseum of course, just to check if ads are blocked in ublock)

**Comment by dhowe** [comment]
See also (fixed) #1265

**Comment by cqx931** [comment]
They are background ads, see https://github.com/dhowe/AdNauseam/issues/451
