### ISSUE TITLE
Remove jQuery from vault.js (use uDOM instead) 

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#127]
Should take a look first and see what this would involve. If its doable without any major rewriting, would be great as we could ditch jquery completely...

**Comment by yansh** [comment]
Seems doable.

**Comment by yansh** [comment]
Ok, I was able to replace the majority of jQuery code but not everything. It seems to work but requires serious testing on all platforms.  I think there is an issue with the "zooming" function.

**Comment by dhowe** [comment]
How to proceed?

**Comment by yansh** [comment]
Does it make sense to have partial coverage?

**Comment by dhowe** [comment]
not sure what you mean...

**Comment by yansh** [comment]
In some places I couldn't find a way to replace jQuery code. So if we cannot completely get rid of jQuery in **vault.js** does it make sense to replace parts of the code with uDom. For example, do we get any performance gains?

**Comment by dhowe** [comment]
No, but its OK to do thing incrementally... As long as you can be sure that the changes you've made don't break anything, then please submit a PR. We can further extend uDom later and then get rid of the rest of the jquery...

Actually, you can see in extract.js that I've already rewritten a few jquery function there ($is, $find, $attr, $text)... 

But why don't you keep a list in a comment at top of vault.js with remaining functions to be replaced...

**Comment by yansh** [comment]
Sounds good.

**Comment by yansh** [comment]
> Actually, you can see in extract.js that I've already rewritten a few jquery function there ($is, $find, $attr, $text).

BTW These are redundant, uDom supports them

**Comment by dhowe** [comment]
Yes, but we are not injecting uDom into content-scripts

**Comment by yansh** [comment]
> Yes, but we are not injecting uDom into content-scripts
Fair enough :)

**Comment by CyrusSUEN** [comment]
There is a problem in vault after importing the following JSON
[adnauseam-v1.330-exported-ads (contains Chinese char).json.zip](https://github.com/dhowe/AdNauseam2/files/222529/adnauseam-v1.330-exported-ads.contains.Chinese.char.json.zip)

With the following error: 
![json1](https://cloud.githubusercontent.com/assets/2461812/14585072/a5178106-0498-11e6-9e54-e57cde0f918c.png)

**Comment by dhowe** [comment]
The problem extends to ALL text-ads

**Comment by yansh** [comment]
I pushed the fix.

**Comment by dhowe** [comment]
Please submit a PR...

**Comment by yansh** [comment]
Done.

**Comment by dhowe** [comment]
The vault is a bit of a mess now. Auto-zooming is broken, as well as the item inspector...
We need to figure out a better way of testing changes before pushing them

**Comment by yansh** [comment]
Does it make sense to have some sort of integration with [Travis](https://travis-ci.org)?

**Comment by dhowe** [comment]
I use travis on most projects, but I don't know a good way to test graphics (so wouldn't have have caught these errors)...

**Comment by yansh** [comment]
Behind each graphics' test there are numbers, perhaps we can use that to devise some automatic tests. I agree, it wouldn't be a straightforward approach but might worth thinking about to avoid similar issue in the future.

**Comment by yansh** [comment]
It seems possible to do GUI testing https://docs.travis-ci.com/user/gui-and-headless-browsers/ 
But not sure if it's robust enough for our purposes.

**Comment by dhowe** [comment]
If you can figure out how to get a browser, with an addon installed, running in travis, loading specific UI views, and doing meaningful tests on them, then by all means...

**Comment by dhowe** [comment]
Meantime though, perhaps we need a list of all the jquery functions used in vault.js, then we can make sure we have alternatives for each

**Comment by dhowe** [comment]
closing for now -- revisit when we have a good d3 person
