### ISSUE TITLE
Can't enable AdNauseam 3.4.402 in Google Chrome

### ISSUE THREAD

**Issue by axzxc1236** [dhowe/AdNauseam#1275]
### Describe the issue
There is no longer have "adnauseam-<ver>.chromium.zip" in release page, so I checked out how to install AdNauseam from wiki page, I followed the guide and completed step 4 (Drag the .CRX file into the extension page), but I can't enable AdNauseam even though I enabled developer mode, and after I restarted Google Chrome it told me it disabled AdNauseam because it's not from webstore.

### One or more specific URLs where the issue occurs
chrome://extensions/

### Screenshot in which the issue can be seen
https://imgur.com/a/k8KhZ

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
I followed [this guide](https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission).
1. Download the adnauseam.chromium.CRX file from the release page **(adnauseam-3.4.402.chromium.crx)**
2. In your Chrome Browser menu, click Windows > Extensions or type chrome://extensions/ in the address bar
3. Check the Developer mode checkbox **(I checked it)**
4. Drag the .CRX file into the extension page

Can't enable Adnauseam in extension page.

### Your settings

- OS/version: Windows 10 64bit 1709
- Browser/version: Google Chrome 62.0.3202.75 64bit
- AdNauseam version: 3.4.402
- Other extensions you have installed: (a lot, but I disabled all of them and can still reproduce this issue.)

**Comment by dhowe** [comment]
I will look in to this, but it should update automatically from now on...

**Comment by cqx931** [comment]
I can't reproduce this with Google chrome 62.0.3202.75 on Mac.
@axzxc1236 Do you see the following window popup after dragging the .CRX file? After I click 'add extension', the extension is installed and enabled in chrome for me.
![image](https://user-images.githubusercontent.com/3056154/32416200-bf0c50ca-c213-11e7-9acb-6790192d68b6.png)

**Comment by superhotpepperz** [comment]
I did that with Google Chrome on Windows 10 and Chrome would not allow AdNauseam. It remained grayed out.
________________________________

**Comment by dhowe** [comment]
@cqx931 until we figure this out, we need to revert to the .zip instructions on the chrome-installation page

**Comment by axzxc1236** [comment]
@cqx931 No, there's no pop-up like this.

**Comment by dhowe** [comment]
@cqx931 until we figure this out, we need to revert to the .zip instructions on the chrome-installation page
