### ISSUE TITLE
Cannot Export Ads with more than 1400 ads collected

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam#128]
![12334](https://cloud.githubusercontent.com/assets/2461812/14480196/19ee27ac-0159-11e6-9812-630a4440e23d.PNG)

I have more than 1400 ads collected and when I try to do "Export Ads" in Options page, it shows error "Failed Network Error" with a link to https://support.google.com/chrome/answer/2898334?p=ui_download_errors&hl=en&ctx=24&rd=1
![2](https://cloud.githubusercontent.com/assets/2461812/14480217/42d7a170-0159-11e6-8456-97bba98da275.PNG)

Here is the console messages from background.html:

```
shared.js:6AdNauseam.initialized: with 1411 ads
shared.js:6 TRYING: Ad#1646(img) http://adserver.adtech.de/?adlink/657/4591526/0/16/AdId=12909785;BnId=1;itime=299471607;key=homepage;
shared.js:6 AdNauseam.export: 1405 ads to AdNauseam_Export_4.13.2016.9.19.23AM.json
```

I've no problem exporting the ads from other profile with fewer ads collected.

Here is my platform:
Windows 10 64bit
Google Chrome Canary Version 52.0.2706.0 canary (64-bit)
Latest ADN2 build at b0b3fc50bd5799e212e639bed04235fa83f2bd32

**Comment by dhowe** [comment]
Please look in the Windows event manager, and the Chrome logs. If this persists we may need to export large numbers of ads in multiple files...

**Comment by CyrusSUEN** [comment]
OK. I've extracted a Chrome log by following [the instructions](https://www.chromium.org/for-testers/enable-logging).
[chrome_debug.zip](https://github.com/dhowe/AdNauseam2/files/233124/chrome_debug.zip) (I cannot get any useful information from the log)

-------------------------------
And then I have tried limiting the size of variable ```admap``` in ```JSON.stringify(admap, null, '  ')```
The original size of my admap variable is 423 which we get the error when outputting the JSON file. And the max number of which it can successfully output the JSON file which is 310.

![size](https://cloud.githubusercontent.com/assets/2461812/14763798/164cfce4-09d4-11e6-9265-8f3b1b78f50a.png)

The JSON file log size (with 310 keys) is 1,248,158 bytes.


> we may need to export large numbers of ads in multiple files...

Agree. Maybe the attribute of 'url' is too long.

**Comment by dhowe** [comment]
Figure out what is the actual problem. Is it a long URL, or > 1400 ads, or the size of the JSON file?

**Comment by CyrusSUEN** [comment]
To reproduce this issue:
2. Import the following 2 adsets:
[268_ads.zip](https://github.com/dhowe/AdNauseam/files/310945/268_ads.zip)
[1002_ads.zip](https://github.com/dhowe/AdNauseam/files/310946/1002_ads.zip)
2. Export ads in Settings page

**Comment by dhowe** [comment]
Please check this on OS X as well

**Comment by CyrusSUEN** [comment]
> check this on OS X as well with the current (non-canary) chrome

Yes. I can confirm the problem also exists on Mac 10.11.5 and Chrome 51.

**Comment by dhowe** [comment]
Interesting. Ok, move on to another ticket

**Comment by cqx931** [comment]
Finally find out why this is not working.
According to this stackoverflow question, this is a bug in chrome that hasn't been fixed for years long.
http://stackoverflow.com/questions/16761927/aw-snap-when-data-uri-is-too-large
[chromium bug page](https://bugs.chromium.org/p/chromium/issues/detail?id=69227)

The recommended workaround is to use a blob URL instead.

This should also be the reason of the failing image download: https://github.com/dhowe/AdNauseam/issues/639

I will first try to use blob URL for json and fix the image download later.

**Comment by cqx931** [comment]
fixed the issue with blob url, tested on ad set over 2000 and works https://github.com/dhowe/AdNauseam/pull/732

**Comment by dhowe** [comment]
excellent.. can we apply this fix to the image download as well?
