### ISSUE TITLE
Serious problem with date-slider (and/or count-text)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1282]
I have 1601 ads in the vault. I extend the date-slider to both ends as far as it can go. But it still shows only 264 ads...

![screen shot 2017-11-17 at 5 57 44 am](https://user-images.githubusercontent.com/737638/32918189-8777a48c-cb5c-11e7-868b-3376325279bf.png)

ads: [AdNauseam_Export_11.17.2017.6.00.29AM.json.zip](https://github.com/dhowe/AdNauseam/files/1480396/AdNauseam_Export_11.17.2017.6.00.29AM.json.zip)

**Comment by cqx931** [comment]
This is related to my change in https://github.com/dhowe/AdNauseam/commit/247699fdd89242f17e70c617f663b52600d2d460.
Fixed it by changing the showing number back to numFound.
Tried a better way to solve the slider update after deleting ad.

Please check: https://github.com/dhowe/AdNauseam/compare/master...cqx931:master
