### ISSUE TITLE
Google Ads are not being added to the vault.

### ISSUE THREAD

**Issue by wizzwizz4** [dhowe/AdNauseam#1283]
### Describe the issue
Google Ads are not being added to the vault. Specifically, those Doubleclick ones with the AdChoices logo and the X sign from left to right on the top-right corner of the advert.

### One or more specific URLs where the issue occurs
http://www.neoseeker.com (I don't know about HTTPS.)

### Screenshot in which the issue can be seen
![Screenshot](https://user-images.githubusercontent.com/12433834/32982795-faff0c76-cc81-11e7-825f-6b518defe402.png)

### Steps for anyone to reproduce the issue
 1. Navigate to http://www.neoseeker.com
 2. Disable NoScript
 3. Manually click all of the unclicked ads. (Optional.)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 57.0 (64-bit)
- AdNauseam version: 3.4.402
- Other extensions you have installed:
    * Test Pilot
    * Stylus
    * Greasemonkey
    * OneTab
    * Textarea Cache
    * Notes (experiment)
    * HTTPS Everywhere

**Comment by dhowe** [comment]
I can't recreate this from Asia. @cqx931 ?

**Comment by cqx931** [comment]
Please check https://github.com/dhowe/uAssets/pull/75/files
- Block body background ads
- ads from locations above should be picked up most of the time. However, sometimes the ads could be dynamic ads, which could not be collected by adnauseam at current stage.

**Comment by Atavic** [comment]
`https://cdn.nsstatic.net/ns/neoseeker.com.js` has some anti features, it checks lists:
`{adblock:null,easylist:null,easyprivacy:null,acceptableads:null,ghostery:null}` then encodes URI and grabs image from `zdbb.net`

**Comment by Atavic** [comment]
Forgot to say that it has dynamic linking, too.

**Comment by dhowe** [comment]
@Atavic is there further work required here -- do you still see ads that are not collected?

**Comment by Atavic** [comment]
No, but I have other blocks in the system. I just want to tell that the JS script comes from
a big group, see [here](https://ssl-tools.net/webservers/a.zdbb.net) if interested.

**Comment by dhowe** [comment]
Ok. Please re-open if you find any other ads either visible or not collected
