### ISSUE TITLE
Still seeing error for "merged1.11.0-2/assets/assets.json?_=209896 404 (Not Found)"

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1285]
GET https://raw.githubusercontent.com/dhowe/AdNauseam/merged1.11.0-2/assets/assets.json?_=209896 404 (Not Found)

<img width="1369" alt="screen shot 2017-11-21 at 6 34 18 pm" src="https://user-images.githubusercontent.com/737638/33064997-ef0234be-ceea-11e7-960c-79a19fb645e8.png">

**Comment by cqx931** [comment]
Have you tried to delete the old file and reinstall the new one? The link should already be removed from the current master.

**Comment by cqx931** [comment]
@dhowe  Do you still see this?

**Comment by dhowe** [comment]
Lets close for now and see if it recurs
