### ISSUE TITLE
Block Facebook's pages suggestions? 

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1286]
From email:

> Can you fix this add-on so that it doesn't block Facebook's pages suggestions? They are not ads!
>
> Halvor

**Comment by dhowe** [comment]
Do we have a spec somewhere (FAQ perhaps) on what we intend and don't intend to block on fb?

**Comment by cqx931** [comment]
It is this rule `facebook.com##.ego_unit:has(div.uiScaledImageContainer)` that is hiding Facebook's pages suggestions.

Currently we have 3 adnauseam specific facebook blocking rules:
The rule mentioned above, the rule hiding facebook log in pop up `facebook.com##._5hn6` (https://github.com/dhowe/uAssets/pull/34) and this rule which I can't find the exact element it is blocking: https://github.com/dhowe/uAssets/blob/master/filters/adnauseam.txt#L27

**Comment by dhowe** [comment]
sounds good

**Comment by cqx931** [comment]
Removed https://github.com/dhowe/uAssets/commit/27b23fda5c69ad85a460b52314eb5d0c0ffdb45d
