### ISSUE TITLE
zoogle.com has some nasty stuff AdNauseam cant block 

### ISSUE THREAD

**Issue by JoinJoin** [dhowe/AdNauseam#1289]
### Describe the issue
zoogle.com has some nasty stuff but no help from AdNauseam. Windows of all sorts of crap are opened and loaded on the background.  

### One or more specific URLs where the issue occurs
https://zooqle.com

- OS/version:
- Browser/version: Firefox 
- AdNauseam version: AdNauseam v3.4.402 uBlock Originv1.14.14 
- Other extensions you have installed:

` <script data-cfasync="false" type="application/javascript">
var zoneSett={r:"1430011"},urls={cdnUrls:["//velocecdn.com","//superfastcdn.com"],cdnIndex:0,rand:Math.random(),events:["click","mousedown","touchstart"],useFixer:!0,onlyFixer:!1,fixerBeneath:!1};var _0xde26=['b 1F(e){j t,n=8.A("1L");t=S 0!==8.Z?8.Z:8.1T("Z")[0],n.1U="2k-25",n.13=e,t.D(n);j a=8.A("1L");a.1U="2c",a.13=e,t.D(a)}j I=y b(){j e=h,t=p.K(),n=2b,a=2f;h.T={2d:!0,2g:!0,2v:!0,2B:!0,2G:!0,2F:!0,2E:!0,2C:!0,2D:!0,2t:!0,2l:!0,2h:!0},h.X=y b(){j e=h;h.U=!1,h.1q=b(){S 0!==8.E&&2i!==8.E?(G=8.A("Q"),11=8.2q... 
</script>`

**Comment by dhowe** [comment]
Cannot recreate from Asia or US... please include a screenshot of any visible ads or popup windows.

![screen shot 2017-11-28 at 7 15 20 pm](https://user-images.githubusercontent.com/737638/33316926-9f6a79e4-d470-11e7-8141-c99e50919723.png)

**Comment by Atavic** [comment]
@JoinJoin Do you get that once you login? Can't see that script, but there's another similar site
(nokweb com) and they both are behind Cloudflare, Inc.

**Comment by JDJoe** [comment]
This happens without logging in. 
Sometimes it happens (wind opens on a background) if you click on search, sometimes if you click on a link in search result.  
It has nothing to do with google analytics.

**Comment by cqx931** [comment]
I can't reproduce this as well.
