### ISSUE TITLE
Verify that all test URLs use the proper test server

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1290]
### Describe the issue

If you find any that go elsewhere, list them here ...

**Comment by cqx931** [comment]
The following test cases need to be copied to rednoise server: 
http://lab-lamp.scm.cityu.edu.hk/adntest/block.html
http://lab-lamp.scm.cityu.edu.hk/adntest/dynamic_iframe_firefox.html
http://lab-lamp.scm.cityu.edu.hk/adntest/effTestPage.html
http://lab-lamp.scm.cityu.edu.hk/adntest/incomingCookies.html
http://lab-lamp.scm.cityu.edu.hk/adntest/incomingCookies_exceptionAllow.html
http://lab-lamp.scm.cityu.edu.hk/adntest/urlList.html

I'm not sure whether we still need the following test cases:
http://lab-lamp.scm.cityu.edu.hk/adntest/cross-domain-iframe.html (need to adjust the content)
http://lab-lamp.scm.cityu.edu.hk/adntest/exception.html
http://lab-lamp.scm.cityu.edu.hk/adntest/iframe-distinguish.html
http://lab-lamp.scm.cityu.edu.hk/adntest/iframeRelativeTarget.html
http://lab-lamp.scm.cityu.edu.hk/adntest/redirect-notice.html
http://lab-lamp.scm.cityu.edu.hk/adntest/simple2.html
http://lab-lamp.scm.cityu.edu.hk/adntest/test.html
http://lab-lamp.scm.cityu.edu.hk/adntest/triple-dyn.html
http://lab-lamp.scm.cityu.edu.hk/adntest/triple-dyn2.html

**Comment by dhowe** [comment]
Done
