### ISSUE TITLE
AdNauseam Prevents Page Displaying Properly

### ISSUE THREAD

**Issue by AdrianRepRap** [dhowe/AdNauseam#1292]
### Describe the issue

In Chrome, my homepage http://adrianbowyer.com/ displays fine if I disable AdNauseam for it. If I enable it however most of the content disappears. There are no ads on the page.

### One or more specific URLs where the issue occurs

http://adrianbowyer.com/

### Screenshot in which the issue can be seen

http://adrianbowyer.com/images/adnausprob.png

Shows AdNauseam disabled (top) and enabled (bottom).

### Steps for anyone to reproduce the issue

Simply load the page in Chrome with AdNauseam disabled, and then again with it enabled.

### Your settings

- OS/version: Ubuntu 16.04.2 64 bit
- Browser/version: Chrome Version 57.0.2987.110 (64-bit)
- AdNauseam version:  3.4.402
- Other extensions you have installed: Privacy Badger (disabled for the test).

**Comment by CalderMarshall** [comment]
This bug is also present when viewing the firebase console in Chrome on the latest version with AdNauseam enabled.  My browser and extension are both on the latest version.  

![screen shot 2017-12-15 at 12 00 28 pm](https://user-images.githubusercontent.com/24924047/34052278-ac2865de-e18f-11e7-929c-e4b07df1e3b3.png)

**Comment by dhowe** [comment]
This is not really an AdNauseam issue, it is a list issue. The main div on your site has 

![image](https://user-images.githubusercontent.com/737638/34053337-5df7e66a-e201-11e7-88db-c5a646bd7c68.png)

![screen shot 2017-12-16 at 1 32 29 am](https://user-images.githubusercontent.com/737638/34053343-60455024-e201-11e7-848e-dafcfba0be13.png)

**Comment by dhowe** [comment]
@CalderMarshall can you clarify your comment? do you have a similar problem on another page, and if so, what is the URL ?

**Comment by CalderMarshall** [comment]
I think I have experienced the css bug on another url, but I cannot recall it directly.  I am positive the bug exists when visiting the firebase console as a logged in user on the latest version of chrome with AdNauseam enabled.  I disabled all of my extensions, and enabled AdNauseam and refreshed the page, the css bug came back.  I wouldn't pass off the notion that a google developer is aware of the extension which they do not support and breaks the firebase css on purpose, but that's just a hunch.

**Comment by dhowe** [comment]
Can you include _specific_ steps below to recreate this error (include any installs or logins)? thanks

**Comment by CalderMarshall** [comment]
Sure.  macOS High Sierra 10.13.2.  
AdNauseam 3.4.402 installed on November 21, 2017.  

Navigate in Chrome to https://console.firebase.google.com/u/0/  
Contemplate life while looking at beautiful CSS pictured above.
Attempt empty cache and hard reload after switching between google accounts.
CSS bug remains.  
Open AdNauseam toolbar from extension icon or from chrome extension manager. 
Disable AdNauseam.  Refresh page.  
CSS bug gone.

I cannot do a logged out test, the firebase console is not accessible without user authentication.

**Comment by dhowe** [comment]
Here's what I see when I log into google and follow your instructions above:

![screen shot 2017-12-17 at 11 06 31 pm](https://user-images.githubusercontent.com/737638/34080821-fac8a12c-e37e-11e7-8e56-6fbd89041c81.png)

**Comment by CalderMarshall** [comment]
@dhowe thanks for all the responses, I don't know how my install created this bug.  I removed the extension and re-downloaded and installed, and the error is gone.  Sorry about the confusion.

**Comment by dhowe** [comment]
no worries
