### ISSUE TITLE
[web-ext] DNT header is not sent

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1295]
Tested on master branch, both web requests and ad visit

**Comment by cqx931** [comment]
From 1.14.0 uBlock has deleted the old vAPI.net in `vAPI-background.js` and use the new vAPI.net in `vapi-webrequest.js` for this.
There is [`onBeforeSendHeaders` function](https://github.com/dhowe/AdNauseam/blob/master/platform/chromium/vapi-webrequest.js#L209) for chrome, but the same does not exist for webext.
See:
https://github.com/dhowe/AdNauseam/blob/master/platform/webext/vapi-webrequest.js

**Comment by dhowe** [comment]
Looks good, but lets make sure to retest in release testing
