### ISSUE TITLE
[3.4.450 Firefox-webExt] µb.adnauseam.onPageLoad() is not called if an ad is clicked from the menu

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1301]
I found this strange behavior when I tested The new text tag "clicked by user".
When the web request type is main_frame,  `OnBeforeRootFrameRequest` should run.
And in Firefox WebExt, this function strangely only runs to https://github.com/dhowe/AdNauseam/blob/master/src/js/traffic.js#L380 and stops going down.
Therefore, the line `µb.adnauseam.onPageLoad(tabId, requestURL);` is never called, and a newpage won't be correctly registered.
https://github.com/dhowe/AdNauseam/blob/master/src/js/traffic.js#L418

**Comment by dhowe** [comment]
good catch... i will investigate

**Comment by cqx931** [comment]
Sorry, I should have frame this in a better way...
This issue is only valid if an ad click is attempted from the menu. And it is working as expected if an url is entered from the address bar/ or an ad clicked from the main browser window.

What I noticed is that if an ad is clicked from the menu, it would be opened in a new browser window instead of the old one, and that might be the reason causing this.

**Comment by dhowe** [comment]
I still can't recreate this, at least not in the debugger:

![image](https://user-images.githubusercontent.com/737638/34090044-37d4c918-e3ef-11e7-9a0f-6741ebe9e05c.png)

**Comment by cqx931** [comment]
I can't reproduce this anymore, close for now
