### ISSUE TITLE
[3.4.450] Auto update is not working as expected.

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1303]
All platforms
To reproduce:
1. Go to start.js and change this line : "µb.scheduleAssetUpdater(µb.userSettings.autoUpdate ? 7 * 60 * 1000 : 0);" to "µb.scheduleAssetUpdater(µb.userSettings.autoUpdate ? 10 * 1000 : 0);"
2. Go to background.js and change autoUpdateAssetFetchPeriod to 1
3. Rebuild AdNauseam
4. Delete and reinstall AdNauseam

**Comment by dhowe** [comment]
Please test this on uBlock before we try to fix it in adn

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/blob/master/src/js/assets.js#L989
The auto update triggering process need to be updated, not an issue in autoupdate itself, close.
