### ISSUE TITLE
[3.4.450 Firefox-webExt] No DNT header for Ad Visits

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1304]
Fixed, please recheck...

![image](https://user-images.githubusercontent.com/737638/34095577-e4c1dc84-e40c-11e7-8b64-17297ead99d8.png)

**Comment by cqx931** [comment]
I still don't see any DNT header after the latest commit.

**Comment by dhowe** [comment]
How are you inspecting network requests (and are you looking at request headers for the correct request) ? Here details of my test-case:

AdNauseam commit c3aff3834
Firefox nightly 59.0a1 (2017-12-17) (64-bit)
OSX 10.13

Below you can see the request to the rednoise simple ad test, then the request to 

![image](https://user-images.githubusercontent.com/737638/34151539-85487d46-e4e6-11e7-8e7c-3a775d23ecc7.png)

**Comment by cqx931** [comment]
Same commit but on Firefox 58.0b11 let me try 59.0a1 and see...

**Comment by dhowe** [comment]
I'd be very surprised if that made a difference (you have DNT clicking and/or hiding enabled, yes?)

**Comment by cqx931** [comment]
Yes, you are right, the results are the same.
What I noticed is that the current commit works on http://rednoise.org/adntest/simple.html. However it doesn't when I check it on nytimes.com or on http://lab-lamp.scm.cityu.edu.hk/adntest/simple.html

**Comment by cqx931** [comment]
Example from nytimes.com
![image](https://user-images.githubusercontent.com/3056154/34153578-6d9d19e2-e467-11e7-8360-899c98120622.png)

**Comment by dhowe** [comment]
Let me check...

**Comment by cqx931** [comment]
Fixed: https://github.com/dhowe/AdNauseam/pull/1305
nytimes.com cases are verified by now. This ticket can be closed after the above PR being verified.
