### ISSUE TITLE
Won't apply changes in "My Filters"

### ISSUE THREAD

**Issue by MrDemocracy** [dhowe/AdNauseam#1309]
### Describe the issue
When I remove a filter line from "My Filters" and click apply, the filter is still there when I refresh the AdNauseam settings page.
I have tried to export the filter list and change the exported file before importing it again, but it didn't work.

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

- OS/version: macOS 10.13.2 (17C88)
- Browser/version: Google Chrome 63.0.3239.84 (Official Build) (64-bit)
- AdNauseam version: v3.5.101

**Comment by cqx931** [comment]
I can't reproduce this issue with the above setting. 
I tried the following steps and things work well for me. 
1.Adding a new filter/remove a filter line
2.Click "Apply Changes" button
3.Refresh the page
4.The change has been updated

**Comment by MrDemocracy** [comment]
Reinstalling AdNauseam solved the problem.
