### ISSUE TITLE
Create a wiki entry for after release todo list

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1310]
1. Upload to Firefox and Opera add-on store
1. Create a .crx version using the adnauseam key (shared among developers)
2. Update the website (version number in 3 locations)
3. Make sure that the version # and link in the following page is updated: ````http://rednoise.org/adnauseam/updates.xml````
4. Install a previous version in chrome and check that auto-update works

[updated]

**Comment by dhowe** [comment]
I've updated your list above...

**Comment by cqx931** [comment]
Added to: https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#after-new-release
close
