### ISSUE TITLE
Video ads visible on SCMP

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1313]
Black/white autoplay video ad

![image](https://user-images.githubusercontent.com/737638/34406049-d8566004-ebf1-11e7-9fba-e7263e2a85df.png)

**Comment by dhowe** [comment]
I added the following 2 rules: please verify

````
www.scmp.com##*[class^="teads"]
www.scmp.com##*[id^="teads"]

**Comment by cqx931** [comment]
With an vpn connecting to HK, I still have issues recreating this. I'm going to revisit this later.
