### ISSUE TITLE
Add notification for private/incognito mode 

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1316]

**Comment by cqx931** [comment]
Are we going to use the same notification system as we have now for private/incognito mode? As a warning? 

What message is going to be displayed?
"You are browsing in private/incognito Mode, AdNauseam won't collect/click any ad for you."

**Comment by dhowe** [comment]
First priority is 'tracker blocking' bc when tracker blocking is on (which it would be for most of our users), ADN doesn't do anything... and this results in lots of false bug reports. and yes, this should just be another notification... I have to think about incognito

**Comment by dhowe** [comment]
(blocked on #1464)

**Comment by dhowe** [comment]
@cqx931 I believe this can be closed?

**Comment by cqx931** [comment]
yes
