### ISSUE TITLE
Admiral Anti-Adblocker

### ISSUE THREAD

**Issue by LtPatterson** [dhowe/AdNauseam#1329]
### Describe the issue
Can't get around this anti-adblocker regardless of filter combinations.

### One or more specific URLs where the issue occurs
https://www.washingtontimes.com/news/2018/feb/19/trump-motorcade-driver-stopped-after-gun-found-bag/

Nearly any Washington times link.
### Screenshot in which the issue can be seen
https://i.imgur.com/yQDxCUh.png

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
Visit site and wait about 3 seconds.
### Your settings

- OS/version: Windows 10
- Browser/version: FF Quantum 58.0.2
- AdNauseam version: 3.5.101
- Other extensions you have installed: Ghostery (listing site as trusted still doesn't work), a few other extensions which would have no impact on this issue.

**Comment by dhowe** [comment]
I can't recreate this from my location. @cqx931 ? 
Where are you browsing from?

**Comment by LtPatterson** [comment]
Only works if I trust the site via ghostery. Guess I'll close this out. Annoying that all of those ad tracking tags still load, but are blocked anyway by AdNauseam I suppose.
