### ISSUE TITLE
Google text ads are not rendered in Firefox?

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1337]
Ex:
Ads are rendered in chrome, but not Firefox(without any plugin)
So far I only see this on google search result, not on other search engines or sites.
https://www.google.com/search?ei=kW-ZWrX7L8aS0wKlxrD4CA&q=credit+card&oq=credit+card

Firefox version: 59.0b13

**Comment by dhowe** [comment]
I see ads in Firefox on this page (with ADN disabled) and then they are hidden with ADN on... What exactly is the issue here?

**Comment by cqx931** [comment]
Yes, I don't see this issue anymore. Close for now.
