### ISSUE TITLE
Video ads on the Economist

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1341]
https://www.economist.com/news/united-states/21739167-even-used-legitimately-it-powerful-intrusive-political-tool-facebook-scandal

![image](https://user-images.githubusercontent.com/737638/37813778-b7474142-2ea1-11e8-8b9f-36c8798a7621.png)

**Comment by dhowe** [comment]
UPDATE: I added the following rule:

    www.economist.com##*[class*="teads"]

Pls double-check

**Comment by cqx931** [comment]
Verified
