### ISSUE TITLE
Ads visible on the weather channel

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1343]
https://weather.com/weather/hourbyhour/l/HKXX0170:1:HK

![image](https://user-images.githubusercontent.com/737638/38174463-04fdf088-3600-11e8-8480-b0990c367b01.png)

**Comment by cqx931** [comment]
hidden rules:
https://github.com/dhowe/uAssets/pull/78

The parser can't collect them, since they are cross-domain iFrames
![image](https://user-images.githubusercontent.com/3056154/42628435-6b3d9e1e-85d0-11e8-953b-dc2624b47e00.png)

**Comment by dhowe** [comment]
how are these handled on ublock ?

**Comment by cqx931** [comment]
I'm not sure whether this will be an issue for uBlock, as they will block most of the script for iframes anyway.
What I found unusual here is that there are actually hidden rules for these ads in EasyList
`##iframe[id^="google_ads_iframe"]`
But they are not hidden even though the element is processed by AdNauseam

**Comment by dhowe** [comment]
does the rule fire at all?

**Comment by cqx931** [comment]
It is not in the logger, but the fact that adnauseam can process it, it means that the rule is fired in the background and at least get processed to this stage:
https://github.com/dhowe/AdNauseam/blob/master/platform/chromium/vapi-usercss.js#L425

**Comment by dhowe** [comment]
status?

**Comment by cqx931** [comment]
I don't see any visible ads any more
![image](https://user-images.githubusercontent.com/3056154/52877131-296cea00-3127-11e9-9850-520997240b48.png)
