### ISSUE TITLE
ca.finance.yahoo.com leads to  false "Microsoft Security Alert" page 

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1345]
URL: ca.finance.yahoo.com

From email: "This has happened to me two or three times, and only on Yahoo Canada Finance... the auto click has linked to a false "Microsoft Security Alert" page that takes over the whole browser and I have to close it through the task window. I'll be on the page for a minute or so and I can tell ADN is clicking the ads, than all of the sudden a fake red "security warning" page will take over."

Chrome with Windows 10

![20180402_082147](https://user-images.githubusercontent.com/737638/38218760-72771256-3705-11e8-8696-6f5c443f1862.jpg)

![20180402_082156-1](https://user-images.githubusercontent.com/737638/38218761-72a52074-3705-11e8-9081-078d634444ba.jpg)

**Comment by mneunomne** [comment]
Website is working fine now apparently, probably outdated, closing for now.
