### ISSUE TITLE
[3.5.101 Firefox] No ads collected from pages or Failed

### ISSUE THREAD

**Issue by unexperiensd** [dhowe/AdNauseam#1346]
### Describe the issue
AdNauseam shows "No Ads collected on this page (showing recent)" in websites that clearly have ads.
I have tested this in the following sites:
www.foxnews.com
www.reuters.com
www.spiegel.de

In all of the websites the ads are correctly not displayed, but AN does not collect any of them.
Even if disabled or whitelisted, the ads do not appear (tested this with reuters.com). The same happens with youtube.

AN looks like it recognizes ads on Facebook, still il fails most of them. It looks like it manages to collect pretty good suggested groups and pages.

### Screenshot in which the issue can be seen
Facebook:
![scrn](https://user-images.githubusercontent.com/38072190/38306433-cfe639ec-3810-11e8-91b6-6e6bf61152ff.png)

Settings:
- OS/version: Windows 10 (happens also on Ubuntu 16.04. Firefox is synced)
- Browser/version: Firefox 59.0.2 (64-bit)
- AdNauseam version: 3.5.101
- Other extensions you have installed: 
TLS 1.3 gradual roll-out, Bloody Vikings!, Blur, Data Selfie, Decentraleyes, DuckDuckGo Privacy Essential, Facebook Container, Facebook Direct Links, FoxyProxy Standard, Greasemonkey, HTTPS Everywhere, Kee, Keepa - Amazon Price Tracker, NoScript, Proxy Docile, TrackMeNot, I don't care about your likes, uBlock Origin (disabled)

I have screenshot the modified rows in the about:config page. If you think helpful or necessary I can upload one or more of them

### Your location/country
Portugal

Thank you for your work.

**Comment by dhowe** [comment]
Thanks for the report. I wonder if you could try the same tests with only AdNauseam enabled? My guess is that some of the other addons may be conflicting (NoScript is one candidate for sure)

**Comment by unexperiensd** [comment]
I've done the test as you suggested, and the results were exactly the same.

I have even disabled AN too, and ads in the aforementioned websites are still not displaying. 
In facebook.com I get the same collection of failed/visited ads.

Maybe this has something to do with some about:config settings (I have modified some of them according to the recommendations of privacytools.io)

Here's screenshots of all the options that are not default:

![confg1](https://user-images.githubusercontent.com/38072190/38361789-dfb27d5e-38ce-11e8-83fa-de9c25ab2852.PNG)
![confg2](https://user-images.githubusercontent.com/38072190/38361790-dfe3f064-38ce-11e8-8b65-35764f44e0c6.PNG)
![confg3](https://user-images.githubusercontent.com/38072190/38361791-e0130674-38ce-11e8-80e2-ed2a708355b9.PNG)
![confg4](https://user-images.githubusercontent.com/38072190/38361792-e047aad2-38ce-11e8-947c-e73da75ced10.PNG)
![confg5](https://user-images.githubusercontent.com/38072190/38361788-df7abfae-38ce-11e8-9105-e44127dcf502.PNG)
![confg6](https://user-images.githubusercontent.com/38072190/38361825-fdd38486-38ce-11e8-8d32-f8640a2b0f48.PNG)
![confg7](https://user-images.githubusercontent.com/38072190/38361826-fe07a05e-38ce-11e8-8045-e223b0a21e55.PNG)
![confg8](https://user-images.githubusercontent.com/38072190/38361827-fe391ad0-38ce-11e8-9694-349f42bb3110.PNG)
![confg9](https://user-images.githubusercontent.com/38072190/38361836-051a0332-38cf-11e8-8563-4aae47e80295.PNG)
![confg10](https://user-images.githubusercontent.com/38072190/38361835-04edcf2e-38cf-11e8-9fc5-0a56d0cbf4af.PNG)

I have deleted, along with the sensitive informations, most if not all of the ...ID. If those strings were necessary I can provide them.
Thank you.

**Comment by dhowe** [comment]
Just to clarify, when you disable ALL addons (including AdNauseam) the ads are still not visible?

**Comment by unexperiensd** [comment]
Yes, with that profile, even with ALL addons disabled, the ads were still not visible.

I have done some tests with a new profile.

The websites I have been using were:

- reuters.com
- foxnews.com
- cnn.com
- bbc.co.uk

In each website I have verified the presence of ads.

First test: just AN
Ads found:
- reuters: 4
- fox: 4
- cnn: 4
- bbc: 1
All visited: yes

AN + Privacy Badger
- reuters 2
- fox: 6
- cnn: 0
- bbc: 0
All visited: yes.

AN +DuckDuckGo Privacy Essentials
All websites gave 0 ads detected.

AN + Blur
All websites gave 0 ads detected.

AN + NoScript*
- reuters: 0
- fox: 6
- cnn: 0
- bbc: 1
*  for each page the option "Temporarily allow all this page" was clicked, even though some scripts were kept blocked.

In all the cases AN was correctly detecting and visiting all ads, once the extra addon was disabled.

I forgot to check Decentraleyes, maybe I will test it later.
