### ISSUE TITLE
[Firefox only] Incorrect parsing of certain filters

### ISSUE THREAD

**Issue by Australis86** [dhowe/AdNauseam#1348]
### Describe the issue
Opening the eBay homepage or the "My eBay" summary page shows the page loading, but briefly after it is blanked out. I disabled all my addons and tested one-by-one and it appears to be AdNauseum that is the key addon.

It seems that when a particular resource is blocked, eBay is editing the style attribute on the body tag and adding a "hidden" string, which hides the entire page (based on a CSS rule in inception.css).

eBay's scripts are rather obfuscated, so it is difficult to tell where exactly the issue lies. I think I have ruled out the JS and XHR requests to 

- ebaystatic.com
- tie.247-inc.net
- cloudfront.net
- adobedtm.com

as allowing each of these via the filters settings does not resolve the issue.

### One or more specific URLs where the issue occurs
https://www.ebay.com.au/

### Screenshot in which the issue can be seen
![ebay adblocking countermeasures results](https://user-images.githubusercontent.com/17158704/39049196-d744167a-44e3-11e8-8af3-eefd99ad0c59.png)

### Steps for anyone to reproduce the issue
Navigate to the website in Firefox with AdNauseum installed.

### Your settings
- OS/version: Windows 10 with latest patches
- Browser/version: Firefox 59.0.2
- AdNauseam version: 3.5.101
- Other extensions you have installed: Avast Online Security, Firefox Multi-Account Containers, DuckDuckGo Privacy Essentials & Update Scanner

### Your location/country
Australia

**Comment by cqx931** [comment]
Hi @Australis86 , thank you for reporting this issue.
I looked into it and it doesn't seem like any ad-blocking countermeasure from ebay to me. This issue doesn't exist for AdNauseam in chrome and by comparing the logger from the chrome version and the firefox version, I found that AdNauseam in Firefox is applying the following rule to the ebay homepage:
`##[style*="base64"]`
It is this rule that accidentally parsed the body tag in ebay (see "base64" in background image url), which caused the issue you report here.
![image](https://user-images.githubusercontent.com/3056154/39068877-de2b80a0-44ab-11e8-86b8-8df5ab49cdb8.png)

However, when I trace back to easylist, where this hiding rule comes from, I found that this rule should not apply to ebay at all, which is how adnasueam(chrome version) and ublock handles ebay. So I think there is something tricky happening when adnauseam parses the rules that makes it to apply `##[style*="base64"]` on ebay.

```
,101greatgoals.com,activistpost.com,allthetests.com,ancient-origins.net,androidcentral.com,batmanstream.com,bibme.org,biology-online.org,blacklistednews.com,breakingisraelnews.com,chicagotribune.com,citationmachine.net,codeproject.com,collectivelyconscious.net,colourlovers.com,connectedly.com,convert-me.com,convertcase.net,crackberry.com,dailygalaxy.com,datpiff.com,destructoid.com,dictionary.com,diffen.com,drudgereport.com,dwatchseries.to,easybib.com,eurweb.com,freewarefiles.com,fullmatchesandshows.com,gelbooru.com,genfb.com,gorillavid.in,grammarist.com,imagepearl.com,imore.com,indiewire.com,jerusalemonline.com,jewsnews.co.il,kizi.com,kshowonline.com,magnetdl.com,mmorpg.com,movpod.in,mywatchseries.to,nba-stream.com,newsarama.com,nydailynews.com,omgcheckitout.com,onwatchseries.to,opensubtitles.org,playbill.com,pocketnow.com,readmng.com,roadracerunner.com,robinwidget.com,rule34.xxx,sh.st,teslacentral.com,tetrisfriends.com,the4thofficial.net,thebarchive.com,thefreethoughtproject.com,thewatchseries.ac,trifind.com,unblckd.org,usherald.com,veteranstoday.com,videotoolbox.com,vrheads.com,watchseries.sk,windowscentral.com,wnd.com,xda-developers.com##[style*="base64"]
```

**Comment by cqx931** [comment]
Please update your adnauseam.txt filter.
I just made a quick fix to adnauseam.txt, as this issue is causing a lot of trouble now. To solve the real issue behind, I need some time to look into this later.

**Comment by cqx931** [comment]
The chunk of filters that might all get parsed as universal filters from the latest update:
<img width="893" alt="screen shot 2018-04-20 at 5 28 02 pm" src="https://user-images.githubusercontent.com/3056154/39074847-0ccdb152-44c1-11e8-8f79-cd51ec872492.png">

**Comment by cqx931** [comment]
I just noticed that Easylist changed the syntax for these filters(syntax error?), so the troubles disappear now even if I disable adnauseam.txt. I will leave the temporary fix there for a while and we can remove them afterwards.

**Comment by Australis86** [comment]
Thanks; I had difficulty working out where the issue was coming from. Looks like the fix has resolved it.

**Comment by mneunomne** [comment]
Fixed. Closing
