### ISSUE TITLE
Youtube videso no longer visible.

### ISSUE THREAD

**Issue by Clydesdale404** [dhowe/AdNauseam#1349]
Videos, either embedded or on youtube, are no longer visible while audio still plays.  This is one of several issues that has popped up in the last day or two.   I suspect this may be something Google is doing to combat the plugin on other browsers since the issues seem to revolve around google services.  If you un-check "Hide Ads" from the AN plugin videos play as normal .

### One or more specific URLs where the issue occurs
Any youtube video reproduces the issue.  Does not appear to affect other sites like Dailymotion etc. 

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/38569237/39067437-a970a854-44a6-11e8-9fae-7e7f2f18eeee.png)

### Steps for anyone to reproduce the issue
I assume it has to do with the latest version of Firefox Quantum and or changes made by google.

### Your settings

- OS/version: Windows 10 Home.  Version 1709 Build 16299.371
- Browser/version: Firefox Quantum 59.0.2 64bit
- AdNauseam version: AdNauseam v3.5.101 uBlock Originv1.14.14 
- Other extensions you have installed: Amazon SMILE, F.B. Purity, Facebook Container, Greasemonkey, Imagus, LastPass, RES, FF Test Pilot, Tree Style Tabs

### Your location/country
US

**Comment by cqx931** [comment]
close for similar issues

**Comment by Clydesdale404** [comment]
![image](https://user-images.githubusercontent.com/38569237/39072475-a33c050c-44b8-11e8-9d30-bb0ab17b063e.png)

Let me know if you want me to grab it all and export it to file.

**Comment by cqx931** [comment]
`##[src*=blob]` This is not showing in my browser, but it seems like a very similar problem caused by another filter. Can you try to add `#@#[src*=blob]` to My Filters, and see whether that solve your issue?

**Comment by cqx931** [comment]
If that doesn't help, please type `##` in the filter of the logger, so that you can make a screenshot of all the hidden elements like the image below:
![image](https://user-images.githubusercontent.com/3056154/39073369-897dfece-44bb-11e8-8fb6-8db73c4dda6b.png)

**Comment by Clydesdale404** [comment]
No luck on the addition to filters.  Here's the SS of the logger:

![image](https://user-images.githubusercontent.com/38569237/39073584-44b0c2c6-44bc-11e8-8ce5-a75aec33f62b.png)

**Comment by cqx931** [comment]
ah, sorry, I think I missed ":" in my filter, it's really vague in the image. Do you mind to try this again`#@#[src*=blob:]`?

**Comment by cqx931** [comment]
I just made another fix in https://github.com/dhowe/uAssets/commit/56eb34647e19a544d549113a8c69c1f707b1e419.
Please update the AdNauseam Filters again and see whether that helps.

**Comment by cqx931** [comment]
You might also want to update your Easylist filter, as I notice that they have fixed a few rules that might cause all the troubles here.

**Comment by Clydesdale404** [comment]
That did it!  Working now.
