### ISSUE TITLE
Login Fields dissaper when active 

### ISSUE THREAD

**Issue by Clydesdale404** [dhowe/AdNauseam#1351]
### Describe the issue
ID and Password Fields vanish when "Hide Ads" is active. Initially they are there until you click on one, then they vanish.

### One or more specific URLs where the issue occurs
Examples below are Think Geek
https://www.thinkgeek.com/brain/account/login.cgi
https://www.reddit.com/login

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/38569237/39068064-026c0794-44a9-11e8-8c31-5d3e93a7ba0d.png)

https://gyazo.com/6cad1b65e5f880414f8179980147a273
![image](https://user-images.githubusercontent.com/38569237/39068127-336bffac-44a9-11e8-8397-4c600cfa6e1a.png)

### Steps for anyone to reproduce the issue
Attempt to log into a website when AN is actively hiding adds. 

### Your settings

- OS/version: Windows 10 Home, Version 1709, Build 16299.371
- Browser/version: FireFox Quantum 59.0.2 64 Bit
- AdNauseam version: AdNauseam v3.5.101 uBlock Originv1.14.14 
- Other extensions you have installed: Amazon SMILE, FB Purity, Facebook Container, Greasemonkey, Imagus, LastPass, RES, FF Test Pilot, Tree Style Tab

### Your location/country
US

**Comment by cqx931** [comment]
close for similar issues
