### ISSUE TITLE
Twitch and Youtube only play audio when AdNauseam is enabled

### ISSUE THREAD

**Issue by Nairda** [dhowe/AdNauseam#1352]
### Describe the issue
Twitch and Youtube only play audio when AdNauseam is enabled.  When AdNauseam is disabled the videos play properly.

### One or more specific URLs where the issue occurs
https://www.youtube.com/
https://www.twitch.tv/

### Steps for anyone to reproduce the issue
Have Adnauseum enabled and try to watch videos on twitch or youtube

### Your settings

- OS/version:
- Browser/version:
- AdNauseam version:
- Other extensions you have installed:

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
Vermont, USA

**Comment by cqx931** [comment]
Please update your Adnauseam filters(the first filter under 3rd-party-filters) or try to update EasyList. It should fix this issue.

**Comment by Nairda** [comment]
Looks like updating the filters worked for me.  Thank you!!!
