### ISSUE TITLE
Videos are blank/black

### ISSUE THREAD

**Issue by bunnybooboo** [dhowe/AdNauseam#1357]
### Describe the issue
Videos showing blank/black screen. Videos also fail to autostart, staying stuck at 0:00.

### One or more specific URLs where the issue occurs
Youtube.com, Vimeo.com, https://www.reddit.com/domain/v.redd.it/

### Screenshot in which the issue can be seen
![screenshot from 2018-04-24 07-50-40](https://user-images.githubusercontent.com/5793295/39170667-e0dcd3e8-478b-11e8-8fcd-10dfc1ad4d17.png)
![screenshot from 2018-04-24 07-58-37](https://user-images.githubusercontent.com/5793295/39170978-f51c4d10-478c-11e8-9e0a-83c84a620048.png)

### Steps for anyone to reproduce the issue
All videos whether emedded or directly on the sites. If I skip ahead the video will begin playing the audio only.

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox Nightly 61 build id 20180424013604
- AdNauseam version: 3.5.101

### Your location/country
GB

**Comment by bunnybooboo** [comment]
Screenshot with AdNauseam disabled
![screenshot from 2018-04-24 08-04-30](https://user-images.githubusercontent.com/5793295/39171322-df0b06dc-478d-11e8-9107-31686c1980ee.png)

**Comment by cqx931** [comment]
If you are still having this issue, please update your `Adnauseam filters`(the first filter under 3rd-party-filters) for a temporary fix. @bunnybooboo

**Comment by bunnybooboo** [comment]
Seems to have since corrected.

Firefox Nightly build id 20180427102245..

![screenshot from 2018-04-27 22-31-42](https://user-images.githubusercontent.com/5793295/39386095-7c817c8a-4a62-11e8-904d-a7cb8356dd6d.png)
