### ISSUE TITLE
Installation issues on Vivaldi browser 

### ISSUE THREAD

**Issue by olekhov** [dhowe/AdNauseam#1361]
### Installation issues on Vivaldi browser 

Greetings.
I am trying to install AdNauseam as it is said in "Installation": 

> For other chromium-based browsers simply download the latest .CRX file and drag into your browser window.

I have downloaded apropriate CRX file to my "Downloads".
It is unclear what do you mean by "drag into your browser window".
Using some sort of File Manager? I do not know about them at all, my habits are around console, command line and occasionally MidnightCommander.

I've tried SpaceFM with no luck. Vivaldi certainly receives dropped files.
I've tried to drop .crx file to this editor window and github complains "We don't support that file type".

As I drop .crx file into Vivaldy's "express panel" window, or "about:blank" window - nothing happens.

I've even tried to File->Open that .crx file. Vivaldi interprets this file://.... url as download action and "downloads" file from local disk to "Downloads" folder again.

### Steps for anyone to reproduce the issue
Install [Vivaldi](https://www.vivaldi.com) browser
Try to install AdNauseam extension "simply download the latest .CRX file and drag into your browser window."

### Your settings

- Gentoo Linux
- Vivaldi  1.15.1146.5 
- AdNauseam version: adnauseam-3.5.101.chromium.crx
- Other extensions you have installed: FoxyProxy Standard
- awesome window manager, but I doubt it could interfere with file dragging

### Your location/country
Russia

**Comment by dhowe** [comment]
Apparently you need to open the Tools->Extensions window first, then drag the .crx file into the browser

![image](https://user-images.githubusercontent.com/737638/39797199-6b312ed8-538d-11e8-9b85-69d64f142b03.png)

**Comment by Dahlstein** [comment]
Thanks! this helped me out a lot.

**Comment by dhowe** [comment]
@cqx931 Lets add this to the README

**Comment by cqx931** [comment]
updated this detail in wiki.
