### ISSUE TITLE
Youtube video ads are getting throught and updating filter take forever

### ISSUE THREAD

**Issue by kevinsmia1939** [dhowe/AdNauseam#1366]
Describe the issue

1) Adnauseam don't block youtube video ads (those 5 seconds ads) and banner ads on the side, this happen just a few minute before this was written. Maybe youtube roll out a new ads block bypass code.

2) So I tried update filter by pressing "purge cache" and "update now" but the loading icon spin forever. 
So I tried disable adnauseam and enable ublock origin and update, it work as expected. So I go back to adnauseam and still same problem 
If I wait for the update spinning for a few minute and then swtich to different "settings" tab, the filter will show that it is update (the clock icon). 

One or more specific URLs where the issue occurs
https://www.youtube.com/

Screenshot in which the issue can be seen
https://imgur.com/sa01Dwj
https://imgur.com/qE1ZmhM

Steps for anyone to reproduce the issue
(Please be as detailed as possible)
I just go to youtube

Your settings

    OS/version: Manjaro KDE stable
    Browser/version: Firefox 60.0.2 (64-bit)
    AdNauseam version: AdNauseam v3.6.205 uBlock Originv1.14.22 
    Other extensions you have installed: uGet integration, Trackmenot, Stylish, KeepassXC-Browser, decentraleye, videodownload helper, noscript

Your location/country

(If the issue is website specific, knowing your approximate location will help us to reproduce it)
Thailand.

**Comment by Metalhead33** [comment]
I have the exact same issue.
```
OS/version: Gentoo Linux 4.15.0
Browser/Version: Firefox Nightly 62.0a1 (2018-06-21) (64-bit)
AdNauseam version: AdNauseam v3.6.205 uBlock Originv1.14.22 
Other extensions you have installed: Adb Helper, cliget, Copy All Links, Empty Cache Button, Enhancer for Youtube, Exhentai Passport, HTML5 Video Everywhere!, Image Search Options, LastPass, No Miner, Stylish, Tamper Monkey
```

**Comment by lyatziv** [comment]
Same Issue
`
OS/version: MacOS 10.12.6 (16G1314)
Browser/version: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
AdNauseam version: AdNauseam v3.6.205 uBlock Originv1.14.22
Other extensions you have installed: Adblock Plus ,AdNauseam , Disconnect, Momentum, React Developer Tools ,Redux DevTools ,ScriptSafe ,Stylebot ,Tab Snooze ,Tampermonkey ,The Great Suspender
`

**Comment by dhowe** [comment]
Unable to recreate this so far on FF 60.0.2. Can someone provide the URL of a page on which this happens ?

**Comment by kevinsmia1939** [comment]
I did try both sign in and out, but still shows video ads and banner ads.

**Comment by kevinsmia1939** [comment]
Lets use a famous channel with ads
https://www.youtube.com/watch?v=gTFvshp9wrI
https://www.youtube.com/watch?v=TGl2X0m2oes
https://www.youtube.com/watch?v=DJKMbyFXjgs
https://www.youtube.com/watch?v=w5gbHSfbiK4
https://www.youtube.com/watch?v=1VWTo5U0AAA
https://www.youtube.com/watch?v=dEJzprv013U
https://www.youtube.com/watch?v=BUaKeMm_SJI

**Comment by dhowe** [comment]
I can only see the ads when I disable adnauseam. Can you open the ublock logger and see if anything is being blocked (menu -> μ -> logger-icon) ? Here is mine (you can see the blocked youtube ads in red). Most of the blocking filters appear to come from EasyList and/or EasyPrivacy...

![screen shot 2018-06-23 at 6 15 41 pm](https://user-images.githubusercontent.com/737638/41808559-ff4a04c6-7711-11e8-8444-b98983ef3895.png)

**Comment by dhowe** [comment]
I'm wondering now if AdNauseam is working at all -- perhaps you can visit this page (https://pythontips.com/tag/python-patreon/) and report what you see...

**Comment by kevinsmia1939** [comment]
This is what pi hole look like
https://imgur.com/yJYJrSh

**Comment by kevinsmia1939** [comment]
Soooo... I disable Adnauseam and then enable it again.
Ads dissapear now...

**Comment by dhowe** [comment]
interesting
@lyatziv @Metalhead33 does this solve the problem for you as well?

**Comment by Metalhead33** [comment]
@dhowe I solved it by reinstalling AdNauseam.

**Comment by lyatziv** [comment]
Still verifying

**Comment by lyatziv** [comment]
disabled & restarted browser. works.
