### ISSUE TITLE
3rd party list updates are slow and/or don't finish

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1367]
3rd party list updates are slow and/or don't finish (this includes the adnauseam list)

**Comment by cqx931** [comment]
no I still can't recreate this issue

**Comment by dhowe** [comment]
Perhaps these issues are just due to unclear iconography. 

For example, you want to update the adnauseam filters which has a little clock icon next to it, so you click 'update'. Then a warning icon flashes , and then the clock icon comes back. First, the state appears to unchanged. Second, the clock icon seems to imply the file _needs_ to be updated... 

Perhaps it would be better to have some (visual) way of knowing the update was a success (like a green clock or check  perhaps, which stays until the page is closed or refreshed...  ??

**Comment by dhowe** [comment]
perhaps just a mouse-over on the update button that says: 'last updated at $date'  ??

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/AdNauseam/pull/1377

**Comment by cqx931** [comment]
can this be closed?

**Comment by dhowe** [comment]
yes, lets keep an eye on it though
