### ISSUE TITLE
Vault: 'Delete Ad' causes incorrectly resets date-slider

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1368]
To recreate:
1. Open vault, and use data slider to increase number of ads showing to > 300
2. Right-click and delete any ad
3. Note that the date slider resets  and no longer shows the correct count

<img width="1112" alt="screen shot 2018-06-25 at 4 10 58 pm" src="https://user-images.githubusercontent.com/737638/41838413-f7c2dafc-7892-11e8-9c29-790768a3da4f.png">

**Comment by cqx931** [comment]
It used to recreate the whole slider after deleting an ad. Now when an ad is deleted, it will recreate the slider using the brush remembered before the deletion.
Please check:
https://github.com/dhowe/AdNauseam/pull/1371
