### ISSUE TITLE
The best way to fight ads

### ISSUE THREAD

**Issue by Capaverde** [dhowe/AdNauseam#1370]
Doxx the ad network owners and spread this info everywhere, the angry mob will do the rest.

Or are you guys just show?

**Comment by Capaverde** [comment]
Send the info of all collected ads to a central server, who makes a map of the ad network, as if a distributed spider. Then make this info easily available, in some sort of "search engine" of ads. This would be useful information for the public.

I can help if you'd like.

**Comment by dhowe** [comment]
similar to the original approach of 'lightbeam'... but likely out of scope for adnauseam

**Comment by mneunomne** [comment]
Lacks information. Closing
