### ISSUE TITLE
How can i change the language of the Ad Nauseam UI ?

### ISSUE THREAD

**Issue by laundmo** [dhowe/AdNauseam#1372]
### Describe the issue
i want to change the language of the adnauseam ui because im tired of having to transalte everything from german to english in my head and vice versa when talking about adnauseam

- OS/version: windows 10: 10.0.17134 Build 17134
- Browser/version: Firefox 61.0.2 (64bit)
- AdNauseam version: AdNauseam v3.6.205 uBlock Origin v1.14.22 
- Other extensions you have installed: 

| Addon Name |  Version |
| --- | --- |
| AdNauseam | 3.6.205 |
| Dark Theme for Google™ | 0.1.7 |
| DeepLT | 1.4. |
| Flash and Video Download |  3.1.7 |
| Reddit Enhancement Suite | 5.12.5 |
| Reddit on Youtube |  2.3.1 |
| ShareX |  1.0.0 |
| Tampermonkey |  4.7.5788 |

### Your location/country
Germany

**Comment by dhowe** [comment]
AdNauseam should automatically follow the language of the browser UI. Have you successfully switched the Firefox UI to German?

**Comment by Dyras** [comment]
@dhowe I'm using Chrome in Swedish and AdNauseum is 100% in English for me.

**Comment by dhowe** [comment]
@cqx931 can you check 
this one?

**Comment by cqx931** [comment]
@Dyras The current AdNauseam release doesn't include the Swedish locale file yet, that's why your AdNauseam is in English while your browser is in Swedish.

@laundmo Is your browser in German?

**Comment by laundmo** [comment]
@dhowe @cqx931 

i was switching my prefered website language to eglish and it confused my why nothing happened.

turns out to switch firefox to english you need to reinstall the english version
