### ISSUE TITLE
Visible ads on http://www.jegstener.dk/start/

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1374]
http://www.jegstener.dk/start/

![image](https://user-images.githubusercontent.com/737638/42433282-fa6ef2d6-8391-11e8-9976-f7077c54ba7f.png)

**Comment by dhowe** [comment]
This should be fixed as soon as the 'adnauseam filters' updates:

![image](https://user-images.githubusercontent.com/737638/42433591-6b85a57c-8393-11e8-9255-4a338a6ea67a.png)

**Comment by cqx931** [comment]
verified
