### ISSUE TITLE
File not found when trying to open an ad in new tab

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1379]
Can't find the blocking page in chrome
![image](https://user-images.githubusercontent.com/3056154/42745966-c6f42702-88d5-11e8-9c24-81a3e071111b.png)

**Comment by dhowe** [comment]
Is that reproducible? Is the file being packaged in the extension?

**Comment by cqx931** [comment]
can't reproduce this any more, close for now
