### ISSUE TITLE
Cannot enable AdNauseam in Chrome or Chromium (version 67.0.3396.99+)

### ISSUE THREAD

**Issue by JestDotty** [dhowe/AdNauseam#1380]
### Describe the issue
Cannot enable AdNauseam in Chrome (or Chromium, I tried)

### One or more specific URLs where the issue occurs
chrome://extensions

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/4729968/43315766-0861d544-9165-11e8-849f-2a9f4f96103b.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1. download new version of AdNauseam crx from github release page (3.6.205)
2. enable developer mode in Chrome extensions
3. drag and drop AdNauseam crx from downloads folder onto Chrome extensions
4. attempt to click the enable button
5. experience issue: button is disabled. Cannot allow extension to be enabled.

This issue is exactly the same in Chromium as well.

### Your settings

- OS/version: Windows 8.1
- Browser/version: 67.0.3396.99 (Official Build) (64 bit) & 68.0.3440.75 (Official Build) (64-bit) of Chrome, 68.0.3440.75 (Official Build) (64-bit) of Chromium
- AdNauseam version: 3.6.205
- Other extensions you have installed:
disabling them doesn't change anything but here they are anyway: Screeps SC (not on webstore), Betternet VPN, google docs offline, google translate, google voice search, moderater toolbox for reddit, pixijs devtools, reddit enhancement suite, ublock origin (been disabled for a while)

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
Canada

**Comment by dhowe** [comment]
To install AdNauseam in Chrome, you need to use the ZIP file on our download page. Please follow the instructions [here](https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission)
