### ISSUE TITLE
Opera - Ad blocking doesnt work

### ISSUE THREAD

**Issue by 60pfennig** [dhowe/AdNauseam#1382]
### Describe the issue
In Opera i see every ad on all pages. Ad Nauseam has the null on the icon every time.

### One or more specific URLs where the issue occurs
on all

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version:
win 10
- Browser/version:
opera 54.0.2952.60  
- AdNauseam version:
AdNauseam v3.6.205 
- Other extensions you have installed:
deactivate google analytics
### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
germany

**Comment by dhowe** [comment]
Did you get AdNauseam from the Opera store?
Can you try closing your browser and re-opening it?
Thanks

**Comment by 60pfennig** [comment]
Yes, I used AdNauseam on 3 devices. I installed it on all of them from the opera store. The problem occurs since a few weeks, so i restarted the browser quite often in this period. I restarted now at this second again. Problem is persisting.

**Comment by dhowe** [comment]
@cqx931 also see #1383

**Comment by Xalusc** [comment]
Can confirm this is also happening to me on Windows 10, even with VPN off and all 3rd-party filters on and updated.

**Comment by cqx931** [comment]
@Xalusc This issue should be fixed now. Please update AdNauseam to 3.7.10 if it is not automatically updated.

**Comment by cqx931** [comment]
@60pfennig
