### ISSUE TITLE
Not working on Opera for Mac

### ISSUE THREAD

**Issue by montievv** [dhowe/AdNauseam#1383]
Other extensions you have installed: 

### Describe the issue
Copy pasted text from another issue created for windows. Problem is exactly the same. In Opera i see every ad on all pages. Ad Nauseam has the null on the icon every time.

### One or more specific URLs where the issue occurs
On all

### Screenshot in which the issue can be seen
![screen shot 2018-08-13 at 19 02 22](https://user-images.githubusercontent.com/42346968/44035143-663e8304-9f2c-11e8-9884-6e5e96120cf2.png)

### Steps for anyone to reproduce the issue
Install from Opera Store. Does not block ads. Restart Browser. Does not block ads. Disabled Opera's in-built ad blocker. Restarted browser. Still does not work.

### Your settings

- OS/version: Mac OS X El Capitan (10.11.6)
- Browser/version: Opera 54.0.2952.71 (64 bit)
- AdNauseam version: 3.6.205
- Other extensions you have installed: Reddit Enhancement Suite (Enabled), Youtube Video Downloader (Disabled)

### Your location/country
India. Issue is not website specific

**Comment by dhowe** [comment]
I can confirm this (see below). @cqx931 pls look into this first thing...

<img width="1123" alt="screen shot 2018-08-13 at 2 30 40 pm" src="https://user-images.githubusercontent.com/737638/44050678-b65c3132-9f05-11e8-9fcb-0146073a23dc.png">

**Comment by dhowe** [comment]
Note the following errors in the addon console:

![image](https://user-images.githubusercontent.com/737638/44050765-f3abfbbc-9f05-11e8-9ba8-aaf56b71ccf2.png)

**Comment by Xalusc** [comment]
Can confirm the issue is also present in Windows 10. VPN off, no other adblockers on, all 3rd party filters enabled.

**Comment by cqx931** [comment]
The error above also exist in uBlock Origin 1.14.22.
https://github.com/dhowe/AdNauseam/pull/1384

Fixed two places for opera in this PR:
1.Missing vapi-usercss.js for opera in tools/make-opera.sh (This was also an issue for uBlock 1.14.22)
https://github.com/gorhill/uBlock/commit/dfcfa5ab9e113fd5429f95102003c3a1d718f047#diff-c2de39fc17ca44daf181a2e18373470f
2.Added back vapi.js in platform/opera/manifest.json

**Comment by dhowe** [comment]
Please create/test a new release ASAP for this
(and respond to existing tickets)

**Comment by montievv** [comment]
Works! Just tested. Thank you.

Had installed Ublock Origin in meantime. Although it was blocking ads, it wasn't blocking "all" ads. Ad Nauseam blocks even the ads which Ublock Origin wasn't blocking for me.
