### ISSUE TITLE
[3.7.301] Layout issue in vault

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1397]
![image](https://user-images.githubusercontent.com/3056154/45062570-7c6e4b80-b077-11e8-8969-15803d9ceabc.png)

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/pull/1404/commits/80bf6513ad488b048f74dce2c78f94d6b7d603da

**Comment by mushon** [comment]
@cqx931 that was quick…
