### ISSUE TITLE
No ads are blocked on rockpapershotgun.com, other sites are fine

### ISSUE THREAD

**Issue by PaperbackSpine** [dhowe/AdNauseam#1408]
### Describe the issue
No ads are blocked on rockpapershotgun.com, other sites are fine.

Creating a new firefox profile with adnauseam installed has the same results.

### One or more specific URLs where the issue occurs

https://www.rockpapershotgun.com/
Main page, but also its separate articles.

### Screenshot in which the issue can be seen
https://i.imgur.com/4nGP2F7.png

Two ads are visible. Adnauseam in the top right says "0".

### Steps for anyone to reproduce the issue

Visit https://www.rockpapershotgun.com/ in Firefox

### Your settings

- OS/version: win 7
- Browser/version: Firefox (updates itself to most recent version)
- AdNauseam version: Latest version from the FF addons site
- Other extensions you have installed: none

### Your location/country
The Netherlands.

**Comment by cqx931** [comment]
This should be fixed by https://github.com/dhowe/uAssets/commit/059183c057af8d7030073a70276066cdc2ce4d41
Please update your Adnauseam filters by clicking the "update" button beside AdNauseam filter on 3rd-party-filters page.

**Comment by PaperbackSpine** [comment]
Excuses for late reply. 

Ads are now hidden, but not detected and clicked.

**Comment by cqx931** [comment]
@KenLiHK Collecting ads from iframe is a bit tricky in firefox for now, could you please add commit your changes above?

**Comment by KenLiHK** [comment]
Committed sources,
https://github.com/dhowe/uAssets/pull/83/commits/e651f9f9a83a22f3b8befb4e38750f2b10f82571
