### ISSUE TITLE
Unable, to use the default EFF whitelist.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [dhowe/AdNauseam#1411]
### Describe the issue
I can't activate the External EFF DNT Policy Whitelist. It isn't activated by default, even by a fresh install.

### One or more specific URLs where the issue occurs
chrome-extension://coonkahcadhgibekanjopbbghkcdlmoa/dashboard.html#whitelist.html

### Screenshot in which the issue can be seen
![2018-09-28_16-28-38](https://user-images.githubusercontent.com/13170204/46214500-9da31e80-c33b-11e8-971a-3f8f9b921934.gif)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1. Open the AdNauseam settings.
2.Navigate to the "Whitelist" tab.
3. Try to click on the the external whitelist button to activate it.

### Your settings

- OS/version: Windows 10 10.0.18237 Insider preview.
- Browser/version: [Sushi Browser](https://github.com/kura52/sushi-browser) a muon based browser. (Previously tried aswell, on [Whale browser](https://whale.naver.com/en/), a chromium based korean browser) 
- AdNauseam version: v3.7.801 (Also tested on v3.7.101)
- Other extensions you have installed:

1. Stylus
2. Decentraleyes
3. Keyboard Privacy
4. Covfefe
5. Nano Defender
6. GitHub User Languages
7. MEGA
8. AutoJoin for SteamGifts
9. Cut YouTube Videos with VideoSegments
10. Neat URL
11. GDPR Please
12. SnooTube for YouTube™
13. TF2 Trading Enhanced
14. Twitter Demetricator
15. Bitwarden
16. OctoLinker
17. Random User-Agent
18. Cyclops
19. Privacy Possum
20. Tampermonkey
21. Refined GitHub
22. Select like a Boss
23. Grammalecte
24. Canvas Blocker (Fingerprint protect)
25. AutoPagerize
26. Grammarly
27. Enhanced Steam
28. WebRTC Leak Prevent
29. OctoPermalinker
30. Gestures for Google Chrome™
31. File Icon for GitHub
32. BehindTheOverlay
33. Universal Bypass
34. Botson
35. PassProtect
36. Refined Twitter
37. AudioContext
38. Isometric Contributions
39. GitHub Issue Link Status
40. UltraWideo
41. I don't care about cookies
42. BetterTTV

##### Your filter lists

Default Filter lists.

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

France.

**Comment by PoorPocketsMcNewHold** [comment]
Tested, with a clean installed version of [Ungoogled Chromium](https://github.com/Eloston/ungoogled-chromium), and it is still happening.

**Comment by cqx931** [comment]
Hi @PoorPocketsMcNewHold, this is the correct behavior for our current design. The EFF DNT Policy Whitelist should be automatically activated if you tick "Don't hide non-tracking Ads" under "Hiding Ads" or "Don't click non-tracking Ads" under "Clicking Ads". If none of these two settings are clicked, it will be deactivated.

**Comment by PoorPocketsMcNewHold** [comment]
I see. I'm gonna close this issue, as it was due to my undertanding of the extension.
