### ISSUE TITLE
[Suggestion] Add a way, to export chosen filter lists.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [dhowe/AdNauseam#1413]
I've took quite some times to select all my filter that i've had before that Adnauseaum new update, and already after that, a hotfix has been released.
I would wish, that the export feature, could also, remember of all the filter lists that we've subscribed too. 
(I've didn't checked if those were already saved locally on a file or something along the lines, I'm just a casual user of this extension.)

**Comment by cqx931** [comment]
Hi @PoorPocketsMcNewHold Do you mean the filter lists that you manually added to the 3rd-party filters?
When I test AdNauseam, it does remember any extra filter I have added and all the filters I have selected before. Could you provide more details about your case? 
It would also be more helpful if you could provide the following information:
- OS/version:
- Browser/version:
- AdNauseam version:
- Other extensions you have installed:

**Comment by PoorPocketsMcNewHold** [comment]
That exactky that. I wanted to know, if they was already a way to export them, when updating your AdNauseaum version, without having to add them again, manually by hand.
As i'm having quite a lot of them, after some visits to the filterlist website.

As it's just a feature suggestion more than a issue report, I doubt this would be useful but here's those informations anyway:

OS/version: Windows 10 18237.1000
Browser/version: [Sushi Browser v0.22.0 Geso(Squid arms)](https://github.com/kura52/sushi-browser) (Muon based web browser).
AdNauseam version: 3.7.801 (Will be updating just after that, to 3.7.802, since i was delaying to install this update due to that)
Other extensions you have installed: 

1. Stylus | Change the appearance of the Web with Stylus, a user style management tool. Stylus allows you to easily install themes and layouts for Google, Facebook, YouTube, orkut and many other sites.| 1.4.20 |
2. Decentraleyes | Protects from tracking related to centralized "free" content distributors. | 2.0.6 |  
3. Keyboard Privacy | Prevents behavioral profiling by randomizing the rate at which characters reach the DOM. | 2.5 |
4. Covfefe | Edit your tweets, finally. | 0.0.20 |
5. Nano Defender | An anti-adblock defuser for Nano Adblocker and uBlock Origin | 15.0.0.45 |
6. GitHub User Languages | See the language usage breakdown of a User or Org right on their GitHub profile page. | 0.1.9 |
7. Polisis | Get an AI-powered summary of any privacy policy | 2.0 |
8. MEGA | Secure Cloud Storage | 3.40.6 |
9. AdNauseam | Fight against advertising surveillance | 3.7.801 |  
10. AutoJoin for SteamGifts | Automatically enters giveaways from Steamgifts.com and site enhancements | 1.7.0.1 | 
11. Cut YouTube Videos with VideoSegments | Easiest way to remove boring content from YouTube videos. Great for listening to music. | 1.11.1 | 
12. Neat URL | Remove garbage from URLs. | 4.1.5 |  
13. GDPR Please | Blocks all web analytics trackers that do not honor informed opt-in consent and other GDPR protected rights. | 1.0.4 |  
14. YouTubeTutor | The best way to organize education by tutorials from YouTube. | 4.0.1 | 
15. SnooTube for YouTube™ | SnooTube for YouTube™ | 3.1 | 
16. TF2 Trading Enhanced | Adds additional features to backpack, outpost and steam. | 1.0.3 | 
17. Twitter Demetricator | Hides all the metrics on Twitter. | 1.0.2 | 
18. Bitwarden - Gestionnaire de mots de passe gratuit | A secure and free password manager for all your devices. | 1.31.2 |  
19. OctoLinker | 4.22.1 | 
20. Random User-Agent | Automatically change the user agent after specified period of time to a randomly selected one, thus hiding your real user agent | 2.2.6 | 
21. Cyclops - Hide YouTube numbers | Extension to hide YouTube numbers | 1.0 | 
22. Privacy Possum | 2018.8.31 |  
23. Tampermonkey | The world's most popular userscript manager | 4.7 |  
24. TrashMail.com: Create a disposable address | Create disposable email addresses. | 3.0.1 | 
25. Refined GitHub | Simplifies the GitHub interface and adds useful features | 18.9.11.1707 |  
26. Select like a Boss | Select link's text just like a regular text (like in Opera'12 browser) - Select like a Boss ;) | 2015.4.24 |
27. Grammalecte [fr] | Grammar, spelling and typography checker for French. | 0.6.5.1 |
28. AskBlocker | Blocks overly-eager permission requests for notifications, location, etc. For example, before you've interacted with the page. | 1.0.7 | 
29. Canvas Blocker (Fingerprint protect) | Prevent HTML canvas element from generating a unique identification key to protect user's privacy | 0.1.1 |
30. AutoPagerize | A browser Extension for auto loading paginated web pages. AutoPagerize use in many web site, and provide efficiently web browsing. | 0.3.9 |  
31. Grammarly for Chrome | Enhance your written communication everywhere you type! | 14.868.1844 |  
32. Enhanced Steam | Enhances the Steam Experience | 9.9 |
33. WebRTC Leak Prevent | Prevent WebRTC leaks using the official API. | 1.0.14 | 
34. OctoPermalinker | Fixes broken GitHub links. | 1.0.0 | 
35. Crumble – Online Privacy, Stop Tracking |   | 1.0.4.7 |  
36. Gestures for Google Chrome™ | Mouse Gestures for Google Chrome™ | 1.13.4 | 
37. File Icon for GitHub, GitLab and Bitbucket | A Chrome Extension which gives different filetypes different icons to GitHub, Gitlab, Bitbucket, gitea and gogs. | 0.7.0 |  
38. BehindTheOverlay | One click to close any overlay on any website. | 0.1.3 | 
39. Universal Bypass | Don't waste your time with compliance. Universal bypass automatically skips annoying link shorteners. | 5.6.4 | 
40. Botson | Detect twitter bots in your newsfeed | 0.3.0 |
41. PassProtect | Stop using bad passwords. PassProtect alerts you about breached credentials. Powered by "Have I Been Pwned?". | 0.1.8 | 
42. Refined Twitter | Simplifies the Twitter interface and adds useful features | 18.9.7.1237 |
43. AudioContext Fingerprint Defender | Defending against AudioContext fingerprinting by reporting a fake value. | 0.1.0 |
44. Isometric Contributions | Renders an isometric pixel view of GitHub contribution graphs. | 1.0.23 |
45. GitHub Issue Link Status | Colorize issue and PR links to see their status (open, closed, merged) | 18.6.14.2005 |
46. UltraWideo | Upscale or stretch any video on the web, to make it look great on UltraWide screens. | 1.5 | 
47. I don't care about cookies | 2.9.1 | 
48. BetterTTV

(Feel free to judge and suggest me some modifications to my extensions lists, I do believe i've may have installed too much, and maybe installed some none useful ones in the lot (Aka possible extensions already doing the job of others))

**Comment by cqx931** [comment]
@PoorPocketsMcNewHold , I see. If you go to the bottom of dashboard.html and click "Backup to File". Then, select "Settings Only" or "Settings and Ads". You will see a json file created for your AdNauseam.
After updating/reinstalling AdNauseam, click "restore from file" at the same place, choose your backup file, then you should be able to all your old selections/filters/etc.

**Comment by dhowe** [comment]
@PoorPocketsMcNewHold can you try to find a simplest test case that we can use to recreate the problem? Something like, 'Start with a fresh adnauseam, add filter list X, save settings, quit the browser, reinstall, etc.'

**Comment by PoorPocketsMcNewHold** [comment]
Setup : An already made backup .json file (Could be from Sushi Browser, or any other browser, as i've tested from a [Ungoogled Chromium](https://github.com/Eloston/ungoogled-chromium) generated backup), Sushi Browser.

1. Download [Sushi Browser](https://github.com/kura52/sushi-browser) and launch it (As i still think is just due to that browser, if you do wish to verify it, this would help to determine if the browser would need to change something precisely)
2. Install AdNauseaum with a .crx file. (Settings > Extension and they're should be a install .crx button there).
3. Open the AdNauseaum settings, and import the .json config using the dashboard.html import button, or the vault.html button to import only the ads from it.

From multiple tries, I've didn't really noticed any of my third parties lists to be imported. As i've said, almost all of them where adden to AdNauseaum using the adp protocol (The classic, click on the link, and a popup window from the extension will ask you if you want to add this filter list). So, i doubt the selection of filter list will influence it.

**Comment by cqx931** [comment]
@PoorPocketsMcNewHold  Thank you for your detailed feedback! Yes, I agree that this issue is more related to the Sushi-browser instead of AdNauseam, so I'm closing this issue now.
