### ISSUE TITLE
Video ads visible on msnbc

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1414]
Video ads visible on msnbc: https://www.msnbc.com/ali-velshi/watch/sen-joe-manchin-shttps://www.msnbc.com/ali-velshi/watch/sen-joe-manchin-speaks-after-announcing-yes-vote-on-kavanaugh-1337843779680?v=railb&peaks-after-announcing-yes-vote-on-kavanaugh-1337843779680?v=railb&

**Comment by cqx931** [comment]
I see a black overlay saying "your video begins in 00:15", then it disappears after 3 seconds, is this what you mean?

**Comment by dhowe** [comment]
@KenLiHK pls check

**Comment by KenLiHK** [comment]
Cannot simulate the case in Firefox and Chrome today.
