### ISSUE TITLE
Vault: update/animate when data changes

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#1417]
### Current state

There are two primary cases when ad data changes while the vault is open: a) new ads are found, and b) the user manipulates the data. Currently case a) is ignored and case b) triggers a full repack. 
This creates a lot of noise and makes it harder to follow ads as they move to a new location in the pack.

### Proposed change

The goal here is to make the vault more dynamic, allowing users to see their data changing over time. Thus we want to animate the transition from one pack to another, in this fashion:

1. The page loads with the latest X number of ads as a pack
2. An event changes the ad list (either a timeline change, a filter change, or a new ad detected in another tab)
3. Any new ads are added to the outer perimeter of the pack and ads no longer included fade out 
4.  Repacking of the updated list happens in the background, with a new target position set for each ad
5. When all positions are computed, each ad animates from its old position to its new position

Note: repacking should not occur when the user is interacting with the visualization, so as avoid interrupting hover/click/inspect interactions.

**Comment by mushon** [comment]
it seems like the basic packery.js code supports similar repacking transition functionality:
https://codepen.io/desandro/pen/qmPwaJ

Maybe that's something we can use?

**Comment by cqx931** [comment]
Further follow up of this ticket can be found https://github.com/dhowe/AdNauseam/issues/1416. Close this as the feature  is now added.
