### ISSUE TITLE
Ads visible on yahoo.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1421]
https://hk.yahoo.com/?p=us

location: hk
browser: firefox

![image](https://user-images.githubusercontent.com/737638/47632919-0e319b00-db87-11e8-8c24-b7b48a9a538e.png)

**Comment by cqx931** [comment]
If you mean the product images on the right, they seem to be the shopping channel of yahoo and ublock also don't block those.

**Comment by cqx931** [comment]
blocked one ad element that I found hidden with uBlock but visible with AdNauseam https://github.com/dhowe/uAssets/commit/2ca678fb8612e4c188988cb9c7cd19164765560d
