### ISSUE TITLE
Vault: date slider problems

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1422]
1. Slider can be pushed off the right edge so that no dates are selected (image 1)
2. Window resize causes slider to get out of sync with ad display (image 2)

![image](https://user-images.githubusercontent.com/737638/47698422-3f26d400-dc4a-11e8-8b07-a16e44ead33f.png)

* To recreate, simply drag slider as far to right as possible until it disappears

![screen shot 2018-10-30 at 1 39 03 pm](https://user-images.githubusercontent.com/737638/47698425-41892e00-dc4a-11e8-9172-7c8eb8fd36e6.png)

* To recreate, select a small number of ads with date slider, adjust window size slightly

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/AdNauseam/pull/1465/commits/f5a080dad279bbc450baaeae344c4000e5735e29
