### ISSUE TITLE
Settings: CSS messed up? 

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1423]
![image](https://user-images.githubusercontent.com/737638/47699211-253ac080-dc4d-11e8-87e4-02c56b9d2bcd.png)

**Comment by cqx931** [comment]
This is not related to the exhibition branch. It is caused by last merge from uBlock with new codeMirror css.

**Comment by cqx931** [comment]
@dhowe what exactly do you find problematic here? Is it the "##" signs? They are designed with a light grey background in uBlock. If we do want to keep it, I can change it to a darker grey.

**Comment by dhowe** [comment]
yes, those are not readable on our dark bg...

**Comment by cqx931** [comment]
done
