### ISSUE TITLE
Video ads playing on CNN

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1426]
Related to Issue #965??

https://www.cnbc.com/video/2018/11/07/president-trump-cnns-jim-acosta-have-heated-exchange.html

Click the video at top of page - get long video ad

**Comment by KenLiHK** [comment]
Find different visible ads on top of the video,
||ads-pd.nbcuni.com/news/INVESTNIAW1501H_NEWS/INVESTNIAW1501H_NEWS_0796.mp4$media

Add the following blocking rules,
||ads-pd.nbcuni.com^

**Comment by KenLiHK** [comment]
Fixed and committed the following source,

https://github.com/dhowe/uAssets/pull/82/commits/44b5ca538549dc634e2c25fff02da0a82386419b
