### ISSUE TITLE
Video ads playing on 9anime.to

### ISSUE THREAD

**Issue by danielb2** [dhowe/AdNauseam#1427]
### Describe the issue

Ads are shown on 9anime.to

### One or more specific URLs where the issue occurs

http://9anime.to

### Screenshot in which the issue can be seen
![screen shot 2018-11-09 at 16 31 22](https://user-images.githubusercontent.com/26678/48295003-eff85480-e43c-11e8-8bdc-9f1c999dd691.png)
![screen shot 2018-11-09 at 16 31 32](https://user-images.githubusercontent.com/26678/48295008-f4bd0880-e43c-11e8-8702-a2c59739c0a1.png)

### Steps for anyone to reproduce the issue

browse to the site. click an anime.

https://www1.9anime.to/watch/bloom-into-you.wmj4/op60pj

### Your settings

- OS/version: macos mojave
- Browser/version: chrome Version 69.0.3497.81 (Official Build) (64-bit)
- AdNauseam version: v3.7.802
- Other extensions you have installed:

##### Your filter lists
none
### Your location/country
us

**Comment by KenLiHK** [comment]
Fixed and commit the following source,
https://github.com/dhowe/uAssets/pull/82/commits/44b5ca538549dc634e2c25fff02da0a82386419b
