### ISSUE TITLE
Site does not load

### ISSUE THREAD

**Issue by mqus** [dhowe/AdNauseam#1430]
### Describe the issue
I'm reading my news on a german IT website - https://www.golem.de . They have also a ordered view of all their news: https://www.golem.de/ticker/ . This page will not load If AdNauseam is enabled. Curiously It is the only page on this site that does not work.

### One or more specific URLs where the issue occurs
https://www.golem.de/ticker/

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1. In Firefox 63.0.3, disable all addons but AdNauseam.
2. Try to open page https://www.golem.de/ticker/
3. Page will try to load but fail after a timeout.
3.1 The Network Tool says that It has resolved the DNS, connected to the server and began the transfer from the server to my browser. It stopped after ~33kb of ~100kb for no reason (console is empty) and still loads (spinning circle on the tab logo)
4. Disable AdNauseam -> Page loads as usual.

### Your settings

- OS/version: Archlinux, Kernel 4.19.2
- Browser/version: Firefox 63.0.3
- AdNauseam version: 7.3.802
- Other extensions you have installed: uMatrix, HTTPSEverywhere, 

##### Your filter lists
Essentials w/o Annoyances and Resource Abuse

+Malware Domain List
+Malware Domains
+DEU

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
Germany

**Comment by dhowe** [comment]
Confirmed. Not sure what is causing this, as the ADN logs show no blocks. @cqx931 can you take a look?

**Comment by cqx931** [comment]
I can't reproduce with FIrefox 64.0b8 on my mac.
@dhowe have you made any special change in the settings to reproduce it?

**Comment by dhowe** [comment]
No, I just see a blank page with normal settings. Perhaps it is location-based ?

**Comment by cqx931** [comment]
@KenLiHK Can you reproduce this ticket?

**Comment by dhowe** [comment]
Have you tried with a German proxy or VPN?

**Comment by KenLiHK** [comment]
Yes, cannot reproduce the case when German proxy is turned on.

![1430](https://user-images.githubusercontent.com/24424527/51782361-e3dd8280-2161-11e9-9cd8-dc44d5100a33.png)

**Comment by mqus** [comment]
I just want to mention that the bug still persists (I have now installed firefox 64.0.2, AN 3.7.802).

Just to mention: Since then I also changed my internet provider (unrelated to this issue, from telefonica to dt. telekom) so this is not due to a specific provider messing with stuff.

**Comment by dhowe** [comment]
Ok, I have confirmed this now.

**Comment by dhowe** [comment]
@cqx931 status on this?

**Comment by cqx931** [comment]
Just tested this on the new release. I couldn't reproduce this issue before and now everything still seems okay to me on this website.

AdNauseam does have the +js cosmetic filters triggered by now. Not sure if that's going to fix the issue.
![image](https://user-images.githubusercontent.com/3056154/61750566-c0436f80-ad73-11e9-8d60-d04a10065029.png)
