### ISSUE TITLE
Add DEV FAQ: color coding in ADN logger

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1431]
![image](https://user-images.githubusercontent.com/3056154/32916525-5f14e648-caea-11e7-87a6-12c4749d4ad9.png)

**Comment by dhowe** [comment]
Excellent. This should be useful for @KenLiHK

**Comment by dhowe** [comment]
@cqx931 please add this to the DEV FAQ as soon as possible

**Comment by dhowe** [comment]
Done: https://github.com/dhowe/AdNauseam/wiki/The-logger

**Comment by cqx931** [comment]
Updating this color guide as the one above is no longer valid for the latest changes:
![image](https://user-images.githubusercontent.com/3056154/71547463-3f198580-296e-11ea-96d0-91602ea96a31.png)
