### ISSUE TITLE
Video ADs have reappeared on youtube

### ISSUE THREAD

**Issue by ADNReport** [dhowe/AdNauseam#1432]
### Describe the issue
Video ADs on youtube

### One or more specific URLs where the issue occurs
https://www.youtube.com/watch?v=VDvr08sCPOc

### Screenshot in which the issue can be seen
https://i.ibb.co/HTpH1sc/Screenshot-2018-11-26-10-50-28.png

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
None (just opened a video)

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 63
- AdNauseam version: Latest
- Other extensions you have installed: No

##### Your filter lists
Default (Malware Blocking DIsabled)

### Your location/country
Bulgaria

**Comment by ADNReport** [comment]
after a lot of working i'm still not able to fix the problem
things i noticed:
the ads are very long (from: 30s to:2m) and also unskipable.
the ads are built into the video player itself (soo trying to block them will also block the the video).
any advices what to do?

**Comment by dhowe** [comment]
Can you check if these ads show using uBlock Origin (with Adnauseam disabled) ?

**Comment by ADNReport** [comment]
please note that i'm using the old layout of youtube
i have 4 Addons installed (ADN,CyDec,Video Blocker,FoxReplacer)
at first i thinked its because some of the other addons but after many try's it looks like its not

What The Addons Do:
ADN: (Hides/Blocks/Clicks Ads)
CyDec ( Example:
Without CyDec (Disabled):
`User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
Screen Resolution: 1024×768
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
`
With CyDec (Enabled)
`User-Agent: Irrdc9HLZw 13VZpe1716cGb trP10p19CbF6 IZ9dyPYZW9jEh Chrome/51.13 ZXg13gDFb11Mn Opera/72715145381010 Za5fM13PnpDB4vyiy j1019k18ut10YWWwV ZhZ19ZKZLCn4 eFZa9nDmdori (Windows NT; Fedora x4579_8839; rv:45109.12) 9stIZ7P9MwxF
Screen Resolution: 1009×715 35-bit
Accept-Encoding: 96gu6f,fcyc9, br,gzip, deflate,hp999lbk,ht9olsg,bz73ux
Accept-Language: wpknv9c,ygazhp,5sl9,en-US,q6j7l6lo,en;q=0.5,i99v8at,pisex,cz51,etmkjkee`

Video Blocker (just document.GetElementById/ClassName, then it removes them .remove)

FoxReplacer (Replaces Text (Not HTML/JS code))

the Problem is because CyDec but not directly.
because youtube can't identify what browser/os i'm using it automaticly redirects me to the old youtube layout but nothing more than that. i examined the source code of CyDec and it does not modify/delete any code in the pages i vist (except for user-agent/Screen-Resolution/etc...)

soo after many tries, yes ADN blocks video ads but only on the new Youtube layout, if you switch to the old one which is still available, it does not block them
i tried to fix it, but here comes the problem the there is nothing to block the ADs are into the video itself
there is nothing to block, there is not even a skip button.

yes you can access it throu bulgarian proxy(there are many) but i tried with french/geramny/usa ip adresses but i still got ads it looks like its not region specific

THANK YOU for wanting to help, i really appreciate it :)

https://user-images.githubusercontent.com/45348732/49209437-29303e80-f3c3-11e8-81bb-14e441b0ca39.png

**Comment by dhowe** [comment]
So if you disable CyDec, you are sent to the new layout where the problem doesn't exist, is that correct?

Would still be useful if you could try with [uBLock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) enabled and AdNauseam disabled...

**Comment by dhowe** [comment]
Ok, I am going to close this as it seems to be a filter list problem, rather than an adnauseam problem (given that no blockers can block these)... Thanks for all the info
