### ISSUE TITLE
AdNauseam hiding some/none of ads on pages

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1433]
@KenLiHK Please check these...

Here are a list of sites in which AdNauseam hides only some/none of the ads
https://adbtc.top
https://nowbitco.in
https://freebitcoin.win
https://bitcohitz.com
https://claimfreebtc.win
http://claimbtc.in/bitcoin-faucet
dailyfreebits.com
http://zetabitco.com/BITCOIN/
dailyfreebits.com
https://bitcoin.treasurebits.net
Screenshot_2018-11-26_10-07-40.png

**Comment by ADNReport** [comment]
Thanks for reading my email :)
i managed to fix the issue by adding
"
##a[href*="advertere"]
##a[href*="adhitzads"]
##a[href*="coinad"]
##a[href*="bitraffic"]
##a[href*="coinzilla"]
"
to "my filters" in "3-rd party filters"
now the ads are hidden and also collected
https://i.ibb.co/wr2LXPH/Screenshot-2018-11-26-12-55-49.png

**Comment by KenLiHK** [comment]
Check that AdNauseam hides only some/none of the ads and raise the following tickets,
-. [#1438](https://github.com/dhowe/AdNauseam/issues/1438)
-. [#1439](https://github.com/dhowe/AdNauseam/issues/1439)
-. [#1440](https://github.com/dhowe/AdNauseam/issues/1440)
-. [#1441](https://github.com/dhowe/AdNauseam/issues/1441)
-. [#1442](https://github.com/dhowe/AdNauseam/issues/1442)
-. [#1443](https://github.com/dhowe/AdNauseam/issues/1443)
