### ISSUE TITLE
Popout video ad visible on www.topuniversities.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1434]
https://www.topuniversities.com/university-rankings-articles/qs-best-student-cities/hong-kong

![screen shot 2018-11-26 at 7 54 52 pm](https://user-images.githubusercontent.com/737638/49012734-48598100-f1b5-11e8-8e44-dda0538ff80f.png)

@cqx931 perhaps you can show @KenLiHK how to create a hiding rule and submit a PR( to uAssets), using this as a test case (see hiding filters below) ?

**Comment by dhowe** [comment]
Hiding rules should be:

www.topuniversities.com###appsnack_teaser_iframe_41b1d47d-6fbd-f83b-ae62-76fc974d66b7
www.topuniversities.com###teaser_41b1d47d-6fbd-f83b-ae62-76fc974d66b7

-> perhaps www.topuniversities.com##*[id*^="teaser"]

www.topuniversities.com###backGroundFadedDiv_41b1d47d-6fbd-f83b-ae62-76fc974d66b7

-> perhaps www.topuniversities.com##div[id^="backGroundFaded"]

<br>

**Comment by KenLiHK** [comment]
Finding:
-. Cannot simulate this case (a pop-up ads) in my Computer
-. OS: macOS High Sierra Version 10.13.6
-. Firefox version: 63.3
-. Chrome version: 70.0.3538.110 (Official Build)(64-bit)
-. AdNauseam version: V3.7.802
-. UBlock Origin version: V1.15.24.0

Testing:
-. Try to add only www.topuniversities.com##*[id*^="teaser"] to "My Filters" in Chrome and Firefox and refresh the page, no collected ads.
-. Try to add only www.topuniversities.com##div[id^="backGroundFaded"] to "My Filters" in Chrome and Firefox and refresh the page, no collected ads.
-. Try to add both patterns to "My Filters" in Chrome and Firefox and refresh the page, no collected ads.

**Comment by dhowe** [comment]
Are you seeing the ad when you visit with no blocker ? If not, then why try with added filters ?

Also, what are you using uBlock Origin for?

**Comment by KenLiHK** [comment]
I cannot see the ad when I visit with no blocker. 

The case cannot be simulated.

**Comment by dhowe** [comment]
If there are other ads on the page, please add the relevant info here: screenshot / etc

**Comment by cqx931** [comment]
I can't reproduce this as well
