### ISSUE TITLE
Image upload blocked

### ISSUE THREAD

**Issue by bunnybooboo** [dhowe/AdNauseam#1435]
### Describe the issue
Seeing this when using the distributed and federated social network called Mastodon. 

When I draft a post, and attempt to add a picture, its preview his hidden from view. It looks like the image is not added to the draft but if you toot it (the name for Mastodon posts) the image shows. This is problematic in that you can't then add an image description for accessibility, and if you instead go to create another post or even respond to another user's post this drafted image is added, despite it hidden from user view.

NOT reproduced in uBlock Origin.

### One or more specific URLs where the issue occurs
https://mastodon.social/
https://mastodon.me.uk
..essentially any of the THOUSANDS of instances which use Mastodon

### Screenshot in which the issue can be seen
Post/Toot with image added
![screenshot from 2018-11-28 13-10-13](https://user-images.githubusercontent.com/5793295/49154166-abf7c180-f30f-11e8-9c5c-2d8dfb3a5c98.png)

Post/Toot after pressing reply to another post and clicking the CW (Content Warning) icon TWICE. Expected behaviour if no image attached is the content hidden image (identified by an eye icon) with NO CROSS through it.
![screenshot from 2018-11-28 13-12-35](https://user-images.githubusercontent.com/5793295/49154306-f24d2080-f30f-11e8-8d5e-841968587d51.png)

Post/Toot after pressing TOOT! button. Image shown is inherited from the original supposedly unsuccessful (and subsequently abandoned) draft

### Steps for anyone to reproduce the issue
(Please be as detailed as possible) Steps as above

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox Nightly (when testing this was Firefox 65.0a1 Build ID 20181127220131)
- AdNauseam version: 3.7.802
- Other extensions you have installed: B.S. Detector, Clippings, Containers on the Go, Cookies AutoDelete, Dark Background and Light Text, Decentraleyes, Emoji Keyoard, Firefox Multi-Account Containers, Forefox Pioneer, Google Docs Line Numbers, HTTPS Everywhere, KeePassXC-Browser, Link Cleaner, Measure It, MinerBlock, Open in VLC Media Player, Reddit Enhancement Suite, Redirect AMP to HTML, Rotate and Zoom Image, Slack Direct, Snap Links, Test Pilot, Update Scanner, Video Speed Control, Vidyo Replay Download. Yes I appreciate this is a lot of additionals but I'll test combinations within the next 24 hours.

##### Your filter lists
Defaults
![screenshot from 2018-11-28 14-13-42](https://user-images.githubusercontent.com/5793295/49157519-e36a6c00-f317-11e8-98bb-6199cfaca2c3.png)

### Your location/country
United Kingdom

**Comment by dhowe** [comment]
I use mastodon as well and haven't seen this (though I'm not sure I am doing the same steps). Two questions:
1) Do things work properly if you simply whitelist mastodon (by clicking 'disable' in the adnauseam menu)
2) Can you be a bit more clear as to the steps required to recreate (I'm not sure I fully get the sequence)?
thanks
