### ISSUE TITLE
global filters don't work on some sites [possible bug]

### ISSUE THREAD

**Issue by ADNReport** [dhowe/AdNauseam#1436]
### Describe the issue
global filters like:
`##iframe[src*="coinad"]`
`##iframe[src*="mellowads"]`
does not work, but:
`freebitcoin.win##iframe[src*="coinad"]`
`freebitcoin.win##iframe[src*="mellowads"]`
works

please correct me if i did something wrong

### One or more specific URLs where the issue occurs
https://freebitcoin.win/

### Steps for anyone to reproduce the issue
just visit the website ;)

### Your settings
Default (Malware Blocking Disabled)

- OS/version: Arch Linux
- Browser/version: Firefox 63
- AdNauseam version: Latest
- Other extensions you have installed: CyDec,FoxReplace,Video Blocker

##### Your filter lists
Default + Custom Filters "My Filters"

### Your location/country
Bulgaria

**Comment by dhowe** [comment]
Can you check if this is also the case with uBlock Origin enabled (and AdNauseam disabled) ?

**Comment by dhowe** [comment]
Also, if you come up with rules that work to hide ads, please submit PRs [here](https://github.com/dhowe/uAssets). Thanks
