### ISSUE TITLE
Ad visible on https://nowbitco.in

### ISSUE THREAD

**Issue by KenLiHK** [dhowe/AdNauseam#1439]
### Describe the issue
Visble Ad in https://nowbitco.in

### One or more specific URLs where the issue occurs
https://nowbitco.in

### Screenshot in which the issue can be seen
Screen in Chrome,
![screen2](https://user-images.githubusercontent.com/24424527/49326494-ee2e3680-f58d-11e8-88aa-1bed4ffdd0f0.png)

Screen in Firefox,
![screen2 firefox](https://user-images.githubusercontent.com/24424527/49326497-f2f2ea80-f58d-11e8-9047-cce1bf031c59.png)

### Steps for anyone to reproduce the issue
1. Add AdNauseam plugin into Chrome / Firefox
2. Enable "HIDE ADS", "CLICK ADS" and "BLOCK MALWARE" in "About" page.
3. Access the URL https://nowbitco.in

### Your settings
- OS/version: Windows 10 Enterprise
- Browser/version:
  1) Chrome Version 70.0.3538.110 (Official Build) (64-bit)
  2) Firefox 63.0.3 (64-bit)
- AdNauseam version: AdNauseam3.7.802
- Other extensions you have installed: N/A

##### Your filter lists
AdNauseam filters​​​​
EasyList​​​​​
EasyPrivacy​​​​​
uBlock filters​​​​​

uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
My filters​​​​​

Malware Domain List​​​​​
Malware domains

### Your location/country
Hong Kong

**Comment by KenLiHK** [comment]
Hiding rules is:
Found these 3 js which will trigger the popup ads in log message.
https://serve.czilladx.com/serve/jslib/fp.js
https://serve.czilladx.com/serve/jslib/fb.js
https://serve.czilladx.com/serve/jslib/fbf.js

filter:
--> https://serve.czilladx.com/serve/jslib/*.js

**Comment by cqx931** [comment]
Please refer to the blocking filter format, and a more general filter for this case would be:
||czilladx.com/serve/*.js^

**Comment by dhowe** [comment]
Correct. No rules, as far as I know, should start with http(s). And again, these are NOT hiding rules. These are BLOCKING rules

**Comment by KenLiHK** [comment]
fixed.

https://github.com/dhowe/uAssets/pull/80/commits/66cd91cfd778fa918d6e9eb2a2d6eb118ee7f130
