### ISSUE TITLE
Ad visible on https://freebitcoin.win

### ISSUE THREAD

**Issue by KenLiHK** [dhowe/AdNauseam#1440]
### Describe the issue
Visble Ad in https://freebitcoin.win

### One or more specific URLs where the issue occurs
https://freebitcoin.win

### Screenshot in which the issue can be seen
Screen in Chrome,
![screen3](https://user-images.githubusercontent.com/24424527/49326601-7234ee00-f58f-11e8-9101-01df4ecb45b9.png)

Screen in Firefox,
![screen3 firefox](https://user-images.githubusercontent.com/24424527/49326604-78c36580-f58f-11e8-9f2c-ef64547ad982.png)

### Steps for anyone to reproduce the issue
1. Add AdNauseam plugin into Chrome / Firefox
2. Enable "HIDE ADS", "CLICK ADS" and "BLOCK MALWARE" in "About" page.
3. Access the URL https://freebitcoin.win

### Your settings
- OS/version: Windows 10 Enterprise
- Browser/version:
  1) Chrome Version 70.0.3538.110 (Official Build) (64-bit)
  2) Firefox 63.0.3 (64-bit)
- AdNauseam version: AdNauseam3.7.802
- Other extensions you have installed: N/A

##### Your filter lists
AdNauseam filters​​​​
EasyList​​​​​
EasyPrivacy​​​​​
uBlock filters​​​​​

uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
My filters​​​​​

Malware Domain List​​​​​
Malware domains

### Your location/country
Hong Kong

**Comment by dhowe** [comment]
fixed
