### ISSUE TITLE
Ad visible on https://bitcohitz.com

### ISSUE THREAD

**Issue by KenLiHK** [dhowe/AdNauseam#1441]
### Describe the issue
Visble Ad in https://bitcohitz.com

### One or more specific URLs where the issue occurs
https://bitcohitz.com

### Screenshot in which the issue can be seen
Screen in Chrome,
![screen4](https://user-images.githubusercontent.com/24424527/49326671-c2f91680-f590-11e8-8bf7-476e046f68de.png)

Screen in Firefox,
![screen4 firefox](https://user-images.githubusercontent.com/24424527/49326673-c5f40700-f590-11e8-87b2-cb2d8072e3c1.png)

### Steps for anyone to reproduce the issue
1. Add AdNauseam plugin into Chrome / Firefox
2. Enable "HIDE ADS", "CLICK ADS" and "BLOCK MALWARE" in "About" page.
3. Access the URL https://bitcohitz.com

### Your settings
- OS/version: Windows 10 Enterprise
- Browser/version:
  1) Chrome Version 70.0.3538.110 (Official Build) (64-bit)
  2) Firefox 63.0.3 (64-bit)
- AdNauseam version: AdNauseam3.7.802
- Other extensions you have installed: N/A

##### Your filter lists
AdNauseam filters​​​​
EasyList​​​​​
EasyPrivacy​​​​​
uBlock filters​​​​​

uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
My filters​​​​​

Malware Domain List​​​​​
Malware domains

### Your location/country
Hong Kong

**Comment by KenLiHK** [comment]
Hiding rules are:

bitcohitz.com##iframe[src="//coinad.com/ads/show/show.php?a=NZNJM1JYICNKI&b=L6QCVY285M522"]
bitcohitz.com###wcfloatDiv
bitcohitz.com###sticky-banner-QY0O9X0YYN51C
bitcohitz.com##.foot_banners

filter:
--> bitcohitz.com###wcfloatDiv
--> bitcohitz.com###sticky-banner-QY0O9X0YYN51C
--> bitcohitz.com##.foot_banners

**Comment by cqx931** [comment]
Good job, please add the filters to uAssets.

Also, I found that somehow these filters don't work in firefox. Could you please verify that?

**Comment by dhowe** [comment]
DOM Ids like this:
    bitcohitz.com###sticky-banner-QY0O9X0YYN51C

are most likely generated and/or quickly changing. Do NOT include them in rules.
It should be:

    bitcohitz.com##*[id^="sticky-banner"]  // any element with id starting with sticky-banner

**Comment by KenLiHK** [comment]
Fixed and update the following sources,

https://github.com/dhowe/uAssets/pull/80/commits/0702ad0110a1f767cfa9b9bb73da91b42c83b2f7
