### ISSUE TITLE
Ad visible on https://claimfreebtc.win

### ISSUE THREAD

**Issue by KenLiHK** [dhowe/AdNauseam#1442]
### Describe the issue
Visble Ad in https://claimfreebtc.win

### One or more specific URLs where the issue occurs
https://claimfreebtc.win

### Screenshot in which the issue can be seen
Screen in Chrome,
![screen5](https://user-images.githubusercontent.com/24424527/49326835-018fd080-f593-11e8-89a4-e06d168c381f.png)

Screen in Firefox,
![screen5 firefox](https://user-images.githubusercontent.com/24424527/49326836-048ac100-f593-11e8-9301-2a2b3631661a.png)

### Steps for anyone to reproduce the issue
1. Add AdNauseam plugin into Chrome / Firefox
2. Enable "HIDE ADS", "CLICK ADS" and "BLOCK MALWARE" in "About" page.
3. Access the URL https://claimfreebtc.win

### Your settings
- OS/version: Windows 10 Enterprise
- Browser/version:
  1) Chrome Version 70.0.3538.110 (Official Build) (64-bit)
  2) Firefox 63.0.3 (64-bit)
- AdNauseam version: AdNauseam3.7.802
- Other extensions you have installed: N/A

##### Your filter lists
AdNauseam filters​​​​
EasyList​​​​​
EasyPrivacy​​​​​
uBlock filters​​​​​

uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
My filters​​​​​

Malware Domain List​​​​​
Malware domains

### Your location/country
Hong Kong

**Comment by KenLiHK** [comment]
Hiding rules are:

claimfreebtc.win###top-ads
claimfreebtc.win###right-adspace
claimfreebtc.win###left-adspace
claimfreebtc.win###middle-adspace
claimfreebtc.win##iframe[src="//ad.a-ads.com/966857?size=728x90"]
claimfreebtc.win##iframe[src="https://claimfreebtc.win/banners/728x90/slot2"]


filter:

--> claimfreebtc.win###top-ads
--> claimfreebtc.win###right-adspace
--> claimfreebtc.win###left-adspace
--> claimfreebtc.win###middle-adspace
--> claimfreebtc.win##iframe

**Comment by cqx931** [comment]
good, please add to adnauseam.txt. Also, please notice that a general filter like`iframe[src*="ad.a-ads.com"]`is preferred here as well. 
Here is aother case: https://github.com/dhowe/AdNauseam/issues/1438

**Comment by KenLiHK** [comment]
Today, the website show this banner when AdNauseam is installed.
I will not add the filter to adnauseam.txt for this website now.

![banner](https://user-images.githubusercontent.com/24424527/50536795-3c395880-0b93-11e9-80cd-dde86f9d0489.png)


![banner2](https://user-images.githubusercontent.com/24424527/50536830-802c5d80-0b93-11e9-8e76-fd3f883507d2.png)

**Comment by dhowe** [comment]
Does this banner occur with ublock? If not, can we figure out why its showing with adnauseam?

**Comment by KenLiHK** [comment]
This banner is not occurred in ublock, please refer to image 2 above.

I think it is due to some generic filtering rules. 

For example, today when I try to find and apply a rule for www.rockpapershotgun.com 
(rule --> www.rockpapershotgun.com##*[class*="ad-"]), 

the page will show a banner said that I am an ads blocker and when I change the rule to 
--> www.rockpapershotgun.com##*[id^="google_ads_iframe_"], 

the banner is NOT shown. 

I will try to find out which rule make this banner occur.

**Comment by dhowe** [comment]
Try wth a $generichide rule

**Comment by KenLiHK** [comment]
Try to comment different filtering / blocking rules in adnauseam.txt, but the banner is still shown in Firefox and Chrome.

If I unchecked "EasyList", the banner is NOT shown.

**Comment by KenLiHK** [comment]
@cqx931 
Is it case same to #1443 below? Need to discuss with ad-community? Thanks!!

https://github.com/dhowe/AdNauseam/issues/1443#issuecomment-447603403

**Comment by cqx931** [comment]
yes, the ad blocker notice happens to ublock as well. Close this ticket for now.
