### ISSUE TITLE
Ad visible on http://claimbtc.in/bitcoin-faucet

### ISSUE THREAD

**Issue by KenLiHK** [dhowe/AdNauseam#1443]
### Describe the issue
Visble Ad in http://claimbtc.in/bitcoin-faucet

### One or more specific URLs where the issue occurs
http://claimbtc.in/bitcoin-faucet

### Screenshot in which the issue can be seen
Screen in Chrome,
![screen6](https://user-images.githubusercontent.com/24424527/49326885-dfe31900-f593-11e8-90a1-44f3ff77d2d2.png)

Screen in Firefox,
![screen6 firefox](https://user-images.githubusercontent.com/24424527/49326888-e4a7cd00-f593-11e8-9ebc-321cad605ffd.png)

### Steps for anyone to reproduce the issue
1. Add AdNauseam plugin into Chrome / Firefox
2. Enable "HIDE ADS", "CLICK ADS" and "BLOCK MALWARE" in "About" page.
3. Access the URL http://claimbtc.in/bitcoin-faucet

### Your settings
- OS/version: Windows 10 Enterprise
- Browser/version:
  1) Chrome Version 70.0.3538.110 (Official Build) (64-bit)
  2) Firefox 63.0.3 (64-bit)
- AdNauseam version: AdNauseam3.7.802
- Other extensions you have installed: N/A

##### Your filter lists
AdNauseam filters​​​​
EasyList​​​​​
EasyPrivacy​​​​​
uBlock filters​​​​​

uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
My filters​​​​​

Malware Domain List​​​​​
Malware domains

### Your location/country
Hong Kong

**Comment by KenLiHK** [comment]
Cannot go to the website on 08/12/2018. HTTP 500 response code is shown. Will try this website later.

**Comment by cqx931** [comment]
Let's revisit this next week and see whether someone in the ad-blocking community has added any filter for this.

**Comment by dhowe** [comment]
@KenLiHK Again, if it is a problem for uBlock, then we don't have to solve it here.
