### ISSUE TITLE
Ad visible on dailyfreebits.com

### ISSUE THREAD

**Issue by KenLiHK** [dhowe/AdNauseam#1444]
### Describe the issue
Visble Ad in dailyfreebits.com

### One or more specific URLs where the issue occurs
dailyfreebits.com

### Screenshot in which the issue can be seen
Screen in Chrome,
![screen1](https://user-images.githubusercontent.com/24424527/49327173-a4971900-f598-11e8-982d-ef7eb77822fe.png)

Screen in Firefox,
![screen1 firefox](https://user-images.githubusercontent.com/24424527/49327174-a6f97300-f598-11e8-8d94-9b5de8d1b46d.png)

### Steps for anyone to reproduce the issue
1) Add AdNauseam plugin into Chrome / Firefox
2) Enable "HIDE ADS", "CLICK ADS" and "BLOCK MALWARE" in "About" page.
3) Access the URL dailyfreebits.com

### Your settings
- OS/version: Windows 10 Enterprise
- Browser/version:
- Chrome Version 70.0.3538.110 (Official Build) (64-bit)
  1) Firefox 63.0.3 (64-bit)
  2) AdNauseam version: AdNauseam3.7.802
- Other extensions you have installed: N/A

##### Your filter lists
AdNauseam filters​​​​
EasyList​​​​​
EasyPrivacy​​​​​
uBlock filters​​​​​

uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
My filters​​​​​

Malware Domain List​​​​​
Malware domains

### Your location/country
Hong Kong

**Comment by KenLiHK** [comment]
Hiding rules is:
Found these 4 js log message which will show ads,

https://serve.czilladx.com/serve/jslib/fb.js
http://coinad.com/ads/show/topbar.js
https://bitraffic.com/show.js
http://dailyfreebits.com/show_ads.js

!||p3.adhitzads.com/5c0bc5c0d2f07814432490gdailyfreebits.com138772$subdocument
!||p3.adhitzads.com/5c0bc5c16da5d144979549gdailyfreebits.com138772$subdocument

http://coinad.com/ads/show/show.php?a=DIBSFTWTONLMI&b=UN86JOFLKX6EI


filter:
--> https://serve.czilladx.com/serve/jslib/fb.js
--> http://coinad.com/ads/show/topbar.js
--> https://bitraffic.com/show.js
--> http://dailyfreebits.com/show_ads.js

--> ||p3.adhitzads.com*

--> http://coinad.com/ads/show/show.php?a=*

**Comment by cqx931** [comment]
I still see one ad visible and one ad grey ad div after applying the filters.
![image](https://user-images.githubusercontent.com/3056154/50048128-438c3c80-0092-11e9-9708-481d7d9e913f.png)

**Comment by dhowe** [comment]
Maybe I'm  missing something but why would we apply a hiding rules (a cosmetic filter) to a javascript file? These are cosmetic filters which only hide visible things in the DOM. Either you hide a DOM element or you block a script file, no? @KenLiHK @cqx931

**Comment by KenLiHK** [comment]
Understood, hide DOM element and block script file.

**Comment by KenLiHK** [comment]
Fixed and update the following sources,

https://github.com/dhowe/uAssets/pull/80/commits/53ca6cfd1ff029d139a7fce2559f8b7f830037f8

**Comment by Dianna1233** [comment]
Trading is a good thing. I lost a lot before I got to were I am today. if you need assistance on how to trade and recover the money you have lost contact mr kent via his (wisetechbtclordinvestment@ gmail.com) or whatsapp ”(+1 602-638-4243)” to get new amazing strategy, If you are also having problems withdrawing your fund from your Forex/binary trade brokers even when you were given a bonus, just contact me, I have worked with a binary broker for 6years, I have helped a lot of people and I wont stop until I have helped as many as possible, contact me when you need my help
