### ISSUE TITLE
Ad visible on https://bitcoin.treasurebits.net

### ISSUE THREAD

**Issue by KenLiHK** [dhowe/AdNauseam#1445]
### Describe the issue
Visble Ad in https://bitcoin.treasurebits.net

### One or more specific URLs where the issue occurs
https://bitcoin.treasurebits.net

### Screenshot in which the issue can be seen
Screen in Chrome (The ads circled by blue color is a problem in Chrome only),
![screen2](https://user-images.githubusercontent.com/24424527/49327442-c5fa0400-f59c-11e8-8050-bfe4fcb1a01b.png)

Screen in Firefox,
![screen2 firefox](https://user-images.githubusercontent.com/24424527/49327453-ef1a9480-f59c-11e8-8ddf-c4bc6cdcf608.png)

### Steps for anyone to reproduce the issue
1) Add AdNauseam plugin into Chrome / Firefox
2) Enable "HIDE ADS", "CLICK ADS" and "BLOCK MALWARE" in "About" page.
3) Access the URL https://bitcoin.treasurebits.net

### Your settings
- OS/version: Windows 10 Enterprise
- Browser/version:
- Chrome Version 70.0.3538.110 (Official Build) (64-bit)
  1) Firefox 63.0.3 (64-bit)
  2) AdNauseam version: AdNauseam3.7.802
- Other extensions you have installed: N/A

##### Your filter lists
AdNauseam filters​​​​
EasyList​​​​​
EasyPrivacy​​​​​
uBlock filters​​​​​

uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
My filters​​​​​

Malware Domain List​​​​​
Malware domains

### Your location/country
Hong Kong

**Comment by KenLiHK** [comment]
Hiding rules are:

||p3.adhitzads.com/*.treasurebits.net192555$subdocument
||p3.adhitzads.com/5c145871a61d7918204175gbitcoin.treasurebits.net192555$subdocument

||ad.a-ads.com/981390$subdocument
||ad.a-ads.com/984525$subdocument
||ad.a-ads.com/*?size=*$subdocument

||treasurebits.net/images/kucoin1.png$image
||static1.freebitco.in/banners/728x90-3.png$image
||static1.freedoge.co.in/banners/728x90-3.png$image
||static1.freebitco.in/banners/728x90-3.png$image
||allcoins.pw/img/728x90.png$image
||tokenfly.pw/img/728_90.gif$image

||www.bitcoadz.io/display/index.php$subdocument
||www.faucetcrypto.com/banners/img/728x90.gif$image

https://p3.adhitzads.com*
https://ad.a-ads.com*

bitcoin.treasurebits.net###icn5z3b
bitcoin.treasurebits.net###lk6s
bitcoin.treasurebits.net###lks9t
bitcoin.treasurebits.net###nfx3a8o

bitcoin.treasurebits.net##.text-left > center:nth-of-type(2)

bitcoin.treasurebits.net##center:nth-of-type(16) > center > center:nth-of-type(1)
bitcoin.treasurebits.net##center:nth-of-type(16) > center > center:nth-of-type(2)
bitcoin.treasurebits.net##center:nth-of-type(16) > center > center:nth-of-type(3)
bitcoin.treasurebits.net##center:nth-of-type(16) > center > center:nth-of-type(4)

bitcoin.treasurebits.net##.w3-cell-top.w3-cell.w3-light-grey.w3-container:nth-of-type(1)
bitcoin.treasurebits.net##.w3-cell-top.w3-cell.w3-light-grey.w3-container:nth-of-type(3)

bitcoin.treasurebits.net##.w3-cell-top.w3-cell.w3-light-grey.w3-container:nth-of-type(2) > center:nth-of-type(8)

bitcoin.treasurebits.net##img[src="https://treasurebits.net/images/kucoin1.png"]
bitcoin.treasurebits.net##img[src="https://tokenfly.pw/img/728_90.gif"]



filter:
bitcoin.treasurebits.net##.w3-cell-top.w3-cell.w3-light-grey.w3-container:nth-of-type(1)
bitcoin.treasurebits.net##.w3-cell-top.w3-cell.w3-light-grey.w3-container:nth-of-type(3)
bitcoin.treasurebits.net##.w3-cell-top.w3-cell.w3-light-grey.w3-container:nth-of-type(2) > center:nth-of-type(7)
bitcoin.treasurebits.net##.w3-cell-top.w3-cell.w3-light-grey.w3-container:nth-of-type(2) > center:nth-of-type(8)

bitcoin.treasurebits.net##center:nth-of-type(9)
bitcoin.treasurebits.net##.text-left > center:nth-of-type(2)

bitcoin.treasurebits.net##center:nth-of-type(16) > center > center:nth-of-type(1)
bitcoin.treasurebits.net##center:nth-of-type(16) > center > center:nth-of-type(2)
bitcoin.treasurebits.net##center:nth-of-type(16) > center > center:nth-of-type(3)
bitcoin.treasurebits.net##center:nth-of-type(16) > center > center:nth-of-type(4)

bitcoin.treasurebits.net##img[src="https://treasurebits.net/images/kucoin1.png"]
bitcoin.treasurebits.net##img[src="https://tokenfly.pw/img/728_90.gif"]

**Comment by cqx931** [comment]
Let's talk about this in details. The rules you have provided are too specific. Here is a reference of what uBlock blocks for this site, and we can go over each case and see what should be the corresponding solution in Adnauseam.
![image](https://user-images.githubusercontent.com/3056154/50048160-e5ac2480-0092-11e9-9eca-945b451f599f.png)

**Comment by dhowe** [comment]
2 thoughts: 
1. Use generic rules, as @cqx931 suggests (the rules above will likely be irrelevant in a week, and, if similar are added for lots of sites, it will significantly increase the download size of our list). 
2. Lets not spend a lot of time on these crappy bitcoin sites. We are primarily interested in high-profile sites with good content. These should be marked as low priority and addressed only when there is extra time.

**Comment by KenLiHK** [comment]
Refer to the result of uBlock Origin and fine turn the filtering / blocking rules as below,
||p3.adhitzads.com*
||ad.a-ads.com*
||bitcoadz.io*
bitcoin.treasurebits.net##iframe[src*="about:blank"]

**Comment by dhowe** [comment]
We should only use blocking rules  as a LAST OPTION, because this means the ads are not collected. We especially don't want to block entire ad networks across all sites, as this means we will never collect any of their ads.

**Comment by KenLiHK** [comment]
Got it and fine turn the filtering rules as below,
bitcoin.treasurebits.net##*[id^="data_"]
bitcoin.treasurebits.net##iframe[src*="about:blank"]

**Comment by KenLiHK** [comment]
Fixed and committed the following sources,
https://github.com/dhowe/uAssets/commit/a2aa30cfae6fd81036f58eaaaf5982cefb5ecd3b
