### ISSUE TITLE
sffirecu.org - login fields on the homepage of the site of this Credit Union hidden by AdNauseum's generic cosmetic filters.

### ISSUE THREAD

**Issue by elvey** [dhowe/AdNauseam#1447]
### Describe the issue
AdNauseum hides the login fields on the homepage of the site of this Credit Union - sffirecu.org

### One or more specific URLs where the issue occurs
https://www.sffirecu.org/

### Screenshot in which the issue can be seen
![screen shot 2018-12-04 at 5 39 03 pm sffirecu org-nologin](https://user-images.githubusercontent.com/1251130/49560502-96cff380-f90a-11e8-8b8a-5d49b4600423.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1: Open URL.  Notice login fields appear briefly at top, and then disappear.
2:Disable AdNauseum
3:Reopen.  Notice login fields are usable.
### Your settings

- OS/version:macOS 10.14
- Browser/version:Firefox 63.0.3 (64-bit) Quantum
- AdNauseam version:3.7802
- Other extensions you have installed:

##### Your filter lists

    AdNauseam filters​ 311 used out of 322​​​​ EasyList​​​​​85,203 used out of 86,113​​
EasyPrivacy​ ​​​​15,796 used out of 15,833​​
uBlock filters​ ​​​​11,439 used out of 11,530​​
​​.
uBlock filters – Badware risks​ 48 used out of 48​​
uBlock filters – Privacy​​​​​ 144 used out of 148​​
uBlock filters – Resource abuse​​​​​ 160 used out of 287​​
uBlock filters – Unbreak​​​​​ 660 used out of 686​​
    My filters​​​​​0 used out of 0​​​​ 
Malware (2)
    Malware Domain List​​​​​1,093 used out of 1,110​​
Malware domains​
​​​​26,858 used out of 26,858​​​​
### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
SF Bay Area.

**Comment by dhowe** [comment]
If you check the logger, you'll see that 

![image](https://user-images.githubusercontent.com/737638/49567032-81d57d80-f967-11e8-9a07-d52b42b47fe4.png)
