### ISSUE TITLE
Ad visible on sohu.com

### ISSUE THREAD

**Issue by KenLiHK** [dhowe/AdNauseam#1448]
### Describe the issue
Ad visible on sohu.com

### One or more specific URLs where the issue occurs
sohu.com

### Screenshot in which the issue can be seen
##Screen in Firefox (Location: Hong Kong)
![1](https://user-images.githubusercontent.com/24424527/49680104-1d7ffe80-facc-11e8-871c-3be7f17b022e.png)
![2](https://user-images.githubusercontent.com/24424527/49680125-40121780-facc-11e8-9824-a670f1ae8032.png)
![3](https://user-images.githubusercontent.com/24424527/49680131-47392580-facc-11e8-95fb-9341a5e4a173.png)
![4](https://user-images.githubusercontent.com/24424527/49680134-4accac80-facc-11e8-852a-3edc6129a00a.png)
![5](https://user-images.githubusercontent.com/24424527/49680136-4dc79d00-facc-11e8-9f8d-5025ffbed047.png)

##Screen in Firefox (Location: US (by proxy))
![us1](https://user-images.githubusercontent.com/24424527/49680171-b282f780-facc-11e8-864b-54eeb08dd944.png)
![us2](https://user-images.githubusercontent.com/24424527/49680173-b4e55180-facc-11e8-94ef-9c60408e6c5a.png)
![us3](https://user-images.githubusercontent.com/24424527/49680174-b878d880-facc-11e8-855d-ddb2e0299735.png)
![us4](https://user-images.githubusercontent.com/24424527/49680175-badb3280-facc-11e8-89ba-b55982194fe0.png)
![us5](https://user-images.githubusercontent.com/24424527/49680178-bd3d8c80-facc-11e8-8f79-f3e8cbec0119.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1.	Add AdNauseam plugin into Firefox
2.	Enable "HIDE ADS", "CLICK ADS" and "BLOCK MALWARE" in "About" page.
3.	Access the URL sohu.com

### Your settings
•	OS/version: Windows 10 Enterprise
•	Browser/version: Firefox 63.0.3 (64-bit)
•	AdNauseam version: AdNauseam3.7.802
•	Other extensions you have installed: N/A

##### Your filter lists
AdNauseam filters
EasyList
EasyPrivacy
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
My filters
Malware Domain List
Malware domains

### Your location/country
Hong Kong / US (by proxy)

**Comment by KenLiHK** [comment]
Hiding rules should be:

||643108e7617ef.cdn.sohucs.com/899e889f3503422db77179c1c5817e9a.jpg$image
||643108e7617ef.cdn.sohucs.com/*.jpg$image
||5b0988e595225.cdn.sohucs.com/c_fill,w_320,h_220,g_faces,q_70/images/20181208/2021a0e25f294066a89e707bb35df4cc.jpeg$image
||5b0988e595225.cdn.sohucs.com/c_fill,w_300,h_150,q_70,g_faces/images/20181208/58dcd52b0a564c9e8372cdac6657a2b9.jpeg$image
||5b0988e595225.cdn.sohucs.com/c_fill,w_*,h_*,g_faces,q_70/images/20181208/*.jpeg$image
||643108e7617ef.cdn.sohucs.com/805457cd410b49ee97f025d722321a07.jpg$image

filter:
--> ||*.cdn.sohucs.com/*image
--> www.sohu.com##.left.god-head
--> www.sohu.com##.clearfix.god-main.area.god-wrapper


www.sohu.com##iframe[src^="//static-alias-1.360buyimg.com/jzt/tpl/sspPic.html?ad_ids=3136:5&adflag=0&clkmn=&expose=&clkm=%2F%2Fi.go.sohu.com%2Fcount%2Fc%3Fsource%3D0%26newsid%3D%26subid%3D%26aid%3D101112361%26apid%3Dbeans_15538%26impid%3D0bc4a2ccbc04f28dd_0_0%26mkey%3D0bc4a2ccbc04f28dd_0_0%26freq%3D0%26ax%3D1241.5%26ay%3D797%26ed%3D%26bucket%3D%26ext%3De%253DOyygn03WYDL%252BVv%252F3mNEQdpe7ntxs1Fh6wvGbHWbgEJqWgDys2ryBAqg1sLr17PXfNhC79pRApjI9A1cacpcd9Kz8ZGocLoi2%252FcleTWtywV%252B2CCSNrcCVDA4GU74d5KJB1X78YK2f9DfEA30%252FTClDRbc0VcMCjkEbeWmnkeu%252Fctd6Ym16cYumKHbMJkYUGXq7i637qNMCUsAVcbEl0bKPtPeKclPXO2mswn1Mzr0y14np4aCUi%252BE81fLGiGDEZnOV9S%252B%252FH%252BvgnYcQBTAuMkkDqa7lchiUNM%252FcgWb5Ahp1Q9%252BgYXnFlpJg%252FzAetMPklx7TUHEIBMXd%252BfKYpB%252BlO%252FMz%252FmaWVNKnzAkLq7x5cvgujQqlNQV0FMNT82yE2hEAI7ZnPl3q1vtFnfRJy8VSaDtOOaLfnmSIHbttc9RM6J%252BHeO%252Fk3vspYUvtYdVF8PoEXampo843xvExDLZMJKYVesYGlVtgShyoWMcr%252BbgLQJfLBUMw0nVwgwaLn4UuNMaKkhrXOOMr90TkIp7rSIgjM6gS5ek2x%252FxCmrKFVAVLuJnx61SMwMwV6H3Pv3RpMPJYiRx3QZq1XMgN2npyvR7ER1vWPkOOhOXZT6"]

filter:
--> ||static-alias-1.360buyimg.com/jzt/tpl/sspPic.html
--> www.sohu.com###god_1


www.sohu.com##iframe[src^="//images.sohu.com/bill/s2017/front/2769.html?clkm=%2F%2Fi.go.sohu.com%2Fcount%2Fc%3Fsource%3D0%26newsid%3D%26subid%3D%26aid%3D101106790%26apid%3Dbeans_15539%26impid%3D04c95d13e5eba4744_0_0%26mkey%3D04c95d13e5eba4744_0_0%26freq%3D0%26ax%3D1241.5%26ay%3D1820%26ed%3D%26bucket%3D%26ext%3De%253DOyygn03WYDL%252BVv%252F3mNEQdoJEq9EEyoKlRzG4U2jFypSeItB28YzKCWIBDmHhP8k%252BrIAMgVDwgrlUalkoJeHCG3JHgys211YcbQwsoUQumEBCx14JUPCzGYIzQ93%252BNoVkOkznDSbaDotnnsj9NfDC1QwNo7XicrYxnGQQZLmBo5pEw32AYjft5sT%252FiMN7%252FLtrv6ZnxxfnGHB720dHbHRKRBdwQnbxKQoahqyo2I%252FPPGVPogGAcSYnP%252Bh%252FS%252BHExR2lSYommkg64U9bJmsvIAlBmw1BvIpoUxIrZluw%252B%252FbHS275EWedtY9ULWsNbZF5ImGjiHJ%252FiQwTlSpIEoE2DyXsDXMWDHvI7KEzD0QsfEc76jGZviK8KRBTeHudY6LZUabZIUNqfpGG2RbG6wydLjLhs7NVP3KaI2EUqn1fQx0%252FbxBtzFF4tPIrNc%252FIASr6b9dr8HbD0kHfdoQNJbQ9xOwjLWdi%252FHBZ6KZzTevnigZn7wog%252Fw3udHZQVxvLUq3oLfonRmoOj0%252ByRNIC1fWo%252Fnj2sdldhlBj3w6S0Gzht3uaa7PvbJ0HQycxxP5mGCW6mQZj9tkqtSDyiVAX8PO6%252FySeoumJucNnU1JzIM2EDCxs%252FNHAdpQMPVMr7D3pw5X1SZvAz5ChOyHQt"]


www.sohu.com##iframe[src^="//images.sohu.com/bill/s2017/jingyanli/1711/23.html?clkm=%2F%2Fi.go.sohu.com%2Fcount%2Fc%3Fsource%3D0%26newsid%3D%26subid%3D%26aid%3D101106650%26apid%3Dbeans_15634%26impid%3D0d1ecdc0bcf903594_0_0%26mkey%3D0d1ecdc0bcf903594_0_0%26freq%3D0%26ax%3D361.5%26ay%3D3752%26ed%3D%26bucket%3D%26ext%3De%253DOyygn03WYDL%252BVv%252F3mNEQdiRwjtdm4Itl5Tn2wZ36TcKvM0UCxSZGhWPhFVFcTnWXEBlhGM3fvdRiKm7yxWRxeCj3bJwuPpAZBou0niojxKWD7xKvojSZJi0wZwHhxkWj21kyp5REN0upQoQI0YZ%252Fg8pNmOcll2MTozkFL2GtGuNmh62Zm4aiSJmO4bW%252BkWu0Ryg2gCsN5tw911lJ2cWxMojf7aZigVLXb5UFyVKqliAAX4tLLiP0%252Fux509FPw8Zy5qGaHyAkm%252BCXUTjpJ%252FVFGsSPcQYUuLJQJs16GJMZg2VdSaf2BrJif3jy2vyvCzRfsyjqk%252FDSNR0yGBVxq20%252BtU3AijqOKlI1YXCIxcuGBZgXyH4QcRSwKMCC%252FKQR7A55Zw7fEnggljKINtXtkTBO%252BwU3WP6okXn3vzo9%252BRk7wPvEEs%252BFVDOf2Leh%252BRtOuWlXF5OOP49UJamZgdllCwkvuq6Xkb9wQqeWV0Nl%252Bu2GdMT2T0o%252B%252Fet4bBm0KEWF5LPEbo71wMY5VNl3sEKibUGxSVd8DWcPqdOu%252F7xhlOkJpqIL%252BO05dWhS2kVQed%252BlnLTxfywwI8HIHt6w9uegnKTJ%252FoszAZu%252FVlhanJDnm74ilXmsbNRaE9IJ%252Fc0gOAW"]

filter:
--> www.sohu.com##.area.clearfix.god-wrapper:nth-of-type(10) > .god-main
--> www.sohu.com##.godR.bordR:nth-of-type(5)
--> www.sohu.com##.godR.bordR:nth-of-type(7)
--> www.sohu.com##.godR.bordR:nth-of-type(9)
--> www.sohu.com##.god-main:nth-of-type(8)
--> www.sohu.com##.god-main:nth-of-type(5)
--> www.sohu.com##.clearfix.area.god-wrapper:nth-of-type(7)
--> www.sohu.com##.area.clearfix.god-wrapper:nth-of-type(10)
--> www.sohu.com##.god-main-top.god-main
--> www.sohu.com##.area.god-cut

**Comment by cqx931** [comment]
All these ads should be blocked by CHN: EasyList China (中文), we are not going to add them specific for adnauseam. Please double check that you enable language specific filters before the testing.

**Comment by dhowe** [comment]
Correct. But again, use more generic filters when possible - instead of the 10 filters above, the ones below captures nearly all the cases:

    www.sohu.com##*[class^="god"]
OR
    www.sohu.com##*[class*="god"]

**Comment by KenLiHK** [comment]
Sally, you are correct. I find that there is a checkbox called "CHN: EasyList China (中文)", when I checked it and test the page again, all ads are blanks and aligned to uBlock Origin. Sorry for inconvenience caused.

Please refer to the following screen captures.
![sohu](https://user-images.githubusercontent.com/24424527/50732638-e92a5b80-11b9-11e9-8688-86768c27dfc1.png)

**Comment by cqx931** [comment]
great, I will close this ticket
