### ISSUE TITLE
Ad visible on zol.com.cn

### ISSUE THREAD

**Issue by KenLiHK** [dhowe/AdNauseam#1449]
### Describe the issue
Ad visible on zol.com.cn

### One or more specific URLs where the issue occurs
zol.com.cn

### Screenshot in which the issue can be seen
Screen in Firefox (Location: Hong Kong),
![1](https://user-images.githubusercontent.com/24424527/49680308-017d5c80-face-11e8-8af4-50d927c764e0.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1.	Add AdNauseam plugin into Firefox
2.	Enable "HIDE ADS", "CLICK ADS" and "BLOCK MALWARE" in "About" page.
3.	Access the URL zol.com.cn

### Your settings
•	OS/version: Windows 10 Enterprise
•	Browser/version: Firefox 63.0.3 (64-bit)
•	AdNauseam version: AdNauseam3.7.802
•	Other extensions you have installed: N/A

##### Your filter lists
AdNauseam filters
EasyList
EasyPrivacy
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
My filters
Malware Domain List
Malware domains

### Your location/country
Hong Kong (Remark: This ads is not visible in US location)

**Comment by KenLiHK** [comment]
Hiding rules should be:

www.zol.com.cn##.today-hot-layer
www.zol.com.cn##.clearfix.wrapper:nth-of-type(5) > div > .gmine_ad


filter:
--> www.zol.com.cn##.today-hot-layer
--> www.zol.com.cn##.clearfix.wrapper:nth-of-type(5) > div > .gmine_ad

**Comment by cqx931** [comment]
I don't think this needs to be blocked.
1) This div is not blocked in uBlock
2) It contains links to content within the site.

If this is clear, please close this ticket afterwards.

**Comment by dhowe** [comment]
Reminder 1 : we generally don't block things that are not blocked in uBlock (with the same lists). These are list problems, not ADN problems.

Reminder 2: we do not block/collect internal links (ads that link directly to the same domain as the page. The only exception to this is when the link is always redirected outside the domain, e.g., Google)

**Comment by KenLiHK** [comment]
Understood and sorry for inconvenience caused.
