### ISSUE TITLE
Consider default lists to be included with AdNauseam

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#145]
This is a pretty important question to be determined before launch. Each list maybe enabled (mode1) fully or, (as of a recent commit), just for hiding (mode2), so as not to block ads we need to collect.  We will definitely enable EasyPrivacy (with minor real-time modifications, for blocking of non-visual trackers) in mode1, and EasyList (for ad-detection via cosmetic filters) in mode2.  All other lists, enabled by default, or by the user, are automatically put into in mode 2, so as not to block ads. However, I would argue for including additional lists in mode1, such as https://github.com/gorhill/uBlock/wiki/Badware-risks, for example. 

Also, in terms of design, we need to either a) not allow disabling of EasyList in settings (as no further ads will be collected and it will appear as if ADN is broken), or show a warning when the user tries to do this. Thoughts @mushon ?

**Comment by mushon** [comment]
I am not an expert in block lists but as for the EasyList policy, I would vote for warning and not prevent disabling the list. For example if a better alternative for the basic list appears we should allow users to switch these two. Maybe we need another alert when no list is chosen or something like that?

**Comment by dhowe** [comment]
EasyPrivacy: We are keeping an array of block lists that DO NOT block ads in the code. So far this only EasyPrivacy but we could add to it over time. The blocking rules for any lists NOT in that array will be ignored. Thus currently if EasyPrivacy is disabled, then no blocking will occur.  However, I intend to add 'Badware-risks' to this array in the next release.

EasyList: This is where most of our Hiding rules come from. If this is disabled, then ADN will appear to be broken as no ads will be collected. So I agree that we need a warning when the user tries to do this. If you add this div to the page as hidden, then I will activate it via JS...

**Comment by dhowe** [comment]
We need to address this in the UI. We don't want users trying AdNauseam, picking a few random lists (possibly disabling EasyPrivacy) and then thinking that the tool is just 'broken'.

**Comment by mushon** [comment]
Design:
![popup-easylist-notice](https://cloud.githubusercontent.com/assets/27123/15736912/94f1e884-28ab-11e6-8f69-00fe0a6a48da.png)

If it is still not activated (as in "I know what I'm doing"):
![popup-easylist-note](https://cloud.githubusercontent.com/assets/27123/15736975/f858bc18-28ab-11e6-8d7f-eea80de5ac92.png)

**Comment by dhowe** [comment]
This looks good to me for the menu, however, we need some type of notice on the options page (under 3rd party filters), which is where the selection is actually made.

**Comment by mushon** [comment]
I've added the ``.alert.warning`` div to dashboard.html in 9003f831342c7482b7ef0e28c91aa583b74a528b
Take it away @dhowe (and let me know if you think the menu warnings are still needed)

**Comment by dhowe** [comment]
done in #32b9075
