### ISSUE TITLE
Ad visible on salon.com

### ISSUE THREAD

**Issue by KenLiHK** [dhowe/AdNauseam#1451]
### Describe the issue
Ad visible on salon.com

### One or more specific URLs where the issue occurs
salon.com

### Screenshot in which the issue can be seen
Screen in Firefox (Location: US (by proxy)),
![1](https://user-images.githubusercontent.com/24424527/49680488-b95f3980-facf-11e8-8b3e-9ed975d7a2ea.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1.	Add AdNauseam plugin into Firefox
2.	Enable "HIDE ADS", "CLICK ADS" and "BLOCK MALWARE" in "About" page.
3.	Access the URL salon.com

### Your settings
•	OS/version: Windows 10 Enterprise
•	Browser/version: Firefox 63.0.3 (64-bit)
•	AdNauseam version: AdNauseam3.7.802
•	Other extensions you have installed: N/A

##### Your filter lists
AdNauseam filters
EasyList
EasyPrivacy
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
My filters
Malware Domain List
Malware domains

### Your location/country
US (by proxy)

**Comment by KenLiHK** [comment]
Cannot simulate the case on 08/12/2018.

**Comment by KenLiHK** [comment]
Cannot simulate the case on 15/12/2018.

**Comment by cqx931** [comment]
I can't reproduce this as well, close for now
