### ISSUE TITLE
Verify new facebook layout doesnt break anything

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1452]
![image](https://user-images.githubusercontent.com/737638/49693415-14b32980-fbad-11e8-8620-1ac5121b444c.png)

**Comment by KenLiHK** [comment]
**Describe the issue**
Ad visible on facebook.com

**One or more specific URLs where the issue occurs**
facebook.com

**Screenshot in which the issue can be seen**
##Screen in Firefox (Location: Hong Kong)
![ads_in_fb](https://user-images.githubusercontent.com/24424527/51068504-14012d80-165a-11e9-9b9e-3ea0ac3660f3.png)

**Steps for anyone to reproduce the issue**
(Please be as detailed as possible)

1. Add AdNauseam plugin into Firefox
2. Enable "HIDE ADS", "CLICK ADS" and "BLOCK MALWARE" in "About" page.
3. Login to access the URL facebook.com

**Your settings**
•	OS/version: Windows 10 Enterprise
•	Browser/version: Firefox 63.0.3 (64-bit)
•	AdNauseam version: AdNauseam3.7.802
•	Other extensions you have installed: N/A

**Your filter lists**
AdNauseam filters
EasyList
EasyPrivacy
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
My filters
Malware Domain List
Malware domains

**Your location/country**
Hong Kong

**Comment by dhowe** [comment]
Lets go ahead and fix this...

**Comment by KenLiHK** [comment]
I try to add some filter "www.facebook.com##*[id^="hyperfeed_story"]", it will keep looping and refresh page. 

The "Vita Family" actually is a facebook page, it is not redirecting to pages in other domain. I think we do not need to fix it.

**Comment by dhowe** [comment]
Ok, if it an internal, then no need to fix. But why create a ticket then?
