### ISSUE TITLE
'My filters' don't work in Firefox

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1453]
### Describe the issue
Filters that work in chrome are not triggered in Firefox if added in 'My Filters'.
This applies both to blocking rules and hiding rules.

- Browser/version:
Firefox

- AdNauseam version:
v3.7.802

Update:
The issue should be related to vAPI.cacheStorage

**Comment by dhowe** [comment]
Is this an issue you experienced, @cqx931  ?

**Comment by cqx931** [comment]
Yes, this happened when I was checking the ad visible issues.

**Comment by cqx931** [comment]
This issue should be related to vAPI.cacheStorage.
After clicking "Apply changes" in My Filters, adnauseam will reload all the filters. In firefox, this will trigger an update through vAPI.cacheStorage, which might be related to this issue.
Meanwhile, blocking and hiding through other UI work as expected(from logger or right click), which trigger the same saveUserAsset() function in asset.js as "Apply changes" but won't reload all filters and update cache.

Still need to figure out how vAPI.cacheStorage is influencing the current parsed filters.

**Comment by cqx931** [comment]
This seems to be solved in the latest master branch. Close for now.
