### ISSUE TITLE
Invisible settings tabs

### ISSUE THREAD

**Issue by Hovborg92** [dhowe/AdNauseam#1455]
### Describe the issue
The tabs on the settings page are not visible. They are visible only once at launch after installation.

### One or more specific URLs where the issue occurs
Not applicable.

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/46073384/50377499-a9427080-061e-11e9-936e-c8fad0667d19.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
Firefox Menu --> Extensions manager --> AdNauseam --> Options

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 64.0
- AdNauseam version: 3.7.802
- Other extensions you have installed: Colorfultabs, Dashlane, Firefox Notes, Lilo, Notifier for Gmail, Signal Spam, snoozetabs, Tab Mix, Test Pilot, Tile Tabs WE and TrackMeNot.

##### Your filter lists

I can not access the filter lists (no tab).
### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

**Comment by cqx931** [comment]
From where do you try to acess the settings page?
If you try to open it from the menu, adnauseam should open "dashboard.html#options.html" and the tabs should be there. In your case, it seems like the link you clicked is directing you to "options.html" directly.

**Comment by dhowe** [comment]
Thanks @MaxValue ... good find. Do you want to submit a [pull request](https://help.github.com/articles/about-pull-requests/)?
