### ISSUE TITLE
Note: There is a way to install the CRX on Google Chrome (no developer warning!)

### ISSUE THREAD

**Issue by UnicornsOnLSD** [dhowe/AdNauseam#1456]
Currently, the wiki says that to install the extension on Chrome, you have to load the unpacked extension. The issue with this is that you get an annoying popup every time you start chrome. There is a way to install the CRX in Chrome, stopping the popup.

## What I did
First, I built the extension from the unpacked files in the extensions menu. Then, I followed [this guide](https://productforums.google.com/forum/#!msg/chrome/9NlMAr6uEVc/ambkrcKpi1cJ) on how to whitelist the extension as by default, Chrome blocks the extension from running as a "security measure". Note that some directories from the policy_templates.zip archive are different from the ones listed in the guide. After that, the extension worked perfectly and I no longer had the popup.

I'm making this issue because AFAIK, I can't make a pull request to edit the wiki. If there is a way for me to do that, I'd happily write a little guide on how to do it properly :)

**Comment by UnicornsOnLSD** [comment]
I made a little guide. I modified the markdown of [this page](https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission) to add the guide. Apparently, you can't fork/PR wikis :p 

[Download the page.](https://github.com/dhowe/AdNauseam/files/2706224/Install-AdNauseam-on-Chrome-Without-Google.s-Permission.txt)

**Comment by dhowe** [comment]
thanks for this
@cqx931 can you give this a test ?

**Comment by UnicornsOnLSD** [comment]
I saw that you added the guide to the wiki. Thanks!
Only other tiny issue is that it says "This is indeed annoying, as Google intends, however there is no workaround we are aware of at this time" at the end of the first guide, but that's just a nitpick.

**Comment by dhowe** [comment]
@cqx931 did you get a chance to test this?
