### ISSUE TITLE
Problems on Yahoo page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1460]
3 problems:

![image](https://user-images.githubusercontent.com/737638/51827323-12a35680-2324-11e9-8338-66b3a8be451d.png)

**Comment by dhowe** [comment]
note: you will need to create a yahoo account to test

**Comment by KenLiHK** [comment]
I cannot simulate the case. Please refer to the screen capture.

![yahoo](https://user-images.githubusercontent.com/24424527/52159369-72ac4b00-26de-11e9-809c-a808b585b258.png)
