### ISSUE TITLE
Google ads visible on TheFreeThoughtProject.com

### ISSUE THREAD

**Issue by BikyAlex** [dhowe/AdNauseam#1462]
### Describe the issue
AdNauseam hides only a few Google Ads on TheFreeThoughtProject, mostly at random (explanation under screenshots)

### One or more specific URLs where the issue occurs
https://thefreethoughtproject.com/shutdown-spending-government/
https://thefreethoughtproject.com/top-fda-official-blows-whistle-as-agency-approves-drug-10x-worse-than-fentanyl-funded-by-dod/

### Screenshot in which the issue can be seen
![screenshot_20190128_085025](https://user-images.githubusercontent.com/17931169/51820207-a867c300-22dd-11e9-8838-bbadb0b4f1bf.png)
![screenshot_20190128_085238](https://user-images.githubusercontent.com/17931169/51820188-a00f8800-22dd-11e9-8564-980d76d5a5e5.png)
As you can see, in the first screenshot, the right-side banner is hidden (and you can't see, but the top ad is hidden as well), but after a page refresh, in those spots, ads can be spotted again. The rest of the ads on the page are not hidden. Another page refresh sometimes hides the top and right side ads, but it's mostly at random, while the rest of the ads are always shown.

### Steps for anyone to reproduce the issue
Visit the pages linked above.

### Your settings
- OS/version: Ubuntu 18.04
- Browser/version: Firefox 64.0 (x64)
- AdNauseam version: 3.7.802
- Other extensions you have installed: Dark Background and Light Text 0.6.10 (disabled from its own quick settings during testing)
- Other settings: using a Squid HTTP and HTTPS proxy to reach the internet

##### Your filter lists
No filters (default / stock AdNauseam)

### Your location/country
Romania - Bucharest

### Note
It seems to be an Ubuntu / Firefox for Linux issue only, AdNauseam works as expected on Windows.

**Comment by dhowe** [comment]
Confirmed (on OS X)...
