### ISSUE TITLE
Detect/warn for Firefox Tracker blocking

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1464]
We need to warn the user (similar to ublock,adblock, etc) that this setting will interfere with AdNauseam's working (only in the case where 'trackers' is selected')

![image](https://user-images.githubusercontent.com/737638/52763143-91530000-3055-11e9-89e5-655febf2a344.png)

**Comment by cqx931** [comment]
What will be the warning message? 
"Your 'Content Blocking' setting will interfere with AdNauseam"? 
I have also created an entry in FAQ page: https://github.com/dhowe/AdNauseam/wiki/FAQ#why-adnauseam-does-not-work-with-certain-firefox-settings

**Comment by dhowe** [comment]
How about: "The 'Content Blocking' settings in your browser may interfere with AdNauseam" ?

And great on the FAQ.... I've added an answer, which you can check/adjust

**Comment by cqx931** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites
"trackingProtectionMode" seems like the property we need to check.

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/AdNauseam/pull/1477

**Comment by cqx931** [comment]
done

**Comment by 0xadada** [comment]
If something manages to pass through the browsers `tracking protection mode` filter, will AdNauseam have an opportunity to block it?

**Comment by dhowe** [comment]
Good question -- its possible, but its not something we've tested. The order of operation of addons is not determined by the spec, so we don't know whether, say, uBlock or AdNauseam will run first (this is one reason we don't recommend using them together, as the results are not predictable). I'm not sure whether Firefox tracker blocking works via the same mechanism or runs before all addons. If the former, then we're not sure, if the latter, then yes. But again, _not_ recommended if you want AdNauseam to work optimally.
