### ISSUE TITLE
Check permissions requested on installation

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1466]
from [hacker news thread](https://news.ycombinator.com/item?id=19278936):

> Amazing concept. My only problem is the permissions it's asking while I tried to install it on firefox.
> 
> - Access your data for all websites [You could take away my passwords]
> 
> - Download files and read and modify the browser’s download history [Why?]
> 
> - Access browser activity during navigation [Why?]

**Comment by cqx931** [comment]
![image](https://user-images.githubusercontent.com/3056154/53661727-09611e80-3c2f-11e9-9f72-9c30de6ad46e.png)
![image](https://user-images.githubusercontent.com/3056154/53661822-57762200-3c2f-11e9-9fe3-1dc3afdca7ca.png)
https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions

A comparison between the manifest.json file for web extensions: [ublock](https://github.com/gorhill/uBlock/blob/master/platform/webext/manifest.json#L78)
 & [AdNauseam](https://github.com/dhowe/AdNauseam/blob/master/platform/webext/manifest.json). 
- Access your data for all websites -> "<all_urls>"
- Access browser activity during navigation ->  "webNavigation"

These two permissions are shared by AdNauseam and uBlock. I don't think there is any way we can remove those.

* Download files and read and modify the browser’s download history ->  "downloads"

This is unique to AdNauseam, but we need it to download all the ads. Although I was wondering why uBlock don't have this permission for backing up all the settings. Is it related to the file size?

**Comment by dhowe** [comment]
Yes, that is a good question. Can you try to remove that permission, then do the settings and advault save?

**Comment by cqx931** [comment]
In merge1.17.0 I have removed the download permission and both settings/advault save work well without it.

**Comment by dhowe** [comment]
Great
