### ISSUE TITLE
Ads block scrolling, but are hidden

### ISSUE THREAD

**Issue by VjyedSC0UFMc8z** [dhowe/AdNauseam#1467]
### Describe the issue
Many iframe ads on https://www.businessinsider.com seem to cover the whole page and block scrolling with attribute scrolling="NO". AdNauseum blocks them, but scrolling is still locked.

### One or more specific URLs where the issue occurs
https://www.businessinsider.com/jeff-bezos-wife-mackenzie-2017-11
https://www.businessinsider.com/subtle-signs-you-are-about-to-be-fired-2018-1
any story

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version:
Windows 10

- Browser/version:
Chrome Version 72.0.3626.121 (Official Build) (64-bit)

- AdNauseam version:
AdNauseam v3.7.802

- Other extensions you have installed:

##### Your filter lists
Default

### Your location/country
Philadelphia, PA, USA

**Comment by dhowe** [comment]
I am unable to recreate this... page works OK for me in both AdNauseam (and ublock).
Can you give a try from the US, @cqx931 ?

**Comment by cqx931** [comment]
I can't reproduce this as well.
