### ISSUE TITLE
party.pl

### ISSUE THREAD

**Issue by krystian3w** [dhowe/AdNauseam#1475]
### Describe the issue

bad generic filter: `##DIV[id^="ad_"]`

### One or more specific URLs where the issue occurs

`https://party.pl/newsy/co-oznacza-besos-magda-gessler-tlumaczy-98009-r1/`

### Screenshot in which the issue can be seen

![obraz](https://user-images.githubusercontent.com/35370833/54725541-bfa18f00-4b6f-11e9-854c-5c1d87341d93.png) |
--- |

Header, footer, so where is main content of site?

### Steps for anyone to reproduce the issue

obviously, no need step by step instruction

### Your settings

- OS/version: Windows 7
- Browser/version: Firefox 66
- AdNauseam version: 3.7
- Other extensions you have installed: none

##### Your filter lists

Default

### Your location/country

Poland

**Comment by dhowe** [comment]
Can this be solved with a 'generichide' filter for the site ?

**Comment by krystian3w** [comment]
I try latter see how many elements must again blocked after use generichide.

**Comment by cqx931** [comment]
I do agree that `##DIV[id^="ad_"]` is too generic so I changed a few filters to domain specific ones. https://github.com/dhowe/uAssets/commit/d2af9370511cf0e6c7648957bff96298d2dea73c

After making that change, I can see a video playing on the right corner, is that an ad or not?@krystian3w

**Comment by krystian3w** [comment]
I suppose self-promotion - Polish advert lists no cut this, but Polish Annoyance filter block this by CSS filter / scriplet filter:

```
gotujmy.pl,party.pl,polki.pl,viva.pl,wizaz.pl##+js(addEventListener-defuser.js, scroll, d.stopPropagation)
```
