### ISSUE TITLE
podstacja.com

### ISSUE THREAD

**Issue by krystian3w** [dhowe/AdNauseam#1476]
### Describe the issue

Anti-adblock Pop-up

### One or more specific URLs where the issue occurs

`https://podstacja.com/`

### Screenshot in which the issue can be seen

![obraz](https://user-images.githubusercontent.com/35370833/55264650-66271780-5275-11e9-8638-7a3e41334609.png)

### Steps for anyone to reproduce the issue

obviously, no need steep by steep

### Your settings

- OS/version:
- Browser/version: Firefox 66.0.2
- AdNauseam version: 3.7
- Other extensions you have installed: -

##### Your filter lists

Default + PL

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

Poland

----

"Bad" filter in AdNauseam: `##*[class^="adsby"]`

```
podstacja.com#@#*[class^="adsby"]
```

**Comment by dhowe** [comment]
Does this happen with ublock origin ?

**Comment by krystian3w** [comment]
Yes - website detect hidden elements with classes `.reklama` / `.adsbygoogle` in EasyList / Polish filter list, but I do not have how many Poles use  AdNauseam with activated `AdNauseam filters`.

@mapx- / @okiehsch.

**Comment by mapx-** [comment]
for anti adb seems working 
```
@@||podstacja.com^$generichide
podstacja.com##.adsbygoogle
```
