### ISSUE TITLE
Zoom in on Ad image when hover over ad in menu

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#148]
Ad images are often too small to see in the menu. Would be nice if on a mouse-over the ad image expanded to full size.

This is an [example](http://jsfiddle.net/27Syr/1206/)
however it should zoom to full size (100%) at least

**Comment by cqx931** [comment]
zoom to full size when the ad is smaller than it's full size:
https://github.com/dhowe/AdNauseam/pull/373/commits

**Comment by cqx931** [comment]
here is another try out of the zooming effect in menu:
how the zooming looks like in different situations
<img width="275" alt="screen shot 2016-09-08 at 9 37 18 am" src="https://cloud.githubusercontent.com/assets/3056154/18334231/88af95cc-75a8-11e6-915e-b11f2c7d8431.png">
<img width="263" alt="screen shot 2016-09-08 at 9 37 25 am" src="https://cloud.githubusercontent.com/assets/3056154/18334232/89e4b08a-75a8-11e6-97fe-195ef4c043ad.png">
wide horizontal ads
<img width="261" alt="screen shot 2016-09-08 at 9 36 26 am" src="https://cloud.githubusercontent.com/assets/3056154/18334235/8d41b638-75a8-11e6-8658-a5a65b53b083.png">
<img width="263" alt="screen shot 2016-09-08 at 9 36 33 am" src="https://cloud.githubusercontent.com/assets/3056154/18334237/8ec8f566-75a8-11e6-97bc-2f3b718f9077.png">
long vertical ads
<img width="264" alt="screen shot 2016-09-08 at 9 38 57 am" src="https://cloud.githubusercontent.com/assets/3056154/18334240/90134eda-75a8-11e6-9ce1-8e2c1b363cf1.png">
<img width="266" alt="screen shot 2016-09-08 at 9 39 35 am" src="https://cloud.githubusercontent.com/assets/3056154/18334241/90d69502-75a8-11e6-8b8e-4ddd093ea69b.png">
