### ISSUE TITLE
wiadomosci.radiozet.pl

### ISSUE THREAD

**Issue by krystian3w** [dhowe/AdNauseam#1480]
### Describe the issue

Blank elements by generic filter.

```
wiadomosci.radiozet.pl#@#DIV[class*="advert"]
```

### One or more specific URLs where the issue occurs

`https://wiadomosci.radiozet.pl/`

### Screenshot in which the issue can be seen

![obraz](https://user-images.githubusercontent.com/35370833/55569551-0c55a000-5702-11e9-9979-27f5b5cb3f35.png) |
--- |

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

N/A

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 66.0.2
- AdNauseam version: 3.7.8
- Other extensions you have installed: N/A

##### Your filter lists

Default + PL

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

Poland

**Comment by dhowe** [comment]
Perhaps this can be fixed with a generichide filter (and possibly domain-specific rules for any ads that persist) ?

**Comment by cqx931** [comment]
this is fixed here: https://github.com/dhowe/AdNauseam/pull/1535/commits/b2c9bc3769ade88a3a80c5d5d00c0d344105da7e
