### ISSUE TITLE
overwatch.pl

### ISSUE THREAD

**Issue by krystian3w** [dhowe/AdNauseam#1484]
### Describe the issue

anti-adblock gernerated by EasyList and AdNauseam lists.

![obraz](https://user-images.githubusercontent.com/35370833/56081954-5847c980-5e13-11e9-89a8-b96f92f029f6.png) |
--- |

```
overwatch.pl#@#.rightAd
overwatch.pl#@#.mini-ad 
overwatch.pl#@#.bottomAd
overwatch.pl#@#.adlabel 
overwatch.pl#@#.advertbox3 
overwatch.pl#@#.sky_advert 
overwatch.pl#@#.top_ad_game


overwatch.pl#@#*[class^="adsby"]


overwatch.pl#@#DIV[class*="advert"]
```

The official issue tracker for uBlock Origin is at:

https://github.com/uBlockOrigin/uBlock-issues/issues

### Screenshot in which the issue can be seen

`https://overwatch.pl/`

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

No needed?

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 66.0.3
- AdNauseam version: 3.7.802
- Other extensions you have installed: -

##### Your filter lists

Default filter lists + PL

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

Poland.

**Comment by dhowe** [comment]
Does this happen with uBlock Origin?

**Comment by krystian3w** [comment]
Yes, because script detect most EasyList generic cosmetic filters.

**Comment by dhowe** [comment]
Seems like an issue for EasyList ...
