### ISSUE TITLE
korzystneit.pl/contact

### ISSUE THREAD

**Issue by krystian3w** [dhowe/AdNauseam#1485]
`https://korzystneit.pl/contact`

generic filter `##*[class^="google"]` hide on  Google map button "see bigger map"

![obraz](https://user-images.githubusercontent.com/35370833/56082779-2f2c3680-5e1d-11e9-9854-4606d508af03.png) |
--- |

Fix this problem:

`www.google.*#@#*[class^="google"]`

**Comment by dhowe** [comment]
Should be fixed. Please update AdNauseam filters and recheck...
