### ISSUE TITLE
Banned in FF?

### ISSUE THREAD

**Issue by belegnar** [dhowe/AdNauseam#1487]
![1](https://user-images.githubusercontent.com/263551/57188745-813c1580-6f0c-11e9-98b1-fa4027c949e3.png)

- OS/version: ubuntu 14.04
- Browser/version: FF 66.0.3
- AdNauseam version: latest?
- Other extensions you have installed: none

**Comment by belegnar** [comment]
Also, it is not possible to reinstall addon from FF store. The page opens but download is failed with connection error

**Comment by dc911x** [comment]
@belegnar AdNauseam isn't banned in FF, on Friday May 3rd, there was an issue with Firefox that prevented existing and new add-ons from running or being installed. 

See Mozilla's blog for a fix: https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
