### ISSUE TITLE
Hide menu scrollbars when not used

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#149]

**Comment by dhowe** [comment]
![screen shot 2016-05-05 at 8 50 40 pm](https://cloud.githubusercontent.com/assets/737638/15043848/25494922-1303-11e6-8313-bcea0c750622.png)

**Comment by mushon** [comment]
I've never seen these. which browser / OS were they encountered on?

**Comment by CyrusSUEN** [comment]
I'm on OS X 10.11 and Firefox 46.0.1 at us.yahoo.com
![screen shot 2016-05-13 at 4 22 29 pm](https://cloud.githubusercontent.com/assets/2461812/15241943/b7a5ab4e-1925-11e6-9915-18a4326f4693.png)

**Comment by mushon** [comment]
couldn’t build ADN on Firefox 46.0.1

:/

**Comment by CyrusSUEN** [comment]
Set the xpinstall.signatures.required preference to "false" in Firefox
'about:config' page and then $ tools/run-ff.sh

**Comment by mushon** [comment]
Yes, I got some help from @dhowe, but I couldn’t recreate the problem to try solving it.

**Comment by dhowe** [comment]
Simply go to any page with less ads than the height of the menu (for example, nytimes.com):

![screen shot 2016-05-13 at 9 42 33 pm](https://cloud.githubusercontent.com/assets/737638/15249728/b1fa4a78-1953-11e6-80ea-8fc64a72a293.png)

**Comment by dhowe** [comment]
If you see something else, leave a screenshot below...

**Comment by mushon** [comment]
I'm not seeing the scrollbar problem. Here on nytimes.com :

![image](https://cloud.githubusercontent.com/assets/27123/15249850/7581d76a-192a-11e6-8051-9eab78bac764.png)

I will address the other problems separately

**Comment by dhowe** [comment]
Thats interesting. What version of FF? @CyrusSUEN please add your version as well...
I am at 46.0.1

**Comment by CyrusSUEN** [comment]
> What version of FF?

I was on Firefox 46.0.1 on OSX10.11 on us.yahoo.com. And the build should be at fd1586ceb1f9d8ab9fed0a38cf3409fa86628161

**Comment by mushon** [comment]
ADN v2.1.13
FF 46.0.1
OSX 10.10.5
![image](https://cloud.githubusercontent.com/assets/27123/15281582/39700b44-1b45-11e6-9b85-3285a874a7ac.png)

**Comment by dhowe** [comment]
All the same versions for me. Very strange... Anyhow, perhaps you can fix this @CyrusSUEN ?

**Comment by CyrusSUEN** [comment]
> perhaps you can fix this

I think so. I remember we had a similar problem back in ADN1 and I'm looking for the previous fix.

**Comment by CyrusSUEN** [comment]
Fixed: https://github.com/dhowe/AdNauseam2/pull/167
please verify

**Comment by dhowe** [comment]
![screen shot 2016-05-16 at 11 22 00 pm](https://cloud.githubusercontent.com/assets/737638/15294071/51f4b6a6-1bbd-11e6-85f2-173be0bb584f.png)

**Comment by CyrusSUEN** [comment]
We are using the CSS attribute ``overflow-y: auto`` from browsers.
Are there some ways to reproduce the issue?

**Comment by CyrusSUEN** [comment]
> Sometimes ok, sometimes not..

I've found a page with 4 ads and there is no scroll bar
![screen shot 2016-06-12 at 9 40 06 pm](https://cloud.githubusercontent.com/assets/2461812/15991471/6862f9d2-30e6-11e6-9500-805ab2dc0886.png)
