### ISSUE TITLE
Warning messages from opera extension store submission

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1496]
![image](https://user-images.githubusercontent.com/3056154/57882156-0cf95000-77f1-11e9-8a04-dbec1af7b09e.png)

I just double checked that download in opera does work. But maybe we want to change the two permissions fore opera accordingly and considering update jQuery to 3.4.0.

**Comment by dhowe** [comment]
Please do

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/pull/1503/commits/d12cae29065b714f4d2b8f3c76eac48a0b811563
