### ISSUE TITLE
AdNauseam Icon Tooltip says it is (off)

### ISSUE THREAD

**Issue by mva1985** [dhowe/AdNauseam#1499]
The AdNauseam Icon that sits on my browser tool bar says it is off when I hover my mouse over it

The icon is purple which I believe indicates that it is on AND when I go and check the settings under AdNauseam's options it appears to be on as well

I am using the Dissenter Browser on a Windows 7 laptop

Great extension!!  Thanks

**Comment by franc3** [comment]
I am having the same issue, firefox 67, (with disconnect, https everywhere, privacy badger, privacy possum, Don't track me and Decentraleys). Linux, fedora 30

**Comment by cqx931** [comment]
@mva1985 Thank you for the report, this is fixed in https://github.com/dhowe/AdNauseam/commit/45c9a4c52c05c499fc75de2a4aad72fce0541e93 and will be included in the next release.
