### ISSUE TITLE
Check ad-detection

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#15]
- Using a browser without extension, manually identify 10 sites (from the 100 top sites list) with ads that are visible without scrolling
- Then check each with current adn2, and note how many of the total count where found by adn2.

**Comment by CyrusSUEN** [comment]
Not sure if the visible count is a reliable indicator
For example on this URL, I do not see Facebook related ads. But from the menu 1 of 3 is the Facebook ad linking to www.facebook.com.
https://us.yahoo.com/

**Comment by dhowe** [comment]
Yes, don't depend on the badge counter either -- please check for  cases where the badge counter does not equal the # of ads shown in the the menu

**Comment by dhowe** [comment]
And look more closely:

![screen shot 2016-02-23 at 8 09 04 pm](https://cloud.githubusercontent.com/assets/737638/13251152/73f31e18-da69-11e5-888f-f29b7c6b7c3a.png)

**Comment by CyrusSUEN** [comment]
> And look more closely:

Maybe they feed different ads each time.

I will try to look for ads on the whole page. (excluding those with endless scrolling / or dynamic popping ones)

**Comment by dhowe** [comment]
Ok -- the mot useful result is a page for which we detect NONE of the ads...

**Comment by CyrusSUEN** [comment]
Include some from top-15 lists

https://us.yahoo.com/	3/4
http://www.bbc.com/	3/3
http://www.huffingtonpost.com/	2/2
http://www.ew.com/	0/5
http://www.hollywoodreporter.com/	1/8
http://variety.com/	0/5
http://deadline.com/	2/2
http://www.techcrunch.com/	3/7
http://www.yardbarker.com/	0/3
http://www.thepostgame.com/	0/1

**Comment by dhowe** [comment]
nytimes.com is also quite problematic
