### ISSUE TITLE
Purge all caches Isn't working

### ISSUE THREAD

**Issue by metapea** [dhowe/AdNauseam#1501]
### Describe the issue
Unlike in the last version, ''Purge all caches'' is stuck in a gray form and i can't click on it to purge caches.

### Screenshot in which the issue can be seen
https://i.ibb.co/prrQHsZ/Screenshot-35.png

### Steps for anyone to reproduce the issue
This was there since i updated.

### Your settings
- Windows 7
- Iridium (Chromium)
- AdNauseam version: 3.8.101

**Comment by cqx931** [comment]
Thank you for the report! This issue is verified and fixed in the following PR:https://github.com/dhowe/AdNauseam/pull/1503/commits

**Comment by metapea** [comment]
thank you.
