### ISSUE TITLE
*.gamepedia.com is breaking down

### ISSUE THREAD

**Issue by metapea** [dhowe/AdNauseam#1502]
### Describe the issue
When you use adblock on gamepedia.com the site works for a few seconds, then it's breaks into nothing but a white background with text

### Screenshot in which the issue can be seen
First:
https://i.ibb.co/7SDq2pt/Screenshot-37.png

Then:
https://i.ibb.co/231DJPv/Screenshot-36.png

### Steps for anyone to reproduce the issue
By going into then website and waiting for a seconds, then the site will break down 

### Your settings

- OS/version:
- Windows 7
- Iridium (Chromium)
- AdNauseam version: 3.8.101

##### Your filter lists
Default filter lists + spam404

**Comment by cqx931** [comment]
I can't reproduce this with Adnauseam on mac os with chromium/chrome, with span404 filter list added.

**Comment by krystian3w** [comment]
@cqx931 bug in EasyList with `ads.scss`? Now fixed in EasyList and `uBO - unbreak` / `Adguard Base`.

**Comment by metapea** [comment]
Oh sorry i forgot to update this, it was fixed (no clue how) so far at the same time when the ''other'' lists (#1498) was showing up again.
I wanted to keep it for a day or two more, just in case if anyone had to say anything else, then i forgot.
I will reopen this if the issue happens again
