### ISSUE TITLE
Gmail breaks with "uBlock Filters" list enabled

### ISSUE THREAD

**Issue by gordan-bobic** [dhowe/AdNauseam#1505]
### Describe the issue

Not manifesting with uBlock Origin, only with AdNauseam. Originally filed bug there first:
https://github.com/uBlockOrigin/uAssets/issues/5731

### Steps for anyone to reproduce the issue

Enable uBlock Filters list.
Load Gmail.
Try moving an email from inbox into a different folder. It won't do anything.
Disable uBlock Filters list.
Reload Gmail
Try moving an email from inbox into a different folder. It will work.

### Your settings

- OS/version: CentOS 7
- Browser/version: Chrome 74.0.3729.169
- AdNauseam version: Was breaking with 3.7.x from a while back, just updated to latest 3.8.x and the same issue manifests.
- Other extensions you have installed: Ghostery, HTTPS Everywhere

##### Your filter lists
All available except POL language based list (caused a different problem in the past).

### Your location/country
UK

**Comment by cqx931** [comment]
Hi @gordan-bobic , I couldn't reproduce the issue on my computer. I tried moving an email from inbox to 'Trash' or 'Starred' folders and both of them work when I have AdNauseam and uBlock Filter list on. Do you still see this issue after you update the uBlock filters to the latest version?

**Comment by gordan-bobic** [comment]
The problem seems to have disappeared. I re-added the "uBlock filters" from the Essentials group, updated, and the problem no longer manifests. Strange, but I accept it's impossible to fix without being able to reproduce it.
