### ISSUE TITLE
Adnauseam breaks Gmail and Maps functionality

### ISSUE THREAD

**Issue by yankarinRG** [dhowe/AdNauseam#1506]
### Describe the issue

Adnauseam breaks Gmail and Maps functionality. Disabling it will make them work again.

### Steps for anyone to reproduce the issue
1. Go to Google Maps or Gmail website with Adnauseam enabled
2. Click on "send" or (on Maps) right click on a point
3. ...nothing...
4. DisableAdnauseam on these two pages and reload
5. Re-do step 2.
6. ... it will work...

### Your settings

- OS/version: Windows 10 Pro x64 1809
- Browser/version: Google Chrome 74.0.3729.169 x64
- AdNauseam version: v3.8.101
- Other extensions you have installed: N/A

##### Your filter lists
Stock

### Your location/country
Italy

**Comment by dhowe** [comment]
Do you want to report this in ublock Origin issues?

**Comment by yankarinRG** [comment]
It was a typo

**Comment by yankarinRG** [comment]
I updated to v3.8.201 and it seems the problem is't there anymore.
