### ISSUE TITLE
Stays at 0 on all sites

### ISSUE THREAD

**Issue by JonathanMis** [dhowe/AdNauseam#1507]
### Describe the issue

Stays at 0 on all sites

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/15129558/58985386-81655480-87db-11e9-80b2-42e65b2ba76f.png)
![image](https://user-images.githubusercontent.com/15129558/58985414-8e824380-87db-11e9-9c82-260f51fc2752.png)
![image](https://user-images.githubusercontent.com/15129558/58985433-96da7e80-87db-11e9-90b0-59fa4b72bbef.png)
![image](https://user-images.githubusercontent.com/15129558/58985485-b07bc600-87db-11e9-9487-9fb9ad621fd5.png)

### Steps for anyone to reproduce the issue

N/A

### Your settings

- OS/version: Windows 10 1809 (x64 pro)
- Browser/version: Firefox 67.0.1
- AdNauseam version: 3.8.201
- Other extensions you have installed: HTTPS everywhere, Lastpass

##### Your filter lists
"Default filter lists + FRA"

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
France

**Comment by JonathanMis** [comment]
And Firefox new blocking settings are disabled 

![image](https://user-images.githubusercontent.com/15129558/58985544-dacd8380-87db-11e9-9eca-b11e49e61f12.png)

**Comment by dhowe** [comment]
Please try this simple test and take a screenshot... thanks

**Comment by JonathanMis** [comment]
![image](https://user-images.githubusercontent.com/15129558/59097231-4ec37500-891d-11e9-9c0f-8f3d290a9ec0.png)

**Comment by dhowe** [comment]
Interesting. There is definitely something wrong with your configuration (most likely a corrupt Firefox profile). Can you try [creating a fresh profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles), then installing adnauseam there?

**Comment by JonathanMis** [comment]
That was it ! 

Thank you !!
