### ISSUE TITLE
Images blocked on atlanticmonthly

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1510]
https://www.theatlantic.com/photo/2019/06/hong-kong-protesters-return-streets-photos/591841/

They re-appear with adn disabled.

**Comment by cqx931** [comment]
blocked by a blocking rule in adnauseam.txt
```
# theatlantic.com (not sure about this)
||www.theatlantic.com^$important,inline-script
```

**Comment by dhowe** [comment]
not sure why that's there... can u test the site without it?

**Comment by cqx931** [comment]
the images load correctly without this rule and I don't see any ad blocker pop ups after browsing the site for a while.

**Comment by cqx931** [comment]
Anything new with this issue or can this be closed? @dhowe
