### ISSUE TITLE
Vast blankness

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1512]
large blank space on nytimes.com

![image](https://user-images.githubusercontent.com/737638/60600346-f77abe00-9d7d-11e9-83ca-3de17d5af91a.png)

**Comment by cqx931** [comment]
When I test this, I can see the blank space for a few seconds, and it gets hidden by adnauseam

**Comment by dhowe** [comment]
seems ok for me now as well (though not yesterday) - closing for now

**Comment by dhowe** [comment]
I still see this problem in firefox:

![image](https://user-images.githubusercontent.com/737638/61422196-90731280-a902-11e9-954e-312ceb405f56.png)

**Comment by dhowe** [comment]
Still there as of today:

![image](https://user-images.githubusercontent.com/737638/61708184-28fdfe00-ad1a-11e9-9418-724eb89a2522.png)

**Comment by dhowe** [comment]
Also, I see a similar blankness further down the page:

![image](https://user-images.githubusercontent.com/737638/61708415-c0fbe780-ad1a-11e9-980f-4641073aa718.png)

**Comment by cqx931** [comment]
This filter should be able to hide all the blank sections above.  
https://github.com/dhowe/AdNauseam/commit/9524573b8d60d8213a813d810f0dcfe64239472a

**Comment by dhowe** [comment]
The top of the page seems fixed, but I still see other blank horizontal bars after update. Has this been updated in both uAssets AND the new location for adnauseam.txt ?

![image](https://user-images.githubusercontent.com/737638/61729061-72634300-ad44-11e9-9784-033957f08cc2.png)

**Comment by cqx931** [comment]
I only updated the one in adnauseam folder. Just updated the one in uAssets, could you give it another try?

**Comment by cqx931** [comment]
@dhowe

**Comment by dhowe** [comment]
perfect!
