### ISSUE TITLE
Chromium CRX release missing?

### ISSUE THREAD

**Issue by mbirth** [dhowe/AdNauseam#1513]
Previous releases also had a CRX for Chromium-based browsers. Where has that one gone?

(That one's also referenced on https://rednoise.org/adnauseam/updates.xml )

**Comment by dhowe** [comment]
Sure, we can bring that back. Out of curiosity, what browser do you use it for?

**Comment by mbirth** [comment]
That would be awesome. I'm using Vivaldi.

**Comment by dhowe** [comment]
Cool. Can you use addons from the opera store in Vivaldi?

Anyhow, just re-added the .crx to the build scripts in the new-assets branch (which will be used for  subsequent builds)

**Comment by mbirth** [comment]
Thanks a lot!

The Opera store doesn't detect Vivaldi as a valid browser and insists on downloading the "real" Opera instead. (IIRC, Vivaldi was made by former Opera employees because they didn't like where the original Opera was headed.) But you can use the Chrome Web Store with Vivaldi.

**Comment by cqx931** [comment]
@dhowe Another reason why we need to keep uploading .crx file is that the chrome update needs the file to work. See [updates.xml](http://rednoise.org/adnauseam/updates.xml)
