### ISSUE TITLE
[v3.8.301]EFF whitelist, tick is off position

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1515]
![image](https://user-images.githubusercontent.com/3056154/60837342-f38fd700-a195-11e9-8bb0-74758089fff6.png)

**Comment by Wolfsbane** [comment]
I'm not sure if it fixes, that is could use a filter list in the whitelist, however I added it their whitelist:
https://www.eff.org/files/effdntlist.txt .
