### ISSUE TITLE
Text-ad parsing not working in Bing/Google/Ask

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1519]
Google:
Hidden but not collected in Firefox; Not hidden and not collected in Chrome
Bing:
Not hidden & not collected
Ask:
Not hidden & not collected -> Historical issue

**Comment by cqx931** [comment]
text ads now are hidden in Firefox, still can't get them collected though.

**Comment by dhowe** [comment]
this is strange -- is this just a case of DOM structure/naming changing?

**Comment by cqx931** [comment]
Some part of it, yes...and that's easy fix for Bing. But when it comes to cases when the same filter works for Firefox but not for Chrome, that's pretty strange.

**Comment by dhowe** [comment]
indeed -- is it possible that [mozilla css](https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_Extensions) extensions are being used?

**Comment by cqx931** [comment]
okay... No I think it's not related to mozilla css. So with Bing I just double checked that it's not related to FIrefox/Chrome, instead it's related to a rule I just added to hide visible ads in Bing.

If you use 3.8.201 to test this (not updated to the latest adnauseam.txt) in chrome

- Default: ads are collected, but they are also visible 
- Add `##.adbDef` to My Filters:  Ads are hidden and collect
- Change the rule to  `bing.com##.adbDef`: Ads are hidden but no-longer collected

I think it should be related to the generic hidden filters...but not sure how exactly it works here.

**Comment by cqx931** [comment]
Update: google text ads can be hidden collected now both in chrome and firefox

**Comment by cqx931** [comment]
After fixing the logger, the issue seems more clear with Bing. In firefox, generichide is parsed correctly, whereas in chrome, it is saying that no cosmetic filtering for bing.
Chrome:
![Screen Shot 2019-07-17 at 1 10 01 PM](https://user-images.githubusercontent.com/3056154/61395778-418e9400-a894-11e9-9f77-c49ee148301e.png)
Firefox
<img width="1270" alt="Screen Shot 2019-07-17 at 1 10 08 PM" src="https://user-images.githubusercontent.com/3056154/61395909-861a2f80-a894-11e9-81c2-5f4026a12772.png">

**Comment by cqx931** [comment]
Update: both bing and ask text-ads are at least hidden at this point. 

Ask text-ads are not hidden by uBlock origin at this point. They are injected iframes from google, so text ads parsing are more trickier there. This should be related to how good adnauseam works for injected iframes.

Both ads collection issues seem to be related to non-triggered adCheck from adnauseam. Now cosmetic filters are being hidden by CSS(see contentscript.js), it seems to me that there are still some cases when an ad  is hidden but can't trigger Adnauseam parser to work.

I will revisit this issue post-new release.

**Comment by cqx931** [comment]
google and bing text ad collection are fixed by https://github.com/dhowe/AdNauseam/pull/1535

**Comment by cqx931** [comment]
both google and bing text ads can be parsed in latest master branch
