### ISSUE TITLE
Better update mechanism for EFF list

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1529]
- [x] Update [eff list in github](https://github.com/dhowe/AdNauseam/blob/master/thirdparties/www.eff.org/files/effdntlist.txt)

- [x] Create an update button for eff filter

**Comment by dhowe** [comment]
post-recommended ext deadline

**Comment by cqx931** [comment]
Eff update button added here: https://github.com/dhowe/AdNauseam/commit/95899aa33b48a1a9c8940f09bdc7adb0c628d005

Updated release testing
