### ISSUE TITLE
Delayed Firefox Release?

### ISSUE THREAD

**Issue by joshsleeper** [dhowe/AdNauseam#1530]
### Describe the issue

Unsure if it's an "issue" per se, or just a manual process that hasn't been done behind the scenes, but the latest AdNauseam release (https://github.com/dhowe/AdNauseam/releases/tag/v3.8.302) still isn't available for Firefox as far as I can tell.

https://addons.mozilla.org/en-US/firefox/addon/adnauseam/

#### Screenshot from AdNauseam page on addons.mozilla.org

![image](https://user-images.githubusercontent.com/849941/61649307-3ca85680-ac7f-11e9-9e3f-9bfb3cf20f03.png)

#### Screenshot of AdNauseam addon installed in latest Firefox

![image](https://user-images.githubusercontent.com/849941/61649379-5c3f7f00-ac7f-11e9-9968-f6880a5458fd.png)

### Steps for anyone to reproduce the issue
Install the addon for Firefox from, see that it's still version `3.8.201`

### Your settings

- OS/version: `Windows 10 Pro 1903 (64-bit)`
- Browser/version: Firefox `68.0.1 (64-bit)`
- AdNauseam version: `3.8.201`
- Other extensions you have installed: N/A for this issue

##### Your filter lists
N/A for this issue

### Your location/country
USA

**Comment by dhowe** [comment]
@joshsleeper thanks for the note, you are correct. The review queue at Firefox has been a bit backed up recently, but we are hoping to see the the release go live in the next 2-3 days. Apologies for the delay... I will update this ticket if/when we have further news

**Comment by joshsleeper** [comment]
No worries at all, just wanted to make sure FF users weren't accidentally missing out on releases!
Thanks so much for the info (and the wonderful extension, of course!).
I'll keep on twiddling my thumbs until it makes it's way through the queue then haha.

**Comment by cqx931** [comment]
The new release is live in Firefox now!

**Comment by mbirth** [comment]
Is this still the case with the current updates? v3.9.106 was released almost 2 weeks ago and the Mozilla Addons page still shows 3.9.104 from 5 months ago as the latest version.

**Comment by cqx931** [comment]
HI @mbirth , you are right, we have already uploaded the latest version to the store but we had some issues with the review process. Sorry about the delay, but we are  trying our best to get it released soon!
