### ISSUE TITLE
Text ads visible on samstroy.com

### ISSUE THREAD

**Issue by Ledarium** [dhowe/AdNauseam#1534]
### Describe the issue

Example page: https://samstroy.com/%D0%BA%D0%BE%D0%BD%D1%86%D0%B5%D0%BF%D1%86%D0%B8%D1%8F-%D1%83%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B4%D0%BE%D0%BC%D0%B0/
Ads are blocked fine with uBO

### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/10389237/62473008-94c77880-b7a8-11e9-89ac-5255623d4885.png)

### Your settings

- OS/version: Windows 10 
- Browser/version: Firefox Quantum 68.0.1
- AdNauseam version: 3.8.302
- Other extensions you have installed: None

##### Your filter lists

Default filter lists + RUS: AdGuard Russian + RUS: RU AdList

### Your location/country
Russia

**Comment by cqx931** [comment]
I can't reproduce this issue on my computer.  @dhowe Can you reproduce it?

**Comment by Ledarium** [comment]
Hmmm, I can not reproduce it now too
