### ISSUE TITLE
Opera setting: allow access to search page results

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1537]
The default for this setting is false. We need to turn this setting on in order to hide and parse text ads from search engines.
![image](https://user-images.githubusercontent.com/3056154/62581100-251fbf00-b876-11e9-852f-e4cc17bc3952.png)

**Comment by cqx931** [comment]
It doesn't seem like a feature that we could influence, same for uBlock origin. 
https://www.reddit.com/r/uBlockOrigin/comments/a147uc/psa_if_youre_using_opera_and_wondering_why_the/

**Comment by krystian3w** [comment]
IMO: Only possible add instructions on Opera Store in `description` and maybe hardcode in addon on about page?

**Comment by cqx931** [comment]
I agree with what @krystian3w suggests and on top of that, one more thing we might add is to add a menu notification if a user is on opera and the current page is a search result page. However, there is no existing API to know whether the user has turned on this setting or not, but we should be able to know this with some walk arounds...

**Comment by dhowe** [comment]
Two options, both assuming that we can determine if we are on Opera AND that setting is enabled...

1.  If we are on Opera AND that setting is enabled AND the current page is a search page, then show a notification (via our notification mechanism)  

2.  If we are on Opera AND that setting is enabled, show a warning on the install screen only

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/AdNauseam/pull/1590

I did the workaround by checking the pageStore and see if adnauseam has any pageStore record at all for search engine pages, if not, a notification will show up in the menu.

![image](https://user-images.githubusercontent.com/3056154/70183819-80db4700-16b4-11ea-8dec-5436f4aa220d.png)

Once the setting is changed, the page needs to be refreshed first to get rid of the notification.

I also added a new FAQ entry [here](https://github.com/dhowe/AdNauseam/wiki/FAQ#why-adnauseam-does-not-work-on-search-engines-in-opera).
