### ISSUE TITLE
ExtensionInstallWhitelist for Linux / OSX

### ISSUE THREAD

**Issue by allo-** [dhowe/AdNauseam#1538]
You note at https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission a workaround for the developer extension popup on Windows and write that you do not know a way to do the same on other OS.

Have a look at this documentation page of the Chromium project:
https://www.chromium.org/administrators/policy-list-3#ExtensionInstallWhitelist

There are the settings and their format documented. I just do not see directly what's the config file where you need to add the settings.

**Comment by dhowe** [comment]
This appears to be (at least on my OSX version): /Applications/Google\ Chrome.app/Contents/Resources/com.google.Chrome.manifest/Contents/Resources/com.google.Chrome.manifest

Can someone test this?

**Comment by cqx931** [comment]
I have tried to modified the manifest file and none of these really worked for me.

Combining what is discussed in https://github.com/dhowe/AdNauseam/issues/1539 I doubt whether adding adnauseam to ExtensionInstallWhitelist makes any difference at all.

According to the [documentation](https://www.chromium.org/administrators/policy-list-3#ExtensionInstallWhitelist), whitelist is designed to allow specific extensions when all extensions are blacklisted(*). The whole system is designed for another context (for example, in institutions or workplace), which is an extra layer someone may want to add on top the basic mechanism(whether an extension is in chrome web store or not).

**Comment by dhowe** [comment]
I'm happy to post this workaround if someone can actually make it work... but otherwise closing for now.
