### ISSUE TITLE
How to enable Ad-Nauseum in private browsing?

### ISSUE THREAD

**Issue by rdcr0** [dhowe/AdNauseam#1541]
How would I let ad-nauseam collect ads and click on them in private browsing mode? I use Firefox with private browsing so it won't remember history, but I can't use ad-nauseam. How can I enable it? Can you add this? It would be disappointing to not be able to use this great extension.

**Comment by dhowe** [comment]
@cqx931 does this not have the expected behavior ?

**Comment by dhowe** [comment]
See also  #1542
