### ISSUE TITLE
Does not work in private windows

### ISSUE THREAD

**Issue by WhoAmI1000** [dhowe/AdNauseam#1542]
Ad-Nauseam will not work in private windows. The ad counter is stuck at 0, even when I have no other ad-blockers.

**Comment by dhowe** [comment]
If all browser support a toggle for addon activation in private mode, then AdNauseam should be allowed to run as usual (though it will not be truly private). Can you check this for Chrome and Opera, @cqx931 

See also #1541

**Comment by cqx931** [comment]
In current versions of Chrome and Opera, the support for private mode/incognito is implemented in similar ways. Users always need to manually enable the extension to be able to use it in private mode. Although the amount of info displayed next to the allow buttons is not the same. See:
Chrome
<img width="691" alt="Screen Shot 2019-09-03 at 6 11 45 PM" src="https://user-images.githubusercontent.com/3056154/64212153-6657be80-ce76-11e9-9e24-e423d97d62e5.png">
Opera
<img width="687" alt="Screen Shot 2019-09-03 at 6 22 00 PM" src="https://user-images.githubusercontent.com/3056154/64212572-c307a900-ce77-11e9-8361-56a8bb13ca44.png">
Firefox
<img width="666" alt="Screen Shot 2019-09-03 at 6 21 21 PM" src="https://user-images.githubusercontent.com/3056154/64212543-a9666180-ce77-11e9-80f8-adbf41244aff.png">

By allowing a certain extension to work in private window, it is already assuming that the browsing is no longer truly private. The least confusing way, in my opinion, is letting adnauseam working as usual if allowed in private mode. However, if we do want to keep offering a true private browsing, another option would be to introduce a setting that disables ad clicking in private mode? By default this setting is off, but whenever the user check adnauseam in private mode, we can show a notification, reminding the user of this option.

**Comment by cqx931** [comment]
this is addressed in https://github.com/dhowe/AdNauseam/commit/80b72e4a9e6303c48e6136afccf4561601f23b4b.
