### ISSUE TITLE
Video ads on DailyMotion

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1543]
![Screen Shot 2019-08-30 at 1 30 10 PM](https://user-images.githubusercontent.com/737638/63995250-78f68e80-cb2a-11e9-92c3-b898da4efc58.png)
https://www.dailymotion.com/video/x5n7b76

**Comment by cqx931** [comment]
```
||dmxleo.dailymotion.com/cdn/manifest/video/
```
Blocking the pattern above fixes the issue for me. Please verify on your side.
