### ISSUE TITLE
'Disable on this page' broken

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1548]
I disable adnauseam on a page and it says it is disabled. Then I refresh the page and it is still enabled.

After disabling:
![image](https://user-images.githubusercontent.com/737638/64472373-e1c7b180-d18f-11e9-8a74-373c29c14878.png)

After refresh:
![image](https://user-images.githubusercontent.com/737638/64472368-cceb1e00-d18f-11e9-9277-4e61d1463cc8.png)

**Comment by dhowe** [comment]
Note: this may have been caused by corrupt FF/AdNauseam profile. Se errors below:

![image](https://user-images.githubusercontent.com/737638/64472441-0bcda380-d191-11e9-82cc-989462760055.png)

**Comment by cqx931** [comment]
It works fine with me after refresh. Which page were you trying to work on?
![image](https://user-images.githubusercontent.com/3056154/64633106-86343880-d3c8-11e9-8c1b-625ccf677789.png)

**Comment by dhowe** [comment]
lets assume it was due to the problems above
