### ISSUE TITLE
Installed/working but no icon on toolbar

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1549]
Firefox 69.0 (64-bit) / OS X 10.13.6 

![image](https://user-images.githubusercontent.com/737638/64472495-f147fa00-d191-11e9-93ae-82f3deb995a8.png)

**Comment by cqx931** [comment]
Can't reproduce it on my computer, did it happen after a standard install from Mozilla store?

<img width="751" alt="Screen Shot 2019-09-10 at 12 38 22 PM" src="https://user-images.githubusercontent.com/3056154/64632842-ec6c8b80-d3c7-11e9-9a23-d73995a1c081.png">

**Comment by dhowe** [comment]
Yes, but may have been a corrupt profile
