### ISSUE TITLE
Independent.co.uk ads visible in Firefox 

### ISSUE THREAD

**Issue by oscaryfish** [dhowe/AdNauseam#1550]
Independent.co.uk showing ads in Firefox quantum 68.0.2, but not Opera 62.0.3331.119

https://www.independent.co.uk/news/science/children-happiness-study-parents-stress-money-christoph-becker-at-heidelberg-university-a9068926.html

![Screen Shot 2019-09-07 at 6 30 08 PM](https://user-images.githubusercontent.com/20669777/64473771-94524100-d19d-11e9-96f5-ca017a670ecf.png)

### Your settings

- OS/version: Sierra 10.12.6
- Browser/version: Firefox quantum 68.0.2
- AdNauseam version: v3.8.302 
- Other extensions you have installed: Dark Mode 0.3.4

### Your location/country
HK

**Comment by dhowe** [comment]
I can't verify this now. Can you check @cqx931 ?

**Comment by cqx931** [comment]
Tested on Firefox 69.0 on Sierra 10.12.6, with Dark Mode installed, no visible ads.
The screenshot looks like a background ad plus video, whereas I see usual iframe google ads.

**Comment by cqx931** [comment]
closed for now
