### ISSUE TITLE
Text ads on https://hongkong.asiaxpat.com/

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1552]
![image](https://user-images.githubusercontent.com/737638/64696485-1c538600-d4d1-11e9-8974-095762334862.png)

**Comment by dhowe** [comment]
Doesn't need collection, just hiding

**Comment by cqx931** [comment]
fixed here: https://github.com/dhowe/AdNauseam/commit/cb6fa0488cb4d0e1cb920b217b1614b023cfe1ab. Please check.
