### ISSUE TITLE
Menu gets cut off

### ISSUE THREAD

**Issue by howdoidoaprogramming** [dhowe/AdNauseam#1554]
### Describe the issue
The extension dropdown menu is cut off.
### Screenshot in which the issue can be seen
https://imgur.com/a/NhuQSLd

### Steps for anyone to reproduce the issue
1. Click on the extension icon. 

### Your settings
Prevent WebRTC leaks, Click Ads always except non-tracking ads, block malware, disable hyperlink auditing, hide ads except for non-tracking ads, disable prefetching, activate debugging mode, display number of ads on icon, make use of context menu.

Also thought my resolution would be relevant:  1366x768
- OS/version:
Debian GNU/Linux bullseye/sid x86_64 
- Browser/version:
Mozilla Firefox Snap for Ubuntu 
69.0 (64-bit)
- AdNauseam version:
AdNauseam v3.8.302
- Other extensions you have installed:
UBO Scope
Multi-Account Containers
Cookie AutoDelete 3.0.2
Decentralytes
TOR Snowflake
HTTPS Everywhere
Wayback Machine
User-Agent Switcher
GNOME Shell Extensions
Certainly Something Certificate Viewer

##### Your filter lists
All included filters -languages

### Your location/country
USA

**Comment by swordfishtr** [comment]
Same here, the menu gets cut off.
https://i.postimg.cc/GtVdRVZb/Screenshot-2019-09-13-18-56-55.png

Using Firefox 69.0 (64 bit) on Manjaro Linux. Resolution is 1366x768

Temporary workaround: I found out that a CSS file in the XPInstall module is for some reason read incorrectly. In firefoxprofile/extensions/adnauseam@rednoise.org.xpi/css/menu.css
`...
html {
  height: 500px;
  width: 400px;
}

body {
  line-height: 1;
  height: 500px;
  width: 400px;
...`
Both widths are read incorrectly as a number less than 400. Editing them to something else, such as 401, seems to mostly solve the issue for me, but it sometimes gets cut off still.

**Comment by howdoidoaprogramming** [comment]
Magically got fixed for me. I changed nothing though.

**Comment by dhowe** [comment]
@howdoidoaprogramming why did you close this?
