### ISSUE TITLE
Ad Collection Dynamic Google Ad

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1556]
Test Cases: 
http://rednoise.org/adntest/googleAdSenseCases.html

Text Only
http://rednoise.org/adntest/textAds.html

**Comment by cqx931** [comment]
@dhowe  updated the test cases. These are 'preserved' dom structures of different kinds of ads that I noticed. Can be used for further ad collections for different kinds

**Comment by dhowe** [comment]
This is what I see with Firefox and v3.8.401 -- is this expected behavior?

![image](https://user-images.githubusercontent.com/737638/65369168-a2fc2600-dc7c-11e9-90f6-3fc41872228a.png)

**Comment by cqx931** [comment]
yes, if you unhide the ad or disable ad hiding, you should be seeing those ads. Only the image ad can be collected at this moment.

**Comment by dhowe** [comment]
but this is the test page... so we should see the problem under normal settings, no?

**Comment by cqx931** [comment]
The problematic rule '.adsbygoogle' only stops us from collecting google ads, as in most of the cases an ad won't be rendered at all if this rule is fired.

So these test cases are mainly setup for ad collection. And since rednoise.org is on EFF list for DNT, the setting should be modified to test hiding functions for DNT sites, instead of a default setting.

**Comment by dhowe** [comment]
Right, so whats the easiest way to disable this '.adsbygoogle' so that we can try new solutions?

**Comment by cqx931** [comment]
Image + Text Scenario.
The Image in this Scenario is actually a background image of a canvas element.
I can write a special case within the parser for the default case to check first for this particular type of ad structure.

**Comment by dhowe** [comment]
indeed we want to make sure that we are handling ALL the 'special' cases for Google as they are by far the biggest ad provider

**Comment by cqx931** [comment]
Please check https://github.com/dhowe/AdNauseam/pull/1564
So far I was able to pick up this particular case on my test page:
http://rednoise.org/adntest/googleAdSenseCases.html

If you visit the page after a build from the latest PR, adnauseam should be able to pick up two ads. However, when I test it on filbert, what I was having issues with is the cross-domain iframes.

Instead of going into the iframes, 
![image](https://user-images.githubusercontent.com/3056154/66080313-d91a8f00-e533-11e9-91da-974ba26d551b.png)

The parser stops because it can't load the content inside that iframe, which is the second layer iframe for this particular case. I searched about this in our past issues and I found you created this ticket long time ago about nested cross-domain iframes https://github.com/dhowe/AdNauseam/issues/158 

Any ideas or insight on this? @dhowe

**Comment by cqx931** [comment]
http://rednoise.org/adntest/crossDomainGoogleCase.html
I created a simlple cross domain google image + text ad case here and adnauseam works on an iframe hosted on my own server.

**Comment by cqx931** [comment]
However, what interesting is that even adnauseam is able collect the ad in the simple test case above, the cross-domain iframe was still ignored in this case, while the image is parsed before that. It seems like what is happening in the content script is actually helping the parser to access to the dom structure inside the iframe here although I'm not very sure what it is doing here.
https://github.com/dhowe/AdNauseam/blob/master/src/js/contentscript.js#L836

Another difference between my test case and the real ad is that the outer iframe is actually dynamically generated, while in my case it is a saved static version. (I'm serving an ad sample from my server in the second iframe)
![image](https://user-images.githubusercontent.com/3056154/66182746-4fa6b200-e644-11e9-9b73-4a2ca4776d02.png)

**Comment by dhowe** [comment]
1. images may be handled differently as the cross-origin may not apply (these are often served from 3rd parties)
2. we need to make the test match the google case as closely as possibly (without touching their servers) -- if they do it dynamically, the test should as well

**Comment by cqx931** [comment]
> are we collecting the text in the test above?

@dhowe at this moment, no, I'm treating them as an image ad for now

**Comment by dhowe** [comment]
I'm not sure I understand -- you are just trying to collect the image, but not the text ?

**Comment by cqx931** [comment]
Yes, at the moment the text is retrieved through ad visiting instead of parsing.

**Comment by cqx931** [comment]
Okay...I got it wrong before. The issue doesn't really lies in iframe, however, it's dynamically generated href links.

**Why simple image ads works?**
Because those links  are not dynamically generated, or at least using a different mechanism. When the outer iframe is hidden, it doesn't interfere the href attribute of the ad <a> tag.

**Why this particular dynamic ad doesn't work?**
The targetURL is generated. And from what I tested, whenever the outer iframe is hidden, the href is not generated at all. The source of the valid link is not that obvious as what we dealt with before.

The script that is doing this is here:
If you block them and visit our test site without ad blocker. If the ad happens to be a dynamic one(with both image and text), you can notice that the ad is not clickable. The mouse will change when I hover the ad, but the whole ad is no longer clickable.
![image](https://user-images.githubusercontent.com/3056154/66519583-9289df00-eab5-11e9-9814-eb73f4f1acd4.png)

When the outer iframe is hidden,  there is no href or any related links in the <a> tag:
`<a id="mys-content" style="width:352px;height:280px;">`

Only when the outer iframe is visible, the href will be rendered:
```
<a id="mys-content" style="width:352px;height:280px;"
data-on-ready-ts="1570652827826"
href="https://adclick.g.doubleclick.net/aclk?sa=L&amp;ai=CU7nGm0KeXb-vCsHAkwPomJy4D7v7p89YsZCJurAJ3sTWsdQXEAEgxa_4dmDJ3oqLwKTYD8gBCagDAcgDwwSqBJ8BT9DMS4XoqudLPTsWCCQ2BJaJzG7tLoA6_SCiT0wE340GpkjAyUixzD2lTW7NI477zCOv77InvEasd0EeQ3jTxGGpUwms9rKOylCYco4TwDDK2kQ2eZL5AYMefGp_GYcpk-CF3HuJrd6mt6bJvu_jFABOSGbjFbPBTxEQNicLwf-LgpsQr6LLngWZVlwJqGDNFCSO4wEo6V1wpyKe4SR9oAYugAfcu_yAAagHjs4bqAfVyRuoB8HTG6gHhdQbqAeB1BuoB4LUG6gHhtQbqAeE1BuoB5PYG6gH4NMbqAe6BqgH2csbqAfPzBuoB6a-G6gH89EbqAfs1RvYBwDSCAcIgGEQARgesQmtOrOkORqayIAKAdgTAg&amp;ae=1&amp;num=1&amp;sig=AOD64_21Z9DCW-IgeJz0a_2alfks3v6t1g&amp;client=ca-pub-4953354000641335&amp;adurl=http://mainackmondal.com%3Ftarget%3D32823846528&amp;mb=33&amp;bg=!hYalhp5YYfWNIawZW-kCAAAAcVIAAAAYmQF08L9LQxE2MBaAlxXDGckPSTj3lLwe94vlIRoVm3COw8XU-m_urdTCoNVdsav_yQTCl2jfuWQ6zzPzaJ1F4IfTG72Y4psRYAKBj9a-lpflc-QweN0Gkbs9f-g7oG1HXb-1f4pP19m35wQxXiU7aNPIomeu_wuMHNsqUuGuEgnV-0hmMy46rJmfN-7YXaAvtXM53EkgQt6cosXobICkBnqrnZAcipCSp6tRjkZ3-dX8cByekl9Aco8E_8D_LKhyIfENFADVmko1IMfcchWR3FLS9FydMNrYkulcGSotgP5P7v2klrIs_zaNZo1psfbGLt7sX6hMfHLhKOjymlEDXjl4WrOMzEBqrEJxbGDko0fk7c_aDVOOQrWdYfjrI3VjZA3zZo301QvWnr-2YVRgKqF71OuVSIfllw6bhWy3Dr5x-g8q8KbNfkrrpP0H8RokSjiWWxnO5qJcLoKc9rDVQoFY6VQzG65P4IuHNAoS8Zvdpmt93A-d"
target="_top"
data-u2-final-url="http://mainackmondal.com?target=32823846528"
data-u2-tracking-url="http://mainackmondal.com?target=32823846528"
data-app-click-info="[&quot;http://mainackmondal.com?target=32823846528&quot;,&quot;https://adclick.g.doubleclick.net/aclk?sa=L&amp;ai=CU7nGm0KeXb-vCsHAkwPomJy4D7v7p89YsZCJurAJ3sTWsdQXEAEgxa_4dmDJ3oqLwKTYD8gBCagDAcgDwwSqBJ8BT9DMS4XoqudLPTsWCCQ2BJaJzG7tLoA6_SCiT0wE340GpkjAyUixzD2lTW7NI477zCOv77InvEasd0EeQ3jTxGGpUwms9rKOylCYco4TwDDK2kQ2eZL5AYMefGp_GYcpk-CF3HuJrd6mt6bJvu_jFABOSGbjFbPBTxEQNicLwf-LgpsQr6LLngWZVlwJqGDNFCSO4wEo6V1wpyKe4SR9oAYugAfcu_yAAagHjs4bqAfVyRuoB8HTG6gHhdQbqAeB1BuoB4LUG6gHhtQbqAeE1BuoB5PYG6gH4NMbqAe6BqgH2csbqAfPzBuoB6a-G6gH89EbqAfs1RvYBwDSCAcIgGEQARgesQmtOrOkORqayIAKAdgTAg&amp;ae=1&amp;num=1&amp;sig=AOD64_21Z9DCW-IgeJz0a_2alfks3v6t1g&amp;client=ca-pub-4953354000641335&amp;adurl=http://mainackmondal.com%3Ftarget%3D32823846528&quot;,&quot;http://mainackmondal.com?target=32823846528&quot;,&quot;http://mainackmondal.com?target=32823846528&quot;,&quot;&quot;,&quot;&quot;]">
</a>
```

**Comment by cqx931** [comment]
At this point, I think we have two options:
(1) Trying to figure out how the url is composed and see whether we can retrieve that without displaying the iframe. 
This would be a temporary solution, if google changes the code, the solution is broken again.
(2)Modifying the current cosmetic rule mechanism. 
This is related to what we were thinking about for the grey rectangular issue. After adopting the css method to hide elements, cosmetic hiding rules are added before elements are rendered. The better solution here would be first allow these elements, and hide them after they are fully rendered.

**Comment by dhowe** [comment]
>     1. Trying to figure out how the url is composed and see whether we can retrieve that without displaying the iframe.  This would be a temporary solution, if google changes the code, the solution is broken again.

Indeed, not ideal, but similar to how we currently handle text-ads

>     2. Modifying the current cosmetic rule mechanism.
>        This is related to what we were thinking about for the grey rectangular issue. After adopting the css method to hide elements, cosmetic hiding rules are added before elements are rendered. The better solution here would be first allow these elements, and hide them after they are fully rendered.

Yes, better solution, but not sure how this would look exactly. I think there is an argument to be made that AdNauseam should ALWAYS work like this. But there may may be a performance hit. Can we simply specify a later time for the content-scripts to run via the manifest, via something other than  "run_at": "document_start" ?

**Comment by cqx931** [comment]
>  Can we simply specify a later time for the content-scripts to run in the manifest, via something other than "run_at": "document_start" ?

This is going to work for this particular case. We could, let's say, modify the "run_at" to "document_end". But even when the document is ready, it only means that the outer iframe is ready, whereas the inner iframe is still not populated. So if adnauseam hides the outer iframe at this point, when the link is generated in the inner iframe, the outer iframe is still already hidden.

**Comment by dhowe** [comment]
> This is going to work for this particular case. 

do you mean this is NOT going to work?

**Comment by cqx931** [comment]
It might be helpful for other dynamic cases, but not really for  layered iframes with inside content generated with certain delay.

**Comment by cqx931** [comment]
Even if it's possible I still don't think this is going to help for this scenario.

Let's say our content-script can be forced to run again inside the iframe when it is finished loading(plus there is also another iframe inside it), the outer iframe has still already been hidden and running the content-script again inside it won't really help...

**Comment by dhowe** [comment]
Hidden or not hidden doesn't really matter as long as all the elements are created and sized and the links generated. The problem is (I think) that once the outer frame is hidden all processing of the inner frame stops... So it would seem that 'run-at: document_idle should work (though this will cause other problems), yes?


  

>   "document_start": corresponds to loading. The DOM is still loading.
>     "document_end": corresponds to interactive. The DOM has finished loading, but resources such as scripts and images may still be loading.
>     "document_idle": corresponds to complete. The document and all its resources have finished loading.

**Comment by cqx931** [comment]
> once the outer frame is hidden all processing of the inner frame stops...

The old cosmetic filter in easylist that hide another element was used to be like that, but this doesn't apply to the current case.

For now, when the outer iframe is hidden, it only influences the generation of targetURL for responsive display ad, not even for image ad. Not sure why it's different per case but the trend would be to apply the same method to all ads.

Hmm, I haven't thought about document_idle yet. Not sure whether "all its resources" include iframes as well, but I can definitely give it a try.

**Comment by dhowe** [comment]
> Hmm, I haven't thought about document_idle yet. Not sure whether "all its resources" include iframes as well, but I can definitely give it a try.
Perhaps it is possible to stopped hiding such frames in our normal ('document_start') content-scripts, but instead use an additional 'document_idle' script that hides them after they have finished loading?

**Comment by dhowe** [comment]
ps. can you include the 'obfuscated' code above as text?

**Comment by cqx931** [comment]
> ps. can you include the 'obfuscated' code above as text?

http://rednoise.org/adntest/gstaticScript.js

**Comment by cqx931** [comment]
I just fixed what I mentioned here https://github.com/dhowe/AdNauseam/issues/1567, trying to at least collect the ad while displaying it.
Then I found that, the targetURL actually only generated when there is a click event(see line 686 in the script).
The process goes like this in the code:
```clickEvent -> Fa() -> L() -> a.href = ....```

**Comment by cqx931** [comment]
Please check:
https://github.com/dhowe/AdNauseam/commit/548da7c6119bd2b374c64aff519633dd680e8262

For this attempt, I was able to collect the ad without hiding it.
I'm firing a mouseDown event in the parser right now if it is a google responsive display ad, and there is no href for the a tag.
However, the mousedown event would only trigger the generative code when the ad is not hidden. 

I can dig more into the code to see what exactly it is checking for the visibility part, but for now, at least we are ready for the clicking experiment.

**Comment by dhowe** [comment]
Also, this huge difference between a responsive display ad and an image ad makes me think it is necessary that we make use of this chance to test through different kinds of ad format, both for ad collection and the clicking experiment.

**Comment by dhowe** [comment]
> Also, this huge difference between a responsive display ad and an image ad makes me think it is necessary that we make use of this chance to test through different kinds of ad format, both for ad collection and the clicking experiment.

Strange, I didn't write that.

**Comment by cqx931** [comment]
> Perhaps it is possible to stopped hiding such frames in our normal ('document_start') content-scripts, but instead use an additional 'document_idle' script that hides them after they have finished loading?

If we implement it in this way, won't the ad be visible for a second then hidden by adnauseam?

**Comment by cqx931** [comment]
http://rednoise.org/adntest/activeViewScript.js
Attaching here another script from gstatic that is related to this issue

**Comment by cqx931** [comment]
@dhowe Please check:  https://github.com/dhowe/AdNauseam/tree/fakehide
I did a temporary attempt of implementing the 0 height method of what I proposed in https://github.com/dhowe/AdNauseam/issues/1555

I tried to unhide the iframe and add a fake css hiding rule to it by changing the height to 0, which turns out to be able to pass google's active view check and successfully collected the ad.

In this commit I also hide the outer ins tag with the same method to hide the grey rectangle.

If there is no further concern with this method we can add another type of cosmetic filter to ublock's current cosmetic filter system. So that we can define these special cases in adnauseam.txt filter with a customized syntax and update the selectors when necessary.
https://github.com/dhowe/AdNauseam/commit/07ecb7c0aeeef4f17abdf97eeb992394ad0a7225

**Comment by dhowe** [comment]
which is the proper test page for this..  is it http://rednoise.org/adntest/crossDomainGoogleCase.html ?

**Comment by cqx931** [comment]
@dhowe yes, I modified the test case, there won't be any href attribute for the a tag at the beginning.

I just pushed another fix to the fakehide branch, you should be able to collect the ad from the above testcase with hiding enabled.

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/AdNauseam/pull/1568
Added a text ad parser for text ads in google adsense

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/blob/master/src/js/static-ext-filtering.js#L664
This is where current cosmetic filters are compiled.

**Comment by dhowe** [comment]
Looks pretty straight-forward if we follow the existing cases as a template

**Comment by cqx931** [comment]
Dynamic Google Ad can be collected and clicked in the latest release, close now

**Comment by cqx931** [comment]
Text ads still can't be collected in the latest release, I opened a new ticket for it.https://github.com/dhowe/AdNauseam/issues/new
