### ISSUE TITLE
Two additions to website

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1557]
- [x] 'Banned by Google, Recommended by Firefox' icon for adnauseam.io 

- [x] 'Help Support AdNauseam' button via open-collective (can be copied from bottom of github page). Should also add FAQ entry about this

**Comment by dhowe** [comment]
@mushon feel free to weigh in if you find a moment, but otherwise @cqx931 will handle this

**Comment by cqx931** [comment]
Shall we also change this section of the website?
![image](https://user-images.githubusercontent.com/3056154/65545811-24092680-dee4-11e9-9d75-14898781467e.png)

Put Firefox as the main icon, with chrome and opera in 'see also' section?

**Comment by dhowe** [comment]
No. That should change based on which browser you are using...

![image](https://user-images.githubusercontent.com/737638/65546657-86950d80-df4a-11e9-911c-e8ba3615d78a.png)

**Comment by cqx931** [comment]
How about this:
![Artboard](https://user-images.githubusercontent.com/3056154/65551654-5e78c080-def0-11e9-9f6d-f3b26ca64d57.png)

**Comment by dhowe** [comment]
Its good, but could perhaps be more clear or 'punchy' 
It reads to me here more like a simple difference of opinion, with equal weights to both sides.

Google needs to look evil in this scenario, banning what is otherwise high-quality, useful software because of its crooked business model

@mushon any quick thoughts?

Also, it should have a 'read more' link somewhere so that people can learn about the two cases

**Comment by cqx931** [comment]
Currently, there is already a link on the website about google banning us, do you mean this banner is going to replace that with another link pointing to adnauseam's page on Firefox's extension store? (Or is there another link/press taking about this?)

**Comment by cqx931** [comment]
![image](https://user-images.githubusercontent.com/3056154/65634541-6f870780-dfac-11e9-8f1b-45ecdab16bf9.png)

**Comment by dhowe** [comment]
Definitely better... Can we make the bottom half more bright and 'blingy' ? Like some kind of shining star effect perhaps...

**Comment by mushon** [comment]
Great work @cqx931. Sorry for not responding earlier. 
Maybe we can try this with the siZe of the banned by Google smaller. Like:
```
Banned by Google 🌑
R E C O M M E N D E D
               by


        FIREFOX


```

If you want I can take a pass at this over the weekend.

**Comment by mushon** [comment]
How about this? (it's in @2x size)
![adn_chrome-firefox-gif](https://user-images.githubusercontent.com/27123/65816808-0e0fa480-e209-11e9-9aa5-113f3d0d624f.gif)

**Comment by cqx931** [comment]
@mushon It looks very nice! I would have expected that the adnauseam icon is going to perform a click at either the beginning or the final stage of the gif. 
Also for FIrefox, it makes more sense to me if "Recommended by" is in orange while Firefox is in White.

**Comment by dhowe** [comment]
looks great, thanks @mushon and @cqx931 .. (and I like the idea of the click as well) !

**Comment by mushon** [comment]
Agreed. How about this one:
![adn_chrome-firefox-gif-2](https://user-images.githubusercontent.com/27123/65830906-88e5c780-e2bc-11e9-8a65-3f9cfe427e70.gif)

**Comment by cqx931** [comment]
I have removed the "new feature in AdNauseam" gif and moved the journal image over to its original place. The new gif right now links to our google press release, while the support banner links to the baker link
![image](https://user-images.githubusercontent.com/3056154/66670900-e23ce780-ec28-11e9-98ef-d3ac4fa8f556.png)

**Comment by dhowe** [comment]
This looks really good to me -- my only question regards the spacing around the elements circled below, which feel a bit cramped compared to the rest of the page?

![image](https://user-images.githubusercontent.com/737638/66696150-0289a680-ecfc-11e9-9131-d38c6099c928.png)

**Comment by cqx931** [comment]
I adjusted the spacing for these elements in this commit. Please check:https://github.com/dhowe/AdNauseam/commit/9ba040730260f1d00eea954b9fe4e67995127e62

**Comment by dhowe** [comment]
> I adjusted the spacing for these elements in this commit. Please check:[9ba0407](https://github.com/dhowe/AdNauseam/commit/9ba040730260f1d00eea954b9fe4e67995127e62)

Can you take a screenshot? thanks

**Comment by cqx931** [comment]
![image](https://user-images.githubusercontent.com/3056154/67889770-d062ac00-fb25-11e9-95c9-6faef5c0a9c1.png)

**Comment by dhowe** [comment]
what happened to the twitter button?

**Comment by cqx931** [comment]
ops, I think that's some cache issues. It's back when I clear my browser history.
![image](https://user-images.githubusercontent.com/3056154/67902625-fe54ea00-fb3f-11e9-9fb3-79c867520508.png)

**Comment by dhowe** [comment]
We've added many new images over the years in somewhat random positions -- I wonder if we should re-layout the various elements on the page ?

**Comment by cqx931** [comment]
Are there any new images you want to add? If not I can go ahead and make a new layout image for the homepage.

**Comment by dhowe** [comment]
Not at the moment (though would be nice to replace the cheesy 'contact-us' envelope) -- other than that, perhaps just a question of layout (and prioritizing the important stuff at the top)

**Comment by cqx931** [comment]
Which content have higher priority? (other than time based criteria)

**Comment by cqx931** [comment]
Attempt to tidy up the layout. I got rid of the press release image for AdNauseam3.0 as it's been quite a long time ago.
![image](https://user-images.githubusercontent.com/3056154/67981955-1a1bc700-fbf8-11e9-8bf3-a15b9d081af6.png)

**Comment by dhowe** [comment]
This looks _much_ better. Can we replace the 'contact-us' envelope, and perhaps put a small "Read the Paper" link somewhere toward the top?

**Comment by cqx931** [comment]
@dhowe do you mean a "Read the Paper" banner or add it in the first paragraph? Which paper should it link to?

**Comment by cqx931** [comment]
Another 'contact us' banner
![image](https://user-images.githubusercontent.com/3056154/69192980-c106cb00-0af3-11ea-8a9b-856e6605b998.png)

**Comment by dhowe** [comment]
> do you mean a "Read the Paper" banner or add it in the first paragraph? Which paper should it link to?

The 'Engineering Privacy and Protest' paper -- maybe just a text link at the end of the first paragaraph? 

Also 'Ad' should be lowercase throughout the text. 

And we can remove the 'press release' link as it is quite old

**Comment by cqx931** [comment]
> And the contact image looks good (it will have a transparent background?)
yes, the black background is just a temporary mockup to cover the original image.

**Comment by cqx931** [comment]
Updated here: https://github.com/dhowe/AdNauseam/commit/f1111ea811fafcd0aebde86309527b270293ef7b

**Comment by dhowe** [comment]
This looks good (do note that commits to the weebsite are immediately 'live', so maybe better to do a PR). 

To small questions/changes:
1. The background for the contact logo is still not fully transparent
2. Can we move 'privacy policy' up under 'frequently asked questions', then slide the book and paper up a bit ?

**Comment by cqx931** [comment]
1. Yes, as we do have other banners with black background, I thought this would be a better fit for the overall theme. But maybe no background looks better?
![image](https://user-images.githubusercontent.com/3056154/69459500-dec87000-0d3f-11ea-8d9a-936a550f9e55.png)

2. Like this?

![image](https://user-images.githubusercontent.com/3056154/69459461-cbb5a000-0d3f-11ea-80c6-8d2b138110d8.png)

**Comment by dhowe** [comment]
Both look better to me (I think). If you think the 2nd change looks too busy,  another options would be to slide 'press and links' and 'engineering privacy...' up a bit into that empty space:

![image](https://user-images.githubusercontent.com/737638/69474632-75f3fd00-0dfe-11ea-8028-18caf965dd9c.png)

**Comment by cqx931** [comment]
I don't think there is any empty space there, if you see that in the current version, that seems like an cache issue for me.

**Comment by dhowe** [comment]
Did you check in Firefox? For some reason, even after clearing cache, these two images do not show:

![image](https://user-images.githubusercontent.com/737638/69482483-fb0b0080-0e56-11ea-8a76-0bcd0959e23b.png)

**Comment by cqx931** [comment]
Interesting, let me check that.

**Comment by cqx931** [comment]
Please check https://github.com/dhowe/AdNauseam/pull/1584

Transparent background for 'Contact Us'

Javascript links for Facebook and Twitter banner

**Comment by dhowe** [comment]
I wonder if 'privacy policy' can fit to the left of 'reambiguation' and everything else on the right move up ?

**Comment by cqx931** [comment]
I think it's a bit too packed if placing 'privacy policy' on the left of 'reambiguation', how about on top of it instead?
![Screen Shot 2019-11-26 at 11 07 34 AM](https://user-images.githubusercontent.com/3056154/69651052-7f1edd00-103d-11ea-950e-20173a8257a0.png)
![Screen Shot 2019-11-26 at 11 11 03 AM](https://user-images.githubusercontent.com/3056154/69651054-7fb77380-103d-11ea-9fc3-d3f09cd6ff71.png)

**Comment by dhowe** [comment]
Yes. I like it! The only thing that bothers me slightly now is the vertical row of twitter, facebook, press (all the same width)...

**Comment by cqx931** [comment]
oh that was a recent change that I made, we can also go back to the original width with the second design.
![image](https://user-images.githubusercontent.com/3056154/69673645-c2427580-1068-11ea-8c5d-e751478dcdf7.png)

**Comment by dhowe** [comment]
> Its not cache issue - rather the images are being blocked by AdNauseam, specifically the following lists:
> 
> ![image](https://user-images.githubusercontent.com/737638/69482517-78cf0c00-0e57-11ea-998b-366b2a47ab98.png)
> 
> Is there a way around this (perhaps generating the href when clicked)? Ideally, no part of the site should be blocked by ANY list that is installed with AdNauseam (whether on or off by default)

@cqx931 I'm seeing the same problem [here](https://rednoise.org/daniel/), specifically with the twitter link in the footer. Can you work the same magic?

**Comment by cqx931** [comment]
Please check:
AdNauseam:
https://github.com/dhowe/AdNauseam/pull/1586/commits/70ec3090782cfdecacc295a51fd3ee550fff27b4

Website twitter tweak:
https://github.com/dhowe/Website/pull/196
