### ISSUE TITLE
Video ad visible on bbc.com in windows firefox 

### ISSUE THREAD

**Issue by oscaryfish** [dhowe/AdNauseam#1562]
Video ad shown on: 
https://www.bbc.com/news/world-asia-china-49835561

Windows 10 Enterprise / Version 1803 / OS Build 17134.950
 
Firefox version 69.0.1 (64-bit)
Adnauseam 3.7.802
Dark Reader 4.8.1

### Your location/country
Hong Kong
![image002](https://user-images.githubusercontent.com/20669777/65835970-8b2d3d80-e31f-11e9-8cac-30b6221b334f.jpg)

**Comment by cqx931** [comment]
@oscaryfish  Thank you for the report, 
Please verify by updating the adnauseam filter in your 3p-filter settings page.
