### ISSUE TITLE
I believe this extension may be entirely ineffective for its purposed intents

### ISSUE THREAD

**Issue by ranolfi** [dhowe/AdNauseam#1563]
It is my understanding that a tracker network (e.g. Google Ads) tracks which pages users visit by loading tracking scripts from their domain into the page. This is [mentioned in the FAQ](https://github.com/dhowe/AdNauseam/wiki/FAQ#what-is-user-tracking-how-does-tracking-work):

> **What is user tracking? How does tracking work?**
> 
> When you visit a webpage, parts of the page may come from domains and servers other than the one you asked to visit. This is an essential feature of the web, but it has also come to be a serious privacy problem. (...)

After reading the FAQ it is clear to me that this extension is developed as a means of protest against such tracking.

But one thing remains not entirely clear - in order for the extension to click the advertisement links, it must load the advertisements from the ad network. Doesn't that mean that all users of this extension are still being tracked?

This is alluded to in [another FAQ entry](https://github.com/dhowe/AdNauseam/wiki/FAQ#isnt-it-safer-just-to-use-an-adblocker-why-engage-with-ad-networks-at-all) _(and I digress the use of the word "marginally" here)_:

> **Isn't it safer just to use an adblocker? Why engage with ad-networks at all?**
> 
> While AdNauseam is far safer than using no blocker at all, it is indeed marginally safer for one to simply use a strong adblocker and protect themselves. But it is also safer to stay at home rather than to attend a protest. Using an adblocker does little to change the status quo (especially for those users without the resources to install/configure one, and so remain at risk). AdNauseam, and the obfuscation strategy in general, instead presents a possible avenue for collective resistance; a means of questioning and perhaps eventually, changing the system. But this is not for everyone. If your goal is primarily self-protection, this tool may not be for you...

I am afraid that, for an advertisement network, **the information of which pages an user visits**, as well as when, for how long, and in what order, **is much more valuable than which ads they might click.** Not only that, but I also find it extremely likely that these ad networks can also detect when someone seems to be 'clicking' too much unrelated/irrelevant ads in a suspicious manner, and discard this information from their main statistics about a certain user.

Have concerns such as these ever been addressed by the extension developer(s)?

Disclaimer: I am not an AdNauseam user.

**Comment by Imparium** [comment]
Hello Ranolfi.
Please take note that AdNauseam send random http headers, such as user-agents, OS, and cookies.
Thus, Google will not be able to trace you back as you are sending random cookies to them, which they rely to locate you.

However, please note that I am NOT a dev from AdNauseam's team. So I may be wrong.

**Comment by sulinys** [comment]
Its better not block, but make random http heater, user-agent and etc. When you block, they know you're blocking, but when you pretend you're lost in general stats. Its same like fingerprints, if you unique - they know you, if you same like millions - they no longer see you.

It’s just my opinion and experience...

**Comment by dhowe** [comment]
Thanks for the comments all. However these questions have been discussed elsewhere, in the FAQ and/or reddit and/or the project's [gitter](https://gitter.im/dhowe/AdNauseam) page. Issues here should be related to bugs, features, enhancements, etc. Please use the [gitter](https://gitter.im/dhowe/AdNauseam) for general and/or philosophical discussion.

**Comment by ranolfi** [comment]
Hi @Imparium, thanks, I wasn't aware of that. But the tracking is done as soon as the external scripts are retrieved/loaded from the ad network; do you know if the measures you are mentioning are also in place for that first request, as opposed to only the ad-clicking requests that are done once the page is loaded?

@dhowe Ok I'll have a look; thanks.
