### ISSUE TITLE
Ads visible on spiegel.de

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1565]
https://www.spiegel.de/international/world/hong-kong-protests-channel-deep-seated-anger-a-1289465.html#ref=nl-international

![image](https://user-images.githubusercontent.com/737638/66264005-ea171900-e82f-11e9-89f8-b92ddc0db21c.png)

**Comment by cqx931** [comment]
fixed here https://github.com/dhowe/AdNauseam/blob/master/filters/adnauseam.txt
