### ISSUE TITLE
Cannot install V3.8.401 AdNauseam into Chrome. Missing manifest file

### ISSUE THREAD

**Issue by lashakv** [dhowe/AdNauseam#1569]
### Describe the issue
Once I've clicked on **Load Unpacked** and selected folder which includes the latest *.CRX file (v.3.8.401.chromium.crx), Chrome failed to load it saying that: 
> Manifest file is missing or unreadable

### Screenshot in which the issue can be seen
<img width="515" alt="Screen Shot 2019-10-17 at 10 49 19 PM" src="https://user-images.githubusercontent.com/1793647/67046698-10db2680-f131-11e9-92a2-965a49546180.png">

### Steps for anyone to reproduce the issue

1. Download the latest *CRX file from: https://github.com/dhowe/AdNauseam/releases/tag/v3.8.401
2. Save it to folder.
3. Go to Chrome. **chrome://extensions/**
4. Click **Load Unpacked** and select the folder with *.CRX file
Actual: Error message: 

> Manifest file is missing or unreadable. Could not load manifest.

### Your settings

- OS/version: MacOS 10.14.6
- Browser/version: Chrome: Version 77.0.3865.120 (Official Build) (64-bit)
- AdNauseam version: v3.8.401
- Other extensions you have installed: grammarly, google translate, wikiwand, lastpass, ghostinspector

### Your location/country
Austria

**Comment by cqx931** [comment]
Hi @lashakv, please follow exactly [the installation instruction for chrome](https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission#manual-install-in-developer-mode). Instead of the CRX file, you should download the zip file for installing AdNauseam as an unpacked extension.

**Comment by lashakv** [comment]
@cqx931 shame on me! seems that I was very asleep.. thank you!
