### ISSUE TITLE
Add export-ads buttons to vault

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#157]
Seems this is where people are more likely to use it... (currently the button is only at the bottom of the setting page):

![screen shot 2016-09-07 at 11 29 32 am](https://cloud.githubusercontent.com/assets/737638/18298874/8289dc6c-74ee-11e6-9ea5-55070a2be6a1.png)

**Comment by dhowe** [comment]
on hold, waiting for design...

**Comment by mushon** [comment]
added button to the vault, @dhowe please hook it in

**Comment by mushon** [comment]
added import and clear buttons too, awaiting implementation

**Comment by leoneckert** [comment]
@dhowe One option here is to import settings.js into vault.html to be able to use the same (export/import/clear-)functions. The other way would be to transfer/copy the functions into vault.js . What would be the preferred way? 
I guess this also depends on whether or not the buttons will remain in the Settings page too, or only exist on the vault from now on.
@mushon the vault is so nicely responsive, but the new buttons are not yet. Just in case you haven't seen. Hi by the way, I am Leon here from ITP.

**Comment by dhowe** [comment]
any reason not to add them to js/adn/shared.js ?

**Comment by leoneckert** [comment]
I can do that, my only worry is that I don't know with some of the functions (e.g. onLocalDataReceived in options.js) whether they are also used in other processes (pretty sure with that one). I guess placing such functions in shared.js would still not break functionality (as shared.js is imported before options.js, but might disrupt the order of the code/break the context a bit. 
Anyhow I will try and you can see what you think about it.

**Comment by leoneckert** [comment]
seems like the import on both options and vault is now not working anymore. working on that

**Comment by dhowe** [comment]
@leoneckert can this be closed (if so, do it)
