### ISSUE TITLE
Video ads on www.dotabuff.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1570]
EMAIL:
> Hi, I love your extension. However there is a website I frequent that has sneaky auto loud auto playing video ads.
>  
> www.dotabuff.com I don’t know the exact timing for the video ads to play but they appear in the bottom right of the page. If I inspect the element when it plays there is what looks like a comment
> “#document” and a whole new body tag. If you reload the page and inspect the source I can’t find the #document line so it seems like it just appear somehow.
>  
> I wonder if you will be able to squash this one.
>  
> Thanks for all your work

**Comment by dhowe** [comment]
Verified:

https://www.dotabuff.com/blog/2019-09-25-three-top-picks-of-the-current-meta-and-what-changes-we-want-to-see

![image](https://user-images.githubusercontent.com/737638/67072420-61956280-f1b7-11e9-825d-e2991e462c74.png)

**Comment by dhowe** [comment]
See also: https://github.com/dhowe/AdNauseam/issues/1571

**Comment by cqx931** [comment]
Does that video just automatically play as soon as the page is loaded? I can't reproduce the video ad.

**Comment by dhowe** [comment]
No, it plays only after some long delay.
For me, I had to click on an article, then scroll to the bottom, then wait for a while (keep your sound on)

**Comment by cqx931** [comment]
Added cosmetic and blocking rules for dotabuff
https://github.com/dhowe/AdNauseam/pull/1577/commits/cd2759cbda537fe090a8e09acde3e82e035da46f
