### ISSUE TITLE
Precedence for adn-allow vs custom filters

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1571]
@cqx931 I have manually added and applied the rule below in my custom filters, yet I still see adn-allow for the resource in question -- what is going on here?

URL in question is: https://www.dotabuff.com/blog/2019-10-15-skywrath-mage--a-new-hero-to-deal-with

![image](https://user-images.githubusercontent.com/737638/67073765-5ee83c80-f1ba-11e9-9f91-86f5f90c9cf7.png)

![image](https://user-images.githubusercontent.com/737638/67073828-79bab100-f1ba-11e9-932f-fb421d6b7ba2.png)

**Comment by cqx931** [comment]
The blocking rule from "My filter" seems to work fine on my end. Tested both in Chrome and Firefox.
<img width="1164" alt="Screen Shot 2019-10-20 at 2 22 05 PM" src="https://user-images.githubusercontent.com/3056154/67164439-853be280-f348-11e9-9933-47172b44fdcf.png">
