### ISSUE TITLE
Add color-key for logger within the logger

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1572]
Would be useful I think to have a key for the logger (as shown below)  to be accessible directly from _within_ the logger, perhaps as an overlay.

https://raw.githubusercontent.com/wiki/dhowe/AdNauseam/logger-colors.png

**Comment by cqx931** [comment]
Or add a "?" icon in the top menu?
<img width="1280" alt="Screen Shot 2019-10-20 at 2 11 24 PM" src="https://user-images.githubusercontent.com/3056154/67163979-8c142680-f343-11e9-9ed0-5e14f0475a04.png">

**Comment by mneunomne** [comment]
@dhowe but the `i` button already links to our wiki of the logger, isn't that enough ?

**Comment by dhowe** [comment]
The thinking was that it would be easier to see it in the logger, but yes... that is why it is just an 'enhancement', without a priority...

**Comment by mneunomne** [comment]
Added a color key icon on the right corner and the image from our documentation with the color key.

![colorIcon](https://user-images.githubusercontent.com/4967860/145716040-d9005f36-cd2a-43ee-b367-3c9ec2414070.PNG)
![color key2](https://user-images.githubusercontent.com/4967860/145716042-3fbfeca2-a4a0-4d01-997b-93c00a9972bb.PNG)

**Comment by dhowe** [comment]
great

**Comment by mneunomne** [comment]
Closing
