### ISSUE TITLE
Visible topbar on www.delfi.lt

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1573]
Email:

> Frequently I read news on www.delfi.lt But currently they use some circumvention software. Each time when I load new article or refresh the page 
> some wide bar still loads on the top of the page. It's a link to topsport site. It's a trash site which I treat as a spam. It's a commercial banner. Duo of 
> .. AdNauseam successfully blocks its image and other millions of adds. But this bar cannot be undergone. Each time I have to right click and to press to block it.
> Then select the bar and on the bottom right corner create new block entry. The add always loads with new and new identification URL:

 
![image](https://user-images.githubusercontent.com/737638/67095846-7b4f9d80-f1e9-11e9-8ff7-7f6f4377f193.png)

> For instance, it goes by www.delfi.lt##hmcxft  - each time new and new six last symbols set.
> 
> I believe you can create or already created a method how to automatically block such toxic circumvention software behavior.  I think it is possible to do so AdNauseam would read it and filter it and block it whatever last six symbols are. It is that bar with commercial shit. 
> 
> Can you create this, please? 
> 
> Here is the video: https://streamable.com/ai2wb
> 
> I look forward to hearing from you.
> 
> P.S. There are sites that detects whether a browser uses addblocker and if it does then a user cannot pass special field with info about blocker. And thus cannot get to the site and read information. Can it be bypassed?

**Comment by cqx931** [comment]
Fixed here: https://github.com/dhowe/AdNauseam/commit/d966fdb33c4db5faa8203853a3b785138fdfd351
