### ISSUE TITLE
Firefox, Mac, no ad clicking

### ISSUE THREAD

**Issue by drunami** [dhowe/AdNauseam#1574]
I've noticed that AdNauseam hasn't clicked anything for me in so long that my ad vault is now empty. I've tried every combo of settings I can and nothing seems to change it. Always "0 ads detected/clicked".

Thoughts?

My system:
Firefox 69.0.3, AdNaus 3.8.401
MacOS Mojave 10.14.6

thx

### Describe the issue

The official issue tracker for uBlock Origin is at:

https://github.com/uBlockOrigin/uBlock-issues/issues

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version:
- Browser/version:
- AdNauseam version:
- Other extensions you have installed:

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

**Comment by dhowe** [comment]
Strange. I wonder if your Firefox profile is corrupt. Would you mind trying with a new one, according to these instructions: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_creating-a-profile

**Comment by drunami** [comment]
Looks like that did it. Thx!
