### ISSUE TITLE
Issues with Google Ads targetURL

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1575]
To have a better understanding of what exactly is happening after each click I tried to track the internet requests for a manual click and an adnauseam click with the help of Live HTTP Headers. And I found despite all the effort, most of the links adnauseam parsed from google is still different compared with the url request with a manual click.

Here is an example of a typical adnauseam parsed targetURL, found in the href attribute of the a tag:
`https://googleads.g.doubleclick.net/aclk?sa=l&ai=CuTjXwGyvXcDUEJWmzgXmgZvADK2L1OtZzJbvpNYHpuPsz58OEAEg2tfFOWDJxqmLwKTYD6AB_9uKyAPIAQbgAgCoAwHIAwqqBPkBT9ClBBGF1w3I1vKXKf7srZ__dO9oSmz-yJlZIjqFt-S9fTLnqCqr1ktjTlRy_wlX-dieF2zw9WJu6MaAhJNwHWtMs6srpzff_f5nZP0xerO2IJAJO3JCcyCM4a5Q70uHZQ3mNgpaybgUhVHR_F4YabjxdBDC0ixBzNWvMt0WBUQAGEo3gJZ3k8nHjHgZeodb8ASQRaBCFV4qQbIDp9wo89YrNPY2nmkY-9zYXimOP3s9hgHSX15JZuIP8Adn5swyMoXOEmk1wwRprLkIXoaasPKbQ2UArPCL-dEPjWoQJB18QzzPSE-BsEIScBB2PZ_d5ORtSSjU8inh4AQBoAY3gAeG85wJqAeOzhuoB9XJG6gHk9gbqAe6BqgH2csbqAfPzBuoB6a-G6gH89EbqAfs1RvYBwHSCAcIgGEQARgd8ggbYWR4LXN1YnN5bi0zOTg2NjkwMTc5MjQ4MDA3sQnUugMVtzXuO4AKA9gTDIgUAQ&ae=1&num=1&sig=AOD64_2i4FrcXSA3PtlgqeIt0SAYnpd0cA&client=ca-pub-3605257360853185&nx=CLICK_X&ny=CLICK_Y&nb=9&adurl=https://www.grammarly.com/%3Futm_source%3Dgdn%26utm_medium%3Dcpc%26utm_campaign%3Dstudent-custominmarket-t1%26utm_phase%3Dstudent%26utm_content%3D289040061813%26placement%3Dwhatismyipaddress.com%26network%3Dd%26gclid%3DEAIaIQobChMIwLSjqeCw5QIVFZOzCh3mwAbIEAEYASAAEgJK-_D_BwE`

Here is an example of the web request from the same ad being manually clicked:
`https://googleads.g.doubleclick.net/pagead/conversion/?ai=CkmwmwGyvXbbYEJWmzgXmgZvADNuE7IxW3K6ukeUJsJAfEAEgpYj7AWDJxqmLwKTYD6AB5df-_APIAQngAgCoAwGqBPMBT9AJxL0E9OCbnNSFvBfenNNIRoaSd2opBDo2MyEEh95-vq60Qv13SLyRbGQjYZFxdXGkATPn43p66LkaAG6ayY0cIlBIbmznloATkvuVmAWVXdJtJBQr9Cin85k84_DM7YDlTPi8rfDtLeKR1djO4-htJCg68JtywsTiQeisTMb7ZqF8TnBjXPnOitEYRk7XFYxQw7azt80kBgDxWLwoxY9SPFqZI8xc8IwYbU_DMXRD3yowsoyFpOaKgS7-2UGp76rG9dQVfJd-irfnXhmQPrHFUjKQ2gW4xel8xCrwhLxr14sOL0n_rmjm5S4oKSOmb5X94AQBoAYRgAeDqIEDqAeOzhuoB9XJG6gHk9gbqAe6BqgH2csbqAfPzBuoB6a-G6gH89EbqAfs1RvYBwDSCAcIgGEQARgdgAoB2BMM&sigh=KJyIAPLW8Tc&cid=CAQSLQDwy9IZ8boddQzorRQ57Z2bdwZGQf_VxlVmindiTJDHVMptTpDgmdmjWGl4GQ&label=window_focus&gqid&qqid=CLa4o6ngsOUCFRWTswod5sAGyA&fg=1`

There is a huge difference between the two links, and despite the obvious difference between `aclk?` and `pagead/conversion/?`, the difference in queries can be better observed with 
[a url parser](https://www.freeformatter.com/url-parser-query-string-splitter.html).

Here is a summary
AdNauseam queries:
'sa', 'ai', 'ae', 'num', 'sig', 'client', 'nx', 'ny', 'nb','adurl'
Real click queries:
'ai','sigh', 'cid','label','qqid','fg'

If we want to construct the correct url, we are sure about these attributes `label=window_focus` and `fg=1`. However, I'm not sure about 'ai','sigh', 'cid'. All these attributes can be found somewhere in the document, but I'm not sure whether they are the correct one to use(they also seem to be different just from my observation). At the same time, I find no trace of 'qqid' within the dom structure. And a manually constructed url made by me with copy and paste only ended up landing on a blank page.

I can find some traces of these conversion urls in the dom structure, which can also be found in our current example http://chenqianxun.com/testcases/googleAdSenseCases_files/mainack.html
(inspect/Elements > search for 'conversion' ). 

Need more time to look for the code to construct these urls. Will report back later with more results.

**Comment by cqx931** [comment]
@dhowe

**Comment by dhowe** [comment]
We do need to investigate headers, and sub-resource requests, but there are also other differences (including the set of javascript events that would be triggered). 

I wonder if we should move this discussion of the public issues page?
