### ISSUE TITLE
'Corrupt' Firefox profiles

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1576]
We've had numerous reports of ADN installs that no longer click correctly. The solution seems to be create a new Firefox profile, however we need to get to the bottom of why this is happening, so I'm creating this ticket for further discussion.

See https://github.com/dhowe/AdNauseam/issues/1574, #1507, https://github.com/dhowe/AdNauseam/issues/1346, #1311, for examples

One possible cause (from #1311):

> ..."Never remember history" looks the same as "Always use private browsing mode." Switching off "Never remember history" does make AdNauseam work again in Windows 7. Then if you choose "Use custom settings for history" and tick "Always use private browsing mode," AdNauseam stops working again per that FAQ item. I believe that my previous experiments with this in Windows 7 were not valid, because I accidentally had Privacy Badger running during them. In any case, the above behavior is repeatable on my machine now.
> 
> This seems like a messaging issue. Firefox doesn't tell you that "Never remember history" is effectively the same as "Always use private browsing mode." The way to get Firefox to stop collecting browsing history and still have AdNauseam work is to select "Use custom settings for history" and then untick "Remember my browsing and download history" as well as "Remember search and form history."

**Comment by cqx931** [comment]
As mentioned in #1311
`browser.privatebrowsing.autostart` is set to True if the history setting is set to "Never remember history" or "Use custom settings for history" + "Always use private browsing mode".
With this attribute setting to True, no ad is collected by adnauseam. And this happens across platforms and is not a windows only issue.

We can add this setting to our firefox setting check code here.
https://github.com/dhowe/AdNauseam/pull/1477/commits/b9c874993efb3fa82153a4c6b46e38527a390500

**Comment by dhowe** [comment]
> I suggest that we add another notification whenever adnauseam detects that the browser is in private mode(no matter which scenario), something like "You have allowed adnauseam to have access to your online activities while private browsing. [Disable AdNauseam for privacy mode]"
> And the [Disable AdNauseam for privacy mode] button can links to about:addons/chrome:extensions page for the user to modify the setting.

Sounds exactly right

**Comment by cqx931** [comment]
@dhowe The only case I could think about is when the user wants to always block and hide the ad, but not collect and click in privacy mode. This means they don't need to adjust the settings every time they change between default/privacy mode.

**Comment by dhowe** [comment]
Right, I see the case. Am I correct that no one has asked for this functionality as yet?

**Comment by cqx931** [comment]
![image](https://user-images.githubusercontent.com/3056154/67983661-864bfa00-fbfb-11e9-8964-ef7a3281536c.png)

Could you please check whether the text being used here is okay? Instead of "in incognito", it is "while private browsing" for firefox.

**Comment by cqx931** [comment]
I updated the new notificationsin developer FAQ, could you please check the general FAQ for private browsing/incognito? Not sure what should be written there in the current situation.

https://github.com/dhowe/AdNauseam/wiki/FAQ#does-adnauseam-respect-the-browsers-private-browsingincognito-modes

**Comment by dhowe** [comment]
Do we really need the warning above? The use has already specifically opted to enable adnauseam in private/incognito mode, so I'm thinking not...

**Comment by dhowe** [comment]
> Does AdNauseam respect the browser's private-browsing/incognito modes?

Yes, AdNauseam does not collect or click Ads that occur on pages loaded in private-browsing or incognito windows, unless manually enabled by the user.  

?

**Comment by cqx931** [comment]
I think the message is mainly for firefox users, especially when the user is not aware that firefox is actually using privacy mode for certain settings that might be helpful. So maybe we can remove that for chrome.

**Comment by cqx931** [comment]
Updated
https://github.com/dhowe/AdNauseam/commit/80b72e4a9e6303c48e6136afccf4561601f23b4b
