### ISSUE TITLE
9

### ISSUE THREAD

**Issue by hadyku** [dhowe/AdNauseam#1578]
### Describe the issue

The official issue tracker for uBlock Origin is at:

https://github.com/uBlockOrigin/uBlock-issues/issues

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version:
- Browser/version:
- AdNauseam version:
- Other extensions you have installed:

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

**Comment by cqx931** [comment]
@hadyku what's the issue you want to report here?
