### ISSUE TITLE
AdNauseam does not block ads as effectively as uBlock Origin.

### ISSUE THREAD

**Issue by blurrred** [dhowe/AdNauseam#1580]
### Describe the issue
Ads get through and are rendered in the browser with AdNauseam that do not get through with uBlock Origin.

The official issue tracker for uBlock Origin is at:

https://github.com/uBlockOrigin/uBlock-issues/issues

### Screenshot in which the issue can be seen
https://imgur.com/a/MJ6ZtMg

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
Some ads will be blocked properly, some won't, even on the same page.

### Your settings

- OS/version: Manjaro Linux 18.1.2
- Browser/version: Firefox 70.0.1 (64-bit)
- AdNauseam version: AdNauseam v3.8.401 uBlock Originv1.17.0 
- Other extensions you have installed: New Tab Override

##### Your filter lists

Default filter lists + enabling just about everything I can that makes sense, such as the annoyance.

### Your location/country
United States of America
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

**Comment by cqx931** [comment]
I have fixed the issue you reported in this ticket here: https://github.com/dhowe/AdNauseam/commit/b1cf3eda3e34d469b4b3258a41efdefed6c81572. Please update adnauseam filter list and see whether that's going to solve the problem on your side. Thank you!

**Comment by blurrred** [comment]
I forgot to specify that Kisscartoon is not the only website that AdNauseam does not filter properly.
I think it might have something to do with AdNauseam's version of uBlock Origin being behind the official uBlock Origin. I don't know how to update it for AdNauseam.

**Comment by cqx931** [comment]
Yes, AdNauseam's version of uBlock Origin is behind but the main reason why some ads are blocked in uBlock Origin but not in AdNauseam is that AdNauseam allows many blocking rules that uBlock Origin blocks. AdNauseam is allowing them because it needs ads to be rendered first to be able to collect/click them.

**Comment by dhowe** [comment]
@blurred please report any other ads that you see while using AdNauseam here, and we'll be sure to update our custom list so they are correctly hidden.

**Comment by MariaLovesGithub** [comment]
uBlock is bloking adds on http://fanserials.market
but AdNauseam is not (with similar filters settings)
https://imgur.com/a/d3ATWTt

**Comment by cqx931** [comment]
the site seems to be offline at the moment, I will check back later.

**Comment by cqx931** [comment]
This is what I see when I try to reproduce the issue, same thing in uBlock. @MariaLovesGithub  can you provide the exact url where you can see the ad?

![image](https://user-images.githubusercontent.com/3056154/69164857-ba119580-0abe-11ea-8a5c-6f4482d691aa.png)

**Comment by helperman** [comment]
The issue still persists with other links:
https://otzovik.com/review_9954215.html

Screenshot in which the issue can be seen:
https://i.imgur.com/bchnMpE.jpg

Your settings

    OS/version: Windows 8
    Browser/version: Firefox 75 (64-bit)
    AdNauseam version: AdNauseam v3.9.104 uBlock Originv1.26.2
    Other extensions you have installed: nothing

Your filter lists
Default filter lists + enabling just about everything I can that makes sense, such as the annoyance.

Your location/country
Russia

**Comment by helperman** [comment]
Another link with ads:
https://yandex.ru/news/quotes/1.html

Screenshot in which the issue can be seen:
https://i.imgur.com/1eMBFQ9.jpg

**Comment by helperman** [comment]
Link with ads:
https://mail.ru

Screenshot in which the issue can be seen:
https://i.imgur.com/QF6r1Xi.png

**Comment by cqx931** [comment]
Fixed the ads in yandex: https://github.com/dhowe/AdNauseam/commit/c76a2632a3ce7e729611f89db9d65262fe7ec36b

I can no longer reproduce the mail.ru issue, please open separate new tickets if it still happens.
