### ISSUE TITLE
Multiple ads visible

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1581]
https://www.atptour.com/en/scores/current/nitto-atp-finals/605/results

![Screen Shot 2019-11-14 at 6 08 13 AM](https://user-images.githubusercontent.com/737638/68808672-36fad480-06a5-11ea-8e36-59ca62bf15b2.png)

**Comment by cqx931** [comment]
I just see that one slot in the image. What are the other ads you mean by "Multiple ads visible"?

**Comment by cqx931** [comment]
Hidden but can't collect this one because the image is dynamic. https://github.com/dhowe/AdNauseam/blob/master/filters/adnauseam.txt

**Comment by dhowe** [comment]
I thought the 'partners' were also ads, but I guess not
