### ISSUE TITLE
add info about chromium-web-store

### ISSUE THREAD

**Issue by KonoromiHimaries** [dhowe/AdNauseam#1582]
Because crx extensions don't work in chrome/chromium
https://github.com/NeverDecaf/chromium-web-store

https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission

Thx.

**Comment by dhowe** [comment]
What kind of information do you suggest?

**Comment by ganhiru** [comment]
Perhaps, a guide for Chrome Enterprise / Edge Chromium users that trust the maintainer of the updates.xml

If they add the following Key's to the HKLM or HKCU, no other actions need to be taken to install AdNauseam

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\ExtensionInstallForcelist]
"1"="pnjfhlmmeapfclcplcihceboadiigekg;https://rednoise.org/adnauseam/updates.xml"

For the Edge Beta you can set the same key in this location.
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\ExtensionInstallForcelist

**Comment by cqx931** [comment]
Updated the wiki page
