### ISSUE TITLE
webmd.com does not load

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1583]
I can't load any pages on this site without disabling adnauseam -- can you verify @cqx931 

https://www.webmd.com/

**Comment by cqx931** [comment]
Interesting... I also have issues loading the page in firefox with adnauseam installed. But same thing doesn't happen to chromium based browsers.

The site also doesn't load even if I disable all the functions in adnauseam. This is the error message I saw in background.html:

![image](https://user-images.githubusercontent.com/3056154/69161383-0e197b80-0ab9-11ea-9dc5-ea59ffd717fc.png)

**Comment by cqx931** [comment]
Not sure how these two lines of code are deleted, but once I put them back, the issue is fixed.
See:
https://github.com/dhowe/AdNauseam/commit/8f89201cf3abb30ca126ceb201a50be3f99aca4c

**Comment by dhowe** [comment]
ok - any eta for a new release?
