### ISSUE TITLE
Video ads on captiongenerator.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1585]
https://www.captiongenerator.com/1586792/Xi-meets-with-Carrie-Lam-after-DC-Elections

![image](https://user-images.githubusercontent.com/737638/69708213-297a2b80-1136-11ea-9dad-72d0a3be8de4.png)

**Comment by cqx931** [comment]
I tried to visit several videos and refreshed the page multiple times, but still can't reproduce this issue.
