### ISSUE TITLE
site www.avito.ru always blocked until I disable the extension.

### ISSUE THREAD

**Issue by dragons-lair** [dhowe/AdNauseam#1587]
### Describe the issue
 www.avito.ru site is permanently blocked if AdNauseam is enabled,
even if I disable all blocking and all filters.
Another browser can connect without problems.

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version: Debian 10
- Browser/version: Firevox 68.2.0esr (64-bit)
- AdNauseam version: 3.8.401
- Other extensions you have installed:

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
Saint-Petersburg, Russia

**Comment by dragons-lair** [comment]
I found that it happens only if "Disable hyperlink auditing" option is enabled. If I uncheck it and restart browser, then everything works.

**Comment by cqx931** [comment]
Hi @dragons-lair, thank you for reporting the issue.
I tried to reproduce this issue on a Mac by enabling "Disable hyperlink auditing" in about:config, but I was not able to see the site you mentioned being blocked. Have you tried the same setting with uBlock origin?

**Comment by dragons-lair** [comment]
> Have you tried the same setting with uBlock origin?

Yes, same result.
I've tried different combinations of filters, no luck.

**Comment by cqx931** [comment]
If you got the same result with uBlock origin, then it is not an issue with AdNauseam. You can try opening an issue in the repo of uBlock origin instead.

**Comment by dragons-lair** [comment]
Looks like it's browser/os issues. Connection via local proxy (same public IP) works fine.
