### ISSUE TITLE
Facebook Sponsored Ad

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1588]
I can see Facebook sponsored posts again(in the feed) on Adnauseam, which also happens in uBlock origin.
Tried a few lists available in uBlocks but none of them could block Facebook's sponsored ads at the moment.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/3056154/70086293-13f67d00-15e0-11ea-91b7-544240efe674.png">

**Comment by cqx931** [comment]
Shall we consider having this list pre-packed by Adnauseam?

Title: "facebook annoyances blocker"
URL: https://easylist-downloads.adblockplus.org/fb_annoyances_full.txt

**Comment by dhowe** [comment]
Yes, I think so

**Comment by cqx931** [comment]
Added here: https://github.com/dhowe/AdNauseam/commit/15339961e0432f792a68f73543e750a3f210d2e2

**Comment by cqx931** [comment]
Seeing these sponsored posts in streamline again.

**Comment by mneunomne** [comment]
The ads are probably showing because the file for "facebook annoyances blocker" no longer exists: [https://easylist-downloads.adblockplus.org/fb_annoyances_full.txt](https://easylist-downloads.adblockplus.org/fb_annoyances_full.txt), which was added in  https://github.com/dhowe/AdNauseam/commit/15339961e0432f792a68f73543e750a3f210d2e2
We probably need to find another equivalent list.

**Comment by dhowe** [comment]
Can we check whether ublock has a replacement as yet?

**Comment by mneunomne** [comment]
@dhowe I tested them but none seem to be successfully hiding fb feed ads. It seems to be a cat-mouse situation at the moment:
https://github.com/uBlockOrigin/uAssets/issues/3367
https://www.reddit.com/r/uBlockOrigin/comments/kejwbz/facebook_sponsored_posts/

**Comment by dhowe** [comment]
are they blocked in ublock then?

**Comment by mneunomne** [comment]
At the moment no (I updated the lists to certificate as well)

With uBlock Origin activated:
![Screen Shot 2021-02-24 at 13 47 26](https://user-images.githubusercontent.com/4967860/109002780-f01ccc80-76a6-11eb-8e42-05509719fac5.png)

**Comment by dhowe** [comment]
then we don't need to worry about it -- it needs to be fixed first on the lists and in ublock

**Comment by mneunomne** [comment]
Sure, but either way we should probably remove what was added on https://github.com/dhowe/AdNauseam/commit/15339961e0432f792a68f73543e750a3f210d2e2, since it is now broken

**Comment by dhowe** [comment]
good point

**Comment by mneunomne** [comment]
reversed https://github.com/dhowe/AdNauseam/commit/15339961e0432f792a68f73543e750a3f210d2e2 with https://github.com/dhowe/AdNauseam/pull/1757
