### ISSUE TITLE
Some blocking rules are not working when the same request is also blocked by EasyList

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1591]
Site: https://www.captiongenerator.com/1586792/Xi-meets-with-Carrie-Lam-after-DC-Elections

Rule:
`/ads?client=*video-pub*`

The rule itself is correct and can be blocked by ublock if added into "My Filters", the same rule does not fire in adnauseam, both in "My Filters" and in adnauseam.txt. 

Previous related issue: https://github.com/dhowe/AdNauseam/issues/847

**Comment by cqx931** [comment]
This is because adnauseams core.js got it's information about net filtering from https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L1167.
According to https://github.com/dhowe/AdNauseam/blob/master/src/js/static-net-filtering.js#L2797, snfe.toLogData() only returns the first token that get matched to a request.

So if the token by easylist is the first blocking filter matched, we will only know that a certain rule is blocked by easylist, while it might also be blocked by adnauseam.txt or My Filters.

**Comment by cqx931** [comment]
@dhowe

**Comment by dhowe** [comment]
seems we need to check each rule, at least until we get one that is a real block, yes?

**Comment by cqx931** [comment]
yes, exactly. It doesn't make a difference for ublock where the rule is from, but it does for us.

**Comment by dhowe** [comment]
lets try it

**Comment by cqx931** [comment]
Please check the PR. The issue is now addresse. If a request is blocked by My Filters and Easylist, adnauseam can now block the request appropriately.
