### ISSUE TITLE
Ads visible on davidwalsh.name

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1592]
https://davidwalsh.name/query-string-javascript

![image](https://user-images.githubusercontent.com/737638/70324845-88911c00-186b-11ea-97f3-e528ea62f8a3.png)

**Comment by cqx931** [comment]
Hidden here: https://github.com/dhowe/AdNauseam/commit/815189efa39b2b5b0a2f97ea2110c2c999348d50

**Comment by cqx931** [comment]
Hidden here: https://github.com/dhowe/AdNauseam/commit/815189efa39b2b5b0a2f97ea2110c2c999348d50
