### ISSUE TITLE
Forbes blocked with AdNauseam

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1593]
Visible with uBlock

https://www.forbes.com/sites/thomasbrewster/2019/12/11/google-gives-feds-1500-leads-to-arsonist-smartphones-in-unprecedented-geofence-search/

![image](https://user-images.githubusercontent.com/737638/70766982-8b739b80-1d9a-11ea-8d4b-55421d52108f.png)

**Comment by cqx931** [comment]
I won't be able to see this after this fix on my end, but this notice is not visible for me on uBlock... so not sure whether the solution also work for you.
https://github.com/dhowe/AdNauseam/commit/d2788d8e25b0a1124a0c22edc1ea8bd8f89ea199

**Comment by cqx931** [comment]
I won't be able to see this after this fix on my end, but this notice is not visible for me on uBlock... so not sure whether the solution also work for you.
https://github.com/dhowe/AdNauseam/commit/d2788d8e25b0a1124a0c22edc1ea8bd8f89ea199

**Comment by dhowe** [comment]
looks good!
