### ISSUE TITLE
AdNauseam breaks Reuters pages

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1594]
Example: https://www.reuters.com/investigates/special-report/hongkong-protests-media/

Shows blank screen -- fine with AdNauseam disabled

**Comment by dhowe** [comment]
See also #1595

**Comment by cqx931** [comment]
This is caused by the same issue is this ticket. https://github.com/dhowe/AdNauseam/issues/1583
Should be fixed in the latest master branch.

**Comment by dhowe** [comment]
ok - any eta for a new release?

**Comment by cqx931** [comment]
See https://github.com/dhowe/AdNauseam/issues/1545, the major issue left is merging uBlock1.20.0 to the master branch and it depends on how many new issues will be found from the release testing.

**Comment by cqx931** [comment]
close this for #1545
