### ISSUE TITLE
'Paid Promotional Links' on Reuters

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1595]
https://www.reuters.com/article/us-hongkong-protests/hong-kong-leader-lam-heads-for-beijing-as-pressure-mounts-at-home-idUSKBN1YI02Q

![image](https://user-images.githubusercontent.com/737638/70843604-14a8d200-1e70-11ea-8094-45ce9d823890.png)

**Comment by dhowe** [comment]
Also, element-blocker does not seem to function on this page

**Comment by cqx931** [comment]
As an advertiser, dianomi seems to have both video ad and similar article feeds as what you saw in Reuters(with or without images).

I would suggest blocking their video ad scripts and creating new text parser for them.

Other sites that they serve: 
https://www.dianomi.com/cms/publishers/

**Comment by dhowe** [comment]
sounds good

**Comment by cqx931** [comment]
Fixed here. 
https://github.com/dhowe/AdNauseam/commit/efae22e68a726a93b4741aa48c9508a0db88243a
There are too many scripts trying to render the ads in different manners to bypass ad blockers, so I decided to block instead of hiding for Dianomi ads.
