### ISSUE TITLE
AdNauseam for cookie warnings 

### ISSUE THREAD

**Issue by Madis0** [dhowe/AdNauseam#1599]
AdNauseam is quite an interesting approach for the advertising nowadays. While I don't entirely agree with the point of this, I thought of a thing this approach _could_ be used for - cookie warnings.

Consider this use case.
User X browses the web a lot. They are indifferent about ads but they certainly don't like the cookie warnings. User wants to hide them while still keeping track of which sites request what.

That's where this extension could come in - hiding the prompts on every site while taking screenshots of the elements that prompt it, similar to what AdNauseam does for ads. 
Then when the user wants to have an overview of cookies used, they use this extension's overview, go to the site and temporarily whitelist it to control the settings.

This would also be compatible with content blockers that only block trackers and ads. 

References: https://www.i-dont-care-about-cookies.eu/ https://www.fanboy.co.nz/fanboy-cookiemonster.txt

**Comment by dhowe** [comment]
This should be possible simply by enabling cookie-warning lists (such as fanboy-cookiemonster.txt) in AdNauseam's 'filter-list' setting. Or am I missing something?

![image](https://user-images.githubusercontent.com/737638/71146455-4818a180-2260-11ea-876c-feecccfe50de.png)

**Comment by cqx931** [comment]
> hiding the prompts on every site while taking screenshots of the elements that prompt it, similar to what AdNauseam does for ads.

I think what the user is suggesting here is a vault for cookie-warning? Though I don't think that aligns with the goals of Adnauseam.

**Comment by dhowe** [comment]
Ah, as in collecting cookie-warnings... If so, then agreed - AdNauseam is designed to focus on advertising, not warnings or annoyances
