### ISSUE TITLE
Consider reconfiguring parser.js and textads.js

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1600]
As we are writing more specific parsers involving both image and text, I am proposing here an alternative reconfiguration of parser.js and textads.js.

Besides the focus on text, the major feature of how current textads works is that they are site-specific parsers. Could we reconfigure the text-ads parser as site-specific parsers? This would actually makes more sense as we add more site-specific parsers that not only involves text.

**Comment by cqx931** [comment]
@dhowe

**Comment by dhowe** [comment]
Yes, this makes sense, for sure.
