### ISSUE TITLE
[merge1.20.0]Asset viewer takes very long time to load

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1605]
To reproduce:
1. Go to 3p filters page
2. Click on "Easylist" to bring up the asset viewer
3. You will notice that it takes a very long time for adnauseam to load it, way longer than how it used to be and ublock

Especially for lists such as EasyList or EasyPrivacy. Shorter lists are fine.

No error message both in background & in asset viewing page. Will cause the computer to hang for a while until the filter is fully loaded.

**Comment by dhowe** [comment]
have you tried running the dev-tools performance monitor?
