### ISSUE TITLE
Re-evaluating test-cases after release

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1610]
- [x] Cookie-setting ad
Can we change the cookie setting request from another server other than rednoise?
    $LAB/adntest/cookie-setting-ad.html
Now the cookies are allowed because DNT 3rd-party cookies are allowed.

- [x] Test that no Ads are collected in incognito/private-browsing windows.
Ads are now collected in incognito.

- [x] Add opera only testing item
https://github.com/dhowe/AdNauseam/issues/1537

- [x] Test auto-upload by modifying variables from advanced-settings.html

- [x] We have two different dynamic iframe cases right now:
1. No src: $LAB/adntest/dynamic_iframe.html
1. With src: $RED/adntest/dynamic_iframe.html

**Comment by cqx931** [comment]
@dhowe 
Can we change the cookie setting request from another server other than rednoise?
http://lab-lamp.scm.cityu.edu.hk/adntest/cookie-setting-ad.html
Now the cookies are allowed because DNT 3rd party cookies are allowed.

**Comment by dhowe** [comment]
We can put it on lab-lamp@cityu, or just click the don't-use-dnt-list checkbox in adnauseam
let me know which you prefer

**Comment by cqx931** [comment]
I would prefer putting it on lab-lamp@cityu. Clicking 'doesn't use dnt list' checkbox does work, but I think it's better if a test case can stand by itself without modifying the setting.

**Comment by dhowe** [comment]
doesn't it need to be a different server than the web-page, to be a third-part test?

**Comment by cqx931** [comment]
yes, so the cookies could come from lab-lamp@cityu but the web page itself can be hosted somewhere else.(could potentially just put it on GitHub and use adnauseam.io?)

**Comment by cqx931** [comment]
New location for cookie-setting-ad: 
https://adnauseam.io/test/cookie-setting-ad.html

**Comment by dhowe** [comment]
(lets try to avoid live server urls in public comments in case of malicious actors)

**Comment by cqx931** [comment]
New test case: https://adnauseam.io/test/cookie-setting-ad.html
