### ISSUE TITLE
[merge1.20.0]new advanced settings for advanced user

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1613]
in ublock1.20.0, if a user ticks the advanced user box, the user can get access to change the following settings. 
<img width="313" alt="Screen Shot 2019-12-30 at 10 08 00 PM" src="https://user-images.githubusercontent.com/3056154/71608709-22897300-2b51-11ea-8a77-e6f7bb3496bd.png">
Clicking the settings icon will open up the following pane:
<img width="543" alt="Screen Shot 2019-12-30 at 10 08 08 PM" src="https://user-images.githubusercontent.com/3056154/71608710-24ebcd00-2b51-11ea-88ab-934aa22de376.png">

This could be very useful for development use, also some advanced users from ublock might want to keep that. Shall we bring back the advanced user tick and having it ticked by default(which is the current setting of adnauseam)?

**Comment by cqx931** [comment]
@dhowe

**Comment by dhowe** [comment]
I thought that we put the user in advanced mode by default ?

**Comment by cqx931** [comment]
Yes, but we hide this setting(including the advanced setting) together for the user as well.

This ticket seems to be related as well: https://github.com/dhowe/AdNauseam/issues/615

**Comment by dhowe** [comment]
so there are two settings? advanced user and the list above?

**Comment by cqx931** [comment]
yes, once the advanced user setting is clicked. The list can be accessed by clicking the small setting icon.

Sally

**Comment by cqx931** [comment]
This advanced setting was originally in settings page in ublock origin so I think it makes more sense to leave it there rather than putting it in the menu.

One potential place to consider is adding an "Advanced settings" header after "Interface" and put the settings icon besides
![image](https://user-images.githubusercontent.com/3056154/71621596-31e2dd80-2b9e-11ea-9e98-56393e9b0c1c.png)

**Comment by cqx931** [comment]
fixed 
![image](https://user-images.githubusercontent.com/3056154/71623553-67da8e80-2bab-11ea-83d2-208ddf4af58b.png)
https://github.com/dhowe/AdNauseam/commit/10da2f4d08c1f380d95c3d7ebcf0c74899e3b3c7
