### ISSUE TITLE
Set default allowGenericProceduralFilters to true in AdNauseam

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1618]
We might need generic Procedural Filters for Adnauseam? This is set to false by default in uBlock to enhance the general performance.

**Comment by mneunomne** [comment]
Now that procedural filters seem to be parsed and generating more ad collections/clicks, this makes sense yes. Needs some testing.

**Comment by mneunomne** [comment]
This is already the case actually. the option "Ignore generic cosmetic filters " is checked-out. Closing.
