### ISSUE TITLE
How do you use the private browsing implimentation in the new 3.9.102 update?

### ISSUE THREAD

**Issue by WhoAmI1000** [dhowe/AdNauseam#1621]
How do I allow adnauseam to collect ads in private browsing mode? In #1541, this was seen added to 3.9.102, but how can I actually enable it so it will click and collect the ads, too?

**Comment by dhowe** [comment]
https://support.mozilla.org/en-US/kb/extensions-private-browsing
https://lifehacker.com/enable-your-extensions-in-incognito-mode-for-safer-mor-1792622065
similar for opera

**Comment by WhoAmI1000** [comment]
Will it still collect ads?

**Comment by dhowe** [comment]
Yes
