### ISSUE TITLE
Does not collect ads in private windows

### ISSUE THREAD

**Issue by WhoAmI1000** [dhowe/AdNauseam#1622]
Adnauseam does not collect ads in firefox private windows. It will hide them, but not collect them, despite having the settings say to click on all ads.

**Comment by dhowe** [comment]
see also #1621

**Comment by cqx931** [comment]
@WhoAmI1000 
This should be fixed in the next release(3.9.102) which is waiting to be reviewed by the Mozilla store.
In the current version, this was the expected behavior in private windows, and we modified it so that Adnauseam can both hide collect ads in private windows from 3.9.

**Comment by WhoAmI1000** [comment]
Thanks.
