### ISSUE TITLE
Ads visible on www.opensubtitles.org

### ISSUE THREAD

**Issue by Skyfire11** [dhowe/AdNauseam#1625]
New annoying sidebar ads started appearing within the last month

![opensubtitles org sidebar ads](https://user-images.githubusercontent.com/60277118/73110604-c0354f80-3f0f-11ea-8b9e-62025439046b.PNG)

Browser: Chrome Version 79.0.3945.117 (Official Build) (64-bit)
Location: Finland

Btw idk if you have another forum...but thank you SO much for your dedication! I'm really happy this projects exists and is being constantly updated

**Comment by cqx931** [comment]
Thank you for reporting the issue! @Skyfire11 
Could you please provide the exact URL where you observer the issue?

**Comment by Skyfire11** [comment]
Happens on every page I have visited so far in the last month or so
However https://www.opensubtitles.org/en/search/subs is the "start" page I'm directed to @cqx931

**Comment by ice-fly** [comment]
Can confirm... top right overlay
ad points to https://xml.realtime-bid.com/click
chrome user

**Comment by cqx931** [comment]
@Skyfire11 
The issue should have been fixed after updating Adnauseam to 3.9.104 and also updating your adnauseam filters. Please verify.

**Comment by Skyfire11** [comment]
@cqx931 
Not so tech savvy, is there a way to update with just the Source code that is available for 3.9.104?
Usually my rare update has been by deleting the previous version and downloading the adnauseam.chromium.zip However that's not yet available for 1.9.104.

**Comment by cqx931** [comment]
@Skyfire11 The files should now be ready to download at https://github.com/dhowe/AdNauseam/releases/tag/v3.9.104

**Comment by Skyfire11** [comment]
Thx @cqx931 
Downloaded that and updated the filters. And we can see an improvement:
![2](https://user-images.githubusercontent.com/60277118/73794003-28a5eb80-47b0-11ea-8fc6-3dc7addce06e.PNG)
The lowest ad has been dealt with

**Comment by cqx931** [comment]
@Skyfire11 Could you please update the filters again and see whether that is going to fix the issue for you? 

The number is correct.

**Comment by Skyfire11** [comment]
Sweet that did the trick. Ty @cqx931  very much appreciated!
