### ISSUE TITLE
Google ads visible on Forbes.com homepage

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1630]
![image](https://user-images.githubusercontent.com/737638/73913866-0cf72e00-48f3-11ea-97ce-1a453024be4b.png)

![Screen Shot 2020-02-06 at 3 10 51 PM](https://user-images.githubusercontent.com/737638/73913855-07014d00-48f3-11ea-94ca-74a51e221910.png)

**Comment by cqx931** [comment]
I can't reproduce the ads above from the US.
After using a VPN from Hong Kong I do see different ads. The number of ads that get collected is different, but I still don't see any one that is visible.
