### ISSUE TITLE
Ads Visible on Ninjakiwi.com

### ISSUE THREAD

**Issue by WhoAmI1000** [dhowe/AdNauseam#1631]
There are ads visible on Ninjakiwi.com. Example: any game.

I went to test Adnauseam on it, and it doesn't block the ads.
![Screenshot_2020-02-08 Bloons Tower Defense 5](https://user-images.githubusercontent.com/39578224/74093955-47490280-4a8e-11ea-96f4-6f42035a283e.png)

**Comment by cqx931** [comment]
All ads on this website are not blocked by ublock origin.

Changes: 
- block pop-up ad
- hide a few ad slots that I could identify

@WhoAmI1000 please include a link and a screenshot if you still see any other visible ads.
