### ISSUE TITLE
AdNauseam collects adchoice logo as advertisement

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1633]
We should not collect Adchoice images and other tiny logos that are images but not the actual ad.
Need more restrictions on image size...

Where: https://www.bbc.com/news

![image](https://user-images.githubusercontent.com/3056154/74955904-5192c700-53d3-11ea-9250-8633820f4007.png)

**Comment by dhowe** [comment]
Yet its quite strange if the ad is removed and the ad choice button is left floating there, no?

**Comment by cqx931** [comment]
yes, so what Im suggesting is to hide them but not collect them as valid ad during verification.

**Comment by dhowe** [comment]
agreed

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/commit/9d5dd0c533b86f6b036d3d5201c4bc26f311f3ed
