### ISSUE TITLE
Chromium - Autoupdate XML points to wrong URL

### ISSUE THREAD

**Issue by ganhiru** [dhowe/AdNauseam#1634]
### Describe the issue
In the Latest release of adnauseam Chromium , the name of the .crx file does not contain the version number, this breaks - the updates.xml 

The Update URL descibed in :
http://rednoise.org/adnauseam/updates.xml
Points to 
codebase="https://github.com/dhowe/AdNauseam/releases/download/v3.9.104/adnauseam-3.9.104.chromium.crx" version="3.9.104"

### 
Current Release URL: https://github.com/dhowe/AdNauseam/releases/download/v3.9.104/adnauseam.chromium.crx

### Steps for anyone to reproduce the issue
Set Chrome Enterprise GPO registry:
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\ExtensionInstallForcelist
"1" REG_SZ "pnjfhlmmeapfclcplcihceboadiigekg;https://rednoise.org/adnauseam/updates.xml"

**Comment by ganhiru** [comment]
The Developer-FAQ suggests these are human steps.
https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ

**Comment by cqx931** [comment]
@ganhiru  Thank you for reporting the issue. I have updated the release asset so that the file name should match what we have in the update URL.

**Comment by ganhiru** [comment]
Confirmed, it's back to normal.
