### ISSUE TITLE
New AdVault Features?

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1644]
@dhowe 
Shall we add an extra info panel in the current AdVault, showing users some basic statistics of their ads based on all the visible ads? (which means that the users can interact with it by dragging the slider) Almost like profiling the ad system from bottom up.

We can show things like:
- The top sites where the ads are from
- The top ad networks where the ads are hosted
- Most Common Ad Format
- Anything else?

I was thinking about these things after today's discussion, the information we need for the test could also be interesting for the users to have a better understanding of their own ad data. Also, we can include ad network information after the user clicks on an ad.

Another feature we could add is more for development/experiment only: ctrl + export to only export the visible ads, so that we can use the slider to export a subset of all the ad data.

**Comment by dhowe** [comment]
Yes, excellent idea. We had originally thought of some of these as items you could filter on; like 'show me all the ads from this network', but never got around to it. 

Ad network seems to be the most useful metric, but other possibilities:
-- highest/lowest ads-per-site ratio
-- highest/lowest pixel count per site
-- $$ per site and/or ad network
-- image ad vs text-ad vs

We might also do better calculation of costs, given that we know more now...

**Comment by cqx931** [comment]
What do you mean by highest/lowest pixel count per site? Those transparent tracking pixels?
Would it be more meaningful to show the highest/lowest ads-per-page ratio? This would be different from the top sites info, but it would also be very interesting to know.

- Top Sites:
Top Ad networks
Each item should contain:
Name of Site/Network | number of ads clicked | $$

- Ad Type:
Image ad: [Number]
Text ad: [Number]

**Comment by dhowe** [comment]
> What do you mean by highest/lowest pixel count per site?
I was thinking about the amount of space on the page taken up by ads, but maybe just raw number of ads is ok. I'm not sure lowest # of ads is interesting, but highest for sure...

**Comment by cqx931** [comment]
Visual Mockups

Default: showing statistics
![image](https://user-images.githubusercontent.com/3056154/77320464-fb24eb00-6ce6-11ea-9cea-cd3749fe3c48.png)
Statistic panel can also be hidden
![image](https://user-images.githubusercontent.com/3056154/77320481-04ae5300-6ce7-11ea-92e7-1bb511bd6ca6.png)

**Comment by cqx931** [comment]
Implemented "My Statistics" panel:
https://github.com/dhowe/AdNauseam/commit/2cb8283296e0414c611afa36a1385fe162eb0f66

PENDING:

- [ ] Add text in "my statistics" panel to Crowdin
- [ ] Ctrl-export
- [ ] better calculation of costs

**Comment by cqx931** [comment]
As a side note, the CPC is getting lower right now, based on the src we are using. 

<img width="867" alt="Screenshot 2020-04-01 at 3 55 49 PM" src="https://user-images.githubusercontent.com/3056154/78180781-45b60e00-7431-11ea-852f-7cc1ad283162.png">

**Comment by dhowe** [comment]
Good -- when it get to zero, we'll be done :)
