### ISSUE TITLE
Document blocked page unclickable buttons

### ISSUE THREAD

**Issue by keldian** [dhowe/AdNauseam#1647]
### Describe the issue

On the _AdNauseam has prevented the following page from loading_ page, the buttons _CLOSE THIS WINDOW_ and _TEMPORARILY_ do nothing when clicked. _PERMANENTLY_ works as intended though.

Appears to be a bug from a recent update.

### Screenshot in which the issue can be seen

https://i.ibb.co/MfTKpxg/adna.png

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

Click on [this link](https://www.dealabs.com/visit/thread/1859925)—or any other link that leads to a block page with your filters—and click the buttons.

### Your settings

- OS/version: Windows 10 1809, Debian 10
- Browser/version: Firefox 74.0, Chrome 79.0.3945.88
- AdNauseam version: 3.9.104
- Other extensions you have installed: none

##### Your filter lists
Default filter lists + FRA

### Your location/country
France

**Comment by cqx931** [comment]
Hi @keldian , thank you for reporting this issue. I can verify that the button 'TEMPORARILY' does not work on my end. I will look into this issue.

However, I think the button 'CLOSE THIS WINDOW' should be  'GO BACK' in the latest version and when I test it it did work as expected. I'm not sure why you are still seeing 'CLOSE THIS WINDOW' on your side. Could you please try installing a new AdNauseam and see whether that button still doesn't work for you?

**Comment by keldian** [comment]
Done on a fresh Firefox install and then on a fresh Chrome install. It's still _CLOSE THIS WINDOW_ and still not responding to click.

**Comment by cqx931** [comment]
Hi @keldian, I have fixed this issue with the latest commit. The fix will be included in our next release.

**Comment by keldian** [comment]
Thanks
