### ISSUE TITLE
DailyKos Petitions blank with Adn in Firefox

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1649]
For example: https://www.dailykos.com/campaigns/petitions/add-your-name-demand-a-coronavirus-response-that-protects-working-families

With ADN enabled
![image](https://user-images.githubusercontent.com/737638/77815814-cf47a200-70f8-11ea-8b01-c88d38d3fd3e.png)

With ADN disabled
![image](https://user-images.githubusercontent.com/737638/77815972-079bb000-70fa-11ea-8066-d20b92dedb9f.png)

**Comment by cqx931** [comment]
Can't reproduce this on my computer, do you still see this issue? Can you take a look at the logger, and check what's being hidden there?

<img width="1405" alt="Screenshot 2020-04-01 at 10 08 53 AM" src="https://user-images.githubusercontent.com/3056154/78146923-cdcfef80-7400-11ea-9e19-7545486af85e.png">

**Comment by dhowe** [comment]
yes, I still see it:

```
<details><summary>Logger output</summary>

```
+23
##.adsbygoogle, ins[id*="aswift"] > iframe, iframe[id^="google_ads_frame"], #google_image_div, #mys-content:style(height:0px!important;)
www.dailykos.com
dom
https://www.dailykos.com/campaigns/petitions/add-your-name-demand-a-coronavirus-response-that-protects-working-families
```
```
+23
##.embed-rendered
www.dailykos.com
dom
https://www.dailykos.com/campaigns/petitions/add-your-name-demand-a-coronavirus-response-that-protects-working-families
```
```
+9
www.dailykos.com
1
font
https://assets.dailykos.com/assets/fonts/fondkons-3d84b14742840a4c203a1a709cfba477.woff
```
```
+8
www.dailykos.com
3
font
https://fonts.gstatic.com/s/opensans/v17/mem5YaGs126MiZpBA-UN7rgOUuhpKKSTjw.woff2
```
```
+6
www.dailykos.com
3
image
https://actionnetwork.org/images/logo_sm.png
```
```
+6
www.dailykos.com
3
image
https://actionnetwork.org/images/spinner8.png
```
```
+6
www.dailykos.com
3
image
https://can2-prod.s3.amazonaws.com/groups/photos/000/016/882/thumb/DailyKosLogo.png
```
```
+6
www.dailykos.com
3
image
https://can2-prod.s3.amazonaws.com/petitions/photos/000/160/928/original/GettyImages-846995510.jpg
```
```
+6
www.dailykos.com
3
script
https://actionnetwork.org/includes/js/can-embed.js?v=9
```
```
+5
##.adsbygoogle, ins[id*="aswift"] > iframe, iframe[id^="google_ads_frame"], #google_image_div, #mys-content:style(height:0px!important;)
www.dailykos.com
dom
https://www.dailykos.com/campaigns/petitions/add-your-name-demand-a-coronavirus-response-that-protects-working-families
```
```
+4
www.dailykos.com
3
xhr
https://www.facebook.com/x/oauth/status?client_id=170357783709&input_token&origin=1&redirect_uri=https%3A%2F%2Fwww.dailykos.com%2Fcampaigns%2Fpetitions%2Fadd-your-name-demand-a-coronavirus-response-that-protects-working-families&sdk=joey&wants_cookie_data=false
```
```
+2
www.dailykos.com
3
object
https://actionnetwork.org/includes/js/can-embed.js?v=9
```
```
+2
www.dailykos.com
3
script
https://actionnetwork.org/includes/js/jquery.min.js
```
```
+2
www.dailykos.com
3
script
https://connect.facebook.net/en_US/all.js?hash=01b1c70b13545551c220e0b1bdf525db
```
```
+2
||chartbeat.com^$third-party
--
www.dailykos.com
3
script
https://static.chartbeat.com/js/chartbeat.js
```
```
+2
www.dailykos.com
3
script
https://connect.facebook.net/en_US/all.js#xfbml=1&appId=170357783709
```
```
+2
www.dailykos.com
3
font
https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFVZ0bf8pkAg.woff2
```
```
+2
www.dailykos.com
3
font
https://fonts.gstatic.com/s/opensanscondensed/v14/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff0GmDuXMR7eS2Ao.woff2
```
```
+2
||browser-update.org^$third-party
--
www.dailykos.com
3
script
https://browser-update.org/update.min.js
```
```
+2
www.dailykos.com
1
image
https://assets.dailykos.com/assets/favicon-a1a889f68cd3ef7fe9afa4b868cb8db9.ico
```
```
+2
/quant.js
--
www.dailykos.com
3
script
https://secure.quantserve.com/quant.js
```
```
+2
||browser-update.org^$third-party
--
www.dailykos.com
3
script
https://browser-update.org/update.min.js
```
```
+2
www.dailykos.com
3
object
https://actionnetwork.org/includes/js/jquery.min.js
```
```
+1
www.dailykos.com
3
script
https://actionnetwork.org/includes/js/yepnope154-min.js
```
```
+1
www.dailykos.com
1
image
https://assets.dailykos.com/assets/dk-logo-med-22207865c333d91431c92c660319bfe8.png
```
```
+1
google-analytics.com/ga.js
<<
www.dailykos.com
script
https://ssl.google-analytics.com/ga.js
```
```
+1
||google-analytics.com/ga.js$script
--
www.dailykos.com
3
script
https://ssl.google-analytics.com/ga.js
```
```
+1
www.dailykos.com
1
script
https://assets.dailykos.com/assets/dk5-campaigns-footer-b1e70279298671ee327a32db8a1058c1.js
```
```
+1
||browser-update.org^$third-party
--
www.dailykos.com
3
script
https://browser-update.org/update.min.js
```
```
+1
www.dailykos.com
3
script
https://actionnetwork.org/widgets/v3/petition/add-your-name-demand-a-coronavirus-response-that-protects-working-families?format=js&referrer=&source=&style=full&css=whitelabel
```
```
+1
www.dailykos.com
1
script
https://assets.dailykos.com/assets/dk5-campaigns-a0cc2d3067d942f2e332fb6dd58cec04.js
```
```
+1
www.dailykos.com
1
css
https://assets.dailykos.com/assets/dk5-campaigns-f899d4eaa83ce14bbb46071d62bb6093.css
```
```
+1
www.dailykos.com
3
script
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js
```
```
+1
www.dailykos.com
3
script
https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js
```
```
+1
www.dailykos.com
3
css
https://fonts.googleapis.com/css?family=Open+Sans+Condensed:700
```
```
+1
www.dailykos.com
3
css
https://fonts.googleapis.com/css?family=Open+Sans:400,700
```
```
+0
www.dailykos.com
1
doc
https://www.dailykos.com/campaigns/petitions/add-your-name-demand-a-coronavirus-response-that-protects-working-families
```
```
+0
https://www.dailykos.com/campaigns/petitions/add-your-name-demand-a-coronavirus-response-that-protects-working-families
```
</details>

```

**Comment by cqx931** [comment]
`##.embed-rendered` might be the one that caused this issue, as I don't see that filter on my end.
Can you take a look at where that rule comes from?

**Comment by dhowe** [comment]
![image](https://user-images.githubusercontent.com/737638/78167520-3363c080-7481-11ea-82ed-e891e886faaf.png)

**Comment by cqx931** [comment]
That's not a default filter list that Adnauseam uses, should we fix those issues in Adnauseam filters that are caused by other lists?

**Comment by dhowe** [comment]
I guess the first question would be whether it causes a problem on ublock. If so, then its a list problem. If not, then we should probably fix...

**Comment by cqx931** [comment]
Yes, this is a list problem. See unlock screenshot after enabling 'Fanboy Annoyance'
<img width="1033" alt="Screenshot 2020-04-01 at 1 37 44 PM" src="https://user-images.githubusercontent.com/3056154/78168486-05996000-741e-11ea-99cd-02f237d4af11.png">

**Comment by dhowe** [comment]
> See unlock screenshot after enabling 'Fanboy Annoyance'

?

**Comment by dhowe** [comment]
Ok, cool.
