### ISSUE TITLE
Need a better way to access uBlock menu, logger, etc.

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#165]
Currently these are (temporarily) available only from the ? button on the menu.
But this is just for dev use...

Because the uBlock menu refers to the current page, it should be launched from the menu, rather than the settings page (or, alternatively, it will require more work to implement, and be less clear to the user what it is referring to)

If we offer an option to go straight to the logger, then the above doesn't apply (we already have this on the addons page, after clicking 'more', in current Firefox), as the logger applies to all pages. 

As a quick/dirty solution, we might just add a 'logger' button at the bottom of the settings page, beside export/import/clear

**Comment by dhowe** [comment]
Raising priority as this our current releases still have the '?' showing the uBlock menu, and no way to get to the FAQ (the original target for the '?' I believe)

**Comment by dhowe** [comment]
Replaced ? with µ for now...

**Comment by dhowe** [comment]
@mushon -- are we ok with the current ublock button (this used to be a link to the FAQ)
If not we need a design...

**Comment by mushon** [comment]
I think we're ok with this for version 2.4
Most of the features there are more advanced and the ones that are not are also available from the right-click menu. I'm voting for moving the redesign of these features to [Possible Futures](https://github.com/dhowe/AdNauseam/milestone/3).
