### ISSUE TITLE
Blocking pictures/ads with wildcards doesn't work (At least on HorribleSubs)

### ISSUE THREAD

**Issue by Dyras** [dhowe/AdNauseam#1651]
### Describe the issue
Greetings! The website HorribleSubs has (ads) pictures of girls on it, and I want to block these. It doesn't work regardless of how many times I try. This is what my blocklist looks like atm
```

||horriblesubs.info/images/b/*.jpg$image
||horriblesubs.info/images/b/*.jpg$image
||horriblesubs.info/images/b/*.jpg$image
||horriblesubs.info/images/b/*jpg$image
||horriblesubs.info/images/b/*jpg$image
```

### Screenshot in which the issue can be seen
![grafik](https://user-images.githubusercontent.com/12563436/77907921-d69eb500-728a-11ea-9696-55298d5b667a.png)
(I'm using a dark theme Stylus script, but it's the same without it)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1. Visit [HorribleSubs](https://horriblesubs.info/)
2. Right-click one of the two anime girl pictures at the top of the screen.
3. Remove the name of the picture and add a * instead.
4. Notice how both pictures turn red.
5. Block it
6. Notice how both anime girls are gone!
7. Press F5
8. They back!

### Your settings

- OS/version: Windows 10 Pro N
- Browser/version: Latest stable Firefox
- AdNauseam version: Latest stable version
- Other extensions you have installed: A lot, but I doubt it matters

##### Your filter lists
Default filter lists

### Your location/country
Sweden, but it shouldn't matter.

**Comment by cqx931** [comment]
I tried this blocking rule as you mentioned: `||horriblesubs.info/images/b/*.jpg$image`, and it seems to work fine on my Firefox.

<img width="1202" alt="Screenshot 2020-04-01 at 10 47 52 AM" src="https://user-images.githubusercontent.com/3056154/78151135-3f5e6c80-7406-11ea-8139-d90472404e67.png">

![image](https://user-images.githubusercontent.com/3056154/78151281-716fce80-7406-11ea-9fb6-a729f9d7f8c2.png)

I'm not sure why the same rule does not work in your adnauseam. Can you try a cosmetic rule in your "My Filters" instead?
`horriblesubs.info##img[src*="images/b/"]`

**Comment by Dyras** [comment]
Hmmm it works for you? For me, they reappear if I F5 a couple of times. It seems they are gone sometimes, and sometimes they aren't:
![grafik](https://user-images.githubusercontent.com/12563436/78166768-95a2ce00-744d-11ea-92f8-b9fa771eea42.png)
![grafik](https://user-images.githubusercontent.com/12563436/78166771-9b001880-744d-11ea-8f59-45466846af65.png)
![grafik](https://user-images.githubusercontent.com/12563436/78166784-a2272680-744d-11ea-8867-909aac8e4c38.png)

The ads are the bottom also seem to be difficult to get rid of. I added this to my filter
`||www.play-asia.com/32/*$image`
And yet it looks like this:
![grafik](https://user-images.githubusercontent.com/12563436/78166888-cedb3e00-744d-11ea-80a4-35cbe41d2885.png)


Your cosmetic rule seems to have fixed the issue with the banners on the top of the page though :)

**Comment by Dyras** [comment]
So I decided to download a portable Firefox, and AdNauseam blocks ads perfectly on that. 
I figured there's something with my Firefox install, so I deactivated all other addons. No change.
I figured there was a setting in AdNauseam that I've been missing, so I reinstalled it. No change.
Currently looking at Firefox settings, will write again if I figure out what setting is causing this.

**Comment by Dyras** [comment]
I couldn't figure out what setting was causing it, but I ran the Firefox installer again and now it works. So I guess it was a broken file or something.

Technology sucks. Thanks for a great addon regardless!

**Comment by Dyras** [comment]
@cqx931 
I just noticed that the ad at the bottom keeps coming back even in my fresh portable Firefox. Any chance you could add it as a default blocked ad (Along with the previously mentioned ads)?
Playasia:
![grafik](https://user-images.githubusercontent.com/12563436/78170240-ed900380-7452-11ea-9c19-bb4caeecc32c.png)

I've tried these two filters, and they don't work
`||www.play-asia.com/32/74u$image`
`||www.play-asia.com/*$image`

However, this seems to work
`horriblesubs.info##[href="https://bit.ly/1NcUUa2"] > .center-block.img-responsive`

Cheers!

**Comment by cqx931** [comment]
I added two cosmetic filters to the Adnauseam filter. Please update your adnauseam filter(it might take 5 minutes for GitHub to update the filter list though) and let me know whether that works for you!
```
horriblesubs.info##img[src*="play-asia"]
horriblesubs.info##img[src*="images/b/"]
```
