### ISSUE TITLE
Does adnauseam still hide ads after you toggle that off?

### ISSUE THREAD

**Issue by SimonGhoul** [dhowe/AdNauseam#1652]
### Describe the issue
I don't see ads when I go to https://ezgif.com/video-subtitles
I still would like to see ads to support websites fairly when I see something interesting and I genuinely want to click on it

ads do show on krunker.io I just don't want any ads to be hidden.

The official issue tracker for uBlock Origin is at:
https://github.com/uBlockOrigin/uBlock-issues/issues

### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/41213690/78886436-308e4000-7a2c-11ea-86eb-b2e8fe276bb9.png)

### Steps for anyone to reproduce the issue
Go to the website and disable the extension, you can see the ads. I also have all the filter lists toggled on.

I feel like I am doing something wrong here, if I disable adblocking filter lists will the ads still be clicked? I wished I could had sent a support request or something rather than an issue because I believe I am the one doing something wrong.

### Your settings

- OS/version: Windows 10
- Browser/version: Version 80.0.3987.163 (Official Build) (64-bit) about to get updated, but last update was a few days ago
- AdNauseam version: 3.9.104
- Other extensions you have installed: a lot of extensions, privacybadger is disabled for that website, https everywhere, trackmenot, Vanilla cookie, and other extensions unrelated to this.

##### Your filter lists
every filter list on it plus I dont care about cookies. Should I disable ad filters? (And should I also add the custom filters I made on ublock origin?)

**Comment by cqx931** [comment]
Hi @SimonGhoul, if I understood you correctly, you can add any sites you want to support to your white list. AdNauseam will be automatically disabled on the site if it is on the white list and you can still use AdNauseam for other websites. Hope that helps!

<img width="733" alt="Screenshot 2020-04-09 at 11 20 37 AM" src="https://user-images.githubusercontent.com/3056154/78911309-24b67400-7a54-11ea-9b54-a6050ca665ff.png">

**Comment by SimonGhoul** [comment]
@cqx931 I don't want to whitelist websites because this would allow trackers to track me and ad nauseam won't click on the ads of the websites then.

What I want is for ad nauseam to still display all ads but still do it's thing of clicking on them. But I still want it to block trackers and malware and other things.

**Comment by SimonGhoul** [comment]
In ublock origin I tended to figure out how to only allow ads to be shown and I made filters of it, simply because I still want to play fair and support websites. But because I noticed how facebook and some ads are able to track me with no respect or regard for my privacy I want to trick those that mess with me like in this way with ad nauseam

**Comment by cqx931** [comment]
> What I want is for ad nauseam to still display all ads but still do it's thing of clicking on them. But I still want it to block trackers and malware and other things.

I see. This should be exactly what AdNauseam does when you disable 'Hiding'. However, there is a difference between disabling the cosmetic filters(which is what AdNauseam does when you disable 'Hiding' ) and having certain ads not rendered at all. Some ads appeared to be 'hidden' because certain web requests are blocked. 

AdNauseam does allow most of the requests in your exception filters. One major difference between AdNauseam and uBlock is that we allow most of the blocking rules in 'EasyList' as most of them are directly related to ad serving. We do still disable requests based on lists that purely dedicated to Privacy and Malwares.

When I test AdNauseam on the site you are mentioning above, it does manage to show ads and still clicking on them. Not sure why it's not working on your computer... Have you tried to disable 'ad blocking'? AdNauseam should still click on ads if you disable blocking

**Comment by SimonGhoul** [comment]
So hiding the ads is basically the same thing as cosmetic filters... bruh

It's also working now, maybe I only had to restart my computer or my browser to have that working. How do I disable ad blocking though? Will disabling adblocking still protect against trackers and stuff?

**Comment by cqx931** [comment]
'Blocking' in AdNauseam mainly means blocking malware and trackers that won't stop ads to be rendered. There might be edge cases that we miss if you found one please let us know. Therefore disabling 'Blocking' in AdNauseam won't protect your browser from trackers and malware anymore.

**Comment by dhowe** [comment]
should consider changing back to two options: clicking, hiding

**Comment by SimonGhoul** [comment]
got it, danke
