### ISSUE TITLE
Sometimes AdNauseam can't collect ad images at Facebook right column

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1655]
AdNauseam can't always pick up ad images at this Facebook ad slot, although the ads do seem to share the same dom structure and attributes. 

It doesn't seem to be related to different types of ads as even the same ad,  sometimes can be picked up but sometimes not. 

Still need to figure out when and why it happens.

**Comment by mneunomne** [comment]
Seems that ad collection on facebook is a lost cause at the moment. Think we can close this.
