### ISSUE TITLE
Blank page on https://botometer.iuni.iu.edu

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1659]
Page shows normally with Adn disabled

**Comment by cqx931** [comment]
I can see the page on my end. Can you take a screenshot of what you see? Also the filters in the logger?
![Screenshot 2020-05-18 at 8 42 17 AM](https://user-images.githubusercontent.com/3056154/82214215-7d92eb00-98e3-11ea-8f52-4d04e67200c8.png)

**Comment by mneunomne** [comment]
@dhowe , its for the same reason as this https://github.com/dhowe/AdNauseam/issues/1784, it's caused by "Fanboy’s Annoyance" filter list. Tested on uBlock.

**Comment by dhowe** [comment]
if we get a bunch of these, we can report them to the list maintainer
