### ISSUE TITLE
Blocking starts only after 3rd party filter update

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#166]
This was detected on us.yahoo.com
with firefox 46.0.1 and ADN 2.1.13
Can we force 3rd party update?

**Comment by dhowe** [comment]
Can you be more specific?

**Comment by mushon** [comment]
I run ADN on FF
went to us.yahoo.com
nothing was blocked
I wend into settings and updated the 3rd party filters
only then were things blocked

**Comment by dhowe** [comment]
Can you test with a new profile, and a fresh install from the github page?

**Comment by CyrusSUEN** [comment]
I can verify the problem with new profiles. And @dhowe solved it in e98dfe1319c9b7133540041c2bffe84c7667c4db in https://github.com/dhowe/uAssets

in local uAssets repo
$ git remote set-url origin https://github.com/dhowe/uAssets.git; git pull

**Comment by mushon** [comment]
Verified this is no longer the case (checked with AdNauseam v2.1.1.1). Closing.
