### ISSUE TITLE
Does not block advertisements on the site. http://fanserials.asia/

### ISSUE THREAD

**Issue by Vovadid** [dhowe/AdNauseam#1664]
Does not block advertisements on the site. In the sections of the video and in general. When playing video, also in the beginning. + new announcements appear after page reload.
Why? Please try and fix.  http://fanserials.asia/
Windows 10 1909
Chrome Version 83.0.4103.61 (Official Build) (64-bit)
AdNauseam v3.9.104 uBlock Origin v1.20.0
Default Filter lists
Location: Russian
![Снимок](https://user-images.githubusercontent.com/39053957/82686144-043a2600-9c5e-11ea-94e1-120f6184fc58.PNG)
![Снимок2](https://user-images.githubusercontent.com/39053957/82686255-38154b80-9c5e-11ea-9d69-0e156b24c2d0.PNG)

**Comment by Snaxeko** [comment]
I can't reproduce but every time I show these kind of background ads, it's due to tpc.googlesyndication.com... Try to block it through dynamic filters, it should work.

**Comment by dhowe** [comment]
I"m unable to reach the site http://fanserials.asia. Is it currently down? Also nslookup fails for the domain:

$ nslookup  fanserials.asia
** server can't find fanserials.asia: NXDOMAIN
