### ISSUE TITLE
Request to change button titles on first-run page

### ISSUE THREAD

**Issue by 20k-ultra** [dhowe/AdNauseam#1667]
was "Change condescending button title"

After you install AdNauseam the settings configuration button says "That's it? Ok..." if you only have 1 feature toggled. Add another and it says "Better, but still..."

I understand the intent is to encourage people to activate all the features available instead of only using 1/3 of the feature set. However, I only need AdNauseam to click ads because I have other extensions blocking trackers and ads. 

This text just feels very unnecessary since we don't know the user's use case and we're making them feel bad for using it the way they want to.

version: 3.9.104

**Comment by cqx931** [comment]
Thank you @20k-ultra for your feedback. I just want to bring it up that AdNauseam's clicking function won't work for many ads if you use other ad blockers. As they might have blocked something that stops ads from rendering at all. That's why we designed the potential conflict warning message for other ad blockers.

@mushon @dhowe Any comments on the text?

**Comment by mneunomne** [comment]
@dhowe will we want to change this button title?

**Comment by dhowe** [comment]
Do we have text proposed to change to ?

**Comment by 20k-ultra** [comment]
I was working on a PR for this and unsure what to do for the other locales...I was going to go with the following:
  
1.    Some features
2.   Most features
3.   All features!

Don't know if I can just pop the english text into a translator and that will suffice ?

**Comment by dhowe** [comment]
we use [crowdin](https://crowdin.com/project/adnauseam) for translation, so the first step would be to agree on text in english

**Comment by mneunomne** [comment]
> 1. Some features
> 2. Most features
> 3. All features!
> 
@dhowe we'll we implement these changes in the buttons then?

**Comment by dhowe** [comment]
perhaps we can simplify things and remove the text...graphic seems clear enough

**Comment by mneunomne** [comment]
Agreed

**Comment by mneunomne** [comment]
ah yes @dhowe i just realized this as well, thanks for fixing

**Comment by mneunomne** [comment]
Closing now
