### ISSUE TITLE
Video ads showing on https://www.wpri.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1670]
Video ads showing on https://www.wpri.com:

https://www.wpri.com/watch/live-streaming-eyewitness-news/

![image](https://user-images.githubusercontent.com/737638/83490882-60653b80-a4e3-11ea-8838-72edaa1a460c.png)

**Comment by cqx931** [comment]
Please update AdNauseam filter and this should be fixed now.
