### ISSUE TITLE
Ad hiding and collecting issues on duckduckgo

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1674]
requests are allowed, dnt domains are correctly parsed.

- [x] hiding: AdNauseam's hiding preference also can't be passed to ublock

**Comment by cqx931** [comment]
dnt ads not clicking not working for ddg.

**Comment by mneunomne** [comment]
![working-dnt-not-click](https://user-images.githubusercontent.com/4967860/126036330-7e2df751-12c0-4c86-9c4d-89b7d2d055ef.PNG)

This is working now, "skipped, allowed due to DNT".

Closing
