### ISSUE TITLE
After roughly 10,000 blocked ads it stops working 50% of the time

### ISSUE THREAD

**Issue by pythonInRelay** [dhowe/AdNauseam#1678]
### Describe the issue
As the title says. I've been uninstalling and re-installing this add-on now for over 1 year and I believe I have finally encountered this issue enough times to get a good idea of what is causing it. After roughly 10,000 blocked ads, aka there are 10,000 available ads in your vault. The add-on will stop working roughly 50% or less of the time. If I open up 5 webpages, 2 of them will display ads regardless of the fact that maybe mere minutes ago they would be all completely blocked on that site.

Closing Firefox and re-opening does not seem to help. Neither does rebooting or clearing cache and so on. It seems to be a total failure of the add-on, but interestingly only happens 50% or a bit less, of the time.

What does seem to help however is uninstalling and re-installing. It will work 100% of the time if I uninstall and just install it again, literally one hundred percent and not fail a single time for about 1 month until roughly 10,000 ads are blocked again, to which it will cease working roughly 50% of the time again.

### Screenshot in which the issue can be seen

Not necessary. It doesn't block anything. There is no point including a website with all of the ads showing here. Basically it looks as if the add-on is disabled or just not even installed.

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

See above.

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 77.0.1
- AdNauseam version: Latest
- Other extensions you have installed: Bitwarden
- AdNauseam settings: Default, with Web-RTC blocked also, no additional lists selected or custom rules made what-so-ever as these are not necessary when the add-on is functioning properly.

##### Your filter lists
Default pre-checked lists included only

### Your location/country
The problem happens to ALL websites, 50% of the time. No location information sorry, because there is really no need to provide this kind of information in the bug report.

To other people who are having this problem, I recommend checking how many ads you have blocked in the map, if it is over 10,000 then you are having the same issue.

**Comment by cqx931** [comment]
Hi @pythonInRelay, [this issue](https://github.com/dhowe/AdNauseam/issues/1657) seems to be related to your issue. We have addressed issue #1657 in v3.9.106, but it is still waiting to be approved by Mozilla add-on store at the moment. I will let you know once it is out there and we can check whether this issue still happens to the new release for you.

Also, you should be able to export your ad data, clear your vault, then re-import the ad data to test this without un-installing and re-installing the whole add-on.

**Comment by cqx931** [comment]
Please follow issue https://github.com/dhowe/AdNauseam/issues/1657 for more updates.
