### ISSUE TITLE
Google ads visible on snopes

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1679]
https://www.snopes.com/fact-check/derek-chauvin-flyer-accuracy/

![Screenshot 2020-06-15 at 7 30 11 PM](https://user-images.githubusercontent.com/737638/84652751-bc49ae80-af3e-11ea-93b1-90bf78dcbc42.png)

**Comment by cqx931** [comment]
I used to reproduce this once, but now I can't see it anymore.

**Comment by mneunomne** [comment]
Also unable to reproduce it at the moment.

**Comment by dhowe** [comment]
Also cannot.
