### ISSUE TITLE
Add AUR package to wiki

### ISSUE THREAD

**Issue by gardenappl** [dhowe/AdNauseam#1680]
Hello, I've been maintaining an AUR (Arch User Repository) package for AdNauseam for a while, you can see it here: [chromium-extension-adnauseam](https://aur.archlinux.org/packages/chromium-extension-adnauseam/). The idea is to provide a method for updating the Chrome/Chromium package for Arch Linux users, of course that's important considering the Google Web Store ban.

I thought it would be nice to have the package mentioned on the wiki here, to make people aware of this method.

(Note that the package does **not actually install the extension** as that still requires some manual intervention. It just makes it easier to download AdNauseam and keep it updated. Read the pinned comment for instructions)

**Comment by cqx931** [comment]
@gardenappl  Thank you so much for maintaining the AUR package! Are you doing it only for chromium? If it won't take too much time, could you please also do it for Firefox? 

And yes, we are happy to include it in the wiki page!

**Comment by gardenappl** [comment]
@cqx931 is a Firefox package really necessary? The point of the Chromium package was to circumvent the Google ban. It's still available on the Firefox addons store, and that's by far the easiest way to install it.

**Comment by dhowe** [comment]
yes, lets include the instructions on the chrome install page

**Comment by cqx931** [comment]
Added here: https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission.

**Comment by gardenappl** [comment]
Thanks!

I was kinda hoping you would put it closer to the top, alongside the "Other Operating Systems" section. But I guess this works, too.
