### ISSUE TITLE
New feature: Strict Blocking Mode

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1681]
This is inspired by https://github.com/dhowe/AdNauseam/issues/1667, and it could be an extra option under "HIDE ADS".

By default we are allowing blocking rules from Easylist or other lists that are not in [Enabled Block Lists](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L38). Could we add an extra option to allow users to block these adnauseam allowed requests to enjoy a better ad free experience while collecting/clicking less ads? We can add an FAQ entry to explain more about the pros and cons of this option.

@dhowe

**Comment by dhowe** [comment]
lets discuss

**Comment by cqx931** [comment]
This is now renamed to "Strict blocking mode" and here is an FAQ link on this new feature:
https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#what-is-strict-blocking-mode-for-and-when-should-i-use-it

**Comment by cqx931** [comment]
TODO: Support strict blocking mode as a site specific feature.


ublock is achieving the site specific settings by adding site specific dynamic filtering rules.
There is also an interface to do this in the ublock menu, but we dont' have to add that for strict blocking.
The minimum setup we need is defining our own dynamic filtering rule in ublock's system.

**Comment by cqx931** [comment]
@dhowe please check: https://github.com/dhowe/AdNauseam/pull/1702/commits/94273b65030cbbeb920e1ca875bc62104bdacba4

now users can add more detailed strict blocking rules such as
`* doubleclick.net * strictBlock` for site specific strict blocking

next TODO: update FAQ entry

**Comment by dhowe** [comment]
what means do we have for testing this is working correctly?

**Comment by cqx931** [comment]
What I did is adding a new action on top of the original "block/allow/noop"  actions in ublock's dynamic filtering system.
Dynamic rules can be written following ublock's dynamic filtering rule syntax.
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax

My only concern is that the name "strict blocking" might be a bit misleading within the dynamic filtering system.
Because "block" will block requests 100% while "strictBlock" is only going to block a request if it is also blocked by some static block rules from any of the filter lists.  Shall we keep using this name or try to come up with another one?

Tests to be added to Pre release testing:
- [ ] Enable global strict blocking in settings, open the logger and go to sites such as nytimes. All blocking rules(including easyList) should be blocked(in red). 
- [ ] Go to "My rules" and add `* doubleclick.net * strictBlock`; Commit the rule and make sure that nothing turns red in codeMIrror; Go to nytimes and make sure that requests from doubleclick.net are all blocked by easylist.
- [ ] Go to "My rules" and add `nytimes.com * * strictBlock`; Commit the rule and make sure that nothing turns red in codeMIrror; Go to nytimes and make sure that blocking filters from easyList are triggered.
- [ ] Go to "My rules" and add `nytimes.com * image strictBlock`; Commit the rule and make sure that nothing turns red in codeMIrror; Go to nytimes and make sure that blocking filters on images are triggered from easyList, but other types of requests are still allowed.

**Comment by cqx931** [comment]
I have edited the FAQ for strict blocking, please check: https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#what-is-strict-blocking-and-when-should-i-use-it

**Comment by cqx931** [comment]
@dhowe Also, shall we move `allowAnyBlockOnDomains` from core.js to default dynamic rules?

**Comment by cqx931** [comment]
Updated release testing

**Comment by dhowe** [comment]
> @dhowe Also, shall we move [`allowAnyBlockOnDomains`](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L35) from core.js to default dynamic strict blocking rules?
> `youtube.com * * strictBlock`
> `funnyordie.com * * strictBlock`

sounds reasonable

**Comment by cqx931** [comment]
TODO: unit tests for bitmap storage

**Comment by mneunomne** [comment]
Should we disable this feature once we implement: https://github.com/dhowe/AdNauseam/issues/1681 ?

**Comment by fourtytwelve** [comment]
Was the "global" aspect of this feature disabled at some point?

AdNauseum fails to block popunder ads for me unless it's in strict blocking mode, and I really would rather not have to enable it for each individual domain.
