### ISSUE TITLE
YouTube Video Ads

### ISSUE THREAD

**Issue by Verdun192** [dhowe/AdNauseam#1682]
On FireFox YouTube ads are no longer blocked. It mostly appears to be this website, though rarely a similar error can occur on Soundcloud.com where an ad banner will pop up but play nothing.

https://cdn.discordapp.com/attachments/393085769842950146/722256113256628374/unknown.png

Literally just launch youtube on firefox, this seems to be an error across the board on all, ad blockers.

### Your settings

AdNauseam v3.9.104 uBlock Originv1.20.0 

Name 	Firefox
Version 	77.0.1

- AdNauseam version: listed above the browser version

- Other extensions you have installed: temporarily installed Adblock Plus for FireFox but disabled it in the image to capture the error. Adnauseam full plays ads, Adblock Plus removes the ads, but I have to press "skip ad"

- AdNauseam settings: N/A

##### Your filter lists
N/A

### Your location/country
U.S.A

** For adult and potential offensive sites/advertisements, please add a [Content Warning] tag in the title to warn developers that there may be offfensive material in the ticket.

**Comment by cqx931** [comment]
@Verdun192 Thank you for your report! We have addressed this issue in the latest release, which can be found here: https://github.com/dhowe/AdNauseam/releases/tag/v3.9.106

We are still waiting for Firefox's approval for the add-on store. If you would like to block youtube ads before it is available in the store, one way is to installing 3.9.106 first as a temporary add-on.
https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

**Comment by dhowe** [comment]
Some feedback on fix:

![Screenshot 2020-06-19 at 12 00 34 PM](https://user-images.githubusercontent.com/737638/85095701-c01e4f00-b224-11ea-9cd9-56ca8c6fbb65.png)

**Comment by krystian3w** [comment]
https://github.com/NanoAdblocker/NanoFilters/issues/518

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/57483

**Comment by cqx931** [comment]
If anyone can provide more details on the issue above I would appreciate it. I don't see any delay on youtube videos using my account, but based on [this ticket](https://github.com/AdguardTeam/AdguardFilters/issues/57483), Youtube might not testing their new ads on me as I'm not a regular user.

**Comment by krystian3w** [comment]
I sometimes have up to two pre-roll ads for about 120 tries, so I can't help with `json-prune` or `set-constant` improvement either.

**Comment by cqx931** [comment]
@krystian3w do you mean you still sometimes get these ads using latest AdNauseam(3.9.107)? And it's a full video ad, not a black/white screen?

**Comment by krystian3w** [comment]
Yeah, I've had 30-45 seconds of advertising blocks twice.

I only once had a white screen with an skip button - shortly before the ads started to turn on freely after several dozen attempts.

**Comment by WhoAmI1000** [comment]
They don't seem to show for me when I get this new release, however they did before I got it.

**Comment by mneunomne** [comment]
@dhowe I have tested Youtube on Firefox with the current version and I wasn't able to detect any issues with Adn, it has the same apparent behaviour as uBlock.
