### ISSUE TITLE
Setting issue (Always click ads)

### ISSUE THREAD

**Issue by TirOFlanc** [dhowe/AdNauseam#1686]
### Describe the issue
The click frequency setting on the ads always remains set to 'Sometimes'.

### Screenshot in which the issue can be seen
![NeverAlwaysClicAds](https://user-images.githubusercontent.com/56934692/85017308-8f2e1380-b16b-11ea-8274-d630ec8e02e9.PNG)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
Set the setting to Always, reopen settings and see it reset

### Your settings

- OS/version: Win 7 x64 Ult
- Browser/version: Brave 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)
- AdNauseam version: AdNauseam v3.9.107 uBlock Originv1.26.0
- Other extensions you have installed: Ghostery / Disconnect (for extension privacy)
- AdNauseam settings: ... want to always click all of ads ...

**Comment by cqx931** [comment]
Thank you for reporting the issue. 

This is an UI issue of the slider, which is caused by accidentally removed code. The clicking probability in the background is correctly updated.

I have fixed the here:  https://github.com/dhowe/AdNauseam/commit/14e9005787f490f9a4d1c3d517d894e07868f374

**Comment by TirOFlanc** [comment]
Oh nice, sorry, my bad !

**Comment by TirOFlanc** [comment]
It appears to be more than just a display error.
![AdNauseam Frequency](https://user-images.githubusercontent.com/56934692/85407568-a9009980-b563-11ea-8509-c576643d7def.PNG)

**Comment by cqx931** [comment]
Let me take another look

**Comment by cqx931** [comment]
I don't see this happen when I test it on 3.9.107. If I install it from fresh using all default settings, all the ads get clicked for me. You do need to set it on 'all', the ui will jump back to 'sometimes' after refresh but the back end should be updated.

I will release an update on this soon, but only after I am sure that the problem is fully fixed.

**Comment by cqx931** [comment]
You can also help us testing the latest master branch here:
[adnauseam.chromium.zip](https://github.com/dhowe/AdNauseam/files/4822428/adnauseam.chromium.zip)
