### ISSUE TITLE
Backup restoring broken

### ISSUE THREAD

**Issue by DarkD** [dhowe/AdNauseam#1687]
As title says - last version where you can restore backup settings is 3.9.104. In newer 106 and 107 you can click button all you want but file opening dialog doesn't shows up.

**Comment by cqx931** [comment]
Hi @DarkD, thank you for reporting the issue. Yes I can verify the issue, the restore button is apparently broken for the new version.

**Comment by cqx931** [comment]
Restore backup settings is now fixed in the master branch
