### ISSUE TITLE
Content invisible on www.essentiallysports.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1688]
Example: https://www.essentiallysports.com/tennis-news-atp-viktor-troicki-becomes-latest-victim-of-coronavirus-from-novak-djokovics-event/

Content returns when ADN is disabled

![image](https://user-images.githubusercontent.com/737638/85359147-11418200-b548-11ea-91b3-232afb850ae1.png)

**Comment by cqx931** [comment]
I can't reproduce this issue when I tried it on firefox and chrome? Do you have any extra filter lists on?

![image](https://user-images.githubusercontent.com/3056154/85417591-cae72580-b53d-11ea-9b8c-d4865fbe5436.png)

**Comment by dhowe** [comment]
![image](https://user-images.githubusercontent.com/737638/85431275-e1c85f00-b5b3-11ea-8a20-4a5fcf688139.png)

Separate question, but what does it mean that the filter can't be found on any of the lists (below)?

![image](https://user-images.githubusercontent.com/737638/85431429-1f2cec80-b5b4-11ea-8570-da2403fc7f32.png)

**Comment by cqx931** [comment]
a) Which link are you talking about?
b) That's the one we are currently using for google ads, to make sure that the clicks are valid . They are treated separately and they are not part of adnauseam.txt, as we don't do display:none with them. I added it in the logger for easy debugging, maybe it's better to add a customized origin for them, like "AdNauseam" ?

**Comment by dhowe** [comment]
Yes, that seems better (see above for image of ad linking to github)

**Comment by cqx931** [comment]
a) That's just the page url where the filter is applied to, it's not really a link to github page.

**Comment by cqx931** [comment]
I will add the customized filter list info. 

Still no content  with cache cleared?

**Comment by dhowe** [comment]
> a) That's just the page url where the filter is applied to, it's not really a link to github page.

But why would the URL be an ADN issue?

**Comment by dhowe** [comment]
> Still no content with cache cleared?

Nope

![image](https://user-images.githubusercontent.com/737638/85433220-ad09d700-b5b6-11ea-9585-2721cc2e63b4.png)

**Comment by cqx931** [comment]
Cause that's the tab(this issue) you probably have opened in the same window session?

**Comment by dhowe** [comment]
Yes I do, but why would that show up in the logger when I refresh the essentiallysports page ?

**Comment by llacb47** [comment]
> Two separate question, but a) why does list/rule link to an ADN github issue? And b) what does it mean that the filter can't be found on any of the lists (below)?

Reverse lookup fail, probably this bug in uBO that was fixed there. https://github.com/uBlockOrigin/uBlock-issues/issues/805

**Comment by dhowe** [comment]
The critical issue here is that disabling the lists and refreshing the page via the logger does not stop those lists from continuing to fire rules.

**Comment by cqx931** [comment]
@llacb47 Thank you for pointing it out. Though our issue is not caused by that bug.

**Comment by cqx931** [comment]
@dhowe are you on v3.9.104 or 107?

**Comment by dhowe** [comment]
3.9.104 (which also raises the question of why I haven't gotten an update or notification)

**Comment by cqx931** [comment]
Cause it's still not live in the extension store, Firefox is still reviewing it.

**Comment by dhowe** [comment]
ah right -- do you think this would make a difference?

**Comment by cqx931** [comment]
You mean whether we should do add another release tag after figuring out this issue?

**Comment by dhowe** [comment]
No, I mean whether the issues might have already been fixes in 107

**Comment by cqx931** [comment]
I can reproduce it with 3.9.104, but not with 3.9.107

**Comment by dhowe** [comment]
excellent... this can be closed then

**Comment by cqx931** [comment]
Added customized text for AdNauseam filters here: https://github.com/dhowe/AdNauseam/commit/f9c3aacec4c7f4eb05e81d5f1b1b9bcd59aa2435
