### ISSUE TITLE
Add some Adguard lists to enabledBlockLists?

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1689]
There were not AdGuard filters when we created enabledBlockLists:
https://github.com/dhowe/AdNauseam/issues/279

Both the [tracking protection filter](https://kb.adguard.com/en/general/adguard-ad-filters#tracking-protection-filter) and [annoyances filter](https://kb.adguard.com/en/general/adguard-ad-filters#annoyances-filter) from AdGuard seem safe to be added to the list.

@dhowe

**Comment by cqx931** [comment]
Also, we are currently moving lists labeled under 'privacy' and 'ads' to the category 'Other' in AdNauseam. 

However, I think it would be better if we keep the category 'Privacy' so that these lists will be easier to be found and enabled by the users.

**Comment by dhowe** [comment]
Both seem good to me

**Comment by cqx931** [comment]
Added: https://github.com/dhowe/AdNauseam/commit/052f7e63338ecf6e9249e621abad2e47421d2cbc

![Screenshot 2020-06-23 at 1 57 48 PM](https://user-images.githubusercontent.com/3056154/85438401-f6780900-b559-11ea-9c8a-069329baa9f5.png)
