### ISSUE TITLE
Privacy Badger is in conflict with AdNauseam

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1690]
Based on [this ticket](https://github.com/dhowe/AdNauseam/issues/1685)
Privacy Badger is now blocking ad requests and it is preventing ads to be collected in AdNauseam. 
Can't really remember why we don't have a warning message for Privacy Badger but it makes sense to include it in verifyAdBlockers() function and show a warning message to users.

![Screenshot 2020-06-24 at 11 17 36 AM](https://user-images.githubusercontent.com/3056154/85583516-529b6580-b60c-11ea-9098-a638ad165cc8.png)

**Comment by dhowe** [comment]
agreed

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/commit/01164f1464f59bf9c7973f0d967309a5df8ea428 done
