### ISSUE TITLE
Ads visible on YouTube: Pre-roll video ads

### ISSUE THREAD

**Issue by JapanYoshi** [dhowe/AdNauseam#1691]
### Describe the issue
Monetized YouTube videos with pre-roll ads show the ads even if AdNauseam is installed.

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1. Install AdNauseam
2. Go to any monetized YouTube video
3. Attempt to play the video and observe the ads

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 77.0.1 64bit
- AdNauseam version: 3.9.104
- Other extensions you have installed: Stylish, GreaseMonkey (no userscripts are installed for YouTube), Facebook Container, Honey, Avast Online Security, HTTPS Everywhere, Bot Sentinel
- AdNauseam settings:
  - [x]  Hide Ads
    - [x] Don't hide non-tracking Ads
    - [ ] Block media elements larger than .. KB
    - [ ] Block remote fonts
  - [x] Click Ads
    - Always
    - [x] Don't click non-tracking Ads
  - [x] Block malware
  - Extra privacy
    - ]x] Disable pre-fetching
    - [x] Disable hyperlink auditing
    - [ ] Prevent WebRTC from leaking local IP addresses
  - Interface
    - [x]Display the number of Ads on the icon
    - [x] Make use of context menu where appropriate
    - [ ] Disable tooltips
    - [ ]  Color-blind friendly
    - [ ] Activate debugging mode
  - Advanced settings
```
allowGenericProceduralFilters false
            assetFetchTimeout 30
    autoCommentFilterTemplate {{date}} {{origin}}
   autoUpdateAssetFetchPeriod 120
   autoUpdateDelayAfterLaunch 180
             autoUpdatePeriod 7
cacheControlForFirefox1376932 no-cache, no-store, must-revalidate
              cacheStorageAPI unset
      cacheStorageCompression true
              consoleLogLevel unset
              debugScriptlets false
           disableWebAssembly false
        ignoreRedirectFilters false
    ignoreScriptInjectFilters false
 manualUpdateAssetFetchPeriod 500
                popupFontSize unset
  requestJournalProcessPeriod 1000
                  selfieAfter 3
 strictBlockingBypassDuration 120
        suspendTabsUntilReady unset
        userResourcesLocation unset
```

##### Your filter lists

Essentials: AdNauseam filters, EasyList, EasyPrivacy, all 5 uBlock filters
Malware: Malware Domain List, Malware domains
Annoyances: Facebook Annoyances Blocker
Other: none
Languages: JPN: AdGuard Japanese

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

** For adult and potential offensive sites/advertisements, please add a [Content Warning] tag in the title to warn developers that there may be offfensive material in the ticket.

**Comment by cqx931** [comment]
Hi @JapanYoshi, AdNauseam 3.9.109 is now available in Firefox's add-on store, could you please check out the latest version and see whether that will fix the issue for you?

**Comment by JapanYoshi** [comment]
I’ve downloaded AdNauseam v3.9.109, and pre-roll video ads seem to be gone! Thank you.
