### ISSUE TITLE
'Prevent WebRTC from leaking...' Breaks Google Remote Desktop

### ISSUE THREAD

**Issue by ice-fly** [dhowe/AdNauseam#1695]
### Describe the issue
The 'Prevent WebRTC from leaking local IP addresses' option prevents Google Remote Desktop from connecting to local computers.

### Steps for anyone to reproduce the issue
Enable 'Prevent WebRTC from leaking local IP addresses' option,
Attempt to create a session at: https://remotedesktop.google.com/
Will fail with notification in lower left.

### Your settings

Google Chrome | 83.0.4103.116 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Windows 10 OS Version 1909 (Build 18363.900)
JavaScript | V8 8.3.110.13

- **AdNauseam version:**
AdNauseam v3.9.108 uBlock Originv1.26.0

**Comment by ice-fly** [comment]
[Maybe needs added to this list](https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address)

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/726

**Comment by ice-fly** [comment]
oop Dupe... Closing!
