### ISSUE TITLE
Youtube Ads Partially Visible

### ISSUE THREAD

**Issue by WhoAmI1000** [dhowe/AdNauseam#1696]
### Describe the issue
When you go to the home screen on YouTube, sometimes there is an ad as the first video suggestion (the ad title is blocked, but the thumbnail and such is visible.

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/39578224/87095392-87571180-c1f5-11ea-817c-da50ff25de7e.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1. Go to youtube.com
2. Done!

### Your settings

- OS/version: Windows 10, latest update as of 7/9/2020
- Browser/version: Latest version of firefox, private browsing
- AdNauseam version: Latest version
- Other extensions you have installed: Privacy badger, bloody vikings, decentraleyes, cookie autodelete, firefox notes, bitwarden, KA extention, calculator, tab auto clearner, tab auto refresher, ecosia, FireX Proxy, Firefox private network, language tool, honey, give with bing, download virus checker, VTZilla, Pixel Zoomer, sponsor block
- AdNauseam settings: Hide ads, click ads (sometimes), block malware, advanced user

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
California, US
** For adult and potential offensive sites/advertisements, please add a [Content Warning] tag in the title to warn developers that there may be offfensive material in the ticket.

**Comment by cqx931** [comment]
Do you mean the first video under "Recommended"? Asking because I don't see the tabs in your screen shot and I still can't see this kind of ad on my home page after about 40 times refresh.
<img width="596" alt="Screenshot 2020-07-10 at 7 43 51 AM" src="https://user-images.githubusercontent.com/3056154/87151020-1c531c80-c281-11ea-9d93-3d1ee78984a0.png">

**Comment by WhoAmI1000** [comment]
![image](https://user-images.githubusercontent.com/39578224/87177222-26c8e280-c290-11ea-90e4-52a9902b3524.png)
Here is another screenshot. When I hover over it, the ad will say 'Visit Site'.
