### ISSUE TITLE
Logger items with black background and blue text are unreadable

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1704]
![image](https://user-images.githubusercontent.com/737638/89089247-f8da4800-d3ce-11ea-8b98-682b4b07ac81.png)

**Comment by cqx931** [comment]
I don't see these blue entries in chrome, only in firefox. And they are all entries with attribute data-aliasid 
<img width="285" alt="image" src="https://user-images.githubusercontent.com/3056154/89107241-99476100-d3fd-11ea-96c5-92587605f5bb.png">

**Comment by llacb47** [comment]
It's a CNAME entry. https://github.com/gorhill/uBlock/releases/tag/1.25.0

**Comment by dhowe** [comment]
thanks  @llacb47 - @cqx931 we need to change the color so that they are readable on our black bg, and also update the  logger faq with this info.

**Comment by cqx931** [comment]
Can switch to light blue instead.
<img width="467" alt="Screenshot 2020-08-01 at 1 59 23 PM" src="https://user-images.githubusercontent.com/3056154/89107463-38208d00-d3ff-11ea-8d1b-31be4d868b88.png">

**Comment by cqx931** [comment]
New color code image
![colorcode](https://user-images.githubusercontent.com/3056154/89107817-acf4c680-d401-11ea-8845-3287e543bf68.png)
