### ISSUE TITLE
Block-element context-menu disappears

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1705]
![image](https://user-images.githubusercontent.com/737638/89089356-77cf8080-d3cf-11ea-8e8a-aa85fc9a87f4.png)

**Comment by cqx931** [comment]
this was fixed in https://github.com/dhowe/AdNauseam/commit/06dcfcabe3991c495fceae042ce9e8d79f9edc15 for master branch, but it's not live in the release.
