### ISSUE TITLE
[Android] Menu UI issues

### ISSUE THREAD

**Issue by RicoHeat** [dhowe/AdNauseam#1708]
![Screenshot_20200816-183903_Firefox](https://user-images.githubusercontent.com/41478458/90332529-274e4a80-dfad-11ea-878e-02e6c28f7648.jpg)
### Describe the issue
Ui in content blocking settings is displaying violet over black making the buttons nearly visible.

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version:android 9
- Browser/version:firefox 89
- AdNauseam version:39109
- Other extensions you have installed:https everywhere 
- AdNauseam settings:

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

** For adult and potential offensive sites/advertisements, please add a [Content Warning] tag in the title to warn developers that there may be offfensive material in the ticket.

**Comment by cqx931** [comment]
verified

**Comment by cqx931** [comment]
This issue should be fixed now in the latest master branch, see screenshot attached from an emulator:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/3056154/90657978-04bc6b80-e211-11ea-9c43-6ac0af7d620d.png">

This update will be included in the next release which we are working on right now.
