### ISSUE TITLE
[Android]Mobile UI of the setting page need to be adjusted

### ISSUE THREAD

**Issue by Real-John-Cheung** [dhowe/AdNauseam#1712]
### Describe the issue
Mobile UI of the setting page is not working well
..../popup_fenix.html and ..../dashboard#options.html 

### Screenshot in which the issue can be seen
![81597841819_ pic](https://user-images.githubusercontent.com/61215358/90647036-75dc3d00-e26a-11ea-92f8-02d4cdd2299f.jpg)
![photo_2020-08-19_22-32-00](https://user-images.githubusercontent.com/61215358/90648209-d455eb00-e26b-11ea-95a9-dc2dd749646c.jpg)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
Open setting page in Firefox for Android

### Your settings

- OS/version:Android 8.0.0
- Browser/version:Firefox 68.11.0
- AdNauseam version:3.9.109
- Other extensions you have installed:none
- AdNauseam settings:default

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

** For adult and potential offensive sites/advertisements, please add a [Content Warning] tag in the title to warn developers that there may be offfensive material in the ticket.

**Comment by cqx931** [comment]
Issues on the master branch:
<img width="341" alt="Screenshot 2020-08-20 at 5 42 31 PM" src="https://user-images.githubusercontent.com/3056154/90829197-50ecd600-e30d-11ea-93ce-0c1473652f32.png">
<img width="319" alt="Screenshot 2020-08-20 at 5 42 42 PM" src="https://user-images.githubusercontent.com/3056154/90829202-52b69980-e30d-11ea-8c24-b2da68c75f2f.png">

**Comment by cqx931** [comment]
In ublock:
<img width="184" alt="Screenshot 2020-08-20 at 5 49 42 PM" src="https://user-images.githubusercontent.com/3056154/90829333-88f41900-e30d-11ea-99fe-1564955d9dcf.png">

**Comment by cqx931** [comment]
filter lists:
<img width="316" alt="Screenshot 2020-08-20 at 7 11 05 PM" src="https://user-images.githubusercontent.com/3056154/90834718-ed68a580-e318-11ea-9797-545aaceb3780.png">

**Comment by cqx931** [comment]
https://github.com/cqx931/AdNauseam/commit/eb3c7254d52a2e9671595de277086e38afaef5e0
<img width="333" alt="Screenshot 2020-08-20 at 8 15 54 PM" src="https://user-images.githubusercontent.com/3056154/90838123-fdd14e00-e321-11ea-9041-b6ceffeaadd9.png">
