### ISSUE TITLE
[Release 3.9.2 Chrome] UI problems 

### ISSUE THREAD

**Issue by Real-John-Cheung** [dhowe/AdNauseam#1720]
refer to issue https://github.com/dhowe/AdNauseam/issues/1710#issuecomment-678587807
1. When DNT is disable and a non-tracking ad page is opened, there is a 'undefined' shows up in the UI 

<img width="397" alt="螢幕截圖 2020-08-22 上午11 48 03" src="https://user-images.githubusercontent.com/61215358/90948079-958f8300-e46d-11ea-8c7d-4ea9fa4a8310.png">
2. the little green question mark seems to be weird..
<img width="397" alt="螢幕截圖 2020-08-22 下午12 04 08" src="https://user-images.githubusercontent.com/61215358/90948279-9b866380-e46f-11ea-85c8-d34e1f6a458c.png">
3. in the vault, when the no. of clicked ads and collected ads change, those text displayed do not change accordingly unless the user refresh the page manually 
<img width="603" alt="螢幕截圖 2020-08-24 上午10 56 50" src="https://user-images.githubusercontent.com/61215358/90999301-d962c380-e5f8-11ea-811d-62e09659d384.png">
4. Seems that there is no notification for the changes of DNT setting

**Comment by cqx931** [comment]
@Real-John-Cheung I don't think we have notifications for the changes of DNT settings...which test case are you referring to?

**Comment by cqx931** [comment]
3. Fixed https://github.com/dhowe/AdNauseam/commit/377299de809b9de6e9fe0f4e1720bc7fbaa9beb4

**Comment by cqx931** [comment]
2. Fixed https://github.com/dhowe/AdNauseam/commit/26eb4156712bbbb976f0f382854711ee31d662be
<img width="398" alt="截屏2020-08-25 下午4 20 35" src="https://user-images.githubusercontent.com/3056154/91223685-02fe1680-e6ef-11ea-8079-bbf593206a58.png">

**Comment by cqx931** [comment]
1. https://github.com/dhowe/AdNauseam/commit/1e83c1d200bfd876c653dc00de2ee783ae11b994
<img width="399" alt="image" src="https://user-images.githubusercontent.com/3056154/91224297-e57d7c80-e6ef-11ea-8e33-2fcba958f14f.png">
so I removed the extra left/right padding for this section to leave more space for languages such as Chinese. But there might still be a second line for other languages or in very rare cases, when the no. displayed is very high. But I think that should be fine for now.

**Comment by cqx931** [comment]
@Real-John-Cheung Please verify the fixes for 1/2/3. Thanks!

**Comment by Real-John-Cheung** [comment]
##Problem 1
You are right, when the cost is more than 10$, there's still a second line. Unfortunately, 10$ is not very high... maybe need a little bit more space for one more digit. English version is good 
<img width="398" alt="螢幕截圖 2020-08-26 下午1 10 10" src="https://user-images.githubusercontent.com/61215358/91258081-14522c00-e79e-11ea-832a-3073f7b47689.png">
<img width="398" alt="螢幕截圖 2020-08-26 下午1 11 39" src="https://user-images.githubusercontent.com/61215358/91258083-14eac280-e79e-11ea-82d6-8bdab669b790.png">
Maybe we should classify this as Language Versions Problem...

##Problem 2
Fixed

##Problem 3
Fixed

**Comment by Real-John-Cheung** [comment]
> @Real-John-Cheung I don't think we have notifications for the changes of DNT settings...which test case are you referring to? DNT related notifications should only show up for DNT sites.

@cqx931  about notifications, they appear in the Interface part under DNT in the checklist

  >  Interface

  >DNT list at top of whitelist.html is checked when either DNT option is checked, otherwise unchecked
  >Check that changing the two DNT settings will trigger DNT notifications with corresponding messages to the menu
 > Check the layout of each DNT notification("?" should be in the middle, 'settings' button appears on hover)

**Comment by cqx931** [comment]
I see, yes the instructions sounds a bit misleading. I will change the instructions.
We have 4 kinds of DNT notifications that correspond to 4 different scenarios of DNT settings
1. Don't hide + don't click
2. Don't hide + click
3. Hide + don't click
4. hide + click

They are notifications that only shows up in menu on dnt sites.

**Comment by cqx931** [comment]
@Real-John-Cheung 
Please check the latest master branch again.
Now the css should adjust automatically if the stats get too wide. And we should be able to handle two digits on all three stats for Chinese. That should be enough for menu

<img width="412" alt="Bildschirmfoto 2020-08-26 um 11 17 03 AM" src="https://user-images.githubusercontent.com/3056154/91322600-ed8bf980-e78d-11ea-91de-e4ae402a67f7.png">

**Comment by Real-John-Cheung** [comment]
Problem 1 Fixed
