### ISSUE TITLE
[Release 3.9.2 Chrome] Language versions problems - Chinese

### ISSUE THREAD

**Issue by Real-John-Cheung** [dhowe/AdNauseam#1721]
refer to issue https://github.com/dhowe/AdNauseam/issues/1710#issuecomment-678587807 
1. When the language set to Chinese, some words are not translated, as you can see below the first line writes "已訪問“ and the rest writes "visited"
<img width="397" alt="螢幕截圖 2020-08-22 下午12 04 08" src="https://user-images.githubusercontent.com/61215358/90948320-f28c3880-e46f-11ea-82d3-26b633ecd837.png">
2.On the menu page, some lines are not translated
<img width="583" alt="螢幕截圖 2020-08-24 下午7 38 38" src="https://user-images.githubusercontent.com/61215358/91040840-806b4d80-e641-11ea-970a-5a3ea7f34ce6.png">

**Comment by cqx931** [comment]
1. Yes this is an interesting issue, I will give it a check

2.The two strings are new features we recently added, I just updated it on crowdin. Could you add the Chinese translations for the two new strings [here](https://crowdin.com/translate/adnauseam/12/en-zhtw)? We uses crowdin to manage all translations and once we have all the necessary translations,(usually shortly before the official release), I will update the locale files in our github repo to match with the latest translations in crowdin. See [import-crowdin](https://github.com/dhowe/AdNauseam/blob/master/tools/import-crowdin.sh)

**Comment by cqx931** [comment]
so the first issue in https://github.com/dhowe/AdNauseam/issues/1721
the second one will be resolved in https://github.com/dhowe/AdNauseam/issues/1723, close this ticket for now
