### ISSUE TITLE
[Release 3.9.2 Chrome] DNT Problems

### ISSUE THREAD

**Issue by Real-John-Cheung** [dhowe/AdNauseam#1722]
refer to issue https://github.com/dhowe/AdNauseam/issues/1710#issuecomment-678587807

1. when disableHidingForDNT is checked, the ads seems to be still hidden and not counted in the no. of collected ads (on duckduckgo.com)
   screenshot when AdNauseam is disable
<img width="1546" alt="螢幕截圖 2020-08-24 下午2 38 51" src="https://user-images.githubusercontent.com/61215358/91011872-b562aa80-e617-11ea-8bf3-657be44ac883.png">
   screenshot when AdNauseam is activated and disableHidingForDNT is checked
<img width="1546" alt="螢幕截圖 2020-08-24 下午2 38 27" src="https://user-images.githubusercontent.com/61215358/91011801-8ea47400-e617-11ea-8947-14462c797969.png">
   the log when disableHidingForDNT is checked
<img width="1642" alt="螢幕截圖 2020-08-24 下午2 40 43" src="https://user-images.githubusercontent.com/61215358/91011930-cd3a2e80-e617-11ea-84da-aa302f614101.png">

**Comment by cqx931** [comment]
@Real-John-Cheung please verify the fix, if it works, the ticket can be closed

**Comment by Real-John-Cheung** [comment]
Fix verified
