### ISSUE TITLE
[Release 3.9.2] Firefox: Issues with Strict Blocking

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1727]
Only observed once, seems to be related to local storage from the previous encoding
NYT is on strict Blocking even it's not set
<img width="624" alt="image" src="https://user-images.githubusercontent.com/3056154/91235639-f59f5700-e703-11ea-9160-d1b40a9c427e.png">

**Comment by cqx931** [comment]
not from what I have experienced

**Comment by dhowe** [comment]
ok, closing for now -- lets see if it shows up again
