### ISSUE TITLE
Breaks eBay listings in Firefox

### ISSUE THREAD

**Issue by Australis86** [dhowe/AdNauseam#1729]
### Describe the issue

With the add-on enabled, some of the functionality on an eBay listing is broken (at least in Firefox). So far I have noted that the photo gallery (i.e. hover to zoom or clicking to change images) does not work, nor do watch lists.

### Screenshot in which the issue can be seen

![eBay glitch](https://user-images.githubusercontent.com/17158704/92110508-2e3edf00-ee2e-11ea-9e92-da0354a8710f.png)

### Steps for anyone to reproduce the issue
Load an eBay listing with the addon enabled
Try to change the gallery image or add an item to watch list

### Your settings

- OS/version: Windows 10 Build 18363
- Browser/version: Firefox 80.0.1 (64-bit)
- AdNauseam version: v3.9.109
- Other extensions you have installed: Avast Online Security, DuckDuckGo Privacy Essentials, Firefox Multi-Containers, Update Scanner, Video DownloadHelper
- AdNauseam settings: 
[AdNauseam_Settings_Export_9.3.2020.9.43.13PM.json.txt](https://github.com/dhowe/AdNauseam/files/5168243/AdNauseam_Settings_Export_9.3.2020.9.43.13PM.json.txt)

### Your location/country
Australia

** For adult and potential offensive sites/advertisements, please add a [Content Warning] tag in the title to warn developers that there may be offfensive material in the ticket.

**Comment by llacb47** [comment]
Fixed already, update your filters https://github.com/easylist/easylist/commit/211c25914d93acf74d600357a9966a24a536752f

**Comment by Australis86** [comment]
Hmm. Updating the filters manually (how often does the add-on update automatically with automatic updates enabled?) now breaks the "My Summary" page in eBay.

**Comment by Australis86** [comment]
Nevermind, cleared all the caches and tried again. Seems to be working now.
