### ISSUE TITLE
Cannot click javascript links on pages where ads are blocked

### ISSUE THREAD

**Issue by McBobb** [dhowe/AdNauseam#1730]
### Describe the issue
While this has only occurred on the domain, "forum2go.nl", it happens on every site there. Any time there is a link that is identified as Javascript, I cannot click it at all while AdNauseum is activated. Once I deactivate AdNauseum and relaunch my browser (Firefox 80.0.1), I'm able to click the previously inactive link. There is no warning message or flag of any time; just nothing happens

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
Simply have AdNauseum active when visiting any page on the "forum2go.nl" domain that has [JavaScript] links, instead of regular URL links, and they will be inactive.

### Your settings

- OS/version: Windows 10 Home, version 1909, Build 18363.1016
- Browser/version: Firefox 80.0.1
- AdNauseam version: 3.9.2
- Other extensions you have installed:
AddToAny: Share Anywhere				ver. 3.4.1
AdNauseam					ver. 3.9.2
Amazon.co.uk					ver. 1.1
Ank Pixiv Tool					ver. 3.0.12
Ant Video downloader				ver. 4.7
Block Site						ver. 4.0.8.2
Bookmark Tab Here					ver. 1.0
Bookmarks Organizer				ver. 3.1.0
Clear Site Cookies					ver. 1.2
Country Flags & IP Whois				ver. 0.3.7
Dark Background and Light Text			ver. 0.7.3
Dark Reader					ver. 4.9.18
Delete History					ver. 2.3
DeviantArt Filter					ver. 6.1.1
Disconnect					ver. 5.19.3
Don't Fuck With Paste				ver. 2.7
Download All Images				ver. 0.7.4
Download Image from Context Menu			ver. 1.0.1
Download Manager (S3)				ver. 5.12
Download with Free Download Manager (FDM)		ver. 0.2.0
Downloader for Instagram™				ver. 1.0.4
DownThemAll!					ver. 4.2.6
DuckDuckGo					ver. 1.0
Easy Video Downloader				ver. 0.1.5
easyGestures N					ver. 6.4
eBay						ver. 1.1
Element-Hider					ver. 1.1
Emoji Keyboard - Emojis For Firefox			ver. 4.2.4
Empty Cache Button				ver. 3.4
Enhancer for YouTube™				ver. 2.0.101
Find & Replace for Text Editing				ver. 1.3.17
Firefox Multi-Account Containers			ver. 7.0.2
Fixed Zoom					ver. 2.1.5
Flash Player 					ver. 1.1.9
Flash Video Downloader				ver. 6.3.14
FoxReplace					ver. 2.3.2
Free Download Manager				ver. 3.0.52
Go to Top of Page Button				ver. 1.3
Grammar and Spell Checker - LanguageTool		ver. 3.1.9
Greasemonkey					ver. 4.9
Happy Right-Click					ver. 1.1.0
Hide Fixed Elements				ver. 1.2
Honey						ver. 12.1.1
HTML Content Blocker				ver. 0.1.9
HTTPS Everywhere					ver. 2020.8.13	
Ignore X-Frame-Options				ver. 1.6.9
Image Downloader					ver. 0.1.1
ImTranslator: Translator, Dictionary, TTS			ver. 15.62
Kee - Password Manager				ver. 3.5.19
Media Panel					ver. 2.6
Merge Windows					ver. 1.0
MeWe+						ver. 1.4
Move Tabs					ver. 0.0.2
Multiple File Downloader				ver. 1.5.0
NoScript						ver. 11.0.41
Nuke Anything					ver. 2.4
Official Media Bias Fact Check Icon			ver. 1.7.1
Open Link in Browser As...				ver. 1.0
Open Links in Tabs					ver. 1.0.3
Open Page in Private Window				ver. 1.2.1
OSINT - Open Selection In New Tab			ver. 1.0
Reload Tabs Button					ver. 1.3
Restart Browser					ver. 1.2
Search Engine Ad Remover				ver. 1.1.3
Show/Hide passwords				ver. 0.4
Simple Close Tab button				ver. 1.2
Simple Form Fill					ver. 2.2.0
Single Window (open links in active window)		ver. 0.1.5
Smart Tab Mute					ver. 1.0.1.1
Snap Links					ver. 3.1.7
Stylus						ver. 1.5.13
Tab Close Button					ver. 1.4
Tab Session Manager				ver. 6.2.0
Tabby - Window and Tab Manager			ver. 2.1
Text Link						ver. 6.1.1
Textarea Cache					ver. 4.2.1
The Pirate Bay Torrent Search				ver. 0.1.8
TrackMeNot					ver. 0.10.46
Undo Close Tab					ver. 6.0.0
Undo Closed Tabs Menu				ver. 2.0
Video Downloader Pro				ver. 1.3.9
Video DownloadHelper				ver. 7.3.9
ViewPDF						ver. 1.1
Web Developer					ver. 2.0.5
Wikipedia (en)					ver. 1.0
YouTube mp3					ver. 1.0.14
YouTube Video and Audio Downloader (Dev Edt.)		ver. 1.0.8
YouTube Video Downloader/YouTube HD Download	ver. 1.1.21
YouTube™ No Buffer (Stop Auto-playing)			ver. 0.3.0.1
Zoom Page WE					ver. 17.8

- AdNauseam settings: Default

##### Your filter lists

Default

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
Canada (EST)

** For adult and potential offensive sites/advertisements, please add a [Content Warning] tag in the title to warn developers that there may be offfensive material in the ticket.

**Comment by mneunomne** [comment]
I tried to reproduce this issue but I visited multiple websites with this domain and all links seemed to be working fine, would perhaps need a more specific example of the exact page where I can this issue can be observed.

However, navigating a [webpage within this domain](https://rflmh.forum2go.nl/app.php/help/faq?sid=bec86733f842792d8e302618f868cd75) I experienced another issue which might be related to the `googleads` not being removed properly:

![Screen Shot 2021-02-16 at 15 28 01](https://user-images.githubusercontent.com/4967860/108076520-cf7fc180-706b-11eb-8d9a-fa8d7f3d25c8.png)

there is still an element with the class `adsbygoogle` without content inside of it, but it is still hovering over the page and blocking the clicks under them.

**Comment by mneunomne** [comment]
Plus, I realised this is a AdNauseam specific problem, with uBlockOrigin the ads disappear without blocking the clicks.

![Screen Shot 2021-02-16 at 16 08 28](https://user-images.githubusercontent.com/4967860/108081632-7581fa80-7071-11eb-800f-e1602d486994.png)
![Screen Shot 2021-02-16 at 16 07 34](https://user-images.githubusercontent.com/4967860/108081646-787ceb00-7071-11eb-9ec7-a639e5ec6833.png)

**Comment by dhowe** [comment]
It seems like some part of the google ad is not being properly removed from the dom... (and is thus blocking things behind it). The first thing to try is adding a rule in AdNauseam's Settings/My-Filters to fully hide that element. You can add it manually and test, or perhaps try with the element-blocker in the context menu (right-click, "block-element")

**Comment by mneunomne** [comment]
Fixed with [this PR](https://github.com/dhowe/AdNauseam/pull/1752)

added a domain specific rule for "forum2go.nl":
```
forum2go.nl##.adsbygoogle
```
There seemed to be an issue where the `##.adsbygoogle` rule from *Easy-List* was being overruled by the *Adn* rule `##ins[id*="aswift"] > iframe`, causing the upper `.adsbygoogle` element not being properly hidden. We should see if the same issue happens on other domains and try to come up with a more non-domain-specific solution.
