### ISSUE TITLE
Ads are still happening when watching twitch streams

### ISSUE THREAD

**Issue by actuallyrandomperson** [dhowe/AdNauseam#1732]
### Describe the issue
Ads are happening when I watch past broadcasts on twitch.tv

### Steps for anyone to reproduce the issue
If you go onto twitch and view a past broadcast of a 'twitch partner', a non-skippable ad occurs roughly every 10 minutes. I am not sure if this occurs during live broadcasts as I am usually unable to catch them, but due to recent changes from Twitch I imagine it does.

### Your settings

- OS/version:  
- Browser/version: Chrome (latest)
- AdNauseam version: AdNauseam v3.9.108
- Other extensions you have installed:
- AdNauseam settings:

##### Your filter lists

Default
### Your location/country
Australia

### Screenshot in which the issue can be seen

![ad-on-twitch](https://user-images.githubusercontent.com/737638/94331791-f62c5580-0001-11eb-9c94-be21a5d3a9d8.jpg)

**Comment by D3XX3R** [comment]
While this is not fixed I found a workaround on reddit.
https://www.reddit.com/r/uBlockOrigin/comments/j2648i/how_to_kill_ads_on_twitch/

**Comment by shejk0** [comment]
This workaround doesn't work as of today.

**Comment by Ashdemai** [comment]
I see ads on Twitch again, seems like they found a workaround again.

**Comment by mneunomne** [comment]
Tested and this is an issue with uBlock Origin as well.

According to [this reddit thread](https://www.reddit.com/r/Twitch/comments/jjepg8/fix_for_ublock_origin_on_twitch_i_updated_the/?sort=new) this seems to be an issue that follows the facebook ad pattern, where constant updates are needed and usually a solution only lasts for a couple of months...

**Comment by dhowe** [comment]
closing for now
