### ISSUE TITLE
Google ads visible on reuters.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1733]
https://www.reuters.com/article/us-britain-china-rights-idUSKCN26G1HR

![image](https://user-images.githubusercontent.com/737638/94331752-b9605e80-0001-11eb-839c-a1ec363b7393.png)

**Comment by Manichayan** [comment]
Same issue on dailymail [https://www.dailymail.co.uk/news/article-8800717/Seven-infected-Amy-Coney-Barrett-superspreader-event-White-House.html]

**Comment by mneunomne** [comment]
The ads do not show to me for me in both of the pages mentioned.

**Comment by dhowe** [comment]
I still see ads on current stories (at least from Australia):

eg https://www.reuters.com/article/us-india-farms-protests-disharavi/disha-ravi-the-indian-climate-and-animal-defender-accused-of-sedition-idUSKBN2AG1RM

![image](https://user-images.githubusercontent.com/737638/108083698-52c20700-70ae-11eb-9804-01a68bb0b77d.png)

**Comment by mneunomne** [comment]
Still, in Germany [the above mentioned ad](https://www.reuters.com/article/us-india-farms-protests-disharavi/disha-ravi-the-indian-climate-and-animal-defender-accused-of-sedition-idUSKBN2AG1RM) doesn't appear

**Comment by dhowe** [comment]
Verified in Australia, Hong Kong and Germany (below):

![image](https://user-images.githubusercontent.com/737638/108224213-9e8bb380-7175-11eb-8718-c4d5bb880aea.png)

**Comment by dhowe** [comment]
closed by @mneunomne
