### ISSUE TITLE
Doesn't block the stuff as effectively as expected

### ISSUE THREAD

**Issue by Agych** [dhowe/AdNauseam#1734]
### Describe the issue

I decided to turn off uBO and try out AdNauseam.
The config and the lists setup in uBO and AdNauseam are identical
So I was expecting AdNauseam to be hiding crap as good as uBO.
In practice, it turned to be not as expected, and the following crap started being visible after I switched:
- Popups and overlays related to cookies / gdpr & terms of use / privacy terms / privacy notice / such stuff on all websites.
- Advertised search results on Startpage.
- Maybe something more that I no longer remember.

Doubt that "Your settings" and "Your filter lists" play any role here, as mentioned they are identical in uBO and AdNauseam, and uBO cuts all the bad stuff very well.

Am I doing something wrong?
Or is it an expected behavior of AdNauseam cutting the stuff not as effectively as uBO?
In case of the latter, I should keep both uBO and AdNauseam active, and configure them in a way that they have no match in active settings and lists (active in the former, disabled in the latter), to cut the crap and in the same time let AdNauseam do its mission, are there any recommendations on how to do it the best / most practical way?

### Screenshot in which the issue can be seen
.

### Steps for anyone to reproduce the issue
.

### Your settings
` 
   "dntDomains": [],
    "parseTextAds": true,
    "eventLogging": false,
    "hidingAds": true,
    "clickingAds": true,
    "blockingMalware": true,
    "disableHidingForDNT": false,
    "disableClickingForDNT": false,
    "clickProbability": 1,
    "removeAdsInPrivate": true,
    "strictBlockingMode": false,
    "clickOnlyWhenIdleFor": 0,
    "noIncomingCookies": true,
    "noOutgoingCookies": false,
    "noOutgoingReferer": false,
    "noOutgoingUserAgent": false,
    "advancedUserEnabled": true,
    "alwaysDetachLogger": false,
    "autoUpdate": true,
    "cloudStorageEnabled": false,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": true,
    "firewallPaneMinimized": false,
    "hyperlinkAuditingDisabled": true,
    "ignoreGenericCosmeticFilters": false,
    "largeMediaSize": 50,
    "parseAllABPHideFilters": true,
    "popupPanelSections": 63,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": true,
    "tooltipsDisabled": false,
    "webrtcIPAddressHidden": false
`

- OS/version: Windows 7
- Browser/version: all my browsers (incl. Opera 58, Vivaldi 3.4)
- AdNauseam version: copy-paste from "About": AdNauseam v3.9.201 uBlock Originv1.29.0
- Other extensions you have installed:
- AdNauseam settings:

#### Your filter lists
`
    "user-filters",
    "adnauseam-filters",
    "easylist",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "adguard-spyware",
    "easyprivacy",
    "fanboy-enhanced",
    "urlhaus-1",
    "spam404-0",
    "adguard-annoyance",
    "adguard-social",
    "fanboy-thirdparty_social",
    "fanboy-cookiemonster",
    "facebook-annoyances-blocker",
    "fanboy-annoyance",
    "fanboy-social",
    "ublock-annoyances",
    "adguard-generic",
    "adguard-mobile",
    "dpollock-0",
    "fanboy-ultimate",
    "mvps-0",
    "plowe-0",
    "DEU-0",
    "FIN-0",
    "RUS-0",
    "https://easylist-downloads.adblockplus.org/adwarefilters.txt",
    "https://gist.github.com/kevincolten/a856d469e408f075f03d1316b4ada7e9/raw/e03fb4794ab132a8b6290797c525c2e9d81f45fd/ad_servers.txt",
    "https://mirror.cedia.org.ec/malwaredomains/justdomains",
    "https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt",
    "https://austinhuang.me/0131-block-list/list.txt",
    "https://gitlab.com/xuhaiyang1234/AAK-Cont/raw/master/FINAL_BUILD/aak-cont-list-ubo.txt",
    "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt",
    "https://easylist-downloads.adblockplus.org/antiadblockfilters.txt",
    "https://filters.adtidy.org/extension/chromium/filters/15.txt",
    "https://filters.adtidy.org/extension/ublock/filters/1.txt",
    "https://raw.github.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt",
    "https://easylist-downloads.adblockplus.org/fb_annoyances_newsfeed.txt",
    "https://www.fanboy.co.nz/fanboy-swedish.txt",
    "https://raw.githubusercontent.com/hant05080/uBlock-filters/master/filters.txt",
    "https://www.i-dont-care-about-cookies.eu/abp/",
    "https://raw.githubusercontent.com/Rudloff/adblock-imokwithcookies/master/filters.txt",
    "https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt",
    "https://raw.githubusercontent.com/Kees1958/WS3_annual_most_used_survey_blocklist/master/Top500",
    "https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt",
    "https://raw.githubusercontent.com/azet12/PopupBlocker/master/PPB.txt",
    "https://easylist-downloads.adblockplus.org/cntblock.txt",
    "https://raw.githubusercontent.com/gioxx/xfiles/master/facebook.txt",
    "https://secure.fanboy.co.nz/fanboy-social.txt?a=0"
`

**Comment by dhowe** [comment]
Hi @Agych - thanks for the report, and apologies for the slow reply. Ideally AdNauseam would work as well as ublock origin in blocking ads, but because of the fact that we also need to collect the ads (in order to click them), this is unlikely to ever be 100% the case.

With that said, the most useful thing for us is when you can include the details of the visible ads or popups that you encounter with AdNauseam (but not with ublock), including the URL and, ideally, a screenshot...

In terms of using them together, I'm not aware of anyone having developed a set of filter lists for each that would work in the way you describe (if you come up with such a list that makes sense, we're happy to publish it somewhere for people to use)

**Comment by mneunomne** [comment]
I think this was partly being caused because of the Dynamic Iframe issues. Agych thanks for the feedback we will continue to work on trying to hide as much as possible like uBlock Origin does. Closing for now.
