### ISSUE TITLE
DailyMail displaying google ads

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1736]
https://www.dailymail.co.uk/news/article-8938507/Donald-Trumps-234-pages-fraud-affidavits-include-unusual-claims.html

see top left of image -- there is a div containing an iframe, both with ids starting with 'google_ads', that we need to block, preferably on ALL sites:

![image](https://user-images.githubusercontent.com/737638/99139642-aa973f00-2675-11eb-8ada-38d44ae1d4c8.png)

![Screenshot 2020-11-14 at 12 28 24 PM](https://user-images.githubusercontent.com/737638/99139581-f990a480-2674-11eb-9fc1-0f1ea336a6e1.png)

**Comment by dhowe** [comment]
I don't see these ads anymore on my system - @mneunomne can you verify this ?

**Comment by mneunomne** [comment]
@dhowe Yes, I can't see them also.
