### ISSUE TITLE
Lilo.org displays ads

### ISSUE THREAD

**Issue by Snaxeko** [dhowe/AdNauseam#1737]
Is it normal that AdNauseam doesn't detect ads on [search.lilo.org](https://search.lilo.org/) ? Even uBO doesn't block these ads, but I though AdNauseam would collect these Microsoft ads.
I think it's a general issue, anyone can repeat that. Otherwise I'll edit to respect the form.

Ex: https://search.lilo.org/?q=bougie

Edit : there are also shopping image ads at the right side
Added screen with the following query : "sac de sport" --> 3 text ads + 5 image ads

![firefox_2020-11-25_23-33-47](https://user-images.githubusercontent.com/20836655/100288522-272ff480-2f77-11eb-8c70-d9e352c6c6cc.png)

**Comment by dhowe** [comment]
If the ads are not blocked by uBlock, then it is an issue for the specific lists where hiding/blocking rules are maintained
Thanks
