### ISSUE TITLE
Prefs don't open with FF 84.0b6 for Apple Silicon / arm64

### ISSUE THREAD

**Issue by mbirth** [dhowe/AdNauseam#1738]
### Describe the issue
On a Mac with the new M1 chip and Firefox 84.0b6 (support for Apple Silicon), AdNauseam seems to load, but I can't configure it. Clicking the settings button from the extension's popup does nothing. Opening the settings from the Add-Ons manager opens them, but clicking on a tab doesn't do anything.

Most other add-on's settings open fine (Imagus and RES don't work, too) so I'm not sure if this is a Firefox issue or an AdNauseam issue. Or both.

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

1. Install Firefox 84 Beta on a Mac with M1 chip
2. Install AdNauseam add-on
3. Try to edit settings in AdNauseam

### Your settings

- OS/version: macOS Big Sur 11.0.1 on MacBook Pro with M1 chip
- Browser/version: Firefox 84.0b6 (latest as of today)
- AdNauseam version: 3.9.201
- Other extensions you have installed: Bitwarden, Copy PlainText, Imagus, Facebook Container, Offline QR Code Generator, Open In IINA, Passwordstate, RES, Search by Image, To Google Translate, Wallabagger, What Hacker News Says
- AdNauseam settings: defaults/empty as I can't get into the settings

### Your location/country

Germany

**Comment by dhowe** [comment]
Will need to find a silicon Mac to test this properly. If you are interested in helping out, please let us know...

**Comment by Real-John-Cheung** [comment]
apparently the problems do not occur in the newest official version (87.0) now
but for that particular version (84.0b6) the setting page keeps crashing.  (in the following official version (85.0) it works well too...)

**Comment by Real-John-Cheung** [comment]
#### test result for Firefox version 87.0 (newest official version) on a Silicon Mac mini with macOS Big Sur 11.2 & AdNauseam 3.9.401
---
#### not passing tests:
* Icon should animate each time an Ad is clicked (Toolbar Icon) 
* Check that the dashboard (if open) is updated when notifications change   -> need to refresh
* DNT-header is being sent correctly for ALL requests (including Ad visits) if either disableClickingForDNT and disableHidingForDNT are enabled (and vice versa) ->not sure what happen but there's no DNT field in the request header...
* Check that the "redirect" and "redirect-rule" are properly working
* Strict Blocking  -> they are not triggered. related requests are mark blue (and-allowed) in logger
* My rules editor -> my rules editor seems to have some problem with `strictBlock`, after saving and commiting a line with `strictBlock` the line cant not be change to `block` `allow` or `noop` (when click save, the action changes to undefine and highlighted in codeMirror)... 

---
#### whole list in txt
[Testing-New-Release-Candidates.txt](https://github.com/dhowe/AdNauseam/files/6290052/Testing-New-Release-Candidates.txt)

**Comment by dhowe** [comment]
Note about the milestone: I'm not sure we need to fix the specific silicon issue for the current release, especially as it seems to affect only a beta version of Firefox, but we do need to test the above issues on other platforms (my sense is that some may be cross-platform issues)

**Comment by mneunomne** [comment]
> #### not passing tests:
> * Icon should animate each time an Ad is clicked (Toolbar Icon)

Does the icon in the toolbar animate when an Ad is clicked? Is it the Adn icon itself or the ad thumbs?  If its the icon I haven't observed it working so far...

> * Check that the dashboard (if open) is updated when notifications change   -> need to refresh

Yes I can confirm that is happening, will create a ticket.

> * DNT-header is being sent correctly for ALL requests (including Ad visits) if either disableClickingForDNT and disableHidingForDNT are enabled (and vice versa) ->not sure what happen but there's no DNT field in the request header...

Not sure If I understood this DNT check, the description seems confusing. 

> * Check that the "redirect" and "redirect-rule" are properly working
> * Strict Blocking  -> they are not triggered. related requests are mark blue (and-allowed) in logger
> * My rules editor -> my rules editor seems to have some problem with `strictBlock`, after saving and commiting a line with `strictBlock` the line cant not be change to `block` `allow` or `noop` (when click save, the action changes to undefine and highlighted in codeMirror)...

These issues are already being handles in other tickets.

**Comment by dhowe** [comment]
> Does the icon in the toolbar animate when an Ad is clicked? Is it the Adn icon itself or the ad thumbs?  If its the icon I haven't observed it working so far...

Yes, the icon should animate. And this has worked in all previous versions. [pls create new ticket]

> 
* DNT-header is being sent correctly for ALL requests (including Ad visits) if either disableClickingForDNT and disableHidingForDNT are enabled (and vice versa)  -> Not sure If I understood this DNT check, the description seems confusing. 

The DoNotTrack header should be sent in all outgoing requests (both normal page loads and ADN ad-clicks) if either of those settings are true.

**Comment by mneunomne** [comment]
> 1. Yes, the menubar icon should animate. This has worked in all previous versions [pls create a new ticket]

Was a bit late on this message, I see you created the ticket, will look into that. 

> 2. The DoNotTrack header should be sent in all outgoing requests (both normal page loads and ADN ad-clicks) if either of those settings are true

Ran the tests and  DoNotTrack header headers appears to be working as expected.
