### ISSUE TITLE
TrackMeNot no longer maintained - still safe to use with Adnauseam?

### ISSUE THREAD

**Issue by jasonbrown1965** [dhowe/AdNauseam#1739]
_greetings all,_

was looking up [TrackMeNot](http://www.cs.nyu.edu/trackmenot/) as per your [FAQ](https://github.com/dhowe/AdNauseam/wiki/FAQ) advising it can work with AdNauseam, and see that the github maintainer recently said he can [no longer maintain the extension](https://github.com/vtoubiana/TrackMeNot/issues/128).

Sidenotes: code was last updated 15 months ago. 

I guess my main query is - **is TrackMeNot still safe to use with AdNauseam? If not should the FAQ be updated?**

Sorry if this is not the right place for this. I did send this ^ to emails adnauseam@rednoise.org and daniel@rednoise.org but I see the site is now offline and the emails bounced.

_jas_

**Comment by dhowe** [comment]
Hi @jasonbrown1965 -- its a good question. We're now looking at ways of funding continuing development of both projects (if you have any ideas, please let us know!). At moment, I can't speak to the state of the TrackMeNot, but I don't imagine there would be anything 'unsafe' about using it with AdNauseam -- TrackMeNot may just not function as well as one would hope...
