### ISSUE TITLE
Image not centered over text on privacy-policy page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#174]
![screen shot 2016-05-25 at 7 31 13 pm](https://cloud.githubusercontent.com/assets/737638/15538544/7b1e5fc0-22af-11e6-925e-999d415d4e95.png)

**Comment by dhowe** [comment]
done

**Comment by CyrusSUEN** [comment]
> done

The fix https://github.com/dhowe/AdNauseam/commit/e8aa609d67da12650cec1be0db5c80ad6a72c3fa is not enough. It fixed the #logo in privacy.html but broke it in press.html.

I've made a fix across 3 HTML pages for the logo and centered the content below the logo. It should be good to merge: https://github.com/dhowe/AdNauseam/pull/191

**Comment by dhowe** [comment]
nice

**Comment by dhowe** [comment]
First paragraph centering doesn't look right on pivacy:

![screen shot 2016-05-28 at 4 58 57 pm](https://cloud.githubusercontent.com/assets/737638/15626347/8f06b8dc-24f5-11e6-93f7-831e97fe5356.png)

**Comment by CyrusSUEN** [comment]
> First paragraph centering doesn't look right on pivacy:

Just fixed in 4809f1830be6be8bb1eb9206fb5c34095c893b70.

Sorry I accidentally pushed the changes directly to the gh-pages branch in dhowe/AdNauseam.
I thought my changes in the branch was pushed to my Github repo.
