### ISSUE TITLE
3.9.201 Breaks after a while on firefox 84.0.2

### ISSUE THREAD

**Issue by kittyluvr** [dhowe/AdNauseam#1740]
### Describe the issue
I'm not sure what the trigger is, but the most recent version (3.9.201) on the addon store breaks after a couple days. It stops blocking ads and the information section (when you click on the icon) does not display correctly. This is only fixed by reinstalling the addon. I have not had this happen with the previous version, so I'm doing to downgrade to that for now.

### Screenshot in which the issue can be seen
![Screen Shot 2021-01-12 at 9 22 36 AM](https://user-images.githubusercontent.com/55204881/104349913-69c27780-54b8-11eb-806d-3697ec75a6a6.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version: macOS 10.15.7
- Browser/version: Firefox 84.0.2
- AdNauseam version: 3.9.201
- Other extensions you have installed: [Bandcamp Volume](https://github.com/DanielKamkha/BandcampVolumeFirefox), [Grammarly](http://grammarly.com/), [New XKit](https://github.com/new-xkit/XKit), [Send to Outline](https://addons.mozilla.org/en-US/firefox/addon/send-to-outline/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser), [Shinigami Eyes](https://shinigami-eyes.github.io/), [Tab for a Cause](https://tab.gladly.io/), [To Google Translate](https://github.com/itsecurityco/to-google-translate), [Video Speed Controller](https://github.com/codebicycle/videospeed), [Zotero Connector](https://www.zotero.org/)
- AdNauseam settings: Defaults

##### Your filter lists
All default filter lists.

### Your location/country
California

** For adult and potential offensive sites/advertisements, please add a [Content Warning] tag in the title to warn developers that there may be offfensive material in the ticket.

**Comment by dhowe** [comment]
Thanks for the report. I wonder if this is might be due to a corrupted Firefox profile. If you don't mind, can you try installing the current version of AdNauseam in a new profile, as described here: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_creating-a-profile

**Comment by dhowe** [comment]
closing due to no response
