### ISSUE TITLE
Question Regarding Element Blocking

### ISSUE THREAD

**Issue by shangles** [dhowe/AdNauseam#1741]
Since this is based on uBlock Origin, will there be a way to block page elements that are not ads?  I currently use that feature a lot with uBlock Origin, and don't want to give it up - since I'll have to disable or uninstall if I want to use AdNauseam.

**Comment by dhowe** [comment]
You should be able, via the element block accessible in the context menu, to block whatever element you like. Is that not the case for you?

**Comment by dhowe** [comment]
Closing due to no response
