### ISSUE TITLE
Keep AdNauseam updated for Brave (Windows' registry location)

### ISSUE THREAD

**Issue by ghost-420** [dhowe/AdNauseam#1744]
Add to: https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission#keep-adnauseam-updated
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\BraveSoftware\Brave\ExtensionInstallForcelist]
```

**Comment by dhowe** [comment]
Please check: https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission

**Comment by ghost-420** [comment]
Thank you.
