### ISSUE TITLE
Translations for Kannada

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1745]
You've got a message from IntrosPector in the conversation "AdNauseam project" on Crowdin.

"Hi, I could try doing the translation to Kannada, an Indian language. Where do I get started?"

**Comment by mneunomne** [comment]
@dhowe I checked the [crowdin for ublock](https://crowdin.com/project/ublock) and the Kannada language is [currently at 34% translated](https://crowdin.com/project/ublock/kn). So the correct procedure is for us to wait until this language is fully support by uBlock and then we set it up on our side, correct ?

Perhaps suggest to IntrosPector to contribute this language to uBlock before start contributing it to us.

**Comment by dhowe** [comment]
Done
