### ISSUE TITLE
gmail fake mail in inbox aren't blocked

### ISSUE THREAD

**Issue by narFnarF** [dhowe/AdNauseam#1746]
### Describe the issue
Gmail includes fake emails in the mailbox that are actually ads. AdNauseam doesn't block them, but uBlock Origin was able to.

### Screenshot in which the issue can be seen
![](https://i.imgur.com/QvoDtLS.png)

### Steps for anyone to reproduce the issue
My gmail is in French. I tried to translate the steps to English as best I could.
1. Login to your email in gmail.com
2. Go to the "Promotions" inbox
3. Observe ads in the "Best choices" section at the top.

Note: If you don't have the Promotions inbox, you might need to first activate it in gmail's Settings > Inbox > Promotions.
https://i.imgur.com/FvdNhCM.png

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox
- AdNauseam version: v3.9.201
- Other extensions you have installed:
- AdNauseam settings: Facebook container

##### Your filter lists
https://i.imgur.com/DpkhwhW.png

### Your location/country
Montréal, Canada

**Comment by mneunomne** [comment]
Yes I confirm this is happening. 

But what's interesting is that with uBlock the whole top segment that I highlighted in red "Principais Recomendações" (main recommendations) disappears, together with two other email links that are not Ads. It seems that gmail mixes the ads with the regular emails so you are most likely to click on it.

I'll try to look up what approach does uBlock have in regards of this. 

![Screen Shot 2021-02-18 at 18 15 09](https://user-images.githubusercontent.com/4967860/108495882-a2205700-72a9-11eb-898c-6bad8045493f.png)
![Screen Shot 2021-02-18 at 18 14 58](https://user-images.githubusercontent.com/4967860/108495894-a482b100-72a9-11eb-96df-4fe0755bd4d6.png)

**Comment by dhowe** [comment]
can use the logger to trace the rules that are firing in ublock to handle these

**Comment by mneunomne** [comment]
closed with https://github.com/dhowe/AdNauseam/pull/1753
