### ISSUE TITLE
Add Chrome/Opera instructions to wiki install page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#175]
https://github.com/dhowe/AdNauseam/wiki/Installing-AdNauseam

**Comment by CyrusSUEN** [comment]
Updated: https://github.com/dhowe/AdNauseam/wiki/Installing-AdNauseam

Please also add Firefox extension files for future releases on Release page.
And for the Chromium releases we do not need to pack them into .crx or .nex format, simply zipping the folder will be enough.

**Comment by CyrusSUEN** [comment]
BTW the Chrome installation instruction page may be duplicated.
See: https://github.com/dhowe/AdNauseam/wiki/Beta-test-AdNauseam-for-Chrome which is linked from  "Try AdNauseam for CHrome button" from https://adnauseam.io/
