### ISSUE TITLE
Manifest warnings cause Adnauseam to be unavailable on Firefox mobile

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1751]
Warnings below:

Warning: "strict_min_version" requires Firefox for Android 55.0, which was released before version 57 introduced support for "browser_action.default_popup".
manifest.json
Manifest key not supported by the specified minimum Firefox for Android version

Warning: "strict_min_version" requires Firefox for Android 55.0, which was released before version 57 introduced support for "options_ui".
manifest.json
Manifest key not supported by the specified minimum Firefox for Android version

Warning: "strict_min_version" requires Firefox for Android 55.0, which was released before version 57 introduced support for "options_ui.open_in_tab".
manifest.json
Manifest key not supported by the specified minimum Firefox for Android version

Warning: "strict_min_version" requires Firefox for Android 55.0, which was released before version 57 introduced support for "options_ui.page".
manifest.json
Flagged file extensions found

Warning: Files were found that are either unnecessary or have been included unintentionally. They should be removed.
assets/update-git.sh
webRequest.filterResponseData is not supported in Firefox version 55.0

Warning: This API is not implemented by the given minimum Firefox version
js/background.js line 136 column 39
webRequest.filterResponseData is not supported in Firefox for Android version 55.0

Warning: This API is not implemented by the given minimum Firefox for Android version
js/background.js line 136 column 39
Unknown word

Warning: An error was found in the CSS file being processed as a result further processing of that file is not possible
css/about.css line 24 column 3
Unexpected }

Warning: An error was found in the CSS file being processed as a result further processing of that file is not possible
css/settings.css line 13 column 1
Inline scripts blocked by default

Warning: Default CSP rules prevent inline JavaScript from running (https://mzl.la/2pn32nd).
unit-tests.html
browserAction.setPopup is not supported in Firefox for Android version 55.0

Warning: This API is not implemented by the given minimum Firefox for Android version
js/start.js line 391 column 5
browserAction.setPopup is not supported in Firefox for Android version 55.0

Warning: This API is not implemented by the given minimum Firefox for Android version
js/start.js line 402 column 9
dns.resolve is not supported in Firefox version 55.0

Warning: This API is not implemented by the given minimum Firefox version
js/vapi-webrequest.js line 289 column 20
dns.resolve is not supported in Firefox for Android version 55.0

Warning: This API is not implemented by the given minimum Firefox for Android version
js/vapi-webrequest.js line 289 column 20

**Comment by cqx931** [comment]
currently based on 1.29.0
merge ublock at least to 1.33.0

**Comment by cqx931** [comment]
@mneunomne  update merge wiki

**Comment by mneunomne** [comment]
`strict_min_version` updated on this merge https://github.com/dhowe/AdNauseam/commit/7e356045c21a1d167564e6445d5689ec7ca5bce2
