### ISSUE TITLE
Ads that open in full-screen mode

### ISSUE THREAD

**Issue by FabienOnGithub** [dhowe/AdNauseam#1756]
### Describe the issue
The issue is simple, when I open a video player (here from streamtape.com) there are some ads that appear in the top-right corner. I cannot block them because the menu of AdNauseam cannot appear on full-screen mode.

### Screenshot in which the issue can be seen
[ads on full screen mode](https://dwayne.wheres-my-ta.co/k61zAk)
[AdNauseam menu that only appear when i quit the full-screen mode](https://dwayne.wheres-my-ta.co/KIDMbK)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
Go to voiranime.com
Click on an anime (the anime that you select doesn't matter)
Select the good video player "Lecteur STAPE" [here a screenshot of where to click](https://dwayne.wheres-my-ta.co/rFu32M)
start the video and enter the full-screen mode, the ads will appear.

### Your settings

- OS/version: Win10
- Browser/version: Brave
- AdNauseam version: 3.9.201
- Other extensions you have installed: Ghostery and Dark Reader
- AdNauseam settings: Default

##### Your filter lists

Default Filer List FRA: AdGuard Français
### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

** For adult and potential offensive sites/advertisements, please add a [Content Warning] tag in the title to warn developers that there may be offfensive material in the ticket.

**Comment by mneunomne** [comment]
@FabienOnGithub I wasn't able to reproduce the issue specifically regarding the ads showing on fullscreen, but I was able to block multiple ads showing in this website. Hopefully this should fix your underlying issue.

https://github.com/dhowe/AdNauseam/pull/1759

**Comment by dhowe** [comment]
@FabienOnGithub if you have further issues with this page, please reopen the ticket
