### ISSUE TITLE
µb.redirectEngine.toURL doesn't exist anymore on 1.33.0

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1764]
The function `toURL` from the `src/js/redirect-engine.js` doesn't exist anymore in uBlock, generating an **exceptionError** in **Adn**. 
It is used inside the `isBlockableRequest` function in the `src/js/adn/core.js` file:
```
   // always allow redirect blocks from lists (?)
    if (µb.redirectEngine.toURL(context)) {
      logNetBlock('*Redirect*', context.docDomain + ' => ' + context.url, context);
      return true;
    }
```
The new equivalent function in the `src/js/redirect-engine.js` is `tokenToURL`, but we don't have the necessary parameters in the above code to run it.

The commit in which this change occurred in uBlock: https://github.com/gorhill/uBlock/commit/157cef6034a8ec926c1e59c7e77f0a1fcbef473c

@dhowe or @cqx931  would you be able to know the purpose of our use of this `toURL` function ? That's the only place that I use it.
For now I just commented this block out, and it *apparently* is not causing any issues. But since I don't know *what* should I test, I can't be sure.

**Comment by dhowe** [comment]
closed in favor of #1771
