### ISSUE TITLE
Refactor navigation of adVault

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1766]
The Zoom-in-out function in the  AD-VAULT is a bit annoying since it always zooms in to the center of the whole page, so when we are far from the center zooming in, it shifts the window towards the center - not zooming where you were aiming for.

An algorithm like this needs to be implemented for that improvement: https://stackoverflow.com/questions/60190965/zoom-scale-at-mouse-position.

**Comment by dhowe** [comment]
can you find a d3 equivalent?

**Comment by mneunomne** [comment]
https://bl.ocks.org/mbostock/2206340
Shouldn't too difficult to implement.

**Comment by mneunomne** [comment]
But actually would be better to refactor this part of the code, since some behaviours are a bit clunky. Like the transition from an element when you click and how does it fit to the screen + the camera transition for it to come to the center... I'll take a look at it see how much time it would take.

**Comment by dhowe** [comment]
excellent -- that part of the code has always been a bit of a hack

**Comment by mneunomne** [comment]
This was already done in https://github.com/dhowe/AdNauseam/issues/1896. Closing
