### ISSUE TITLE
[ublock-v1.33.0] wrong font in menu

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1768]
Also throughout settings...

![image](https://user-images.githubusercontent.com/737638/111305191-96019c80-8691-11eb-8290-aa1928f7342e.png)

**Comment by mneunomne** [comment]
@dhowe Can you tell me which browser this is ?

**Comment by dhowe** [comment]
all tests should be done in firefox unless other specified

**Comment by mneunomne** [comment]
Still wasn't able to reproduce. Perhaps check console see if there is 404 font request ?

**Comment by dhowe** [comment]
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/737638/111862135-3c99b600-898e-11eb-95f3-11d6f74f6afd.png">

Don't see any errors regarding fonts in the console

Are you using a fresh firefox profile for your tests?

**Comment by dhowe** [comment]
See this even 

<img width="650" alt="Screenshot 2021-03-20 at 3 36 43 PM" src="https://user-images.githubusercontent.com/737638/111862766-4a513a80-8992-11eb-9b10-6c4e52a423ce.png">

**Comment by mneunomne** [comment]
Strange, I have run the project from a new Firefox profile, and tried different ways of building, cleared the git cache, changed to the branch __ublock1.33.0__ but still this font error doesn't appear to me.

Perhaps give a check if the CSS font definition is there, and also if the font file can be found in the requests ?

![Screen Shot 2021-03-22 at 16 10 04](https://user-images.githubusercontent.com/4967860/112012515-8e2a7800-8b29-11eb-97dd-5125323af323.png)
![Screen Shot 2021-03-22 at 16 09 45](https://user-images.githubusercontent.com/4967860/112012544-9387c280-8b29-11eb-8082-ee4c2e721ae7.png)

**Comment by dhowe** [comment]
So as you can see below, the font is loading correctly because it renders some elements correctly. But apparently a .css rule for HiDPI (retina) displays (in dshboard.css) is overriding it (I'm guessing you aren't using a retina display). The two screencaps below should give you the info you need for a fix.

<img width="1440" alt="Screenshot 2021-03-23 at 2 39 07 AM" src="https://user-images.githubusercontent.com/737638/112041510-6f57d000-8b81-11eb-8e0a-dfb3e827c89e.png">

<img width="1440" alt="Screenshot 2021-03-23 at 2 37 36 AM" src="https://user-images.githubusercontent.com/737638/112041539-77177480-8b81-11eb-8184-9d67b9ab5a2c.png">

**Comment by mneunomne** [comment]
Aha, I wasn't able to reproduce because my monitor is not HiDPI. Will fix it right away.

![Screen Shot 2021-03-22 at 20 32 44](https://user-images.githubusercontent.com/4967860/112047581-ca6fcf80-8b4d-11eb-8cfe-e64403f85cb2.png)
