### ISSUE TITLE
Warning on firstrun.html

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1774]
`This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.`

**Comment by mneunomne** [comment]
This comes from uBlock itself:

https://github.com/dhowe/AdNauseam/blob/095825de278c4607df399b9f38862993bd7036e0/src/css/dashboard-common.css#L12-L16

They should change it at some point, but maybe we can wait if they will do that ?

https://developer.mozilla.org/en-US/docs/Web/CSS/zoom says:
> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behaviour may change in the future.

**Comment by dhowe** [comment]
That's fine, closing for now
