### ISSUE TITLE
Review the lists in core::enabledBlockLists

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1776]
Review the lists of allow blocks. 

https://github.com/dhowe/AdNauseam/blob/095825de278c4607df399b9f38862993bd7036e0/src/js/adn/core.js#L41-L50

But how exactly to review them ? @dhowe

**Comment by dhowe** [comment]
Largely through inspection: both of the list description and some subset of the rules themselves. For example, if a list is current and still being updated, and its stated purpose is to block, say, social medium sharing links, then this it is likely fine to allow blocks from that list. 

Also keep in mind that we can disallow blocks from a list, but still also add some subset of those blocking rules to adnauseam.txt to deal with specific things we want to block.

**Comment by mneunomne** [comment]
From the review I made this list seem correct.  I wouldn't be able to know at the moment how to improove it. I certified that all these lists are still part of our filter list as well. (had to check since some were removed last version)

**Comment by dhowe** [comment]
The last thing we should do before closing this is to make sure that these lists (actually all lists that we use) are still in use by uBlock.

**Comment by mneunomne** [comment]
Yes, our filters are in sync with uBlock. On every merge we get updated.  
I was getting confused by the file `https://github.com/dhowe/AdNauseam/blob/master/assets/ublock/filter-lists.json` which is not being called anywhere. Deleting it on following commit

**Comment by mneunomne** [comment]
Okay, it seems that removing it causes some issues in our build for some reason. uBlock doesn't have this file or folder in assets, but somehow creates it on build. Will check this later. Closing this and creating another ticket to address this minor thing.
