### ISSUE TITLE
Ads visible on dimsumdaily.hk

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1779]
Ads visible on: https://www.dimsumdaily.hk/man-robbed-of-hk3-8m-in-cash-in-tin-hau-carpark-when-trying-to-buy-bitcoin/

<img width="976" alt="image" src="https://user-images.githubusercontent.com/737638/112250450-5ab82c80-8c94-11eb-8347-8057e4880da7.png">

**Comment by mneunomne** [comment]
Fixed with https://github.com/dhowe/AdNauseam/pull/1782
