### ISSUE TITLE
Page broken on liberalarts.tulane.edu

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1783]
Blank page renders on https://liberalarts.tulane.edu/programs/digital-media-practices
With ADN disabled, page reappears

**Comment by mneunomne** [comment]
@dhowe was not able to reproduce, the page works fine in Both Firefox and Chrome, in both current and next Adn release. Maybe you have some extra configuration causing this issue ?

**Comment by dhowe** [comment]
also can no longer recreate, closing
