### ISSUE TITLE
Page broken: https://www.bmeia.gv.at/

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1784]
Because the cookies popup is blocked, their is an semi-transparent overlay on the page and scrolling is disabled.

https://www.bmeia.gv.at/en/travel-stay/entry-and-residence-in-austria/entrance-and-residence/settlement-and-residence/

Filter lists:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/737638/112983908-cd437380-9190-11eb-8f00-62757997400a.png">

**Comment by mneunomne** [comment]
@dhowe  This seems to be an issue with "Fanboy’s Annoyance" filter list. I tested it on uBlock with this filter list activated and the same issue occurred.

**Comment by dhowe** [comment]
Had better check also with "Adguard Annoyances" and "uBlock filters - Annoyances"

**Comment by mneunomne** [comment]
No, apparently its only the "Fanboy’s Annoyance".

**Comment by dhowe** [comment]
if we get a bunch of these, we can report them to the list maintainer
