### ISSUE TITLE
Reply to UI question in Discussions

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1787]
Please see #1786

**Comment by mneunomne** [comment]
@dhowe From this discussion I think there is an issue with "my rules" tab on Adn actually. There seems to be a malfunction with the "save" and "commit" mechanism when trying to edit the rules through plain text. I compared with uBlock and smth seems to be not working. 
Unless I am missing something that is naturally different between uBlock and Adn.

**Comment by dhowe** [comment]
Nope, should work the same...

**Comment by mneunomne** [comment]
Ok, I answered the discussion and created the ticket
