### ISSUE TITLE
Fix CSS in 'Filter Lists' settings panel

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1788]
Add vertical space -- difficult to read currently:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/737638/112983354-2c54b880-9190-11eb-985d-5ee3a3630df1.png">

**Comment by mneunomne** [comment]
@dhowe you mean add vertical space between the segment titles? like "languages" "custom" etc ?

**Comment by dhowe** [comment]
yes, I think at very least we need some space above each of those
it also doesn't seem consistent now, as space below 'Essentials' != space below the others
