### ISSUE TITLE
Can't properly edit "My Rules" on dashboard 

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1789]
### The Issue

Adnauseam don't behave as expected when tryng to edit "My Rules" on the dashboard. Most of the time after editing the rules, after clicking "save" the "commit" button doesn't activate as it is supposed to.

This is a critical issue since if a block rule is added from the µ menu, it can't be removed any longer. Causing the user to have to reset to default settings to remove them.

### How to reproduce

__!!!Careful trying to reproduce this issue since it may cause you to have to reset to default settings__ 

- Create some rules from the Dynamic filtering menu
- Go to "My rules" and try to erase them from the right-hand side editor 
- Click "Save"
- The "commit" button won't show. Or it will show but the text will be wrongly saved.  

Tested both on Firefox and Chrome, current and 1.33.0 release.

**Comment by mneunomne** [comment]
@dhowe the issue seems to be with the [dynamic-net-filtering.js](https://github.com/dhowe/AdNauseam/blob/master/src/js/dynamic-net-filtering.js) file. Adn has some modification adding some bytes to support an extra action of `Strict Block` and some other things, maybe you can help to understand why is that?

**Comment by dhowe** [comment]
Can you give me some more context as to what is happening (or not happening), preferably with line numbers ?

**Comment by dhowe** [comment]
@cqx931 wondering if you can remember what this added constant is doing in [dynamic-net-filtering.js](https://github.com/dhowe/AdNauseam/blob/master/src/js/dynamic-net-filtering.js#L56)  ?

**Comment by mneunomne** [comment]
Tested and appears to be working as expected now.
