### ISSUE TITLE
Feature: vault 'purge' dead ads

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1791]
for ads that can no longer be rendered, we should have a button to remove these from the vault

**Comment by mneunomne** [comment]
Should we automatically just filter them out ?

**Comment by dhowe** [comment]
perhaps we should filter them from the view, but we'd need a way to keep track of which have not rendered.
and we also need to make sure that we don't remove or hide ads when a person loses internet connectivity

**Comment by mneunomne** [comment]
Yes I don't think we should remove them from the json file automatically. But not rendering them would also make it not possible to be manually deleted. Perhaps an option "hide failed ads" ?

**Comment by dhowe** [comment]
you mean a vault option? yes, I think that works... and it can probably be the default
perhaps we call them 'expired ads', rather than 'failed'

**Comment by mneunomne** [comment]
Implemented the "purge dead ads" it gives a warning to make sure that you are connected to the internet. Then deletes all ads that have "image-error" in them.

**Comment by mneunomne** [comment]
@dhowe I was thinking about this, but this approach might complicate things a bit, I would say if its just a user choice we don't need to automate it.

**Comment by dhowe** [comment]
ok for now
