### ISSUE TITLE
Better documentation for logger

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1800]
Logger documentation is quite thin: https://github.com/dhowe/AdNauseam/wiki/The-logger

(fix directly post release)

Need to include (at least):

- [x] "~~" for ADN-Allow rules
- [x] "@@" for DNT-Allow rules
- [x] Image 1 below: (why are there two ADN-Allow entries with different casing and dashing, and no DNT entries ? )
- [x] Update image for current release (image 2 below)

![](https://user-images.githubusercontent.com/3056154/89107817-acf4c680-d401-11ea-8845-3287e543bf68.png)

![](https://raw.githubusercontent.com/wiki/dhowe/AdNauseam/logger.png)

**Comment by cqx931** [comment]
The last line in the logger documentation image above should be DNT Allow.

**Comment by dhowe** [comment]
Ok, and lets be consistent with naming:

- Block
- Allow
- Cosmetic
- ADN-Allow
- DNT-Allow
- CNAME

**Comment by mneunomne** [comment]
@dhowe here are some updates, what else should we add ? 

### Update menu pictures to new version

![logger-menu-1](https://user-images.githubusercontent.com/4967860/117322505-5b94ce80-ae8e-11eb-8f27-10304a9cd321.png)

![logger-menu-2](https://user-images.githubusercontent.com/4967860/117322598-6f403500-ae8e-11eb-985a-6b3f33d32c9b.png)

## Logger events

### Block
**Code**: `--`
![Block](https://user-images.githubusercontent.com/4967860/117323367-1de47580-ae8f-11eb-9e67-77547da6743a.png)

### Redirect
**Code**: `<<`
![Redirect](https://user-images.githubusercontent.com/4967860/117323657-61d77a80-ae8f-11eb-9d2e-8b94038c7ed2.png)

### Cosmetic
**Code**:   none
![Cosmetic](https://user-images.githubusercontent.com/4967860/117323793-7f0c4900-ae8f-11eb-815b-18cff3d2ce69.png)

### ADN-Allow
**Code**: `~~`
![ADN-Allow](https://user-images.githubusercontent.com/4967860/117323980-a9f69d00-ae8f-11eb-9654-2e00ec499a61.png)

### DNT-Allow
**Code**: `@@`
![DNT-Allow](https://user-images.githubusercontent.com/4967860/117324056-b8dd4f80-ae8f-11eb-8237-847c286280cc.png)

**Comment by dhowe** [comment]
This looks good -- wonder if we can combine into one image as before (maybe some creative cut/paste?)

**Comment by mneunomne** [comment]
Okay, I am just lacking any decent image editing software at the moment, but I'll find a solution.

**Comment by mneunomne** [comment]
Updating Wiki with this image

![logger-colors](https://user-images.githubusercontent.com/4967860/118269253-ccf00500-b4be-11eb-9c64-ddadef91d6d2.png)

**Comment by mneunomne** [comment]
Screenshot with new brighter colors

![Screen Shot 2021-05-14 at 14 18 42](https://user-images.githubusercontent.com/4967860/118269692-57d0ff80-b4bf-11eb-968e-3651c04272d2.png)

**Comment by mneunomne** [comment]
Already updated, closing
