### ISSUE TITLE
Advertising boxes on petapixel.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1804]
https://petapixel.com/2021/03/18/beijing-silvermine-discarded-unseen-photos-of-china-in-the-80s-and-90s/

<img width="942" alt="image" src="https://user-images.githubusercontent.com/737638/114261385-d93ef900-9a0c-11eb-9ff6-d1a2290c57be.png">

**Comment by mneunomne** [comment]
Wasn't able to reproduce this with my settings. Without Adn the ads do show, so I don't think it's location based.

**Comment by dhowe** [comment]
seems fixed now
