### ISSUE TITLE
Dashboard settings don't update when settings are changed via toolbar

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1806]
When a setting, for example `Activate Ad Hiding` is reactivated from the toolbar menu, it doesn't automatically update on dashboard settings if it is already open, it requires refresh.

![Screen Shot 2021-04-13 at 01 06 51](https://user-images.githubusercontent.com/4967860/114473473-98093d80-9bf4-11eb-87a4-f9f1dafb5b69.png)

![Screen Shot 2021-04-13 at 01 07 10](https://user-images.githubusercontent.com/4967860/114473468-96d81080-9bf4-11eb-9998-5260d5b4ed44.png)

**Comment by dhowe** [comment]
Can add it to current release if there is time while waiting for strictBlocking

**Comment by mneunomne** [comment]
@dhowe this isn't working also on currently published version. I looked into to the code and didn't find where this functionality is actually implemented. I wonder if this was un-implemented at some point of if it stoped working.

**Comment by dhowe** [comment]
Notice that it _does_ work, for example, when EasyList is deactivated on 3rd-party filters, and then is reactivated from the menu: EasyList will be updated on the 3rd party filters page if it is open.

**Comment by dhowe** [comment]
this should be fixed with 662aa5d4020f

please verify

**Comment by mneunomne** [comment]
Fixed, tested with Firefox.
