### ISSUE TITLE
Simple test cases for global and domain-specific strictBlocking

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1807]
@mneunomne we need 2 test-cases for _strictBlocking_ that can be placed on rednoise.org and integrated into our release testing:

- [x] Global strictBlocking: requests from lists, e.g., EasyPrivacy, that would normal be ADN-allowed, are blocked when the `strictBlock` feature is enabled in settings
- [x] Domain-specific strictBlocking: requests to a specific domain from lists that would normal be ADN-allowed,  are blocked when there is a `strictBlock` rule in _My Rules_

**Comment by mneunomne** [comment]
@dhowe I have come up with a same html that can work for both cases. This would be a step-by-step with expected results if it is working.

### Sample html

Simply an iframe requesting two files that is normally ADN-allowed (the original blocking rules comes from EasyList): 
```
<!DOCTYPE html>
<html>
  <head><meta charset="utf-8"></head>
  <body>
    <iframe src="https://tpc.googlesyndication.com/sodar/sodar2/222/runner.html"></iframe>
    <iframe src="https://www.google.com/ads/measurement/l?ebcid=ALh7CaTgdm6I4nAZSMpDelUOKF0q07y1r5sInZMCxjGcQNTKez-JmIlaq7jbFI84MepdZMYj0PCp"></iframe>
  </body>
</html>
``` 

###  Without strictBlocking 

The logger output should have both`||tpc.googlesyndication.com^` and `.com/ads/$subdocument,domain=~sabotage-films.com` being **blue**, which according to the [adn logger](https://github.com/dhowe/AdNauseam/wiki/The-logger) refers to **ADN-allow**: 
![Screen Shot 2021-04-15 at 00 15 21](https://user-images.githubusercontent.com/4967860/114787370-f7478900-9d7f-11eb-9c61-95d30681a6b0.png)


###  With Global strictBlocking (Activate Strict Blocking Mode from the Settings) 

The logger output should result with both `||tpc.googlesyndication.com^` and `.com/ads/$subdocument,domain=~sabotage-films.com` being *red*, which means that they are now  **BLOCKED**:
![Screen Shot 2021-04-15 at 00 14 29](https://user-images.githubusercontent.com/4967860/114787423-147c5780-9d80-11eb-9a31-56c94e0bab12.png)

 
###  Domain-specific strictBlocking

- Make sure Global strictBlocking is **deactivated**
- Create the a `strictBlock` rule for one of the requests in the **My Rules** tab in the dashboard. (In this case the test page domain is `127.0.0.1`) 
```
127.0.0.1 tpc.googlesyndication.com * strictBlock
```  
- Open the logger and the `||tpc.googlesyndication.com^` request should be Blocked **red** , while the other request `.com/ads/$subdocument,domain=~sabotage-films.com` should be still ADN-allow **blue**.

![Screen Shot 2021-04-15 at 00 14 48](https://user-images.githubusercontent.com/4967860/114787652-6f15b380-9d80-11eb-9fc0-85d5e5ccb5f2.png)

**Comment by dhowe** [comment]
strict-blocking.html pages created on red and lamp
