### ISSUE TITLE
Values in Menu not always updated

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1808]
### Values not updated in Menu. 

Values sometimes (most of the time) do not update as they should in the menu. Perhaps this is part of a bigger underlying issue where things are not being updated on-the-fly on the dashboard.  

![Screen Shot 2021-04-14 at 11 58 10](https://user-images.githubusercontent.com/4967860/114692857-4e664300-9d19-11eb-9de9-ff2f6b3abcba.png)

Tested on both Safari and Chrome on latest commit https://github.com/dhowe/AdNauseam/commit/812cce28061faa8cea1384051cab8acda224a763

**Comment by dhowe** [comment]
How is this intermittent?

**Comment by dhowe** [comment]
this bug appears to have been introduced in d230bcf

**Comment by dhowe** [comment]
fixed in 6ae7ab139 @mneunomne pls verify and close

**Comment by mneunomne** [comment]
Verified, seems to be back to normal now.
