### ISSUE TITLE
first-run page not showing up after installed

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1809]
this happens to the current master branch.

To reproduce:
1) build the extension
2) load the extension in the browser
3) settings page pops up instead of first-run

**Comment by dhowe** [comment]
This is intentional for dev-builds (specified via version number containing 3 dots X.Y.Z.A instead of the usual 3).
The usual items (clicking, hiding, blocking, dnt) are selected automatically, and logging is enabled.
Finally the settings page opens instead of the the firstrun page.

**Comment by dhowe** [comment]
If this is ok for you @cqx931 pls close

**Comment by cqx931** [comment]
understood!
