### ISSUE TITLE
Peter Lowe's Ad and tracking server list is missing

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1813]
Peter Lowe's Ad and tracking server list is listed by default for ublock but not for AdNauseam, can't find it under filters.
It's already like this in the currently release but is there a reason why?

<img width="554" alt="image" src="https://user-images.githubusercontent.com/3056154/115107498-7947d580-9f6b-11eb-92dc-39e29f4a29f6.png">

it's hidden and off in our assets.json file but not in ublock's.
our assets.json
https://github.com/dhowe/AdNauseam/blob/master/assets/assets.json#L292

ublock:
https://github.com/gorhill/uBlock/blob/master/assets/assets.json#L246

**Comment by cqx931** [comment]
It's deliberately removed here: https://github.com/dhowe/AdNauseam/issues/913

**Comment by dhowe** [comment]
It was removed from the default set with other lists that result in a high number of blocked, as opposed to hidden, ads. 

Note that it can still be added as a custom list. Full blocking from this list can also be enabled via the [strictBlock setting](https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#what-is-strict-blocking-and-when-should-i-use-it), although (as noted) this will reduce the number of ads that AdNauseam can collect and click.
