### ISSUE TITLE
Not identifying duckduckgo.com as DNT on Firefox

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1814]
### Describe the issue

Duckduckgo is not being identified as DNT in Firefox, but it is on Chrome.

- Visit [duckduckgo.com](https://duckduckgo.com/?q=credit+card&t=h_&ia=web)
- `This page respects DO NOT TRACK` notification doesn't appear on Firefox, but it does on Chrome.
- Ads do not appear on page regardless of weather the option `Don't hide non-tracking Ads` is activated or not. Again, works as expected on chrome but not on Firefox.

### Screenshots

Chrome, working :
![Screen Shot 2021-04-19 at 11 48 02](https://user-images.githubusercontent.com/4967860/115216878-37529700-a105-11eb-8a79-f2583c0ab8cd.png)
![Screen Shot 2021-04-19 at 11 48 17](https://user-images.githubusercontent.com/4967860/115216891-391c5a80-a105-11eb-8756-eb4b06bd14e4.png)

Firefox (no notification and ads are being hidden):
![Screen Shot 2021-04-19 at 11 47 50](https://user-images.githubusercontent.com/4967860/115216909-3de10e80-a105-11eb-8748-c07926e04d8a.png)

### Your settings

- OS/version: Mac OS High Sierra 10.13.6 (17G66)
- Browser/version: Firefox 87.0
- AdNauseam version: Latest commit https://github.com/dhowe/AdNauseam/commit/36da713a8cf74ba662eec133a3d6422aac275cfa
- AdNauseam settings: Standard

**Comment by dhowe** [comment]
Is this the case for other DNT domains as well, or _only_ duckduckgo ?

**Comment by mneunomne** [comment]
After testing some websites from https://github.com/dhowe/AdNauseam/blob/master/thirdparties/www.eff.org/files/effdntlist.txt, I have only detected this issue in the following domain: `https://safenetforum.org/`

**Comment by dhowe** [comment]
These are both working for me in firefox:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/737638/115309362-bfd14600-a19e-11eb-891c-87105e6cfb2a.png">


<img width="968" alt="image" src="https://user-images.githubusercontent.com/737638/115309328-b2b45700-a19e-11eb-9637-0dacb8463d46.png">

**Comment by dhowe** [comment]
Notice also that the top of our "?" is being cut off

**Comment by dhowe** [comment]
These are both working for me in firefox with 662aa5d4020f 
Please verify

<img width="689" alt="image" src="https://user-images.githubusercontent.com/737638/115309362-bfd14600-a19e-11eb-891c-87105e6cfb2a.png">


<img width="968" alt="image" src="https://user-images.githubusercontent.com/737638/115309328-b2b45700-a19e-11eb-9637-0dacb8463d46.png">

**Comment by dhowe** [comment]
Notice also that the top of our "?" is being cut off

**Comment by mneunomne** [comment]
Working now, fixed also the notify-link positioning.
