### ISSUE TITLE
Separate ADN's locale strings from uBlock's

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam#182]
Currently all the locale strings are stored in ``./src/_locales/*/messages.json`` including uBlock's and ADN's own strings. Need them to be separated for easier Crowdin project management.

**Comment by dhowe** [comment]
Pull then look at the two files under src/_locales/en
Then build adn and test that things still work OK

**Comment by dhowe** [comment]
then upload to crowdin

**Comment by CyrusSUEN** [comment]
Crowdin settings updated and now contains 51 languages (same as uBlock). 
Added a script to import ADN locale by ``$ tools/import-adn-crowdin.sh`` after downloading the locale file from https://crowdin.com/project/adnauseam/settings#translations

PR: https://github.com/dhowe/AdNauseam/pull/183/files
