### ISSUE TITLE
[v3.10.1rc3] Ad collection not working in Opera 

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1820]
Ad collection not working at all it seems in Opera v74.0.3911.160, even with the simplest test case. Working normally in *v3.9.201* release. 

Tested in the following pages:
- http://lab-lamp.scm.cityu.edu.hk/adntest/simple.html 
- https://www.bing.com/search?q=credit+card&form=QBLH&sp=-1&pq=credit+&sc=0-7&qs=n&sk=&cvid=46B734872CDB42B1B80A66BE1B6B84D6
- https://www.scientificamerican.com/article/space-junk-removal-is-not-going-smoothly/

**Comment by dhowe** [comment]
any content blocking settings enabled?

**Comment by mneunomne** [comment]
@dhowe Default ones. I tested the exact same browser settings with version v3.9.201 and ad collection works normally.

**Comment by dhowe** [comment]
ok, can you check what is different in the logs?

**Comment by mneunomne** [comment]
Seems like the ads are not being detected by Adn for some reason. Will need to debug in more detail.

### v3.10.1b3

`2core.js:870 [PAGE] https://rednoise.org/adntest/simple.html (0 existing ads)`

### v3.9.201 

```
[FOUND] Ad#2(img) {id: 2, attempts: 0, visitedTs: 0, attemptedTs: 0, contentData: {…}, …}
core.js:869 --Storage Ad Data--
core.js:869 [TRYING] Ad#2(img) http://www.bonhams.com/departments/JWL/
core.js:869 [VISIT] Ad#2(img) Bonhams : Jewellery
core.js:869 --Storage Ad Data--
```

**Comment by mneunomne** [comment]
Should be fixed with https://github.com/dhowe/AdNauseam/pull/1825

**Comment by dhowe** [comment]
confirmed
