### ISSUE TITLE
[v3.10.1rc3] Notifications don't appear immediately in open dashboard right after settings are changed.

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1821]
Notifications don't appear immediately in open dashboard right after settings are changed, but when clicked through "reactivate" the dashboard is updated as expected.

From the Ad Vault the notification are displayed and hidden  immediately as expected.

Occurs both in Firefox and Chrome.

**Comment by dhowe** [comment]
@mneunomne Steps to recreate?

**Comment by mneunomne** [comment]
Simply change settings such as "HIDE ADS" "BLOCK MALWARE" and the corresponding notifications don't show up immediately in the dashboard as they perhaps should. Only after refresh do they show up.

**Comment by dhowe** [comment]
Confirmed. Can check the current version for correct behavior.

**Comment by mneunomne** [comment]
Fixed with https://github.com/dhowe/AdNauseam/pull/1824

**Comment by dhowe** [comment]
verified, nice work
