### ISSUE TITLE
DNT-header is only being sent if Firefox DNT settings are set to "Always"

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1823]
Test page: https://rednoise.org/adntest/cookie-setting-ad.html

Testing in Firefox I was only able to detect the `DNT: 1` in the request header if the `Send web sites a “Do Not Track” signal that you don’t want to be trackedLearn more` was selected as `Always` in the __Privacy & Security__ preferences. Otherwise it does not appear.

**Comment by dhowe** [comment]
this can wait for next release

**Comment by mneunomne** [comment]
I believe this is happening because the following function is not being called anywhere:

https://github.com/dhowe/AdNauseam/blob/6bd2ecdc31aef3e7b74d292201c9f4b125f2dab2/src/js/traffic.js#L65-L102

**Comment by mneunomne** [comment]
Fixed, closing
