### ISSUE TITLE
FirstRun.html on EVERY LAUNCH

### ISSUE THREAD

**Issue by mon5termatt** [dhowe/AdNauseam#1826]
### Describe the issue
firstrun.html ALWAYS SHOWS when launching chrome

### Screenshot in which the issue can be seen

I gotchu fam:
http://cdn.mon5termatt.club/files/gitissue43021.mp4

### Steps for anyone to reproduce the issue
Install On fresh install of chrome
Run Firstrun.html
close Chrome
open chrome
Run Firstrun.html again

### Your settings

- OS/version: Win 10 20H2 (19042.508)

- Browser/version: Google Chrome is up to date
Version 90.0.4430.93 (Official Build) (64-bit)

- AdNauseam version: Latest v3.10.3

- Other extensions you have installed: None (testing environment)

- AdNauseam settings: N/A

**Comment by dhowe** [comment]
verified in opera

**Comment by dhowe** [comment]
potential fix in c4b300e, please verify

**Comment by mon5termatt** [comment]
gonna be honest, I dont know how to build this one.

**Comment by mneunomne** [comment]
Fix verified, closing
