### ISSUE TITLE
Clicking options from extension page brings up blank settings

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1827]
Discovered in Opera. Please also test on FF and Chrome.

![image](https://user-images.githubusercontent.com/737638/116770280-18dd8b80-aa75-11eb-808b-e5b3fb79c9e5.png)

<img width="957" alt="image" src="https://user-images.githubusercontent.com/737638/116770283-1e3ad600-aa75-11eb-8c3b-b6e213f90fa6.png">

**Comment by metapea** [comment]
I've now been getting a similar things in the dashboard after when i click the ''fillter list'' tab (#3p-filter):
![filter list](https://user-images.githubusercontent.com/35351174/130341733-c8cd0be8-ae91-4127-ba1f-ca8926f5395b.png)
and when i click on anything else:
![c](https://user-images.githubusercontent.com/35351174/130341749-07808910-19e5-4c92-b8d4-79b39d9aa62f.png)
 when i click on the ''update'' then ''apply changes'' button:
![u](https://user-images.githubusercontent.com/35351174/130341760-0ebf2bb3-be9d-44d6-a718-155029977f55.png)
Browser: Chromium

**Comment by mneunomne** [comment]
Solved, closing
