### ISSUE TITLE
Check whether DNT list state needs updating (broken in merge1.13.2)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1836]
Code below was commented out after merge with ub 1.13.2, with the following TODO:

      // need a new way to check this (broken in merge1.13.2) ************************

      /* check whether DNT list state needs updating (TODO:)
  
      if (note === ClickingDisabled || note === HidingDisabled) {
  
        //console.log('clicking: ', state, µb.userSettings.clickingAds || µb.userSettings.clickingAds);
        const off = !(µb.userSettings.clickingAds || µb.userSettings.hidingAds);
  
        // µb.selectFilterLists({ location: µb.adnauseam.dnt.effList, off: off })

      }*/

**Comment by mneunomne** [comment]
What does this part supposed to do? I havent really understood it

**Comment by dhowe** [comment]
the DNT list tells us which sites we can whitelist for clicking, hiding or both, because they comply with DNT

what the code above does is to enable that list in settings when it is selected by the user. In pseudocode:

`if (dontClickDNT || dontHideDNT) showDNTlistAsEnabled(true)`

**Comment by mneunomne** [comment]
Is the list selected in the "whitelist" tab in the settings? There are effList in the filter list

![efff](https://user-images.githubusercontent.com/4967860/148646791-63423edc-ccf2-4d85-889e-f409b13a8225.PNG)

**Comment by dhowe** [comment]
Yes

**Comment by mneunomne** [comment]
Ah ok, this is already working actually. We can remove these comments i think
