### ISSUE TITLE
Ads showing up with delay not being collected

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1838]
## Test case
2 types of delayed ads on this html page, one being delayed only the image inside the div that fires the rule `#adunit`, and another one which delays the rendering of the html element that fires the rule itself `#adUn_1`
```HTML
<html>

<head>
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
  <meta content="utf-8" http-equiv="encoding">
  <title>
    Simple Image Ad
  </title>
</head>
<div id=text>
  Image appearing inside ad container after 3 seconds:
</div>
<div id="adunit">
  <a href="http://www.bonhams.com/departments/JWL/"></a>
</div>
<div id=text>
  Whole ad container apparenting in html after 5 seconds:
</div>
<div id="delayed-container"></div>
<script>
  setTimeout(function () {
    document.querySelector("#adunit a").innerHTML += '<img class="img-holder" src="https://rednoise.org/adntest/buyme.png">'
  }, 3000)

  setTimeout(function () {
    document.querySelector("#delayed-container").innerHTML += '<div id="adUn_1"><a href="https://globoesporte.globo.com/"><img class="img-holder" src="https://firstpartysimulator.org/static/images/title.png"></a></div>'
  }, 6000)
</script>
</html>
```

## Issue

Ads are being hidden but not collected in either cases.

This happens because the functions in `contentscript.js` that run when the ads are being added with delay are `surveyPhase1` and `surverPhase3`: https://github.com/dhowe/AdNauseam/blob/7bd1e414f1709bd32e55affc26c240154c90fd4a/src/js/contentscript.js#L1527
https://github.com/dhowe/AdNauseam/blob/7bd1e414f1709bd32e55affc26c240154c90fd4a/src/js/contentscript.js#L1450

But the function that enables us to collect these ads only runs after the page is loaded, which is `bootstrapPhase2` with the following function:
https://github.com/dhowe/AdNauseam/blob/7bd1e414f1709bd32e55affc26c240154c90fd4a/src/js/contentscript.js#L1636-L1646

## Possible solution

The obvious way I found to test and collect these ads was to simply copy the part of the `bootstrapPhase2` call of the `vAPI.adCheck` inside the `surveyPhase3` function. Which will most likely cause a performance issue but I guess we need to find a way to run the querySelectors from the `vAPI.domFilterer` in the `surveyPhase1` or `surveyPhase3` which run when elements are added or updated (apparently).

With this the ads are being properly collected with the delay:
```js
    const surveyPhase3 = function(response) {
        console.debug('[ADN] surveyPhase3', response)
        const result = response && response.result;
        let mustCommit = false;

        if (vAPI.domFilterer) {
            vAPI.domFilterer.filterset.forEach(function(c){
              let nodes = document.querySelectorAll(c.selectors);
              for ( const node of nodes ) {
                  vAPI.adCheck && vAPI.adCheck(node);
              }
            })
          }
```

**Comment by dhowe** [comment]
lets make that into a function and call it from both locations
the think we want to avoid is that it runs many times as many new dom elements are being added
so we may need to add some type of timer check

**Comment by mneunomne** [comment]
I think for this case we should find a real-world case (in preference multiple) so we can make sure we *should* invest time in this improvement. I'll be looking for them.

**Comment by dhowe** [comment]
makes sense

**Comment by mneunomne** [comment]
List of websites for which this solution fixes the ad collection issue:
```
https://www.cpomagazine.com/data-privacy/new-fbi-plans-for-social-media-surveillance-already-raising-significant-privacy-concerns/

```
(will continue to update this list here)

**Comment by dhowe** [comment]
what is the status on this issue?

**Comment by mneunomne** [comment]
Need to get back to work on it, would be nice to have some help to do so, since its a core feature.

**Comment by dhowe** [comment]
happy to, lets discuss tues

**Comment by mneunomne** [comment]
Okay, I found something out. It seems uBlock already has a DOMWatcher actually. 
https://github.com/dhowe/AdNauseam/blob/a1f2c5ca6f11a9e032edd36bd54b88758c7e575f/src/js/contentscript.js#L26-L37

The thing is that when it fires it doesn't run the filters that we need apparently.

I added some logs on the filter set and here it's how it looks:
![Screen Shot 2021-06-01 at 10 06 42](https://user-images.githubusercontent.com/4967860/120289060-2d55b380-c2c1-11eb-8596-0e417f692215.png)
![Screen Shot 2021-06-01 at 10 07 03](https://user-images.githubusercontent.com/4967860/120289068-2fb80d80-c2c1-11eb-97e5-8809132293ce.png)

The first image shows the filters that run right when the page is loaded (and fires the text parser), then the second image shows the filters that run after `domWatcherInterface`, with a huge list of filters, but not catching any to run the parser.

It seems that the specific rules that we need are only being fired when the page is loaded, then the rest of them are indeed firing when the dom changes but doesn't pick up what we need.

**Comment by mneunomne** [comment]
This ugly solution solves it for most of the cases mentioned above, basically repeating the bootstrapPhase1 once again after 2 seconds.
```
setTimeout(() => {
    vAPI.messaging.send('contentscript', {
        what: 'retrieveContentScriptParameters',
        url: vAPI.effectiveSelf.location.href,
    }).then(response => {
        bootstrapPhase1(response);
    });
}, 2000)
```

**Comment by mneunomne** [comment]
@dhowe this is the most basic approach, we can try this out. The problem with the approach of trying to just copy what we need from boostrapPhase1 and 2 to the survey functions. is that `vAPI.domFilterer.filterset` is used on both and its changes actually. So not sure how to work around that. 

PR: https://github.com/dhowe/AdNauseam/pull/1862

**Comment by dhowe** [comment]
this is not ideal, but if commented well we can use it temporarily
can you update the PR with clear comments around that function

**Comment by mneunomne** [comment]
Added this comments: https://github.com/dhowe/AdNauseam/pull/1862/commits/e3c047195bae7c54a9f44a34f5bc51f2bcb27ac8

**Comment by mneunomne** [comment]
@dhowe found a better solution now. It is working with the DomWatcher, but still I needed to add a delay in the bootstrapPhase2 to our function because in the case of duckduckgo.com for example, the delay in which the page appears does not trigger the DomWatcher

https://github.com/dhowe/AdNauseam/pull/1862

**Comment by mneunomne** [comment]
Closing. FIxed with https://github.com/dhowe/AdNauseam/pull/1862

**Comment by mneunomne** [comment]
It seems that in website that the content is always changing dynamically, our parser runs like crazy way too many times, need to find a way to avoid that. Reopening to find a solution.

**Comment by mneunomne** [comment]
Adding a minimal interval of 1000ms between times running `bootstrapPhaseAdn` which is trigger by `DOMChanged` and `DOMCreated`. Also added a maximum of 256 times for this function to run in the given document. Got this number from times `surveyTimer` is allowed to miss:
https://github.com/dhowe/AdNauseam/blob/b179812132c1cd0efb0e938e0533ef031993f4a5/src/js/contentscript.js#L1106-L1110

**Comment by mneunomne** [comment]
Created a separate issue related to it running too many times: https://github.com/dhowe/AdNauseam/issues/1879
Closing this one
