### ISSUE TITLE
Pixelated logo on mozilla page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1839]
![image](https://user-images.githubusercontent.com/737638/117683769-f969ff80-b1e6-11eb-89ac-81b776c65a5b.png)

**Comment by mneunomne** [comment]
@dhowe I assume perhaps you have fixed this yourself? Closing 

![capturesss](https://user-images.githubusercontent.com/4967860/126036175-cf0546d8-28e7-4867-85f9-27f70fea069a.PNG)
