### ISSUE TITLE
Testing of release

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#184]
- [x] check the version number
- [x] test a set of pages for each, and make sure that ads are being captured and visited
- [x] check the menu and the vault
- [x] test import/export/clear functions
- [ ] test that no output is being written to console.log
- [x] check the adnauseam filter list

**Comment by CyrusSUEN** [comment]
Updated the above checklist on clean browser profiles for the release https://github.com/dhowe/AdNauseam/releases/tag/v2.2.0

Everything is good on all browsers except the following:
> test that no output is being written to console.log
On https://www.google.com.hk/search?q=credit+card&oq=credit+card&aqs=chrome..69i57j0l5.1403j0j7&sourceid=chrome&ie=UTF-8
Console messages from:
```
contentscript-end.js:369
extract.js:30
extract.js:71
```

On Vault page:
```
vault.js:1160 Vault-Slider.createAdSets: 5/5 ads
vault.js:108 Vault.doLayout: 5 ad-sets, total=5
vault.js:1436 Vault-slider.filterAdSets: 5/5 ads
```
