### ISSUE TITLE
Mozilla disallows Adnauseam on Firefox mobile

### ISSUE THREAD

**Issue by 2chfl** [dhowe/AdNauseam#1840]
Adnauseam (and many other addons) cannot be installed on mobile Firefox.

**Comment by dhowe** [comment]
We are aware of this, and have written to Mozilla about it. There are no problems with the Firefox/Android version (in fact we've spent much time optimizing it in this version) yet it has still not been made available. Will update if/as we hear back.

**Comment by 2chfl** [comment]
Is there any opportunity to install adnauseam without using addons.mozilla.org?

**Comment by dhowe** [comment]
I'm not 100% sure (would be great if someone wanted to experiment), however this is not Mozilla's intention, as can be seen in this [ticket](https://support.mozilla.org/en-US/kb/unable-install-add-ons-extensions-or-themes) which explicitly includes tests to ensure this is not doable:

> The testing will be focused on:
> 
>     Testing that approved add-ons are visible on the add-ons listing page.
>     Testing that approved add-ons can be installed and uninstalled.
>     Testing that approved add-ons can be enabled and disabled.
>     **Testing that no add-ons that are not approved on Firefox Preview can be installed or enabled.**
>     Testing that add-ons are active when enabled on web pages.
>     Testing that add-ons UI elements are present and functioning as expected in the menu areas.
>     Testing that the approved add-ons function as expected.

**Comment by dhowe** [comment]
Apparently this Mozilla's current policy: absolutely NO extensions can be used in production Firefox, outside of the handful that they have pre-approved. Very disappointing policy on Mozilla's part, as it completely disregards user freedom and autonomy over the browser.

**Comment by thatcatdrout** [comment]
What if we make a webview based AdNauseam

**Comment by dhowe** [comment]
Might be possible: see https://docs.google.com/document/d/1fVLHKh8lmN3rQDyueabReNB11DU0kGmx8UVyeZvmmHc/edit#
Are there existing examples ?

**Comment by thatcatdrout** [comment]
or we make a Firefox mobile fork with AdNauseam hardcoded into it

**Comment by thatcatdrout** [comment]
`postMessage() between app (embedder) and WebView, and vice versa.
This allows an app to communicate with content scripts it has injected into the WebView, and act as a relay between the extension and the WebView.` looks possible

**Comment by thatcatdrout** [comment]
Yes there is some examples

**Comment by dhowe** [comment]
> Yes there is some examples

links?

**Comment by dhowe** [comment]
> I have a idea. We fork the mobile firefox and hardcode the extension into the source code

a possible option, especially if we can simply modify the list of 'approved' extensions...

**Comment by dhowe** [comment]
another option is to use fennec from f-droid store - needs to be tested

**Comment by thatcatdrout** [comment]
> > Yes there is some examples
> 
> links?

my browser is weird and does not want me to copy links

**Comment by thatcatdrout** [comment]
[](https://media.discordapp.net/attachments/933390150694731789/934424944018866226/Screenshot_20220122-132959.jpg) I found how we can do this

**Comment by dhowe** [comment]
How does downloading the file help?

**Comment by thatcatdrout** [comment]
We could code that the app could import the file into the mobile browser.
Like a firefox developer mode to import addons

**Comment by thatcatdrout** [comment]
> > I have a idea. We fork the mobile firefox and hardcode the extension into the source code
> 
> a possible option, especially if we can simply modify the list of 'approved' extensions...

we will use your method to bypass restrictions

**Comment by thatcatdrout** [comment]
> > I have a idea. We fork the mobile firefox and hardcode the extension into the source code
> 
> a possible option, especially if we can simply modify the list of 'approved' extensions...

Where is the list located at the repo.

**Comment by dhowe** [comment]
good question... repo is here: https://github.com/mozilla-mobile/fenix

**Comment by FrostKnight** [comment]
> another option is to use fennec from f-droid store - needs to be tested

Actually, forget Fennec f-droid, there is a better one in the f-droid store, called Mull

I would know, someone showed this to me a while back, like a month or so ago.

;)

**Comment by Oporman** [comment]
👍

**Comment by mneunomne** [comment]
AdNauseam is available on Firefox at the moment. Closing.
