### ISSUE TITLE
Filters not being injected in dynamically created iframes

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1860]
It *seems* that we are not being able to add all the filters we need inside empty src iframes.

[This is a theoretical test case](http://lab-lamp.scm.cityu.edu.hk/adntest/dynamic_iframe.html). But it seems to be not hiding on Chrome and on Firefox the ad is not even rendered for some reason (might be an issue with the test script). 

I *suspect* this is related to this issue: https://github.com/dhowe/AdNauseam/issues/1844

**Comment by mneunomne** [comment]
This should be dealing with this in theory, but this line is never reached when we need it to be.
https://github.com/dhowe/AdNauseam/blob/709a8eb6429812207eaf948a0fada8f473d5c6df/src/js/contentscript.js#L1530-L1539
because `result` is null. 
https://github.com/dhowe/AdNauseam/blob/709a8eb6429812207eaf948a0fada8f473d5c6df/src/js/contentscript.js#L1498-L1511

**Comment by mneunomne** [comment]
We need a test case to confirm this behavior:

> **2. IFrames**
> 
>  If an iFrame matches a cosmetic selector and has a valid 'src' attribute, `processIFrame()` is called. If the iFrame's 'src' and parent page have the same origin, `processIFrame()` selects all images within the iFrame and handles them as above. If the iFrame is cross-domain, however, we will not be able to access its contents due to "Same Origin" security restrictions. In this case, we may need to manually create a new cosmetic filter for the element of interest _inside_ the  the iFrame (and add it to adnauseam.txt).
> If, on Chromium-based browsers, an iFrame is dynamically-generated, the `primeLocalIFrame()` function attempts to inject the usual contentscripts into the iFrame (this will happen automatically on Firefox).  If the injection is successful, a console message in the addon console will read as follows:
> `[INJECT] Dynamic-iFrame...`
> You may inspect the [pageStore object](https://github.com/dhowe/AdNauseam/blob/master/src/js/pagestore.js) to find more information about the iFrame.

**Comment by mneunomne** [comment]
Some info can be found in this discussion as well: https://github.com/gorhill/uBlock/issues/1740

**Comment by dhowe** [comment]
this relates to dynamically created iframes, correct?

**Comment by mneunomne** [comment]
It seems that indeed this seems to be happening. As you can see uBlock injected the content script in the `about:blank` iframe windows, while Adn did not. 

uBlock Origin:
![French Open 2021 Stream Free - Google Chrome 09 06 2021 11_07_26](https://user-images.githubusercontent.com/4967860/121326905-412d9500-c913-11eb-9a8f-f99ced51dc62.png)

Adnauseam:
![Windows 10 Screenshot - So erstellen Sie Screenshots in Windows 10 - IONOS - Google Chrome 09 06 2021 11_07_12](https://user-images.githubusercontent.com/4967860/121326927-4559b280-c913-11eb-849f-b46573e1e9aa.png)

**Comment by mneunomne** [comment]
@dhowe found another example:

I can confirm this is happening since when thying to hide the ad above in Adnauseam, doesn't matter how much i add blocking filters even with `$important` they are not blocked. 

I'm adding a high priority since this is the cause of a huge amount of ads appearing with Adnauseam.

Adnauseam, ad frame `about:blank` with no injected content script:
![Mazy Streams _ Stream 1 - Google Chrome 6_14_2021 12_19_47 PM](https://user-images.githubusercontent.com/4967860/121877599-12e0f880-cd0b-11eb-8dcf-f2791a38f036.png)

in uBlock Origin, ad frame `about:blank` and content script injected.
![Mazy Streams _ Stream 1 - Google Chrome 6_14_2021 12_23_21 PM](https://user-images.githubusercontent.com/4967860/121877828-56d3fd80-cd0b-11eb-80d5-9276671bd90f.png)

**Comment by mneunomne** [comment]
At least in the case of chrome it was suposed to be happening here:

https://github.com/dhowe/AdNauseam/blob/5ada7ba857e7c759d91e6879d1d64701bf155f30/platform/chromium/vapi-background.js#L1416-L1420

**Comment by mneunomne** [comment]
Tested, closing
