### ISSUE TITLE
Edge Chromium Store not uptodate

### ISSUE THREAD

**Issue by ganhiru** [dhowe/AdNauseam#1861]
The AdNauseam plugin on the Edge Chromium Store is out of date:
Version 3.9.2
27 august 2020
https://microsoftedge.microsoft.com/addons/detail/adnauseam/mlojlfildnehdpnlmpkeiiglhhkofhpb?hl=nl

### Steps for anyone to reproduce the issue
Install AdNauseam via the Edge Chromium extentions store

### Your settings

- OS/version: Edge Chromim
- Browser/version: 91
- AdNauseam version: 3.9.2
- Other extensions you have installed:
- AdNauseam settings:  default

**Comment by dhowe** [comment]
@mneunomne can we get this updated and integrated into our build/release process ?

**Comment by amanhigh** [comment]
Facing Youtube issue maybe due to out of date build which is 3.9.2

**Comment by dhowe** [comment]
The update has been submitted to the Edge store -- just waiting on approval from Microsoft

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/737638/120888844-23b7ad00-c62d-11eb-8eb0-4d7d6c7003c1.png">

**Comment by amanhigh** [comment]
Things are working fine on youtube after the latest edge update. Thanks for the upload

**Comment by dhowe** [comment]
For anyone else interested, here is the link to [AdNauseam in the Edge store](https://microsoftedge.microsoft.com/addons/detail/adnauseam/mlojlfildnehdpnlmpkeiiglhhkofhpb?hl=en-US)
