### ISSUE TITLE
Package is invalid: 'CRX_REQUIRED_PROOF_MISSING'

### ISSUE THREAD

**Issue by ganhiru** [dhowe/AdNauseam#1863]
### Describe the issue

Installation via GPO on Chrome and Edge chromium does not work anymore.
Manual Installation ( By dragging the crx on to the Settings tab ) throws an "crx_required_proof_missing" error.

Even with , ExtensionInstallSources , ExtensionInstallWhitelist , ExtensionInstallForcelist GPO settings configured.
and ExtensionAllowInsecureUpdates GPO setting on 1 ( Chrome seems to have used this in the past )

Installing AdNauseam in developer mode works without issues.

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/39408/120592111-995d2680-c43d-11eb-84a2-416f6e1b33ff.png)

### Steps for anyone to reproduce the issue
Download a .crx build from https://github.com/dhowe/AdNauseam/releases , 
Open Settings
Drag the .crx file from your download folder to the Settings tab

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Edge Chromium, Google Chrome v91
- AdNauseam version: v3.10.4 , tested with crx files down to v3.9.200
- Other extensions you have installed: none
- AdNauseam settings: default

### Thoughts
_Google Groups Post: ExtensionInstallForceList won't install extension in 75_ https://groups.google.com/a/chromium.org/g/chromium-extensions/c/3fvSNKUe3s0
On this topic the suggestion is that the CRX version needs to be 3

_Edge Chromium extension issue "Package is invalid: 'CRX_REQUIRED_PROOF_MISSING'" #102_ https://github.com/erickutcher/httpdownloader/issues/102
This issue with an other extention, suggests it's a lack of a hosted Privacy Policy url the crx.

**Comment by dhowe** [comment]
Can you provide a link to another extension NOT in the chrome store that installs correctly from a .crx ?
