### ISSUE TITLE
YouTube no longer functioning

### ISSUE THREAD

**Issue by Reeceeboii** [dhowe/AdNauseam#1865]
### Describe the issue

When AdNauseam is enabled, YouTube videos either fail to load completely or display an incorrect offline message.

### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/42159320/120817140-5a1bfc00-c549-11eb-8c87-2ab7fa70a3ec.png)
![image](https://user-images.githubusercontent.com/42159320/120817147-5be5bf80-c549-11eb-9de8-9f0f706807da.png)

### Steps for anyone to reproduce the issue
Open Edge, go to YouTube, click on any video in the recommended feed, it fails to play as in the screenshots above. Disabling AdNauseam allows playing to resume as expected.

### Your settings

- OS/version: Windows 10 Education 20H2 build 19042.1023
- Browser/version: Microsoft Edge (Chromium) 91.0.864.37
- AdNauseam version: AdNauseam v3.9.2 uBlock Origin v1.29.0
- Other extensions you have installed: Bitwarden, React dev tools, custom new tab URL
- AdNauseam settings: In attached zip
[AdNauseam.zip](https://github.com/dhowe/AdNauseam/files/6599190/AdNauseam.zip)

##### Your filter lists
![image](https://user-images.githubusercontent.com/42159320/120817074-4a9cb300-c549-11eb-9142-67c35e7a00cc.png)

### Your location/country
United Kingdom

**Comment by TheodoreHua** [comment]
Happens to me as well.

- OS/version: Windows 10 Pro for Workstations Version 2004 Build 19041.985
- Browser/version: Google Chrome Version 90.0.4430.212
- AdNauseam version: AdNauseam v3.9.201 uBlock Origin v1.29.0
- Other extensions you have installed: This is a long long list, but I've tested my browser using just AdNauseam and the issue happens, without it, it goes away.

**Comment by sarahkittyy** [comment]
Updating to AdNauseam v3.10.4 fixed it for me.

**Comment by Reeceeboii** [comment]
> Updating to AdNauseam v3.10.4 fixed it for me.

This solved it!
