### ISSUE TITLE
Youtube plays dead with AdNauseam enabled (on Vivaldi/Chromium)

### ISSUE THREAD

**Issue by Arbitrary** [dhowe/AdNauseam#1866]
### Describe the issue
with AdNauseam on, youtube stops loading before displaying any content - the youtube logo, the search bar, and otherwise a blank page as visible in the screenshot linked.
Turn AdNauseam off on youtube, and youtube resumes functioning just fine.

### Screenshot in which the issue can be seen
https://cdn.discordapp.com/attachments/247270968899141633/850647613559537674/unknown.png

### Steps for anyone to reproduce the issue
Install AdNauseam, go to youtube.com and try to watch a video - it will fail and show a blank page
Pull up AdNauseam's dialog and disable it on the blank youtube page. Refresh and watch as it works like magic.

### Your settings

- OS/version: Windows 10 Home, 20H2
- Browser/version: Vivaldi (version: literally the one it would update you today as of this posting, can't find the number rn)
- AdNauseam version: AdNauseam v3.9.201 uBlock Originv1.29.0 
- Other extensions you have installed: Cluster Window & Tab Manager, Feedbro, Fraidycat, Mercury Reader, Midnight Lizard, NoScript, RedditEnhancementSuite, Reddit Masstagger, RSS Subscription Extension (by Google), Shinigami Eyes, SponsorBlock for YouTube, TamperMonkey (no relevant scripts to speak of)
- AdNauseam settings:

##### Your filter lists
Default filter lists (everything on the filter page checked and no other actions taken)

### Your location/country
East Coast, USA

** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

**Comment by amanhigh** [comment]
Facing same issue with slightly different error.

OS: Windows 10 20H2
Browser: Edge (Latest)

![SNAG--2021-06-05-007](https://user-images.githubusercontent.com/409973/120887118-bf85f080-c60e-11eb-89c0-4133c2eb9f5b.jpg)

**Comment by Arbitrary** [comment]
> Facing same issue with slightly different error. Disabling extension restores youtube play.
> 
> OS: Windows 10 20H2
> Browser: Edge (Latest)
> 
> ![SNAG--2021-06-05-007](https://user-images.githubusercontent.com/409973/120887118-bf85f080-c60e-11eb-89c0-4133c2eb9f5b.jpg)

Have actually seen this variation - I dunno what it is exactly but vivaldi won't apply any extensions or scripts to the first page loaded on start (not here to litigate that issue), but when it does that on youtube and I turn adNauseam on I get your error instead of the one I posted. So, almost definitely related.

Potentially useful note - I installed uBlock Origin straight off the chrome store and youtube is not playing dead, so it's something specific to AdNauseam afoot.
Not saying they've found a way to target AdN specifically but it sure feels like they have.

**Comment by dhowe** [comment]
Thanks for the report. We are aware of this issue and it should be resolved in the new version of AdNauseam (3.10.4). Can you try installing this and let us know if it solves the problem? thanks

**Comment by Arbitrary** [comment]
After some futzing about (turns out Vivaldi is close enough to Chromium you need to use the zip, I'd forgotten since it's been a while), I can at least tentatively say that 3.10.4 has fixed the issue. I'm not gonna close it myself just yet, just in case anyone's got any last words they need to say about the matter.

Curious why this only just started happening to me, if apparently this has been known for so long that it's already got a fix up, but it's just curious,.

**Comment by dhowe** [comment]
Not sure why either, but we've only started getting reports of this in the last few days.

**Comment by NiteSite** [comment]
3.10.4 100% fixed my issue I was also getting the You're offline Thank you!!

**Comment by dhowe** [comment]
closing for now
