### ISSUE TITLE
Double-check installation details for Edge/Brave

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1867]
here: https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission

**Comment by jaw-sh** [comment]
To clarify, it is definitely possible to install AdNauseum on Brave. On Manjaro, I was able to drag+drop the crx file into the extensions page and it installed successfully. The help page that the wiki links to citing Brave does not support custom extensions not available via the Chrome store says the opposite now.

**Comment by mneunomne** [comment]
I am able to drag and drop the crx fie in Brave but not able to active it, it remains "off" and can't activate it.

![Brave](https://user-images.githubusercontent.com/4967860/122928622-58846d80-d36a-11eb-87b6-6c6e58e55aff.PNG)

**Comment by mneunomne** [comment]
@dhowe drag+drop the .crx doesnt seem to work on any chromium based browser for me in windows at least, It is added but I can enable it. Only unzipping then using the "load unpacked" seems to be working.

**Comment by dhowe** [comment]
right, pls update docs and close

**Comment by mneunomne** [comment]
Updated the Wiki, closing
