### ISSUE TITLE
Failed ad collection at ebay-kleinanzeigen.de

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1868]
### Failed ad collection at ebay-kleinanzeigen.de

Pages at ebay-kleinanzeigen.de have wrongly collected elements, picking up the placeholder image and failing with the link:

https://www.ebay-kleinanzeigen.de/s-anzeige/sun-sea-kayak-defekt-/1790066699-230-2645

**gescheitert = failed**

![incorrect](https://user-images.githubusercontent.com/4967860/121056392-71175400-c7be-11eb-9bc8-b364fc852435.PNG)

**Comment by dhowe** [comment]
is this a false positive for something that is not an ad, or an unsuccessful visit?

**Comment by mneunomne** [comment]
Inspecting it closer it is actually just a false visit. The no picture is part of the ad itself. 

![kein-bild](https://user-images.githubusercontent.com/4967860/121070081-901de200-c7ce-11eb-99b5-6c827815f3bf.PNG)

**Comment by mneunomne** [comment]
It seems that now the ad visit is occouring correctly. It seems like it was an issue with the website instead. Closing for now.
