### ISSUE TITLE
Confusing first results

### ISSUE THREAD

**Issue by patfla** [dhowe/AdNauseam#1886]
### Describe the issue

New to AdNauseum.  Installed into latest FF on Windows 10 and checked against
nytimes.com and bbc.com/news.  AdVault shows 10 and 5 ads respectively and so I figure, OK, it's working.

I'm a recently retired developer, was curious how it works, and so built the extension
for Firefox in WSL2 which is an MS subsystem for Linux running, in my case, Ubuntu.  Ran
with web_ext run - check the same two pages - no ads collected at all.  What might the FF debugger
console tell me?

https://imgur.com/a/3ZovVZM

Not sure what to make of that.

Chrome's tends to be the best supported browser and maybe I'll have the most tools with which to look at this
and I should try Chrome, on Windows, anyway.  0 ads collected for either nytimes.com or bbc.com/news.  Although
this is what I find when I look in the Chrome debugger console and are ads in fact being intercepted?

https://imgur.com/a/DcUy2st

I speculate because of the net::ERR_BLOCKED_BY_CLIENT messages I see - attached to urls that look like they
might be ad-related.

Have poked around a little here in Issues to see what's going on and found and tried

https://rednoise.org/adntest/simple.html

which doesn't seem to work either in Chrome on Windows.

https://imgur.com/a/94WyCQJ

### Screenshot in which the issue can be seen

several above.

### Your settings

- OS/version: 10.0.21390 N/A Build 21390
- Browser/version:  FF Windows 89.0.2   FF Ubuntu 89.0.2  Chrome Windows 91.0.4472.124 (Official Build) 
- AdNauseam version: latest
- Other extensions you have installed:  a lot but turned adblockers off.
- AdNauseam settings:  default - haven't changed.

##### Your filter lists

Haven't set any filters.

### Your location/country

US

**Comment by patfla** [comment]
Read around some more and experimented further with my different combinations.  Behavior is now consistent in that ADN appears not to work in the same places regardless of browser and OS.  That means for one, that ADN successfully collects ads on some sites, but not others.

Seems one can satisfy Needs-verification with a [failed] browser console log.  Nytimes:

https://gist.github.com/patfla/90c7e2ef593f8f61091c4ddef55389ae

With as I said more experimentation, I think what I'm seeing is #1778 - which seems to have gone quiet as of May 14th.

That is, https://rednoise.org/adntest/simple.html and https://www.atptour.com/ work but sites, that I visit more frequently, like https://nytimes.com and https://bbc.com/news don't collect ads.  So this is maybe a dupe of #1778.

Probably naively, as I scan [PARSER] messages what I think I see is that ADN doesn't find ad images.

**Comment by dhowe** [comment]
Thanks @patfla - is it the case that there are two potential issues here, A) ads not being found when run via web-ext, including simple test pages, and B) ads not being found on sites ? Or is B) now the only issue?

**Comment by patfla** [comment]
Hi @dhowe,

Hadn't gone back to web-ext (ADN version I built) in a while because Windows Insider upgraded me to Windows 11 several days ago - and hadn't used (updated) wsl.

Doing so now I see the same behavior there as on Windows.  Simple sites work - more complex ones don't collect ads.  Same examples I gave above (2 for each case).

The only (or main) reason I'm using wsl (Linux) is that it seemed to me the extension might build better on Linux.  Other than that I don't necessarily care a whole lot.  (although I do much prefer developing on Linux than on Windows ...)

So, in short, B only.

> But for similar cases where ads are being hidden/blocked but not collected, we generally need to know the following information for the ad/site:
> 
>     1. browser/os/adnauseam versions
> 
>     2. the page URL
> 
>     3. screengrab of the ad on the page
> 
>     4. your access location (in case the page is different for different regions)
> 

1.  Firefox 89.0.2 on Microsoft Windows [Version 10.0.22000.51]  (Windows 11 prerelease)  AdNauseum is the latest released version ... which seems to be 3.10.4.
2. https://www.nytimes.com
3. Uh, I'm confused - uBlock is working and suppresses visible ads.  I see, as best I can tell, no visible ads on https://www.nytimes.com.
4. US.

**Comment by dhowe** [comment]
> Uh, I'm confused - uBlock is working and suppresses visible ads. I see, as best I can tell, no visible ads on https://www.nytimes.com.

Right, so to see the add you would have to update disable AdNauseam on the site via the menu icon

The build process for Linux has not been tested in some time, as we have been building on OS X. If you wanted to help with testing this, it would be great. I don't think Windows is (or will be) supported for building from source...

As for the New York Times (and sites structurally similar), the issue has been addressed and is just waiting for the next release, which should be within a few days.
