### ISSUE TITLE
Test with DuckDuckGo Extension

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1887]

**Comment by mneunomne** [comment]
Tested with DuckDuckGo Extension in Firefox and it seems like it doesn't affect Adnauseam. Ad collection and visits seems to work fine.

**Comment by mneunomne** [comment]
@dhowe is there something specific you want to get tested ?

**Comment by dhowe** [comment]
I'm specifically interested in the following functionality in the DDG extension:

> Escape Online Tracking — block hidden trackers lurking on the websites you visit (e.g., when you click on search results). Stop companies behind those trackers before they use sneaky tactics to try to collect and sell your data. 

If DDG is blocking trackers (e.g., Google ads) then ADN will likely not be able to collect those ads...

**Comment by mneunomne** [comment]
@dhowe I just tested again and ads from google are still being collected.
![Capture](https://user-images.githubusercontent.com/4967860/125790780-45bad60f-9d9a-43db-ac75-93e0c3414642.PNG)

If this is the case we wouldn't need a warning for this extension i guess...

**Comment by dhowe** [comment]
closing for now -- lets keep an eye on this
