### ISSUE TITLE
Pages on hookandbullet.com don't load

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1889]
https://www.hookandbullet.com/s/fishing-new-york/

<img width="746" alt="image" src="https://user-images.githubusercontent.com/737638/124393368-307cfe80-dcc8-11eb-991a-f451f870f0be.png">

**Comment by mneunomne** [comment]
Cannot reproduce in my system, currently using windows. @dhowe perhaps good describe if you are using your profile with thousands of ads collected or the a clean one

**Comment by dhowe** [comment]
Fixed in current ADN (when building from source)
