### ISSUE TITLE
900 ads on nytimes.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1890]
This seems incorrect

![image](https://user-images.githubusercontent.com/737638/124519058-3a7d2b00-ddb6-11eb-8a15-7e13bf017e7c.png)

**Comment by chirag127** [comment]
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/124824118-9353eb80-df8f-11eb-96f5-9df6658db669.png)


</details><br/>
only 3 for me on default settings.

**Comment by dhowe** [comment]
closing for now, possibly an artifact of a particularly large vault
