### ISSUE TITLE
Clarify FAQ for ad processing in iframes

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1892]
Seems this info may be outdated, can you give a check @mneunomne 
https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#how-does-ad-parsing-work

**Comment by mneunomne** [comment]
It seems that this is still relavant, but perhaps now I should add the information regarding the contentscript and the dom-watcher events.

**Comment by mneunomne** [comment]
Added this segment: https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#when-is-the-ad-parser-fired

And changed the part of the dynamic iframe which was out of date.
