### ISSUE TITLE
Facebook marketplace ads no longer blocked

### ISSUE THREAD

**Issue by giantofthenorth** [dhowe/AdNauseam#1894]
a few days ago ads started appearing again in Facebook marketplace as listings as shown below
![annoying](https://user-images.githubusercontent.com/87623541/126097088-b7baf21f-0231-41d4-9d54-1589b63ac9c6.PNG)

### Your settings

- OS/version: win 10
- Browser/version: firefox v90
- AdNauseam version: was updated as of today
- Other extensions you have installed: disconnect.me, duck duck go privacy, facebook container,

##### Your filter lists
Default filter lists + FRA, facebook annoyance blcoker

**Comment by mneunomne** [comment]
@giantofthenorth thanks for the feedback, but unfortunatelly this is not Adn specific. The same is occuring with uBlock Origin which is what we are based on in this case. This tends to be a cat and mouse situation and it takes a little bit sometimes for the ublock filters to be updated when facebook changes their html structure. 

Same behavior with uBlock origin (Patrocinado = Sponsored):
![not-adn-specific](https://user-images.githubusercontent.com/4967860/126200093-4a11ba7c-c194-4e56-9f71-d5fa57634ef9.PNG)

If you want you can submit an issue into their repo as well :)))
https://github.com/gorhill/uBlock
