### ISSUE TITLE
Check operations in private-mode

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#190]
Please verify this statement from out privacy policy in all browsers:

"Whenever you use a 'Private Browsing' window in your browser, AdNauseam is disabled for that window and no information about that window is stored"

**Comment by CyrusSUEN** [comment]
> Whenever you use a 'Private Browsing' window in your browser, AdNauseam is disabled for that window and no information about that window is stored"

This is false currently.

ADN2 works as usual in Private Mode on all browsers. Please note that for Chrome and Opera users have to manually enable it in chrome://extensions page to allow it Private Mode.

**Comment by CyrusSUEN** [comment]
We could simply make ADN unavailable in Private Mode by specifying the manifest file

> Use the "incognito" manifest key with either "spanning" or "split" to specify how this extension will behave if allowed to run in incognito mode. Using "not_allowed" to prevent this extension from being enabled in incognito mode.

https://developer.chrome.com/extensions/manifest/incognito

**Comment by dhowe** [comment]
We need to discuss. For now, I have removed that line from our privacy policy...
