### ISSUE TITLE
First-run page shows every launch (OperaGX)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1901]
From email:

> First, I want to apologize for any mistake I will make in this mail. I have an issue with Adnauseam (which I am really thankful for your work), everytime I launch OperaGX ; Adnauseam keep asking me to select what I want to block like it’s the first time I’m using it. I don’t know why this issue occur but I tried reinstalling it and it doesn’t work. I didn’t tried on another browser tho. I’m using all lastest version of both Adnauseam and OperaGX. 

Verified (with v3.10.3 only, new release has not yet been approved in Opera store). 

Actually there are several similar reports on the page for generic Opera, so this is likely not related to OperaGX. However, it appears to have been fixed in the current release (which is not yet available).

**Comment by dhowe** [comment]
@mneunomne can you test this on opera with the current release?

**Comment by mneunomne** [comment]
@dhowe I did the tests with Opera on our current release 3.11.4 and was not able to detect this issue. Tested both with Windows and Mac

**Comment by dhowe** [comment]
thanks, closing with a note that this IS a problem in version 3.10.3 of AdNauseam, but has been FIXED in 3.11.4. Opera users will either need to manually update or wait through the rather slow approval process for the Opera store.
