### ISSUE TITLE
Ads visible on businessxm.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1907]
https://businessxm.com/
![image](https://user-images.githubusercontent.com/737638/127725092-eeaae0a7-d1f1-49ef-bb66-12d954fd64ae.png)

**Comment by mneunomne** [comment]
These types of ads are the ones that most often appearn in adn, the fake notification ones. We cant collect them because their DOM structure is complely dynamically constructure with no class or id pattern. So the only choice is to block the javascript that generates it.

**Comment by mneunomne** [comment]
Website not working any longer... 

![asasdsdaasd](https://user-images.githubusercontent.com/4967860/130440165-e6016f05-0d15-4628-82d3-cfd2564057ab.PNG)
