### ISSUE TITLE
Error after rebuild

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1916]
I'm getting this error after I re-build Adn sometimes on the current master, which makes the Filter lists tab go blank. After I reset the settings it comes back working as usual.

Chrome gives this error when I reload adnauseam on  the add-ons page:

![error_chrome](https://user-images.githubusercontent.com/4967860/129105206-6cad256e-6de0-4098-a376-2c0b7c888025.PNG)

**Comment by dhowe** [comment]
@mneunomne is this still happening? 
I don't see anything in that code that looks like a potential bug.
Though we should probably be using `Object.assign `instead...
