### ISSUE TITLE
Vault: Font incorrect for 'Visited' text?

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1917]
To recreate, open vault, go to page with ads, watch vault for when the ad is visited

Not sure if this is an actual issue

![image](https://user-images.githubusercontent.com/737638/129297227-d6062559-a506-4401-935a-b74efbfe3aa5.png)

**Comment by mneunomne** [comment]
The font before was not loaded actually, I changed it because before it was going to the default Times-new Roman, i changed it to Helvetica. https://github.com/dhowe/AdNauseam/issues/1898
Commit: https://github.com/dhowe/AdNauseam/pull/1900/commits/0255399ff168d67ee83422630e2ec53c8fed86e3
