### ISSUE TITLE
Can I disable AdNauseam for local subnet w/o having to disable each site/IP manually?

### ISSUE THREAD

**Issue by TubaOrNotTuba** [dhowe/AdNauseam#1922]
### Discussed in https://github.com/dhowe/AdNauseam/discussions/1921

<div type='discussions-op-text'>

<sup>Originally posted by **TubaOrNotTuba** August 14, 2021</sup>
I find AdNauseam blocking functionality of local subnet sites, especially network management sites.  With everyone having at least one of these, their router, but in my case a couple dozen that I use for testing and project building, is there a way to disable AdNauseam from doing anything on any site on the local subnet.  I tried adding 192.168.0.0/23 to the whitelist page but that didn't do any good.  Thoughts?</div>

**Comment by dhowe** [comment]
Thanks for the question. 
I think you'd need to ask this on the uBlock origin issues board:  https://github.com/gorhill/uBlock/issues
We use their white-listing mechanism pretty much as-is...
