### ISSUE TITLE
AdNauseum seems to be interfiering with YouTube wathcing history

### ISSUE THREAD

**Issue by CodedSakura** [dhowe/AdNauseam#1923]
### Describe the issue

YouTube seems to be unable to update watching history while AdNauseum is enabled. Disabling AdNauseum loads in all watched videos.

Note: I applied for the free trial of YouTube Music on 17th, and started noticing the issue on 19th. (I don't think the events are related, but just in case..)

### Steps for anyone to reproduce the issue

- Open YouTube
- Enable AdNauseum
- Watch a video
- Wait about 10 seconds
- Navigate to History tab
- Observe that it does not appear in the History tab
- Disable AdNauseum
- Refresh the History page
- Wait about 10 seconds
- Refresh the History page again
- Observe the watched video appear

Note: if you navigate to the History page while watching a video with AdNauseum off, you can already see it there before the video even has ended.

### Your settings

- OS/version: Ubuntu 21.04 / Kernel 5.11.0-18-generic
- Browser/version: Google Chome 92.0.4515.131
- AdNauseam version: 3.11.4
- Other extensions you have installed: BitDefenter, JetBrains Toolbox Extension, React Dev Tools, Wayback Machine
- AdNauseam settings: Hide adds (excl. DNT), Always Click adds (excl. DNT), Block malware; first 3 checked in Extra Privacy,
 nothing checked under Default Behavior

##### Your filter lists
Default filter lists

### Your location/country
Europe, Latvia

**Comment by CodedSakura** [comment]
Interesting.. the problem seems to be gone now... I haven't changed anything, maybe some filter lists updated?

**Comment by dhowe** [comment]
Possible. Closing for now, but let us know if the problem reappears
