### ISSUE TITLE
Сonstantly pop-up window with the extension settings every time you open Yandex browser

### ISSUE THREAD

**Issue by Sekktor21** [dhowe/AdNauseam#1926]
Hello. There was such a problem-a constantly pop-up window with the extension settings every time you open Yandex browser. I understand this is a bug of version 3.10.3. This has been fixed in version 3.10.4. Is it possible to add a newer version to the Yandex Browser extensions catalog? I attach a screenshot. I added a new version manually, this problem disappeared there,but the request to enable this extension is constantly displayed(it is not convenient to constantly enable it).
![Безымянный](https://user-images.githubusercontent.com/89397422/130455493-ed81ccca-0870-4c97-bd53-949c8b1537a4.png)

**Comment by mneunomne** [comment]
@Sekktor21 I realized that the Yandex extension catalog is following Opera's. For some reason they are taking very very long time to approve our updates. We will get back to you as soon as they accept it. Thanks for the heads up!

**Comment by dhowe** [comment]
@Sekktor21 the update has happened in the Opera store so should update on the yandex store very soon...
