### ISSUE TITLE
Verify permissions requested on Firefox install

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1929]
Need to verify that we are requesting the miminal set of permissions needed for ADN to function

Via Twitter:
"if I’m trying to keep big tech from my data or at least give them a headache how does it help me to give AdNauseum access to all passwords and data? I want my privacy that’s the whole point. Can you explain it for us smooth brains? 

...I was referring to the permissions - access data across all websites. Firefox explains it as access to everything including passwords and more. It was very confusing."
"

**Comment by dhowe** [comment]
I see the following on Firefox install.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/737638/132627067-66f20837-1de3-494f-928a-c87493e74c2b.png">

**Comment by mneunomne** [comment]
Going through our list of permission in comparisson with uBlock Origin, the only difference is that we have **Management**, which according to [documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API):
```
management
Get information about installed add-ons.
```
We can go through our permissions to see what we actually need. But I would *guess* if uBlock has it, we probably need it.

**Comment by dhowe** [comment]
Can you double-check the install procedure on FF and chrome, and compare what the user sees on install of ublock and adn ( quick screenshot should be fine) ?

**Comment by mneunomne** [comment]
Firefox:
![firefix-installPNG](https://user-images.githubusercontent.com/4967860/133924902-707df048-dbb2-4678-9f9f-3b787876e3d3.PNG)

Chrome doesn't really say anything, only these info on the description:
```
Berechtigungen:
- Browserverlauf lesen (read browser history)
- Apps, Erweiterungen und Designs verwalten (administer apps, extensions, design)
- Datenschutzeinstellungen ändern (Change data-protection settings)
```

**Comment by dhowe** [comment]
where does "read modify privacy settings' come from?

**Comment by mneunomne** [comment]
`privacy` permission I believe

**Comment by dhowe** [comment]
**Read and modify privacy settings**

The extension could change privacy related settings controlling:

  
-   Network behavior
-   Whether passwords are stored in the browser’s password manager
-   The way the browser interacts with websites 

Extensions requesting this permission might:

-     Disable browser storage of passwords as part of an enhanced password manager
-     Help protect your privacy by managing the information made available in real-time chat and video applications
-     Offer additional tracking protection features

**Comment by mneunomne** [comment]
@dhowe we need this permission to check the Firefox privacy settings. We have the warning when the FF privacy settings are set in "strict" mode. uBlock also requires it so I imagine there are other things that make use of this permission.

**Comment by dhowe** [comment]
I see -- so the only difference, is as you say above, "Monitor extension usage and manage themes", which we use to check for potential conflicts with other addons. 

Unfortunate these permissions are so un-granular that it is confusing for users, but nothing further to be done at this point. 

To summarize, our permissions are the same as [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/), on which AdNauseam is based, with the exception of one added permission ('Monitor extension usage and manage themes'), which we use to warn users about potential conflicts with other addons like 'Adblock Plus'
