### ISSUE TITLE
Total loss of filters/filter lists

### ISSUE THREAD

**Issue by GrimTheWanderer** [dhowe/AdNauseam#1930]
The Filter List appears to have purged all filters. They appear after reinstalling, but viewing the filter list page has resulted in their being purged again, with only the auto-update checkbox present. Ticking the box and hitting apply pops up two "reactivate" buttons, the easylist reactivate button can (but not always) return the filters, if it doesn't it causes a page filling checkmark to appear momentarily, while the adnauseam reactivate button prompts a "leave page without saving changes" confirmation alert.  switching to any other tab also prompts the same alert, regardless of the "reactivate" status. Restarting firefox does not resolve the issue. This time the issue occurred after enabling the second adguard filter.
During this process, the following error appears in the browser console:

Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:3557
    send moz-extension://606b7497-f3d2-4d13-b60b-e54a884d8ef3/background.js:3557

![adnauseambug](https://user-images.githubusercontent.com/54718456/132953270-40a91c0d-7461-44d5-82e6-9187806ac799.png)

I am unsure if this issue can be reproduced.

### Your settings
- OS/version: Windows 10 version 2004 (OS build 19041.1165)
- Browser/version: Mozilla Firefox version 92.0
- AdNauseam version: 3.11.4
- Other extensions you have installed: Augmented Steam, Bitwarden - Free Password Manager, Bypass Paywalls, Decentraleyes, Facebook Container, Google Analytics Blocker, Google Translator for Firefox, Google Unlocked, Greasemonkey, HTTPS Everywhere, New Tab Suspender, Popup Blocker (strict), Redirector, Searchonymous, Universal Bypass, View Image, 
- AdNauseam settings:

##### Your filter lists
Default Filter lists
9Anime Filter-list: No Banner Ads
Dandelion Sprout's Annoyances List
Dandelion Sprout's Redirector List

### Your location/country
USA

**Comment by dhowe** [comment]
perhaps related to #1916 ?

**Comment by metapea** [comment]
I been getting the same thing
https://github.com/dhowe/AdNauseam/issues/1827#issuecomment-903210362

**Comment by GrimTheWanderer** [comment]
I noticed that the conditions to replicate the issue were present and have done so:

![screen1](https://user-images.githubusercontent.com/54718456/134091755-41585e5d-172d-4306-b5e4-ccd25abf3596.jpg)
![screen2](https://user-images.githubusercontent.com/54718456/134091776-c598a3c3-cf87-4171-8a5c-78b89bbc81a2.jpg)
![screen3](https://user-images.githubusercontent.com/54718456/134091783-fd8f1d1f-34ce-48c4-afea-1c2b5ca6cee9.jpg)

I activated the debugger beforehand, this time, here is the output
![screen4](https://user-images.githubusercontent.com/54718456/134091845-a4994893-6fe1-4edb-bc99-dc5e2f67131d.jpg)

**Comment by mneunomne** [comment]
Thank you @GrimTheWanderer , This makes it easier for us to fix this. Will update once I found a way to fix this.

**Comment by mneunomne** [comment]
Found out this exception is happening because the "adnauseam-filters" are coming to the `oldAvailableLists` asset list only with a property `off: false` property:

![offff](https://user-images.githubusercontent.com/4967860/135725967-58b0f2f6-e358-4823-8557-c4f91ccac69e.PNG)

Not sure why this is happening, but it causes issues since it has no `contentURL`  etc

**Comment by mneunomne** [comment]
Fixing at least the exception error with this PR https://github.com/dhowe/AdNauseam/pull/1941. 

Needs more testing to verify if the underlying issue is not causing further problems. At the moment I wasn't able to identify any,

**Comment by dhowe** [comment]
Do we have a set of steps with which we can recreate this ?

**Comment by mneunomne** [comment]
@dhowe I'm actually failing to reproduce this error even without the fix above at the moment. Been trying by re-building multiple times.
I wonder if it is something to do with github servers themselves...

**Comment by dhowe** [comment]
>  I wonder if it is something to do with github servers themselves...
Seems unlikely but possible. In any case, we should test the error-handling when the network is down

**Comment by Xalusc** [comment]
Steps to reproduce:

- Go into AdNauseam settings > Filter Lists
- Two filters should be deactivated; "Block access to LAN" and "AdGuard tracking protection" (not sure about this last one)
- Check both and click "apply changes"
- A warning banner should appear on top of the screen, saying "Activate the AdNauseam filter"
- Click the "reactivate" button on the banner

Now all of the filter lists have been purged. The only way to fix is to reinstall the extension.

**Comment by mneunomne** [comment]
Thank you @Xalusc , this is indeed the way to reproduce it. Will try to solve this issue

**Comment by dhowe** [comment]
@mneunomne status? (just happened again to me under normal use)

**Comment by mneunomne** [comment]
Hey @dhowe I'm now doing the merge from ublock 1.38.0, I believe that will fix it.
It's a lot of changes do it's taking me a bit of time at the moment.
