### ISSUE TITLE
Unable to view Youtube, FaceBook and Google

### ISSUE THREAD

**Issue by bipinkumarb** [dhowe/AdNauseam#1931]
I updated to the newest version of Firefox yesterday night and the issue is happening since then. My Youtube and Facebook pages are black/blank and my Google search keeps refreshing continuously and does not display the search results. The continuous refreshing happens on a couple of other banking websites as well. 

These issues stop when I disable the Adnauseum add-on on Firefox.

AdNauseam v3.11.4
Firefox version 92.0 (64 bit)

Other extensions installed:
Dashalne Password Manager
SurfShark VPN
Facebook Multi-Account Containers
Dark reader
Google Keep Notes
Zoom Scheduler
Grammarly for Firefox
HTTPS Everywhere
Newsgaurd
Privacy Badger
SimpleSearch
PKCS11 Loader
Token Signing
UnHook - Remove YouTube recommended videos
Awesome Screenshot: Screen Capture, Annotate
Google Container
Facebook Container

**Comment by bipinkumarb** [comment]
Screenshots of Blank Youtube and FB pages

**Comment by dhowe** [comment]
I'm not able to recreate this (see below visiting youtube with current ADN/FF) -- what is your OS?
Perhaps you try with a fresh [Firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_creating-a-profile)? I've seen updates in FF cause corrupted profiles, especially with lots of addons

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/737638/132998093-38e7fe5a-6b9e-4632-b372-2a022e1d05e1.png">

**Comment by mneunomne** [comment]
Also not able to reproduce in Firefox, both on windows and macOS
