### ISSUE TITLE
install folder vanishing

### ISSUE THREAD

**Issue by lyingonthefloor** [dhowe/AdNauseam#1934]
Following the steps to install, but Extensions can't find adnauseum.chromium in my files. Says path does not exist.

**Comment by dhowe** [comment]
we need your platform, browser, and OS version to be able to accurately diagnose any problem
however, note that you need to download and unpack the adnauseam.chromium zip file to a safe place where the folder will not be changed or deleted (my guess is that it was deleted, either  automatically or manually)

**Comment by lyingonthefloor** [comment]
you're so right I forgot to unpack it - all good. thanks!

**Comment by mneunomne** [comment]
Closing
