### ISSUE TITLE
Broken CSS in Menu on LibreFox

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1936]
To recreate, download LibreFox ([here for OSX](https://gitlab.com/librewolf-community/browser/macos/-/releases)) and install AdNauseam from Mozilla store

<img width="954" alt="image" src="https://user-images.githubusercontent.com/737638/135062695-76c36c77-abb2-4101-ade7-e241436eb52b.png">

**Comment by mneunomne** [comment]
@dhowe do you know how to test development version in LibreWolf? When I try to add the built adn firefox version on it, it says the manifest is not valid:
![Screen Shot 2021-10-06 at 11 11 46](https://user-images.githubusercontent.com/4967860/136174384-404d35a9-5f92-46f9-a191-f3a445669703.png)

It works when i download the zip from the release version:

![Screen Shot 2021-10-06 at 11 12 36](https://user-images.githubusercontent.com/4967860/136174515-f76dc88f-6b51-4c3c-a1b2-239dec677a79.png)

**Comment by dhowe** [comment]
You need to load from the unpacked folder -- click 'load temporary' then navigate to the manifest file:

![image](https://user-images.githubusercontent.com/737638/136175965-6a7d5525-8bac-47a5-8a1b-9b29402e88f3.png)

**Comment by mneunomne** [comment]
ah ok, now it worked.

I pulled master and the bug still persists:

![Screen Shot 2021-10-06 at 13 44 52](https://user-images.githubusercontent.com/4967860/136196318-706e4081-d926-41ad-b7eb-bce7df042e4c.png)

**Comment by mneunomne** [comment]
Cool, tested and it seems to be working, didn't know it was in the temp branch. Good job :)

**Comment by mneunomne** [comment]
But i guess there is the issue now where the warnings don't always fit into the new width 

![Screen Shot 2021-10-13 at 16 05 58](https://user-images.githubusercontent.com/4967860/137149083-295ddfa3-6d51-4938-9fdb-04e99f4684e4.png)

**Comment by mneunomne** [comment]
Apparently uBlock Origin also changed their menu to this width. If it looks too small now we should adjust font-sizes, things like that, to fit the UI more confortable in this width

**Comment by mneunomne** [comment]
Perhaps simply a change in font-size for the $ text would do? 

Previous:
![Screen Shot 2021-11-08 at 17 03 18](https://user-images.githubusercontent.com/4967860/140775978-2a1648fe-488a-4d8f-af31-abd17543ec0a.png)


Current
![Screen Shot 2021-11-08 at 17 02 20](https://user-images.githubusercontent.com/4967860/140775828-594aff1e-3c68-49a0-91af-7398689a6c46.png)

**Comment by mushon** [comment]
Is it a change in font size or the width of the element? Either way, it is probably a good idea. @mneunomne Pull request?

**Comment by mneunomne** [comment]
Made some improvements on the CSS already so its not breaking line on the price area:

![Screen Shot 2021-11-12 at 20 15 18](https://user-images.githubusercontent.com/4967860/141522764-a7a142c1-6974-4415-8276-708dd7c81c9a.png)

The notification is a bigger issue, it was barely fitting before.

**Comment by mneunomne** [comment]
@dhowe maybe we can close this issue? If yet more css improvements to be made we can create a separate issue
