### ISSUE TITLE
Cross-platform handing of private-mode

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#194]
How to detect whether a window is in private-mode (incognito)?

CHROME
http://developer.chrome.com/dev/extensions/extension.html#property-inIncognitoContext

FF(via JSM)
https://developer.mozilla.org/EN/docs/Supporting_per-window_private_browsing

FF(via SDK)
`    if (require("sdk/private-browsing").isPrivate(wnd)) { }`

**Comment by dhowe** [comment]
Fixed. @CyrusSUEN, please verify that no ads are collected in private/incognito modes on ff/chrome/opera

**Comment by CyrusSUEN** [comment]
> verify that no ads are collected in private/incognito modes on ff/chrome/opera

Yes, I can confirm that.
ADN continues to block ads on all platforms in Private mode but does not collect any ads although on Chrome and Opera we need to manually allow it to run in Private mode.

I think we need provide some hints or feedback to users how should ADN behaves in Private mode.

**Comment by dhowe** [comment]
This should be a new FAQ entry
