### ISSUE TITLE
False warning on adnauseam filter (disappearing filter lists)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1940]
I've somehow entered a state where the adnauseam list is on, but the warning is also showing. Note also that adNauseam.txt has relocated itself as a 'custom filters' . This originally occurred after enabling a new filter list and then clicking some combination of (the confusing) 'apply now', 'purge caches' and 'update' buttons. 

I have not thus far been able to recreate this.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/737638/135739133-940701ae-f7ff-4191-ae42-3ceb4e15e667.png">

**Comment by dhowe** [comment]
After clicking 'reactivate' I get an empty filter list page:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/737638/135739212-d6827543-ec77-46ad-a4dd-adfd4b6d86b4.png">

**Comment by mneunomne** [comment]
@dhowe based on what I have been testing it is related yes. It has something to do how the adnauseam filter gets saved in the storage without the needed information.

**Comment by mneunomne** [comment]
this is for sure a consequence of https://github.com/dhowe/AdNauseam/issues/1930, I would say it can be closed
