### ISSUE TITLE
Curious about privacy ramifications due to ad content bias

### ISSUE THREAD

**Issue by alxpettit** [dhowe/AdNauseam#1951]
Sorry for the derpy issue title. Basically, I've been looking at my statistics for the past few months, and I've noticed that the ads being clicked on are _mostly_ tech related.

I'm a techie, and I go on a lot of tech-oriented sites, and tech oriented sites tend to run tech-oriented ads. Wouldn't this mean that in practice, rather than adding enough noise to confuse the ad companies -- simply by averaging everything out, they could tell that I'm a techie?

This seems to be a class of problem I haven't seen much on in the Ad Nauseam docs or community -- but I'm pretty new here, so maybe I missed something?

If not, I'm curious if there's any plan to add heuristical ad filtering so that it only clicks on, e.g., non-tech ads.

**Comment by dhowe** [comment]
If you are largely visiting tech-sites and thus AdNauseam is clicking largely on tech ads, it is likely true that your profile will not be obfuscated in the topic sense that you suggest (of course profile obfuscation is only one of the goals of ADN). Actually we've been kicking around the idea of a sort of obfuscating agent, which would visit sites and click on things, perhaps do searches as well (a la TrackMeNot), but making this work correctly is nontrivial, and, sadly, we can barely keep up with bug fixes for existing projects

**Comment by alxpettit** [comment]
Sounds _very_ nontrivial for a small FOSS team with limited resources... totally understandable.

I think it'd be better to just have an option to filter the kind of ads it clicks on more -- so you can ban the tech ads, for instance. Filters could be configurable in much the same way that the adblock filters themselves are configurable.
