### ISSUE TITLE
[3.11.5b1 ] Any changes in filter list activates "Activate the AdNauseam filter ?" warning

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1954]
Whenever you disactivate/activate some filter in the filter list (for example, uBlock filters), after applying changes it displays: `Activate the AdNauseam filter ?` warning. When it should not.

![Screen Shot 2021-11-08 at 17 00 52](https://user-images.githubusercontent.com/4967860/140775562-f398296a-dba6-4724-9349-fc2ab0c0ea60.png)

**Comment by dhowe** [comment]
I am seeing this as well
