### ISSUE TITLE
[3.11.5b1 ] Google ads reappearing on guardian.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1955]
https://www.theguardian.com/international

note: not selectable via 'block element' menu

AdNauseam v3.11.5b1 uBlock Originv1.33.0   (shouldn't this be 1.38 for ub?)

<img width="815" alt="image" src="https://user-images.githubusercontent.com/737638/140857982-93e58f21-b2d5-4f5c-b4c3-ee006c7838e5.png">

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/737638/140858106-d59f4dde-3dbd-4d74-ba67-cf6a529a4225.png">

**Comment by mneunomne** [comment]
These are not occuring to me. Maybe try to build again from last PR's ? I installed through temporary add-on and it is working fine
