### ISSUE TITLE
Chrome rejects manifest file at 2.2.0

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#196]
![814436027_139556_4521462829956469822](https://cloud.githubusercontent.com/assets/27123/15653104/911d5eba-2693-11e6-9786-b34267ac9253.jpg)
![423912042_63669_7858899679095550749](https://cloud.githubusercontent.com/assets/27123/15653105/911e8ca4-2693-11e6-8a94-839811a0aee9.jpg)

It seems that the folder has another folder inside with the same ``adnauseam.chromium`` name alongside a ``META-INF`` folder. installing the ``adnauseam.chromium`` does work

**Comment by CyrusSUEN** [comment]
Did you do ``$ brew install jq``? It may solve this

**Comment by dhowe** [comment]
We need more information to debug this. Did you build the extension, or just install from the zip?

Also, please see #196

**Comment by mushon** [comment]
This is from the zip file on [this page](https://github.com/dhowe/AdNauseam/wiki/Help-test-AdNauseam-for-Chrome):
![image](https://cloud.githubusercontent.com/assets/27123/15657036/e5db451c-26b5-11e6-9197-24a0395aacc9.png)

**Comment by dhowe** [comment]
See #193
