### ISSUE TITLE
Ads displayed in reloaded tabs after browser restart [Opera]

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1972]
From email:

>  I am on Opera, and use the option in opera to reopen the tabs and windows you have when you close it. When it does this, specifically when the computer starts from shutdown or restart, not just Opera restarting, some ads aren't blocked. The instance I remember at the moment was a few Youtube ads. I have sorta found a way to temporarily fix this by opening the extensions menu, and just toggling the disable button off and back on, then reloading the page. It's not a massive issue, just a minor annoyance and it's been going on for a while so I thought I'd report it to you all. 
> Also wanted to get the obvious out of the way, I don't use any other ad blockers including opera's built in one so it's not a conflict there.

**Comment by mneunomne** [comment]
I can confirm this is happening, but  I tested and the behaviour is the same in uBlock. After the page is reloaded the ads dissapear again. Not sure there is anything we can do about it...

**Comment by dhowe** [comment]
if same as ublock, then ok for now
lets recheck in next merge

**Comment by Klowner666** [comment]
I seem to have a similar problem on firefox 99.0.1 (64-bit). When I close and reopen the browser, all adds are displayed, I need to personally reactivate the add blocking / malware blocking / addclicking, in the adnauseam settings. (As if this was the first time I was lauching adnauseam.) My advault remains empty at all times. Even when adnauseam works after reactivating manually all options (the ads are blocked). 

I assume it has something to do with permissions or that adnauseam does not save userdata after closing the browser. 

I don't use any other adblockers, and tried disabling all extensions, tried uninstalling reinstalling adnauseam, did not change. However tried with just uBlock origin, it works even when I close / open browser so the issue does not seem to come from the adblocker. 
Thank you for all your excellent work.

**Comment by mneunomne** [comment]
Wasn't able to reproduce this issue on Opera at least when restarting. It seems this was related to this issue on uBlock Origin: https://github.com/gorhill/uBlock/issues/1327

Seems it was fixed already.

Closing
