### ISSUE TITLE
Transparent ads background color change?

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1978]
This is a just a detail, but apparently most (almost all) of ads that appear from google searches for example, are collected as trasnparent images that pre-supose a white background. Since our interface is mostly dark these ad images don't show so well in on adnauseam:
![Screen Shot 2021-12-06 at 12 51 27](https://user-images.githubusercontent.com/4967860/144841785-0b7b6757-02f5-4066-854a-a2dc2685bd65.png)

### Possible solutions

Set a standard white background for all ad images?

![Screen Shot 2021-12-06 at 12 56 12](https://user-images.githubusercontent.com/4967860/144841979-a2d42f4a-91af-4be6-b16a-5034e20f9f24.png)

Perhaps we can know that the images are from google or something like that and set only them as white background?

**Comment by mneunomne** [comment]
Another issue is that when we focus, it becomes even more invisible:

![Screen Shot 2021-12-06 at 16 27 55](https://user-images.githubusercontent.com/4967860/144873873-b201ac4b-a1c0-484e-87b2-ac043f4f9411.png)

**Comment by mneunomne** [comment]
With white background (possible solution):

![Screen Shot 2021-12-06 at 16 29 09](https://user-images.githubusercontent.com/4967860/144874033-9addd7e7-8d80-413d-9f26-3bcdcbb85497.png)

**Comment by dhowe** [comment]
I like this but it assumes non-white text and graphics -- are there cases where we have a transparent background with a white ad ?

**Comment by mneunomne** [comment]
I didn't observe transparent ads that assume a black background. It seems at least thats not how google ads work at least. I also tested putting google on dark mode but it still generate ads with the white background added through CSS.

Perhaps we can limit this to google ads for now?

**Comment by dhowe** [comment]
or just for it for all... I think it is quite infrequent that a transparent ad has white text

**Comment by mneunomne** [comment]
I made a solution where I only add white-bg to images that are png data strings, contaning `data:image/png`. Which is the case of google ads

I saw some cases where the white background looks strange so I think a non-global solution seems better:

![Capture-shoes](https://user-images.githubusercontent.com/4967860/145717682-4415a722-1e76-41d3-bd64-b3ad75995c9f.PNG)

**Comment by mneunomne** [comment]
Looks good with a large ad set

![large ad set](https://user-images.githubusercontent.com/4967860/145717882-00793613-c800-4dd7-9c2e-dda339aaf10b.PNG)

**Comment by mneunomne** [comment]
And some white images with transparent background were also avoided to dissapear in white bg:


![Capturenigger](https://user-images.githubusercontent.com/4967860/145717894-f673f65a-9283-4deb-82bb-e55a1a79ae4c.PNG)

**Comment by dhowe** [comment]
excellent, you can close this

**Comment by mneunomne** [comment]
Closing

**Comment by mneunomne** [comment]
Forgot to add the white bg on the menu as well, reopening

**Comment by mneunomne** [comment]
Implemented, closing

![sapatos](https://user-images.githubusercontent.com/4967860/145736362-31cd6d57-9c6d-4f96-b98b-de7147c04ee7.PNG)
