### ISSUE TITLE
[Opera] "Allow access to search page results" notification not showing

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1979]
When the option "Allow access to search page results" is unchecked, a notification should appear on Adn menu when the user is currently on a search page.

![](https://user-images.githubusercontent.com/4967860/143271129-ad8a515e-dc5d-4655-9491-bf1d07768e83.png)

**Comment by mneunomne** [comment]
Fixed, closing

![Screen Shot 2021-12-06 at 15 40 17](https://user-images.githubusercontent.com/4967860/144866528-b3b7cea4-2dda-459e-a110-031a0d543138.png)

**Comment by dhowe** [comment]
on click I assume it takes the user to the relevant setting checkbox?

**Comment by mneunomne** [comment]
@dhowe it actually leads to our page: https://github.com/dhowe/AdNauseam/wiki/FAQ#why-adnauseam-does-not-work-on-search-engines-in-opera

**Comment by dhowe** [comment]
sounds good, you can close if done...

**Comment by mneunomne** [comment]
Closing
