### ISSUE TITLE
Optimizations for ad vault updates

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1983]
These should help with memory, especially the first item below as it happens on every page

- [ ] only send ads for page and recent to menu, not full set (*important)
- [ ] only send updated/new ads to menu/vault on update, not full set

**Comment by mneunomne** [comment]
@dhowe I dont see where we are sending the full set of ads to the menu though

https://github.com/dhowe/AdNauseam/blob/72837e708ccfd70d999efc4e72978f817bd081e6/src/js/adn/menu.js#L37-L41

https://github.com/dhowe/AdNauseam/blob/72837e708ccfd70d999efc4e72978f817bd081e6/src/js/adn/menu.js#L445-L454

https://github.com/dhowe/AdNauseam/blob/72837e708ccfd70d999efc4e72978f817bd081e6/src/js/adn/core.js#L2229-L2254

**Comment by mneunomne** [comment]
and it seems that in the adVault this also already happens:

https://github.com/dhowe/AdNauseam/blob/bada276526a19aa0b2ed155e8793e8743352ba3f/src/js/adn/vault.js#L73-L88

**Comment by mneunomne** [comment]
There are probably other improovement that can be made, but i believe these two points are already implemented actually

**Comment by dhowe** [comment]
do you have specific improvements in mind? if so, lets create tickets for them
but I think this can be closed
