### ISSUE TITLE
[3.12] Gray ad bar at top of nytimes.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1987]
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/737638/145803376-12d18b45-3357-43f8-ae15-d04f9a18f48f.png">

**Comment by mneunomne** [comment]
Fixed, closing

**Comment by mneunomne** [comment]
https://github.com/dhowe/AdNauseam/issues/1995 was caused by this change actually, reversing and reopening

**Comment by mneunomne** [comment]
this is not happening with me any longer on master
