### ISSUE TITLE
Implement outgoing visit flags and add to options

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#199]
Preferences:
- [x] noOutgoingReferer (header: 'Referer')
- [x] noOutgoingCookies (header: 'Cookie')
- [x] noOutgoingUserAgent (header: 'UserAgent')

**Comment by dhowe** [comment]
done in ae52a968fe

**Comment by dhowe** [comment]
@CyrusSUEN please verify

You will need to check (by whatever means) that outgoing requests obey these new options settings.

For example, if noOutgoingUserAgent == true, then the request sent for an ADN click, should have either no "User-Agent" header, or it should be blank.

**Comment by CyrusSUEN** [comment]
I use [Charles](https://www.charlesproxy.com/) to check the packets.

They all work on all platforms. :thumbsup:

Attached the saved sessions from Charles program:
[Charles_saved_sessions.zip](https://github.com/dhowe/AdNauseam/files/299299/Charles_saved_sessions.zip)
