### ISSUE TITLE
Adjust HTML structure in Options.html 

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1994]
The HTML structure of our options.html page in the dashboard is really outdated. In general it is fine, but it makes our checkboxes look ugly in comparisson with ublock: 

![Captureublock](https://user-images.githubusercontent.com/4967860/146659166-79a7ceaf-50f5-4a76-9552-16472aadfe9e.PNG)

![Capturedashboard](https://user-images.githubusercontent.com/4967860/146659167-00bda651-1c92-46cb-93de-8e8ded9d0b2e.PNG)

### I was able to fix this at the filter list page: 

![Capture3pfilters](https://user-images.githubusercontent.com/4967860/146659169-81e7a796-38f9-4a86-9499-65157a1c3d01.PNG)

But at the options it is much more tricky to do so... Very time consuming plus some adaptations are necessary.

**Comment by dhowe** [comment]
I've marked this as next-release though could go in the current if there is time...

**Comment by mneunomne** [comment]
We can close this after the last merge https://github.com/dhowe/AdNauseam/pull/2142
