### ISSUE TITLE
Update Filter List division to match uBlock's

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2004]
It seems our filter list page has different sections names that of uBlock at the moment, not sure to which extend this is intended, it seems that there are some updates needed

![Screen Shot 2021-12-28 at 07 03 44](https://user-images.githubusercontent.com/4967860/147558366-7577b92b-bd4d-4515-98a2-e060b64d7857.png)

![Screen Shot 2021-12-28 at 07 03 47](https://user-images.githubusercontent.com/4967860/147558371-871b36b7-4ccd-4c1b-89e8-da3cdb85337b.png)

**Comment by dhowe** [comment]
Using their layout is fine, we just need to remove the 'Ads' category, and add adnauseam.txt to 'Essentials'

**Comment by mneunomne** [comment]
I realized this is actually correct. The segments that don't appear is because we have actually dissabled the lists that make them appear. Closing
