### ISSUE TITLE
Keyboard shortcut incorrect for whitelisting-page on OS X

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2012]
currently says ctrl-click, but should be alt-click, at least on OS X

![image](https://user-images.githubusercontent.com/737638/148536620-192d752d-d577-4b4f-9fa2-67a9b11389d7.png)

**Comment by mneunomne** [comment]
Hm I see, we would need to create a new version entry on crownin and check with javascript for the user OS

**Comment by dhowe** [comment]
lets push to next release

**Comment by dhowe** [comment]
duplicate of #1996
