### ISSUE TITLE
Script tools/make-artifacts only works on MacOS

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2019]
Due to these lines it can obviosuly only work on MacOS:

https://github.com/dhowe/AdNauseam/blob/09aad2c0dac2e13642f9a7ffcb815407872aed3e/tools/make-artifacts.sh#L10-L12

which is a bit anoying since I am tending to work on Windows and have to switch back to MacOS to upload the release files.

**Comment by dhowe** [comment]
yes, it can either be a) modified to take command line arguments for the paths, or b) you can perhaps detect the OS, and include the windows  default paths (or both)

**Comment by dhowe** [comment]
should support linux, not sure if its worth the time for windows

**Comment by mneunomne** [comment]
Added a code block where the standard path for windows can be added later if necessary.
