### ISSUE TITLE
Update design for settings page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#202]
We have several user-settings(hideOutgoingReferer, hideOutgoingUserAgent, stripOutgoingCookies) to add to the settings page, which is getting a bit crowded. I suggest adding an AdNauseam label at the top to delineate the ADN-relevant options, then a uBlock label underneath. Alternatively we might leave settings combined (as is) and include these 3 new settings under 'privacy'

design thoughts @mushon  ? 

please also include any warnings we want to show when changing these options (e.g., #145)

![screen shot 2016-06-04 at 12 30 18 pm](https://cloud.githubusercontent.com/assets/737638/15797693/7e7b3c1e-2a53-11e6-80f5-a07970d60067.png)

**Comment by dhowe** [comment]
![screen shot 2016-06-24 at 6 33 57 pm](https://cloud.githubusercontent.com/assets/737638/16335630/3c5a529c-3a3a-11e6-8576-97f8c006074e.png)

**Comment by mushon** [comment]
I think the number of ads on the icon makes more sense under the "interface" title, no?
+
I think it makes sense for the first three options from the firstrun screen to maintain their group.

I also think we should not use "Adnauseam-Advanced" But simply call it advanced or separate them with a ``hr``

As for default behavior. We should probably explain how can these behaviors be changed on a per-site basis

**Comment by mushon** [comment]
So one way we could go about customizing the settings is to use a different structure for the tabs and actually break into two hierarchies:
```
GENERAL
├ HIDE ADS (  ●)
│└ all hiding rules appear here (hidden or grayed-out if disabled)
├ CLICK ADS (  ●)
│└ all clicking rules appear here (hidden or grayed-out if disabled)
├ BLOCK MALWARE (  ●)
│└ all blocking rules appear here (hidden or grayed-out if disabled)
└ INTERFACE
  ┝ Make use of context menu where appropriate
  ┝ Disable tooltips
  ┝ Color-blind friendly
  └ I am an advanced user (Required reading)

FILTERS RULES AND LISTS
┝ FILTERS (including my filters)
┝ RULES
└ WHITELISTS

ABOUT
```
@dhowe your thoughts?

**Comment by dhowe** [comment]
minor edits included in the above...

**Comment by dhowe** [comment]
@mushon, status?

**Comment by mushon** [comment]
Busy week. Haven't gotten to it yet. 

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by mushon** [comment]
First pass in with fe73ffe0ff440776fc1eed8ccd7f1ba0abafc472

**Comment by leoneckert** [comment]
is there something for me to do on this one currently?

**Comment by mushon** [comment]
I suggest we close this and address specific issues separately.

**Comment by dhowe** [comment]
see #530
