### ISSUE TITLE
Exclude small 'marker' ads from being collected

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2025]
We have code in the parser ([here](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/parser.js#L240)) to skip such small non-ads, requiring any ad to be at least 31x64, however it appears to no longer be working, and many such marker ads are still being collected. 

One of many URLs where this is happening: https://www.seriouseats.com/sichuan-peppercorn-recipes

- [x] Check why parser code is not currently working for such ads
- [ ] If needed, also implement in core.js validate() function
- [ ] If needed, add code to check image URL for these common cases (avoid if possible)

<img width="731" alt="Screenshot 2022-01-11 at 2 04 50 PM" src="https://user-images.githubusercontent.com/737638/148889941-1fc4b01f-65d3-45ed-86e6-51663df57973.png">

Upper: 192 × 30, https://tpc.googlesyndication.com/pagead/images/abg/en.png
Lower: 15 x 15, https://tpc.googlesyndication.com/pagead/images/abg/icon.png

<img width="292" alt="image" src="https://user-images.githubusercontent.com/737638/148889551-001bd551-625b-437c-ba69-e9cf32440617.png">

**Comment by dhowe** [comment]
cannot recreate

**Comment by dhowe** [comment]
seeing this again in v3.12.1 (rc):

<img width="316" alt="image" src="https://user-images.githubusercontent.com/737638/149277695-f8751996-7ddf-4e96-9b21-9ea6c6d3c6aa.png">

**Comment by mneunomne** [comment]
wasn't able to reproduce it on this particular link, but i believe i have seen this happen already

**Comment by mneunomne** [comment]
Finally found a page where I detect this again:

https://www.wikitechy.com/tutorials/javascript/why-does-javascript-only-work-after-opening-developer-tools-in-ie-once

**Comment by chirag127** [comment]
![image](https://user-images.githubusercontent.com/76880977/178106846-c1cc913a-55e0-46c5-af0a-469f70a133aa.png)

**Comment by chirag127** [comment]
on https://www.newindianexpress.com/nation/2022/jul/09/congress-to-hold-press-conferences-across-india-on-saturday-to-expose-bjp-on-udaipur-murder-2474668.html
