### ISSUE TITLE
Warning text is unreadable

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2026]
When warning text extends off the right-edge (a common occurrence), it gets ellipses... One expects that a mouse-over should reveal the hidden text, however instead the 'Settings' button slides out from the right. Thus there is no way to read the hidden (and sometimes important) text for the warning...

<img width="319" alt="image" src="https://user-images.githubusercontent.com/737638/148892071-fcdc67c4-e07b-488b-977a-782fd507cf3f.png">

with mouse-over:
![image](https://user-images.githubusercontent.com/737638/148892486-b05f53f6-fecf-4d83-9a82-086c3964e30d.png)

**Comment by mushon** [comment]
Can we slide the text to the right with the button trailing at its end?

**Comment by mneunomne** [comment]
Implemented the sliding text on hover, @dhowe can you check test please ?

**Comment by dhowe** [comment]
Small thing but seems the footnote gets obstructed when the text slides:
<img width="309" alt="Screenshot 2022-01-13 at 11 03 41 PM" src="https://user-images.githubusercontent.com/737638/149354949-49ef35b6-4169-48f9-883f-5abe4e338e22.png">

**Comment by mneunomne** [comment]
Okay, now i realized that the warning with a button on hover look weird when sliding...

**Comment by mneunomne** [comment]
Fixed, seems its working both in german and english as well, (and in theory, other language as well)
