### ISSUE TITLE
Add a mobile AdNauseam

### ISSUE THREAD

**Issue by thatcatdrout** [dhowe/AdNauseam#2033]
### Describe the issue

*NOTE: if you are having a problem where ads are not collected, please FIRST TRY to create a new new Firefox profile as described [here](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_creating-a-profile). A corrupt Firefox profile is the most common cause of this issue.*

A lot users use mobile to search the web and adnauseam should add a mobile version to fight  advertising surveillance

### Your settings

- OS/version: Android
- Browser/version: 
- AdNauseam version: latest
- Other extensions you have installed: none
- AdNauseam settings:

### Your location/country: Sweden
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

**Comment by dhowe** [comment]
We have a mobile version tested and ready. Unfortunately Mozilla policy only allows a handful of "pre-approved" addons for mobile.

 If you disagree with this policy, you can write to them here: amo-admins@mozilla.com

**Comment by thatcatdrout** [comment]
I have a idea. We fork the mobile firefox and hardcode the extension into the source code
