### ISSUE TITLE
Update design for menu to clarify and support strict-blocking

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2035]
Need to support the following in the bottom section of the menu (*indicates a new item):

- strict-block-site *
- disable-on-site 
- disable-on-page
- ublock settings
- settings (perhaps switch to gear icon?)
- faq

There is also the potential concern that the current 'disable' button suggests disabling ADN altogether, rather than _only_ for the current page/site

![image](https://user-images.githubusercontent.com/737638/152336585-08bc590b-e269-44bc-9fda-e97858da07d9.png)

**Comment by dhowe** [comment]
![image](https://user-images.githubusercontent.com/737638/152336411-e6fddf1f-a97c-4468-9629-57eae099ff3d.png)

**Comment by mneunomne** [comment]
We could maybe have instead of the "disabled" button, a 3-state button, when the following actions to the current webpage:

- Disable adn on this website (allow all requests)
- Default behavior
- strictBlock (Blocks all requests like uBlock does)

## 3 state button example

![image](https://user-images.githubusercontent.com/4967860/152342950-51b50e83-27bf-4b64-a7a7-ebe310e41af8.png)

## uBlock has a clear big button indicating it, with the domain name under it:
![bingCapture](https://user-images.githubusercontent.com/4967860/152342858-39c8e00e-e955-4f01-9626-78dc86a883d3.PNG)

**Comment by mushon** [comment]
Can we maybe do this with a sub-menu? Like:
- Disable Here (with icon)
  - disable only this page
  - disable on domain.tld 
  - disable everywhere
  - strict block (what does that mean?)
- Settings (with gear)
  - Adnauseam settings
  - Unlock (ad blocker) settings
- Help (icon only)

**Comment by dhowe** [comment]
So "strict-block" means that for the current domain, ADN acts just like ublock. Rather than trying to hide and collect ads, it simply blocks everything outright, as ublock would. 

This is needed for pages which either have many videos with embedded ads (eg. youtube) or very aggressive spam ads, which would require too many rules to hide/collect (eg. piratebay)

**Comment by mushon** [comment]
Should we maybe add this as an extra option after someone chooses to disable on url?
As in: 
- [x] keep malware protection

**Comment by dhowe** [comment]
this is very different than disabling:
* disabling is as-if you are not using any blocker (you will see ads, etc.)
* strict-blocking is as-if you are using ublock (stronger protection, but no collection/clicking)

**Comment by mushon** [comment]
Then is strict blocking similar to = "only block, don't click"

**Comment by dhowe** [comment]
I suppose it is somewhat similar, for a single domain... 
But it is stronger in terms of blocking and protection.

Currently we have 'disable', which is the equivalent of 'whitelist'.
Strict-block is closer to 'blacklist', or 'treat as dangerous'...

One question is how many of these options do we really need in the menu?

Certainly 'settings', but this could perhaps be a single gear icon somewhere, rather than the full word.

Do we need disable/whitelist? Not sure... Seems much more likely that someone would choose the new 'strict-block' options (for example, when they see ads that sneak through), rather than the 'disable' option, which will show them even more ads. Users are also able to easily add sites to the 'whitelist' tab in settings.

Do we need uBlock settings? Not sure... this could perhaps be an option from our main settings page instead

Do we need the '?' which leads to our FAQ? Not sure... perhaps clicking on the ADN icon could take the user there, instead of to our homepage (the '?' could show on hover)

**Comment by mushon** [comment]
So each page/domain can be in one of 3 states:
[ DISABLED ]   **[ ACTIVE ]**  [ STRICT BLOCK ]
We can use a toggle for this and pop a dropdown type of menu when disabled is chosen
We can also add explanation on hover

+ add Gear & ? icons besides

**Comment by dhowe** [comment]
a domain can be in one of 3 states: [ DISABLED ] [ ACTIVE ] [ STRICT BLOCK ]
at present a single page cannot be strict-blocked, but we might be able to add this...

we also have the same 3 _global_ settings for adnauseam: disabled everywhere, active everywhere, or strict-block everywhere

**Comment by mushon** [comment]
So should I mock up that toggle?

**Comment by dhowe** [comment]
makes sense to me - any comment @mneunomne ?

**Comment by mneunomne** [comment]
Was thinking, and isnt perhaps better that we use the uBlock menu for this instead? It already has space and the webpage name under.... We would just need replace this sign for a 3 state button

![moresense](https://user-images.githubusercontent.com/4967860/152769614-310c9761-1ed0-42a1-8ec5-e0eee2156991.PNG)

**Comment by mneunomne** [comment]
> Do we need uBlock settings? Not sure... this could perhaps be an option from our main settings page instead

@dhowe I believe we do need the uBlock menu, I know some users definetelly use it to create the blocking rules with the rules UI in uBlock menu, also the logger, etc

**Comment by mneunomne** [comment]
> Certainly 'settings', but this could perhaps be a single gear icon somewhere, rather than the full word.

This I agree, and would leave more space for a 3 state button

**Comment by mushon** [comment]
So to summarize we go for the 3 state toggle + 2 icons. Yes?

**Comment by mneunomne** [comment]
@mushon the gear Icon we already have. The other icon you mean for the 3state toggle?

**Comment by mushon** [comment]
Let me send something tomorrow and we’ll take it from there

Mushon Zer-Aviv
Recent work: Normalizi.ng
Mushon.com | Shual.com | @mushon

**Comment by mushon** [comment]
This is what I had in mind:
![image](https://user-images.githubusercontent.com/27123/152966428-488dff03-27c6-49f2-b803-3aad5a72d82d.png)

**Comment by dhowe** [comment]
I like it 
- where does one find the ublock settings? 
- disable on site / page - works same as now with ctrl-click ?

**Comment by mneunomne** [comment]
> I like it
> 
> * where does one find the ublock settings?
> * disable on site / page - works same as now with ctrl-click ?
> * perhaps just 'strict' instead of 'strict block' ?

Agreed. 

Maybe the "?" can go to the top instead?

The gear icon we will use the same as uBlock I guess, which has three gears:

![](https://user-images.githubusercontent.com/4967860/152769614-310c9761-1ed0-42a1-8ec5-e0eee2156991.PNG)

**Comment by mushon** [comment]
here's a (basic) prototype:
https://www.figma.com/proto/UEvj2moMOJDFb3Brc95shq/ad_view?page-id=0%3A1235&node-id=0%3A2012&viewport=382%2C48%2C1.19&scaling=min-zoom&starting-point-node-id=0%3A2012

**Comment by mushon** [comment]
Disabled / Just block / Block & click

UBlock Options:
Just block
Block
Extreme blocking
Strict block
Block onlyl
Full options:
Block & click
Enabled
Full on!
…
We can also pop a confirmation dialogue that would make sure that if you go for block only you are disabling the main reason you installed this and that it would only do that on this domain.

**Comment by mneunomne** [comment]
> maybe we need to rename 'strict' as something more daunting, like 'extreme' blocking... we want to avoid people using this regularly as it basically disables adnauseam (and replaces it with ub)

Actually not. Because strict blocking doesn't unables ad collection, just decreases it.
If you use uBlock together with Adn some ads still go through and are collected. Because some ads are not unrendered by uBlock but rather are just hidden with cosmetic filters as well. So I think `Strict` is the most appropriate name

**Comment by mneunomne** [comment]
For example, google ads can still be collection with Strict Block enabled (and uBlock enabled):

![for_example](https://user-images.githubusercontent.com/4967860/153062401-2516106e-004d-47d4-9276-0f9e1e44bf0a.PNG)

**Comment by mneunomne** [comment]
> here's a (basic) prototype: https://www.figma.com/proto/UEvj2moMOJDFb3Brc95shq/ad_view?page-id=0%3A1235&node-id=0%3A2012&viewport=382%2C48%2C1.19&scaling=min-zoom&starting-point-node-id=0%3A2012

@mushon i like the drop down, but i would say it doesnt seem so necessary on the "settings" part. The Adnauseam settings is more necessary to the avarage user then the ublock settings menu. The uBlock settings menu (in my view) would be more for the advanced user.

And one bad news.... __Our menu now is 320px wide and not 385px__ We had to change it to support have support in certain browsers...

**Comment by dhowe** [comment]
> @mushon i like the drop down, but i would say it doesnt seem so necessary on the "settings" part. The Adnauseam settings is more necessary to the average user then the ublock settings menu. The uBlock settings menu (in my view) would be more for the advanced user.

@mneunomne I agree with this, ADN settings likely gets clicked much more frequently --  do you think it is necessary in the menu? If so, then maybe just the small ub icon we have now

**Comment by mushon** [comment]
OK, now in 320px (I had to change the header as well). Here's what's different:
- help moved to top left
- toggle reordered
- added dividers to toggle
- gear moved to the right and will take to ADN settings (and a link to uBlock from there)
- Scaling:
  - changed list type size
  - changed logo size
  - changed button proportions
  - DNT notice is trimmed and would require animation
  
[Figma prototype here](https://www.figma.com/proto/UEvj2moMOJDFb3Brc95shq/ad_view?page-id=0%3A1235&node-id=0%3A2012&viewport=382%2C48%2C1.19&scaling=min-zoom&starting-point-node-id=0%3A2012)

![image](https://user-images.githubusercontent.com/27123/153159884-e4985695-9dcb-475f-b9db-2aea47432016.png)

**Comment by dhowe** [comment]
Getting quite close... @mneunomne do you think we need ublock settings accessible from menu? if so, we could use another tiny icon, like the '?' (I had used 'µ'), either on the top right corner, or.. if we change the text to 'strict' rather than 'strict block', there's still room on bottom row...

**Comment by dhowe** [comment]
Basically we have [Active, Strict, Disable^] along the bottom, then 3 other small icons: ?, µ, and gear(s), each of which can go in any of the 4 corners... does this make sense to everyone ? if so, then @mushon can work his magic...

**Comment by mushon** [comment]
I feel like µ is not communicating.
Maybe an “inspect” type icon may also work, also switched to "just block":

![image](https://user-images.githubusercontent.com/27123/153196722-893aac65-65d6-42d9-87ab-72108c20adaa.png)

**Comment by dhowe** [comment]
maybe 'block only' ? though, as @mneunomne mentions there still may be a few hides going on

for the ublock settings, this is really just an advanced feature that a few experts use (and may well be already familiar with µ)

**Comment by mneunomne** [comment]
I think the ublock icon is good because our advanced users already know it. And some people even have requested a way to activate the uBlock menu directly somehow... I think it's fine if its cryptic, since it is not inteded for the avarage user anyway.

And we should remember that perhaps advanced users are the minory, but are probably the users that we make sure that we don't loose because we are doing things more difficult for them.

**Comment by dhowe** [comment]
perhaps a blue version of 
![image](https://user-images.githubusercontent.com/737638/153331182-bfb3de36-c478-45dc-93fb-2d4e1a9ec7c1.png)

**Comment by mushon** [comment]
![image](https://user-images.githubusercontent.com/27123/153354312-88c0f367-0bea-4926-8d60-7159cb013867.png)

**Comment by mneunomne** [comment]
this looks good now, what do you think @dhowe ?

**Comment by mushon** [comment]
I suggest to switch the uBlock icon with the gear. I think this does the trick:
![image](https://user-images.githubusercontent.com/27123/154066503-b207fb1c-1f2d-46c8-b167-82e0b7a49eb7.png)

**Comment by mushon** [comment]
maybe better a outline:
![image](https://user-images.githubusercontent.com/27123/154069120-73d7c8d9-9ece-4185-bf44-d6afaf49ae04.png)

**Comment by mneunomne** [comment]
Okay, so I will start implementing this. @dhowe I think we should make a separate branch for this feature change. And keep the master clean until we have it 100%. So we don't stop possible release-fix from the master along the way...

**Comment by mneunomne** [comment]
@dhowe I still wonder about 2 things in the menu:

1. Naming: maybe strickt/active/disabled? "Block only" doesnt sound very clear to me, "Strict" i think is perfect for what it does. We can also go with uBlock new naming "Trusted/Untrusted/Regular" idk... 
2. Do we need the dropdown? I think its better that we only implement on disable/strict on domains.

**Comment by dhowe** [comment]
As discussed, we do need the drop-down for the  site/domain distinction. Strict vs Block-only, not sure... What we want to avoid is people clicking that button frequently, as this essentially disables ADN's defining function

**Comment by dhowe** [comment]
@mushon -- appearance for 'disabled' and 'strict-blocked' states?

**Comment by mneunomne** [comment]
This is when the page is blocked from "My Rules":

![Uploading aspect_block.PNG…]()

**Comment by mushon** [comment]
> @mushon -- appearance for 'disabled' and 'strict-blocked' states?

not sure I understand the question

@mneunomne I see you have access to the Figma file. Let me know if you're missing anything there (you can also comment inside the file itself)

**Comment by dhowe** [comment]
perhaps this is in the figma already? what the menu should look like, after adn is disabled for the page, or strict-blocked for the page

**Comment by mushon** [comment]
Is it something we may solve like this?

**Comment by mneunomne** [comment]
@dhowe what are the main languages that are used with adnauseam ?
The toggle buttons indeed might become an issue since the space is already quite tight with english...

**Comment by dhowe** [comment]
not sure -- here's the full list: https://crowdin.com/project/adnauseam

**Comment by mneunomne** [comment]
> not sure -- here's the full list: https://crowdin.com/project/adnauseam

I mean the most often used. English, Russian, Chinese, German... Another one that we should definetelly test? Just to make sure that the UI doesnt get very broken

**Comment by mneunomne** [comment]
@dhowe I implemented new footer menu with mostly working interactions (not implemented the "On this page" / "domain" differences):

![example](https://user-images.githubusercontent.com/4967860/157732888-0e6c4942-a2e4-4b65-8477-ec8206430b09.png)

### Some things that we need to think about:

- Implement some sort of notification or status when Strict is enabled (and maybe linking to the strictBlockList page)
- Perhaps remove the "DISABLE - EVERYWHERE" functionality, it does not exist in uBlock and it would require some other not-implented mechanism.

**Comment by dhowe** [comment]
> Perhaps remove the "DISABLE - EVERYWHERE" functionality, it does not exist in uBlock and it would require some other not-implemented mechanism.

agreed - the browser already provides this function for all addons

**Comment by mneunomne** [comment]
@mushon @dhowe I think for the strict state this type *(no ads collected)* of menu alert should be implemented? Perhaps better than the usual "warning"

![Screen Shot 2022-03-17 at 17 04 46](https://user-images.githubusercontent.com/4967860/158843012-ddeff3bb-ea4b-437b-822c-963d01048f30.png)

**Comment by dhowe** [comment]
that is an alert for when there are no ads FOUND on the page (either there are none, or we couldn't parse any)
 we could do something similar to below, with text that says 'no
<img width="380" alt="Screenshot 2022-03-18 at 12 14 18 AM" src="https://user-images.githubusercontent.com/737638/158844850-f0161997-8152-4878-8a84-4aa2b5bce08f.png">

**Comment by mneunomne** [comment]
@dhowe I wonder if it should be this alert instead, since some ads can still be collected even if Strict Blocked mode is enabled.

![Screenshot 2022-03-24 at 14 12 58](https://user-images.githubusercontent.com/4967860/159924069-9919d9f4-9e3e-4eb7-9311-7444de09d241.png)

**Comment by dhowe** [comment]
That works for me (though the css should match the other alerts)
I think we also need a link (perhaps to the "strict-blocked" text) to the FAQ entry
And strict-blocked should probably be lower-case...

**Comment by mneunomne** [comment]
> I think we also need a link (perhaps to the "strict-blocked" text) to the FAQ entry
Will do

**Comment by mneunomne** [comment]
### Implemented the alert when 'strict' is on:

![Screenshot 2022-04-02 at 16 36 33](https://user-images.githubusercontent.com/4967860/161388177-0bf14f1c-8c6e-4ccd-a2b9-7747b898c53b.png)

### Added a short text in the 'strict block list' page:

> The strict block list serves to help the users to strict block specific domains or pages more easily. [link](https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#what-is-the-strict-block-list)

![Screenshot 2022-04-02 at 14 12 19](https://user-images.githubusercontent.com/4967860/161388191-1a8b2411-87ca-4ae1-bb1a-38f3e69bb130.png)

@dhowe any final comments?

**Comment by dhowe** [comment]
again, strict block is only for domains, correct?

**Comment by mneunomne** [comment]
Yes. But the user can still make a page-based strict-block directly in the "Strict Block List".

**Comment by dhowe** [comment]
yes, but it doesn't make it 'more easy' to do...

**Comment by dhowe** [comment]
> @dhowe any final comments?

Let's add a dash between 'strict' and 'blocked', but otherwise looks good to me, @mushon?

**Comment by dhowe** [comment]
ok for me, @mushon ?

**Comment by mushon** [comment]
Sure thing..

Mushon Zer-Aviv

Recent work: Normalizi.ng
Mushon.com | Shual.com | @Mushon

On 29 April 2022 at 12:03:52, Daniel Howe ***@***.***) wrote:

ok for me, @mushon ?

**Comment by mneunomne** [comment]
Great work! As we already have implemented i'll be closing this issue
