### ISSUE TITLE
Generic Cosmetic Filtering not working on "My Filters"

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2038]
uBlock has implemented the option to disable generic cosmetic filters:

![coocapture](https://user-images.githubusercontent.com/4967860/152802784-c19230c7-c8b5-4677-910e-16e2c8b84fe6.PNG)

The default for the varible `noGenericFiltering` is false, but the following line is returning true, I believe is not the intended behavior on Adn:

https://github.com/dhowe/AdNauseam/blob/4e75cc966b2d110ccfa1498d2793970467df0b4f/src/js/messaging.js#L630-L631

This is causing the generic cosmetic filters not to work on "My Filters", but it seams that it works normally when they come from the filters files. 

### Testing
Just add a generic cosmetic filters on "My Filters" and see if the element is correctly hidden. e.g.:
```
##.adsbyvli
```

**Comment by dhowe** [comment]
make sure to test carefully and then add your tests (for generic filters in both 3rd party filter lists and 'my filters') to the release testing suite
