### ISSUE TITLE
False positive: .wasm from Godot game blocked by AdNauseum

### ISSUE THREAD

**Issue by JapanYoshi** [dhowe/AdNauseam#2045]
### Describe the issue
I'm trying to deploy a browser game built on the Godot engine. However, the .wasm file that contains the game code is blocked by AdNauseum.

### Screenshot in which the issue can be seen

With AdNauseum enabled:
![image](https://user-images.githubusercontent.com/8707990/153988397-b18ea4ca-9820-410f-a44e-6511446ff963.png)

With AdNauseum disabled:
![image](https://user-images.githubusercontent.com/8707990/153988501-bc0f3a44-57b6-47bf-8f7f-3a69e9b42786.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1. Go to https://haitouch.ga/me/shingo/index.html

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 97.0, 64bit
- AdNauseam version: 3.12.2
- Other extensions you have installed:
- AdNauseam settings:

##### Your filter lists

![image](https://user-images.githubusercontent.com/8707990/153988718-c5d0ce3b-d9f1-4ede-8f61-171062b33233.png)
Plus EasyList Spanish and AdNauseam filters.

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
Japan.

** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

**Comment by mneunomne** [comment]
@JapanYoshi This is the same behavior as in uBlock. Since Adnauseam is based on uBlock, I suggest that this issue should be addressed directly to uBlock:

https://github.com/uBlockOrigin/uBlock-issues/issues

Otherwise you can simply create an exception rule on "My Filters", this one should work:
```
@@||haitouch.ga^
```

**Comment by mneunomne** [comment]
@dhowe  This issue is not Adnauseam specific, so I suggest that we close it.
