### ISSUE TITLE
Use static link for Chrome instructions page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2046]
Page: https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chromium-based-browsers

Rather than redirecting people to the releases page, we should have a direct link, of the form: https://github.com/dhowe/AdNauseam/releases/latest/download/adnauseam.chromium.zip

**Comment by dhowe** [comment]
please add a quick test for this in release tests (note also that we need to update the language on that page to reflect the change in the menu to a 'gear' icon for settings)

**Comment by mneunomne** [comment]
@dhowe okay I added a checkbox for us to test the built artifacts on their browsers before the release.

> (note that we need to also update the text on this page to reflect the change in the menu to a 'gear' icon for settings, and possible elsewhere...)

Where do we need to change it ? I didn't get it

**Comment by dhowe** [comment]
page linked at top of ticket

**Comment by mneunomne** [comment]
Tests on artifact are working and link on wiki is updated, closing
