### ISSUE TITLE
Change title from 'White List' to 'Trusted Sites'

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2047]
We need to address this that was discussed in uBlock issues: 

[Remove ALL references of black/whitelist within uBlock Origin #1114](https://github.com/uBlockOrigin/uBlock-issues/issues/1114)

And possibly check some other changes they have made regarding this.

Also change possible references to this in the documentation.

**Comment by dhowe** [comment]
Agreed, lets include this in new release.

**Comment by mneunomne** [comment]
Basically we need to change the translation... I wonder if there is a way for us to just import the changes from uBlock.

**Comment by dhowe** [comment]
Good question... I'm sure crowdin has export/import

**Comment by mneunomne** [comment]
Implemented in english https://github.com/dhowe/AdNauseam/pull/2287

**Comment by mneunomne** [comment]
Implemented, closing
