### ISSUE TITLE
Advault: data not visible for large ads with focus

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2049]
no way to zoom in on this info, as zooming in/out returns user to the full vault view:

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/737638/155828134-b6145e6e-6f85-43b4-8e83-183603adc1b7.png">

**Comment by mneunomne** [comment]
i think maybe we can add a maximum size to ads in the vault

**Comment by mneunomne** [comment]
Implemented a max width and height of `800px` to ad vault images. It should make the ad vault render with a nicer aspect i think.

**Comment by dhowe** [comment]
is this for normal display or focused display (or both) ?

**Comment by mneunomne** [comment]
For both, I am limiting the ad size in the grid itself. It also makes the grid look more balanced, since some ad images are absolutely huge for no apparent reason.
