### ISSUE TITLE
Advault: Sites showing up as ad networks

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2050]
<img width="319" alt="image" src="https://user-images.githubusercontent.com/737638/155829736-d8fc7ae8-e4d1-4226-92bb-08574dc854f5.png">

**Comment by mneunomne** [comment]
It seems it was at least meant that way. Should we not put an Ad Network if it doesnt hit any of the cases bellow?

https://github.com/dhowe/AdNauseam/blob/eef6feb173f2362e7c77a00ca69bd677f048b46a/src/js/adn/vault.js#L253-L283

**Comment by dhowe** [comment]
yes, I think we should leave that blank or 'unknown' if we don't know the network...
but we also need to add more networks

**Comment by mneunomne** [comment]
@dhowe we can add Youtube as part of google ad network right?

**Comment by dhowe** [comment]
sounds right

**Comment by mneunomne** [comment]
Fixed, closing
