### ISSUE TITLE
New errors in Chrome 98

### ISSUE THREAD

**Issue by Destroyinator69420** [dhowe/AdNauseam#2052]
The following code file is cited by chrome://extensions as the source of the error.
Error in event handler: TypeError: Cannot read properties of undefined (reading 'forceUpdate')
"""
case 'forceUpdateAdnauseam':
        µb.assets.forceUpdate("Adnauseam");
        break;
"""
"""
// Auxiliary process to main process: default handler
        if ( portDetails.privileged ) {
            r = this.defaultHandler(request.msg, portDetails, callback);
            if ( r !== this.UNHANDLED ) { return; }
        }
"""
"""
);
        port.onMessage.addListener((request, port) =>
            this.onPortMessage(request, port)
        );
        const portDetails = { port };
        const sender = port.sender;
        const { tab, url } = sender;
        portDetails.frameId = sender.frameId;
        portDetails.frameURL = url;
        portDetails.privileged = url.startsWith(this.PRIVILEGED_URL);
        if ( tab ) {
            portDetails.tabId = tab.id;
            portDetails.tabURL = tab.url;
        }
        this.ports.set(port.name, portDetails);
        // https://bugzilla.mozilla.org/show_bug.cgi?id=1652925#c24
        port.sender = undefined;
    },
"""
Error in event handler: TypeError: Assignment to constant variable.
"""
 if (name === 'referer') {
            refererIdx = i;
"""
"""
// if so, handle the headers (cookies, ua, referer, dnt)
        ad && beforeAdVisit(details, headers, prefs, ad, respectDNT);
"""
"""
makeNewListenerProxy(clientListener) {
        const actualListener = details => {
            this.normalizeDetails(details);
            return clientListener(details);
"""

I think that these can be fixed by merging with the latest ublock instead of lagging behind.
All the best,
Destroyer

**Comment by dhowe** [comment]
version of adnauseam / os?
location of log shown above?

**Comment by Destroyinator69420** [comment]
@dhowe I was using Chrome 98 on chrome OS at the time. I found the log in the adnauseam settings page on the chrome://extensions.

**Comment by dhowe** [comment]
and were there any 'symptoms' ? any problems you noticed, besides the message?

**Comment by mneunomne** [comment]
I would say this issue is now outdated, I imagine something to do with the 3pfilters page, but probably disappeared with the latest merges.
