### ISSUE TITLE
Ads visible on carousell.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2057]
URL: Ads visible on https://www.carousell.com.hk/

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/737638/158113955-36bc3633-2a60-4f08-975c-9cefcbfb9c42.png">

**Comment by mneunomne** [comment]
These ads seem to be manually implemented in the HTML itself, and all the links are internal except for the first one. So i'm not sure if there is anything we should do about it.

**Comment by dhowe** [comment]
can we add a blocking rule for the external call?

**Comment by mneunomne** [comment]
Is it still showing for you? For me the first element in the carrousel dissapeared

**Comment by dhowe** [comment]
same here
