### ISSUE TITLE
Consider switch from crowdin to weblate

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2058]
via email:
> Crowdin, according to their Privacy Policy, uses a considerable amount of user tracking, including Google DoubleClick and Analytics and Facebook (https://support.crowdin.com/cookies/). Isn't this in contradiction with the privacy principles guiding your extension?
> 
> I'd suggest Weblate. They have a free tier (https://hosted.weblate.org/about/), their Privacy Policy seems to be ok (https://hosted.weblate.org/legal/privacy/) and they don't seem to use Google cookies or the like.

**Comment by mneunomne** [comment]
Believe we should close this, if uBlock is using it i think it should be fine.
