### ISSUE TITLE
Activate Easylist Filter Warning

### ISSUE THREAD

**Issue by Noruas29** [dhowe/AdNauseam#2062]
If you don't activate the EasyList filter, an alert is displayed. However, I never activate EasyList because the filter produces some problems with French sites and the respect of the RGPD (display problems). On the other hand, the AdGuard Base filter (which is based on EasyList) does not cause any problems and has the same function as the EasyList filter.
You can see the documentation here:
[https://kb.adguard.com/en/general/adguard-filter-policy
](https://kb.adguard.com/en/general/adguard-filter-policy
)
This is neither a bug nor an issue but more a request to remove the warning when either EasyList or Adguard Base is activated (or both).

- OS/version: Manjaro
- Browser/version: Vivaldi 5.1.2567.66 (Stable channel) stable (64 bits) 
- AdNauseam version: v3.12.2
- AdNauseam settings: basic

### Your location/country
France

**Comment by mneunomne** [comment]
@dhowe should we simply remove the easylist filter warning then ?

**Comment by dhowe** [comment]
I think users with this case can check the 'disable warnings' option in settings... @Noruas29 does this work for you?

**Comment by mneunomne** [comment]
I think t his can be closed since it can be addressed with the "disable warnings" option.
