### ISSUE TITLE
General questions about addon-detection and ip-based tracking

### ISSUE THREAD

**Issue by ChaosNicro** [dhowe/AdNauseam#2064]
Hey there,
I am considering to put this in both my mobile Fennec and desktop Firefox installations, however there are two things that are keeping me:

Firstly, while I have taken big steps to eliminate Google from my devices and use webapps and alternative clients where I haven't been able to do that yet, I would like to avoid having my account terminated. Is that still an issue and how does ublock get a pass here, which I have been using for years? 

Secondly, is there any impact on privacy when making the http-requests to adservers? Do things like ip- or useragent-based profiling need to be mitigated separately? I suppose a dynamic ip isn't as vulnerable here but ADN could make fingerprinting much easier, right? 

As a final note: Is there a space for general discussion, like for example a Matrix-Room? It might help with keeping the GitHub focused on development.

Thanks in advance.

**Comment by dhowe** [comment]
If you don't mind I'll move this to our discussion section
