### ISSUE TITLE
AdNauseam's tags in its listing at addons.mozilla.org need additions. (suggestion/metadata enhancement)

### ISSUE THREAD

**Issue by elvey** [dhowe/AdNauseam#2067]
### Describe the issue
AdNauseam's [listing at addons.mozilla.org](https://addons.mozilla.org/firefox/addon/adnauseam/) should have more tags.

Why?  Because AdNauseam doesn't appear when I click, for example, at the popular page https://support.mozilla.org/en-US/kb/javascript-settings-for-interactive-web-pages on "[privacy extensions](https://addons.mozilla.org/firefox/search/?tag=privacy)". AdNauseam isn't listed, but adding the tag "privacy" would change that. 

Adding tags [appears to be self-service by the developer](https://extensionworkshop.com/documentation/develop/create-an-appealing-listing/#create-a-meaningful-set-of-keywords).  There are directions there, including "You can add these keywords as tags to your add-on listing (in the Basic Information section)."...

(I tried to find the content of the listing in the code base on github by searching and failed.)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

**AdNauseam's Tags:
*   ad blocker
* <yup! just one tag!>**

**Ghostery's Tags:**
* ad blocker
* anti malware
* content blocker

**UBO has Tags:**
* ad blocker
* anti malware
* anti tracker
* content blocker
* privacy
* security

**Comment by dhowe** [comment]
So I attempted to add additional tags, but I cannot find that section anywhere. Perhaps you can only add them when you initially submit?
