### ISSUE TITLE
Estimate current daily useage and download numbers for ADN

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2070]
We need a) a quick answer, and b) a good method, in the longer term for estimating these data.

For daily usage, please check all the app stores, and add together with an estimate for Chrome. For example, Firefox is around 40k daily users.

Not exactly sure how to handle ongoing and total download numbers, but we need a best estimate of these.

Can also use the number of downloads from github releases...

**Comment by mneunomne** [comment]
Extracted data of download_counts for the last version:

"name": "v3.12.2",
        "name": "adnauseam-3.12.2.chromium.crx",
        "download_count": 1155,
        "name": "adnauseam-3.12.2.chromium.zip",
        "download_count": 3025,
        "name": "adnauseam-3.12.2.edge.zip",
        "download_count": 247,
        "name": "adnauseam-3.12.2.firefox.zip",
        "download_count": 130,
        "name": "adnauseam-3.12.2.opera.crx",
        "download_count": 82,
        "name": "adnauseam.chromium.zip",
        "download_count": 2653,
    "name": "v3.12.1",
        "name": "adnauseam-3.12.1.chromium.crx",
        "download_count": 7,
        "name": "adnauseam-3.12.1.chromium.zip",
        "download_count": 44,
        "name": "adnauseam-3.12.1.edge.zip",
        "download_count": 9,
        "name": "adnauseam-3.12.1.firefox.zip",
        "download_count": 10,
        "name": "adnauseam-3.12.1.opera.crx",
        "download_count": 7,
    "name": "v3.11.4",
        "name": "adnauseam-3.11.4.chromium.crx",
        "download_count": 288250,
        "name": "adnauseam-3.11.4.chromium.zip",
        "download_count": 11415,
        "name": "adnauseam-3.11.4.edge.zip",
        "download_count": 982,
        "name": "adnauseam-3.11.4.firefox.zip",
        "download_count": 483,
        "name": "adnauseam-3.11.4.opera.crx",
        "download_count": 305,
    "name": "v3.11.3 (rc3)",
        "name": "adnauseam-3.11.3.chromium.crx",
        "download_count": 8,
        "name": "adnauseam-3.11.3.chromium.zip",
        "download_count": 67,
        "name": "adnauseam-3.11.3.edge.zip",
        "download_count": 6,
        "name": "adnauseam-3.11.3.firefox.zip",
        "download_count": 9,
        "name": "adnauseam-3.11.3.opera.crx",
        "download_count": 7,
    "name": "v3.11.2 (rc2)",
        "name": "adnauseam-3.11.2.chromium.crx",
        "download_count": 32,
        "name": "adnauseam-3.11.2.chromium.zip",
        "download_count": 92,
        "name": "adnauseam-3.11.2.edge.zip",
        "download_count": 16,
        "name": "adnauseam-3.11.2.firefox.zip",
        "download_count": 13,
        "name": "adnauseam-3.11.2.opera.crx",
        "download_count": 9,
    "name": "v3.10.4",
        "name": "adnauseam-3.10.4.chromium.crx",
        "download_count": 118348,
        "name": "adnauseam-3.10.4.chromium.zip",
        "download_count": 6111,
        "name": "adnauseam-3.10.4.edge.zip",
        "download_count": 477,
        "name": "adnauseam-3.10.4.firefox.zip",
        "download_count": 236,
        "name": "adnauseam-3.10.4.opera.crx",
        "download_count": 226,
    "name": "v3.10.3",
        "name": "adnauseam-3.10.3.chromium.crx",
        "download_count": 3935,
        "name": "adnauseam-3.10.3.chromium.zip",
        "download_count": 206,
        "name": "adnauseam-3.10.3.edge.zip",
        "download_count": 15,
        "name": "adnauseam-3.10.3.firefox.zip",
        "download_count": 15,
        "name": "adnauseam-3.10.3.opera.crx",
        "download_count": 3,
    "name": "v3.10.2",
        "name": "uBlock0_v3.10.2.chromium.zip",
        "download_count": 2,
    "name": "v3.10.1rc5",
        "name": "adnauseam-3.10.1.5.chromium.crx",
        "download_count": 8,
        "name": "adnauseam-3.10.1.5.chromium.zip",
        "download_count": 15,
        "name": "adnauseam-3.10.1.5.edge.zip",
        "download_count": 3,
        "name": "adnauseam-3.10.1.5.firefox.zip",
        "download_count": 5,
        "name": "adnauseam-3.10.1.5.opera.crx",
        "download_count": 1,
        "name": "uBlock0_v3.10.1rc5.chromium.zip",
        "download_count": 2,
    "name": "v3.10.1rc4",
        "name": "uBlock0_v3.10.1rc4.chromium.zip",
        "download_count": 2,
    "name": "v3.10.1rc3",
        "name": "adnauseam-3.10.1.3.chromium.crx",
        "download_count": 9,
        "name": "adnauseam-3.10.1.3.chromium.zip",
        "download_count": 16,
        "name": "adnauseam-3.10.1.3.edge.zip",
        "download_count": 1,
        "name": "adnauseam-3.10.1.3.firefox.zip",
        "download_count": 8,
        "name": "adnauseam-3.10.1.3.opera.crx",
        "download_count": 4,
    "name": "",
        "name": "adnauseam-3.9.201.chromium.crx",
        "download_count": 355802,
        "name": "adnauseam-3.9.201.chromium.zip",
        "download_count": 22436,
        "name": "adnauseam-3.9.201.edge.zip",
        "download_count": 1631,
        "name": "adnauseam-3.9.201.firefox.zip",
        "download_count": 737,
        "name": "adnauseam-3.9.201.opera.crx",
        "download_count": 393,
    "name": "",
        "name": "adnauseam-3.9.2.chromium.crx",
        "download_count": 7522,
        "name": "adnauseam-3.9.2.chromium.zip",
        "download_count": 300,
        "name": "adnauseam-3.9.2.edge.zip",
        "download_count": 35,
        "name": "adnauseam-3.9.2.firefox.zip",
        "download_count": 28,
        "name": "adnauseam-3.9.2.opera.crx",
        "download_count": 15,
    "name": "",
        "name": "adnauseam-3.9.108.chromium.crx",
        "download_count": 3767,
        "name": "adnauseam-3.9.108.chromium.zip",
        "download_count": 3872,
        "name": "adnauseam-3.9.108.firefox.zip",
        "download_count": 163,
        "name": "adnauseam-3.9.108.opera.crx",
        "download_count": 78,
    "name": "",
        "name": "adnauseam-3.9.107.chromium.crx",
        "download_count": 872,
        "name": "adnauseam-3.9.107.chromium.zip",
        "download_count": 510,
        "name": "adnauseam-3.9.107.firefox.zip",
        "download_count": 59,
        "name": "adnauseam-3.9.107.opera.crx",
        "download_count": 21,
    "name": "",
        "name": "adnauseam-3.9.106.chromium.crx",
        "download_count": 592,
        "name": "adnauseam-3.9.106.chromium.zip",
        "download_count": 217,
        "name": "adnauseam-3.9.106.firefox.zip",
        "download_count": 54,
        "name": "adnauseam-3.9.106.opera.crx",
        "download_count": 13,
    "name": "",
        "name": "adnauseam-3.9.104.chromium.crx",
        "download_count": 6184,
        "name": "adnauseam-3.9.104.chromium.zip",
        "download_count": 7819,
        "name": "adnauseam-3.9.104.firefox.zip",
        "download_count": 292,
        "name": "adnauseam-3.9.104.opera.crx",
        "download_count": 222,
    "name": "",
        "name": "adnauseam-3.9.103.chromium.crx",
        "download_count": 3,
        "name": "adnauseam-3.9.103.chromium.zip",
        "download_count": 572,
        "name": "adnauseam-3.9.103.firefox.zip",
        "download_count": 39,
        "name": "adnauseam-3.9.103.opera.crx",
        "download_count": 3,
    "name": "",
        "name": "adnauseam-3.9.102.chromium.crx",
        "download_count": 1796,
        "name": "adnauseam-3.9.102.chromium.zip",
        "download_count": 1035,
        "name": "adnauseam-3.9.102.firefox.zip",
        "download_count": 59,
        "name": "adnauseam-3.9.102.opera.crx",
        "download_count": 43,
    "name": "",
        "name": "adnauseam-3.8.401.chromium.crx",
        "download_count": 5777,
        "name": "adnauseam-3.8.401.chromium.zip",
        "download_count": 6515,
        "name": "adnauseam-3.8.401.firefox.zip",
        "download_count": 240,
        "name": "adnauseam-3.8.401.opera.crx",
        "download_count": 108,
    "name": "",
        "name": "adnauseam-3.8.302.chromium.crx",
        "download_count": 3811,
        "name": "adnauseam-3.8.302.chromium.zip",
        "download_count": 3547,
        "name": "adnauseam-3.8.302.firefox.zip",
        "download_count": 170,
        "name": "adnauseam-3.8.302.opera.crx",
        "download_count": 82,
    "name": "",
        "name": "adnauseam-3.8.201.chromium.crx",
        "download_count": 10,
        "name": "adnauseam-3.8.201.chromium.zip",
        "download_count": 3713,
        "name": "adnauseam-3.8.201.firefox.zip",
        "download_count": 170,
        "name": "adnauseam-3.8.201.opera.crx",
        "download_count": 692,
    "name": "",
        "name": "adnauseam-3.8.101.chromium.zip",
        "download_count": 1291,
        "name": "adnauseam-3.8.101.firefox.zip",
        "download_count": 101,
        "name": "adnauseam-3.8.101.opera.crx",
        "download_count": 249,
    "name": "",
        "name": "adnauseam-3.7.802.chromium.crx",
        "download_count": 10288,
        "name": "adnauseam-3.7.802.chromium.zip",
        "download_count": 15681,
        "name": "adnauseam-3.7.802.firefox-legacy.xpi",
        "download_count": 746,
        "name": "adnauseam-3.7.802.firefox.zip",
        "download_count": 543,
        "name": "adnauseam-3.7.802.opera.nex",
        "download_count": 241,
    "name": "Release v3.7.801",
        "name": "adnauseam-3.7.801.chromium.crx",
        "download_count": 34,
        "name": "adnauseam-3.7.801.chromium.zip",
        "download_count": 37,
        "name": "adnauseam-3.7.801.firefox-legacy.xpi",
        "download_count": 80,
        "name": "adnauseam-3.7.801.firefox.zip",
        "download_count": 15,
        "name": "adnauseam-3.7.801.opera.nex",
        "download_count": 12,
    "name": "Release v3.7.101",
        "name": "adnauseam-3.7.101.chromium.crx",
        "download_count": 62252,
        "name": "adnauseam-3.7.101.chromium.zip",
        "download_count": 3871,
        "name": "adnauseam-3.7.101.firefox-legacy.xpi",
        "download_count": 153,
        "name": "adnauseam-3.7.101.firefox.zip",
        "download_count": 81,
        "name": "adnauseam-3.7.101.opera.nex",
        "download_count": 61,
    "name": "",
        "name": "adnauseam-3.6.205.chromium.crx",
        "download_count": 122378,
        "name": "adnauseam-3.6.205.chromium.zip",
        "download_count": 3750,
        "name": "adnauseam-3.6.205.firefox-legacy.xpi",
        "download_count": 208,
        "name": "adnauseam-3.6.205.firefox.zip",
        "download_count": 108,
        "name": "adnauseam-3.6.205.opera.nex",
        "download_count": 62,
    "name": "Release v3.5.1",
        "name": "adnauseam-3.5.101.chromium.crx",
        "download_count": 8580,
        "name": "adnauseam-3.5.101.chromium.zip",
        "download_count": 10783,
        "name": "adnauseam-3.5.101.firefox-legacy.xpi",
        "download_count": 639,
        "name": "adnauseam-3.5.101.firefox-webext.zip",
        "download_count": 295,
        "name": "adnauseam-3.5.101.opera.nex",
        "download_count": 192,
    "name": "Release v3.4.4",
        "name": "adnauseam-3.4.402.chromium.crx",
        "download_count": 3457,
        "name": "adnauseam-3.4.402.chromium.zip",
        "download_count": 3613,
        "name": "adnauseam-3.4.402.firefox-legacy.xpi",
        "download_count": 430,
        "name": "adnauseam-3.4.402.firefox-webext.zip",
        "download_count": 170,
        "name": "adnauseam-3.4.402.opera.nex",
        "download_count": 77,
    "name": "Release v3.4.2",
        "name": "adnauseam-3.4.202.chrome.crx",
        "download_count": 1835,
        "name": "adnauseam-3.4.202.chromium.zip",
        "download_count": 2077,
        "name": "adnauseam-3.4.202.firefox-legacy.xpi",
        "download_count": 225,
        "name": "adnauseam-3.4.202.firefox-webext.zip",
        "download_count": 68,
        "name": "adnauseam-3.4.202.opera.nex",
        "download_count": 45,

**Comment by mneunomne** [comment]
Plotting all the combined downloads for each version from the github API it looks like this:

![Screenshot 2022-04-01 at 14 14 33](https://user-images.githubusercontent.com/4967860/161261407-bba6aea9-2c37-4163-b7b3-e290c574aaf0.png)

I am not sure if automatic downloads shape these numbers, they seem a bit absurly high (highest value being 355802 for version 3.9.201)

I can make this script better, and upload it somewhere so we can keep track of it in the future.

**Comment by mneunomne** [comment]
These are the numbers from uBlock, which are much smaller than AdNauseam. But that *perhaps* makes sense, since uBlock is at the Chrome Store and we aren't...

![Screenshot 2022-04-01 at 14 28 31](https://user-images.githubusercontent.com/4967860/161263411-19e243df-aab6-451e-857c-f77ddb7410b6.png)

**Comment by dhowe** [comment]
Right. One would imagine that a) the vast majority of downloads are from Google Chrome users for whom this is the only option, and b) this includes some number of bots, as (I imagine) most downloads counts do. 

Please check the other stores as well (Opera, Edge, etc.)

**Comment by mneunomne** [comment]
## Edge

2,000+‬ Users

## Firefox

39,601 Users

## Opera

Current at around 200 weekly downloads, with 172,120 in total. Not sure what that would mean for active users.

## Chrome

From the numbers It seems that up to 100k users would not be an over-estimation...

**Comment by hfn1** [comment]
Downloads vs users?  Seems we only have good download numbers. What if we
stick to that?

Sent from my iPhone

On Apr 1, 2022, at 09:07, Alberto Harres ***@***.***> wrote:

﻿

Edge

2,000+‬ Users
Firefox

39,601 Users
Opera

Current at around 200 weekly downloads, with 172,120 in total. Not sure
what that would mean for active users.
Chrome

From the numbers It seems that up to 100k users would not be an
over-estimation...

—
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dhowe_AdNauseam_issues_2070-23issuecomment-2D1085878318&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=EqY2RwQR-VG3CtL0LzAt_2i95_uQxaX-fiVNvnCyuZU&m=vdSvdsF9eoeGf9MuWesWfQGXXQ8KqdXog4az7Ru6sg6Zqwr6pLb5C7FWe58WlYk2&s=YRRldmaaVtIC6hw-NyePhnHDRW98zXZelXPT0r0NDak&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AB5244IWSXEMRARYUKKPDQLVC3YH5ANCNFSM5SHSE2TA&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=EqY2RwQR-VG3CtL0LzAt_2i95_uQxaX-fiVNvnCyuZU&m=vdSvdsF9eoeGf9MuWesWfQGXXQ8KqdXog4az7Ru6sg6Zqwr6pLb5C7FWe58WlYk2&s=YUEJSVyzoGU_IjVQ6rC1iQbhXBlcI69CwCp1j62oKeo&e=>
.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by mneunomne** [comment]
@dhowe above are the numbers I could currently retrieve. The download numbers from Firefox and Edge I can't currently access.
