### ISSUE TITLE
AdNauseum breaking Material Icons

### ISSUE THREAD

**Issue by KTibow** [dhowe/AdNauseam#2072]
### Describe the issue

*NOTE: if you are having a problem where ads are not collected, please FIRST TRY to create a new new Firefox profile as described [here](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_creating-a-profile). A corrupt Firefox profile is the most common cause of this issue.*

I was working on making a new site using Material Icons, but the font seemed to not load. I checked the Network tab of devtools and the `woff2` file was being blocked by AdNauseam.

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/10727862/161392270-7a6518c9-b6fb-43bc-9740-41cd3bf488d7.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
Go to [this example](https://jsfiddle.net/wmy2Lfa0/) with AdNauseum on. See the text not being an icon. Turn off AdNauseum on that page. Press Run (upper-left). See the text being an icon.

### Your settings

- OS/version: Ubuntu 21.10
- Browser/version: Firefox 98.0.2
- AdNauseam version: v3.12.2
- Other extensions you have installed: 
![image](https://user-images.githubusercontent.com/10727862/161392371-68397e30-4f37-4713-b26e-d71e736aa0d5.png)

- AdNauseam settings: [AdNauseam_Settings_Export_4.2.2022.9.33.03AM.TXT](https://github.com/dhowe/AdNauseam/files/8402943/AdNauseam_Settings_Export_4.2.2022.9.33.03AM.TXT)

##### Your filter lists
![image](https://user-images.githubusercontent.com/10727862/161392420-3fb60a88-c21e-4a9e-8285-7f0e989c6efb.png)

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
Not relevant
** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

**Comment by mneunomne** [comment]
Thank you @KTibow for reporting the issue, I'm submiting a change to our filter list that should fix this issue. Once it is merged you can updated and it should be fixed.

On the mean time you can add the following rule to avoid this:
```
@@||gstaticadssl.l.google.com^$~font,third-party,~xmlhttprequest
```

**Comment by mneunomne** [comment]
Fixed, closing
