### ISSUE TITLE
Reset CSS + HTML for future merges 

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2073]
At the moment we are accumulating a huge edits in the CSS+HTML code that are getting harder and harder to do the merges. uBlock changes the HTML structure rather often, and since AdNauseam built the interface based on uBlock code quite a few version ago, as times goes, it become more and more difficult to keep track of the changes.

#### There are two options for future development:

1. On the code level, reset all css and html files that are shared exactly as uBlock has it, then adapt it once again to AdNauseam, in a clean way.
2. Create our own html + css files from scratch with different file names, so we don't automatically merge, and just pull the uBlock code when we think is necessary. 

#### Notes

- The first option has the advantage of using uBlock well structured style, where we can make a AdNauseam theme, rather than simply replacing the colors etc manually. 
- The second has the advantage of not creating so much issues with the merges, the only thing we need to be aware of is when something in the HTML structure affects the interactions in JavaScript.
- Another option is a mixture of both, selecting what html files we don't want to be tracked by git, and the ones that we do.
- If we want some design re-vamp, this would be a good time to do that.

**Comment by dhowe** [comment]
Defer to your opinion here

**Comment by mneunomne** [comment]
Can you expand?

**Comment by mneunomne** [comment]
I might have to do this for the version 1.41.0 already... perhaps at least partially, there are a lot of css changes...

**Comment by mneunomne** [comment]
## To do

- [ ] Re-writte again the dashboard HTML pages based on uBlock structure.
- [ ] Reset css files to the uBlock state on v1.41.0, and start re-styling the theme back to Adnauseam's design
- [ ] Create an AdNauseam theme on uBlock? (Check uBlock docuumentation on themes to see what is possible)
- [ ] Improve some class/id names to be more consistent with uBlock's pattern
- [ ] Scan & Update the JS files for any reference to the HTML that were updated

**Comment by mneunomne** [comment]
Changed this to High Priority since this is one of the major reasons why the merges have been getting more problematic.

**Comment by mneunomne** [comment]
The more i work on this the more i realize the nightmare it is.

im trying without success to rest the css and html to the current uBlock standard... But I wonder if that is a smart decision, since it is so often changed.

Perhaps the wisest decision at the moment is simply "freeze" the adnauseam css putting it on a different folder and stop pulling ublock css changes all together.

I'll keep working on this to see what makes the most sense

**Comment by mneunomne** [comment]
I spent some time looking at this. It doesn't seem to make sense for us to reset everything. Indeed a best practice would be to make Adnauseam styles a theme instead of direct edits to the uBlock style, but doesn't seem like it's worth the efford at this moment.

The previous 2 merges address the more important issues which were the inconsitencies in checkboxes, some button issues and the general theme coloring in the uBlock menu and logger.

I would say we can close this and just keep an eye on the more drastic style changes in uBlock to keep it more-or-less update.

But __IF__ we ever get approved again for Firefox Android, then probably yes we need to clean up a lot.

**Comment by mneunomne** [comment]
CSS has now become more stable and easier to merge since the latest big style structure changes that happened in the last few versions. I will be closing now since this doesn't seem to be an issue in the current releases.
