### ISSUE TITLE
Manifest version 2 is deprecated

### ISSUE THREAD

**Issue by ice-fly** [dhowe/AdNauseam#2084]
## Describe the issue
**Manifest version 2 is deprecated**, and support will be removed in **June 2023**. At that time, Manifest V2 extensions no longer function in Chrome even with the use of enterprise policy.
Unfortunately not just as easy as changing to V3 or running a script on the V2 json... [Migration to manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/)
Main thing that will need to be done is to [Migrate from backround.page to a background.service_worker](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/)
See: [V3 Migration Checklist](https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/)
![image](https://user-images.githubusercontent.com/11548922/164955204-3bc31159-65de-47d2-8596-ce73b6fc7cfa.png)
### AdNauseam Version
3.13.0.1
### Steps for anyone to reproduce the issue
Load unpacked Extension into Chrome

**Comment by mneunomne** [comment]
Thank you @ice-fly , we already have an issue for this https://github.com/dhowe/AdNauseam/issues/2055

I'll wait a bit for uBlock to change theirs so we can pull and keep in sync. 

Closing this for now since its duplicate
