### ISSUE TITLE
Implement "support" tab, like uBlock Origin

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2086]
uBlock has now the "support" tab, which makes easier for users to find documentation info and also copy+paste current settings when creating an issue. 

We should consider implement a page like this.

<img width="816" alt="Screenshot 2022-04-27 at 15 28 28" src="https://user-images.githubusercontent.com/4967860/165529826-c539bc12-b597-4777-9591-5c791b64e647.png">

<img width="822" alt="Screenshot 2022-04-27 at 15 28 30" src="https://user-images.githubusercontent.com/4967860/165529813-2f228184-3c79-4b22-b402-7ef568370840.png">

**Comment by mneunomne** [comment]
@dhowe should we use a different text as uBlock on this page? I'm not sure how ok it is for us to "copy" the text itself and just make the tweaks in relation to Adnauseam...

**Comment by dhowe** [comment]
Its pretty straightforward stuff, and we are clear that we are a fork of ublock, so I wouldn't worry about it... But also feel free to make changes that you think would be useful to users

**Comment by mneunomne** [comment]
Original ublock text:
------------------------------- 

### Documentation

Read the documentation at uBlock/wiki to learn about all of AdNauseam's features.

### Questions and support
Answers to questions and other kinds of help support is provided on the subreddit /r/uBlockOrigin.

### Filter issues/website is broken

Report filter issues with specific websites to the uBlockOrigin/uAssets issue tracker. Requires a GitHub account.

__Important__: Avoid using other similarly-purposed blockers along with AdNauseam, as this may cause filter issues on specific websites.

__Tips__: Be sure your filter lists are up to date. The logger is the primary tool to diagnose filter-related issues.

### Bug report

Report issues with AdNauseam itself to the uBlockOrigin/uBlock-issue issue tracker. Requires a GitHub account.

**Comment by mneunomne** [comment]
Current text with auto-replace from "ublock origin" to "adnauseam":
------------------------------- 

### Documentation

Read the documentation at Adnauseam/wiki to learn about all of AdNauseam's features.

### Questions and support

Answers to questions and other kinds of help support is provided ~~on the subreddit /r/uBlockOrigin~~ at the Github Discussion page.

### Filter issues/website is broken

Report filter issues with specific websites to the uBlockOrigin/uAssets issue tracker. Requires a GitHub account.

__Important__: Avoid using other similarly-purposed blockers along with AdNauseam, as this may cause filter issues on specific websites.

__Tips__: Be sure your filter lists are up to date. The logger is the primary tool to diagnose filter-related issues.

### Bug report

Report issues with AdNauseam itself to the dhoweAdnauseam issue tracker. Requires a GitHub account.

**Comment by dhowe** [comment]
Edited page for AdNauseam
------------------------------- 

### Documentation

Read the documentation on the [AdNauseam wiki]() to learn about all of AdNauseam's features.

### Questions and support

Answers to questions and other kinds of help support are provided on our Github [discussion page]().

### Filter issues/website is broken

Report filter issues with specific websites to the AdNauseam [issue tracker]() (requires a GitHub account).

__Important__: Avoid using other similarly-purposed blockers along with AdNauseam, as this may cause filter issues on some websites.

__Tips__: Be sure your filter lists are up to date. The logger is the primary tool to diagnose filter-related issues.

### Bug report

Report any issues with AdNauseam itself on our [issue tracker]() (requires a GitHub account).

**Comment by dhowe** [comment]
Looks good -- I made some edits above. Can you add in the links?

**Comment by mneunomne** [comment]
> A question: is that the right location for filter list issues in uBlock?

This is the link: https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue

But I wonder about one thing: Usually when adnauseam has problems with ads appearing its because of our "adn-allow" feature. So I guess we shouldn't foward issues by default to uBlock Origin, since for general (and perhaps even for advanced ones) it is kind of hard to know if the problem is Adnauseam specific.

What we can do is to we add in the text the suggestion to make sure that the issue is adn specific (as we already do in the new issue template in github)

**Comment by mneunomne** [comment]
And btw, uBlock new About page is also different design now, has much more information than ours:

<img width="610" alt="Screenshot 2022-05-22 at 01 46 24" src="https://user-images.githubusercontent.com/4967860/169672645-e4ca9175-e9ff-4ed1-a0d5-8d23613cd211.png">

uBlock Origin 1.42.4

Copyright (c) Raymond Hill 2014-present
[Privacy policy](https://github.com/gorhill/uBlock/wiki/Privacy-policy)
[Changelog](https://github.com/gorhill/uBlock/releases)
[Source code (GPLv3)](https://github.com/gorhill/uBlock)

Contributors
[Source code](https://github.com/gorhill/uBlock/graphs/contributors)
[Translations](https://crowdin.com/project/ublock)
[Filter lists](https://github.com/uBlockOrigin/uAssets/graphs/contributors)

External dependencies (GPLv3-compatible):
[CodeMirror](https://codemirror.net/) by [Marijn Haverbeke](https://github.com/marijnh)
[Punycode.js](https://github.com/bestiejs/punycode.js) by [Mathias Bynens](https://github.com/mathiasbynens)
[Metropolis font family](https://github.com/chrismsimpson/Metropolis) by [Chris Simpson](https://github.com/chrismsimpson)
[Inter font family](https://github.com/rsms/inter) by [Rasmus Andersson](https://github.com/rsms)
[FontAwesome font family](https://fontawesome.com/) by [Dave Gandy](https://github.com/davegandy)
[An implementation of Myers' diff algorithm](https://github.com/Swatinem/diff) by [Arpad Borsos](https://github.com/Swatinem)
[Regular Expression Analyzer](https://github.com/foo123/RegexAnalyzer) by [Nikos M.](https://github.com/foo123)
[HSLuv - Human-friendly HSL](https://github.com/hsluv/hsluv) by [Alexei Boronine](https://github.com/boronine)

uBO's own filter lists are freely hosted on the following [CDNs](https://wikipedia.org/wiki/Content_delivery_network):
[Cloudflare Pages](https://pages.cloudflare.com/), [Combinatronics](https://combinatronics.io/), [GitCDN](https://gitcdn.xyz/), [GitHub Pages](https://pages.github.com/), [jsDelivr](https://www.jsdelivr.com/), [Statically](https://statically.io/)
A randomly picked CDN is used when a filter list needs to be updated

**Comment by mneunomne** [comment]
implemented, closing
