### ISSUE TITLE
Ads visible on machinelearningknowledge.ai

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2090]
https://machinelearningknowledge.ai/tutorial-on-spacy-part-of-speech-pos-tagging/

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/737638/166460399-c69d2241-5dc9-4ac4-b12b-288d3a1d359d.png">

**Comment by mneunomne** [comment]
This is an internal ad. Not really worth it to ad to our filter list I think. The image is hosted in the same domain:

https://machinelearningknowledge.ai/ezoimgfmt/merchant.linksynergy.com/fs/banners/39197/39197_15033.png?ezimgfmt=rs:728x90/rscb1/ng:webp/ngcb1

**Comment by dhowe** [comment]
the target href is actually external, so its sort of a gray area, but it does seem to be fed by an ad network (https://click.linksynergy.com/fs-bin/click), which argues for fixing it
