### ISSUE TITLE
Warnings in Google Chrome v100

### ISSUE THREAD

**Issue by Destroyinator69420** [dhowe/AdNauseam#2097]
### Describe the issue

Adnauseam throws the following errors in chrome://extensions:

"""
js/messaging.js:183 (Object.onMessage [as defaultHandler])
js/vapi-background.js:1070 (Object.onPortMessage)
js/vapi-background.js:851 (anonymous function)
"""

The error syntax is "file:linenumber_error type."

### Steps for anyone to reproduce the issue
Use adnauseam on chrome 100 on a chromebook
enable "collect errors"
browse the web for a while
check back on adnauseam's chrome://extensions page after a while

### Your settings

- OS/version: Chrome OS stable version 100 platform 14526.89.0
- Browser/version: Chrome
- AdNauseam version: 1.13.1
- Other extensions you have installed: trackmenot, privacy pass, auto clicker, kami, clearurls, iba opt out, google analytics opt out
- AdNauseam settings: click all ads, hide all ads, block malware, remove ads collected in private mode, disable pre-fetching, disable hyperlink auditing, prevent webrtc from leaking local ip addresses

##### Your filter lists
all preinstalled essential filter lists
all preinstalled privacy filter lists
all preinstalled malware filter lists
ublock annoyances

### Your location/country
California, USA

** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

N/A

**Comment by dhowe** [comment]
does this cause any problematic behavior that you notice thus far ?

**Comment by Destroyinator69420** [comment]
not that I can notice on the websites I browse, but it may be affecting the extension internally. Chrome developer tools are not good enough for me to tell. You might want to update the upstream ublock, these issues might have been fixed there.

**Comment by mneunomne** [comment]
Thank you @Destroyinator69420, we will update to the upstream ublock as soon as possible.

**Comment by mneunomne** [comment]
This seems to be fixed after the 1.41.0 merge, closing
