### ISSUE TITLE
Update Wiki to Include MacOS Chrome Instructions

### ISSUE THREAD

**Issue by tthorntone** [dhowe/AdNauseam#2101]
Hello AdNauseam team! I found a procedure for getting rid of that annoying warning in MacOS Chrome, and wanted to share it out.

I forked the Wiki, as found here: [Main New Article](https://github.com/tthorntone/AdNauseam-Wiki/blob/adds-chrome-mac-os-instructions/Install-AdNauseam-in-Chrome-on-MacOS.md)

The files i've touched are:
1. Added: Install-AdNauseam-in-Chrome-on-MacOS.md -- Detailed instructions on how to do what we already do for Windows, in MacOs
2. Install-AdNauseam-in-Chrome-on-Windows.md -- Just updated the current extension id, since I was in here anyways.
3. Install-AdNauseam-on-Chromium-based-browsers.md -- Link to the new page.

Let me know if you have any questions! Doesn't seem like there's a nice way to submit PRs for Wiki updates, which is kinda sad, otherwise I would've done that :(

**Comment by dhowe** [comment]
This is great, thanks @tthorntone

**Comment by mneunomne** [comment]
Awesome, thank you @tthorntone I updated the wiki:

- https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-in-Chrome-on-MacOS
- https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-in-Chrome-on-Windows
- https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chromium-based-browsers

**Comment by mneunomne** [comment]
Closing, thank you again @tthorntone )))
