### ISSUE TITLE
Cleanup formatting of Firefox page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2103]
the part below the ***

<img width="848" alt="image" src="https://user-images.githubusercontent.com/737638/170943170-ee70bf79-808d-449b-9e7a-5d437c0bf6a7.png">

**Comment by mneunomne** [comment]
## Edit

AdNauseam not only blocks ads, it obfuscates browsing data to resist tracking by the online ad industry. To throw ad networks off your trail AdNauseam “clicks” blocked and hidden ads, polluting your data profile and injecting noise into the economic system that drives online surveillance. The interactive AdVault allows you to visualize and explore the ads that AdNauseam has captured.

***
- For best results, disable 'Strict mode' for 'Enhanced Tracking Protection.- If you have either of the following settings enabled, make sure to allow AdNauseam in private browsing mode:-- History -> "Never remember history"-- History -> "Use custom settings for history" -> "Always use private browsing mode"
--

**Comment by mneunomne** [comment]
We can improve with some html tags:

![Screenshot 2022-05-30 at 14 22 46](https://user-images.githubusercontent.com/4967860/170991497-363924b1-4948-4fdd-a416-538c5e875797.png)

**Comment by mneunomne** [comment]
<b><a href="http://adnauseam.io/">AdNauseam</a></b> not only blocks ads, it <b>obfuscates</b> browsing data to resist tracking by the online ad industry. To throw ad networks off your trail AdNauseam “clicks” blocked and hidden ads, polluting your data profile and injecting noise into the economic system that drives online surveillance. The interactive AdVault allows you to visualize and explore the ads that AdNauseam has captured.

<ul><b>If you have either of the following settings enabled, make sure to allow AdNauseam in private browsing mode:</b>
<li>History -> "<em>Never remember history</em>"</li>
<li>History -> "<em>Use custom settings for history</em>" -> "<em>Always use private browsing mode</em>"</li>
</ul>

**Comment by mneunomne** [comment]
@dhowe should we add some more "tips" into the description ?

**Comment by dhowe** [comment]
sure, what do you have in mind  ?

**Comment by mneunomne** [comment]
I was thinking that we could put the suggestion regarding the strick security settings of Firefox that interferes with Adn, but perhaps that is an unnecessary information given that a warning already appears in our interface. I will update as it is above. If we come up with extra things, I'll change again.

**Comment by mneunomne** [comment]
<img width="702" alt="Screenshot 2022-06-06 at 23 04 06" src="https://user-images.githubusercontent.com/4967860/172248979-94da207f-a345-4aea-82e5-63deb6f38688.png">

**Comment by mneunomne** [comment]
Fixed, closing
