### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by venkat2305** [dhowe/AdNauseam#2105]
auto backup settings and ads to a local folder. Is it possible to add this feature?

**Comment by mneunomne** [comment]
Thanjk you @venkat2305 for your feedback. Do you mean an accessible folder with the updated data files of ads and settings?
 
I am not sure yet what would be a sensible way to implement this. Could perhaps expand on the context that you felt like this feature was needed?

**Comment by venkat2305** [comment]
> Thanjk you @venkat2305 for your feedback. Do you mean an accessible folder with the updated data files of ads and settings?
>  
> I am not sure yet what would be a sensible way to implement this. Could perhaps expand on the context that you felt like this feature was needed?  

If theres a folder which will be update ads and settings of adnauseam, I can easily sync the folder to cloud. If somehow I lost the data, it will be easily available on the cloud for me to restore again.

**Comment by mneunomne** [comment]
I checked this and apparently seems not to be viable in our case. The browser has the extension data but in compiled format, not in the format we need.

To have auto-save feature would imply some kind of backend structure which really isn't on our current plans from my perspective.

**Comment by dhowe** [comment]
Is it not possible to sync the entire profile folder, either for this addon, or for all your addons ?

**Comment by mneunomne** [comment]
Seems like for any addon. It is not something we can implement. 

[venkat2305](https://github.com/venkat2305) but apparently Firefox has this as a feature to sync addon across multiple devices, perhaps using this could be useful?

https://wiki.mozilla.org/Services/Sync/Features/Addon_Sync

**Comment by mneunomne** [comment]
Think this won't be possible to be implemented, @dhowe we can close this i believe.
