### ISSUE TITLE
$important blocks from "My Filters" and "Adnauseam Filters" are being adn-allowed 

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2110]
## The issue

Some filters are not working on 'my filters', specially the ones trying to overturn a adn-allow rule. 

The problem seems to lie in the "StaticFilteringParser". Where the filter added in "my filters" can't be found by the `listsForFilter" function:

https://github.com/dhowe/AdNauseam/blob/9d4ed7df4ae9918acd396f4bce7b086686c64376/src/js/adn/core.js#L1100-L1152

Catched this while trying to solve [this issue](https://github.com/dhowe/AdNauseam/issues/2108).

## How to reproduce:

- Url: https://yts.land/movie/free-guy-2021-staycalmtorrent144/
- Check that the following rule is being 'adn-allowed': `||dozubatan.com^`
- Try to reverse it by adding in "my filters" the following: `||dozubatan.com^$important`
- You'll see that the rule is still being adn-allowed rather than blocked.

**Comment by mneunomne** [comment]
I didn't catch this since our workflow was not in our test set, I just added referencing this issue:

> - [ ]  Test reversing 'adn-allow' rules on "My Filters" (e.g.: https://github.com/dhowe/AdNauseam/issues/2110)

**Comment by mneunomne** [comment]
This is tricky, seems that the issue happens before the function I have mentioned above. Not sure why the "$important" tag is not being picked up when set in "My Filters"

**Comment by mneunomne** [comment]
okay, seems I figured out what was the problem. 

There are actually two issues happening:
- The variable `listEntries` in adn/core.js is not being updated when the "My Filters" is being saved.
- `$important` tag on block is not working for some reason in the case of adn-allow when it comes from the "My Filters"

**Comment by mneunomne** [comment]
- [ ] check which version has issue started

**Comment by mneunomne** [comment]
what sfneData returned on 3.11.4:

```js
{
	raw: "||mail-ads.google.com/mail/u/0/ads/$xmlhttprequest,important,domain=mail.google.com"
	regex: "mail-ads\\.google\\.com/mail/u/0/ads/"
	result: 1
	source: "static"
	tokenHash: 101719
	[[Prototype]]: Object
}
```

what it returns now:

```js
{
	raw: "||mail-ads.google.com^"
	regex: "mail-ads\\.google\\.com\\.?(?:[^%.0-9a-z_-]|$)"
	result: 1
	source: "static"
	tokenHash: 268435456
}
```

**Comment by mneunomne** [comment]
The reason for that might be that the static-net-filtering has changed so much since the last merges. Perhaps need to figure some other way of doing this operation.

**Comment by mneunomne** [comment]
I found a rather obscure fix to this: https://github.com/dhowe/AdNauseam/pull/2114/commits/55b67dcc3ed9336d906da6c50c819b8aaa9a6ae6#

Tested in the context of https://github.com/dhowe/AdNauseam/issues/2115 and it seems to be working as expected now.

--------

The problem that we were facing is that ublock filters a request in the following order:

A-> if there is a normal block
B-> if there is an allow for that block
C-> then if there is an $important to overwrite the allow

And if A is true, the SFNE doesn't even check if there is another $important block to that url. Which makes total sense for Ublock (it doesn't need to check if there is an important block for something that doesn't have a conflicting allowed filter).

But for Adnauseam's case, we *do* need to know if there is a parallel $important in the adnauseam filters, since that will later on tell us if we should or not overwrite an expected adn-allowed url.

Not sure I made myself clear,  but what I found a rather obscure fix to this: https://github.com/dhowe/AdNauseam/pull/2114/commits/55b67dcc3ed9336d906da6c50c819b8aaa9a6ae6#
 does, is check if there are any important blocks even if there is no "allow" competing with the normal block. 
 
 I don't believe this will affect the usual blocking mechanism, it will just tell us in the function `listsForFilter` that the filters comes from the "Adnauseam filter list" or "My Filters", and there for NOT adn-allow it. 
 
 ----------

**Comment by mneunomne** [comment]
> * [x]  check which version has issue started

This started in the merge with 1.38.0 it seems when uBlock changed the SNFE structure, but it was obscure to the point that I didn't fully catch it until now. 

- [ ] Add release test for such types of discrepancies in the blocking pattern between versions.

**Comment by dhowe** [comment]
See offline comments re: filter precedence

**Comment by mneunomne** [comment]
## How uBlock works:

- Any Allow exception `@@||` will overwrite any scope of block that is not `$important`:
    e.g.: `@@||nytimes.com` Allows over the more specfic scope `||nytimes.com/svc/nyt/data-layer$script`
- Any `$important` will have precedence over any allow exception`@@||`

## How AdNauseam is currently working:

- Like the normal uBlock Allow exception `@@||`, `Adn-Allow` can only be overwritten by `$important` tag, OR with an exact matching filter.


| Allow-Block-List (e.g. Adnauseam Filters)               | Adn-Allow-Lists (e.g. EasyList)                         | Result   |
|---------------------------------------------------------|---------------------------------------------------------|----------|
| `\|\|nytimes.comˆ`                                      |                                                         | block    |
|                                                         | `\|\|nytimes.comˆ`                                      | adn-allow|
|                                                         | `\|\|nytimes.comˆ$important`                            | adn-allow|
| `\|\|nytimes.comˆ`                                      | `\|\|nytimes.comˆ`                                      | block    |
| `\|\|nytimes.comˆ`                                      | `\|\|nytimes.comˆ$important`                            | adn-allow|
| `\|\|nytimes.com/svc/nyt/data-layer$script`             | `\|\|nytimes.comˆ`                                      | adn-allow|
| `\|\|nytimes.comˆ$important`                            | `\|\|nytimes.com/svc/nyt/data-layer$script`             | block    |

**Comment by dhowe** [comment]
Precedence:
-------------------
- adnauseam.txt should override any other filter list
- any user added rule should override any other rule

**Comment by mneunomne** [comment]
The initial error was already fixed. If we want to change how the precedence is working, we can continue working on https://github.com/dhowe/AdNauseam/issues/2119

Think we can close this for now
