### ISSUE TITLE
Youtube ads still getting through

### ISSUE THREAD

**Issue by Jaxinson** [dhowe/AdNauseam#2113]
I don't know how or why, I've tried playing with some of the settings but there's some ads from several advertisers getting through on youtube videos.

![image](https://user-images.githubusercontent.com/44829737/173698636-34464bc1-9203-4fcc-ba76-d69ff701d40d.png)

I don't know how to recreate the issue, I just noticed a few weeks ago youtube ads have started to actually get through

- OS/version: Windows 11
- Browser/version: Chrome 102.0.5005.63
- AdNauseam version: 3.13.1
- Other extensions you have installed: Return Youtube Dislikes, Honey, and Ecosia
- AdNauseam settings: Default settings

I am using completely default settings, every ad should be blocked, I think

Massachusetts

**Comment by mneunomne** [comment]
thank you @Jaxinson for the feedback. I have just tested 3.13.1 with the same installed extensions and same Chorme version and works fine for me. Do any errors appear in the extension logs?

**Comment by Jaxinson** [comment]
None that I can see
Again not really sure what causes this and only certain ads seem to be
getting through, such as YouTube's ads for itself

**Comment by mneunomne** [comment]
Also related to https://github.com/dhowe/AdNauseam/issues/2110

**Comment by mneunomne** [comment]
https://github.com/dhowe/AdNauseam/issues/2110 fixed this, closing
