### ISSUE TITLE
Gmail ads are not blocked

### ISSUE THREAD

**Issue by LiamMCW** [dhowe/AdNauseam#2115]
### Describe the issue

Gmail fake email ads are not blocked, despite ublock origin correctly blocking them.

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/35670972/173881665-962e06c9-5439-4a02-9362-b037ea5731d1.png)
(Cropped for privacy)

### Steps for anyone to reproduce the issue
Sign into gmail, navigate to the Promotions tab, and wait a few seconds for ads to load. Normal Ublock origin successfully blocks the built in gmail ads.

### Your settings

- OS/version: Windows 10, latest updates.
- Browser/version: Firefox 101.0.1 (64-bit)
- AdNauseam version: AdNauseam v3.13.1
- Other extensions you have installed: None, a new profile was created to test this issue
- AdNauseam settings: Default settings with Hide Ads, Click Ads, Block Malware, and no exceptions for non-tracking ads.

##### Your filter lists
Default filter lists

### Your location/country
Netherlands, behind VPN

**Comment by LiamMCW** [comment]
mail-ads.google.com being unblocked for some reason seems to be the cause of this issue, manually blocking it in the popup GUI prevents the fake ads from loading.

**Comment by mneunomne** [comment]
Thank you for the feedback @LiamMCW, submited the PR above which fixes it. 

But I believe the real cause of this issue lies in https://github.com/dhowe/AdNauseam/issues/2110

**Comment by mneunomne** [comment]
Fixed in master, closing
