### ISSUE TITLE
Bug v3.14.1b (rc1): The Setting GUI is not working and doesn't load user's settings, custom filters or ''my filter''

### ISSUE THREAD

**Issue by metapea** [dhowe/AdNauseam#2128]
When starting up AdNauseam and going into settings, the extension look like this:
![chrome](https://user-images.githubusercontent.com/35351174/175462938-7bb280a4-de61-4948-b136-755a7b305cb7.png)
And none of the my settings are loaded

**Comment by mneunomne** [comment]
I believe these this issue is related to the change in the key on manifest: https://github.com/dhowe/AdNauseam/issues/2127

**Comment by mneunomne** [comment]
(added an entry to the test runs to make sure this doesn't happen again)

- [ ] Test unpack manual update
  1. Update the folder where Adnauseam is installed with the new version
  2. Close the browser
  3. Make sure that Adnauseam is still installed
  4. Make sure all the settings from previous installation are present

**Comment by metapea** [comment]
> I believe this issue is also related to the change in the key on manifest: #2127
well it's only v3.14.1b (rc1) that does this, 1.13.1 is fine (it still has #2127 but it's works)
and yeah i testing on chrome while using it

**Comment by metapea** [comment]
Good news: 

- v3.14.1b (rc2) fixed the gui:

![Screen](https://user-images.githubusercontent.com/35351174/180881009-9b1fa165-9e5b-4ae8-bae6-04402d4d541e.png)

- It's load on start if you install it with [.crx](https://github.com/dhowe/AdNauseam/releases/download/v3.14.2b/adnauseam-3.14.0.2.chromium.crx)

Bad news:

- 3.14.0.2 doesn't load on start if you're installing with [.zip](https://github.com/dhowe/AdNauseam/releases/download/v3.14.2b/adnauseam-3.14.0.2.chromium.zip) 
- It still doesn't load your settings from before:
![Screens](https://user-images.githubusercontent.com/35351174/180881806-760f6854-7605-43aa-9150-9cb9df77446b.png)
![Screens3](https://user-images.githubusercontent.com/35351174/180881753-706adf99-16c6-4ee6-b3ac-47ca5ffe39a1.png)
- After installing v3.14.1b (rc2) and rolling back to v3.13.1, i couldn't use ''Backup to file''

**Comment by metapea** [comment]
- 3.14.5 still doesn't load on start and it doesn't load your past settings, It starts a new one instead.
- I still can't use ''Backup to file'' and clicking on it does nothing

**Comment by dhowe** [comment]
@mneunomne pls check this

**Comment by mneunomne** [comment]
@metapea im sorry to see you are still experiencing this issue. 

- Did you try installing it on a browser profile to see what happens?
- Is the export button has an issue on the new version 3.14.5 or in your previous one?

**Comment by metapea** [comment]
- Did you try installing it in a new browser profile to see what happens?
 No

- Does the export button have the issue on the new version (3.14.5) or in your previous one?
Both, also starting with new settings/storage can make the export work. But i can't export with my old settings

**Comment by metapea** [comment]
> Maybe you can share what errors appear in the extension logger?
tell me where can i find it?

>perhaps have messed up the storage of the extension on your browser profile
That my guess, the only way you can import is by copy and pasting to another folder in Default\Local Extension Settings

**Comment by mneunomne** [comment]
You can find error logs here:

<img width="919" alt="Screenshot 2022-09-30 at 13 37 04" src="https://user-images.githubusercontent.com/4967860/193261494-353df651-6a9c-4fa4-82ac-eacdeff31f76.png">

**Comment by mneunomne** [comment]
Changing this issue from milestone 3.15 to ongoing, since this is an issue that occurred on a specific version, it has already been fixed, but the users who used this pre-release can still experience issues related to this.

**Comment by metapea** [comment]
> You can find error logs here:
> 
> <img alt="Screenshot 2022-09-30 at 13 37 04" width="919" src="https://user-images.githubusercontent.com/4967860/193261494-353df651-6a9c-4fa4-82ac-eacdeff31f76.png">
There no errors in extensions

**Comment by mneunomne** [comment]
The cause of this issue was the change in the key manifest during one beta release, this should not happen anymore since the key is staying consistent.

**Comment by mneunomne** [comment]
I believe this can be close if can't be reproduced outside of the context of that particular release.

**Comment by metapea** [comment]
The main part of the loading the settings from the last version.
The only bug left is that "Backup to file" still doesn't work
