### ISSUE TITLE
Disable menu should show dynamic domain rather than "domain.com"

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#2130]
### Describe the issue

The url in the menu should be dynamic, referring to the domain we're on rather than "domain.com"
For example, on Github it should say `ON GITHUB.COM` etc… (if we need we can make the menu wider and truncate long URLs with a `…`)

### Screenshot in which the issue can be seen

<img width="328" alt="image" src="https://user-images.githubusercontent.com/27123/177029069-f07257aa-9f1b-4cff-8e01-14811b99b90e.png">

### Steps for anyone to reproduce the issue

click the disable menu

### Your settings

https://whatismybrowser.com/w/EKDBEXM
AdNauseam v3.13.1
uBlock Originv1.40.4

Thanks

**Comment by mneunomne** [comment]
Implemented https://github.com/dhowe/AdNauseam/pull/2133

**Comment by mneunomne** [comment]
implemented, closing
