### ISSUE TITLE
Provide option to edit the cost per click. 

### ISSUE THREAD

**Issue by chirag127** [dhowe/AdNauseam#2131]
### Describe the feature

I want a ability to change the cpc in the extension because I personally think that it's different than that you are taking as a default amount and I have to manually calculate the total cost by myself because I prefer to use a different rate. And I hope you are able to understand that the cpc depends upon the purchasing power of the user depending upon the nationality of the user. So , a ad clicked India cost much less than that of a ad clicked in the US.

**Comment by dhowe** [comment]
@chirag127 would you be willing to work on this feature and submit a PR ?

**Comment by chirag127** [comment]
> @chirag127 would you be willing to work on this feature and submit a PR ?

Not sure about it b

**Comment by mneunomne** [comment]
### Implementing the option to change the `costPerClick` in the hiddenSettings:

![Screenshot 2022-08-17 at 12 55 55](https://user-images.githubusercontent.com/4967860/185102767-46348fba-a538-4d53-b7c7-bc4f3add2865.png)

![Screenshot 2022-08-17 at 12 56 04](https://user-images.githubusercontent.com/4967860/185102757-97b47010-2b9b-40cb-9e10-46eb39d4f612.png)

**Comment by dhowe** [comment]
looks good

**Comment by chirag127** [comment]
But no release?

**Comment by mneunomne** [comment]
https://github.com/dhowe/AdNauseam/releases/tag/v3.14.4

**Comment by mneunomne** [comment]
@chirag127 this is a experimental feature designed specially for you! if something comes up feel free to make a comment on this issue or create a new one. And careful edditing the hiddenSettings since it might break something in Adnauseam.

**Comment by chirag127** [comment]
> @chirag127 this is a experimental feature designed specially for you! if something comes up feel free to make a comment on this issue or create a new one. And careful edditing the hiddenSettings since it might break something in Adnauseam.

I normally mean release as releasing to https://microsoftedge.microsoft.com/addons/detail/adnauseam/mlojlfildnehdpnlmpkeiiglhhkofhpb

**Comment by mneunomne** [comment]
Ah ok, it's currently on review, should be updated soon.
