### ISSUE TITLE
Google text ad not collected

### ISSUE THREAD

**Issue by chirag127** [dhowe/AdNauseam#2132]
### Describe the issue

Google text ad are not being collected
### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/76880977/178134920-3f1a8a0e-1182-49d5-b385-d9961cb87e7c.png)

### Steps for anyone to reproduce the issue

search free AI writer in Google

### Your settings

- OS/version: windows
- Browser/version:
![image](https://user-images.githubusercontent.com/76880977/178135116-00056c24-7521-4b2c-b0a5-36ac28a2457a.png)

![image](https://user-images.githubusercontent.com/76880977/178134996-28c82f38-c957-4d31-bf25-6e6d62373769.png)

- AdNauseam version:[image](https://user-images.githubusercontent.com/76880977/178134996-28c82f38-c957-4d31-bf25-6e6d62373769.png)
- AdNauseam settings: Default

##### Your filter lists
Default filter lists

### Your location/country
India

**Comment by dhowe** [comment]
cannot recreate
<img width="1422" alt="Screenshot 2022-07-10 at 11 49 42 AM" src="https://user-images.githubusercontent.com/737638/178152061-efca2ad7-df88-42ee-b170-aaa4a84ceb21.png">

**Comment by chirag127** [comment]
You tried to use Indian VPN?

**Comment by chirag127** [comment]
I had disabled hiding to show that there are ads on page but not collected as I have click ads enabled.

**Comment by chirag127** [comment]
Most probably no one is able to detect that the ads on Google because you guys are hiding them

**Comment by mneunomne** [comment]
Updating the google text ad parser: https://github.com/dhowe/AdNauseam/pull/213

thank you @chirag127 for the feedback

**Comment by chirag127** [comment]
> Updating the google text ad parser: #2134
> 
> thank you @chirag127 for the feedback

I was reluctant to make this issue because I was quite surprise to see that Google ads are not being collected and thought that it should be me doing something wrong but I am delighted to know that you are thankful to me. I just switched from chrome to edge and found that this extension is not banned by Microsoft and started using it, but found that the memory usage is quite High in comparison to ublock origin.

**Comment by dhowe** [comment]
@chirag127 please create a separate ticket with your findings re: memory usage on edge

**Comment by mneunomne** [comment]
Implemented in the merge above, closing

**Comment by chirag127** [comment]
Can you guys close this issue only when released to firefox and edge ? So that I can search which issues are solved and which not in release?

**Comment by mneunomne** [comment]
@chirag127 it has been released on firefox on edge already, it should have automatically updated on your browser
