### ISSUE TITLE
Feature request: collect but not hide ads

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2136]
It would be __very__ useful for those working how to better collect ads, if there is a way that we can implement an option to "Collect without hiding the ads". So we can "debug" the non-collecting ads while being able to easily inspect their html structure.

Right now there is only the option to either parse or not parse the cosmetic filters, but that of course makes it impossible for us to collect the ads.

Perhaps that are some users that are interested in that as well? not sure, but would be a good developer option to have for sure.

The following code lines would have modified to implement this feature:

https://github.com/dhowe/AdNauseam/blob/f2d663c3557074526a49bab708d0c14a92fcbbe4/src/js/cosmetic-filtering.js#L942-L951

https://github.com/dhowe/AdNauseam/blob/f2d663c3557074526a49bab708d0c14a92fcbbe4/src/js/cosmetic-filtering.js#L1122-L1126

https://github.com/dhowe/AdNauseam/blob/f2d663c3557074526a49bab708d0c14a92fcbbe4/src/js/cosmetic-filtering.js#L1157-L1173

**Comment by dhowe** [comment]
Perhaps we replace 'block' in the main settings menu (and first-run-page) with 'collect'?

I can't think of a reason for that setting (other than the fact that google demanded it for the chrome store)
But regardless, we could preserve that option as a checkbox in settings, under "Default behavior"

**Comment by mneunomne** [comment]
I would say better not include this behaviour in the firstrun page. 

The changes I am suggesting would actually not-hide all ads, just disable the cosmetic filters that we parse ourselves and add the "display: none;". Some other cases where, for example, ublock-list modifies the style of an element, will still occur.

This feature should really be just a "developer option" for better debugging, so the option could go right next to "enable debugging" or something of that sort.

**Comment by mneunomne** [comment]
I have implemented, just not sure about this weird description:

_"Show ads for ad-collection debugging"_

<img width="393" alt="Screenshot 2022-08-03 at 13 05 31" src="https://user-images.githubusercontent.com/4967860/182570319-33cbdd57-f1c0-4ac1-b5f4-8634325f9575.png">

**Comment by dhowe** [comment]
How does this interact with the current 'hide ads' settings -- does it toggle it off automatically ? it will be potentially confusing for the user if, for example they have this setting ON and hide-ads OFF, and then turn hide-ads ON, but ads are still visible

**Comment by mneunomne** [comment]
When this option is enabled, some ads are still hidden, only those that are currently collectable are displayed. It servers for developers to understand better how to better collect ads in a page.

This option only makes sense when "Hide ads" is enable, because the blocking rules are still enforced, just the cosmetic filters do not hide even though they are parsed.

As I said it's really a developer's option. But would make sense perhaps to implement a warning related to it.

**Comment by dhowe** [comment]
We just need to be clear what the various states are supposed to do. 

But are you saying that only successfully collected ads are hidden, or is there some other criteria for 'collectable' ads ?

**Comment by mneunomne** [comment]
Perhaps this should be a dev only option then? a variable in the code itself like some other cases like this? If its not intended for the users, perhaps let's just keep it in the code...

**Comment by mneunomne** [comment]
I have hidden this option from the UI in the last PR, seems like a much more sensible approach.

**Comment by dhowe** [comment]
I actually like it in the UI, as long as it makes sense with the other options. This will help greatly with debugging ad collection and we don't want to have to switch to a dev version every time we encounter a problem when using a release version...

**Comment by mneunomne** [comment]
Ah ok, if so you can deny last PR.

The thing is that this kind of reveals to the user the process of ad collection, but at the same time reveals why it is such a tricky thing. 

as I said, this feature will:
- Still hide ads that are being blocked (not adn-allowed).
- Show the ads that are being rendered (adn-allowed).
- Will show All collected ads.
- Will also show the ads that are not being collected but are being adn-allowed.

**Comment by dhowe** [comment]
I think we just need to be clear in the UI that this is an advanced debugging feature, and not for general use

**Comment by mneunomne** [comment]
So maybe we can add it to the hidden advanced settings instead?

<img width="1201" alt="Screenshot 2022-08-12 at 15 34 27" src="https://user-images.githubusercontent.com/4967860/184364766-acee4baf-89c9-42b0-b098-0555fcc7ce93.png">

**Comment by dhowe** [comment]
sure

**Comment by mneunomne** [comment]
- [ ] Add warning when this feature is enabled (sometimes i forget it is on, and think there is a bug happening)

**Comment by mneunomne** [comment]
https://github.com/dhowe/AdNauseam/pull/2199 implements notification on this feature:

<img width="318" alt="Screenshot 2022-10-24 at 19 01 08" src="https://user-images.githubusercontent.com/4967860/197583423-aff1871d-7ea7-432c-9167-6881400592f8.png">

**Comment by mneunomne** [comment]
Everything implemented, closing
