### ISSUE TITLE
Where is this cometic rule coming from?

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2147]
While testing nytimes.com I realised that there there are some cosmetic filters showing up that are not in any list, not sure if they are being automatically generated in some other way, but it is indeed weird:

Website: https://www.nytimes.com/2022/08/11/us/politics/trump-fbi-subpoena.html

Rule: `##.GoogleActiveViewElement:style(/*display:none!important;*/)`

<img width="1329" alt="Screenshot 2022-08-11 at 19 45 35" src="https://user-images.githubusercontent.com/4967860/184199559-de1a130f-6ea7-4602-8aff-52144853a81b.png">

**Comment by dhowe** [comment]
that's strange - lets try to figure out where it is coming from

**Comment by mneunomne** [comment]
Can't reproduce it no longer, will close until further notice.
