### ISSUE TITLE
Click/drag not working correctly in vault

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#215]
1. Does not drag in real-time, only after mouse is released
2. Also, doesn't work when dragging on an image
3. Cursor is not consistent (sometimes hand, sometimes [when on the grid] an axis)

**Comment by CyrusSUEN** [comment]
> Cursor is not consistent (sometimes hand, sometimes [when on the grid] an axis)

Is it fixed in https://github.com/dhowe/AdNauseam/issues/214?
If not, please specify the condition.

**Comment by dhowe** [comment]
No. On click/drag, when outside of the collage, cursor turns from a hand into an crosshair, inside the collage it turns into a pointer

**Comment by CyrusSUEN** [comment]
> cursor turns from a hand into an crosshair

Please try this: https://github.com/dhowe/AdNauseam/pull/222

**Comment by dhowe** [comment]
#3 above is fixed. #1 and #2 are not. #2 is not important.

**Comment by CyrusSUEN** [comment]
#2 is mentioned in https://github.com/dhowe/AdNauseam/issues/210 and fixed in  https://github.com/dhowe/AdNauseam/pull/221

**Comment by dhowe** [comment]
Confirmed. Only 1. remains

**Comment by leoneckert** [comment]
currently working on this approach, but there are still problem - mainly it's very laggy 
![screen shot 2016-09-17 at 21 09 00](https://cloud.githubusercontent.com/assets/14130931/18612014/fd585b1a-7d1a-11e6-8de4-d492143d2a13.png)

**Comment by dhowe** [comment]
status? I guess I don't understand why there is such a huge lag...

**Comment by leoneckert** [comment]
I haven't gotten back to this since then, will try to think of a different approach

**Comment by leoneckert** [comment]
yay, solved it! PR in just a a little bit

**Comment by dhowe** [comment]
Good work. However, please also see #529 (not sure if its related or not)
