### ISSUE TITLE
Are all cosmetic filters being parsed by AdNauseam ad-parser? 

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2150]
While implementing https://github.com/dhowe/AdNauseam/issues/2136 I checked that in the [cosmetic-filtering.js](https://github.com/dhowe/AdNauseam/blob/master/src/js/cosmetic-filtering.js) file there are multiple different treatments for different types of cosmetic filters, for example declarative style actions (e.g.: `gay69.stream##.unselectable:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)
`

We need to check if Adnauseam is properly parsing these all if these different filters into our ad-parser.

**Comment by mneunomne** [comment]
Task: 
- [ ] check the cosmetic filters that are appearing in the logger, and check if all of them are being parsed.
- [ ] specifically test if all declarative style actions are being parsed _(with `:style()` commands)_

**Comment by mneunomne** [comment]
while working on #2173 realized something, interesting:

_Why do we only parse declarative filters when checking for collectable ads?_

https://github.com/dhowe/AdNauseam/blob/bb110ea345eb49f6f19de686d155eace77f174dd/src/js/contentscript.js#L1293-L1301

It seems there are also procedural filters that we are not parsing for ad detection:

![Screenshot 2022-09-28 at 21 57 30](https://user-images.githubusercontent.com/4967860/192876946-abd27181-5b04-4cd3-a492-8e4ddf02a7a5.png)

**Comment by dhowe** [comment]
good catch... not sure why this would be the case
can you investigate?

**Comment by mneunomne** [comment]
Now also parsing procedural filters https://github.com/dhowe/AdNauseam/pull/2198

Sometimes it occurs that the ProceduralfilterInstance on contentscript.js is null and was generating an exception, I handled the exception but not sure why this was happening. 

```js
/* start of Adn exception fetching */ 
var instance = this.proceduralFiltererInstance()
if (instance == null) {
    if (vAPI.prefs.logEvents) console.warn("[ADN] proceduralFiltererInstance null")
    break;
}
/* end of Adn exception fetching */
```

**Comment by mneunomne** [comment]
this was now corrently implemented as documented in https://github.com/dhowe/AdNauseam/issues/2252, closing now.
