### ISSUE TITLE
Update Logger Color Reference.

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2151]
In high resolution screens the image reference for the logger colors is really low quality. We should probably do it in HTML instead.

![Screenshot 2022-08-16 at 15 20 03](https://user-images.githubusercontent.com/4967860/184890073-aa3d9848-f14b-44ff-bae6-f45ce7034297.png)

**Comment by mneunomne** [comment]
The colors are a bit off and also now realised that the Redirect-rule is missing. Will update this for the current release.

**Comment by mneunomne** [comment]
Re-done the logger color keys with actual html, so that if we change the css colors, it will change automatically with it: 

![Screenshot 2022-08-16 at 17 44 00](https://user-images.githubusercontent.com/4967860/184922039-681ffb70-c9b0-4f7f-a077-c4ded7d77584.png)

**Comment by dhowe** [comment]
nice
