### ISSUE TITLE
Update Ad Cost-Per-Click Calculation

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2157]
When re-checking the cost-per-click calculation value noticed that the value we currently have __$1.58__, is outdated.

> [Pay-per-Click (PPC)](https://en.wikipedia.org/wiki/Pay_per_click) is a common internet advertising model in which advertisers pay for individual clicks on Ads. The cost involved varies widely depending on a number of factors. One important factor is the type of website the Ad appears on; whether a normal 'display' website, or a 'search' website where the Ads shown are based on the user's query. The latter is generally more effective, with prices commonly calculated on the spot through a real-time bidding system. Display Ads may use fixed prices or other pricing models to determine click cost. Depending on these and other factors, costs per click range from below 1$ to over $50. As the precise cost generated by clicks is not visible to the client, AdNauseam calculates an estimate using an average value of $1.58 for each clicked Ad. This value is taken from [this analysis](https://www.hochmanconsultants.com/cost-of-ppc-advertising/), in which various advertising models and platforms are taken into account.

The latest value available on the [analysis](https://www.hochmanconsultants.com/cost-of-ppc-advertising/) we have as reference is __$1.03__.

![Screenshot 2022-08-16 at 16 45 12](https://user-images.githubusercontent.com/4967860/184909686-979e9fd8-0ed4-43a0-8e8b-940a161375d7.png)

Or perhaps we can add an option for the user to update this value as suggested in this issue?
https://github.com/dhowe/AdNauseam/issues/2131

**Comment by dhowe** [comment]
We shouldn't update the current value, and make sure it is linked in the FAQ. But to me this doesn't seem an option many users will use. But I wonder if we want to have some configuration options, for advanced options, that we don't want to have in the UI, similar to Firefox's `about:config` page

**Comment by mneunomne** [comment]
Perhaps this value should go in the "hidden settings"? advanced users can simply directly change the value there.

**Comment by mneunomne** [comment]
Implemented in Hidden serttings + updated the value to $1.03.

**Comment by mneunomne** [comment]
![Screenshot 2022-08-17 at 12 56 04](https://user-images.githubusercontent.com/4967860/185103553-b08d5151-16e7-4ec8-a9f7-ec0ce6a0569f.png)

**Comment by mneunomne** [comment]
Implemented, closing
