### ISSUE TITLE
Implement new options

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#216]
hideAdverts
visitAdverts
blockMalware
(also noIncomingCookies)

**Comment by dhowe** [comment]
Please verify that all current options work correctly in FF/chrome.
If not clear on what any of them means (or should do), ask me...

**Comment by CyrusSUEN** [comment]
> check that no (incoming) cookies are being set by ad-visits

Is this the default settings? I see incoming cookies stored in Chrome browser on default settings.

> Block malware and non-visual trackers

When the option is checked, there are many script files blocked (by those privacy lists) on http://www.nytimes.com/.
But I still notice a few script files blocked (by the privacy lists) in logger-ui.html page even after unchecking the option.

**Comment by CyrusSUEN** [comment]
> Hide ads identified by your chosen filter lists

It works but ADN cannot collect ads after unchecking this option.

**Comment by CyrusSUEN** [comment]
> check that no (incoming) cookies are being set by ad-visits

Steps to verify:
1. Remove all cookies from ``chrome://settings/cookies`` page
2. let ADN collect and visit the ads from [this page](https://www.google.com/search?sourceid=chrome-psyapi2&rlz=1C1CHZL_enHK695HK695&ion=1&espv=2&ie=UTF-8&q=credit%20card&oq=credit%20card&aqs=chrome..69i57j0l2j69i65l3.2040j0j7)
3. There should be some cookies from the domain names of the collected ads on ``chrome://settings/cookies`` page

**Comment by dhowe** [comment]
Please recheck incoming cookies. I've left some logging on, so you should be able to see the incoming headers in the console (for background.html)

**Comment by CyrusSUEN** [comment]
> recheck incoming cookies

Thanks for the log! I can see most of the cookies are getting removed.

I've come up with another testing:
1. Remove all cookies from ``chrome://settings/cookies`` page
2. Impor the following adset 
[AdNauseam_Export_6.4.2016.6.19.30PM.json.zip](https://github.com/dhowe/AdNauseam/files/310870/AdNauseam_Export_6.4.2016.6.19.30PM.json.zip)

After a while I see there are still some cookies not getting cleared in the cookies page:
![screen shot 2016-06-13 at 1 27 27 am](https://cloud.githubusercontent.com/assets/2461812/15992745/08f7e096-3106-11e6-97b8-913b5ebba753.png)

And do you think we should also remove local storage file from the ads ADN visited?

**Comment by CyrusSUEN** [comment]
> include which elements were blocked with 'blockingMalware' set to false

Results on http://www.nytimes.com/ with a default ADN settings:
Checked ``Block malware and non-visual trackers``
![default](https://cloud.githubusercontent.com/assets/2461812/15992826/8b2a633e-3108-11e6-8360-8aea7f9e9630.png)
For the first screenshot, all script files blocked were from privacy lists.

Unchecked ``Block malware and non-visual trackers`` 
![disabled](https://cloud.githubusercontent.com/assets/2461812/15992820/723d7c12-3108-11e6-93bb-17f141c9b743.png)
For the second screenshot, only the second entry is not from a privacy list. Others are from privacy lists.

**Comment by dhowe** [comment]
Ok. I will look into this. However, isn't the 2nd entry in the 2nd screenshot in easyList.txt (line 446) ?

**Comment by CyrusSUEN** [comment]
> isn't the 2nd entry in the 2nd screenshot in easyList.txt (line 446) ?

Yes, the 2nd entry in the 2nd screenshot is from easyList.txt. And it is the only script file getting blocked by a non-privacy rule after I set 'blockingMalware' to false.

For the above 2 screenshots, I've only filtered to list what were blocked.

**Comment by dhowe** [comment]
So are you suggesting that there is 1 error (img 2, line 2), or 7 errors (all entries in img 2) ?

**Comment by CyrusSUEN** [comment]
> So are you suggesting that there is 1 error (img 2, line 2), or 7 errors (all entries in img 2) ?

I am suggesting the all entries one.
I just think there shouldn't be elements blocked by rules coming from privacy lists after we set blockingMalware to false.

**Comment by CyrusSUEN** [comment]
![disabled](https://cloud.githubusercontent.com/assets/2461812/15992820/723d7c12-3108-11e6-93bb-17f141c9b743.png)
These rules on the above screenshot are from EasyPrivay:
```
||analytics.edgekey.net^
||nytimes.com/?url*&referrer$script
||newrelic.com^$third-party
||optimizely.com^$third-party
```

**Comment by dhowe** [comment]
I wonder if they are not getting blocked, by getting logged nonetheless...
In any case I will look into it tomorrow

**Comment by dhowe** [comment]
Please verify:

- [ ] Hide ads identified by your chosen filter lists
- [ ] Block malware and non-visual trackers

**Comment by CyrusSUEN** [comment]
> Capture text-only ads when possible (check with Hiding on/off)

It works but this is more like a **hide** collected text ads. Simply by enabling / disabling this option and check the Vault page I can see the collected text ads appeared or disappeared.

**Comment by dhowe** [comment]
No, it should be that no new text ads are collected. Please verify

**Comment by CyrusSUEN** [comment]
> it should be that no new text ads are collected. Please verify

I can confirm this.

Checking / unchecking `Capture text-only ads when possible` will hide / unhide those previously collected text ads. And unchecking the option there will be no more new text ads added to Vault page.

**Comment by dhowe** [comment]
And also, none should appear in the menu. Is that correct?

**Comment by CyrusSUEN** [comment]
> no new text-ads should appear in the menu. Is that correct?

Yes.
