### ISSUE TITLE
Text and images for Chrome store submission

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#217]
- [x] 1 [Icon](https://developer.chrome.com/webstore/images?hl=en-US#icons): [128x128]
- [x] 3-5 [ScreenShots](https://developer.chrome.com/webstore/images?hl=en-US#screenshots): [ 1280x800 or 640x400 ]
- [x] 1-3 [Promotional Images](https://developer.chrome.com/webstore/images?hl=en-US#promo): [ 440x280, 920x680(optional),1400x560: (optional) ]
- [x] Detailed description: max 16000 chars (draft below)
- [x] Video link: https://vimeo.com/111943439
- [x] Website link: https://adnauseam.io/
- [x] Support/FAQ link: https://github.com/dhowe/AdNauseam/wiki/FAQ

**Comment by dhowe** [comment]
**Description:**

(draft) AdNauseam is a browser extension designed to obfuscate browsing data and protect users from tracking by advertising networks. Like an adblocker, AdNauseam blocks malware and hides ads on the pages you visit. But AdNauseam does more, collecting each ad and allowing you to explore visualizations of the ads you've been served. AdNauseam can also be configured to automatically click each blocked ad in the background, polluting your data profile and frustrating the trackers who violate our privacy and facilitate bulk-surveillance agendas.

**Comment by mushon** [comment]
As for promotional images we have our clickerbot image.
I want to create the screenshot but don't have a proper ad batch (got erase in some of the latest test installs) @dhowe is there something I can import and use?

**Comment by mushon** [comment]
added 2 images to the /img/ folder in the gh-pages branch:

![uploads/0e5fc0ac-b15a-460e-946f-7cf35f255c99/adnauseam_logo_440x280.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0e5fc0ac-b15a-460e-946f-7cf35f255c99%2Fadnauseam_logo_440x280.png)

![uploads/d7eb81f8-9508-4b70-b239-e3d08ca8bb65/adnauseam_1280x800.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd7eb81f8-9508-4b70-b239-e3d08ca8bb65%2Fadnauseam_1280x800.png)

**Comment by mushon** [comment]
Text edit:
AdNauseam is a browser extension designed to protect users from tracking by advertising networks by obfuscating their click stream. Like a content-blocker, AdNauseam can block malware and hide ads on the pages you visit. But AdNauseam does more, as it also collects each ad in its 'ad-vault' for you to interactively explore. Optionally AdNauseam can automatically click each blocked ad in the background, polluting your data profile and frustrating the trackers by virtually "liking" all ads.

**Comment by mushon** [comment]
> Which one do you think we should use as are lead image?
The options are:
- vault
- menu (in action)
- on boarding options 
- clickbot
- logo

**Comment by dhowe** [comment]
do you mean lead promo image? they main image needs to be a screenshot

**Comment by dhowe** [comment]
do you mean lead promo image? they main image needs to be a screenshotOn 11 Jun, 2016, at 1:25 am, Mushon Zer-Aviv <notifications@github.com> wrote:> Which one do you think we should use as are lead image?
The options are:
- vault
- menu (in action)
- on boarding options 
- clickbot
- logo

**Comment by mushon** [comment]
Ok. So for a screenshot we should definitely go with the vault. 

Can you send a link explaining how would the other 3 images and their different sizes be used?

**Comment by dhowe** [comment]
It just says 'promo' images and the sizes needed -- should be able to reverse engineer this from looking at other chrome extensions in the store

**Comment by dhowe** [comment]
@mushon  ?

**Comment by dhowe** [comment]
Icon specs:

Upload an icon image that represents this item, and ensure it complies with the following:

* 128x128 total pixels
* For square icons, use alpha to make 16 of the 128 pixels per side transparent (96x96 visual weight)
* For circular icons, the visual icon should be 112x112 (use alpha to make the remaining pixels transparent)
* For other icon shapes, use alpha to maintain the same 96x96 visual weight

Additional advice:
Your icon should be flat; avoid noticeable perspective, 3D, and shadows.
Don’t use text in your icon.

**Comment by mushon** [comment]
I added the 2 remaining screenshots
