### ISSUE TITLE
Add Edge link on website

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2172]
Without or (preferably) With autodetection of Edge as user browser.

Also we need to make sure that the version # gets updated on the website (via pull to gh-pages branch), it was still at 3.9

![image](https://user-images.githubusercontent.com/737638/189846838-f7aefa1c-67d9-47e7-94d6-03fd1e663d6f.png)

![pngwing com(1)](https://user-images.githubusercontent.com/737638/189847101-0b7ec85e-812f-43ed-8346-114f02c39a50.png)

**Comment by mneunomne** [comment]
Implemented, closing
