### ISSUE TITLE
Merge to uBlock Origin v1.44.2 

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2173]
Or as close as it is possible to reach at this point.

https://github.com/gorhill/uBlock/tree/1.44.2

**Comment by dhowe** [comment]
any idea when they will migrate to manifest v3?

**Comment by mneunomne** [comment]
Don't see a planned date, but seems like it is still in the conceptual discussion level. Apparently it will be a huge change, so I imagine we need to be ready for a very big future merge:

https://github.com/uBlockOrigin/uBlock-issues/issues/338

**Comment by mneunomne** [comment]
> merged to 1.42.0, some issues appearing:
> 
> ![Screenshot 2022-09-16 at 20 14 47](https://user-images.githubusercontent.com/4967860/190705283-2b615ab4-27fa-4620-96f0-ad6f7e985cd0.png)

Fixed, minor typo

**Comment by mneunomne** [comment]
Testing merge on 1.43.0. The following issues appearing:


__js/contentscript.js:1302 (anonymous function)__
```
Uncaught (in promise) SyntaxError: Failed to execute 'querySelectorAll' on 'Document': '.' is not a valid selector.
```

**Comment by mneunomne** [comment]
### Other errors: 

_Error in event handler: TypeError: Cannot read properties of null (reading 'name')_
 ```js
 onPortDisconnect: function(port) {
        this.ports.delete(port.name);
    },
```

_Uncaught SyntaxError: Failed to execute 'toggle' on 'DOMTokenList': The token provided must not be empty._
js/udom.js:640 (anonymous function)

**Comment by mneunomne** [comment]
This last issue occurs when opening the menu, but I don't see any consequences of it yet.

**Comment by mneunomne** [comment]
Currently UpToDate to uBlock Origin latest release, closing
