### ISSUE TITLE
Test on Thunderbird, SeaMonkey, Firefox for Android

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#218]
Test on Thunderbird, SeaMonkey, Firefox for Android

Put results here (if there are problems, we need to remove these listing from the FF store)

**Comment by CyrusSUEN** [comment]
**Thunderbird** is a pure email client to me. I can install AdNauseam and uBlock on it but I just do not know how to make use of them. (at least no menu icons)

**SeaMonkey**: it works as good as it does on Firefox.
![123](https://cloud.githubusercontent.com/assets/2461812/15805637/15e64d54-2b63-11e6-84e0-f63035ef349d.png)

**Firefox for Android**: also works fine including exporting / import ads.
![bluestack](https://cloud.githubusercontent.com/assets/2461812/15805640/27a35532-2b63-11e6-91bf-ca01635f4011.png)
![blue2](https://cloud.githubusercontent.com/assets/2461812/15805642/2abdec50-2b63-11e6-9b4a-1376b671a7cf.PNG)
![blue3](https://cloud.githubusercontent.com/assets/2461812/15805644/2ec3c9be-2b63-11e6-9858-4bdb2505dc20.PNG)

But the problem for Firefox on Android is that we need to at least update the text ads detection rules as it cannot collect ads from m.google.com

**Comment by CyrusSUEN** [comment]
> if there are problems, we need to remove these listing from the FF store

I can find [uBlock Origin](https://addons.mozilla.org/en-US/thunderbird/addon/ublock-origin/?src=search) and [Adblock Plus](https://addons.mozilla.org/en-US/thunderbird/addon/adblock-plus/?src=hp-dl-featured) as well as [AdNauseam](https://addons.mozilla.org/en-US/thunderbird/addon/adnauseam/?src=search) on [Thunderbird addon page](https://addons.mozilla.org/en-US/thunderbird/) (compatibile with Thunderbird)

I think it is safe to follow their suite.

**Comment by dhowe** [comment]
agreed
