### ISSUE TITLE
Merge to uBlock Origin 1.45.0

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2212]
1.45.0 has the development of the mv3 build, so we can try start testing based on it.

This version has quite a few changes, will need a bit more reviewing to catch all issues. I had to change most of our files now to modules so the i18n can be imported (since it is now also a js module).

Some of the filtering mechanism seems to have changed which is causing some filters not be considered valid for some reason, checking this now.

**Comment by dhowe** [comment]
Lets not spend too much time on mv3 for Google Chrome until we decide its worth doing

**Comment by mneunomne** [comment]
Yes, I just need to make some tests, and for that adnauseam needs to be at least in v1.45.0.

**Comment by mneunomne** [comment]
Already merged, closing
