### ISSUE TITLE
Sponosored ads reappearing on instagram

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2218]
logged in, OS X 11, Firefox 107
element blocker fails

<img width="576" alt="image" src="https://user-images.githubusercontent.com/737638/204458044-ae0f562e-090d-4d24-9fa3-4f5bfb655c24.png">

**Comment by mneunomne** [comment]
duplicated https://github.com/dhowe/AdNauseam/issues/2254
