### ISSUE TITLE
Ad count not updating correctly

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#224]
In images below, you can see two different sets of ads, both showing a count of 399. For whatever reason, the count never goes over 400. This should be the initial setting (max=400), but after the use adjusts the date filters, any count should be OK (and accurate).

![screen shot 2016-06-07 at 8 58 58 am](https://cloud.githubusercontent.com/assets/737638/15842737/5c58c790-2c8e-11e6-9dcb-a51439d02484.png)

![screen shot 2016-06-07 at 8 58 38 am](https://cloud.githubusercontent.com/assets/737638/15842738/5f0f919e-2c8e-11e6-9981-5b22556c4c05.png)

**Comment by CyrusSUEN** [comment]
Please verify: https://github.com/dhowe/AdNauseam/pull/237

**Comment by dhowe** [comment]
Please verify

**Comment by CyrusSUEN** [comment]
> Please verify

ebfac1304936d751c2ac7ba1702d3f2e43f5178d does not fix the problem. 
![screen shot 2016-06-12 at 9 25 28 pm](https://cloud.githubusercontent.com/assets/2461812/15991387/33cf64be-30e4-11e6-8ee2-93cc6b309dd6.png)


This is the ad set I've been using: 
[AdNauseam_Export_6.4.2016.6.19.10PM.json.zip](https://github.com/dhowe/AdNauseam/files/310782/AdNauseam_Export_6.4.2016.6.19.10PM.json.zip)

**Comment by dhowe** [comment]
Does not fix the problem is not a useful description -- please list the steps needed to recreate the problem you found.

**Comment by CyrusSUEN** [comment]
> list the steps needed to recreate

Updated comment https://github.com/dhowe/AdNauseam/issues/224#issuecomment-225432683

**Comment by dhowe** [comment]
Ok, as there are too many higher priority issues, I've reverted to your earlier fix (in #237) for now, after fixing another vault bug (see below) and lowering maxStartNum to 300. Please verify things still work correctly.

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.`

**Comment by CyrusSUEN** [comment]
Actually we can keep using `filterAdSets()` when the total number of ads is fewer than `maxStartNum` for performance purpose.

My approach was to recreate `gAdSets` every time when we move the slider. But there was no need to recreate `gAdSets` if the number of ads is fewer than `maxStartNum`. (simply add a if-else condition will suffice)

Should I try this before verifying? If it works I will create a PR.

**Comment by dhowe** [comment]
Ok

**Comment by CyrusSUEN** [comment]
> keep using filterAdSets() when the total number of ads is fewer than maxStartNum

Fix verified: https://github.com/dhowe/AdNauseam/pull/256
