### ISSUE TITLE
"Recent update has broken layout of popup." ?

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2246]
![Screen Shot 2022-12-30 at 07 29 26](https://user-images.githubusercontent.com/4967860/210031599-92f02d71-3fca-467f-ab66-3fb76a0935aa.png)

This was submitted as a review in firefox store, but can't reproduce it.

**Comment by tiomny** [comment]
![изображение](https://user-images.githubusercontent.com/24210383/212561260-65b6f774-111e-486d-ac66-a66a8a36dac5.png)

**Comment by mneunomne** [comment]
Was not able to reproduce. closing for now.

**Comment by tiomny** [comment]
> Was not able to reproduce. closing for now.

Steps to reproduce:
* install additional language in browser. Words in that language should be spelled with more letters. French, Polish or Russian suits.
* Select that language to display menus.
* Restart browser.
* Click on AdNauseam icon in toolbar.
* See screenshot above.

**Comment by mneunomne** [comment]
@tiomny In the PR above I fixed the breaking menu layout and also I added a fallback font for cyrilic characters:

<img width="1207" alt="Bildschirm­foto 2023-02-21 um 14 42 41" src="https://user-images.githubusercontent.com/4967860/220363248-407faf3f-ad1d-4dc0-9267-ef4c9f81209b.png">
<img width="318" alt="Снимок экрана 2023-02-21 в 14 39 21" src="https://user-images.githubusercontent.com/4967860/220363251-0d7c8943-a5c8-46c3-88b2-549d1e1b17df.png">
<img width="1099" alt="Bildschirm­foto 2023-02-21 um 14 42 45" src="https://user-images.githubusercontent.com/4967860/220363237-25154b53-d888-4941-a9e3-9b37abc25a5f.png">

**Comment by mneunomne** [comment]
tested in other languages as well, seems fine now:

<img width="200" alt="Captura de Tela 2023-02-21 às 14 52 58" src="https://user-images.githubusercontent.com/4967860/220364348-62d39c9a-16e5-448d-bf36-7c26d4e47294.png"><img width="200" alt="Capture d’écran 2023-02-21 à 14 51 04" src="https://user-images.githubusercontent.com/4967860/220364358-3868737b-81cd-4563-9ad7-e8e04f41de07.png"><img width="200" alt="Bildschirm­foto 2023-02-21 um 14 50 35" src="https://user-images.githubusercontent.com/4967860/220364362-9a59847d-10c6-48ad-8441-d388bf485ad2.png">

**Comment by mneunomne** [comment]
(polish, arabic, hebrew all dont have translation for the menu button at this moment)

**Comment by mneunomne** [comment]
Fixed, closing.
