### ISSUE TITLE
Error: vAPI.domFilterer undefined 

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2251]
ADN: v3.16.0 (Firefox)

When accessing pages on localhost

```
01:25:38.977 [ADN] vAPI.domFilterer undefined contentscript.js:1315:21
    bootstrapPhaseAdn moz-extension://24f3831f-2700-4275-b64a-2edc6acd90d5/js/contentscript.js:1315
    bootstrap moz-extension://24f3831f-2700-4275-b64a-2edc6acd90d5/js/contentscript.js:1498
    (Async: promise callback)
    bootstrap moz-extension://24f3831f-2700-4275-b64a-2edc6acd90d5/js/contentscript.js:1496
    <anonymous> moz-extension://24f3831f-2700-4275-b64a-2edc6acd90d5/js/contentscript.js:1504
```

<img width="622" alt="image" src="https://user-images.githubusercontent.com/737638/212526369-a437b066-ed6b-446c-a58f-e8027412549d.png">

**Comment by mneunomne** [comment]
@dhowe for now I think its better to just remove this warning I think, this doeesn't seem to be causing any issues, but I wasn't able to figure out what is happening.

**Comment by ghostebony** [comment]
> @dhowe for now I think its better to just remove this warning I think, this doeesn't seem to be causing any issues, but I wasn't able to figure out what is happening.

this happens to me on chromium browsers too if I disable AdNauseam for the website

**Comment by mneunomne** [comment]
This does not occur anymore, closing
