### ISSUE TITLE
Merge to uBlock Origin 1.45.0

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2256]
Currently working on the uBlock Origin 1.45.0 merge. Documenting some changes here:

- i18n is now a JS module, need to change how its called in many different places, which makes other adnauseam scripts to consequently also become JS modules.\
- Due to the changes in the i18n, had to change the shared.js into a js module, and therefore decided to split it into `notification.js` and `adn-utils.js` files, where the functions need to be specifically called in other files.
- There is a current issue with filter parsing with the `getAllSelectors` function in the `contentscript.js`, need to possibly change the method of gathering than applying the cosmetic filters in order for ad collection.

(will add more documentation bellow as I try to address everything)

**Comment by romulasry** [comment]
How about 1.46.0?

**Comment by mneunomne** [comment]
Coming soon, this merge was a bit tricky because of so many changes to modules in the script structure. Hope 1.46.0 will be easier.

**Comment by mneunomne** [comment]
(I just started the 1.46.0 merge now, and it will be tricky indeed, the whole uDom system changed...)

**Comment by romulasry** [comment]
There was just a https://github.com/gorhill/uBlock/releases/tag/1.47.0 1.47.0 release.

**Comment by mneunomne** [comment]
merged, closing
