### ISSUE TITLE
ads not collected on dawn

### ISSUE THREAD

**Issue by chirag127** [dhowe/AdNauseam#2259]
### Describe the issue
ads not collected on dawn https://www.dawn.com/news/1733534/india-invites-fm-bilawal-for-shanghai-cooperation-organisation-meeting-reports

### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/76880977/214525542-8880282c-aee8-4226-9ef7-26b8cc6d6e22.png)

##### Your filter lists
"Default filter lists"

### Your location/country
India

**Comment by dhowe** [comment]
I don't see this from the US:

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/737638/214759969-2998731a-10a4-4f0a-a2f7-c64932341806.png">

**Comment by mneunomne** [comment]
Also can't see it. @chirag127 Maybe you can try to activate the `IND: IndianList` filter list on the "Language" segment of the "filter lists" menu.

**Comment by chirag127** [comment]
> Also can't see it. @chirag127 Maybe you can try to activate the `IND: IndianList` filter list on the "Language" segment of the "filter lists" menu.

It's not Indian site.

**Comment by chirag127** [comment]
I myself not able to reporduce
