### ISSUE TITLE
do I have to log out while using all google products?

### ISSUE THREAD

**Issue by chirag127** [dhowe/AdNauseam#2260]
### Describe the issue

not an issue, just a question, do I have to log out while using all google products? I am very concerned about my email address and don't want to lose one. So I just want to understand why you guys recommend to log out? Show. Yeah. Do you have any kind of proof that some of the account has got banned. Because I have read the https://github.com/dhowe/AdNauseam/wiki/FAQ#can-i-use-adnauseam-while-logged-into-my-youtube-channel and I am very concerned after reading this answer.

**Comment by mneunomne** [comment]
Good question. I think this might be outdated. I have always used youtube while logged on, and never experienced any issue.

@dhowe do we have any reports in the last years regarding this?

**Comment by chirag127** [comment]
> Good question. I think this might be outdated. I have always used youtube while logged on, and never experienced any issue.
> 
> @dhowe do we have any reports in the last years regarding this?

Yeah, cause it is not possible for me to use the YouTube without internet.

**Comment by mneunomne** [comment]
I would say you can use it yes, I haven't experienced any issues.

**Comment by dhowe** [comment]
updated faq
