### ISSUE TITLE
[Adblocker Detected]

### ISSUE THREAD

**Issue by q-l-p** [dhowe/AdNauseam#2261]
### Site detects I use an adblocker.

The following site became unusable recently
https://www.matrimoniale.ro/

### Screenshot in which the issue can be seen

![adblockDetected](https://user-images.githubusercontent.com/19322149/214886914-4bbbc3ba-6f06-4c12-b3a8-d58a28fb64d8.png)

### Steps for anyone to reproduce the issue
Just visit the site:
https://www.matrimoniale.ro/

### Your settings

- OS/version: Windows 10 (64-bit)
- Firefox 109.0 (64-bit)
- AdNauseam version: 3.16.0

**Comment by dhowe** [comment]
I cannot recreate this:

![image](https://user-images.githubusercontent.com/737638/215923328-8ed4a03f-8094-490c-a9c1-339f669ab7f0.png)

**Comment by q-l-p** [comment]
Well... this is odd. Now I can't recreate it either. It seems the site works fine again. I don't know how it happened.

**Comment by dhowe** [comment]
ok, closing for now... let us know if this happens again
