### ISSUE TITLE
Suggest reload once strict-block is activated on the menu 

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2263]
It is a bit frustrating when using the strict-block function on the menu, since it will only matter once you reload the page (most ad scripts are loaded in the first page requests). 

Perhaps we can have something like uBlock menu has once you disable it for that page/domain:

<img width="250" alt="Screenshot 2023-01-27 at 16 18 56" src="https://user-images.githubusercontent.com/4967860/215122131-a25c0b38-0167-46bb-ab51-0b644db43bfc.png">

**Comment by mneunomne** [comment]
(actually this can also be applied for "disable" as well)

**Comment by mneunomne** [comment]
@dhowe but i think we need some sort of design for it. 

How the page currently looks:

<img width="318" alt="Screenshot 2023-01-27 at 21 01 41" src="https://user-images.githubusercontent.com/4967860/215186258-91e7f2fb-a158-420f-869e-893fa1c0820e.png">

**Comment by mneunomne** [comment]
@mushon would you have some suggestion for this?

**Comment by mushon** [comment]
Just to make sure I'm getting this straight, we want to add to the alert a CTA for reloading the page?

**Comment by mneunomne** [comment]
would be nice yes, I wonder if it can work as a notification perhaps? 

uBlock works like this, once you click on the power button, the refresh icon appears on the side:

<img width="254" alt="Screenshot 2023-02-25 at 15 21 41" src="https://user-images.githubusercontent.com/4967860/221361995-cf6897b1-1118-48bd-93fd-d077dc641f03.png">
<img width="253" alt="Screenshot 2023-02-25 at 15 21 38" src="https://user-images.githubusercontent.com/4967860/221361996-b235c32b-6b56-4f25-a314-f0da8735d45d.png">

**Comment by mushon** [comment]
I think in our case it would make sense to include this online with the notification. No?

**Comment by mneunomne** [comment]
Actually yes, I'll implement it as notification.

**Comment by dhowe** [comment]
@mneunomne please make sure that the warning disappears if the user _doesn't_ click refresh, and comes back to the menu later...

**Comment by mneunomne** [comment]
Yes, @dhowe implemented in a way that it is not actually a notification, but it just renders at the menu when changed. Also it dissapears if you change back to the original state before you do the refresh.

**Comment by mneunomne** [comment]
Implemented, closing
