### ISSUE TITLE
How to use adnauseam on kiwi browser 

### ISSUE THREAD

**Issue by chirag127** [dhowe/AdNauseam#2266]
### Describe the issue

How to use adnauseam on kiwi browser in the Android phone, please provide. Crx file as many other extensions which are banned from Google provide that .

**Comment by mneunomne** [comment]
@chirag127 I just tested and you can install Adnauseam using the `.crx` file available in the [release page](https://github.com/dhowe/AdNauseam/releases/latest).

![telegram-cloud-photo-size-2-5438542149068112761-y](https://user-images.githubusercontent.com/4967860/219638753-04ab0808-48b0-42da-9727-404b95a8b5e9.jpg)

Will add it to the installation documentation. thank you for the headsup, didnt know about kiwi browser for android.

**Comment by mneunomne** [comment]
I added kiwi as part of supported browsers on our wiki. Closing.
