### ISSUE TITLE
https://www.trackmenot.io/resources/trackmenot2009.pdf is 404

### ISSUE THREAD

**Issue by chirag127** [dhowe/AdNauseam#2267]
https://www.trackmenot.io/resources/trackmenot2009.pdf is 404 on https://github.com/dhowe/AdNauseam/wiki/About-AdNauseum

**Comment by mneunomne** [comment]
Thank you @chirag127. @dhowe I believe the file supposed to be this one? https://www.trackmenot.io/_files/ugd/654565_96fc2dcd8f7f4b55bc6caff610d061c2.pdf

**Comment by chirag127** [comment]
> Thank you @chirag127. @dhowe I believe the file supposed to be this one? https://www.trackmenot.io/_files/ugd/654565_96fc2dcd8f7f4b55bc6caff610d061c2.pdf

No problem, I found that while reading the complete Wiki but I am pretty surprised that I am the only one to point it out.

**Comment by dhowe** [comment]
has this been resolved ?

**Comment by mneunomne** [comment]
If the correct pdf file is https://www.trackmenot.io/_files/ugd/654565_96fc2dcd8f7f4b55bc6caff610d061c2.pdf than yes.

**Comment by chirag127** [comment]
It is not the pdf, it don't even mention adnauseam. I was looking for a
research paper where the authors had tested that adnauseam really cost them
money or not if they run ads.

**Comment by mneunomne** [comment]
@chirag127 you are right. But in the context of this wiki i guess the TrackMeNot paper was being referenced. The correct adnauseam paper would be this one:

https://ceur-ws.org/Vol-1873/IWPE17_paper_23.pdf

**Comment by dhowe** [comment]
Done

Feb 20, 2023 1:59:01 PM Alberto Harres ***@***.***>:

**Comment by mneunomne** [comment]
@chirag127 regarding your question:

>  I was looking for a research paper where the authors had tested that adnauseam really cost them money or not if they run ads.

This would be the correct paper:  https://nissenbaum.tech.cornell.edu/papers/The%20Big%20Story-%20Opinion.pdf

**Comment by chirag127** [comment]
> @chirag127 regarding your question:
> 
> > I was looking for a research paper where the authors had tested that adnauseam really cost them money or not if they run ads.
> 
> This would be the correct paper: https://nissenbaum.tech.cornell.edu/papers/The%20Big%20Story-%20Opinion.pdf

Oh thanks, now you can close this issue if you want because I got what I wanted

**Comment by chirag127** [comment]
Oh the link is replaced
