### ISSUE TITLE
AdNauseam considers YouTube thumbnails as image ads

### ISSUE THREAD

**Issue by Jurtaa** [dhowe/AdNauseam#2269]
### Describe the issue

Whenever I access the YouTube home page, AdNauseam immediately registers each video thumbnail as an image ad, causing some of them to not load.

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/29545237/218308606-3808d918-8f34-40d5-9d96-81703ea639ba.png)
![image](https://user-images.githubusercontent.com/29545237/218308622-230f5f7c-4266-4ba5-8925-833f6f2650ba.png)

### Steps for anyone to reproduce the issue
1. Load up the YouTube home page.
2. Note that thumbnails of videos won't load up and that they're all being considered as ads by AdNauseam.

### Your settings

- OS/version: Windows 11 Pro x64 (build 22621.1105)
- Browser/version: 109.0.1 (64-bit)
- AdNauseam version: v3.16.0
- Other extensions you have installed: Purely an AdNauseam issue, no other extensions I have could be contributing to this.
- AdNauseam settings: Hide Ads, Click Ads, and Block Malware

##### Your filter lists
Default filter lists

### Your location/country
United Kingdom

**Comment by romulasry** [comment]
> it appears that this is sporadic. sometimes it'll detect them as image ads but sometimes it won't.

Yes sometimes you have to refresh the page up to 5-10 times.

**Comment by mneunomne** [comment]
This is now fixed in master branch, I will make a release asap along with the fix.

**Comment by mneunomne** [comment]
Fixed in the current pre-release, should be out in official release in the next couple of days. Closing
