### ISSUE TITLE
First launch settings page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#227]
- Hide Ads
- Click Ads
- Block Malware

**Comment by mushon** [comment]
@dhowe how about this?
![popup-onboarding-1](https://cloud.githubusercontent.com/assets/27123/15961055/5aac76e2-2f0b-11e6-90a8-202ad752b19f.png)

**Comment by dhowe** [comment]
A couple of text issues, but otherwise great... I assume we want to automatically open the menu on install and show this screen?

**Comment by mushon** [comment]
Yes.
We could open the video in a tab or show the clickbot with a message like, I'm on it and an animation of clicking underway or something.

**Comment by dhowe** [comment]
so are you talking about the menu, a tab, or both?

**Comment by mushon** [comment]
The menu in the onboarding but maybe we should echo this in the first tab too?

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by dhowe** [comment]
Is there html/css for this?

**Comment by mushon** [comment]
Not yet. Where should I make them? Want to point me at a file?

**Comment by dhowe** [comment]
Ok, I've setup a page to launch on install. This gives us more space than the menu to add instructions, or a video, or whatever (and I think both would be annoying). So you can add whatever content you want in firstrun.html and firstrun.css.

**Comment by mushon** [comment]
Will do. Thanks. 

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by dhowe** [comment]
should also get an X for closing, like the vault

**Comment by dhowe** [comment]
Note also that we need some notification in the menu for when ad-hiding is set to false
