### ISSUE TITLE
Freestar VRM by Admiral popup: ublock detector

### ISSUE THREAD

**Issue by romulasry** [dhowe/AdNauseam#2271]
### Describe the issue

Freestar VRM by Admiral popup: ublock detector pops up on many sites

### Screenshot in which the issue can be seen
![Screenshot from 2023-02-13 15-39-36](https://user-images.githubusercontent.com/19944656/218637832-7f0360c4-807f-426f-b849-29e78d39f450.png)

### Steps for anyone to reproduce the issue
https://www.craiyon.com
Pops randomly after every so many times

### Your settings

- OS/version: Fedora Rawhide Linux
- Browser/version: Firefox/109.0
- AdNauseam version: 3.16.0
- Other extensions you have installed: Dark Reader
- AdNauseam settings:  Hide ads, Click ads and Block malware

##### Your filter lists
Default + uBlock filters – Annoyances

### Your location/country
Southern California, USA

** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

**Comment by mneunomne** [comment]
Tried to fix it with https://github.com/dhowe/AdNauseam/pull/2274, seems it is working on my side, need to keep testing since it is intermintent
