### ISSUE TITLE
Fallback font that supports scripts other than latin

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2288]
<img width="323" alt="Снимок экрана 2023-02-21 в 12 57 21" src="https://user-images.githubusercontent.com/4967860/220338762-a38445d1-deb4-42ee-8894-c6097fad28ea.png">

Besides the obvious layout issues with the different size of string https://github.com/dhowe/AdNauseam/issues/2246, would be also good to have a fallback font that has UTF-8 support for scripts other than latin that can match this same style (something like impact? i'm not sure). The issue here is with the 'bebas_neue' font that we are using.

**Comment by mneunomne** [comment]
Found this font "Yanone Kaffeesatz" with free lincense which is condensed and has support for cyrilic alphabets:

https://fonts.google.com/specimen/Yanone+Kaffeesatz?category=Sans+Serif&subset=cyrillic&width=2&noto.lang=bg_Cyrl&noto.script=Cyrl

**Comment by mneunomne** [comment]
## Before:

<img width="772" alt="Bildschirm­foto 2023-02-21 um 14 45 17" src="https://user-images.githubusercontent.com/4967860/220362509-1c564dca-7253-43e7-baa1-f67c3dfa859e.png">
<img width="909" alt="Bildschirm­foto 2023-02-21 um 14 45 14" src="https://user-images.githubusercontent.com/4967860/220362516-2a0db3e8-8d42-40c9-8e5d-c6c1c9a35233.png">

## After:

<img width="1099" alt="Bildschirm­foto 2023-02-21 um 14 42 45" src="https://user-images.githubusercontent.com/4967860/220362588-e03fc8db-a3f8-4b0a-9b95-1e69c17d0af5.png">
<img width="1207" alt="Bildschirm­foto 2023-02-21 um 14 42 41" src="https://user-images.githubusercontent.com/4967860/220362593-c1501de4-dd32-49d8-acc8-effd5b7e60d7.png">
<img width="318" alt="Снимок экрана 2023-02-21 в 14 39 21" src="https://user-images.githubusercontent.com/4967860/220362595-3f5b78c9-615e-4e1c-abf2-86bccf8b8cd5.png">

**Comment by mneunomne** [comment]
@mushon let me know if this is ok, if you find another font maybe with wider support, let me know and I can substitute.

**Comment by mneunomne** [comment]
## Test fonts for other writing systems:

- [ ] Arabic 
- [ ] Hebrew
- [ ] Japanese
- [ ] Chinese
- [ ] Hindi

**Comment by mushon** [comment]
I suggest we build the stack like this:
1. Bebas Neue <https://fonts.google.com/specimen/Bebas+Neue?preview.text=ADNAUSEAM&preview.text_type=custom&query=bebas>
2. Roboto Flex <https://fonts.google.com/specimen/Roboto+Flex/tester?vfonly=true&preview.text=ADNAUSEAM&preview.text_type=custom>
3. Noto Sans Display <https://fonts.google.com/noto/specimen/Noto+Sans+Display/tester?vfonly=true&query=noto+sans&preview.text=ADNAUSEAM&preview.text_type=custom>

Does that make sense?

Mushon Zer-Aviv

///

Recent:
Friction & Flow Keynote @ RISD <https://youtu.be/J2uV8DByF9g>
Normalizi.ng <https://normalizi.ng/>
What do normal people look like? <https://www.goethe.de/prj/zei/en/pdk/22769146.html>

///

mushon.com <http://mushon.com/>
@mushon <http://twitter.com/mushon>

**Comment by mneunomne** [comment]
@mushon yes, makes sense. I just need to know what width (or other variable axes) should I use Roboto Flex and Noto Sans to match the shape of bebas neue, so it is condensed the same way.

**Comment by mushon** [comment]
Yes, that’s the idea. They are both variable fonts so you can get pretty close to the width on Bebas with them.

**Comment by mneunomne** [comment]
Cool, tested now with multiple languges and looks good, they are following the font fallback order as you mentioned:

1. Bebas Neue <https://fonts.google.com/specimen/Bebas+Neue?preview.text=ADNAUSEAM&preview.text_type=custom&query=bebas>
2. Roboto Flex <https://fonts.google.com/specimen/Roboto+Flex/tester?vfonly=true&preview.text=ADNAUSEAM&preview.text_type=custom>
3. Noto Sans Display <https://fonts.google.com/noto/specimen/Noto+Sans+Display/tester?vfonly=true&query=noto+sans&preview.text=ADNAUSEAM&preview.text_type=custom>

## Chinese (Traditional)

<img width="1111" alt="截圖 2023-02-21 18 21 31" src="https://user-images.githubusercontent.com/4967860/220415838-387f779c-564a-4fee-98ac-872c10f3036a.png">

<img width="1283" alt="截圖 2023-02-21 18 21 26" src="https://user-
images.githubusercontent.com/4967860/220415845-4b008302-6a2a-4e2a-b486-19788fffff52.png">

## Japanese

<img width="1025" alt="スクリーンショット 2023-02-21 18 20 15" src="https://user-images.githubusercontent.com/4967860/220415851-86c39063-286a-4869-9390-2003be7a8472.png">

<img width="1377" alt="スクリーンショット 2023-02-21 18 20 12" src="https://user-images.githubusercontent.com/4967860/220415853-747bfc64-c461-4675-a3bb-35415aa6189c.png">

<img width="318" alt="スクリーンショット 2023-02-21 18 20 01" src="https://user-images.githubusercontent.com/4967860/220415860-86e48c48-a8a3-46dc-b943-cf425b66a30f.png">

## Ukranian

<img width="1117" alt="Знімок екрана 2023-02-21 о 18 19 29" src="https://user-images.githubusercontent.com/4967860/220415862-cc5a6147-ef88-4750-939f-bff45f58841e.png">

<img width="915" alt="스크린샷 2023-02-21 18 17 36" src="https://user-images.githubusercontent.com/4967860/220415867-60cc3217-95f4-4d9f-91fa-81caaca89db6.png">

## Chinese (Simplified)

<img width="1187" alt="截屏2023-02-21 18 17 01" src="https://user-images.githubusercontent.com/4967860/220415872-093c2b2a-0511-430f-8fe0-3a638c644822.png">

<img width="319" alt="截屏2023-02-21 18 16 45" src="https://user-images.githubusercontent.com/4967860/220415875-729482b8-0970-4fca-9247-845cede3719d.png">

## Russian 

<img width="1148" alt="Снимок экрана 2023-02-21 в 18 16 12" src="https://user-images.githubusercontent.com/4967860/220415877-0cb2e113-9c4e-45c4-a876-70612fa99e37.png">

<img width="1240" alt="Снимок экрана 2023-02-21 в 18 16 07" src="https://user-images.githubusercontent.com/4967860/220415882-73961961-8f5f-47ee-b9be-3b316a246c69.png">

<img width="320" alt="Снимок экрана 2023-02-21 в 18 16 03" src="https://user-images.githubusercontent.com/4967860/220415885-e755f4dd-811f-473d-bdb9-8df9c91f3407.png">

**Comment by mneunomne** [comment]
## Hindi

<img width="1048" alt="स्क्रीनशॉट 2023-02-21, 18 37 14 पर" src="https://user-images.githubusercontent.com/4967860/220419080-d73880da-1b0f-411d-9487-27b8790cb78f.png">

## Bengali

<img width="1131" alt="Screenshot 2023-02-21 at 18 36 42" src="https://user-images.githubusercontent.com/4967860/220419095-48db9b03-a2d8-4cc5-90dc-0f3c43561ec6.png">
<img width="319" alt="Screenshot 2023-02-21 at 18 36 33" src="https://user-images.githubusercontent.com/4967860/220419097-9d250837-7b9d-46a9-aab3-9522bfeb6da8.png">

**Comment by mushon** [comment]
Great, thanks!

**Comment by mneunomne** [comment]
Implemented, closing.
