### ISSUE TITLE
clicking youtube videos

### ISSUE THREAD

**Issue by venkat2305** [dhowe/AdNauseam#2297]
### Describe the issue

the YouTube videos are being clicked. not the ads. 

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/55329452/221107092-53b32d18-52bf-44af-8431-8e146ce688b2.png)

### Steps for anyone to reproduce the issue
open youtube home page

### Your settings

- OS/version: Windows 10
- Browser/version: 110.0.1587.50
- AdNauseam version: 3.16.0
- Other extensions you have installed: no other extensions installed which can block ads / modify web pages.
- AdNauseam settings: 

##### Your filter lists
![image](https://user-images.githubusercontent.com/55329452/221107454-9e1a4469-8208-4e92-a159-893ccc1614da.png)

### Your location/country
India

** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

**Comment by Jurtaa** [comment]
already resolved, see #2269

**Comment by venkat2305** [comment]
When can we expect the update?

**Comment by mneunomne** [comment]
Released now https://github.com/dhowe/AdNauseam/releases/tag/v3.16.2, we will submit to the extension stores today and should be updated within the next few days.

**Comment by mneunomne** [comment]
Since this is already fixed, closing now.
