### ISSUE TITLE
this site has an error when the extension is active.

### ISSUE THREAD

**Issue by aquila0101** [dhowe/AdNauseam#2303]
this is the site link:

https://factorioprints.com/view/-LXKNiq2eQz5_MUxuEDY

![Captura de tela 2023-02-26 095329](https://user-images.githubusercontent.com/84749877/221411671-6138ca78-b7df-4427-8221-e519c6085dcd.png)
![Captura de tela 2023-02-26 095354](https://user-images.githubusercontent.com/84749877/221411674-0a96e41c-1d73-4d60-b645-389145042405.png)

**Comment by mneunomne** [comment]
Thank you @aquila0101 for letting us know. It seems that the javascript of this page is somehow dependent on some ad scripts. 

Had to do an extra blocking of the following script in order for it to work:

```
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=factorioprints.com,important
```

Already on master, you can update the filter now and it should work.

**Comment by aquila0101** [comment]
Thank you working without problems.
