### ISSUE TITLE
bing.com

### ISSUE THREAD

**Issue by chirag127** [dhowe/AdNauseam#2305]
### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/76880977/221860317-19d3d4bf-0110-4c87-b484-4cef94c8ddd4.png)

### Steps for anyone to reproduce the issue
1. go to site https://www.bing.com/search?q=ai+writing+tool+online+free&FORM=R5FD
2. see ad

### Your settings

- OS/version:

Edition	Windows 11 Home Single Language
Version	21H2
Installed on	‎05-‎07-‎2022
OS build	22000.1219
Experience	Windows Feature Experience Pack 1000.22000.1219.0

- Browser/version: 
![image](https://user-images.githubusercontent.com/76880977/215261644-7bc2a962-2431-4a80-a741-1a44178d5b8c.png)

- AdNauseam version: 
![image](https://user-images.githubusercontent.com/76880977/215261634-a76f1799-dba9-4cdd-8985-d31ef7b6d5f2.png)

- Other extensions you have installed: no
- AdNauseam settings: default

##### Your filter lists
 "Default filter lists"

### Your location/country
India

**Comment by mneunomne** [comment]
Was only able to temporarily reproduce the ads appearing, perhaps not updated filter lists?

Either way ads were not being collected, updated a fix for up above adding the domain to the `internalLinkDomains` list.

**Comment by chirag127** [comment]
> Was only able to temporarily reproduce the ads appearing, perhaps not updated filter lists?
> 
> Either way ads were not being collected, updated a fix for up above adding the domain to the `internalLinkDomains` list.

hmm.. so, the issue should be closed? if just the issue of not updated filter lists?

**Comment by chirag127** [comment]
https://www.bing.com/search?q=free+ai+content+writer&FORM=R5FD 


![image](https://user-images.githubusercontent.com/76880977/222431342-ff5f3163-a13b-4f1c-b2d0-44a81c7e14e5.png)


I can still reproduce after update

**Comment by chirag127** [comment]
and the bing ads are very misleading as the mention of **ad** is very small

**Comment by chirag127** [comment]
> Was only able to temporarily reproduce the ads appearing, perhaps not updated filter lists?
> 
> Either way ads were not being collected, updated a fix for up above adding the domain to the `internalLinkDomains` list.

I have seen that the bing don't show ads of same term after shown once

**Comment by chirag127** [comment]
but that doesn't mean adnaeseam is blocking ads
