### ISSUE TITLE
Make lists on core.js editable by the user

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2311]
The following lists on core.js are currently hard-coded:

- ~~`enabledBlockLists`~~
- ~~`removableBlockLists`~~
- `internalLinkDomains`

which makes issues such as https://github.com/dhowe/AdNauseam/issues/2310 only fixable by making a new release. This should be able to controlled directly by the user by one of the options:
- specific tab for such lists
- advanced settings

**Comment by dhowe** [comment]
tradeoff here is how often/likely/useful they are to be adjusted by user vs the implementation and maintenance cost

if we do implement, need to make sure these are hidden away from the typical user in some kind of advanced management tab...

**Comment by mneunomne** [comment]
Here in the advanced settings you have the option to have parameters as arrays as well:

![Screen Shot 2023-03-05 at 15 41 02](https://user-images.githubusercontent.com/4967860/222967257-a4c30099-5b85-4e17-b97a-bc8b8d3bc5eb.png)

**Comment by mneunomne** [comment]
I'll apply the case above for `internalLinkDomains` only. `enabledBlockLists` should be done in the 3p-filters tab with a checkbox somehow, as suggested here https://github.com/dhowe/AdNauseam/issues/1003
