### ISSUE TITLE
Ads on YouTube & regular videos being recognised as ads and clicked on

### ISSUE THREAD

**Issue by nitrogenfive** [dhowe/AdNauseam#2315]
### Describe the issue

I'm still receiving ads during videos on YouTube, and AdNauseum seems to be clicking every YouTube video

### Screenshot in which the issue can be seen
<img width="1219" alt="Screenshot 2023-03-16 at 4 31 54 pm" src="https://user-images.githubusercontent.com/105533515/225559657-55eb5774-ce12-4fad-a145-f891bc669761.png">

### Steps for anyone to reproduce the issue
Use YouTube.com

### Your settings

- OS/version: MacOS 13.2.1
- Browser/version: Arc 0.93.0 (Chromium 111.0.5563.64)
- AdNauseam version: v3.16.0 
- Other extensions you have installed: Bypass Paywalls Clean, 12ft Free, Bitwarden, Download All Images, Modern for Wikipedia, Neeva Search + Protect, Promoted Pin Hider, Ruffle, Shinigami Eyes, SponsorBlock, Tumblr Savior, XKit Rewritten, User-Agent Switcher
- AdNauseam settings: `{
  "timeStamp": 1678955797664,
  "version": "3.16.0",
  "userSettings": {
    "dntDomains": [
      "00px.net",
      "0sercher.biz",
      "18plus-online.com",
      "18plusvideos.me",
      "18video-on.com",
      "1lida.org",
      "1music-online.me",
      "1video-online.me",
      "2ysts6mjemhg.com",
      "65daysofstatic.com",
      "99designs.community",
      "ablackcover.com",
      "abzugame.com",
      "acceptww.com",
      "addsearch.com",
      "addsleeper.com",
      "adultcontent18.com",
      "adultplayone.site",
      "advwomennews.ru",
      "airlinepilot.life",
      "ajile.life",
      "alfonsino.top",
      "algolia.net",
      "algolianet.com",
      "allfileshere.cc",
      "allow-space.com",
      "allowandgo.club",
      "allowandgo.com",
      "allowandgo.link",
      "allowww.com",
      "almestal.com",
      "alwadeluze.net",
      "anidb.info",
      "anidb.net",
      "anqnw28cp567.com",
      "answerswords.xyz",
      "anwapfile.live",
      "apel.top",
      "appbox.co",
      "appboxes.co",
      "appplepie.biz",
      "appsmode.me",
      "artxlagos.com",
      "atlasrn.fr",
      "attrition.org",
      "au01.bid",
      "august-wap.com",
      "barbel.top",
      "bazzzmedia.com",
      "beastclick.biz",
      "beksvideo.lol",
      "best-click.net",
      "bestgore.fun",
      "bigplans.biz",
      "bigsoul.biz",
      "bitcointv.com",
      "blackmusic24.biz",
      "blancstructure.com",
      "bloodyhellbighead.com",
      "bluelabelsky.com",
      "blueskyactivecontrol.com",
      "blueskyactivecontrol.net",
      "blueskymotions.com",
      "blueskymotions.net",
      "bluestringline.com",
      "bollingerjack.top",
      "bolt.io",
      "branddnewcode1.me",
      "bringmeredline.com",
      "bro1.biz",
      "brocode1s.com",
      "brocode2s.com",
      "brocode3s.com",
      "brocode4s.com",
      "brodirect.site",
      "brodirect2s.com",
      "brodmn.com",
      "brodownload.site",
      "brodownloads.site",
      "broforyou.me",
      "brolink.site",
      "broluckycode.site",
      "bromusic.site",
      "brop1.com",
      "bropu2.com",
      "bropushnew.site",
      "broredir.site",
      "brovideos.site",
      "broweb.site",
      "brownluxuryservice.com",
      "brownluxuryservice.net",
      "browntouchmysky.com",
      "browork3er.cc",
      "broworker1s.com",
      "broworker4s.com",
      "broworker7.com",
      "bualpush1.biz",
      "burnermail.io",
      "butdoesitfloat.com",
      "bv2fb.com",
      "cadence.moe",
      "cangomedia.biz",
      "cargo.site",
      "checkandgo.info",
      "checkfilter.biz",
      "checkmerobot.cc",
      "checkmyplace.com",
      "checkpost.club",
      "checkrobotics.com",
      "checkrobotics.link",
      "checkup01.biz",
      "checkup02.biz",
      "checkup03.biz",
      "checkup05.biz",
      "checkup07.biz",
      "checkup08.biz",
      "chopose.icu",
      "chow-chow.top",
      "christienmeindertsma.com",
      "chya.info",
      "clarifyspotify.online",
      "classicvideo.ru",
      "clearblueline.com",
      "cleargreenline.com",
      "cleverwhitespaces.com",
      "click2.club",
      "clickgate.biz",
      "clickgate01.biz",
      "clickgate02.biz",
      "clickgate07.biz",
      "clickgate09.biz",
      "clickstar.club",
      "clicktimes.bid",
      "clickworker.me",
      "cloudsao.com",
      "codepoints.net",
      "codesbro.com",
      "complexcare.biz",
      "conf.tube",
      "conservationphotographers.org",
      "content-hub.biz",
      "content-lib.biz",
      "contentpass.net",
      "coryschmitz.com",
      "countersmoon.com",
      "coursera-apply.org",
      "creativetwilight.com",
      "ctworker.biz",
      "dabuttonfactory.com",
      "dao01.bid",
      "ddg.gg",
      "deeepmedia.biz",
      "deencourier.biz",
      "deidamiapele.com",
      "destinyinbluesocks.com",
      "destinyinredsocks.com",
      "destruction.top",
      "detectmus.com",
      "detectvid.com",
      "di02.biz",
      "di03.biz",
      "di04.biz",
      "di05.biz",
      "di06.biz",
      "di07.biz",
      "di1.biz",
      "di10.biz",
      "di12.biz",
      "di13.biz",
      "di3.biz",
      "di4.biz",
      "digestion.top",
      "diode.zone",
      "avatars.discourse.org",
      "try.discourse.org",
      "disruptiveimaginations.com",
      "dm01.biz",
      "dm02.biz",
      "dm03.biz",
      "dm04.biz",
      "dm06.biz",
      "dm07.biz",
      "dm08.biz",
      "dm9.biz",
      "dn9.biz",
      "do-not-tracker.org",
      "donttrack.us",
      "download-app.net",
      "downloadnow-on.com",
      "dr0.biz",
      "dr5.biz",
      "dr6.biz",
      "dr7.biz",
      "dreamnews.biz",
      "drukkerijmiddelburg.nl",
      "ds0.biz",
      "ds1.biz",
      "ds3.biz",
      "ds5.biz",
      "ds6.biz",
      "duck.com",
      "duckduckgo.com",
      "duckduckgo.de",
      "datawrapper.dwcdn.net",
      "edpresenfer.com",
      "act.eff.org",
      "eff.org",
      "eisenmanarchitects.com",
      "elyotherm.fr",
      "ericchakeen.com",
      "expertrec.com",
      "exploremedias.biz",
      "express-new.com",
      "extravideo.live",
      "f4t6y.monster",
      "f5h7j.monster",
      "factormedia.biz",
      "famousletterss.online",
      "fps-farfetch-payment-gateway.farfetch.net",
      "fastcheck.top",
      "favelapainting.com",
      "favoritespace.top",
      "filemix-1.com",
      "finance-calculator.co.uk",
      "first-bitcoin.site",
      "firstpartysimulator.net",
      "firstpartysimulator.org",
      "flirtmedia.biz",
      "flitsmeisterapp.com",
      "flowersforsunshine.com",
      "followpractice.com",
      "folowme.biz",
      "framatube.org",
      "frankerfacez.com",
      "freeradical.zone",
      "fresh-content.biz",
      "freshdollars.biz",
      "fuckass.org",
      "g1news.biz",
      "g3news.biz",
      "g4news.biz",
      "g5news.biz",
      "games-n1.ru",
      "gamingonlinux.com",
      "gandi.net",
      "gcpay.com",
      "gegenstimme.tv",
      "geoffreybawa.com",
      "gerdvideo.biz",
      "ggc747r7479t.com",
      "gitvideo.cam",
      "gloveryforbluewine.com",
      "gloveryforredwine.com",
      "glowersfornightmare.com",
      "gmunk.com",
      "go0s.biz",
      "go1news.biz",
      "go4s.biz",
      "go5s.biz",
      "go6s.biz",
      "go7s.biz",
      "go9s.biz",
      "gobacktothefuture.biz",
      "goldflowerservice.com",
      "goldflowerservice.net",
      "goldline-plus.ru",
      "gomajor1.com",
      "gomajorlink.com",
      "gonewind.biz",
      "gonews2.com",
      "goodinc.com",
      "goodvibesforus.com",
      "goodvibesmatterforus.com",
      "gopusher1.com",
      "gopushka1.com",
      "gopushmajor1.com",
      "goredb.com",
      "goresee.com",
      "gorf.tube",
      "gps-data-team.com",
      "grapheneos.org",
      "greatlandingpagecopy.com",
      "green-wap.com",
      "greenskymotions.com",
      "greenskymotions.net",
      "greenspecialmyline.com",
      "gregoryfavorite.top",
      "groundflares.com",
      "groundflares.net",
      "growcontent.biz",
      "haip2wek.site",
      "hausofwonder.kr",
      "havanese.top",
      "hd-720.xyz",
      "hd-click.net",
      "healingautoimmune.com",
      "heartmedia.biz",
      "helllomedias.com",
      "henryhargreaves.com",
      "hiorbye.de",
      "holystick.design",
      "horgi.top",
      "hotservers.net",
      "howtoons.com",
      "hubzilla.org",
      "hubzilla.rocks",
      "humminbird.top",
      "ice-hockey.top",
      "impermanent.digital",
      "ingmar.club",
      "innoreader.com",
      "ino.com",
      "inoreader.com",
      "ipp-meredith.com",
      "iwascoding.com",
      "iwascoding.de",
      "jms1.net",
      "johannesburg.top",
      "joshuadavis.com",
      "juanamolina.com",
      "july-wap.com",
      "justsoftwaresolutions.co.uk",
      "kastking.top",
      "ketosummit.com",
      "klemusvid.cc",
      "kodmagic1.me",
      "lan01.bid",
      "lan02.bid",
      "lan03.bid",
      "lauren-mccarthy.com",
      "letmeok.com",
      "lex-forum.net",
      "lhspeaking.com",
      "libre.video",
      "lida.in",
      "lifecontext.me",
      "lifestyleupdated.com",
      "lightgreenstep.com",
      "lightredstep.com",
      "lin01.bid",
      "lin02.bid",
      "linksforyou.me",
      "list2list.biz",
      "listen-heres.com",
      "listingme.biz",
      "listlist.club",
      "livewweb.click",
      "load02.biz",
      "load04.biz",
      "load16.biz",
      "load18.biz",
      "load5.biz",
      "load7.biz",
      "lodder7.biz",
      "lodmagic.com",
      "lookvideonow.eu",
      "looo.ch",
      "lot-ek.com",
      "lovehoneyforum.com",
      "lowrance.top",
      "lugnsk.org",
      "luuming.com",
      "lyeaxoybav9w.com",
      "magic1.biz",
      "magic1.me",
      "magic4.biz",
      "magic5.biz",
      "magicstt.com",
      "magictt1.com",
      "majoriklink.com",
      "majorikmedia.com",
      "majorikwork.com",
      "majorilink.com",
      "majorius.com",
      "majorlink.club",
      "majorlinker.biz",
      "majorlinker.com",
      "majorpusher1.com",
      "majortoplink.com",
      "majorworkbig.com",
      "majorworker.club",
      "majorworker.com",
      "majorworker1.com",
      "majorworkertop.com",
      "majorworkhard.com",
      "majorworkio.com",
      "majorworkjob.com",
      "majorworklink.com",
      "mediadate.net",
      "mediapush1.com",
      "cdn-client.medium.com",
      "cdn-images-1.medium.com",
      "cdn-static-1.medium.com",
      "glyph.medium.com",
      "miro.medium.com",
      "mediumhiquality.com",
      "meekness.biz",
      "meredithbardo.com",
      "mixshnuk.ru",
      "mo01.biz",
      "mo02.biz",
      "mo06.biz",
      "mo07.biz",
      "mo08.biz",
      "mo10.biz",
      "mo11.biz",
      "mo12.biz",
      "mo13.biz",
      "mo14.biz",
      "mo16.biz",
      "mo17.biz",
      "mo18.biz",
      "mo19.biz",
      "mo20.biz",
      "mo21.biz",
      "mo23.biz",
      "mol1.biz",
      "mol17.biz",
      "mol2.biz",
      "monterrey.top",
      "more6.biz",
      "mos3.biz",
      "mosaic.org",
      "mous0.biz",
      "mous3.biz",
      "mous5.biz",
      "mous6.biz",
      "mous7.biz",
      "mous9.biz",
      "msgby.ru",
      "music-listen1.com",
      "musicinmysoul.biz",
      "musicplay-on.com",
      "musmentportal.com",
      "muson4ik.site",
      "musvidplay.cc",
      "muzeeum.nl",
      "my-tracking.info",
      "myarcadeplugin.com",
      "n06.biz",
      "n17.biz",
      "n19.biz",
      "n1gopush.com",
      "n1goserch.com",
      "n1major.com",
      "n1serch.biz",
      "n1topserch.com",
      "n4serch.biz",
      "n7pusher.com",
      "nastub.cz",
      "ne02.biz",
      "ne05.biz",
      "ne09.biz",
      "ne20.biz",
      "net00.biz",
      "net06.biz",
      "net17.biz",
      "netspooke2.biz",
      "netspooke3.biz",
      "newess2wik.site",
      "newporta.pro",
      "newpost777.ru",
      "newpostgeo.ru",
      "newpush.site",
      "news02.biz",
      "news2day.me",
      "news98.biz",
      "newscode.me",
      "newsforyou.me",
      "newtext.club",
      "newzmaker.me",
      "ngo-online.de",
      "ninaberman.com",
      "nobodyhere.biz",
      "nocodekorea.org",
      "nonamebooks.com",
      "nopattern.com",
      "omglord.com",
      "oo00.biz",
      "oo01.biz",
      "op00.biz",
      "op02.biz",
      "op04.biz",
      "op05.biz",
      "op06.biz",
      "op08.biz",
      "op09.biz",
      "op10.biz",
      "openimp.net",
      "p2ptv.ru",
      "paintedseries.com",
      "paleoflourish.com",
      "pasteapp.com",
      "peertube.uno",
      "petrohradskakolektiv.com",
      "pianosnyc.com",
      "picmedia.biz",
      "pieterhugo.com",
      "piovenefabi.it",
      "planetaryhealthalliance.org",
      "plastique-fantastique.de",
      "playmusicvideo1.com",
      "plusclick.biz",
      "poidirectory.com",
      "pointephemere.org",
      "politicosta.biz",
      "pony.tube",
      "porno-info.com",
      "postday.me",
      "postmarketos.org",
      "powerain.biz",
      "presssnews.biz",
      "productcontent.company",
      "pu1.biz",
      "pu3.biz",
      "pu4.biz",
      "pushadv.biz",
      "pushadvert.bid",
      "pushbr.shop",
      "pusher1.com",
      "pusherworker.com",
      "pushmajor1.com",
      "pushratio.ru",
      "pushrobot.ru",
      "pushview.biz",
      "pushworks.bid",
      "qoubvideo.ru",
      "qqqqdesign.com",
      "quicksub.bid",
      "ravescout.club",
      "raymarine.top",
      "razvod-suprugov.ru",
      "readthedocs.org",
      "realityripple.com",
      "recutservice.com",
      "redirectsi.ru",
      "redirit1.me",
      "redirzp5.me",
      "redmatrix.us",
      "rednoise.org",
      "redspecialmyline.com",
      "redstringline.com",
      "relaxtime24.biz",
      "report3.biz",
      "ro3.biz",
      "ro5.biz",
      "roboverify.club",
      "roboverify.vip",
      "rockstonefirst.com",
      "rockstonesecond.com",
      "rodacy.tv",
      "romain-laurent.com",
      "rozitaz.ru",
      "rpbln.work",
      "rproot.work",
      "rtfd.io",
      "rtfd.org",
      "safenetforum.org",
      "saint-petersburg.top",
      "sampaints.com",
      "sapsrc3.site",
      "saretx.website",
      "scroll.com",
      "se01.biz",
      "se03.biz",
      "se04.biz",
      "se05.biz",
      "se06.biz",
      "se07.biz",
      "se10.biz",
      "se13.biz",
      "se14.biz",
      "se15.biz",
      "se17.biz",
      "se19.biz",
      "selectrobots.biz",
      "serch01.biz",
      "serch02.biz",
      "serch05.biz",
      "serch07.biz",
      "serch24.biz",
      "serch26.biz",
      "sergiovillalba.com",
      "serii.co",
      "sexateam.ru",
      "shar-pei.top",
      "share.tube",
      "shotatube.xyz",
      "silverlinetogther.com",
      "silverlinetogther.net",
      "similarworlds.com",
      "simpledeeep.com",
      "simpleworker.biz",
      "siteforyou.me",
      "sixminutes.biz",
      "skeptikon.fr",
      "skydive-club.com",
      "skymedia7.me",
      "slate.app",
      "smartklick.biz",
      "smilerweek.com",
      "snopyta.org",
      "solo8.biz",
      "solo93.biz",
      "solutionwords.xyz",
      "somenewforyou.cc",
      "somenewforyou.com",
      "sovendus.com",
      "sovendus.de",
      "spacecollective.org",
      "starka.st",
      "startmode.biz",
      "state51.com",
      "stepbystepz.biz",
      "stitchfiddle.com",
      "stripe.community",
      "strongblackspaces.com",
      "strongwhitespaces.com",
      "subsworker.bid",
      "sunnoodle.com",
      "sunwheather.biz",
      "superfamous.com",
      "supermedia777.biz",
      "susanmeiselas.com",
      "sutteruk.biz",
      "swconnect.biz",
      "swimsunleisure.com",
      "teodormoisescu.com",
      "termovideo.ru",
      "texterra.me",
      "textureontexture.kr",
      "thenewraw.org",
      "theobituaryproject.org",
      "thewrong.org",
      "thomas-mcbrien.com",
      "tilvids.com",
      "tinariwen.com",
      "to1s.biz",
      "to2s.biz",
      "to3s.biz",
      "to5s.biz",
      "to6s.biz",
      "to7s.biz",
      "to8s.biz",
      "togo01.site",
      "togo02.site",
      "togo03.site",
      "togo04.site",
      "toloudme.biz",
      "topmusic01.biz",
      "topwebsites.me",
      "trackspecialdomain.com",
      "trackspecialsdomain.com",
      "travis-ci.community",
      "trendcounter.com",
      "trustersmile.com",
      "tvkinot.ru",
      "twittercommunity.com",
      "unurth.com",
      "unusual.la",
      "updatemeter.com",
      "us02.biz",
      "us03.biz",
      "us04.biz",
      "us05.biz",
      "us07.biz",
      "us08.biz",
      "us09.biz",
      "ussr.win",
      "vasyarun.ru",
      "vectorlogo.zone",
      "vektprava.ru",
      "veovideo.tech",
      "verifyrobot.info",
      "verifyrobot.online",
      "viddetect.com",
      "video-search-on.com",
      "video-watch1.com",
      "video18on.com",
      "videoforyou.me",
      "videoplay-on.com",
      "videopool.ru",
      "videos18plus.me",
      "videospots.ru",
      "vidsy.ru",
      "viewing.nyc",
      "viewunic.ru",
      "vinuser5.biz",
      "vinuser6.biz",
      "visualmelt.com",
      "visura.co",
      "vpnclick.biz",
      "w1sercher.biz",
      "w720nvsrhihq.com",
      "wap-karas.com",
      "warszawawpigulce.pl",
      "washedout.net",
      "watch-visd.com",
      "watchvideonow.eu",
      "wbru.com",
      "whiteclick.biz",
      "whitetouchmysky.com",
      "widemus.de",
      "winworker.club",
      "wirtube.de",
      "wordsinfo.xyz",
      "workerconnect.biz",
      "workerz1.com",
      "wpstagecoach.com",
      "wstep1.biz",
      "wstep3.biz",
      "wstep4.biz",
      "wstep5.biz",
      "wwclickads.club",
      "wwclicknews.club",
      "wwclickserv.club",
      "wwopenclick.club",
      "wwopenclick.space",
      "wwopenclick.vip",
      "wwserch41.biz",
      "wwserch44.biz",
      "xxxconent.biz",
      "xxxmedia.bid",
      "y.com.sb",
      "yewtu.be",
      "youngjerks.com",
      "youngmedias.biz",
      "yourbestbro.site",
      "yourbrolink.me",
      "z93sjhj5p58j.com",
      "zcode-sites.com",
      "zcode10.me",
      "zcode11.me",
      "zcode12.me",
      "zcode6.me",
      "zcode7.me",
      "zcode8.me",
      "zebra-flex.com",
      "zerotrust.plus",
      "zotum.net",
      "zpcode11.com",
      "zpgetworker11.com",
      "zpworker1.com",
      "zpworker2.com",
      "zpworker5.me",
      "zworker10.com",
      "zworker11.me",
      "zworker7.me",
      "zworker9.me"
    ],
    "firstInstall": false,
    "hidingAds": true,
    "clickingAds": true,
    "blockingMalware": true,
    "disableHidingForDNT": true,
    "disableClickingForDNT": true,
    "importedLists": []
  },
  "selectedFilterLists": [
    "user-filters",
    "assets.json",
    "public_suffix_list.dat",
    "ublock-resources",
    "adnauseam-filters",
    "eff-dnt-whitelist",
    "ublock-badlists",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "ublock-quick-fixes",
    "easylist",
    "easyprivacy",
    "urlhaus-1"
  ],
  "hiddenSettings": {},
  "whitelist": [
    "about-scheme",
    "chrome-extension-scheme",
    "chrome-scheme",
    "edge-scheme",
    "moz-extension-scheme",
    "opera-scheme",
    "vivaldi-scheme",
    "wyciwyg-scheme"
  ],
  "dynamicFilteringString": "behind-the-scene * * noop\nbehind-the-scene * inline-script noop\nbehind-the-scene * 1p-script noop\nbehind-the-scene * 3p-script noop\nbehind-the-scene * 3p-frame noop\nbehind-the-scene * image noop\nbehind-the-scene * 3p noop\nyoutube.com * * strictBlock\nfunnyordie.com * * strictBlock",
  "urlFilteringString": "",
  "hostnameSwitchesString": "no-large-media: behind-the-scene false",
  "userFilters": "! 2023-02-27 https://knowyourmeme.com\nknowyourmeme.com##.vjs-user-inactive.vjs-playing.lx-size-0.ac-lre-small-player.vjs-layout-x-small.cc-hidden.vjs-has-started.vjs-v7.vjs-workinghover.vjs-controls-enabled.vjs-fluid.ac-lre-vjs-d0hUeJ2xpnU8DhlRO7FZTpoqgZoSegSG-dimensions.vjs-default-skin.video-js\n"
}`

##### Your filter lists
Default

### Your location/country
Australia

** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

**Comment by mneunomne** [comment]
this should have been fixed in the last release, you sure you are using 3.16.2?

**Comment by nitrogenfive** [comment]
I am now! Thanks
