### ISSUE TITLE
YouTube AdBlock ban bypass?

### ISSUE THREAD

**Issue by ThePlayingGoblin** [dhowe/AdNauseam#2327]
Hello, could you guys please see if this can be replicated on your end?
![image](https://github.com/dhowe/AdNauseam/assets/32787189/edc41bf5-c64c-4f09-87eb-f46a38551784)

Reddit Page:

https://www.reddit.com/r/youtube/comments/13cfdbi/apparently_ad_blockers_are_not_allowed_on_youtube/

Thought i'd point this out to you guys to prepare Adnauseum when this more widely rolls out. Hopefully we'll continue blocking youtube ads.

**Comment by BamsTheSergal** [comment]
looks like chrome is outright just disabling it when the browser closes fully, like removing it from being loaded, readding it fixes it

**Comment by ThePlayingGoblin** [comment]
A little update on this:

![image](https://github.com/dhowe/AdNauseam/assets/32787189/bb76a7ab-ea68-4b11-92b4-e3a41f391f36)

https://www.reddit.com/r/youtube/comments/14kmd07/youtube_cracking_down_on_if_youre_not_paying_them/

It looks like they're doing a 3 strike policy on select users globally.

**Comment by allanlaal** [comment]
Chrome and all other Chromium based browsers are doomed anyway, since they will soon limit adblock lists to 50 000 entities by disabling Manifest V2 extension support (for our "protection", ofcourse). Google meant to drop this in 2023-01-01, but they extended it to 2024-01-01.

its better to bite the bullet now and move to Firefox - a true Free browser

**Comment by ThePlayingGoblin** [comment]
Thank goodness Firefox is my main browser. Hopefully google doesn't punish and create a monopoly over non-chromium browsers.

**Comment by allanlaal** [comment]
they prolly will, you know, for our "safety" :D

**Comment by mneunomne** [comment]
This is not AdNauseam specific, not sure if we should keep it as an issue, since we will follow uBlock Origin behaviour on this. @dhowe ?

**Comment by dhowe** [comment]
agreed

**Comment by mneunomne** [comment]
@dhowe I'll reopen this issue, seems like the fight with youtube is always on-going, but its good idea that we keep of what is going on here: https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by mneunomne** [comment]
This doesn't seem to be happening anymore, probably related to the other youtube related issues that have been fixed in the latest release. Closing for now.
