### ISSUE TITLE
Updated Install-AdNauseam-in-Chrome-on-MacOS.md Wiki Document

### ISSUE THREAD

**Issue by EasyG0ing1** [dhowe/AdNauseam#2329]
Since there is no mechanism for creating a pull request in Wiki's, I added some info to this file that is specific for MacOS Ventura. Markdown file is attached, it should be relatively easy for you to put the file in the wiki.

[Install-AdNauseam-in-Chrome-on-MacOS.zip](https://github.com/dhowe/AdNauseam/files/11502753/Install-AdNauseam-in-Chrome-on-MacOS.zip)

**Comment by mneunomne** [comment]
Updated, thank you @EasyG0ing1 !
