### ISSUE TITLE
ads showing on watchseinfeld.com

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2334]
e.g.: https://watchseinfeld.com/episode-watch/seinfeld-7x12/

<img width="498" alt="Screenshot 2023-05-19 at 07 44 02" src="https://github.com/dhowe/AdNauseam/assets/4967860/6e1ece2b-8b79-48f4-85df-894983592c22">

**Comment by dhowe** [comment]
great -- can this be closed?

**Comment by mneunomne** [comment]
Closed
