### ISSUE TITLE
Does not properly block video ads on YouTube, Twitch, &c.

### ISSUE THREAD

**Issue by Fleckeri** [dhowe/AdNauseam#234]
I may not have configured it properly, but using AdNauseum does not block video ads that disrupt YouTube, Twitch, and other similar video streaming sites like uBlock does. Is there anything I can do to fix this, or is this an upcoming feature?

**Comment by dhowe** [comment]
@Fleckeri can you include a few URLs that we can use to test?

**Comment by Fleckeri** [comment]
Here are some I noticed them on, but I'm sure it can be easily generalized:

https://www.twitch.tv/dotamajor
https://youtu.be/1ph_kKTURxE

For Twitch, there are periodic ads the streamer can activate, so you may need to leave it on for ~5 minutes to see. For YouTube, they are the typical beginning ads you normally see.

**Comment by dhowe** [comment]
thanks, looking into it

**Comment by dhowe** [comment]
Can you verify the version of AdNauseam you are using (in settings->about)?

**Comment by Fleckeri** [comment]
It says it's Version 2.2.0. Just to confirm, I've disabled my uBlock extension while running this. Should I leave it turned on while running AdN, or will AdN be enough on its own?

**Comment by dhowe** [comment]
Definitely don't need both. Can you retry with just AdNauseam? Also, a screenshot of your lists (from settings/3rd-party) would be great.

**Comment by Fleckeri** [comment]
[Settings](http://prntscr.com/bf1fd1)
[Filters](http://prntscr.com/bf1fi9)

Here's a screenshot of my settings and filters.

**Comment by dhowe** [comment]
And you have the same problem after disabling uBlock?

**Comment by dhowe** [comment]
Ok, I will investigate further

**Comment by Fleckeri** [comment]
Windows 10 (64 bit)

**Comment by dhowe** [comment]
@CyrusSUEN see if you can figure out which request is getting blocked in uBlock but not adn

**Comment by CyrusSUEN** [comment]
@Fleckeri Please try to 
![1](https://cloud.githubusercontent.com/assets/2461812/16170255/581bcb06-357f-11e6-9cc6-65fbcd71f56e.PNG)
1. add `=adunit&` to My filters tab in ADN's settings page.
2. Make sure you've checked My filters in 3rd-party filters tab in Settings page. 
3. do Update now, Purge all caches and Apply see if you it blocks video ads on YouTube.

![2](https://cloud.githubusercontent.com/assets/2461812/16170257/58e589f0-357f-11e6-95bb-bba3f1241f82.PNG)

**Comment by dhowe** [comment]
This is fixed in 7552146
@CyrusSUEN please verify

**Comment by CyrusSUEN** [comment]
> fixed in 7552146

Fix verified on YouTube.
