### ISSUE TITLE
'Block element' context menu intermittently missing

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2340]
Page: https://hongkongfp.com/
Not sure if this is browser specific

With adn (ff):
![image](https://github.com/dhowe/AdNauseam/assets/737638/f080cff9-b64a-4954-a2f9-0d6bc48f7ebc)

With ubo (chrome):
![image](https://github.com/dhowe/AdNauseam/assets/737638/f9ebe1cf-985e-45ca-85a1-a418465beaf5)

**Comment by dhowe** [comment]
for v3.19

**Comment by mneunomne** [comment]
@dhowe are there any errors on the console when this issue occurs? I can't reproduce it on my end at the moment.

**Comment by dhowe** [comment]
a re-install fixed the problem - lets close for now and see if it recurs
