### ISSUE TITLE
Manifest File is Missing or Unreadable

### ISSUE THREAD

**Issue by Calebtheaa** [dhowe/AdNauseam#2342]
When loading the folder to google, an error pops up, which is shown in the image below.
![image](https://github.com/dhowe/AdNauseam/assets/90156844/300b732a-6567-4080-b127-24cb8a74436b)
Do you know why this is happening?

**Comment by mneunomne** [comment]
@Calebtheaa which browser is this?

**Comment by Calebtheaa** [comment]
I am using google chrome,

**Comment by Calebtheaa** [comment]
After trying it again, it works again. I believe I was using an outdated version of chrome in that image.
