### ISSUE TITLE
just look at the image

### ISSUE THREAD

**Issue by heh101** [dhowe/AdNauseam#2343]
![image](https://github.com/dhowe/AdNauseam/assets/73348559/de6d68e1-621d-4f41-b1d0-2966b2f1c8b1)
### **_why does this happen_** 

> this thing doesnt load at all they may have patched it _**r.i.p**_

**Comment by dhowe** [comment]
see also: https://github.com/dhowe/AdNauseam/issues/2342

**Comment by mneunomne** [comment]
Hello @heh101, you should first unzip the file, then load the folder instead.
