### ISSUE TITLE
Ads not being collected on Amazon

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2346]
<img width="1439" alt="Screenshot 2023-07-02 at 11 55 20" src="https://github.com/dhowe/AdNauseam/assets/4967860/246bb54f-720e-475a-a703-5da34287845b">

**Comment by dhowe** [comment]
url/location to recreate? login or no ?

**Comment by mneunomne** [comment]
This was in germany, logged in

**Comment by mneunomne** [comment]
Turned out all was needed was to add the amazon domains to the `internalLinkDomainsDefault`:

```
"amazon.ae","amazon.ca","amazon.cn","amazon.co.jp","amazon.co.uk","amazon.com","amazon.com.au","amazon.com.be","amazon.com.br","amazon.com.mx","amazon.com.tr","amazon.de","amazon.eg","amazon.es","amazon.fr","amazon.in","amazon.it","amazon.nl","amazon.pl","amazon.sa","amazon.se","amazon.sg",
```

now the ads are being properly collected.

![Screenshot 2023-07-25 at 16 45 16](https://github.com/dhowe/AdNauseam/assets/4967860/cd4b9e6e-52ed-4ad7-ad19-2bd9a020ecee)
