### ISSUE TITLE
Website Detect extension

### ISSUE THREAD

**Issue by aquila0101** [dhowe/AdNauseam#2348]
### Describe the issue

I would like to report a site that detects the ad blocker.

https://www.games-manuals.com/vacuum-warrior/vacuum-warrior-save-game-location-backup-installation/68779/

Attached are the extensions used by me, site capture, my settings in .txt file

![Captura de tela 2023-07-13 223117](https://github.com/dhowe/AdNauseam/assets/84749877/9f7bf411-c884-41d5-8202-e34d448454b2)

![Captura de tela 2023-07-13 223148](https://github.com/dhowe/AdNauseam/assets/84749877/67287fbb-e829-4bbb-af72-b0d448afff70)

### Your settings

- OS/version: Windows 10
- Browser/version: Mozilla Firefox 115.0.2
- AdNauseam version: 3.17.0
- Other extensions you have installed: AVG Online Security, LanguageTool, TWP - Translate Web Pages, Return YouTube Dislike
- AdNauseam settings:

##### My exported settings
[AdNauseam_Settings_Export_13.07.2023.22.29.14.txt](https://github.com/dhowe/AdNauseam/files/12045525/AdNauseam_Settings_Export_13.07.2023.22.29.14.txt)

**Comment by dhowe** [comment]
Note that this is also the case for ublock origin:

<img width="901" alt="image" src="https://github.com/dhowe/AdNauseam/assets/737638/3c506071-935b-4d2f-a123-05a86a6c6e2a">

**Comment by aquila0101** [comment]
I just want you to know
If it happens on more sites, I'll let you know here.

**Comment by mneunomne** [comment]
These things usually just take a bit of time for the ad-filter community to pick up. Since this is not adnauseam-specific I will close it. but thank you @aquila0101 for letting us know.
