### ISSUE TITLE
Mistake in the Swedish translation since 7 years

### ISSUE THREAD

**Issue by Dyras** [dhowe/AdNauseam#2349]
### Describe the issue

The Swedish translation is wrong in one place, and has been so for the past 7 years.

The addon currently says 
"Klicka på inte annonser utan spårning"
Which roughly translates to 
"Click on don't ads without tracking"
It should say
"Klicka inte på annonser utan spårning"
Which roughly translates to
"Don't click on ads without tracking"

I noticed it a few weeks ago, but apparently I submitted a fix 4 years ago and it was never accepted.

See the picture.

### Screenshot in which the issue can be seen
![image](https://github.com/dhowe/AdNauseam/assets/12563436/0953d615-5267-44b7-9f9c-6643e7dbf099)

### Steps for anyone to reproduce the issue
1. Use the Swedish translation
2. Go into the settings
3. The place that says "Don't click non-tracking Ads" will now be wrong in Swedish

**Comment by mneunomne** [comment]
Thank you @Dyras , I just accepted your translation. there are many languages to manage and sometimes things like this go unnoticed. 

Closing now.

**Comment by Dyras** [comment]
Yeah no issue. I wouldn't look at the foreign translations either tbh.
