### ISSUE TITLE
Check 'Origin' header for outgoing visit requests

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#235]
Compare Origin header for a normal (user-initiated click) with that of an ADN-click

**Comment by dhowe** [comment]
Also need to remove: 'HTTP_X_REQUESTED_WITH' header

**Comment by dhowe** [comment]
please verify

**Comment by CyrusSUEN** [comment]
> please verify

Here is the comparison:
![302](https://cloud.githubusercontent.com/assets/2461812/16087856/1d79dada-3357-11e6-9672-d50c1990edb0.PNG)
https://www.diffchecker.com/dqrnxjqa
302 header

![200](https://cloud.githubusercontent.com/assets/2461812/16087858/22115bc2-3357-11e6-96f7-796106ff3c5a.PNG)
https://www.diffchecker.com/ojaznsue
200 header

`Referer` attribute is not the same.

I wonder if we can rearrange the order of ADN's header attributes to make it more like the original header.

x-client-data attribute information:

> This Chrome-Variations header (X-Client-Data) will not contain any personally identifiable information, and will only describe the state of the installation of Chrome itself, including active variations, as well as server-side experiments that may affect the installation.

**Comment by dhowe** [comment]
So regular browser requests don't have the 'x-client-data' header?

**Comment by CyrusSUEN** [comment]
> Standard chrome browser requests don't have the 'x-client-data' header?

I've already disabled those options sending feedback to Google in Chrome's Settings page. But the attribute was still there.

And then I tried the header test on Microsoft Edge browser, it has no `x-client-data` in the header.

**Comment by dhowe** [comment]
Please compare the full set of headers on FF and Opera as well...

**Comment by CyrusSUEN** [comment]
> compare the full set of headers on FF and Opera

Tests are done in default ADN settings.
On the left are the original headers and on the right are from ADN visits

Firefox 302 header:
![firefox_302](https://cloud.githubusercontent.com/assets/2461812/16156105/2267d1de-34e5-11e6-935f-642c655ad544.PNG)
https://www.diffchecker.com/moo9opam

Firefox 200 header:
![firefox_200](https://cloud.githubusercontent.com/assets/2461812/16156111/23e1ca9c-34e5-11e6-826a-dd83b68b29f4.PNG)
https://www.diffchecker.com/i2igxm8p

It looks all good except that ADN's `Referer` attribute has an '/' at the end.

Opera 302:
![opera_302](https://cloud.githubusercontent.com/assets/2461812/16156000/99af079a-34e4-11e6-9abb-2c36bbb4f6f8.PNG)
https://www.diffchecker.com/aptlpptw

Opera 200:
![opera_200](https://cloud.githubusercontent.com/assets/2461812/16155995/96ef3160-34e4-11e6-8fde-4b1dfaa8d505.PNG)
https://www.diffchecker.com/xykc0gaa

Opera has no problem at all.

I do not see `x-client-data` attribute in other browsers.
