### ISSUE TITLE
Can't install on firefox nightly for android "add-on not supported"

### ISSUE THREAD

**Issue by alyxbb** [dhowe/AdNauseam#2351]
### Describe the issue
when trying to install on firefox nightly for android through the add on store, the following error message appears "add-on not supported"

### Screenshot in which the issue can be seen
![Screenshot_20230717_200739_Firefox Nightly](https://github.com/dhowe/AdNauseam/assets/40714465/e4ccd811-a425-4747-900b-3d04cac0eea9)

### Steps for anyone to reproduce the issue
go to https://addons.mozilla.org/en-GB/android/addon/adnauseam/
click add to Firefox
the addons page will open and the error message will appear.
### Your settings

- OS/version: android 12
- Browser/version: firefox nightly 117.0a1
- AdNauseam version: 3.17.0
- Other extensions you have installed: shinigami eyes
- AdNauseam settings:n/a

##### Your filter list
n/a

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
n/a

**Comment by mneunomne** [comment]
It is rather silly, but seems that one can only install it on the "add-on" menu of the application, but not through the website. Following these steps it works for me:

<img width="200" src="https://github.com/dhowe/AdNauseam/assets/4967860/f58003bf-4b85-4dfc-8a74-5bc1e121a9cf"/>
<img width="200" src="https://github.com/dhowe/AdNauseam/assets/4967860/15872a0f-d4b9-4c94-a2b6-3e5cf7f9c72f"/>
<img width="200" src="https://github.com/dhowe/AdNauseam/assets/4967860/bd4550cd-d409-4cf3-830e-2968d797f5a8"/>

**Comment by dhowe** [comment]
is this something we can fix?

**Comment by mneunomne** [comment]
Testing on version __Firefox Nightly 118.0a1__ Actually I was able to install it through the link mentioned on this issue: https://addons.mozilla.org/en-GB/android/addon/adnauseam/ on Firefox nightly. Not sure what happened on this case.

The issue I mentioned about was actually by clicking on the button on the non-android extension page:
https://addons.mozilla.org/en-US/firefox/addon/adnauseam/

Not sure what happened on your case @alyxbb. Also why doesnt it show the recomended addons on your add-on page? for me it does.

**Comment by alyxbb** [comment]
turns out that having custom add ons was preventing me from adding it.

**Comment by mneunomne** [comment]
Closing
