### ISSUE TITLE
no toolbar icon

### ISSUE THREAD

**Issue by linwiz** [dhowe/AdNauseam#2352]
I have installed ad nauseam in the brave browser through unpacked unpacked extension, downloaded from the website. I have enabled developer mode in Brave. Stock Brave settings, disabled braves ad blocker. stock adnauseum settings.  the toolbar icon does not show up however it seems adnauseum appears to be working.

Brave [Version 1.52.130 Chromium: 114.0.5735.198 (Official Build) (arm64)](https://brave.com/latest/)
AdNauseam 3.17.0
MacOS Ventura 13.4.1 (c) (22F770820d)

- Other extensions you have installed:
None
- AdNauseam settings:
Default

Disabled Brave's built in ad blocker

Stock Filter Lists

Country US

**Comment by linwiz** [comment]
I'm not sure if these errors are related to the issue or not, however reloading the extension fixed the toolbar icon. The errors are still there though.

<img width="697" alt="Screenshot 2023-07-19 at 12 08 30 PM" src="https://github.com/dhowe/AdNauseam/assets/4132159/54ec6dc7-71c8-46f3-b362-6a3dcac085f5">
<img width="414" alt="Screenshot 2023-07-19 at 12 08 23 PM" src="https://github.com/dhowe/AdNauseam/assets/4132159/6a9802f4-3706-429e-a086-f2294435e472">

**Comment by mneunomne** [comment]
hello @linwiz. 

the error you submited is not related. Seems that adnauseam was installed fine, did you check if the browser icon isnt hidden on the extension options. Might be silly of me to think so, but maybe it is here:

<img width="328" alt="Screenshot 2023-07-24 at 18 41 40" src="https://github.com/dhowe/AdNauseam/assets/4967860/c3d93b9b-3475-4d7b-b003-7a516d69e6fe">

**Comment by dhowe** [comment]
strange... closing for now -- pls reopen if this recurs
