### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by SoniEx2** [dhowe/AdNauseam#2353]
It would be neat to see a variant of AdNauseam designed to maximize ad impressions. Instead of trying to hide ads in detectable ways, it should just render a black box over ads in an undetectable way. Would that be possible? Who knows. Well, maybe ppl with webext dev experience know, but anyway.

Such a "silent mode" would be intended to block ads for being an assault on the mind. It would be particularly important for video ads (preroll etc), but to be truly undetectable it should apply to all ads.

And importantly, since websites increase ads shown to meet impression targets, existing detectable adblockers cause non-adblocker users to see more ads, while "silent mode" would cause them to end up seeing less ads. Thus, "silent mode" is win-win for everyone, regardless of whether or not they use an adblocker.

It does mean you lose the performance advantages of a traditional adblocker. But honestly, sometimes that's very much worth it.

**Comment by dhowe** [comment]
Good suggestion @SoniEx2 
I implemented something similar in the past and was thinking about how the black-box overlays could be used in interesting ways to subvert ad-surveillance... for one example, 'donating' that space to sites/systems proposing alternative models...

**Comment by SoniEx2** [comment]
@dhowe that's just adware.

**Comment by dhowe** [comment]
not sure what you mean, but in any case, I'm going to move this to 'Discussions'
