### ISSUE TITLE
Handle ads on twitter/x

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2376]
<img width="591" alt="image" src="https://github.com/dhowe/AdNauseam/assets/737638/effacd36-2ec6-41b5-a314-ebea2b3a3b43">

**Comment by mneunomne** [comment]
On my end currently twitter ads are being hidden, and some also collected. Tested on both firefox and chrome.

![Screenshot 2023-09-18 at 16 18 57](https://github.com/dhowe/AdNauseam/assets/4967860/ce907bbe-b053-4114-a7c3-8bd53144f81d)

**Comment by dhowe** [comment]
I also can't recreate at moment -- closing for now, but lets keep an eye on this...
