### ISSUE TITLE
Not blocking ads in spotify web player 

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2384]
(via email)
 
<img width="822" alt="image" src="https://github.com/dhowe/AdNauseam/assets/737638/3d8498dd-7d26-4b89-add9-e4e211bbb249">

**Comment by mneunomne** [comment]
Tested, seems that v3.18 fixed this along with the youtube ads. Can be closed.

**Comment by mneunomne** [comment]
actually i detected an ad after sometime listening... it succesfully skips the ad in strict mode, so I guess its a good idea to ad spotify in default strict.
