### ISSUE TITLE
Update button not working as expected for adnauseam.txt

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2387]
Expected: clicking 'update' causes an update
Actual: nothing appears to happen -- instead you need to click the clock icon, then click 'update now' at top

**Comment by Jencansee** [comment]
[Firefox 117] I have the same issue, clicking update button on AdNauseam filters do nothing.

![image](https://github.com/dhowe/AdNauseam/assets/55334086/e4490f94-a595-433e-b828-33325ecd385f)

**Comment by mneunomne** [comment]
Fixed, closing
