### ISSUE TITLE
Implement generic Notifications to include in the menu/vault/settings

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#239]
**Notifications (info, success, warning, error/danger)**

- EasyList Disabled (warning): vault, menu, settings
- Clicking Disabled (warning): vault, menu, settings
- Malware Blocking (by-list) Disabled (danger): vault, menu, settings
- Hiding Disabled (warning): vault, menu, settings
- DNT off in browser settings with respect-DNT on (warning: respect-DNT will be disabled)

**Comment by mushon** [comment]
Should we continue from the design offered in #145?

**Comment by mushon** [comment]
Continuing from the design offered in #145 define a system for different types of alerts.
Use this as reference:
![image](https://cloud.githubusercontent.com/assets/27123/17408106/944a15f2-5a72-11e6-9237-fa88e785976c.png) from [here](http://getbootstrap.com/css/#buttons-options)

**Comment by mushon** [comment]
New design:

![uploads/ec8008fe-bcfd-4fac-988b-9e472c97ade9/popup-alerts.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fec8008fe-bcfd-4fac-988b-9e472c97ade9%2Fpopup-alerts.png)

**Comment by mushon** [comment]
This design is now implemented in markup both for the settings and the menu (css set in common.css which I imported into the menu - which might require more refactoring)
check https://github.com/dhowe/AdNauseam/commit/f6007d339b34b283c8fffbbb4b5713f2d25ab022
use:
```
.notification.info
.notification.success
.notification.warning
.notification.error
```
reassigning to @dhowe

**Comment by dhowe** [comment]
done, though needs design/css fixes
