### ISSUE TITLE
Vault slider does not show accurate representation of # of ads

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#241]
and never has -- has a maximum of ~15 bars, even when there are hundreds of ads

![screen shot 2016-06-12 at 6 06 51 pm](https://cloud.githubusercontent.com/assets/737638/15990560/95f51c5e-30c8-11e6-99e1-bf124e772163.png)

**Comment by mushon** [comment]
the actual lines aren't supposed to be countable, they just represent a stack. What is an issue, is that there's an ongoing unattended error in the bars height being clipped rather than having their height scaled. I think we should fix it for 3.0.

**Comment by dhowe** [comment]
agreed

**Comment by mushon** [comment]
@dhowe if we want to release 3.0 soon (because of the store take down), this will unfortunately have to be postponed.

**Comment by dhowe** [comment]
some time soon? this has been sitting around for some time...

**Comment by dhowe** [comment]
some time soon? this has been sitting around for some time...

**Comment by mushon** [comment]
this is a D3 coding issue, not a design issue. I mean we can decide that the stack isn't doing it for us since it implies individual items (I don't think it does but I could be wrong). But the main issue here is the fact we don't scale the bars correctly and they get trimmed by the slider's height. No?

**Comment by dhowe** [comment]
Can you describe how it is supposed to work?

**Comment by mushon** [comment]
the most active day should set the scale to the others, right now the scale is hardcoded and when more active days go beyond the height of the timeline they simply get cropped. We need to use d3.scale to align the bar height with the data extents. 
https://www.dashingd3js.com/d3js-scales

**Comment by dhowe** [comment]
@mushon can you take this on for v3.5, this has been lingering for far too long

**Comment by mushon** [comment]
Yes. It's been bugging me too. 
I'll try playing with it and howl if I need help.

**Comment by dhowe** [comment]
this looks much better! 
what is supposed to happen when it hits the top:

![image](https://user-images.githubusercontent.com/737638/30909122-9af03690-a3b2-11e7-9106-c09e37cd251f.png)

**Comment by mushon** [comment]
It will never go over the top as the bar you marked is the maximum value. So the graph is always scaled from 0 to the largest bin.

**Comment by dhowe** [comment]
I wonder if the maximum bin should be a pixel or two less than the maximum height (of the slider) ?
