### ISSUE TITLE
AdNauseam clicking every video on Youtube

### ISSUE THREAD

**Issue by fzzyhmstrs** [dhowe/AdNauseam#2411]
### Describe the issue

Opened Youtube today, and just about every clickable element is a grey box, and the Ad Nauseum dropdown shows that it clicked "401" ads, which seems very incorrect. It's showing that it clicke on every video tile on the main page. *Except the "Try Youtube TV" section, those tiles seem unaffected.*

### Screenshot in which the issue can be seen
![image](https://github.com/dhowe/AdNauseam/assets/72876796/f2cb901f-75b8-4d90-93d4-e4e243a76c0b)

### Steps for anyone to reproduce the issue
I just opened Firefox today, after checking I see that 3.18.0 is installed now, and the issue happens.

### Your settings

- OS/version: Windows 11
- Browser/version: Firefox 118.0.1 64 bit
- AdNauseam version: 3.18.0
- Other extensions you have installed: Ecosia, OpenTabs
- AdNauseam settings: Virtually default. A couple whitelisted sites, "Don't click on non-tracking ads" selected

##### Your filter lists
Not sure. I haven't really messed with the settings at all, besides "Don't click on non-tracking ads". Here is the "support" log thing from the settings:

```
AdNauseam: 3.18.0
Firefox: 118
filterset (summary):
 network: 42047
 cosmetic: 0
 scriptlet: 0
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  eff-dnt-whitelist: null
  ublock-filters: null
  ublock-badware: null
  ublock-privacy: null
  ublock-abuse: null
  ublock-unbreak: null
  easyprivacy: null
  urlhaus-1: null
  ublock-quick-fixes: null
 default:
  adnauseam-filters: 506-358, never
  easylist: 71055-29156, never
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings:
 admap: [redacted]
 firstInstall: false
 hidingAds: true
 clickingAds: true
 blockingMalware: true
 disableClickingForDNT: true
 parseAllABPHideFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1450 ms
 maxAssetCacheWait: 320 ms
```

### Your location/country
USA East Coast

**Comment by fzzyhmstrs** [comment]
The suggested next videos after a video finishes are completely blank as well. I've restarted Firefox at least twice while trying to diagnose this, by the way.
![image](https://github.com/dhowe/AdNauseam/assets/72876796/99fe62af-7737-4e05-85b3-ebb5971e03af)

**Comment by SkylerFur** [comment]
Firefox 118 on Linux hadn't shown this behaviour.

**Comment by dhowe** [comment]
@mneunomne status of this?

**Comment by mneunomne** [comment]
I wasn't able to reproduce and according to @SkylerFur, it has disappeared, I'll close for now.
