### ISSUE TITLE
window.open is now broken

### ISSUE THREAD

**Issue by wodim** [dhowe/AdNauseam#2418]
As discussed in #2405 you have added the following line to the adnauseam filter

`*##+js(set, window.open, undefined)`

This disables window.open in all websites, which means websites can no longer open new tabs using javascript.

**Comment by mneunomne** [comment]
True, @wodim , disabled this filter already. Thank you

**Comment by gbesacier** [comment]
You can disable the other one from the same commit too

`*##+js(window-close-if, /plan/select?popup=noads)`

Injecting javascript blindly in all webpages (*) to minimize a little annoyance on a specific website is insane. (It doesn't even fix the annoyance completely: the pop-up does still open and is immediately closed.)

**Comment by Pantyhose-X** [comment]
*##+js(set, window.open, undefined)

He can still open "new tab".
It only blocks all "new windows."

**Comment by Pantyhose-X** [comment]
*##+js(set, window.open, undefined)

He can still open "new tab".
It only blocks all "new windows." 

test open "new tab". https://www.w3schools.com/jsref/met_win_open.asp
