### ISSUE TITLE
AdNauseam updating filters slower than uBlock?

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2420]
This is just an impression I have at the moment, based on the user's feedback. Need to make proper tests.

One possibility is the fact uBlock users the `assets/assets.json` on their master remote, and we use it on ours, which is always outdates to the last merge. Not sure what is the correct approach since we had problems in the past when we got stuck too far behind, and the assets on uBlock master started to be too far ahead of our code.

**Comment by dhowe** [comment]
labelled as high-priority in relation to youtube-video issues

**Comment by dhowe** [comment]
see also https://github.com/dhowe/AdNauseam/discussions/2425

**Comment by mneunomne** [comment]
@dhowe maybe we should add a warning on youtube for the users to keep their list updated to prevent ads?

**Comment by mneunomne** [comment]
Regarding the `assets.json`, I'm thinkling if there is a way for us to always use the uBlock assets.json instead of ours, and just inject adnauseam asset object in the list. Currently because we have to reference our own, we tend to get outdated if the assets get changed.

```js
{
"adnauseam-filters": {
		"content": "filters",
		"group": "default",
		"title": "AdNauseam filters",
		"tags": "ads",
		"contentURL": [
			"https://raw.githubusercontent.com/dhowe/AdNauseam/master/filters/adnauseam.txt",
			"assets/ublock/adnauseam.txt"
		],
		"cdnURLs": [
			"https://cdn.jsdelivr.net/gh/dhowe/AdNauseam@master/filters/adnauseam.txt",
			"https://cdn.statically.io/gh/dhowe/AdNauseam/master/filters/adnauseam.txt"
		],
		"supportURL": "https://github.com/dhowe/adnauseam/issues"
	},
}
```

**Comment by dhowe** [comment]
when would this update/inject happen ?

**Comment by mneunomne** [comment]
What I am implenting is that the reference of the assets.json to be from adnauseam@master. Which means that if we want to keep up-to-date with uBlock assets filter list, then we need to make sure is that the merge from uBlock Origin are made more frequently, also with their beta-releases, so that our master branch is as close-as-possible from theirs. 

If we inject the adnauseam filter to the ublock@master then we wouldnt have this need, but we would need to understand well how the asset management system how it currently works. For now the solution of having it referencing to adnauseam@master makes more sense. We can have the injection solution as a possible future improvement.

**Comment by mneunomne** [comment]
I have tested now, and it seems that AdNauseam filter are updating quite fast. I am not sure which of our changes have improved this - either (https://github.com/dhowe/AdNauseam/issues/2420 or https://github.com/dhowe/AdNauseam/pull/2473).

**Comment by mneunomne** [comment]
Fixed, closing.
