### ISSUE TITLE
Stack Trace

### ISSUE THREAD

**Issue by simpaul13** [dhowe/AdNauseam#2437]
### I tried to reproduce the issue when...

- [X] AdNauseam is the only extension.
- [X] AdNauseam uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Uncaught TypeError: Cannot read properties of null (reading '1')

### URL(s) where the issue occurs.

https://www.youtube.com/

### Screenshot(s)

![image](https://github.com/dhowe/AdNauseam/assets/35400010/eceff7f8-789f-4b46-9ac7-b84f0fd816bf)

### Steps to Reproduce

1. Just by going on youtube

### Configuration

     src = div.style.cssText.match(/url\((.*?)\)/)[1];
     var parsed = src.replace(/\\/g,"");

**Comment by mneunomne** [comment]
Fixed, closing
