### ISSUE TITLE
Spanish website which list items for sale. https://www.milanuncios.com

### ISSUE THREAD

**Issue by Baantjer** [dhowe/AdNauseam#2452]
If AdNauseam is set to active it bocks all content. Fist image below shows this. Second image illustates the website with AdNauseam disabled.

*NOTE: if you are having a problem where ads are not collected, please FIRST TRY to create a new new Firefox profile as described [here](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_creating-a-profile). A corrupt Firefox profile is the most common cause of this issue.*

### Screenshots
![screenshot1](https://github.com/dhowe/AdNauseam/assets/114300941/b6d9ee04-198e-48ed-9c89-1d86a280ece3)

![screenshot2](https://github.com/dhowe/AdNauseam/assets/114300941/ddb542e0-9f34-4737-aedd-f4e4a7eb4f05)

### Steps for anyone to reproduce the issue
I had to disable 

### Your settings

- OS/version: Windows
- Browser/version: FF 115.3.1
- AdNauseam version: 3.18.0
- Other extensions you have installed: Easy Screenshot. Bypass Paywalls Clean. Return YouTube Dislike
- AdNauseam settings: Nothing other than normal. For this website now disabled.

##### Your filter lists
Websites https://www.bbc.com- https://www.expat.com-https://www.independent.co.uk because a few adverts crept in.

### Your location/country Spain
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

**Comment by mneunomne** [comment]
Fixed, there was a generic cosmetic filter breaking the page. https://github.com/dhowe/AdNauseam/pull/2460

**Comment by mneunomne** [comment]
Thank you for submitting the ticket, closing now.
