### ISSUE TITLE
Disable button on Menu not working on certain urls 

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2454]
Based on what was shared in this discussion thread, there is a bug on the 'disabled' button which I have now just confirmed. It not happening on all pages, investigating why.

where bug is present:
```
nytimes.com 
```

where is not
```
g1.globo.com
```

**Comment by mneunomne** [comment]
I understood the issue now.

It seems that now "disable on current page" option should be possible when you are at the home of the domain, for example:
```
https://nytimes.com/
```

It should only be possible when we are at some _specific page_ :
```
https://www.nytimes.com/2023/11/08/world/middleeast/hamas-israel-gaza-war.html
```

THis was causing a bug where one couldn't disable that domain anymore because of an errouneus entry to the 'trusted sites' tab. 

I will disable the "on this page" option when the user is at the home of the domain.

**Comment by dhowe** [comment]
This may be difficult to detect in some cases, but still better than not having it

**Comment by mneunomne** [comment]
How ublock implements it, is that if you are on 'home' page of a domain, you don't have the option to disable only on page, and only allows for 'domain' disable instead. I thought this behaviour would be sensible?

**Comment by mneunomne** [comment]
This is now fixed, closing.
