### ISSUE TITLE
detects ad block randomly

### ISSUE THREAD

**Issue by hieusStorm** [dhowe/AdNauseam#2463]
### Describe the issue
Youtube will randomly realize that adblock is running while using Adnauseam and shutdown the video from being ran

### Steps for anyone to reproduce the issue
Just load the page with adnauseam running and it should be detected

### Your settings

- OS/version: Windows 10
- Browser/version: latest Firefox
- AdNauseam version: current?
- Other extensions you have installed: malware bytes w/ adblock disabled, Grammarly
- AdNauseam settings: default

##### Your filter lists

default filter list

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

**Comment by dhowe** [comment]
closing in favor of #2422
