### ISSUE TITLE
Outdated external URL in FAQ content

### ISSUE THREAD

**Issue by reinhart1010** [dhowe/AdNauseam#2466]
From [FAQ](https://github.com/dhowe/AdNauseam/wiki/FAQ#how-does-adnauseams-clicking-differ-from-click-fraud) section,

> ## How does AdNauseam's clicking differ from 'click-fraud'?
> We understand what click-fraud is and do not believe we are engaging in it (nor do the lawyers we have consulted). Turning the tables, we would like to hear why someone holds that AdNauseam does commit click fraud. Would they say the same of anyone who clicks on an Ad in which they are not really interested?
> 
> "Click Fraud is the practice of falsely clicking on advertiser’s sponsored links to gain credit for the publisher while charging fraudulent, invalid clicks to the advertiser." (from http://clickfraud.org/)

The referenced website now no longer exists and this is what I currently got instead:

![image](https://github.com/dhowe/AdNauseam/assets/17312341/5860c048-6442-4521-ab01-dc8b5837f699)

It may be possible to link to an archived version of the URL, like https://web.archive.org/web/20170326151643/http://clickfraud.org:80/ (The last known capture from Internet Archive before the website was taken down). Or reference from a new, currently-accessible source.

Note that I cannot suggest any PRs here as the content is documented using GitHub's Wiki feature.

**Comment by dhowe** [comment]
thanks @reinhart1010 
should be fixed now
