### ISSUE TITLE
Youtube detects AdNauseam and blocks playback

### ISSUE THREAD

**Issue by Derahex** [dhowe/AdNauseam#2475]
**Issue:**
AdNauseam is being detected by YouTube, causing videos not to play

![image](https://github.com/dhowe/AdNauseam/assets/58238159/fb1c6dde-59bd-4b5b-bb3b-84738677bb71)

**Steps to recreate issue:**
I'm on Firefox and view a video on youtube.

**System settings:**
- Windows 10
- Firefox 120.0
- AdNauseam 3.18.0
- Tested with no other extensions active
- AdNauseam settings: factory default

**Filter Lists:**
Default

**Location:**
Canada

Thank you

**Comment by mneunomne** [comment]
We have just released new version, waiting to be aproved in firefox store, it should fix this issue.

**Comment by dhowe** [comment]
closing in favor of https://github.com/dhowe/AdNauseam/issues/2422
