### ISSUE TITLE
adnauseum addon icon changes position

### ISSUE THREAD

**Issue by astro46** [dhowe/AdNauseam#2482]
### Discussed in https://github.com/dhowe/AdNauseam/discussions/2481

<div type='discussions-op-text'>

<sup>Originally posted by **astro46** December  4, 2023</sup>
I am using vivaldi, a chromium based browser.  The problem that I have been having for some time is that adnauseum is the only icon, in the taskbar list of addons, that won't stay where I place it. I open vivialdi and find that has shifted itself over to the left, no. 1 position.   I move it over to the right, and some time later, there it is again , on the left.  I know it is an important addon, but I would still like it to stay put.  It doesn't need to be no. 1.

What is going on?</div>

**Comment by astro46** [comment]
I am getting the idea that this is being treated as bug report. I didn't knowingly post it as a bug, but as discussion (though maybe it is a bug?. Other addons aren't behaving this way).  Perhaps there is a setting that i missed, or something else to change that would affect it.

**Comment by dhowe** [comment]
This _would_ be a bug if we can track what is happening back to AdNauseam. To be clear, we don't have any code that messes with the ordering of menu items. My only guess is that Vivaldi treats _unpacked_ extensions differently than those from the chrome store, and that this has some effect on the icon ordering. 

Would be good if you could provide some step-by-step instructions for a dev to recreate the problem from a fresh vivaldi install...

**Comment by astro46** [comment]
let me see if i can come  up with useful info.   will respond.

**Comment by astro46** [comment]
I sync vivaldi once a week between desktop and laptop, .  There are certain profile files/folders that are sync'd (considered essential to vivaldi user profile) in order to make the destination a functional copy. It is after this sync process, in either direction , that adnauseum changes its position in list of addons on the destination. i can correct the order and it stays there, as I find currently, until the next sync, when it changes position on the destination version of vivaldi.  

I don't identify any of the files/folders as being obviously related to add-ons. adnauseum is the only addon, of the eight addons, whose icon shifts positions. 

I have also determined that if I hide (so not visible on taskbar) the adnauseum icon on laptop and conduct sync to desktop it appears there, out of order. If I then hide it on desktop, I can sync in either direction and not see it on taskbar.  this tells me that the file/folder that holds "hide" info is not syncing. 

If there is any other info that may help, please ask.

**Comment by mneunomne** [comment]
@astro46 the only reason why I could imagine this is happening is because AdNauseal might be the only extension you are manually installing? But I imagine not. As @dhowe already said, we have no control on the order of where the icon of our extension appear, that's entirely the decision of the browser itself. I have found some people complaining about icon ordering in vivaldi online, so my guess is that there is some sort of vivaldi malfunction which in your case is affecting AdNauseam for some reason.

**Comment by mneunomne** [comment]
Since there is no way for is to confirm this, and doesn't sound like we could do something about it, I will close it for now.
