### ISSUE TITLE
Youtube blocks adnauseam

### ISSUE THREAD

**Issue by DavidHaenniIT** [dhowe/AdNauseam#2483]
### Ad block blocker of youtube still detects adnauseam

i don't think a screenshot is neccesary 

### My settings

- OS/version: windows 11
- Browser/version: edge don't know wich version
- AdNauseam version: 3.18.0
- Other extensions you have installed: dark mode and youtube video downloader
- AdNauseam settings: anything but the default behaviors

##### Your filter lists
filter list doesn't work with the youtube ads

### Your location/country
I live in Switzerland

Thanks for looking into my support ticket

**Comment by dhowe** [comment]
Please see https://github.com/dhowe/AdNauseam/issues/2422

(closing as duplicate)
