### ISSUE TITLE
AdNauseum detected on blue media download link generator

### ISSUE THREAD

**Issue by ConcernedCoder** [dhowe/AdNauseam#2486]
https://bluemedialink.online/url-generator-1.php?url=XWWUCOrsJWk+kpqcqmf3WWFH7HVAsadPUPyVhtc0mj123WaRQQ0vJlM9mphi2RYNrMLD5pyy4CxSUAXSWDZthOn8GKylJ5DBUWOZJlJDH2U=
Detects AdNauseum

AdNauseam: 3.18.0
Chromium: 121
filterset (summary):
 network: 104106
 cosmetic: 129836
 scriptlet: 24700
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28225-30, 1m
  adguard-mobile-app-banners: 4848-9, 1m
  adguard-other-annoyances: 13966-8, 1m
  adguard-popup-overlays: 26629-74, 1m
  adguard-social: 22101-924, 1m
  adguard-widgets: 2374-3, 1m
  fanboy-thirdparty_social: 69-3, 1m
  ublock-cookies-adguard: 806-5, 1m
 default:
  user-filters: 1-0, never
  adnauseam-filters: 512-2, 1m
  easylist: 75886-92, 1m
  easyprivacy: 33117-134, 1m
  eff-dnt-whitelist: 685-0, 1m
  ublock-badware: 7633-138, 1m
  ublock-filters: 36434-685, 1m
  ublock-privacy: 948-12, 1m
  ublock-quick-fixes: 116-5, 1h.3m
  ublock-unbreak: 2175-33, 1m
  urlhaus-1: 4352-0, 1m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
untrustedset:
 added: [array of 1 redacted]
userSettings:
 admap: [redacted]
 firstInstall: false
 hidingAds: true
 clickingAds: true
 blockingMalware: true
 disableHidingForDNT: true
 disableClickingForDNT: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 382 ms (selfie)
 maxAssetCacheWait: 241 ms
popupPanel:
 blocked: 0
 enabled: false

**Comment by mneunomne** [comment]
This is an interesting one, I can't figure out why the scriptlet is not working on adnauseam, all the behaviour seems the same as ublock but the function can't seem to be stoped.

**Comment by mneunomne** [comment]
It seems that is only fixed when pulling the latest version of uBlock, so I assume it is related to the most updated assets list. I can push the latest changes to marge and start making the beta for the next release, so that the current version can use the master/assets.json, as well as prepare for the upcoming new version of uBlock Origin.

**Comment by mneunomne** [comment]
The following rules fix this issue as well:

```py
bluemedialink.online#@##ads-left
bluemedialink.online#@##ads-right
bluemedialink.online#@##ads-center
bluemedialink.online###ads-left iframe
bluemedialink.online###ads-right iframe
```

**Comment by mneunomne** [comment]
Fixed, closing
