### ISSUE TITLE
locale: should show "no ads collected on this page" instead of "no ads on this page"

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam#249]
When unchecked "Hide ads identified by your chosen filter lists" and "Capture text-only ads when possible" in Settings, it seems weird that it showed no ads on this page when there were actually ads on the page:
![screen shot 2016-06-14 at 9 39 47 pm](https://cloud.githubusercontent.com/assets/2461812/16046796/3cb46f50-3280-11e6-82b8-c68b81c53fb9.png)

**Comment by dhowe** [comment]
Correct. Please implement

**Comment by CyrusSUEN** [comment]
Updated: https://crowdin.com/project/adnauseam
Fixed: https://github.com/dhowe/AdNauseam/pull/255
