### ISSUE TITLE
Default settings causes blank Pinterest home feed

### ISSUE THREAD

**Issue by thankfulmachine** [dhowe/AdNauseam#2491]
### I tried to reproduce the issue when...

- [X] AdNauseam is the only extension
- [X] AdNauseam uses default lists and settings
- [X] Using a new, unmodified browser profile

### Description

When visiting pinterest.com with default settings in Firefox 121.0 (64-bit) on Windows 11 Pro 22H2 22621.2861

### URL(s) where the issue occurs.

https://pinterest.com

### Steps to Reproduce

Visit pinterest.com (logged in) with default settings.

Note: Turning off ad hiding allows the home feed to load.
Note: Other areas of the site, such as editing your profile, are also blank unless you turn off ad hiding.

### Configuration

- Firefox 121.0 (64-bit)
- Windows 11 Pro 22H2 22621.2861

**Comment by mneunomne** [comment]
Fixed, closing
