### ISSUE TITLE
Video ads playing on DailyMotion

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2499]
Video ads playing (no image, only sound) on DailyMotion on Chrome. Doesn't happen with uBlock.

Note: on Firefox I see the 2nd image below instead

### This is an AdNauseam-specific issue.

- [X] I have tested the same page on *uBlock Origin*, and the Ad is not visible.

### I have tried to reproduce the issue when...

- [X] AdNauseam is the only extension
- [X] AdNauseam uses default lists and setting.
- [X] Using a new, unmodified browser profile
- [X] All filter lists are updated

### URL(s) where the issue occurs.

https://www.dailymotion.com/video/x6j5k2h

### Your location/country.

US

### Screenshot(s)

<img width="1145" alt="Screenshot 2024-01-09 at 6 11 33 PM" src="https://github.com/dhowe/AdNauseam/assets/737638/95c58c55-9bd9-4270-ac23-2ea904dcfc94">

<img width="997" alt="Screenshot 2024-01-09 at 6 12 16 PM" src="https://github.com/dhowe/AdNauseam/assets/737638/02170b43-0afb-4040-afae-a1e4e9a6b3e4">

**Comment by mneunomne** [comment]
After a lot of testing I was able to isolate the issue, and the uBlock rule that seems the be fixing the ad detection is:

```
@@||dailymotion.com^$ghide
```

Which for some reason doesn't seem to be working in AdNauseam, which is a really critical bug. I'm looking now into the staticNetFilteringEngine system to see the difference with between Adn and uBlock.

**Comment by mneunomne** [comment]
as reference:

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#generichide
generichide

> When used in an exception filter, it will turn off generic cosmetic filtering on matching pages. Generic cosmetic filters are hiding filters that apply to all pages - ##.ad-class.

**Comment by mneunomne** [comment]
Enabled setting `noGenericCosmeticFiltering` which makes `generichide` exception possible. I didn't understand before why this was needed, but now I do... Tested and dailymotion not detecting AdNauseam any longer.

**Comment by mneunomne** [comment]
Closed the merge for now. It seems that enabling `generichide` in adnauseam, also causes more ads to appear on websites. Such as in `https://bluemedialink.online/` submited on https://github.com/dhowe/AdNauseam/issues/2486.

... 


__So the matter is:__

- if `generichide` is disabled in adnauseam, adnauseam can get detected on some websites.
- if its enabled with following rule e.g.: `@@||dailymotion.com^$ghide`, adnauseam doesn't get detected ads are more likely to appear on those websites, making it necessary for strict-mode to be enabled most likely.

__Possible solutions__

a. auto-enable strict-mode on pages with generichide exception
b. let the ads appear and the user set the strict mode themselves
c. check all websites with `generichide` domain exception rules and deal with the ads appearing individually each one (seems not practical, 1000+ entries)
d. keep `generichide` disabled and create individual exceptions to avoid AdNauseam to get detected

**Comment by mneunomne** [comment]
Seems that option D might be the best solution. The following exception of a generic rule on dailymotion.com also solves the detection:

```
dailymotion.com#@#.ad_box
```

**Comment by mneunomne** [comment]
Submited PR again with the filter exception instead:

https://github.com/dhowe/AdNauseam/pull/2500

**Comment by mneunomne** [comment]
Fixed, closing
