### ISSUE TITLE
Should refresh Vault page every time when open Vault button is clicked

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam#251]
Currently if Vault page has already been open, clicking the open Vault button will only switch to the Vault tab page which is only showing the previous state. Users have to manually refresh the page again to see the changes.

Or this could be a temporary measure. Ideally the Vault page should automatically load / add newly collected ads without refreshing itself.

**Comment by dhowe** [comment]
"Ideally the Vault page should automatically load / add newly collected ads without refreshing itself."
Correct.
