### ISSUE TITLE
Ads visible on reinteractive.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2511]
This specific ad links to surveymonkey.com: https://www.surveymonkey.com/r/67XR5QL

### This is an AdNauseam-specific issue.

- [ ] I have tested the same page on *uBlock Origin*, and the Ad is not visible.
Also visible with ublock origin

### I have tried to reproduce the issue when...

- [X] AdNauseam is the only extension
- [X] AdNauseam uses default lists and setting.
- [X] Using a new, unmodified browser profile
- [X] All filter lists are updated

### Does Strict-Block mode solves the issue?

- [X] I have tested the same page with Strict-Block enabled, and the Ad is still visible.

### URL(s) where the issue occurs.

https://reinteractive.com/articles/running-open-source-AI-models-locally-with-ruby

### Your location/country.

HK

### Screenshot(s)

![image](https://github.com/dhowe/AdNauseam/assets/737638/e22dbca2-678a-4862-b717-c2751b9ad03e)

### Configuration

OSX/FF

**Comment by mneunomne** [comment]
Fixed, closing
