### ISSUE TITLE
Some Vietnamese newspaper pages display advertisements

### ISSUE THREAD

**Issue by bigdargon** [dhowe/AdNauseam#2512]
### This is an AdNauseam-specific issue.

- [X] I have tested the same page on *uBlock Origin*, and the Ad is not visible.

### I have tried to reproduce the issue when...

- [X] AdNauseam is the only extension
- [X] AdNauseam uses default lists and setting.
- [X] Using a new, unmodified browser profile
- [X] All filter lists are updated

### Does Strict-Block mode solves the issue?

- [X] I have tested the same page with Strict-Block enabled, and the Ad is still visible.

### URL(s) where the issue occurs.

```https://kienthuc.net.vn/```

```https://tuoitre.vn/quy-dao-trai-dat-bi-thay-doi-mot-cach-bi-an-20240220073743299.htm```

```https://tuoitre.vn/```

```https://laodong.vn/photo/xe-cho-du-khach-nguoi-dan-du-xuan-xep-hang-dai-len-chua-linh-ung-da-nang-1303459.ldo```

### Your location/country.

Vietnam

### Screenshot(s)

![Screenshot 2024-02-20 085926](https://github.com/dhowe/AdNauseam/assets/10969626/d5c253cd-997a-4f31-b0e3-c667f4346625)

![Screenshot 2024-02-20 085735](https://github.com/dhowe/AdNauseam/assets/10969626/7ace8281-cf21-44a3-b89a-3682e57c8a0e)

![Screenshot 2024-02-20 085719](https://github.com/dhowe/AdNauseam/assets/10969626/b5f6b670-c95b-496a-8f48-8ec98c5cf932)

![Screenshot 2024-02-20 085634](https://github.com/dhowe/AdNauseam/assets/10969626/a3c494b9-89b3-4fa5-83b3-82d2f32943b7)

![Screenshot 2024-02-20 085347](https://github.com/dhowe/AdNauseam/assets/10969626/e4944df6-650f-4b3e-88e4-1c86151a6a2e)

![Screenshot 2024-02-20 085330](https://github.com/dhowe/AdNauseam/assets/10969626/bff33dcd-87f5-4760-aaf5-9b8795c715c6)

### Configuration

AdNauseam: 3.20.0
Chromium: 121
filterset (summary):
 network: 140030
 cosmetic: 159397
 scriptlet: 42369
 html: 0
listset (total-discarded, last-updated):
 added:
  VIE-1: 1819-0, 32m
  adguard-generic: 80439-509, 2d.11h.52m
  easylist-annoyances: 4372-56, 19h.42m
  easylist-chat: 181-0, 6d.10h.59m
  easylist-newsletters: 6995-22, 19h.42m
  easylist-notifications: 2941-90, 19h.42m
  fanboy-cookiemonster: 66143-16146, 19h.41m
  fanboy-social: 16182-32, 19h.41m
  fanboy-thirdparty_social: 68-15, 6d.10h.59m
  ublock-cookies-easylist: 944-3, 19h.42m
 default:
  user-filters: 0-0, never
  adnauseam-filters: 531-8, 19h.43m
  easylist: 81274-1388, 32m Δ
  easyprivacy: 50240-186, 32m Δ
  eff-dnt-whitelist: 657-0, 2d.11h.52m
  ublock-badware: 7886-248, 2d.11h.52m
  ublock-filters: 37275-3618, 32m Δ
  ublock-privacy: 744-7, 32m Δ
  ublock-quick-fixes: 116-4, 32m
  ublock-unbreak: 2210-102, 32m Δ
  urlhaus-1: 3460-0, 32m
filterset (user): [empty]
userSettings:
 admap: [redacted]
 firstInstall: false
 hidingAds: true
 clickingAds: true
 blockingMalware: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2149 ms (selfie)
 maxAssetCacheWait: 1299 ms
 cacheBackend: browser.storage.local

**Comment by mneunomne** [comment]
Thanks for sharing @bigdargon Just merged some filters to hide the ads you mentioned. I currently can't set my location to Vietnam, so maybe I have missed some ads being displayed, so  if something still appears don't hesitate to share here.
