### ISSUE TITLE
EFF DNT list unable to be activated/de-activated in 'trusted sites' panel

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2526]
### I tried to reproduce the issue when...

- [X] AdNauseam is the only extension
- [X] AdNauseam uses default lists and settings
- [X] Using a new, unmodified browser profile

### Description

EFF DNT list unable to be activated

### Screenshot(s)

<img width="650" alt="image" src="https://github.com/dhowe/AdNauseam/assets/737638/e3a5b4b7-34ea-47ce-8404-811890dc0c9a">

**Comment by dhowe** [comment]
I think the issue here is that when on the 'trusted sites' page, users don't know that the check-button is controlled _only_ from the main settings page. So we just need some way to make this clear, could even just be a mouse-over

**Comment by mneunomne** [comment]
Added a tooltip to the checkbox: "EFF DNT Policy is automatically set if Non-tracking Ads are both NOT hidden and NOT clicked."
