### ISSUE TITLE
Context-menu disappears

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2528]
### Description

Context-menu disappears after failing to block element

### Screenshot(s)

<img width="707" alt="image" src="https://github.com/dhowe/AdNauseam/assets/737638/d3d2a611-8312-4c70-acd1-ead5411660c8">

### Configuration

AdNauseam: 3.21.0
Firefox: 124
filterset (summary):
 network: 126254
 cosmetic: 129865
 scriptlet: 30713
 html: 1986
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29114-60, 1d.8h.1m
  ublock-cookies-adguard: 1062-0, 3d.17h.11m
  adguard-other-annoyances: 14105-385, 3d.8h.35m
  easylist-annoyances: 4453-21, 4d.11h.12m
  fanboy-cookiemonster: 50769-3883, 1d.3h.1m
  ublock-cookies-easylist: 1062-1055, 3d.17h.10m
  ublock-annoyances: 6884-1090, 1h.26m Δ
 default:
  user-filters: 20-3, never
  adnauseam-filters: 538-2, 3d.17h.11m
  eff-dnt-whitelist: 616-0, 1d.23h.16m
  ublock-filters: 37467-110, 1h.26m Δ
  ublock-badware: 8053-15, 3d.45m
  ublock-privacy: 777-0, 1h.26m Δ
  ublock-unbreak: 2297-0, 1h.26m Δ
  ublock-quick-fixes: 214-0, 7h.27m
  easylist: 84408-454, 1h.26m Δ
  easyprivacy: 50427-84, 1h.26m Δ
  urlhaus-1: 3798-1, 6h.27m
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 12 redacted]
userSettings:
 admap: [redacted]
 firstInstall: false
 hidingAds: true
 clickingAds: true
 blockingMalware: true
 disableHidingForDNT: true
 clickProbability: 0.65
hiddenSettings: [none]
supportStats:
 allReadyAfter: 79098 ms (selfie)
 maxAssetCacheWait: 8819 ms
 cacheBackend: indexedDB

**Comment by mneunomne** [comment]
@dhowe what do you mean by "failing to block element" ?

**Comment by dhowe** [comment]
I believe that I right-clicked 'block element', the element was not blocked, and the option disappeared from the context menu

**Comment by mneunomne** [comment]
any errors in the logger?

**Comment by dhowe** [comment]
not sure - when I try to recreate the issue the block works, however the context-menu changes from reading 'adnauseam' to reading 'block element' -- what is the correct label ?

**Comment by mneunomne** [comment]
This depends if you are clicking inside an iframe or not. When clicking in iframe, there is option to "block element in frame" or "block element". Is that your case?

![Screenshot 2024-05-06 at 10 59 44](https://github.com/dhowe/AdNauseam/assets/4967860/cf88e956-2da2-4eff-9eda-96e164c5e858)

**Comment by dhowe** [comment]
both cases on that page -- I'll keep an eye out for the problem in the future and we can re-open
