### ISSUE TITLE
MegaUp Detects AdBlock

### ISSUE THREAD

**Issue by ConcernedCoder** [dhowe/AdNauseam#2535]
MegaUp detects adblock and denies downloads.
![Screenshot_21-5-2024_11449_download megaup net](https://github.com/dhowe/AdNauseam/assets/57155683/d9d5a21d-6075-4110-9db7-da55e5e72397)
[AdNauseam_Settings_Export_5.21.2024.11.49.36AM.json](https://github.com/dhowe/AdNauseam/files/15392319/AdNauseam_Settings_Export_5.21.2024.11.49.36AM.json)

**Comment by dhowe** [comment]
Cannot recreate. 
Location ?

**Comment by ConcernedCoder** [comment]
https://megaup.net/e289670f38ee7816fdcda66a4639f11c/Kenophobia.rarYou may need to check settings file--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 5/23/24, 1:07 AM Daniel Howe ***@***.***> wrote:

   
  Cannot recreate. Location ?

**Comment by mneunomne** [comment]
Also unable to recreate

**Comment by dhowe** [comment]
closing for now
