### ISSUE TITLE
Many Youtube Sponsored block ads on front page

### ISSUE THREAD

**Issue by BamsTheSergal** [dhowe/AdNauseam#2539]
### This is an AdNauseam-specific issue.

- [X] I have tested the same page on *uBlock Origin*, and the Ad is not visible.

### I have tried to reproduce the issue when...

- [X] AdNauseam is the only extension
- [X] AdNauseam uses default lists and setting.
- [X] Using a new, unmodified browser profile
- [X] All filter lists are updated

### Does Strict-Block mode solves the issue?

- [X] I have tested the same page with Strict-Block enabled, and the Ad is still visible.

### URL(s) where the issue occurs.

`youtube.com`

### Your location/country.

Iowa, USA.

### Screenshot(s)

![image](https://github.com/dhowe/AdNauseam/assets/12705993/08787cf8-2006-4cbf-9e34-6d05214b50b2)
![image](https://github.com/dhowe/AdNauseam/assets/12705993/b946cbd2-27b2-43ce-9757-d854018c33de)
![image](https://github.com/dhowe/AdNauseam/assets/12705993/ca716b8b-6490-484b-8ae0-1de5f3bea6e4)
![image](https://github.com/dhowe/AdNauseam/assets/12705993/7c0b8c58-5080-40a8-8eeb-8cc6cba1634e)

### Configuration

```
AdNauseam: 3.21.4
Firefox: 127
filterset (summary):
 network: 136247
 cosmetic: 47174
 scriptlet: 19948
 html: 1849
listset (total-discarded, last-updated):
 default:
  user-filters: 3-1, never
  adnauseam-filters: 538-2, 58m
  eff-dnt-whitelist: 567-0, 1d.6h.59m
  ublock-filters: 39001-114, 1d.6h.59m
  ublock-badware: 8924-0, 1d.6h.59m
  ublock-privacy: 929-2, 4d.7h.35m
  ublock-unbreak: 2423-2, 1d.6h.59m
  ublock-quick-fixes: 109-0, 2h.54m
  easylist: 87222-195, 5d.7h.27m
  easyprivacy: 51097-65, 5d.7h.27m
  urlhaus-1: 14870-0, 8h.54m
filterset (user): [array of 3 redacted]
untrustedset:
 added: [array of 6 redacted]
userSettings:
 admap: [redacted]
 firstInstall: false
 hidingAds: true
 clickingAds: true
 blockingMalware: true
 disableHidingForDNT: true
 disableClickingForDNT: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1750 ms (selfie)
 maxAssetCacheWait: 64 ms
 cacheBackend: indexedDB
```

**Comment by BamsTheSergal** [comment]
i've also been getting at random times, ads within the video player. i wasnt able to screenshot those before the sponsored block ones.

**Comment by mneunomne** [comment]
Sorry for this, a new release fixing this should be rolling out in the next days.

**Comment by mneunomne** [comment]
all youtube issues will be here from now on: https://github.com/dhowe/AdNauseam/issues/2544

closing this one and referencing on the main one.
