### ISSUE TITLE
ww8.gogoanimes.org: nuisance

### ISSUE THREAD

**Issue by FirstSgtDan** [dhowe/AdNauseam#2541]
### I tried to reproduce the issue when...

- [X] AdNauseam is the only extension
- [X] AdNauseam uses default lists and settings
- [X] Using a new, unmodified browser profile

### Description

When using AdNauseam on Mozilla Firefox, all buttons and links on gogoanimes.org become weird to click, including buttons on video players. A single left click doesn't do anything anywhere, a slow double-click doesn't do anything anywhere, a really fast double click might work in video players.

Workaround:
- Middle-clicking page buttons/links (like the buttons at the top of the page, "HOME", "ANIME LIST", "POPULAR", etc) or right clicking and selecting "open link [...]";
- Really fast double clicking might work in video players.

### URL(s) where the issue occurs.

Home page: `https://ww8.gogoanimes.org/`
Example page with video player: `https://ww8.gogoanimes.org/watch/nierautomata-ver1-1a-part-2-episode-1`

### Configuration

<details>

```yaml
AdNauseam: 3.21.4
Firefox: 127
filterset (summary):
 network: 138940
 cosmetic: 47512
 scriptlet: 20170
 html: 1857
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  adnauseam-filters: 538-2, now
  eff-dnt-whitelist: 563-0, now
  ublock-filters: 39156-112, now
  ublock-badware: 8732-1, now
  ublock-privacy: 1025-4, now
  ublock-unbreak: 2433-2, now
  ublock-quick-fixes: 114-2, now
  easylist: 86594-190, now
  easyprivacy: 52720-66, now
  urlhaus-1: 17070-5, now
filterset (user): [empty]
userSettings:
 admap: [redacted]
 firstInstall: false
 hidingAds: true
 clickingAds: true
 blockingMalware: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 856 ms
 maxAssetCacheWait: 344 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  1152394790.rsc.cdn77.org: 1
  cloudflareinsights.com: 3
  deedeisasbeaut.info: 3
  googletagmanager.com: 3
 extended:
  ##+js(abort-on-property-read, LieDetector)
  ##+js(no-window-open-if)
  ##+js(abort-current-script, Math, break;case $.)
  ##+js(abort-current-script, document.documentElement, break;case…
  ###overlayads
  ##div[style^="position: fixed; inset: 0px; z-index: 2147483647; …
  ##div[id][style^="position: fixed; inset: 0px; z-index: 21474836…
  ##+js(abort-on-property-write, adcashMacros)
  ##+js(abort-on-property-read, Adcash)
```
</details>

**Comment by mneunomne** [comment]
Fixed with PR above, closing.
