### ISSUE TITLE
AdNauseam opens logger in a tab instead of a separate window.

### ISSUE THREAD

**Issue by kotenok2000** [dhowe/AdNauseam#2543]
### I tried to reproduce the issue when...

- [X] AdNauseam is the only extension
- [X] AdNauseam uses default lists and settings
- [X] Using a new, unmodified browser profile

### Description

Ublock origin operns logger in a separate window.
AdNauseam opens logger in a tab.

### URL(s) where the issue occurs.

https://google.com

### Screenshot(s)

Ublock origin version 1.58.0
![image](https://github.com/user-attachments/assets/c4ae0235-1cbe-4c30-91be-d06da4750f43)

![image](https://github.com/user-attachments/assets/812aa12e-03c4-4e27-866e-fa16a187b8d7)

### Steps to Reproduce

1.Press on a UbO button in AdNauseam
2.Press on Logger button.

### Configuration

AdNauseam: 3.21.4
Chromium: 126
filterset (summary):
 network: 115517
 cosmetic: 68510
 scriptlet: 23204
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
 added:
  dpollock-0: 11689-4, 20m
  RUS-0: 40750-42, 3h.25m Δ
 default:
  user-filters: 3-0, never
  adnauseam-filters: 538-2, 1d.22h.54m
  eff-dnt-whitelist: 560-0, 1d.23h.59m
  ublock-filters: 39328-121, 6m Δ
  ublock-badware: 9428-2, 20m
  ublock-privacy: 1057-2, 6m Δ
  ublock-unbreak: 2391-0, 20m
  ublock-quick-fixes: 164-0, 20m
  easylist: 87174-442, 21m
  urlhaus-1: 14830-0, 20m
filterset (user): [array of 3 redacted]
userSettings:
 admap: [redacted]
 firstInstall: false
 hidingAds: true
 clickingAds: true
 blockingMalware: true
 strictBlockingMode: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 661 ms (selfie)
 maxAssetCacheWait: 167 ms
 cacheBackend: indexedDB

**Comment by dhowe** [comment]
Is there a particular problem this causes ? Our UI does not always match that of uBlock...

**Comment by dhowe** [comment]
closing for now
