### ISSUE TITLE
Bunkr (File Host) Showing Ads

### ISSUE THREAD

**Issue by fuwamocoanon** [dhowe/AdNauseam#2547]
### This is an AdNauseam-specific issue.

- [X] I have tested the same page on *uBlock Origin*, and the Ad is not visible.

### I have tried to reproduce the issue when...

- [X] AdNauseam is the only extension
- [X] AdNauseam uses default lists and setting.
- [X] Using a new, unmodified browser profile
- [X] All filter lists are updated

### Does Strict-Block mode solves the issue?

- [X] I have tested the same page with Strict-Block enabled, and the Ad is still visible.

### URL(s) where the issue occurs.

Both NSFW
`https://bunkr-albums.io/`
`https://bunkr.site/a/D3ZFAeSa`

### Your location/country.

USA

### Screenshot(s)

NSFW (Ads covered in white as 100% NSFW)
`https://postimg.cc/7b1dThPZ`
`https://postimg.cc/1f9T0S4c`

**Comment by fuwamocoanon** [comment]
Tested with default config w/o Strict Mode. Ads _appear_ to be handled in a similar manner to others, though AdNauseam not detecting them means they're using a different method. Such ad methods could be useful to detect moving forward, but unsure.

**Comment by mneunomne** [comment]
Fixed w/ #2547
