### ISSUE TITLE
keep erro on mainfest version

### ISSUE THREAD

**Issue by boomyi12345** [dhowe/AdNauseam#2572]
sorry I don't know I'm type correct I'm not English speaker from South Korea

 OS/version: windows 10
AdNauseam: 3.23.2
Chromium: 131
filterset (summary):
 network: 137507
 cosmetic: 53730
 scriptlet: 23247
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  adnauseam-filters: 547-2, 1d.20h.40m
  eff-dnt-whitelist: 510-0, 1d.20h.40m
  ublock-filters: 40632-142, 6m Δ
  ublock-badware: 11970-1, 6m Δ
  ublock-privacy: 1486-22, 6m Δ
  ublock-unbreak: 2507-1, 6m Δ
  ublock-quick-fixes: 220-4, 6m Δ
  easylist: 79043-290, 6m Δ
  easyprivacy: 53270-145, 6m Δ
  urlhaus-1: 19790-0, 6m
  KOR-1: 5215-30, 6m
filterset (user): [empty]
userSettings:
 admap: [redacted]
 firstInstall: false
 hidingAds: true
 clickingAds: true
 blockingMalware: true
 disableHidingForDNT: true
 disableClickingForDNT: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 336 ms (selfie)
 maxAssetCacheWait: 66 ms
 cacheBackend: indexedDB

**Comment by dhowe** [comment]
closing for now until some further info
