### ISSUE TITLE
Bug report AdNauseam

### ISSUE THREAD

**Issue by solun1** [dhowe/AdNauseam#2573]
Hi,

just wanted to report possible issue with AdNauseam on price comparison website heureka.cz. Not sure if the issue is on the side of AdNauseam, just forwarding the report here, I will just disable the add-on when I use the site and that solves the issue.

Thanks!

![error 2024-11-23 193623](https://github.com/user-attachments/assets/a2e12834-1c78-4f4e-98f9-46cbb88720ec)
### Describe the issue

*NOTE: if you are having a problem where ads are not collected, please FIRST TRY to create a new new Firefox profile as described [here](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_creating-a-profile). A corrupt Firefox profile is the most common cause of this issue.*

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version: Windows 11 home Version	10.0.26100 Build 26100
- Browser/version: Firefox 132.0.2
- AdNauseam version: 3.23.2
- Other extensions you have installed:  no other extensions
- AdNauseam settings: 

### Your location/country Czech Republic
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

**Comment by mneunomne** [comment]
Seems like the latest merge has fixed it @solun1
