### ISSUE TITLE
Vault buttons overlap timeline in narrow browser windows

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2577]
### I tried to reproduce the issue when...

- [X] AdNauseam is the only extension
- [X] AdNauseam uses default lists and settings
- [X] Using a new, unmodified browser profile

### Description

Vault buttons overlap timeline (import, export, etc) in narrow browser windows

<img width="944" alt="image" src="https://github.com/user-attachments/assets/29521b6c-77af-4ef5-8ff3-509de3f519be" />

**Comment by mneunomne** [comment]
Fixed:

![Screenshot 2024-12-20 at 15 59 45](https://github.com/user-attachments/assets/2ec9cf2b-d2b0-47d3-93ff-489c1155df67)
