### ISSUE TITLE
AdNauseam list blank in asset-viewer

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#258]
Shows 8 rules, but empty when clicked:

![screen shot 2016-06-16 at 7 25 13 pm](https://cloud.githubusercontent.com/assets/737638/16115174/2732af74-33f8-11e6-9ac7-a3f1ce2e4ec1.png)

**Comment by dhowe** [comment]
please verify adnauseam rules are visible in asset-viewer

**Comment by CyrusSUEN** [comment]
> verify adnauseam rules are visible in asset-viewer

my build is at 2e6350f484665368f8c284e60068a6ce94254efc and adnauseam rules are working correctly on my usually Chrome browser profile and on a new Chrome browser profile
