### ISSUE TITLE
Manifest error

### ISSUE THREAD

**Issue by vampiregoat699** [dhowe/AdNauseam#2584]
### I tried to reproduce the issue when...

- [X] AdNauseam is the only extension
- [X] AdNauseam uses default lists and settings
- [X] Using a new, unmodified browser profile

### Description

Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.

### Configuration

Just installed it and get this error

**Comment by dhowe** [comment]
This should be a warning, not an error. Please re-open if this is not the case
