### ISSUE TITLE
Text in text-ads not fitting in bounding boxes

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#261]
![screen shot 2016-06-17 at 5 54 40 pm](https://cloud.githubusercontent.com/assets/737638/16147269/acab2868-34b4-11e6-8b91-09fcf49e37be.png)

**Comment by mushon** [comment]
I'm not seeing text-ads at all in my vault even though the ``Capture text-only Ads when possible`` is active. Do you?

**Comment by dhowe** [comment]
Ok in latest release:

![screen shot 2016-07-26 at 10 25 17 pm](https://cloud.githubusercontent.com/assets/737638/17162003/09535f74-5380-11e6-9765-9367b81e751a.png)

**Comment by mushon** [comment]
@dhowe fixed in https://github.com/dhowe/AdNauseam/commit/663d281efab18232dd24b6af2020169452b55e4a please confirm

**Comment by dhowe** [comment]
ok
