### ISSUE TITLE
Check lists for ads: 'uBlock filters – Unbreak' and 'uBlock filters – Privacy'

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#264]
Check that these two lists have no rules that could block ads

**Comment by CyrusSUEN** [comment]
Tested on test 100 domains from https://docs.zoho.com/sheet/ropen.do?rid=x5joj133f1987b17f473285e5a644ba96e982

uBlock filters – Privacy is fine except the following rule blocks a visible ads on the upperright of on http://9gag.com/
```
||googletagservices.com/tag/js/gpt.js$script
```

uBlock filters – Unbreak‎
on http://www.food.com/
```
||amazon-adsystem.com/aax2/amzn_ads.js$script
```

**Comment by dhowe** [comment]
We need to test EasyList next...
But first, please describe exactly how you are doing this testing?

**Comment by CyrusSUEN** [comment]
> how you are doing this testing

Enabled only a single filter list for the test on uBlock
Opened the URLs of the above spreadsheet and notice if there were numbers on the badge icon
If there were and I notice missing ads, opened logger-ui.html on the responding page and then test the rule triggered by the following steps:

![1](https://cloud.githubusercontent.com/assets/2461812/16325411/66f56c20-39f0-11e6-93d7-301f272cc739.PNG)

![2](https://cloud.githubusercontent.com/assets/2461812/16325412/6c16622c-39f0-11e6-92be-7ca0290a9b61.PNG)

The page would refresh and then I would check if the ads appeared again

**Comment by CyrusSUEN** [comment]
> need to test EasyList next...

Do you mean EasyPrivacy? https://github.com/dhowe/AdNauseam/issues/34#issuecomment-218977280

**Comment by dhowe** [comment]
No, I mean "EasyList‎ (forums.lanik.us)"

**Comment by CyrusSUEN** [comment]
> No, I mean "EasyList‎ (forums.lanik.us)"

That's a list specially for ads. I think almost all the rules from the list block ads.

**Comment by dhowe** [comment]
The question is whether the rules are for hiding or blocking. But you can ignore that one for now. I will create another ticket for any further lists we need to check
