### ISSUE TITLE
Testing of release v2.2.8

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#266]
[Download](https://github.com/dhowe/AdNauseam/releases/tag/v2.2.8.1) and test on Firefox, Chrome, Opera:

- [x] check the AdNauseam version number
- [x] test a set of pages for each, and make sure that ads are being captured and visited
- [x] test the options (click-ads, block-malware, hide-ads)
- [x] test the header-options (cookies, referer, user-agent )
- [ ] test that incoming cookies are being blocked for adn-visits
- [x] test that no ads are collected in incognito/private-browsing windows
- [x] check general function of menu and vault
- [x] test import/export/clear functions
- [ ] test that no output is being written to console.log
- [x] Ask: test that no ads are showing and some text-ads are found
- [x] check the uBlock version number in the uBlock menu

**Comment by CyrusSUEN** [comment]
Done the test on new browser profiles on Chrome, Opera and Firefox.

The change of `Show the number of found ads on the icon` option is not on-the-fly. Users have to refresh the page to see the effect when turning it on and off.

The 'import ads` shows nothing if imported invalided ad set file. I think it's better to show at least something like `0 ads were imported` as if it imported an empty json file or `invalid ad set` etc.



> test that no ads are collected in incognito/private-browsing windows

There are actually ads collected and clicked in incognito mode on Chrome, Opera.
To enable ADN on Chrome and Opera, we need to check "Allow in incognito" in `chrome://extensions/` page.

> test that no output is being written to console.log

I only see console.log() from background.html

> check the uBlock version number in the uBlock menu

Do you think we should also show uBlock version in `/dashboard.html#links.html`

**Comment by CyrusSUEN** [comment]
> test that incoming cookies are being blocked for adn-visits

For the cookies part, the old issue persists: https://github.com/dhowe/AdNauseam/issues/216#issuecomment-225449559

I first clean the cookies page on `chrome://settings/cookies` and then imported and waited for ads to visit from [1002_ads.zip](https://github.com/dhowe/AdNauseam/files/326997/1002_ads.zip)

And then refresh the cookies page, there some incoming cookies not cleaned:
![cookies](https://cloud.githubusercontent.com/assets/2461812/16254867/ea5359b8-3876-11e6-9392-5f3d83290b9e.PNG)

**Comment by dhowe** [comment]
Can you check this with the current code?
Also, I don't see the new tickets mentioned above...

**Comment by CyrusSUEN** [comment]
Tickets created: 
> 'Show the number of found ads on the icon' option should updates all tabs

https://github.com/dhowe/AdNauseam/issues/272

> 'import ads' should show zero-count

https://github.com/dhowe/AdNauseam/issues/273

> Fix 'allow in incognito' for chrome/opera

https://github.com/dhowe/AdNauseam/issues/274

**Comment by CyrusSUEN** [comment]
> 2) Check the incoming cookie issue with the current code: 28f0964

Still getting some cookies.
![screen shot 2016-06-22 at 5 29 50 pm](https://cloud.githubusercontent.com/assets/2461812/16261731/415d4d68-389f-11e6-98b7-93b979325975.png)

I thinking if the cookies were collected from getting the ad image in Vault page. But I haven't open / touch the Vault page during the test.

**Comment by dhowe** [comment]
How we can verify this is whats happening? What site is the ad served from?

**Comment by CyrusSUEN** [comment]
> Test this by disabling 3rd party-cookies in the browser

Tried and still saw cookies.

I've extracted an ad that will generate cookies when visited by ADN.
[travelmama.com.hk.json.zip](https://github.com/dhowe/AdNauseam/files/329301/travelmama.com.hk.json.zip)
To use, please first clear existing cookies and ads and import this one. After it's being visited.

**Comment by dhowe** [comment]
fixed/pv,

**Comment by CyrusSUEN** [comment]
> fixed/pv

The cookies from travelmama.com.hk.json.zip were gone.

But there are still ads generating cookies when visited by ADN.
[www.cicaf.com.json.zip](https://github.com/dhowe/AdNauseam/files/331084/www.cicaf.com.json.zip)
[www.worldtech.com.hk.json.zip](https://github.com/dhowe/AdNauseam/files/331085/www.worldtech.com.hk.json.zip)

**Comment by CyrusSUEN** [comment]
Is there an easy / existing way to extract just certain types of ads from the exported JSON?
e.g. extract just those with `"targetUrl": "http://www.travelmama.com.hk",` attribute

**Comment by dhowe** [comment]
use jq

**Comment by dhowe** [comment]
Closing and creating a new ticket for the strange case of `www.worldtech.com.hk`, where a 'doubleclick' cookie is still sneaking through
