### ISSUE TITLE
'import ads' alert should show zero-count for invalid input file

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam#273]
The 'import ads' alert should always shows something after using it -- either `n ads imported`, `0 ads imported` or `invalid ad set`.

**Comment by dhowe** [comment]
fixed, pv -- not sure how to handle internationalise arbitrary error messages ... but you can create a separate ticket for this

**Comment by CyrusSUEN** [comment]
Fix verified.

> not sure how to handle internationalise arbitrary error messages

Do you mean `msg.error` in https://github.com/dhowe/AdNauseam/commit/d2d302287f3113e226cd6b04fda55a099f7ced7e#diff-958e2e19c4b35fb8f31b1aece632b311R42?
I don't think we need to translate that error.
