### ISSUE TITLE
Fix 'allow in incognito' for Chrome and Opera

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam#274]
There are currently ads collected and clicked in incognito mode on Chrome, Opera. ADN should disable the instance in incognito mode.

**Comment by dhowe** [comment]
fixed, please verify

**Comment by CyrusSUEN** [comment]
I can verify that no ads collected and clicked while in the mode. Should we also change the icon?

**Comment by dhowe** [comment]
interesting idea, but not critical for today's launch... we can let @mushon think about this later

**Comment by CyrusSUEN** [comment]
We can use the existing design. But sure we can wait. 
![screen shot 2016-06-23 at 1 41 45 pm](https://cloud.githubusercontent.com/assets/2461812/16292918/5432cbda-3948-11e6-91db-bb0057ea3821.png)
