### ISSUE TITLE
Check lists for Blocked Ads

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#279]
Verify that the checked items below do NOT block visual ads, and then test any unchecked items:

- [ ] Peter Lowe's Ad server list *** [Blocking rules]
- [x] Malware filter list by Disconnect‎ [Blocking rules]
- [ ] Malvertising filter list by Disconnect‎ [Blocking rules]
- [x] Fanboy’s Annoyance List‎ [Both]
- [ ] All Chinese region lists
 - [x] CHN: CJX's Annoyance List‎ [Both]
 - [ ] CHN: CJX's EasyList Lite [Both]
 - [ ] CHN: EasyList China [Both]
- [x] Spam404‎ (www.spam404.com)  [Both]
- [x] uBlock filters – Badware risks‎ [Both]
- [x] Anti-Adblock Killer | Reek‎ [Both]
- [x] Adblock Warning Removal List‎ [Both]
- [x] Malware Domain List‎ [Blocking rules]
- [x] Malware domains‎ [Blocking rules]
- [x] Malware domains (long-lived)‎ [Blocking rules]
- [x] Anti-ThirdpartySocial [Both]
- [x] Fanboy’s Social Blocking List‎ [Both]
- [x] EasyPrivacy [Blocking rules]
- [x] Basic tracking list by Disconnect‎ [Blocking rules]
- [ ] Dan Pollock’s hosts file‎ (someonewhocares.org) HTTP [Blocking rules]
- [ ] Fanboy’s Enhanced Tracking List‎ (forums.lanik.us)  [Both]
- [ ] Fanboy+Easylist-Merged Ultimate List‎ (forums.lanik.us)  [Both]
- [ ] hpHosts’ Ad and tracking servers‎ (hosts-file.net) HTTP [Blocking rules]
- [ ] MVPS HOSTS‎ (winhelp2002.mvps.org) HTTP [Blocking rules]
- [ ] uBlock filters – Experimental‎  (github.com) [Blocking rules]

**Comment by CyrusSUEN** [comment]
By blocking do you mean "not to download the visual ads at all"?

These are the 3 Chinese region filters I found from filter page:
> CHN: CJX's Annoyance List‎ (github.com)
 CHN: CJX's EasyList Lite (main focus on Chinese sites)‎ (github.com)
 CHN: EasyList China (中文)‎ (abpchina.org)

2 of them were created specifically to block / hide any ads possible based on EasyList.
I shall only check `CHN: CJX's Annoyance List‎`

**Comment by dhowe** [comment]
I mean that you should check, as we've done with all the others, that these lists don't block visual ads from loading.

**Comment by CyrusSUEN** [comment]
> Peter Lowe's Ad server list ***
> Malvertising filter list by Disconnect‎

There is a chain of rules blocking ads. Allowing a few rules will trigger more rules to block the ads. almost Impossible to modify.

>  Malware filter list by Disconnect‎
> Spam404‎ (www.spam404.com)

No visual ads are blocked. Not even a single rule got triggered in our test sample. (after all they are dedicated filters at blocking malware and scam)

> Fanboy’s Annoyance List‎

No visual ads are blocked.


> CHN: CJX's Annoyance List‎ (github.com)

No visual ads are blocked.

> CHN: CJX's EasyList Lite (main focus on Chinese sites)‎ (github.com)

Dedicated ads filters with too many chained rules (blocking one triggers others). Even blocks Google ads from non-Chinese websites.

> CHN: EasyList China (中文)‎ (abpchina.org)

Dedicated ads filters with too many chained rules (blocking one triggers others). Does not block Google ads from non-Chinese websites.

**Comment by dhowe** [comment]
@CyrusSUEN have you finished this ticket? Are all the checked lists above ok?

**Comment by CyrusSUEN** [comment]
> have you finished this ticket?

Yes. I've finished this on Jul 8 2016.

> Are all the checked lists above ok?

Yes. At least at Jul 8.

**Comment by CyrusSUEN** [comment]
List of the websites for checking visual ads: https://docs.zoho.com/sheet/ropen.do?rid=x5joj133f1987b17f473285e5a644ba96e982 shared with @cqx931 

### Steps to check visual ads
1. Visit all the links with only one filter list enabled
2. Check if there are visual ads missing. If so, go to logger-ui.html page from ADN menu and reload the web page again and find out which rules trigger the block 
3. Verify your finding by temporarily marking the triggered rule with Green color in the logger page and then refresh the page

As for the meaning of the colored entries, here is the [explanation from uBlock Origin](https://github.com/gorhill/uBlock/wiki/The-logger):

> The color of a row hints at how the resource was filtered:
> 
> No color: The request for the resource was allowed to go through because it matched no filter/rule.
> Red: The request for the resource was canceled because of a block filter/rule.
> Green: The request for the resource was allowed to go through because it matched a filter/rule which purpose is to bypass a matching block filter/rule.
> Yellow:
> A DOM element which was blocked by a cosmetic filter; OR
> A blocked request for a resource was redirected to a local replacement resource.

**Comment by dhowe** [comment]
@CyrusSUEN -- Just to clarify,  the following lists are OK for blocking (that is, they do not block ANY visual ads):

-  Spam404‎ (www.spam404.com)
-  uBlock filters – Badware risks‎
-  Anti-Adblock Killer | Reek‎
-  Adblock Warning Removal List‎
-  Malware Domain List‎
-  Malware domains‎
-  Malware domains (long-lived)‎
-  Anti-ThirdpartySocial
-  Fanboy’s Social Blocking List‎
-  EasyPrivacy

**Comment by CyrusSUEN** [comment]
> they do not block ANY visual ads

Yes. I do not see visual ads getting blocked from the [list of websites here](https://docs.zoho.com/sheet/ropen.do?rid=x5joj133f1987b17f473285e5a644ba96e982)

**Comment by dhowe** [comment]
Adblock Warning Removal List‎ (forums.lanik.us)
 Anti-Adblock Killer | Reek‎  (github.com)
 Basic tracking list by Disconnect‎
 Dan Pollock’s hosts file‎ (someonewhocares.org) HTTP
 Fanboy’s Enhanced Tracking List‎ (forums.lanik.us)
 Fanboy+Easylist-Merged Ultimate List‎ (forums.lanik.us)
 hpHosts’ Ad and tracking servers‎ (hosts-file.net) HTTP
 MVPS HOSTS‎ (winhelp2002.mvps.org) HTTP
 uBlock filters – Experimental‎  (github.com)

**Comment by cqx931** [comment]
**Adblock Warning Removal List‎ (forums.lanik.us)**
**Anti-Adblock Killer | Reek‎  (github.com)**
Don’t block any visual ads, they are mainly for blocking those script that tries to block adblocks or adblock warning messages

**Basic tracking list by Disconnect‎**
Don’t block any visual ads, a short list for anti-tracking

**Fanboy’s Enhanced Tracking List‎ (forums.lanik.us)**
Block visual ads from googletagservices or doubleclick

**Dan Pollock’s hosts file‎ (someonewhocares.org) HTTP**
Block many visual ads, especially the section "ad sites" and "spyware-sites"

**Fanboy+Easylist-Merged Ultimate List‎ (forums.lanik.us)**
A combined list of Easylist and Fanboy list,  an ultimate visual ad blocking list.

**hpHosts’ Ad and tracking servers‎ (hosts-file.net) HTTP**
Many ad servers are blocked by the list

**MVPS HOSTS‎ (winhelp2002.mvps.org) HTTP**
Many ad servers are blocked by the list

**uBlock filters – Experimental‎  (github.com)**
A short list of experimental filters that may cause breakage, targeting on google’s ad services as well

**Comment by dhowe** [comment]
Please also mark whether each list (for the whole set) has blocking rules, hiding rules, or both...

**Comment by cqx931** [comment]
Updated info about blocking rules/hiding rules

**Comment by dhowe** [comment]
Please also check the rules (block,hide, or both) in the original comment above, thanks

**Comment by cqx931** [comment]
The full list has been updated now.

**Comment by dhowe** [comment]
👍

**Comment by dhowe** [comment]
Please compare the above lists to the [enabledBlockLists](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L41) array.

If a list above contains only cosmetic rules, or blocks visual ads, then it should NOT be included in enabledBlockLists. If it does not block visual ads, but does block other things, then it should be included.

The only exception to this is lists for which only a few specific rules cause visual ads to be blocked. In these cases we can add the list to 'enabledBlockLists' and then ignore those specific rules by adding them to [disabledBlockingRules](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L35)

**Comment by cqx931** [comment]
The following three lists from enabledBlockLists array is not included in the above lists, but since they all don't block visual ads, they shall be ok to stay.
'uBlock filters – Unbreak',
'uBlock filters – Privacy'
'EasyPrivacy'

The following lists shall be removed according to your standard:
Peter Lowe's Ad server list *** [Blocking rules]
Malvertising filter list by Disconnect‎ [Blocking rules]
Dan Pollock’s hosts file‎ (someonewhocares.org) HTTP [Blocking rules]
 hpHosts’ Ad and tracking servers‎ (hosts-file.net) HTTP [Blocking rules]
 MVPS HOSTS‎ (winhelp2002.mvps.org) HTTP [Blocking rules]
 uBlock filters – Experimental‎  (github.com) [Blocking rules]

**Comment by dhowe** [comment]
Please add these to 'hiddenLists' in 3p-filters.js
We should also consider simply removing them from assets/ublock/filter-lists.json
