### ISSUE TITLE
Incoming cookies slipping through the net

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#283]
Specifically "doubleclick" cookies. What is happening here (might this be a case of respawn/sync)?

To recreate:
1. create a .json file with the ad below
2. clear ads and browser cookies
3. import the .json file
4. wait for visit and check browser cookies

```
{
  "http://forum4.hkgolden.com/view.aspx?type=TO&message=5100362": {
      "forum4.hkgolden.com::https://tpc.googlesyndication.com/simgad/5617557006391557812": {
      "id": 1198,
      "attempts": 0,
      "visitedTs": 0,
      "attemptedTs": 0,
      "contentData": {
        "src": "https://tpc.googlesyndication.com/simgad/5617557006391557812"
      },
      "contentType": "img",
      "title": "Pending",
      "resolvedTargetUrl": null,
      "foundTs": 1460264993142,
      "targetUrl": "http://www.worldtech.com.hk",
      "pageTitle": "邊度仲有 MG GUNDAM 00 賣?? - 香港高登討論區",
      "pageUrl": "http://forum4.hkgolden.com/view.aspx?type=TO&message=5100362",
      "pageDomain": "forum4.hkgolden.com",
      "version": "2.0.6"
    }
  }
}
```

**Comment by dhowe** [comment]
@cqx931 see if you can recreate this issue

**Comment by cqx931** [comment]
I have followed the steps you mentioned,but I didn't find any new cookies coming in after the visit.
<img width="860" alt="screen shot 2016-09-22 at 9 02 24 am" src="https://cloud.githubusercontent.com/assets/3056154/18734084/5be3556e-80a3-11e6-9c06-6beaa1da7315.png">

**Comment by dhowe** [comment]
ok, closing for now, thanks...
