### ISSUE TITLE
Optimize background image of firstrun page 

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam#285]
![firstrun page](https://cloud.githubusercontent.com/assets/2461812/16343202/600e4d82-3a68-11e6-8ca7-ddaa92f7d756.png)
The background image does not look so right given an excessive browser height (compared to the width). 

The best way to do it in my opinion would be separating [the image](https://github.com/dhowe/AdNauseam/blob/master/src/img/adn_clickbot_bg.jpg) to 3 elements:
- the grid mesh background
- the bot and the button
- the light bulb

So that the bot will always stick to the bottom of the browser and the light bulb will stick to the browser's ceiling and then apply the mesh background on top of them.

**Comment by cqx931** [comment]
I also noticed this when I did android testing, here is a quick fix: 
https://github.com/dhowe/AdNauseam/pull/987/commits/110a371f825d0de9d8f93e0a1ad144a03b369a03

**Comment by dhowe** [comment]
@mushon @cqx931  can this be closed ?

**Comment by mushon** [comment]
Ok by me.

**Comment by cqx931** [comment]
I think so...this is fixed.
