### ISSUE TITLE
Bug in CSS on homepage (gh-pages) 

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#295]
see commit cf90c3e0ff8cc368c96
also, see #291 

<img width="632" alt="screen shot 2016-07-19 at 12 37 47 pm" src="https://cloud.githubusercontent.com/assets/737638/16959124/765ad5a4-4db1-11e6-8241-2f21c3609c66.png">

**Comment by mushon** [comment]
I will hopefully get to it tomorrow. It has something to do with the :nth-child(last) logic in the css.

**Comment by mushon** [comment]
I've tried fixing this in css but apparently ``:last-of-type`` doesn't work for classes.
I think this would have to be fixed in JS after all.
@dhowe any chance we can make the fix less temporary?

**Comment by dhowe** [comment]
sure

**Comment by dhowe** [comment]
Re-opening -- @mushon, what does your design specify for non-supported browsers, e.g., Safari, etc. ?

**Comment by mushon** [comment]
It currently doesn't. 
I would suggest not to target them but to choose either Firefox or Chrome and by that implicitly suggest using a different browser.

**Comment by dhowe** [comment]
defaults to chrome now
