### ISSUE TITLE
Add cost to menu/vault for number of ads clicked

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#296]
Something like this: http://www.nytimes.com/interactive/2015/10/01/business/100000003949287.mobile.html

**Comment by mushon** [comment]
they are talking about the cost of loading on mobile devices based on data plan charges. I was thinking this is not the economic question we want to focus on, but rather try to estimate how much are all these clicks worth. Now I am not sure we can calculate or even accurately estimate that, but maybe some guesstimate can be interesting enough to present.

According to [this site](https://www.hochmanconsultants.com/cost-of-ppc-advertising/) the average PPC price is $1.58, which would mean that my current install that has clicked detected 1015 ads has cost advertisers about $1603.7. That's a pretty nice number to present in the vault and maybe even at the top of the menu.

**Comment by mushon** [comment]
I've added the design for this for both the menu and the vault:

![uploads/e731fd51-ec1a-42b7-b9b1-d7fbc61eab96/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe731fd51-ec1a-42b7-b9b1-d7fbc61eab96%2Fblob)


![uploads/f59a0a57-4ae2-475e-8130-739c609eb325/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff59a0a57-4ae2-475e-8130-739c609eb325%2Fblob)

@dhowe review / implement?

**Comment by mushon** [comment]
markup available on https://github.com/dhowe/AdNauseam/commit/7a1da21d0c08a909f89f38fd18cc601c022d8a28

**Comment by dhowe** [comment]
see also #323

**Comment by dhowe** [comment]
made some adjustments, @mushon please verify b469a16

![screen shot 2016-08-08 at 6 02 44 pm](https://cloud.githubusercontent.com/assets/737638/17497981/8884992c-5d92-11e6-8294-4ce0cbf58b36.png)

**Comment by dhowe** [comment]
Also, I think we need to add a ? in the menu as well, as this is what most users will see first...

**Comment by dhowe** [comment]
And we should consider adding energy costs for blocked resources (which we are not handling now)...

**Comment by mushon** [comment]
@mushon would change the vault wording to ``Total Estimated [cost $14.22?]``

**Comment by mushon** [comment]
note, I kept the "=" in the vault. I could go with or without it, if you don't like it let me know.
