### ISSUE TITLE
Add 'New Features' panel to homepage

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#297]
New features:

* whitelisting (by page, by site)
* list-subscription
* tracker-blocking
* options: 'block trackers, but see ads'
* ???

...

**Comment by mushon** [comment]
ok, text:

* clicking & blocking ads (thanks uBlock!)
* actually you can click all ads, but still see them
* we now also block non-ad trackers
* whitelist pages or sites
* subscribe to filter lists

**Comment by mushon** [comment]
![new-in-adn](https://cloud.githubusercontent.com/assets/27123/17023069/1af1ead6-4f5a-11e6-8d81-fd304744d1e9.gif)

closed?

**Comment by dhowe** [comment]
a little bit carnival, but gets the point across

**Comment by mushon** [comment]
Glad you liked it.

**Comment by mushon** [comment]
If it's ok I will prioritize getting the video done first and then enter these adjustments

**Comment by mushon** [comment]
can we drop the "add your own custom rules (thanks ublock)"? it means nothing to most people

**Comment by dhowe** [comment]
Ok, so:

**NEW! In AdNauseam 2.0**       [Note the capital I]
- hide and click ads 
- click all ads without hiding them (if you want)
- block trackers and malware
- whitelist pages and sites
- subscribe to filter lists (thanks ublock)
- and even more!

**Comment by mushon** [comment]
@dhowe please close

**Comment by dhowe** [comment]
still doesn't match the text, unless these are intentional changes on your part...

**Comment by mushon** [comment]
so you want to drop the ``(thanks uBlock)`` from block trackers and malware?
why?

**Comment by dhowe** [comment]
they need only to be thanked once, no?

Before re-editing the GIF, make whatever changes you want to the text above, until we've agreed...

**Comment by mushon** [comment]
I'm ok with your wording, I will apply them to the gif:

- hide and click ads
- click all ads without hiding them (if you want)
- block trackers and malware
- whitelist pages and sites
- subscribe to filter lists (thanks uBlock)
- and even more!

**Comment by mushon** [comment]
can we close this?
