### ISSUE TITLE
Should redirect http request to https version of ADN homepage

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam#299]
After entering the URL of `http://adnauseam.io` or simply `adnauseam.io`, it loads the `http` version of the homepage.
![capture](https://cloud.githubusercontent.com/assets/2461812/17057670/16cb0f74-504e-11e6-83ce-1411ad7f6f86.png)

 It should automatically redirect users to the `https` version even if the user request a `http` only protocol.

**Comment by dhowe** [comment]
No. If no protocol is specified, https should be used. If http is specified, then http should be used.

**Comment by CyrusSUEN** [comment]
Will it be easier to just redirect all connections to HTTPS by [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) when implementing?

Or just redirect `adnauseam.io` to `https://adnauseam.io` in apache?
http://httpd.apache.org/docs/current/rewrite/avoid.html#redirect

**Comment by dhowe** [comment]
this page is hosted on github-pages which, as best I can tell, does not support HSTS for custom domains:

![screen shot 2016-08-11 at 6 47 13 pm](https://cloud.githubusercontent.com/assets/737638/17607507/2e4f4e98-5ff4-11e6-91b2-8638717c256c.png)
