### ISSUE TITLE
Auto-replacement of social media links

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#302]
See Privacy Badger's [implementation](https://github.com/EFForg/privacybadgerchrome/blob/master/src/socialwidgets.js)

**Comment by dhowe** [comment]
@CyrusSUEN this is a content-script, so there should not be bery many dependencies...
But please document them here

**Comment by CyrusSUEN** [comment]
> document them here

The following functions 
https://github.com/EFForg/privacybadgerchrome/blob/master/src/socialwidgets.js#L331-L339
https://github.com/EFForg/privacybadgerchrome/blob/master/src/socialwidgets.js#L349-L354
both call `webrequirest.js` which further relies on other module https://github.com/EFForg/privacybadgerchrome/blob/master/src/webrequest.js#L25

**Comment by dhowe** [comment]
this should be an opt-in setting

**Comment by arpie42** [comment]
Is this going to happen?

Is there an alternative way to achieve this (eg another browser extension that does this but wont clash with AdNauseum)?

I currently use AdBlock but would like to switch to AdNauseum, this is the only thing preventing me... I want all social media links blocked but afaict AdNauseum doesn't block them, wheras AdBlock does.

**Comment by dhowe** [comment]
Adnauseam can block these... You just need to go to Settings->Third-Party-Filters and enable the lists under 'Annoyances'. AdNauseam should be able to block anything that Adblock can (if not, please let us know).

**Comment by arpie42** [comment]
Hmmm... yes, it looks like it does block them if I turn on Annoyances... but it doesn't tell me it has done it.  Does AdNauseum have a way of finding out what has been blocked on a page?  Also, I presume the little number next to the icon counts clicks, not blocks?

**Comment by mneunomne** [comment]
@dhowe is this still relavant? Otherwise we should close, all the links in the post are broken
