### ISSUE TITLE
Test on Panopticlick 2.0 test-set for blockers

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#304]
Please check all 4 tests and report below...

https://panopticlick.eff.org/

<img width="740" alt="screen shot 2016-07-22 at 9 36 09 pm" src="https://cloud.githubusercontent.com/assets/737638/17075003/be1ba63e-5054-11e6-8fdc-4e1831658cfe.png">

**Comment by cqx931** [comment]
I also see the same result as above, though sometimes I see the first test as "no" as well.

I have fixed some notification/icon issue for DNT site here: https://github.com/dhowe/AdNauseam/pull/771

The result from "Does your browser unblock 3rd parties that promise to honor Do Not Track?" seems a bit weird for me. I can see from both the logger and the console that we are allowing requests from do-not-tracker.org...
![image](https://cloud.githubusercontent.com/assets/3056154/22054084/fe226e3a-dd8e-11e6-8932-f6282a354842.png)

**Comment by dhowe** [comment]
the important thing here is to fix the DNT result -- does your PR do this?

**Comment by cqx931** [comment]
My PR is not about fixing the DNT result. I am still checking this issue now.

**Comment by cqx931** [comment]
After blocking the two tracking domains, we are able to pass the DNT test. https://github.com/dhowe/uAssets/pull/24
