### ISSUE TITLE
Option to check/honor EFF DNT postings

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#306]
as eff.org/pb does...

something like:
- check each domain encountered (only once within a specified time-frame), for a valid DNT posting
- if exists, and is valid, add domain to whitelist (mark as DNT)
- if not exists, or is not valid, and exists on whitelist, marked as DNT, remove from whitelist
- once whitelisted, ads will not be hidden, or visited

**Comment by mushon** [comment]
Ideally this have been implemented as a subscribable whitelist?

**Comment by dhowe** [comment]
Yes, the only issue here would be maintenance... though a script (run by eff.org) could automatically updated the list. But a list of (exception) rules in the abp/ublock/pb/adn format would be pretty nice for any other tools wanting to adopt EFF's DNT mechanism. 

This would also eliminate a fair number of requests being made by PrivacyBadger (and soon, AdNauseam) as each extension is checking and re-checking for the same DNT files over and over. See PB ticket https://github.com/EFForg/privacybadgerfirefox/issues/764 .

I guess the question for EFF is whether this goes against PB's philosophy, that each client figures out how to act on its own, based on real-time data (though it already uses a centralized [cookie-block list]())... any thoughts on this @cooperq ?

**Comment by cooperq** [comment]
I am currently working on an ABP format white list for DNT compatible domains, privacy badger won't be using this for various reasons, but I am hoping to convince abp and others to use it. 
Tracking this issue in https://github.com/EFForg/privacybadgerchrome/issues/894

**Comment by dhowe** [comment]
Note:  we need to consider what to do when a user selects this option while, at the same time, having sending of the DNT header disabled in the browser itself.  

The options are:
1. show a warning (and possibly do one of the below)
2. ignore the browser setting and send DNT anyway
3. toggle the browser setting to correspond to user choice
4. don't send the header, but still whitelist DNT-posted sites
5. disallow enabling DNT-respect unless its already set in the browser

**Comment by mushon** [comment]
I vote for 1+3

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by dhowe** [comment]
@mushon Need to think about how/whether we show the DNT list under 3rd-party settings; we want people to be able to see when its out of date and trigger an update-check (like other lists), yet we don't want them to be able to toggle it on/off (instead, this should be automatically done when they select either of the honorDNT options)

**Comment by cooperq** [comment]
FWIW in privacy badger we just automatically send the DNT:1 header. I agree that 3 is the best option, you should probably make clear to the user that this means the DNT header will be sent (AFAIK you can not programatically set the DNT header in chrome.)

**Comment by cooperq** [comment]
Permallink to EFF DNT whitelist: https://www.eff.org/files/effdntlist.txt

**Comment by dhowe** [comment]
Per our discussion, I think we will go with the following:
- include a non-user-interactive DNT list entry on our 'whitelists' page in settings
- send the DNT header, and enable the DNT list entry whenever either DNT setting is enabled

**Comment by dhowe** [comment]
done in 3.0.5
