### ISSUE TITLE
Delete ad failing in vault

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#308]
Delete ad in vault, then refresh page and it returns.

**Comment by CyrusSUEN** [comment]
Can I have the exported JSON file? It works fine on my ADN at 228ff4d4157946d549c8ff9f192310d67640cabf

**Comment by dhowe** [comment]
[AdNauseam-81-image-ads.json.zip](https://github.com/dhowe/AdNauseam/files/392181/AdNauseam-81-image-ads.json.zip)

**Comment by CyrusSUEN** [comment]
Fixed, please verify: https://github.com/dhowe/AdNauseam/pull/320
