### ISSUE TITLE
Better language for whitelisting via menu

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#309]
Currently the button reads "pause adnauseam" which is not what we the user is doing. We are whitelisting either the page or the site... this is quite misleading.

**Comment by mushon** [comment]
do you have a better suggestion?

**Comment by mushon** [comment]
Change "Pause AdNauseam" to "Disable On Domain"
if the 'ctrl' button (or the right click) is clicked change to "Disable On Page"
If the page/domain is disabled, change to "Resume AdNauseam"

**Comment by dhowe** [comment]
Need to capture the key-event in js for ctrl...

**Comment by dhowe** [comment]
@mushon, where are we this?

**Comment by mushon** [comment]
UI wise it seems implemented but I'm not sure it works.
Also CTRL+Click is probably not the right way to go as it functions as right click on Mac. Maybe we should use shift+click or alt+click instead?

**Comment by dhowe** [comment]
your call..

**Comment by mushon** [comment]
Alt+Click

**Comment by dhowe** [comment]
@cqx931 we need to detect the alt-keystroke in js, then switch text

**Comment by cqx931** [comment]
Can we change the text to "Disable AdNauseam"? And explain the default performance and "alt + click" performance on hover?
the translation of "Disable On Domain"/"Disable On Page" from some languages could be too long for the space we have in menu.

**Comment by mushon** [comment]
Would it help if we simply drop the word AdNauseam?

When ADN is enabled we can go with:
Click: Disable On Domain 
Ctrl+Click: Disable On Page

And when ADN is disabled we can go with:
Click: Enable On Domain 
Ctrl+Click: Enable On Page

**Comment by dhowe** [comment]
fine by me

**Comment by cqx931** [comment]
Double checked with Windows and Linux, alt-click is not included in the default keyboard short cut.
https://support.microsoft.com/en-us/help/126449/keyboard-shortcuts-for-windows
https://help.ubuntu.com/community/KeyboardShortcuts

I have modified the button text in the latest update, can this be closed now?
