### ISSUE TITLE
Ads in vault disappear after window resize

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#310]
To recreate:

1. Make browser window very large
1. AdNauseam: Clear ads
2. Visit [this page](https://www.google.com.hk/search?q=Credit+cards&oq=Credit+cards)
3.  AdNauseam: Open vault
4. Drag from right edge to make window smaller
5. Watch as ads disappear (and cannot be recovered without refreshing page)

<img width="991" alt="screen shot 2016-07-26 at 4 04 04 pm" src="https://cloud.githubusercontent.com/assets/737638/17153410/a02ad872-534a-11e6-8409-a1d96cf592cf.png">

v2.3.1 Chrome, OS X

**Comment by CyrusSUEN** [comment]
Using Chrome 52 on MacOS 10.10 and Win10 with a monitor resolution of 2560 * 1440 and ADN was built at 228ff4d4157946d549c8ff9f192310d67640cabf, I cannot reproduce this problem on both platforms. 

![screen shot 2016-07-29 at 8 54 14 pm 2](https://cloud.githubusercontent.com/assets/2461812/17248786/49f56fb2-55cf-11e6-985a-ef92af562b36.png)

**Comment by dhowe** [comment]
close for now, reopen if  occurs again
