### ISSUE TITLE
Add 'Press Kit' link to web-site

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#313]
Including the creation of the press kit itself

**Comment by dhowe** [comment]
progress? we are getting close to 2.4

**Comment by mushon** [comment]
Sorry, I'm currently on vacation until Oct 17th, but will try to put in some hours maybe on the plane back. 

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by dhowe** [comment]
status @mushon? this is the main issue holding back release..

**Comment by mushon** [comment]
Waiting for an ok from @dhowe on the outline and then will edit accordingly: https://hackpad.com/AdNauseam-2.0-Press-Release-ThhzjZ8pR7p

**Comment by mushon** [comment]
current press release posted on the 3.0 branch
