### ISSUE TITLE
Implement Click-Frequency slider

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#317]
Something like: Always/Often/Sometimes/Rarely ?

**Comment by mushon** [comment]
As in when should ads be clicked?
+ Do you see this as something to go in the settings only or also in the first-run screen?

**Comment by dhowe** [comment]
Always: click every ad
Often: several per hour
Sometimes: several per day
Rarely: several per week

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/23891494/9668715e-08d1-11e7-8ee2-622608e42935.png)

**Comment by dhowe** [comment]
good start... horizontal alignment?

**Comment by cqx931** [comment]
Do you think they should align?(the check boxes) I think it makes more sense like this, as they belong to one sub group

**Comment by dhowe** [comment]
Or maybe it should be:

- [ ] Click ALL ads
- [ ] Click MOST ads
- [ ] Click SOME ads
- [ ] Click OCCASIONAL ads

with a thin rectangle around the group... ?

**Comment by cqx931** [comment]
But what you suggested above is different... per hour/day/week is time frequency and this is something different.

**Comment by dhowe** [comment]
Note also that 'Don't send cookies' will be off by default in new installs

**Comment by cqx931** [comment]
I think it looks better without the box...
![image](https://cloud.githubusercontent.com/assets/3056154/23892601/381741d4-08d6-11e7-9b1f-04c6a5625b88.png)

**Comment by cqx931** [comment]
But "Click MOST ads" and "Click SOME ads" sound like that AdNauseam clicks some ads and not the others.

**Comment by dhowe** [comment]
Right so the question is whether we click all ads, but slowly, or whether we click some ads.
I think we want to do the latter. Can we try with all, most, some & occasional ?

**Comment by cqx931** [comment]
I uploaded that one but it didn't show up before, you should be able to see it now.

**Comment by dhowe** [comment]
Yes, random selection, at least to start. I like the bottom most image above. Can you try it with a rounded rectangle?

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/23894166/06365d66-08dc-11e7-9559-0a972a32dcd8.png)

**Comment by dhowe** [comment]
Ok, please implement (and localize)... but ads should be "Ads", capital A...

**Comment by cqx931** [comment]
Shall I push this to a new branch or master is ok?
We should also need an info button for this section.

**Comment by dhowe** [comment]
master is fine (and yes, info button for the group, as mentioned above, as well as for 'Dont send cookies')

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/AdNauseam/pull/928
Only the interface for now. No background script is added accordingly.

**Comment by mushon** [comment]
How about implementing this as a slider with 4 ticks?

**Comment by dhowe** [comment]
Lets start with checkboxes, then once we have it working, we can consider other designs

**Comment by dhowe** [comment]
@cqx931 please enable the interface to select values for the 'clickProbability' preference: [all:1, most: .75, some: .3, occasional: .1] for now ...

**Comment by mushon** [comment]
Re:
> Lets start with checkboxes, then once we have it working, we can consider other designs

Sure thing

**Comment by mushon** [comment]
How about this:
![image](https://cloud.githubusercontent.com/assets/27123/24079078/4ee45f5e-0c88-11e7-9a76-3c6c5205824c.png)

**Comment by dhowe** [comment]
So this is still a button-group, but with a slider 'illustration'? That is, the user still must select 1 of 4 choices...

Actually the intent of the slider (even with tick-marks showing common settings) is to allow the user to select any value between 0% and 100% (perhaps selecting 0% also disables the 'click ads' toggle)

**Comment by mushon** [comment]
Yes, this is a discrete slider and as a slider it better communicates its scale functionality (which is not represented by the radio buttons). Functionality-wise it is equivalent to the radio buttons and I think it should stay that way.

**Comment by dhowe** [comment]
At some point, relatively soon, we should move to a continuous slider (see #969), however in the meantime, whether to use the toggle-group we have now, or something more graphical, like above, is a visual design decision you should make
