### ISSUE TITLE
Metrics for 3rd-party blocking

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#321]
https://github.com/gorhill/uBlock/wiki/Blocking-mode

include the number of ads found (in each mode) in the results

to test 'no blocking', disable all-lists except 'easylist'

**Comment by CyrusSUEN** [comment]
> to test 'no blocking', disable all-lists except 'easylist'

This is actually the [very easy mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-very-easy-mode) tested by the author of uBlock.
For testing no blocker mode, I literally did not enable AdNauseam for the test.

Here are the results:
![06 3rd_party_hit](https://cloud.githubusercontent.com/assets/2461812/17403183/38dd95a6-5a89-11e6-8b42-14d306f143a7.PNG)
![07 ads_collected](https://cloud.githubusercontent.com/assets/2461812/17403182/38c2da22-5a89-11e6-9838-3fc7a22bf67c.PNG)
The number of ads found in Medium mode is especially low and I've tested this mode twice to verify that.

This is the zip containing all the result and the spreadsheet:
[adnauseam hit test.zip](https://github.com/dhowe/AdNauseam/files/401699/adnauseam.hit.test.zip)

**Comment by dhowe** [comment]
No, VeryEasy mode includes uBlock filters. We want only to include EasyList (or alternatively, disable blocking altogether)

**Comment by CyrusSUEN** [comment]
> We want only to include EasyList

I'm adding this mode and running the test again.

**Comment by CyrusSUEN** [comment]
I've updated the filter lists before the new test.
Here are the new results:

![07 3rd_party_hit](https://cloud.githubusercontent.com/assets/2461812/17413036/418e62ce-5ab2-11e6-90aa-3330d1b9be20.PNG)

![08 ads_collected](https://cloud.githubusercontent.com/assets/2461812/17413037/419ff732-5ab2-11e6-9f78-8cffc476bd7f.PNG)

[adnauseam hit test 2.zip](https://github.com/dhowe/AdNauseam/files/402303/adnauseam.hit.test.2.zip)

**Comment by CyrusSUEN** [comment]
3rd test using updated sessbench and ADN
detailed ad counts per page listed in the second page of the attached spreadsheet
[adnauseam_3rd_party_hit_3rd_test.zip](https://github.com/dhowe/AdNauseam/files/404929/adnauseam_3rd_party_hit_3rd_test.zip)


![3rd_party_hit](https://cloud.githubusercontent.com/assets/2461812/17455667/2d5f8c56-5bf2-11e6-8124-9fe95abf2cbf.PNG)

![ads_collected](https://cloud.githubusercontent.com/assets/2461812/17455666/2d5ecdc0-5bf2-11e6-9a5b-6090cf58dcc5.PNG)

**Comment by dhowe** [comment]
The numbers for 'hard' still don't make sense (look at wsj.com for example). 
So we need to isolate what is causing the vast increase in ads for 'Hard' mode.
Are sites serving local ads, images, & css when 3rd party-everything is blocked?
Or is the site so broken that we are getting false-positives ?

1. Make a list of 10-20 sites like wsj.com that show a big increase in ads for 'hard' mode
2. Configure two ADN setups, one with 'medium', one with 'hard'
3. Visit each site manually with the two browsers and make notes (or take screenshots) of what you see
4. Count the actual ads on each page and compare to the numbers we are getting.

Also, run one test set with sessBench using the following configuration:

EasyList
Add * * 3p block

**Comment by CyrusSUEN** [comment]
> Or is the site so broken that we are getting false-positives ?

This is the case. The collected ads on wsj.com were actually their news articles
such as:
```json
{
  "http://www.wsj.com/asia": {
    "www.wsj.com::-1::https://si.wsj.net/public/resources/images/OJ-AN646_CPHONE_E_20160809235652.jpg::-1": {
      "id": 1,
      "attempts": 0,
      "visitedTs": 0,
      "attemptedTs": 0,
      "current": true,
      "contentData": {
        "src": "https://si.wsj.net/public/resources/images/OJ-AN646_CPHONE_E_20160809235652.jpg",
        "width": -1,
        "height": -1
      },
      "contentType": "img",
      "title": "Pending",
      "resolvedTargetUrl": null,
      "foundTs": 1470837700401,
      "targetUrl": "http://www.wsj.com/articles/for-chinas-hottest-phone-maker-the-old-ways-work-1470812857",
      "pageTitle": "The Wall Street Journal & Breaking News, Business, Financial and Economic News, World News and Video",
      "pageUrl": "http://www.wsj.com/asia",
      "errors": null,
      "pageDomain": "www.wsj.com",
      "version": "2.3.2"
    },
    "www.wsj.com::-1::https://si.wsj.net/public/resources/images/BN-PH829_CNAVY0_Z120_20160809101247.jpg::-1": {
      "id": 2,
      "attempts": 0,
      "visitedTs": 0,
      "attemptedTs": 0,
      "current": true,
      "contentData": {
        "src": "https://si.wsj.net/public/resources/images/BN-PH829_CNAVY0_Z120_20160809101247.jpg",
        "width": -1,
        "height": -1
      },
      "contentType": "img",
      "title": "Pending",
      "resolvedTargetUrl": null,
      "foundTs": 1470837700402,
      "targetUrl": "http://www.wsj.com/articles/chinas-south-china-sea-moves-draw-ire-of-u-s-pacific-fleet-chief-1470762489",
      "pageTitle": "The Wall Street Journal & Breaking News, Business, Financial and Economic News, World News and Video",
      "pageUrl": "http://www.wsj.com/asia",
      "errors": null,
      "pageDomain": "www.wsj.com",
      "version": "2.3.2"
    }
}
```

**Comment by dhowe** [comment]
You should have been able to figure this out, given the nonsensical results.

We may need to ignore ads who's targets are in the same domain. 

Next we need to figure out why 'EasyList-only' finds less ads than 'Very Easy Mode'. Are you including 'AdNauseam filters' in both, or just the latter?

**Comment by CyrusSUEN** [comment]
> Are you including 'AdNauseam filters' in both, or just the latter?

'AdNauseam filters' were included in both profiles.
According to the definition of [very easy mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-very-easy-mode), it is a super set of Easy List only plus uBlock filters. (and I have 'AdNauseam filters' enabled for both).

**Comment by CyrusSUEN** [comment]
> We may need to ignore ads who's targets are in the same domain.

After adding this option, I believe the hard mode will score the fewest number of ads collected if not 0.

**Comment by dhowe** [comment]
So why does 'EasyList-only', which blocks nothing, find less ads than 'Very Easy Mode' which blocks some 3rd-parties?

**Comment by CyrusSUEN** [comment]
> So why does 'EasyList-only', which blocks nothing, find less ads than 'Very Easy Mode' which blocks some 3rd-parties?

The number of them were actually quite similar. 
After comparing the spredsheet I found that the following 2 sites made quite a difference between EasyList Only and Very Easy Mode:
`
http://www.tmz.com/
http://www.games.com/
`

Very Easy:
![image](https://cloud.githubusercontent.com/assets/2461812/17562629/3107eac8-5f5e-11e6-9491-96cb9650bc2f.png)
![image](https://cloud.githubusercontent.com/assets/2461812/17562596/15f25e3a-5f5e-11e6-9adf-cec991c866ca.png)

EasyList Only:
![image](https://cloud.githubusercontent.com/assets/2461812/17562643/3ff77fda-5f5e-11e6-9d8e-e409f8398c94.png)
![image](https://cloud.githubusercontent.com/assets/2461812/17562650/479b7bb0-5f5e-11e6-8ff1-cc5970dbc1d9.png)

Very Easy detected more ads with the help of uBlock filters.

**Comment by dhowe** [comment]
once I've made live the fix to ignore internal ad links, we will need to run the tests again, and post the final results here

**Comment by dhowe** [comment]
And is it possible to run this same tests against no-blocker, ublock,and abp, each with default settings, as we did with page-load times?

**Comment by CyrusSUEN** [comment]
> once I've made live the fix to ignore internal ad links, we will need to run the tests again

Yes, sure!

> And is it possible to run this same tests against no-blocker, ublock,and abp, each with default settings, as we did with page-load times?

Has it been fixed? Because for a fair comparison (as those ads and 3rd party connections change and the websites themselves change over time) I need to run ADN test along with newly-added test

**Comment by dhowe** [comment]
Yes, you can do the test now with 3055809df
Please re-run the test with no-blocker, ublock,and abp, each with default settings

**Comment by CyrusSUEN** [comment]
> test now with 3055809
> Please re-run the test with no-blocker, ublock,and abp, each with default settings

Updated:
![1](https://cloud.githubusercontent.com/assets/2461812/17649550/d4ef919a-626a-11e6-9989-d4a4a1af1864.PNG)

![2](https://cloud.githubusercontent.com/assets/2461812/17649555/f28a2710-626a-11e6-9e15-7d331a0b1268.PNG)

I cannot upload zip files to Github now. Uploaded the full log to Google Drive:
https://drive.google.com/file/d/0BzHBWuszZv5_Ry1rUkFUYnN6MkU/view?usp=sharing

**Comment by dhowe** [comment]
1.  run the test with 3rd-party test with no-blocker, adnauseam, ublock, and abp; each with default settings, and include no other results
2. the number of ads collected in 'hard' mode is still totally wrong -- please investigate

**Comment by CyrusSUEN** [comment]
> number of ads collected in 'hard' mode is still totally wrong -- please investigate

It is still the same. Most of the ads found in hard mode are actually false-positive
https://github.com/dhowe/AdNauseam/issues/321#issuecomment-238894899

This is the exported JSON in hard mode:
https://drive.google.com/file/d/0BzHBWuszZv5_SFRuckRXV203MDg/view?usp=sharing

**Comment by CyrusSUEN** [comment]
> Test 1: run the 3rd-party test with ONLY no-blocker, adnauseam, ublock, and abp; each with default settings

![number of 3rd-party hit](https://cloud.githubusercontent.com/assets/2461812/17669652/082b21d8-6341-11e6-893d-71891d78e29e.png)

See the log here: https://github.com/dhowe/AdNauseam/pull/350

**Comment by dhowe** [comment]
This seems much worse than the prior runs -- why are we doing worse than ABP now?

**Comment by CyrusSUEN** [comment]
> why are we doing worse than ABP now?

Compared to the Easy mode, AdNauseam has no `Peter Lowe’s Ad server list‎`.
I'm re-running this part of the test again and adding an extra one using `Peter Lowe’s Ad server list‎` for comparison.

**Comment by dhowe** [comment]
This is highly unlikely to change anything as 'Peter Lowe’s Ad server list‎' is not included in our enabledBlockLists

**Comment by CyrusSUEN** [comment]
For this test all extensions and browsers settings are default.

![untitled](https://cloud.githubusercontent.com/assets/2461812/17724958/37981ae6-6479-11e6-9921-72b3816c914b.png)
So I've rerun the test with extra profiles.

On ADN Easy mode (and other mode) there is a settings that we should `disable 3rd party cookies` in Chrome browser settings which is the big difference and caused the difference and the number reduced to 930 from 1323.

**Comment by dhowe** [comment]
see #359
