### ISSUE TITLE
Ad showing on homepage of youtube

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#322]
https://www.youtube.com/

Not there when using vanilla ublock

![screen shot 2016-08-02 at 11 07 31 am](https://cloud.githubusercontent.com/assets/737638/17333964/83dddc8e-58a2-11e6-82a2-79027fec6153.png)

**Comment by dhowe** [comment]
Another one:

![youtube-fail](https://cloud.githubusercontent.com/assets/737638/17454984/07fbcb2a-5b78-11e6-8b47-392f8a99fed7.png)

**Comment by CyrusSUEN** [comment]
Can I have your ADN settings? (perhaps we need to reimplement uBlock's import / export settings along with ADN's settings)

I'm using ADN at build f6007d339b34b283c8fffbbb4b5713f2d25ab022 with default settings. The ads were gone.
![1](https://cloud.githubusercontent.com/assets/2461812/17455873/e5b74528-5bf7-11e6-84d0-c71cad6b966b.PNG)
After pausing ADN and I can see the ad.
![2](https://cloud.githubusercontent.com/assets/2461812/17455880/078ad764-5bf8-11e6-9645-3bde09d154f1.PNG)

**Comment by dhowe** [comment]
on hold until we have another case
