### ISSUE TITLE
Research Cost-Per-Click that advertisers actually pay

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#323]
http://www.wordstream.com/blog/ws/2015/05/21/how-much-does-adwords-cost

"The average cost per click in Google AdWords is between $1 and $2 on the search network. The average CPC on the Display Network is under $1. The most expensive keywords in AdWords and Bing Ads cost $50 or more per click."

![adwords-industry-benchmarks-average-cpc](https://cloud.githubusercontent.com/assets/737638/17335093/bf131ff4-58a6-11e6-87c3-193b0f1a9626.jpg)

from: http://www.wordstream.com/blog/ws/2016/02/29/google-adwords-industry-benchmarks

**Comment by leoneckert** [comment]
reading into all this, found this interesting https://support.google.com/adsense/answer/1348752?hl=en and wonder if our clicks are caught by this
