### ISSUE TITLE
First Run options should be off by default

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#325]
The options are:
- [ ] Hide Ads*
- [ ] Click Ads*
- [ ] Block Malware

*non-tracking ads are excluded (gear)

The * next to the options and the note under them appears only after activating one of them. The gear icon links to the settings.

@mushon add the option and @dhowe will hook the JS functionality

**Comment by dhowe** [comment]
Might also take a look at PB's firstrun page: 
![pg](https://cloud.githubusercontent.com/assets/737638/17381672/100fad88-599b-11e6-9256-3139bf8ec792.jpg)

**Comment by mushon** [comment]
Here's how I think it should work:
As soon as we toggle HIDE ADS or CLICK ADS, the DNT exception should appear as a checkbox (default: checked). Like this:
![image](https://cloud.githubusercontent.com/assets/27123/17674835/e6d31556-632f-11e6-8331-30586b6ae739.png)
@dhowe @hfn1 your thoughts

**Comment by hfn1** [comment]
I like that, particularly if it doesn’t involve too much difficulty or instability.

Helen Nissenbaum, Professor
Media, Culture, & Communication, NYU
http://www.nyu.edu/projects/nissenbaum

**Comment by mushon** [comment]
Cool, thanks.
And yes we actually have some people from EFF who will be working on this with us defining a whitelist for DNT respecting domains based on the work they do in Privacy Badger. So as soon as we have that implementing it should be pretty straight forward.

I like that, particularly if it doesn’t involve too much difficulty or instability.

Helen Nissenbaum, Professor
Media, Culture, & Communication, NYU
http://www.nyu.edu/projects/nissenbaum

**Comment by dhowe** [comment]
We will need to consider a range of options here, some of which may override the browser's settings. For example, ADN should (by default, I would argue) do some sensible things to protect users from trackers and malware, none of which interfere with our ability to collect and visit ads:

1. Replace auto-playing flash with click-to-play versions
2. Replace 3rd-party buttons that track with non-tracking versions
3. Block 3rd-party cookies (which may not be checked in the browser)
4. Send the DNT-header when 'allow non-tracking ads' is checked (it may not be checked in the browser)

**Comment by mushon** [comment]
I generally agree, but we should document this well and also consider that 3rd party buttons sometimes have extra features that are not supported by non-tracking buttons (like tweet count on Twitter buttons)

**Comment by dhowe** [comment]
I think its important we always let users know what we are going to do on their behalf (and the first-run page seems a good place for this). We might have a note or popup on install that says, 'ADN is setting up your browser to do the following' (then the numbered items above). Perhaps even an animation showing the browser's 3rd-party cookies and DNT header options being toggled on, and/or a social-media icon being swapped out ...

**Comment by mushon** [comment]
@mushon would figure out the right wording for the BLOCK MALWARE subheading with a link to the 3rd party settings page (or something)

**Comment by mushon** [comment]
how about:
``optimizes your browser settings to protect from malware and other non-visual trackers (customize)``
with the ``customize`` being a link to the settings:
![image](https://cloud.githubusercontent.com/assets/27123/18433920/dab29dae-78f2-11e6-9299-2aca961f8b13.png)

**Comment by hfn1** [comment]
This looks good to me!

Helen Nissenbaum, Professor
Media, Culture, & Communication, NYU
http://www.nyu.edu/projects/nissenbaum

**Comment by dhowe** [comment]
I would prefer:
```
hide ads in your selected [filter lists]
register visits on ads found via your [filter lists]
optimize your settings to protect you from malware and other non-visual trackers [customize]
```
