### ISSUE TITLE
Ad appears on ADN, not on uBlock

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#331]
This ad:
<img width="1195" alt="screen shot 2016-08-07 at 10 12 50 am" src="https://cloud.githubusercontent.com/assets/27123/17461067/a99a2778-5c87-11e6-984b-77bb7f98af7b.png">
appears on this page load:
http://www.haaretz.co.il/opinions/editorial-articles/1.3030617
It covers the page and then disappears after a few seconds (it's that annoying type)

This does not happen in uBlock.
Both tested with ``ISR: EasyList Hebrew‎``

here we can see it blocked by uBlock:
![image](https://cloud.githubusercontent.com/assets/27123/17461094/8321af8e-5c88-11e6-92e6-4e04cd09e3a1.png)

And not blocked by ADN:
![image](https://cloud.githubusercontent.com/assets/27123/17461098/97684b38-5c88-11e6-99de-31f27697dfdc.png)

**Comment by dhowe** [comment]
the rule in question is from easylist; @CyrusSUEN can you check whether any of the blocking rules in this list block ads...

**Comment by mushon** [comment]
Your rule didn't work, but I followed your guidelines to add one that would.
Are there more specific guidelines and repercussions for adding wider rules? ones that would work across sites?

**Comment by dhowe** [comment]
see https://adblockplus.org/filter-cheatsheet
though actually  your rule _will_ work across multiple sites, which might not be a good thing
as I commented in the commit:

_we might want to add the domain here, as this could collide with actual content_

**Comment by dhowe** [comment]
👍

**Comment by dhowe** [comment]
I've moved the notes above to the Developer FAQ on the wiki...
