### ISSUE TITLE
Manual tests for reddit.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#338]
1. Visit https://www.reddit.com/ and count ads manually 
2. Visit with ADN default (check ads found against 1.)
3. Visit with ADN with hiding disabled (make sure ads reappear and check ads found against 1.)

Note results here

**Comment by CyrusSUEN** [comment]
> Visit https://www.reddit.com/ and count ads manually

3 ads counted manually and 2 of them are in house ads (except the Google ads)

> Visit with ADN default (check ads found against 1.)

5 ads collected

> Visit with ADN with hiding disabled (make sure ads reappear and check ads found against 1.)

Yes. I can see the ads with hiding disabled and the ad count drop to 3 from 5

**Comment by dhowe** [comment]
closing for now
