### ISSUE TITLE
Text ads showing on yahoo

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#339]
Please recheck all [text-ad filters](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/textads.js#L230)

https://search.yahoo.com/yhs/search?p=watch&ei=UTF-8&hspart=mozilla&hsimp=yhs-001

![screen shot 2016-08-10 at 1 03 31 pm](https://cloud.githubusercontent.com/assets/737638/17562893/ed6880d8-5efa-11e6-80fd-52dabd5ae6b5.png)

AND

https://search.yahoo.com/search;_ylt=AobuKuzXeLt1BfpCsufHm7ibvZx4?p=watch&toggle=1&cop=mss&ei=UTF-8&fr=yfp-t-334&fp=1

![screen shot 2016-08-10 at 1 07 45 pm](https://cloud.githubusercontent.com/assets/737638/17563028/7fd437e6-5efb-11e6-935d-e4975685df04.png)

**Comment by CyrusSUEN** [comment]
I'm at build 0efa2a309fecde44af889d6572a748e9d15364c6 with default settings and Yahoo Search works perfectly.

Also tested:
http://search.aol.com/aol/search?s_chn=prt_dol-g&q=loan&s_it=comsearch-simple
https://duckduckgo.com/?q=loan&t=he&ia=meanings
http://www.ask.com/web?q=credit+card&qsrc=0&o=0&l=dir&qo=homepageSearchBox
https://www.google.com.hk/search?q=credit+card&oq=credit+card&aqs=chrome..69i57j0l5.3553j0j7&sourceid=chrome&ie=UTF-8 (I saw double 'Related Search' sessions on ask.com but it is actually normal after comparing it with ADN disabled)
http://www.bing.com/search?q=watch&go=Search&qs=n&form=QBRE&pq=watch&sc=8-5&sp=-1&sk=&cvid=16896092B9FA4B9A85FF74C7642BDBDE

And they are all good except that on Duckduckgo it failed to collect the related text ad.

**Comment by dhowe** [comment]
Also, there is too much text for these text-ads (at least for the current design) -- @mushon can you help address this?

![screen shot 2016-08-10 at 2 31 37 pm](https://cloud.githubusercontent.com/assets/737638/17565961/811fa2c8-5f07-11e6-9c57-57e775d01406.png)

**Comment by CyrusSUEN** [comment]
OK. Closing this for now because the remaining duckduckgo problem is a legacy issue: https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/textads.js#L149
