### ISSUE TITLE
Find uBlock or ABP list of trackers

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#34]
We need a uBlock or ABP ad-blocking list containing ONLY(invisible) trackers, with no visual ads.

**Comment by CyrusSUEN** [comment]
Found 3 from uBlock's builtin filter list
https://www.fanboy.co.nz/enhancedstats.txt
https://easylist-downloads.adblockplus.org/easyprivacy.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt

2 Websites for doing tracker test (But It always shows "Invalid domain. Please check your config settings." when I press the "test me" button)
https://do-not-tracker.org
https://trackersimulator.org

2 privacy check websites
http://ipinfo.info/html/privacy-check.php
http://analyze.privacy.net/Default.asp

**Comment by dhowe** [comment]
Can we verify that there are no ads in these?

**Comment by CyrusSUEN** [comment]
Just the second list, Easyprivacy, is enabled by default in uBlock.

The first and second list block visible ads. Not pure tracker lists.

The 3rd one is originally from an extension called Disconnect. 
It does not block visible ads. (at least not blocking the visible ads on us.yahoo.com and nytimes.com)
Also found a database from Disconnect that gets regular updated.
https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json
But I cannot verify if it only blocks visible ads.
Also tried Disconnect extension myself, it keeps blocking visible ads even I unchecked blocking Advertising from its menu.

Ghostery is another extension to prevent online trackers. It handles the trackers so well that I can configure it to only block invisible trackers. 

Ghostery is not hosted on Github but I've found the [direct download link](https://clients2.google.com/service/update2/crx?response=redirect&x=id%3Dmlomiejdfkolichcflejclcbmpeaniij%26uc&prodversion=32)

And found the following message from the source code:

> This proprietary database is protected by copyright, and is owned exclusively by Ghostery and all rights to it are expressly reserved. **If you are interested in using this database for any purpose outside of the Ghostery application, contact Ghostery at info@ghostery.com. Ghostery may grant permission to use our proprietary database as determined in our sole discretion**. Unauthorized use of this proprietary database, or any portion of it, may result in legal proceedings against you, seeking monetary damages and an injunction against you, including the payment of legal fees and costs.

**Comment by dhowe** [comment]
@cyrus please return to this issue. We need one uBlock compatible list that ONLY blocks trackers, NOT visual ads

**Comment by CyrusSUEN** [comment]
Emailed Ghostery for its tracker list.

------------------------
We can also compare the following EasyList and EasyPrivacy lists line by line to make the list.
https://easylist-downloads.adblockplus.org/easylist.txt
https://easylist-downloads.adblockplus.org/easyprivacy.txt

If there are identical lines both lists, remove the lines from EasyPrivacy since EasyList is supposed to be a list for visible ads.

**Comment by CyrusSUEN** [comment]
Ghostery rejected.

EasyList and EasyPrivacy basically have no intersections. 

After some testing I found that the original EasyPrivacy list minus or comment out the following rules can be a viable tracker filter list without affecting the visible ads:
```
||googleadservices.com^$third-party
||pixanalytics.com^$third-party
||stats.g.doubleclick.net^
```

**Comment by dhowe** [comment]
Lastly, can you check if any of the following malware lists block ads:

uBlock filters – Badware risks‎
Anti-Adblock Killer | Reek‎
Adblock Warning Removal List‎
Malware Domain List‎
Malware domains‎
Malware domains (long-lived)‎
Anti-ThirdpartySocial 
Fanboy’s Social Blocking List‎

**Comment by CyrusSUEN** [comment]
These all are safe and they do not block visible ads except maybe the last 2 filters.

**uBlock filters – Badware risks**
Blocks only 4 websites delivering malware.

**Anti-Adblock Killer | Reek‎
Adblock Warning Removal List‎**
The first one detects and disables those website countering ad blocking features.
The second is to remove some warning messages when ad blockers are detected on certain websites. 


**Malware Domain List‎
Malware domains‎
Malware domains (long-lived)‎**
These redirect malware domain URLs to localhost. They have no effect on individual ads but block the whole website.

**Anti-ThirdpartySocial 
Fanboy’s Social Blocking List‎**
These remove Facebook, twitter buttons on 3rd parties websites. 
For example the Fanboy’s Social Blocking List‎ removes the Twitter button on http://rednoise.org/rita
![capture](https://cloud.githubusercontent.com/assets/2461812/15393413/b23eaeba-1dff-11e6-9fbb-04a6108b6cfb.PNG)
The last 2 filters will have a big visual and functional impact on websites implementing Facebook comment API and other features such as "Like", "Share on Facebook".

**Comment by dhowe** [comment]
Ok, we will leave those off by default, and turn on ONLY:

     Malware Domain List‎ (malwaredomainlist.com)
     Malware domains‎ (www.malwaredomains.com)

as these are enabled by default in uBlock.

Please also check these last two (also enabled by default):

     uBlock filters – Privacy‎ : 25 used out of 25
     uBlock filters – Unbreak‎ : 99 used out of 100PURGE CACHE

**Comment by CyrusSUEN** [comment]
uBlock filters – Unbreak is used only to unbreak websites by fixing other filter lists and should be enabled.

uBlock filters – Privacy‎ is another privacy filter list.
But the following rule blocks many visible Google ads. (e.g. on http://nytimes.com, http://www.theverge.com)
```
||googletagservices.com/tag/js/gpt.js$script,redirect=googletagservices.com/gpt.js
```

**Comment by dhowe** [comment]
can we verify that only those 2 rules will cause problems?

**Comment by CyrusSUEN** [comment]
> can we verify that only those 2 rules will cause problems?

Yes. I've ran through a list of websites from ZoHo spreadsheet.

**Comment by dhowe** [comment]
implemented
