### ISSUE TITLE
Text-ads bounds incorrect

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#342]
URL for text-ads with large amounts of text extending past bounds...

From: https://www.bing.com/search?q=watch&PC=U316&FORM=CHROMN

Not sure if we want so much text in the body as well (perhaps ellipses for both?)

![screen shot 2016-08-10 at 2 31 37 pm](https://cloud.githubusercontent.com/assets/737638/17565961/811fa2c8-5f07-11e6-9c57-57e775d01406.png)

**Comment by mushon** [comment]
fixed in https://github.com/dhowe/AdNauseam/commit/ecb6afe6f69be8c21615d7f234f7c6385a889dac please check

**Comment by CyrusSUEN** [comment]
Fix verified. Closing.
