### ISSUE TITLE
Metrics for page-load times

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#343]
adnauseam compared to nothing, adblock plus, ublock, all with default configurations

**Comment by CyrusSUEN** [comment]
I've done the test once and this is the result::
![page load test](https://cloud.githubusercontent.com/assets/2461812/17594961/b9e04790-601d-11e6-880e-cc7a1eaa12c1.png)

However it could be done multiple times for each profile setting to minimize the variance between each test and there is actually a [cache mechanism](https://github.com/gorhill/uBlock/wiki/Cosmetic-filtering-in-%C2%B5Block:-version-0.4.0.0-update) starting at 0.4.0 which reduces the time of loading / applying the cosmetic filters when re-visiting a site. 

attached the full log here:
[page load test.xlsx](https://github.com/dhowe/AdNauseam/files/413612/page.load.test.xlsx)

**Comment by dhowe** [comment]
I'm curious whats happening with yahoo, where we are slowest... can you check into this?

**Comment by CyrusSUEN** [comment]
> whats happening with yahoo (where we are slowest)... can you check into this?

I've just re-run the test on Yahoo news. I don't think it is good for testing because it always feeds different news articles on different browsers (profiles). I can hardly get the same content in no blocker, ABP and ADN profiles. 

I cleared browser cache before each run and this is one of the results:
no blocker:  8.54s
ADN: 8.6s
ABP: 10.1s

Yahoo News feeds webp format pictures on Chrome browsers and the delivery time of the pictures is not so steady which I believe should be the biggest variance between each run.

**Comment by dhowe** [comment]
Lets substitute this [url](https://search.yahoo.com/search?p=watch) for the yahoo above, as this will also test if there are performance issues with text-ad parsing...

**Comment by CyrusSUEN** [comment]
> substitute this url for the yahoo above

![image](https://cloud.githubusercontent.com/assets/2461812/17647921/377569a4-6237-11e6-93fe-89f7a68f1bed.png)

Updated chart (only updated the Yahoo entry):
![load time](https://cloud.githubusercontent.com/assets/2461812/17647926/6370143c-6237-11e6-8d20-b8ee5fda98c9.png)

[page load test 2.xlsx](https://github.com/dhowe/AdNauseam/files/416931/page.load.test.2.xlsx)

**Comment by CyrusSUEN** [comment]
> test if there are performance issues with text-ad parsing

There is no performance problem at least it is not shown by the page load time nor causing any stuttering to the browser. 

But ADN cannot capture any text ads on Yahoo Search on my old profile.
Captured only 8 img ads:
![old profile](https://cloud.githubusercontent.com/assets/2461812/17648018/460ab174-623a-11e6-81cd-107e8117e9f4.PNG)

Captured text ads in addition to the 8 img ads in a new profile:
![new profile](https://cloud.githubusercontent.com/assets/2461812/17648022/5865ef82-623a-11e6-9866-c295ba9fe093.PNG)

The same situation happens on my Mac and PC on Chrome 52.

**Comment by dhowe** [comment]
Test again please

**Comment by CyrusSUEN** [comment]
Updated:
![page load time](https://cloud.githubusercontent.com/assets/2461812/17669474/5ce6af0e-6340-11e6-91bd-1dc509302840.png)

the test log is in a PR: https://github.com/dhowe/AdNauseam/pull/350

**Comment by dhowe** [comment]
Please fix the spelling for 'Privacy Badger'

**Comment by CyrusSUEN** [comment]
Updated 
Use the default extension settings for  Privacy Badger (and the others). Only updated their filter lists (if applicable) to the latest before the benchmark.

**Comment by dhowe** [comment]
pls include the updated image here

**Comment by CyrusSUEN** [comment]
![untitled](https://cloud.githubusercontent.com/assets/2461812/17781172/cfeae4ea-65a0-11e6-94b7-7ce99f92c0df.png)

Here is the full log: https://drive.google.com/file/d/0BzHBWuszZv5_YlI1Wk1YS29OY2c/view?usp=sharing (I still cannot upload zip files to github.com)

**Comment by dhowe** [comment]
Please fix the spelling for 'Privacy Badger'

**Comment by CyrusSUEN** [comment]
Sorry about that and updated:
![image](https://cloud.githubusercontent.com/assets/2461812/17817786/dbf5d240-6672-11e6-854e-b3463c0cfc59.png)

https://drive.google.com/file/d/0BzHBWuszZv5_TzZqY190RVloMk0/view?usp=sharing

**Comment by dhowe** [comment]
Why would allowing or blocking 3rd-party cookies change the number of 3rd-party servers hit? Whether or not a cookie is accepted should not affect whether we contact other 3rd-parties in the future... (or am I missing something?)

**Comment by dhowe** [comment]
see #359
