### ISSUE TITLE
Create a FAQ entry for "How do we estimate click cost?"

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#344]
We are currently using a flat value of $1.58 per ad, as discussed in the tickets below...

Create the FAQ entry as a comment below (in the same markdown style as the other FAQ entries), so that it can first be checked, before going live...

Relevant tickets:
   https://github.com/dhowe/AdNauseam/issues/323
   https://github.com/dhowe/AdNauseam/issues/296

**Comment by mushon** [comment]
and then link to it to the ``?`` next to the cost in the menu and the vault

**Comment by leoneckert** [comment]
how about something along these lines? 

### How do we estimate click cost?

[Pay-per-Click (PPC)](https://en.wikipedia.org/wiki/Pay_per_click) is a common internet advertising model in which advertisers pay for each individual click on one of their ads appearing on a website. 
The cost involved varies widely depending on the type of website the Ad appears on; as a generalisation it can be distinguished between 'search websites' where corresponding ads appear based on the user's query, and 'display websites'. The former is more effective and costs are commonly calculated on the spot through a biding system. Pages might use fixed prices or even different models altogether). The content of the Ad also matters. Depending on these factors, costs per click range from below 1$ to over $50. 
As the precise cost generated by clicks is not visible to the client, **AdNauseam calculates an estimate using an average value of $1.58**. The value is taken from this [analysis](https://www.hochmanconsultants.com/cost-of-ppc-advertising/) in which various advertising models and platforms are taken into account.

**Comment by dhowe** [comment]
Looks good. Can we add some reference links, both to a) where our numbers come from and b) where to go for more info ? Also see #494

**Comment by leoneckert** [comment]
updated above comment

**Comment by leoneckert** [comment]
should I add this to the FAQ and link the "?" ?

**Comment by dhowe** [comment]
I made a couple of small tweaks. Please add to FAQ (the question is already there) and link to question-marks in vault and menu!
