### ISSUE TITLE
Metrics for memory-usage

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#347]
Do we have an automated way to run these? (for no-blocker, ublock, abp, adn only)

![mem-usage-overall-chart-20141224](https://cloud.githubusercontent.com/assets/737638/17644982/0cff3870-6166-11e6-8a7c-6d91ee9b2b45.png)

**Comment by CyrusSUEN** [comment]
We don't have one currently.

Even if we want to manually conduct the test on Chrome it will be difficult because there is no more `chrome://memory/` page to check its memory usage in Chrome browsers.

**Comment by dhowe** [comment]
What about the tests in /AdNauseam/doc/benchmarks, 
like:

![mem-usage-20141223-before](https://cloud.githubusercontent.com/assets/737638/17653283/f020cd9e-6260-11e6-9e03-87199ba46815.png)

**Comment by CyrusSUEN** [comment]
> What about the tests in /AdNauseam/doc/benchmarks,

Yes. We can still access Task manager and check the memory usage. But the easiest way to check it was to look for `chrome://memory` page which was removed by Google https://bugs.chromium.org/p/chromium/issues/detail?id=588790

I've captured and sumed up the memory usage of the Chrome's Task Manager in the PR: https://github.com/dhowe/AdNauseam/pull/350

![memory usage](https://cloud.githubusercontent.com/assets/2461812/17669621/e832fc5c-6340-11e6-8d4a-b123dd517456.png)

**Comment by dhowe** [comment]
Can we figure out where the largest memory allocations are coming from?

**Comment by CyrusSUEN** [comment]
I've updated the spreadsheet which now includes the detailed memory usage

![image](https://cloud.githubusercontent.com/assets/2461812/17700250/9619dc62-63f7-11e6-9cd1-436c6b43d7c4.png)


For AdNauseam Adobe Flash is the problem which caused over 419MB of RAM usage and the GPU Process caused 150MB.
![image](https://cloud.githubusercontent.com/assets/2461812/17700312/d6d479ce-63f7-11e6-9d55-38e1d6400a8a.png)
![image](https://cloud.githubusercontent.com/assets/2461812/17700414/3073055e-63f8-11e6-8c81-948418d45f5c.png)

On uBlock Origin there was no Adobe Flash process and the GPU process only caused 58MB
![image](https://cloud.githubusercontent.com/assets/2461812/17700448/5643ea82-63f8-11e6-9028-e61fc6fe6c06.png)

I think the relatively high GPU process is related to Adobe Flash content. And if we could get rid of Flash process I think ADN will reduce the memory usage by 500MB in this benchmark.

**Comment by dhowe** [comment]
That is certainly one problem. Flash should be click-to-play by default. See this ticket: #319,
and start investigating how it can be done

**Comment by dhowe** [comment]
see #359
