### ISSUE TITLE
10tv.nana10.co.il : case for unblocked content

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#348]
On ADN video ad appears before video even though it doesn't on uBlock
http://10tv.nana10.co.il/Category/?CategoryID=600339

used default lists + ISR: EasyList Hebrew‎

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/372

**Comment by dhowe** [comment]
@leoneckert please verify that this ad no longer appears

**Comment by leoneckert** [comment]
verified
