### ISSUE TITLE
Updating filter lists voids 3 rules in AdNauseam filters

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam#349]
Press 'Update Now' in the page will void 3 rules in AdNauseam filters, see the following screenshot which shows 13 used of 16:
 
![screen shot 2016-08-14 at 5 40 28 pm](https://cloud.githubusercontent.com/assets/2461812/17648404/85126612-6246-11e6-8bab-35cf80f53885.png)

Unless I do a 'Purge all cache' and 'Apply', 3 of the Yahoo rules in AdNauseam filters cannot be used.
But doing so will also revert other filter lists to older versions.

**Comment by dhowe** [comment]
Doesn't that just mean that the rule is duplicated?
