### ISSUE TITLE
Disable 3rd-party cookies on install

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#353]
We should consider this as an addition to the first-run screen (perhaps as a note under 'block malware')? 

Also, see #319...

**Comment by dhowe** [comment]
This is implemented, waiting on design of first-run page...

**Comment by dhowe** [comment]
opt-in or opt-out ?

**Comment by mushon** [comment]
We've decided to go for opt-out and will allow customization of the settings through a link. This issue is referred to in #325

**Comment by dhowe** [comment]
closing for now, but may need to revisit...
