### ISSUE TITLE
Font/CSS problems in Firefox

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#357]
![screen shot 2016-08-22 at 12 46 24 am](https://cloud.githubusercontent.com/assets/737638/17843945/fa5ca46c-6801-11e6-9f6a-5315294bbff3.jpg)

**Comment by mushon** [comment]
I'm having problems running the Firefox build
``JPM [error] No Firefox binary found at null
JPM [error] Error: spawn /Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox-bin ENOENT``
Any help will be appreciated towards me addressing the Firefox bugs

**Comment by dhowe** [comment]
Seems that '/tools/run-ff.sh' expects your firefox binary to be at:

  `/Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox-bin`

If its somewhere else (which it appears to be in your case) you need to change the FIREFOX_BIN variable at the top of /tools/run-ff.sh (or just install the developer edition)

**Comment by mushon** [comment]
ok, fixed it by installing the dev edition.
+ also fixed that stupid bug
