### ISSUE TITLE
Missing button labels on Firefox extensions page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#358]
![screen shot 2016-08-22 at 12 48 40 am](https://cloud.githubusercontent.com/assets/737638/17843973/5a6aa9d0-6802-11e6-820a-2216ad83cee3.jpg)

**Comment by CyrusSUEN** [comment]
The initial finding is that when both uBlock Origin and AdNauseam are installed, clicking on the same option buttons from uBlock Origin page will open the corresponding option / logger page for AdNauseam.

**Comment by dhowe** [comment]
This is irrelevant -- simply install adn from source on Firefox and notice that the buttons are blank.
Please verify

**Comment by dhowe** [comment]
![screen shot 2016-08-24 at 12 27 51 pm](https://cloud.githubusercontent.com/assets/737638/17939053/c16c3ff4-69f6-11e6-9f1a-97f2bcadbd73.jpg)

**Comment by cqx931** [comment]
caused by wrong addonId name in vapi-background.js   
fixed with https://github.com/dhowe/AdNauseam/pull/378
