### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#359]
### Metrics
- Number of 3rd-parties contacted
- Overall memory footprint (MB)
- Total page load time (sec)
### Extensions
- No Blocker
- AdNauseam
- Adblock Plus
- uBlock Origin
- Privacy Badger (untrained)
- Privacy Badger (trained)
### Settings
- Horizontal bar graphs, using the order of extensions above
- All extensions using default settings and updated with the latest filter lists 
- Extensions are downloaded from Google Chrome Store except AdNauseam is built from source, using the latest commit, unless otherwise specified
- Each extension should installed on and tested with a new Chrome profile with default settings, except that Flash and 3rd party-cookies should be disabled

&nbsp;

**Comment by CyrusSUEN** [comment]
![image](https://cloud.githubusercontent.com/assets/2461812/17902290/464c9e52-6999-11e6-8552-d76e4f9621ad.png)
![image](https://cloud.githubusercontent.com/assets/2461812/17902163/c1db9f9c-6998-11e6-8778-b9c61af1f470.png)
![image](https://cloud.githubusercontent.com/assets/2461812/17901564/87a81adc-6996-11e6-80d1-13cc3fec06bb.png)

PR: https://github.com/dhowe/AdNauseam/pull/360

**Comment by CyrusSUEN** [comment]
New graphcs following the specifications and updated PR:
![image](https://cloud.githubusercontent.com/assets/2461812/17919745/38819624-6a02-11e6-8eae-4d7b734b450d.png)

![image](https://cloud.githubusercontent.com/assets/2461812/17919741/338301da-6a02-11e6-9e73-e394a16de575.png)
![image](https://cloud.githubusercontent.com/assets/2461812/17919748/3dcbddc4-6a02-11e6-9d46-72fd194af0ca.png)

**Comment by CyrusSUEN** [comment]
To generate graphs with the above style in Microsoft Excel:

1. Select the rows / cols of the graph data 
2. In Excel Menu bar select Insert > `2-D Clustered Column` 
3. Double click on the bars of the generated graph to access `Format Data Series` panel
4. In the panel select set `Series Overlap` to `-24%` and `Gap Width` to `100%`
5. Set all the color of the text of the graph to RGB(89, 89, 89)
6. Title of the graph is font Calibri at 16 size

The trickiest part is step 3 and here is a screenshot demostration:
![graph](https://cloud.githubusercontent.com/assets/2461812/17920606/1e281fe0-6a08-11e6-82c8-ee99780c2665.PNG)

**Comment by dhowe** [comment]
Questions pending for @CyrusSUEN

**Comment by CyrusSUEN** [comment]
## Steps for doing all the metrics for AdNauseam:

## Common setup:

* All extensions using default settings and updated with the latest filter lists 
* Extensions are downloaded from Google Chrome Store except AdNauseam is built from [Github repo](https://github.com/dhowe/adnauseam) using the latest build (or unless specified)
* Each extension installed on and tested with individual [Google Chrome browser profile](chrome://settings/createProfile) with default settings

### Doing 3rd-party domain hit test:

1. Install [dhowe/Sessbench extension](https://github.com/dhowe/sessbench) for each browser profile to be tested
2. Open Developer Tools panel of Chrome browser and access the Sessbench tab
3. Copy and paste the following script to run the test
4. After around 50 mins it will finish and paste the result from Sessbench tab to calculate the number of  entries of `3rd-party domains` in the spreadsheet.

Note that for Privacy Badger extension there are trained and untrained results. (Privacy Badger analyzes and stores a list of the 3rd party domains to be blocked in its settings page) 
To do a untrained one, just test it with its out of the box settings. And do it again with the same Privacy Badger profile for a trained result. 

The sessbench script be found here and also in the following spreadsheet:
https://github.com/dhowe/AdNauseam/blob/master/doc/benchmarks/adnauseam/sessbench/sessbench-script.txt

### Doing memory usage test:

1. Have the blocker enabled and each profile properly setup
2. Have only the "new tab" opened and clear all browser data
3. Remove all other browser extensions (except for the required ad blocker for each test)
4. Disable Flash plugins in about://plugins page and then restart Chrome
5. Paste http://news.yahoo.com/ in address bar, wait for page to finish loading
6. Open new tab, paste http://news.google.com/, wait for page to finish loading
7. Open new tab, paste http://www.huffingtonpost.com/, wait for page to finish loading
8. Open new tab, paste http://www.cnn.com/, wait for page to finish loading
9. Open new tab, paste http://www.nytimes.com/, wait for page to finish loading
10. Open new tab, paste http://www.foxnews.com/, wait for page to finish loading
11. Open new tab, paste http://www.nbcnews.com/, wait for page to finish loading
12. Open new tab, paste http://www.dailymail.co.uk/, wait for page to finish loading
13. Open new tab, paste http://www.washingtonpost.com/, wait for page to finish loading
14. Open new tab, paste http://www.theguardian.com/, wait for page to finish loading
15. Open new tab, paste http://news.ycombinator.com/, wait for page to finish loading
16. Leave the browser idle for two minutes
17. Open Google Chrome's Task manager and take a snapshot of it
18. Sum up all the memory usage numbers
19. Open Task Manager of Google Chrome and do a screen capture 
20. Go to http://www.onlineocr.net/ and get the optical charactor result in Microsoft Excel format
21. Format and tidy up the above Excel formatted result manually (or use [regex](https://regex101.com/) to help getting rid of unwanted noise characters)
22. Paste the formatted result into table format into the [spreadsheet](https://github.com/dhowe/AdNauseam/blob/master/doc/benchmarks/adnauseam/AdNauseam-metrics.ods) and generate bar charts from the tables

### Doing page load time test:

1. Have the blocker enabled and each profile properly setup
2. Have only the "new tab" opened and clear all browser data
3. Install 'Page load time' extension (https://chrome.google.com/webstore/detail/page-load-time/fploionmjgeclbkemipmkogoaohcdbig?hl=en)
4. Restart Chrome
5. Copy and paste the above URL and wait for each to finish 
6. Measure the time by 'Page load time' extension
7. Clear browser cache and cookies and then repeat the test 3 times for each ad blockers


The above steps can also be found here in the spreadsheet: https://github.com/dhowe/AdNauseam/blob/master/doc/benchmarks/adnauseam/AdNauseam-metrics.ods

**Comment by dhowe** [comment]
@CyrusSUEN please add the expected amount of time required for each task above

**Comment by cqx931** [comment]
@CyrusSUEN 
Doing 3rd-party domain hit test:
3.Copy and paste the following script to run the test

What is the script here?

**Comment by CyrusSUEN** [comment]
3rd-party domain hit test: 
Total ~1.5 hrs
50 mins for the sessbench to complete and another 30 mins to sort the data
note: if there are some websites failed to load in sessbench, we need to comment it out and it will take another 50mins.

Doing memory usage test:
Total 1.5 hrs
8 mins for each profile and 30 mins to sort the data

Doing page load time test:
Total 1 hr
8 mins for each profile and 5 mins to sort the data

**Comment by CyrusSUEN** [comment]
> the script

https://github.com/dhowe/AdNauseam/blob/master/doc/benchmarks/adnauseam/sessbench/sessbench-script.txt

Here it is.

It is best to first download and checkout the [spreadsheet](https://github.com/dhowe/AdNauseam/blob/master/doc/benchmarks/adnauseam/AdNauseam-metrics.ods) first before doing the test.
