### ISSUE TITLE
Still seeing video ads on YouTube

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#361]
To recreate (hopefully):
1. open YouTube.com
2. click first suggested video
3. ad appears before video

This was detected on ADN ver. 2.3.2
uBlock 1.8.4 did manage to block the ads

**Comment by dhowe** [comment]
Verified. 
We may need to recreate a separate block list for youtube

**Comment by dhowe** [comment]
Note: this is probably worth a separate release, once fixed ***

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/372

**Comment by dhowe** [comment]
@leoneckert please verify that no video ad ever appear on youtube, then close

**Comment by leoneckert** [comment]
verified

**Comment by dhowe** [comment]
@cqx931 please recheck this (@mushon is still seeing ads)

**Comment by cqx931** [comment]
could you please provide the link where you are seeing ads? @mushon

**Comment by dhowe** [comment]
homepage

**Comment by cqx931** [comment]
issue solved when youtube is blocked by domain
