### ISSUE TITLE
SSL cert expired on adnauseam.io

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#362]
![screen shot 2016-08-30 at 9 15 03 pm](https://cloud.githubusercontent.com/assets/737638/18090360/f002dcec-6ef6-11e6-9243-618a2ee6c8bd.png)

**Comment by mushon** [comment]
I started looking into it, but being in a conference and on a flimsy connection I can't manage to get enough time to carry it all the way. There are two recommended ways. One is the [EFF's Certbot](https://certbot.eff.org/) though I couldn't really tell how to make it work for gh-pages. The second one which seems quite stable and popular is Cloudflare's free support for SSL which is [documented specifically for gh-pages here](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/). I was about to go with Cloudflare, but I just can't seem to find the free time online and I'm not sure I'll manage to do that before Monday.

**Comment by dhowe** [comment]
I need to know where our DNS (for adnauseam.io) is handled...

**Comment by mushon** [comment]
AFAIK it is handled in our NameCheap account

**Comment by dhowe** [comment]
![screen shot 2016-09-04 at 9 17 17 pm](https://cloud.githubusercontent.com/assets/737638/18231207/10bb7ff6-72e5-11e6-8ee0-7e548f2f663a.png)

**Comment by mushon** [comment]
![giphy 1](https://cloud.githubusercontent.com/assets/27123/18231349/42d24a12-72c0-11e6-955a-85e17f8ba7a1.gif)

**Comment by dhowe** [comment]
lets get rocking on 2.4
