### ISSUE TITLE
Make adnauseam.txt an external / 3rd-party list

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#366]
this would enable us to fix issues (like #361) without new releases (assuming users auto-update or manually update their lists)

perhaps just host on github

**Comment by dhowe** [comment]
@cqx931 do you want to give this one a try? we would need to host the file on github (probably in my fork of uAssets) then treat it like the other 3rd party lists...

**Comment by cqx931** [comment]
sure, I can try to do this.

**Comment by cqx931** [comment]
Here is the steps I plan to go through to achieve this, please tell me if I miss anything.

In uAsset
1.create a github.com folder in 'thirdparties' folder
2.put adnauseam.txt into it
3.in update-3rdparties.sh add the following line to assets = ( )
['thirdparties/github.com/adnauseam.txt']='https://raw.githubusercontent.com/dhowe/uAssets/master/thirdparties/github.com/adnauseam.txt'

in AdNauseam
4.add the following line to make-assets.sh
cp -R ../uAssets/thirdparties/github.com          $DES/thirdparties/

**Comment by dhowe** [comment]
what about simply including the file in the 'filters' dir?

**Comment by cqx931** [comment]
oh I see... so files in filters folder are hosted from github, whereas those from thirdparties are hosted somewhere else?

**Comment by dhowe** [comment]
i believe so, yes...

**Comment by cqx931** [comment]
So the revised steps:
In uAsset
1.move adnauseam.txt to 'filters' folder
2.in update-ublock0.sh add the following line to filters = ( )
'./filters/adnauseam.txt'
Just like this?

**Comment by dhowe** [comment]
let me work on this for a few more moments

**Comment by dhowe** [comment]
closing for now
