### ISSUE TITLE
Use language detection for pre-activating filters

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#367]
JS can identify languages [like here](http://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference) and we cannot expect users to actually know they need to activate local filters. So we want to turn these filters on by default based on the user's installed languages.

This could actually be a nice contribution back the the uBlock project.

**Comment by cqx931** [comment]
Just want to support this feature from a user feedback on firefox Addon store:
![image](https://cloud.githubusercontent.com/assets/3056154/23407783/8789a3dc-fe00-11e6-93a0-e8853bcf7ad2.png)
According to google translate, the user is complaining that ads are not blocked on mail.ru.
If I turn on all Russian specific filters, the ads on mail.ru do get blocked. But this is hard to know as the whole language section is collapsed by default.

Another option is to let the user to select their "mostly used languages" on the first-run page. (Though my browser is set to English, I also browse a lot in Chinese...)
And the browser language could be preselected with JS detecting.

**Comment by dhowe** [comment]
Would be nice to add a checkbox for the correct language list when a location is detected... @mushon?

**Comment by cqx931** [comment]
uBlock implemented this in 1.11.0, please check [`autoSelectRegionalFilterLists` ](https://github.com/dhowe/AdNauseam/blob/merged1.11.0-2/src/js/storage.js#L436)and [another related case](https://github.com/gorhill/uBlock/issues/2344):

**Comment by dhowe** [comment]
Excellent -- is anything required on our part, or can this be closed?

**Comment by cqx931** [comment]
Tested on Chinese System, and Chinese filter lists are automatically selected when first installed.
This issue can be closed now.
