### ISSUE TITLE
First-run page: DNT exception checkbox should only appear once either 'click' or 'hide' is enabled

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#370]
see firstrun.html and firstrun.js
<img width="557" alt="screen shot 2016-09-06 at 7 30 04 pm" src="https://cloud.githubusercontent.com/assets/737638/18272101/82a25a0c-7468-11e6-8289-173e5b1657e5.png">

this should be checked by default

**Comment by leoneckert** [comment]
solved this but waiting for our call later for best practise pushing to the repo
