### ISSUE TITLE
First-run page options implementation

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#371]
SPECIFICATION: 

- all toggles here (hiding, clicking, malware) should be false by default

- if user enables hiding or blocking, respectDNT checkbox should appear, default enabled (note: this single toggle controls 2 user settings: _disableClicksForDNT_, and _disableHidingForDNT_.

- if user clicks OK or closes the tab while neither hiding or blocking are true, then the respectDNT toggle must be set to false

- if user ever disables respectDNT on the firstrun page, it should remain disabled, even after hiding/clicking are disabled, then reenabled

- the settings page has separate options (under the _hiding_ and _clicking_ headers respectively) for the two settings:  _disableHidingForDNT_ and _disableClicksForDNT_ (see #202 for the design)

**Comment by leoneckert** [comment]
after setting option in firstrun.html, they can be seen (and edited) in ADN's settings page. Only the DNT exception can not be changed afterward, at least I don't see it in the Settings page, is that intended?

**Comment by leoneckert** [comment]
I think the best way of handling (and I guess that's what you were thinking of from the start) is to have it the respectDNT set TRUE by default,  then let the user do with it whatever he wants. Finally, on submitting the setting, I check whether both Hide and Click are disabled, and if so, also force disable respectDNT. That's how I have it now and I think it works this way. will send pull request now.

**Comment by dhowe** [comment]
Looks good -- I made a few minor tweaks in 830552f51ee

Question: does this properly handle the case where the first-run tab is just closed without a confirm?

**Comment by leoneckert** [comment]
Looking at the case of it being closed without hitting "OK". 
Do you mean two check boxes, one for "hide ads", the other for "click ads"? 
Also, I notice the question mark next to "Make exception for non-tracking-ads?" does not work fore me.

**Comment by leoneckert** [comment]
Okay so I fixed closing without "OK" now. For that I went back to having all values False by default -> if window is clicked away directly, they are all false (I checked that by looking in the Setting panel afterwards - let me know if there is a preferred way). 
Then, if the user does switch either Hide or Click, the box not only appears, but also turns True, from there it is down to the user what he does with it, unless both Hide nor Click are False, then respectDNT will always be False, too. 

I could send a pull request right now, but will wait because I think I don't quite understand what you mean in 397, two checkboxes?

**Comment by leoneckert** [comment]
I also just notice that all the "OK" button does, is closing the window. The settings the user changes are saved as it is done... the user can check Hide for example, then close the window without hitting "OK", but the setting will still be set. Is that intended?

**Comment by dhowe** [comment]
'Ok' and closing the window should have the same effect, so you can probably delegate the logic here to the closing event, which should fire in either case

**Comment by leoneckert** [comment]
is this good to close?

**Comment by dhowe** [comment]
No, this code is not in the master branch, and there is no open PR. Resubmit.

**Comment by dhowe** [comment]
Yes, though we will have to revisit when the new settings design lands... @mushon, are you working further on #202?
