### ISSUE TITLE
German translation of locale strings

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#380]
Note: this needs to wait until #379 is finished

@leoneckert can you handle this?

the translation project is [here](https://crowdin.com/project/adnauseam/de#)

**Comment by leoneckert** [comment]
As far as I understand the crowding interface, I am done.

**Comment by dhowe** [comment]
@cqx931 pls go through the crowdin update [process](https://github.com/dhowe/AdNauseam/wiki/Handling-languages,-locales,-and-translations) and verify that these translations are correctly updated and built
