### ISSUE TITLE
Menu zoom goes offscreen to right

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#386]
from #148

_note: extra-low priority_

![screen shot 2016-09-10 at 2 31 31 pm](https://cloud.githubusercontent.com/assets/737638/18408489/9ecb0ff0-7763-11e6-828a-ea0587cc4559.png)

I think we have 3-4 choices here:
* we stop zooming at the right edge of the menu
* we show a horizontal scrollbar when zoom extends past right-edge
* we zoom to the left (from upper-right corner of image, instead of upper-left)
* leave as is

**Comment by dhowe** [comment]
thoughts @mushon @leoneckert

**Comment by mushon** [comment]
Let's go w option one using the CSS max-width property.

**Comment by cqx931** [comment]
the max-width option was actually my first try. 
It just has a limited zooming effect with wide ads.
![screen shot 2016-10-07 at 7 58 37 pm](https://cloud.githubusercontent.com/assets/3056154/19189072/81ab05b8-8cc8-11e6-961e-2c6db5f0eae1.png)

**Comment by mushon** [comment]
For full zoom we should use the vault. Possible (future) enhancement: click to see it focused in the vault.

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/commit/f1caaf7c997cf78dd855f6950221f5ed08640317
