### ISSUE TITLE
Testing of new release candidate

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#387]
Please check the wiki page here for updated documentation: https://github.com/dhowe/AdNauseam/wiki/Testing-New-Release-Candidates

**Comment by dhowe** [comment]
@CyrusSUEN please document, either here or in a wiki entry, the specific steps for testing each of the above items (including any tools used)

**Comment by CyrusSUEN** [comment]
For looking up header infomation I use [Charles](https://www.charlesproxy.com/latest-release/download.do) which is a crossplatform application for web debugging. This should come in handy for checking header-specific options.

As for the list of URLs for text ads, this the list of our text ad detection rules.
https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/textads.js#L231-L261
Usually I will go to their page and search for commonly advertised terms: `credit card`, `loan`

**Comment by cqx931** [comment]
Please check the wiki page here: https://github.com/dhowe/AdNauseam/wiki/Testing-New-Release-Candidate
