### ISSUE TITLE
Add adn-specific data to logger interface

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#389]
Added/augmented log entries:
- [ ] blocks (from adnauseam.txt) 
- [ ] allows (from adnauseam.txt) 
- [x] adn-allows
- [x] DNT-allows (new, in bright green)
- [ ] cosmetic rules that result in a collected ad

Also need to link to FAQ entries for each

**Comment by dhowe** [comment]
@cqx931 can you check into what this would require?

**Comment by cqx931** [comment]
"AdNauseam allow" is implemented here:
https://github.com/dhowe/AdNauseam/issues/966
"Blocks" are already indicated in the logger

**Comment by dhowe** [comment]
We need 
1. to link to the existing rule (in adnauseam.txt) for adn-allowed/purple entries
2. add entries for cosmetic rules that result in a collected ad (in a bright color)

**Comment by cqx931** [comment]
> 1. Entry type for cosmetic rules that result in a collected ad (in a bright color, prob purple)

If we use purple for this, then we need to change adn-allowed to some other color, maybe blue?

> 1. Entry type for DNT-allows (in bright green)

Not sure whether we need this, because there are not many green entries in general, and DNT rules have a special format, which makes it quite obvious that it is DNT-allows
![image](https://user-images.githubusercontent.com/3056154/32339849-591db9f2-bfcf-11e7-8f63-5afb5a3245be.png)
![image](https://user-images.githubusercontent.com/3056154/32339855-5e4ee5d6-bfcf-11e7-8649-5f0d49813cd0.png)

> 1. mouseover linking to FAQ for each adn-entry

It makes sense for me to add FAQ link for DNT-entries, what are other cases for a FAQ entry?

> 1. special color for any rules that match in adnauseam.txt (with link, perhaps a tr outline)

What do you mean by tr outline? Link to where? The content page for adnauseam.txt?

**Comment by dhowe** [comment]
< If we use purple for this, then we need to change adn-allowed to some other color, maybe blue?
good
< Not sure whether we need this, because there are not many green entries in general, and DNT rules have a special format, which makes it quite obvious that it is DNT-allows
When I look, its not really clear to me why those things where allowed, except that I know the domains on the list... any harm in making it green (to match the outline in the menu) ?

<special color for any rules that match in adnauseam.txt (with link, perhaps a tr outline)
I meant an different border color for matches in adnauseam.txt, which would already be purple (from 1)
But  maybe we don't need this as long we show the list(s) that matched for each cosmetic filter that results in a collected ad

**Comment by cqx931** [comment]
Ok, so here are the color specs:

**Ublock entries**

- Allow: Green
- Cosmetic: Yellow
- Block: Red

**AdNauseam entries**
- Adn-allows :Blue
- DNT-allows: Bright Green
- Cosmetic rules that result in a collected ad: Purple

Can we use a tag to indicate that the entry is a match from adnauseam.txt?(see image below)
- Allows (from adnauseam.txt)
- Blocks (from adnauseam.txt)

Mock up:
![image](https://user-images.githubusercontent.com/3056154/32901758-96a1f712-cabe-11e7-819f-8e50ac25c8c5.png)

**Comment by dhowe** [comment]
The color spec is good, but I'm not sure about the ADN tags. Lets start with just the colors, and discuss the tags after?

**Comment by cqx931** [comment]
Or something like this for the ADN tag:
![image](https://user-images.githubusercontent.com/3056154/32916525-5f14e648-caea-11e7-87a6-12c4749d4ad9.png)

**Comment by dhowe** [comment]
Better, but I don't love the change of style -- the rest is all plan text in a single font
and we want this to be quite subtle...

What about just placing an A in the cell just to the left (or is that cell already used for something there?)

**Comment by cqx931** [comment]
That cell is supposed to be an link that bring up the ublock menu for that specific tab, but it should be ok if we just place an A in it.

**Comment by dhowe** [comment]
and a click on the 'a' should probably go to the adnauseam-list itself, preferably to the rule itself...

**Comment by cqx931** [comment]
I'm not sure whether it is a good idea to change the link here, I never use this the link from second colomn, but there might be some user from uBlock who does that.
Currently when clicking on the rule(3rd colomn), the window below pops up.
![image](https://user-images.githubusercontent.com/3056154/32917064-fc539d04-caeb-11e7-9cc2-893c3e0e8bb1.png)
However, the current link is linking to the page instead of the file itself. One option would be to add a second link besides, linking to the file instead.

**Comment by dhowe** [comment]
So clicking the blue 'AdNauseam Filters' link takes one to the settings page, not the list itself?
And this is standard for uBlock, correct?
If so, then I agree we should add a second link to the page itself (preferable to the specific rule)

**Comment by cqx931** [comment]
no, it links to the corresponding supportURL from assets.json

**Comment by dhowe** [comment]
so that clicks takes us to adnauseam's github page, which is not very useful...
can we link directly to the page in uAssets:  https://github.com/dhowe/uAssets/blob/master/filters/adnauseam.txt

**Comment by cqx931** [comment]
I'm not sure whether it is a good idea only changing the behavior of the link for adnauseam.txt. This could be potentially confusing for some users.
A second link sounds like a better solution for me.

**Comment by dhowe** [comment]
But why take them to a repo that doesn't contain the list, as we do now ?

**Comment by cqx931** [comment]
Because supporting URL is where the users can ask questions/file an issue?

**Comment by cqx931** [comment]
Please check:
https://github.com/dhowe/AdNauseam/pull/1287
Updated:
new adn-allowed: dark blue
dnt-allowed: bright green

Todo: cosmetic rules that result in a collected ad
Shall we try to save the triggering rule in the ad parser? Then asking the background script whether the current cosmetic rule is matched with any triggering rule from the current page? I'm not sure how to get the triggering cosmetic rule from the content script.

**Comment by dhowe** [comment]
Sounds good -- I will add this...

Blocked on #1288

**Comment by dhowe** [comment]
Note that we must also update the FAQ entry to show ALL colors in the logger (including those standard to uBlock, as the colors appear different in our interface)...

**Comment by dhowe** [comment]
Actually, I'm not clear about #1288... do we need to link the rule to the ad, or just link the ad logger entry to the logger-entry for the cosmetic filter (which contains the rule) ?

**Comment by dhowe** [comment]
>Sounds good -- I will add this...
Blocked on #1288
