### ISSUE TITLE
Break respectDNT option into two prefs disableClicksForDNT and disableHidingForDNT

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#397]
this is an update to what has to happen in #371:

- we now have 2 settings: disableClicksForDNT and disableHidingForDNT
- firstrun page still has a single checkbox for DNT, which sets both options in settings
- settings page has separate option (under clicking and hiding respectively) for the two

**Comment by leoneckert** [comment]
I don't quite understand what you mean here. 
Do we need a second box in firstrun?
Do we need two seperate boxes in Settings? (I also only see one DNT box here "Respect DoNotTrack exceptions" under "AdNauseam-advanced"
If we need two separate ones somewhere, I could surely do this on the frontend,but how will this actually take action, what's the mechanism that makes DNT only be respected for hide or click respectively?

**Comment by dhowe** [comment]
I've now split the single option into two in background.js.
The full spec is updated in #371.

**Comment by dhowe** [comment]
Closing in favor of #371
