### ISSUE TITLE
Implement adn-specific dynamic-filters / firewall

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#399]
in start.js

**Comment by cqx931** [comment]
Can I add defaultDynamicFilters to the list of returned items in core.js, in order to pass the variable to start.js? I'm not very familiar with passing variables between js files, so correct me if I am wrong...

**Comment by dhowe** [comment]
I've implemented the dynamic rule we discussed, but I'm still not sure it fixes the problem. 
Please test and report back...

**Comment by cqx931** [comment]
tested and it works.
A minor tweak:
https://github.com/dhowe/AdNauseam/pull/403

**Comment by cqx931** [comment]
The ad content loading problem in NY-Times homepage is also caused by the blocking of googletagservices.com/tag/js/gpt.js$script, which is actually in the list of disabledBlockingRules.

When I check the uBlock logger within AdNauseam, it shows me that this request is blocked
<img width="743" alt="screen shot 2016-09-17 at 4 22 51 pm" src="https://cloud.githubusercontent.com/assets/3056154/18607075/8bb1553c-7cf4-11e6-9d12-ac2ffcfbc54a.png">
Though in background.html, there is no hint of the block but a Redirect:
<img width="984" alt="screen shot 2016-09-17 at 4 31 46 pm" src="https://cloud.githubusercontent.com/assets/3056154/18607090/d756ea06-7cf4-11e6-9bd0-ccad1a4a12e3.png">

When I add a dynamic filter or static filter that allows this request in setting, it does allow the blocking.
But when I add the same rule to defaultDynamicFilters or an exception in adnauseam.txt, it still gets blocked.

**Comment by dhowe** [comment]
Interesting, let me check...

**Comment by cqx931** [comment]
the blocking issue is fixed by https://github.com/dhowe/AdNauseam/commit/7aee055f08adbe0c10d8b73b5268db86023f4624
now ads could be successfully generated on New York Times
