### ISSUE TITLE
AdNauseam is collecting images from Sponsored posts in facebook, but not hiding them

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#404]
<img width="1016" alt="screen shot 2016-09-15 at 9 43 11 am" src="https://cloud.githubusercontent.com/assets/3056154/18535678/f5c656ac-7b28-11e6-85e4-c31d65d26319.png">

**Comment by dhowe** [comment]
these should be hidden as well -- can we add a rule to adnauseam.txt?

**Comment by cqx931** [comment]
facebook.com###stream_pagelet div[id^="hyperfeed_story_id_"]:has(a.uiStreamSponsoredLink)
it should be hidden by cosmetic filter in uBlock from the latest uBlock list.  They will be correctly hidden after I do an update of the filters. In this case, is is still needed to add it to adnauseam.txt?

**Comment by dhowe** [comment]
not if its already in ublock... which list?

**Comment by dhowe** [comment]
actually, if you pull uAssets and re-build, then purge caches, the rule should be there...

**Comment by cqx931** [comment]
uBlock filters‎

**Comment by cqx931** [comment]
yes, it's there now

**Comment by dhowe** [comment]
ok, so verify that those posts are now hidden (and collected), then you can close this ticket

**Comment by cqx931** [comment]
verified on the latest update. Sponsored posts are now hidden and images are collected.
