### ISSUE TITLE
Add '-' signs to 3rd-party lists categories when expanded

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#409]
same as '+' sign when collapsed (see Languages)

![screen shot 2016-09-16 at 2 12 09 pm](https://cloud.githubusercontent.com/assets/737638/18581314/9b7c3760-7c32-11e6-98c3-4bc742042f89.png)

**Comment by mushon** [comment]
@dhowe would you please upload the screenshot again?

**Comment by dhowe** [comment]
@leoneckert please include the issue # in your PRs
