### ISSUE TITLE
Error when exporting Ads:"'storageUsed' of null"

### ISSUE THREAD

**Issue by leoneckert** [dhowe/AdNauseam#411]
Both in options.html and vault.html, when clicking to Export Ads, this Error shows up. 
<img width="456" alt="screen shot 2016-09-16 at 15 23 08" src="https://cloud.githubusercontent.com/assets/14130931/18598600/a3362ec2-7c21-11e6-8092-3c171d1032bf.png">
Lines 176+ in shared.js is where this gets thrown. On Loading the page, the the onLocalDataReceived function is called for the first time, and works, I believe because the details paramter is passed in the correct format. When called again as a callback from exportToFile function however, the error gets thrown. Is the callback even needed in there? 
<img width="780" alt="screen shot 2016-09-16 at 15 25 17" src="https://cloud.githubusercontent.com/assets/14130931/18598631/cbc1935e-7c21-11e6-90a4-8701c2595270.png">

**Comment by dhowe** [comment]
Duplicate
