### ISSUE TITLE
Don't allow 'bad' resource types in our default firewall rules

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#417]
e.g., swf

We currently use *, which means 'any type' -- can we instead use 'any type except a,b,c,' ?

**Comment by cqx931** [comment]
according to the Dynamic filtering documentation:https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax
Dynamic rules could be either hostname-based, or type-based.
now, with nytimes.com nytimes.com * allow, it is a host-based rule, and for the type it can only be *.
However, we can use two specific rules instead to achieve your goal:

nytimes.com http://et.nytimes.com xmlhttprequest allow
nytimes.com https://et.nytimes.com script allow

**Comment by dhowe** [comment]
Is 'xmlhttprequest' a valid type?
If so, then I think we want 'inline-script' and '1p-script' as well
But yes, please make this update, then verify that all the nytimes ads are still being collected

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/419

**Comment by dhowe** [comment]
@cqx931 please close if all set

**Comment by cqx931** [comment]
no need to allow requests from nytimes.com for now.

**Comment by dhowe** [comment]
@cqx931 can we close this ticket, removing nytimes from the firewall list?

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/429/commits/20b2226203eed50a2a6f1061cbb86bd571287e05
Removed
