### ISSUE TITLE
switches on firstrun page: styling 

### ISSUE THREAD

**Issue by leoneckert** [dhowe/AdNauseam#422]
I noticed these switches in firstrun don't switch fully to the right. I guess they use the same css as the new switches in options and maybe that's why? 
<img width="583" alt="screen shot 2016-09-20 at 22 16 41" src="https://cloud.githubusercontent.com/assets/14130931/18695476/26809522-7f80-11e6-9653-e1d4176413b8.png">

**Comment by dhowe** [comment]
@mushon does this have something to do with the new settings design?
