### ISSUE TITLE
send DNT header whenever clickingForDNT or hidingForDNT are enabled

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#424]
you might check how PrivacyBadger does this, as they do the same

**Comment by cqx931** [comment]
In what circumstance do we add a DNT header to a web request?Is it for all web requests or not? I am checking the onBeforesendHeaders function in traffic.js. If I understood it correctly, that function only cares about behind-the-scene ad request..

**Comment by dhowe** [comment]
for all outgoing requests, if clickingForDNT or hidingForDNT are enabled

**Comment by dhowe** [comment]
IN TRAFFIC.JS, this code should come just before:

```
    // We only care about behind-the-scene requests here
    if (!vAPI.isBehindTheSceneTabId(details.tabId)) return;
```

**Comment by cqx931** [comment]
yes, I got that now. btw. does "whenever clickingForDNT or hidingForDNT are enabled " mean (disableClickingForDNT == false || disableClickingForDNT == false) ?;       
I see them both set to true in my default setting...therefore I'm a little bit confused here. The user won't have DNT header by default?

**Comment by dhowe** [comment]
After the first run-page, none, one, or both DNT settings will be selected. If disableClickingForDNT is true OR disableHidingForDNT is true, then we send the DNT header. If they are both false, then we don't. Clear?

**Comment by cqx931** [comment]
ok, clear. Please check https://github.com/dhowe/AdNauseam/pull/428

**Comment by cqx931** [comment]
An Update for checking whether DNT header already exists.https://github.com/dhowe/AdNauseam/pull/429
