### ISSUE TITLE
Issues with notification layout

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#425]
Notifications push other content down and off the page on menu.html, hiding our button (see image below). Similarly, on vault.html, they conflict with the zoom and close buttons at the top

Css needs adjusting, but I'm not sure what the design calls for.
You can test by disabling 'EasyList' in 3rd-party filters

![screen shot 2016-09-21 at 12 22 54 pm](https://cloud.githubusercontent.com/assets/737638/18697726/93491532-7ff6-11e6-99f5-e08b00bb7047.png)

**Comment by dhowe** [comment]
Also, on pages where adn is disabled or paused, notifications are hidden as well:

![screen shot 2016-09-22 at 8 21 16 pm](https://cloud.githubusercontent.com/assets/737638/18747924/64343eae-8102-11e6-9a37-e9205b8467ba.png)

**Comment by cqx931** [comment]
same layout issue with dashboard.html
![Uploading Screen Shot 2016-09-28 at 3.17.16 pm.png…]()

**Comment by cqx931** [comment]
same layout issue with dashboard.html (push buttons offpage)
![screen shot 2016-09-28 at 3 17 16 pm](https://cloud.githubusercontent.com/assets/3056154/18904115/1d167a00-858f-11e6-9c99-99e80536529c.png)

**Comment by mushon** [comment]
I looked into this problem in the settings pages and it has to do with the dynamic iFrame height. Dynamically deducting the notifications height from the iFrame height will fix the problem.

As for the menu and the vault, I couldn't see the notification there (even after disabling EasyList) but the solution there should be the same: dynamically deducting the height from the main area: ``#ad-list`` in the menu and in the vault add to the ``top`` margin of: ``#x-close-button``, ``zoom`` and ``ratio``.

This needs to be done in JS (and don't forget to remove it when the notification is closed), reassigning to @cqx931. Thanks!

**Comment by cqx931** [comment]
As for the vault, can we move` #x-close-button` and `ratio` into `#stage` div (the same as` zoom`) and add a"position:relative" to `#stage`, so that all these three little things will have their absolute position according to `#stage`?
Please let me know, if this could causing any possible trouble to the function of vault, if not, I think this might be easier than adding a dynamic margin.

**Comment by cqx931** [comment]
fix it for menu & dashboard here
https://github.com/dhowe/AdNauseam/pull/471/commits/cf6e2c454783acee06758589ee3807011e011de1

**Comment by mushon** [comment]
@cqx931 sure thing. Go ahead…

**Comment by cqx931** [comment]
All fixed, please verify https://github.com/dhowe/AdNauseam/pull/473
