### ISSUE TITLE
Test list of important sites for ads either appearing, or not being collected

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#427]
Ken, start by visiting each of the sites below manually and take note of the # of ads you see. Then visit with AdNauseam (ADN) and check 1) number of ads visible, and 2) number of ads collected. Record your findings. For any visible ad, please create a new ticket like [this](https://github.com/dhowe/AdNauseam/issues/1425)
- si.com
- cnn.com
- lingscars.com
- forbes.com
- pcmag.com
- examiner.com
- dictionary.com
- salon.com
- answers.com
- sfgate.com
- theatlantic.com
- nypost.com
- facebook.com
- theinquirer.net

Chinese
- taobao.com
- 163.com
- sohu.com
- sina.com
- qq.com
- zol.com.cn
- baidu.com

**Comment by leoneckert** [comment]
went through all english websites on the list today:

# si.com
seen: 7
**adn (allON):**
	seen:0
	collected:0
**adn (allON, no DNT exception):**
	seen:0
	collected:1

----------------------------------------------------
# cnn.com
seen: 7
**adn (allON):**
	seen: 0
	collcted: 0
**adn (allON, no DNT exception):**
	seen:0
	collected:3

----------------------------------------------------
# lingscars.com
seen: 0
**adn (allON):**
	seen: 0
	collcted: 0
**adn (allON, no DNT exception):**
	seen:0
	collected:0

----------------------------------------------------
# forbes.com
seen: 4
**adn (allON):**
	seen: 2
	collcted: 0
**adn (allON, no DNT exception):**
	seen:2
	collected:0

----------------------------------------------------
# pcmag.com
seen: 6
**adn (allON):**
	seen: 2
	collected: 9
**adn (allON, no DNT exception):**
	seen:2
	collected:9

----------------------------------------------------
# examiner.com (axs.com)
seen: 0
**adn (allON):**
	seen: 0
	collected: 0
**adn (allON, no DNT exception):**
	seen:0
	collected:0

----------------------------------------------------
# dictionary.com
seen: 3
**adn (allON):**
	seen: 1
	collected: 0
**adn (allON, no DNT exception):**
	seen:1
	collected:0

----------------------------------------------------
# salon.com
seen: 10
**adn (allON):**
	seen: 0
	collected: 0
**adn (allON, no DNT exception):**
	seen:0
	collected:0

----------------------------------------------------
# answers.com
seen: 4
**adn (allON):**
	seen: 0
	collected: 3
**adn (allON, no DNT exception):**
	seen:1
	collected:3

----------------------------------------------------
# sfgate.com
seen: 10
**adn (allON):**
	seen: 1
	collected: 0
**adn (allON, no DNT exception):**
	seen:1
	collected:0

----------------------------------------------------
# theatlantic.com

interesting Ads that look exactly like articles even with atlantic style graphics, but with this disclaimer:
This Content is made possible by our Sponsor; it is not written by and does not necessarily reflect the views of The Atlantic's editorial staff. See our Advertising Guidelines, or email advertising@theatlantic.com to learn more.

seen: 7 (2/5)
**adn (allON):**
	seen: 0/5
	collected: 1
**adn (allON, no DNT exception):**
	seen:0/5
	collected:1

----------------------------------------------------
# nypost.com
seen: 4
**adn (allON):**
	seen: 0
	collected: 0
**adn (allON, no DNT exception):**
	seen:0
	collected:0

----------------------------------------------------
# facebook.com
seen 2 real ads/+ (scrolling)
'suggested/sponsored' posts are ads
**adn (allON):**
	seen: all 'suggested/sponsored' posts
	collected: 5
**adn (allON, no DNT exception):**
	seen: all 'suggested/sponsored' posts
	collected:0

**Comment by dhowe** [comment]
For each URL where an ads is visible, we need to first test whether it is visible on uBlock alone. If so, then it should be added to this ticket: https://github.com/dhowe/AdNauseam/issues/381, preferably with a screenshot.

For each URL where an ad is hidden, but not collected, the page needs to be added to this ticket: https://github.com/dhowe/AdNauseam/issues/356

**Comment by cqx931** [comment]
Shall I check the two lists for Chinese sites in uBlock when I test the Chinese ones?
<img width="688" alt="screen shot 2016-09-22 at 10 34 38 am" src="https://cloud.githubusercontent.com/assets/3056154/18735417/428efda4-80b0-11e6-8539-adee59004f09.png">

**Comment by dhowe** [comment]
@cqx931 yes, to your question above
generally, why don't you handle the Chinese sites on this list, and @leoneckert can do the others...

**Comment by cqx931** [comment]
cool, then I will just finish the si.com one and leave the rest to @leoneckert .

**Comment by cqx931** [comment]
Chinese sites
*uBlock with Chinese filters on

### taobao.com
seen: 0
**uBlock**
seen:0
**AdNauseam**
seen:0
collected:0

### 163.com
seen: 25
**uBlock**
seen:0
**AdNauseam**
seen:13
collected:0

### sohu.com
seen:16
**uBlock**
seen:0
**AdNauseam**
seen:3
collected:2

### sina.com
seen:24
**uBlock**
seen:0
**AdNauseam**
seen:11
collected:0


### qq.com
seen:9
**uBlock**
seen:0
**AdNauseam**
seen:4
collected:0

###zol.com.cn
seen:9
**uBlock**
seen:0
**AdNauseam**
seen:1 (3 not prooerly collapsed ad windows)
collected:6

###baidu.com ...
Search Example:化妆品(cosmetics)
seen:  3 ad sections
**uBlock**
seen:0
**AdNauseam**
seen:3
collected:0

**Comment by dhowe** [comment]
Good. Please also see https://github.com/dhowe/AdNauseam/issues/279 -- we need to determine the remaining lists that we can allow blocks from... (you may need to consult with @CyrusSUEN )

**Comment by dhowe** [comment]
First step is adding them all to #381, then working on them one by one...

**Comment by cqx931** [comment]
For Chinese sites, I think my first step shall be adding the two Chinese filters to the hiddenLists and work on those sites one by one later?

**Comment by dhowe** [comment]
I don't understand, those lists are already there (under languages). Why do you want to hide them?

**Comment by cqx931** [comment]
Oh, I think I got the hiddenList thing wrong... What I want is to have the cosmetic filtering rules from Chinese list. Are they already there? I only see CHN: CJX's Annoyance List‎ (github.com) under languages, when I go to the settings Page

**Comment by dhowe** [comment]
I see three chinese lists (which you need to enable):

**Comment by cqx931** [comment]
Sorry,my fault... now I see three lists in the language settings.

fixed si.com with https://github.com/dhowe/AdNauseam/pull/433

**Comment by leoneckert** [comment]
checking on further popular pages right now.

- [ ] http://www.msn.com/ there is a 'Microsoft Store Offers' Box at the bottom. 

To be fair, MSN=Mircosoft, but it still says "sponsored" and links through http://clk.tradedoubler.com. uBlock and ABP don't hide it, should we, @dhowe ?

**Comment by dhowe** [comment]
if they don't hide it, lets not worry about it

**Comment by leoneckert** [comment]
unless otherwise instructed I'll spend time going through popular news sites today:

- [ ] https://www.yahoo.com/news
- [ ] https://news.google.com
- [ ] http://www.huffingtonpost.com
- [ ] http://www.cnn.com
- [ ] http://www.nytimes.com/
- [ ] http://www.foxnews.com
- [ ] http://www.nbcnews.com
- [ ] http://www.dailymail.co.uk/ushome/
- [ ] https://www.washingtonpost.com
- [ ] https://www.theguardian.com/us
- [ ] http://www.wsj.com
- [ ] http://abcnews.go.com
- [ ] http://www.bbc.com/news
- [ ] http://www.usatoday.com
- [ ] http://www.latimes.com
- [ ] http://www.cbsnews.com
- [ ] http://www.reuters.com
- [ ] https://wn.com
- [ ] http://www.msnbc.com
- [ ] http://www.cbc.ca/news
- [ ] http://time.com
- [ ] http://www.ap.org
- [ ] https://consortiumnews.com
- [ ] http://www.news.com.au

1) count # of ads I see without AdBlocker. 
2) number of ads visible with ADN
3) number of ads collected with ADN 
4) distinguish between [ads visible, but hidden on uBlock] -> #381 and [ads hidden, but not collected] -> #356 
5) work on results.

**Comment by dhowe** [comment]
Good. Now add any visible Ads to #381 and all un-collected Ads to #356 (this should be standard procedure going forward, whenever we do this sort of testing).
