### ISSUE TITLE
CSS for DNT list on whitelist.html

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#436]
![screen shot 2016-09-23 at 8 10 47 pm](https://cloud.githubusercontent.com/assets/737638/18785273/ebe60374-81c9-11e6-91cd-d34bb0cf6cbb.png)

**Comment by dhowe** [comment]
Please adjust CSS (remove the '-' sign, align left, and add space below 'EXTERNAL LISTS' -- perhaps font should be larger as well...)

**Comment by leoneckert** [comment]
can this be closed?
