### ISSUE TITLE
match red colors (2) on options.html

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#437]
2 red colors should be the same, either way...

**Comment by leoneckert** [comment]
I personally prefer the color of the little info cicle. But the reason the "Clear Ads" button is that shade is that same style applies to it as to this banner:

<img width="1028" alt="screen shot 2016-09-28 at 15 39 35" src="https://cloud.githubusercontent.com/assets/14130931/18929367/32e2fa68-8592-11e6-9dc4-7793694fb506.png">

I went for the option of making a smaller design decision and adapted the info circle to the rest. Pull request comming..

**Comment by leoneckert** [comment]
also, I noticed that at all the buttons with this shape:

<img width="280" alt="screen shot 2016-09-28 at 15 45 17" src="https://cloud.githubusercontent.com/assets/14130931/18929505/ba6d759e-8592-11e6-8851-1086ea295280.png">
we don't use a  "pointer" cursor. Could change quickly if that's wanted

**Comment by dhowe** [comment]
whatever is standard

**Comment by mushon** [comment]
This is the standard our notifications follow:
```
.notification.info
.notification.success
.notification.warning
.notification.error
```
![image](https://cloud.githubusercontent.com/assets/27123/18942899/defec7fe-8624-11e6-9f39-ee23df1afc4b.png)

The way I see it, it makes sense for the clear ads button to be orange/yellow-ish

**Comment by leoneckert** [comment]
yap that makes sense

**Comment by leoneckert** [comment]
can be closed?
