### ISSUE TITLE
Test notification system on Firefox and Opera

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#444]
List of steps here: https://github.com/dhowe/AdNauseam/wiki/Testing-New-Release-Candidates#notifications

**Comment by dhowe** [comment]
on hold

**Comment by leoneckert** [comment]
**Firefox:**
- [ ] Check that disabling hiding, clicking, or blocking on the first-run generates a notification warning at the top of the dashboard (all tabs), menu, and vault page (after first-run is closed or 'ok' is clicked).
- [ ] Check that disabling hiding, clicking, or blocking on the dashboard/options page generates a notification warning at the top of the dashboard(all tabs), menu, and vault page.
- [ ] Check that disabling EasyList on the dashboard/3p-filters page generates a notification warning at the top of the dashboard(all tabs), menu, and vault page.
- [ ] Check that clicking 'reactivate' on a notification warning at the top of the dashboard, menu, or vault pages causes the visual state to change correctly, and the setting in question to be updated correctly.
- [ ] Check that the vault (if open) is updated when notifications change
- [ ] Check that the dashboard (if open) is updated when notifications change
- [ ] Dashboard::settings (options.html) Check that page refreshes correctly when a notification is 'reactivated'
- [ ] Dashboard::3rd-Party (3p-filters.html) Check that page refreshes correctly when a list-notification is 'reactivated'

**Comment by leoneckert** [comment]
**Opera:**
- [ ] Check that disabling hiding, clicking, or blocking on the first-run generates a notification warning at the top of the dashboard (all tabs), menu, and vault page (after first-run is closed or 'ok' is clicked).
- [ ] Check that disabling hiding, clicking, or blocking on the dashboard/options page generates a notification warning at the top of the dashboard(all tabs), menu, and vault page.
- [ ] Check that disabling EasyList on the dashboard/3p-filters page generates a notification warning at the top of the dashboard(all tabs), menu, and vault page.
- [ ] Check that clicking 'reactivate' on a notification warning at the top of the dashboard, menu, or vault pages causes the visual state to change correctly, and the setting in question to be updated correctly.
- [ ] Check that the vault (if open) is updated when notifications change
- [ ] Check that the dashboard (if open) is updated when notifications change
- [ ] Dashboard::settings (options.html) Check that page refreshes correctly when a notification is 'reactivated'
- [ ] Dashboard::3rd-Party (3p-filters.html) Check that page refreshes correctly when a list-notification is 'reactivated'

**Comment by leoneckert** [comment]
all tested and working.

**Comment by dhowe** [comment]
👍
