### ISSUE TITLE
Reactivate button not working both in the menu and in dashboard

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#457]
![screen shot 2016-09-28 at 3 14 58 pm](https://cloud.githubusercontent.com/assets/3056154/18908411/0e70a4c2-85a2-11e6-952a-2126267cdb7e.png)
![screen shot 2016-09-28 at 3 15 06 pm](https://cloud.githubusercontent.com/assets/3056154/18908415/121e0d12-85a2-11e6-93ed-70e4a533e724.png)

**Comment by dhowe** [comment]
Options:
- just change the setting
- take you to the page where the setting is
- both
?

**Comment by cqx931** [comment]
I vote for just change the setting and show a successful message afterwards

**Comment by dhowe** [comment]
sounds right, i'll take a first pass...
