### ISSUE TITLE
ads move off center in vault when only text ads are in storage

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#459]
The center of the ads will move with the data filter slider. It seems to have some correlation to the width of the slider.
![screen shot 2016-09-28 at 6 23 45 pm](https://cloud.githubusercontent.com/assets/3056154/18910018/ba917b22-85a8-11e6-82f1-7122856084f7.png)

**Comment by leoneckert** [comment]
@cqx931 does this happen for you anytime you use the slider? I couldn't replicate the issue at first. 

Now I found it only happens for me when dragging/releasing the slider behind its actual end (too far to the right or left). And when doing so the ads will slide as long as the slider was dragged, very strange. Looking into it.

**Comment by leoneckert** [comment]
So, the only thing I found is that it is not restricted to text ads (I get the same bug with images and texts) and that dragging the slider is just mistaken for dragging the Ads vault (essentially dragging the two of them at once). Is your bug a different one, @cqx931 ?

**Comment by leoneckert** [comment]
check if that fixes the bug you saw, @cqx931 , what exactly changes is written in the pull request

**Comment by dhowe** [comment]
awaiting your comment @cqx931

**Comment by cqx931** [comment]
It doesn't happen every time when I use the slider. But yes, when I drag it really to the right(short width) or left, it goes off center.
I have tested your fix, it solves the problem well! 
Please merge.@dhowe

**Comment by cqx931** [comment]
fixed
