### ISSUE TITLE
Add 'disable on this page'  button to AdNauseam menu

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#46]
Need to be able to disable AdNauseam for a page, a site, or entirely (although this last is already handled in the browser's extension manager).

**Comment by mushon** [comment]
I suggest that the default would be to pause on this page and then we will allow a follow up option to either reactivate or to pause AdNauseam continuously everywhere (we need to think of the right wording). @dhowe let me know what you think and I will follow up with a design.

**Comment by dhowe** [comment]
Well, we do need both options. Of course from the extensions menu you can already disable the addon, but this is not so easy to find. So the choices then are 2 buttons or clickable icons (pause/disable-on-this-page) or one button with a follow-up as you describe above. I leave this to @mushon. 

The other consideration is whether disable-for-this-page is a sticky setting, that is, does it  add the page to the current whitelist? If not, then we need an easy way to do this as well (it is possible from the options page, but again perhaps not intuitive). One option is to keep our current 'pause' button and add a 2nd, smaller icon/button with a tooltip reading something like 'whitelist this page' ...

**Comment by mushon** [comment]
ok, I’ll mock it up and account for whitelisting too.

**Comment by dhowe** [comment]
Here is another way to do 2 options:

![screen shot 2016-03-18 at 11 18 52 pm](https://cloud.githubusercontent.com/assets/737638/13882324/f18d691a-ed5f-11e5-8831-749bea7c4370.png)

**Comment by mushon** [comment]
First draft:
![popup paused](https://cloud.githubusercontent.com/assets/27123/13899493/79c69aac-edf8-11e5-9c43-92d40784da9f.png)

**Comment by dhowe** [comment]
I like it the look, but find it less than fully clear in terms of function. 
The full set of options are (I think) :
1) Disable temporarily on this page
2) Disable temporarily on this domain
3) Disable on this page (add to whitelist)
4) Disable on this domain (add to whitelist)
5) Disable completely

To simplify, at least until we get requests to the contrary, I think we should take uBlock's approach and allow people to disable only on the extensions page (thus removing button 5).

I think we might be able to gloss over the difference between temporarily and permanently by always adding the item to the whitelist, and then removing it when disabled, thus all changes are 'permanent', but undoable'  (thus removing buttons 1 & 2).

And I would also argue for removing the large "resume adnauseam" button, as its confusing to me whether I should un-click 'disable all over nytimes.com' or "resume adnauseam" and what the difference would be between the two.

So I would propose the message at the top, reading "AdNauseam is currently paused on this page/domain)", followed by 2 radio buttons (#3, #4)

@mushon ?

**Comment by mushon** [comment]
Good points.
Heres' another attempt:
![popup_paused_2](https://cloud.githubusercontent.com/assets/27123/14019238/6b870fd6-f1da-11e5-9bb4-db079d2de00d.png)

By default the pausing would pause the page. This can be changed to pausing the domain by stating the domain (``) or pausing ``all the web``

**Comment by dhowe** [comment]
Looks good. Can you add it (hidden) to adn-popup.html and src/css/adn/menu.css

**Comment by mushon** [comment]
Just published the paused-menu branch. @dhowe please check and let's talk:
https://github.com/dhowe/AdNauseam2/tree/paused-menu

**Comment by dhowe** [comment]
Initial implementation in 3708f29a72
@mushon will need to tweak visual style for 'disabled' state
and add tooltip(s)

**Comment by mushon** [comment]
@dhowe let me know when things are ready for me to tweak and let's touch base to make sure I am tweaking them in the right direction

**Comment by dhowe** [comment]
@mushon lets discuss the 'resume' button. i am fine with a centered button under the paused message, however, this makes the footer resume button useless, so we should perhaps just gray out the original 'pause adn' button and not change its text. Also, even when paused on a page/site, one should still be able to view settings, FAQ and vault...

**Comment by mushon** [comment]
There is no problem with having two buttons on the same page that both do the same thing. And yes, settings, FAQ and Vault should still work, I can keep them grayed-out but allow them to maintain their original hover effect. 

Greetings from Berlin #rpTEN

**Comment by dhowe** [comment]
Nice, enjoy. 

Unless there is a specific reason to do so, I don't see the point of having two buttons within a very small space that do the same thing, one that appears active and the other grayed out. 

And why do we want to gray-out active buttons in the interface (FAQ, Vault, Settings, etc) ? This tells people NOT to click on them, when it is a quite common use-case to view the advault (or settings, or FAQ), while on a whitelisted page ...

**Comment by dhowe** [comment]
Close this if you like, or suggest an improved design...

**Comment by mushon** [comment]
closing
