### ISSUE TITLE
 Text ads detection issue in bing

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#460]
AdNauseam seems to combine all the text ads in each section area to one text ad.
![screen shot 2016-09-28 at 6 01 52 pm](https://cloud.githubusercontent.com/assets/3056154/18910094/0c02b412-85a9-11e6-85b0-2de758387b79.png)

**Comment by dhowe** [comment]
confirmed, please fix

**Comment by cqx931** [comment]
fixed with https://github.com/dhowe/AdNauseam/pull/465
