### ISSUE TITLE
Text Layout in "My Rules" tab

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#461]
For me, the titles "Temporary rules" and "Permanent rules" are too close to the buttons. Is this intentional or a bug?
![screen shot 2016-09-28 at 6 07 59 pm](https://cloud.githubusercontent.com/assets/3056154/18910463/b1660f66-85aa-11e6-8777-450e095f7cdf.png)

**Comment by dhowe** [comment]
a bug, please fix

**Comment by cqx931** [comment]
fixed with https://github.com/dhowe/AdNauseam/pull/471/commits/76c21dbbdca544a59eb4063a78144c4716ac2bb7
