### ISSUE TITLE
Notification not showing in menu.html when no ads collected in the current page

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#468]
<img width="363" alt="screen shot 2016-09-29 at 3 19 30 pm" src="https://cloud.githubusercontent.com/assets/3056154/18944890/6422e764-865a-11e6-9cd8-50b172d9d71e.png">

**Comment by dhowe** [comment]
this is related to the css layout issues in #425

**Comment by cqx931** [comment]
I think it is not really realted to no ads collected....let me double check...

**Comment by cqx931** [comment]
can't see this happen anymore, close for now.
