### ISSUE TITLE
setting page is not properly refreshed(if open) when reactivate button in clicked in vault/menu

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#470]
To reproduce:
1.uncheck HIDE ADS in setting page, leave the page open

2.a.go to another tab and click the reactivate button in menu, the button disappears after click
2.b.go to vault and click the reactivate button in menu, the button disappears after click

3.go back to the setting page, the button disappears but HIDE ADS is still unchecked
4.refresh the page, HIDE ADS is checked

**Comment by cqx931** [comment]
This is still happening in the latest implementation.Are we going to just leave it like this? Things works well after refreshing the pages. @dhowe

**Comment by dhowe** [comment]
No, we need to either redraw notifications, or simply refresh the page, whenever notifications change (as is already the case in menu/vault)

**Comment by dhowe** [comment]
I think I have a solution...

**Comment by cqx931** [comment]
verified.close
