### ISSUE TITLE
Page unreadable (due to unblocked to overlay?)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#474]
But fine with uBlock:

http://www.computerworld.com/article/3125587/web-browsers/mozilla-tests-ad-blocking-feature-in-firefox.html

![screen shot 2016-09-30 at 12 45 52 am](https://cloud.githubusercontent.com/assets/737638/18963439/92d112f0-86a7-11e6-9f2a-e7d589ddd7ed.png)

**Comment by dhowe** [comment]
![screen shot 2016-09-30 at 12 45 52 am](https://cloud.githubusercontent.com/assets/737638/18963408/73e4b194-86a7-11e6-9588-530bbe482365.png)

**Comment by leoneckert** [comment]
should be fixed with https://github.com/dhowe/AdNauseam/pull/476

**Comment by dhowe** [comment]
👍
