### ISSUE TITLE
Add interface button (or shortcut) to disable blocking on a site

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#477]
This would simply create a temporary firewall rule for the page/site allowing all outgoing requests. Here is an example that would be created for [this accuweather.com page](http://www.accuweather.com/en/hk/hong-kong-weather)

![screen shot 2016-09-30 at 7 22 35 am](https://cloud.githubusercontent.com/assets/737638/18975796/4d8357fc-86df-11e6-86ac-249db4f5e593.png)

We might pair this 'no-blocking' button with the 'no-hiding' button currently in uBlocks menu interface

**Comment by mneunomne** [comment]
Is this still needed?

**Comment by dhowe** [comment]
Don't remember the use-case... closing for now
