### ISSUE TITLE
Wrong uBlock version information in about tab for firefox and opera

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#480]
<img width="380" alt="screen shot 2016-09-30 at 1 05 37 pm" src="https://cloud.githubusercontent.com/assets/3056154/18981392/72713b02-8710-11e6-8b46-cff875370544.png">

**Comment by cqx931** [comment]
I find these two lines of code are missing in make-firefox.sh and make-opera.sh.
<img width="629" alt="screen shot 2016-09-30 at 3 49 18 pm" src="https://cloud.githubusercontent.com/assets/3056154/18984501/94eeace0-8725-11e6-82a2-eaf4286dda43.png">
Can I solve this by just copy these two lines to make-firefox.sh and make-opera.sh? 
Or can we actually achieve this in about.js?
<img width="756" alt="screen shot 2016-09-30 at 3 51 45 pm" src="https://cloud.githubusercontent.com/assets/3056154/18984572/f82855fe-8725-11e6-94fc-f4022061084b.png">

**Comment by dhowe** [comment]
Good catch -- just add those two lines to make-firefox.sh and make-opera.sh (the other code you mention is for the adn version -- we dont actually have the ublock version in our codebase)

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/482/commits/7caef2aa0912d2094aa3451c7295ac5ca3b1dbe6 fixed and verified.
