### ISSUE TITLE
Missing link for ad cost 

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#491]
Where do we want this question mark for ad cost linking to? Currently the href value is just "#" for both vault and menu
![image](https://cloud.githubusercontent.com/assets/3056154/19117336/3cf8c7e4-8b4b-11e6-863b-1ba9ad5ae6fb.png)

**Comment by dhowe** [comment]
this should link to the FAQ -- see https://github.com/dhowe/AdNauseam/issues/344 (@leoneckert)

**Comment by dhowe** [comment]
Exact URL: https://github.com/dhowe/AdNauseam/wiki/FAQ#how-does-adnauseam-estimate-the-click-cost-it-shows-in-the-menu-and-vault

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/pull/498
