### ISSUE TITLE
 'no 3rd-party cookies' option can't be enabled again in opera

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#492]
After clicking the little 'i' icon, nothing happens.
![image](https://cloud.githubusercontent.com/assets/3056154/19117854/16a5fb46-8b4d-11e6-99e4-983e34a586d2.png)

**Comment by dhowe** [comment]
but fine on ff/chrome?

**Comment by cqx931** [comment]
yes, the info button can not be clicked and also can't be enabled. Chrome is fine. In firefox's I can't see adnauseam controlling this option and the default is always allowing 3rd party cookies... but as long as user can change the option I think it is making a different here...
![image](https://cloud.githubusercontent.com/assets/3056154/19124656/ae018dd4-8b66-11e6-80c7-d5c0fec97e82.png)

**Comment by dhowe** [comment]
We may want to disable this feature, but I'm curious about what's happening in Firefox. Can you check that [these lines](https://github.com/dhowe/AdNauseam/blob/master/platform/firefox/vapi-background.js#L303) are actually getting executed?

Here is [the spec](http://kb.mozillazine.org/Network.cookie.cookieBehavior) for what should be required in FF.

**Comment by cqx931** [comment]
here is what I find in Firefox:
1.in `rememberOriginalValue`:
`hasUserValue` is undefined, so at the end this.originalValues[key] is also undefined.
2.SettingVal is true ->  this.clear('network.cookie', 'cookieBehavior');
3.And inside `clear('network.cookie', 'cookieBehavior')`
` Services.prefs.getBranch(path + '.').clearUserPref(setting);`
[this line](https://github.com/dhowe/AdNauseam/blob/master/platform/firefox/vapi-background.js#L182) shall be executed.

I can find some details about controlling user settings from the the chrome link . But firefox doesn't seem to support that? What is this feature actually doing, unblock 3-rd party cookies for AdNauseam?

**Comment by dhowe** [comment]
This just disabled 3rd-party cookies. The reason it wasn't working is that it was turned off in background.js (so actually it was working). I've re-enabled that option in 67fded1, however, the chrome issue remains.

**Comment by cqx931** [comment]
I see... Does the check box need be checked after installing? For both chrome and opera I can see this option to be controlled by AdNauseam but not checked. That's why I was a bit confusing...
<img width="335" alt="screen shot 2016-10-06 at 5 04 50 pm" src="https://cloud.githubusercontent.com/assets/3056154/19146658/0bf66808-8be7-11e6-8184-3b375ae262ee.png">

Which version of Opera are you using? I still can't click the info icon...

**Comment by dhowe** [comment]
pull and try again

**Comment by dhowe** [comment]
there is a problem here, which is that the user cannot override the adn default without completely disabled adn -- which means, I think, that we need to remove this feature

**Comment by cqx931** [comment]
now I can see the checkbox being checked in both opera and chrome. But in opera when I click the info it can't show the popup fully.
<img width="482" alt="screen shot 2016-10-06 at 5 32 03 pm" src="https://cloud.githubusercontent.com/assets/3056154/19147477/db99ac7a-8bea-11e6-8d70-e2ace423fae2.png">

**Comment by dhowe** [comment]
I've removed this feature in 8d8871e74f

**Comment by cqx931** [comment]
modified corresponding sections in testing new release workflow page

**Comment by dhowe** [comment]
excellent
