### ISSUE TITLE
Same ad image getting different sizes

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#496]
In this exported ad file, we can see the same ad from the same page discovered twice, once with a valid width/height of 270x194, and once with an incorrect -1x-1. This needs to be debugged in parser.js.

**Comment by cqx931** [comment]
where is the exported ad file?

**Comment by dhowe** [comment]
{
  "https://rednoise.org/adntest/simple.html": {
    "rednoise.org::174::https://rednoise.org/adntest/buyme.png::290": {
      "id": 1,
      "attempts": 1,
      "visitedTs": 1475778288920,
      "attemptedTs": 0,
      "contentData": {
        "src": "https://rednoise.org/adntest/buyme.png",
        "width": 290,
        "height": 174
      },
      "contentType": "img",
      "title": "Bonhams : Jewelry",
      "resolvedTargetUrl": "http://www.bonhams.com/departments/JWL/",
      "foundTs": 1475778281612,
      "targetUrl": "http://www.bonhams.com/departments/JWL",
      "pageTitle": "https://rednoise.org/adntest/simple.html",
      "pageUrl": "https://rednoise.org/adntest/simple.html",
      "errors": null,
      "current": true,
      "pageDomain": "rednoise.org",
      "version": "2.3.6",
      "targetDomain": "bonhams.com",
      "requestId": "373853"
    },
    "rednoise.org::-1::https://rednoise.org/adntest/buyme.png::-1": {
      "id": 2,
      "attempts": 1,
      "visitedTs": 1475778353740,
      "attemptedTs": 0,
      "contentData": {
        "src": "https://rednoise.org/adntest/buyme.png",
        "width": -1,
        "height": -1
      },
      "contentType": "img",
      "title": "Bonhams : Jewelry",
      "resolvedTargetUrl": "http://www.bonhams.com/departments/JWL/",
      "foundTs": 1475778349161,
      "targetUrl": "http://www.bonhams.com/departments/JWL",
      "pageTitle": "https://rednoise.org/adntest/simple.html",
      "pageUrl": "https://rednoise.org/adntest/simple.html",
      "errors": null,
      "current": true,
      "pageDomain": "rednoise.org",
      "version": "2.3.6",
      "targetDomain": "bonhams.com",
      "requestId": "374178"
    }
  }
}

**Comment by cqx931** [comment]
But when I go to the page: https://rednoise.org/adntest/simple.html, AdNauseam only picks up one Ad on my computer.

**Comment by cqx931** [comment]
fixed, please check
<img width="426" alt="screen shot 2016-10-23 at 1 15 56 pm" src="https://cloud.githubusercontent.com/assets/3056154/19624329/6ceaca7a-9923-11e6-9711-4e4ee8d6a918.png">
https://github.com/dhowe/AdNauseam/pull/543
