### ISSUE TITLE
First-run: what should happen when user simply clicks 'OK' ?

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#500]

**Comment by mushon** [comment]
I think the "OK" should be disabled unless you chose something, no?

**Comment by dhowe** [comment]
what if you want to choose nothing?

**Comment by mushon** [comment]
and install an extension that does nothing? I think at least in the firstrun, that shouldn't be an option.

**Comment by dhowe** [comment]
@leoneckert pls implement the above

**Comment by mushon** [comment]
hmmm… we have the notification system we can use whenever any of our core functions aren't used. Either way, I think we shouldn't allow hitting "OK" without any core function.

**Comment by leoneckert** [comment]
just a thought: if instead of "OK" it said something like "Start AdNauseam" and have that button greyed out before any adjustments are made, then the user might be more likely to actually make adjustments.

**Comment by dhowe** [comment]
this is an ongoing debate about what people expect when downloading an addon (that it will do certain things by default), vs. wanting everything to be explicitly opt-in (so that users are totally clear about what they are asking the software to do for them).

But I think the change we need implement is that at least one of the 3 toggles on the first-run page must be enabled for the 'ok' button to be enabled (clickable): see #541.

My question above was different. It referred to the fact that notifications never show (at least in our current implementation) on the first-run page, so that if a user selects only HIDE-ADS, for example, they will not see the DANGER warning about BlockingMalware until they eventually go to the menu or settings, which may be much later, or possibly even not at all.

**Comment by mushon** [comment]
Sorry, I was sure I answered this before but apparently I haven't.
Anyway, I am not too concerned about those who will chose only one option. Otherwise we can also create an ADN icon that is partly disabled or somewhat hallow or something - indicating a notification.

**Comment by dhowe** [comment]
one options or two options, the question is the same -- they don't see a warning until much later, or maybe never

**Comment by mushon** [comment]
I can live with it. I think it doesn't make sense to show a warning on the firstrun page.

What we could do is present a "loader" type feedback every time a toggle is used,
or play with the button text. Something like:

- 0 toggle: make me do it
- 1 toggle: that's it? ok…
- 2 toggle: better, but still…
- 3 toggle: LETS GO!

**Comment by mushon** [comment]
@cqx931 please add this functionality in JS:
every toggle should change the text according to the above ^
and switch classes on the body tag:
''.disabled``
''.toggled1``
''.toggled2``
''.toggled3``
+ (make sure the ``disabled`` mode indeed doesn't allow clicking)

**Comment by dhowe** [comment]
this should be around [here](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/firstrun.js#L92)

**Comment by mushon** [comment]
On the stickers we use “GO”. I think it could probably work in this case too.

**Comment by mushon** [comment]
I agree with this description. 
+
I think it's ok we won't show notifications in the firstrun screen and take the chance that a very small minority might not toggle on all options and might also not open the menu. I assume that when they will feel ADN is not doing what they want it to they will open the menu. 

One notification I will vote for including in the firstrun is if the user is using an ad blocker that conflicts with ADN. If we can alert them about it I think we should.

**Comment by dhowe** [comment]
agreed, see #564

**Comment by cqx931** [comment]
Something like this? @mushon 
<img width="1004" alt="screen shot 2016-10-26 at 5 23 46 pm" src="https://cloud.githubusercontent.com/assets/3056154/19720523/103f6ec2-9ba1-11e6-8863-e985d6fbd794.png">

**Comment by mushon** [comment]
That’s nice but I actually had something more minimal in mind - to simply change the text on the button itself (and maybe slightly play with the styling to emphasize the intensity, I can do that via CSS) What say you?

**Comment by cqx931** [comment]
I also thought about changing the text on the button...so by (disable -> more blue -> more blue -> full blue) you mean the intensity of color?

**Comment by cqx931** [comment]
<img width="720" alt="screen shot 2016-10-26 at 11 56 24 pm" src="https://cloud.githubusercontent.com/assets/3056154/19733842/e05dab9c-9bd7-11e6-92c6-ff7b9b9e34df.png">

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/19734163/1a1e6438-9bd9-11e6-891c-e1f124036885.png)

**Comment by mushon** [comment]
awesome! (the last one)
let's just keep the "Let's go" in full opacity. ok?

**Comment by cqx931** [comment]
cool, I will implement this.

**Comment by cqx931** [comment]
Please check https://github.com/dhowe/AdNauseam/pull/549

**Comment by mushon** [comment]
awesome. merged. thanks!
