### ISSUE TITLE
Send most common user-agent instead of none, when noOutgoingUserAgent is true

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#501]
Should be: "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.85 Safari/537.36"

from http://www.browser-info.net/useragents

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/503 please check
