### ISSUE TITLE
DuckDuckGo Text ads failing

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#505]
https://duckduckgo.com/?q=best+credit+card&t=h_&ia=web

![screen shot 2016-10-12 at 11 50 05 am](https://cloud.githubusercontent.com/assets/737638/19296869/14e87520-9072-11e6-92a8-1eb59e3f9a14.png)

Note that may need to disable the DNT list to debug this...

**Comment by dhowe** [comment]
onhold for now

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/commit/61a9ac2ed70c19f33e617b01d1b5dd2ff7d4d903
