### ISSUE TITLE
Don't block cookies for ADN-allowed requests if domain is on DNT list

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#507]
see #301

**Comment by dhowe** [comment]
Please make sure this is covered in #555

**Comment by dhowe** [comment]
So the case here is: there is a domain on the DNT list, for which a rule exists on a filter-list that is not allowed to block (for example, EasyList). So, when we get a request from such an adn-allowed host, we usually block the incoming cookies (as uBlock, for example, would not even allow the request in the 1st place). However, in the DNT case, we need to allow such cookies.

So, we need a test example for this...

**Comment by cqx931** [comment]
I didn't understand what this means "a rule exists on a filter-list that is not allowed to block". You mean not blocking cookies from the request if it is blocked from our lists? If the request is always allowed, do we still want to allow such cookies?

**Comment by dhowe** [comment]
https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#what-is-the-relationship-between-blocking-and-hiding-rules-in-ublock-and-adn

**Comment by dhowe** [comment]
If the request is _adn-allowed_, its cookie is usually blocked. However, if the request is ALSO on a DNT list, then the cookie should not be blocked.

**Comment by dhowe** [comment]
Note: we can likely test this by creating a custom list with DNT domains on it, as long as one of them tries to set a cookie

**Comment by cqx931** [comment]
Do we still want this for Release 3.2?

**Comment by dhowe** [comment]
Do we have a test for this in the release checklist ?

**Comment by cqx931** [comment]
It is in the release checklist, but we never tested it nor implement this due to lack of testing cases.
Maybe we can add one of our servers (ex:rednoise.org) to the DNT list and put this cookie-setting test in a folder called "ad".
Easylist has `.org/ad/` as blocking rule...So something like "http://rednoise.org/ad/cookie-setting-ad.html" can be a valid url for this case.

**Comment by dhowe** [comment]
sounds good... make it so :)

**Comment by cqx931** [comment]
All the testcases are now on http://lab-lamp.scm.cityu.edu.hk/adntest/, but I think it might influence the other tests if we add lab-lamp to DNT? 
Another option is to put `@@||lab-lamp.scm.cityu.edu.hk/adntest/abmw/^$third-party ` to our own dnt list, as `/abmw/*` can also trigger Easylist.

**Comment by dhowe** [comment]
Whatever you think is best -- we just need the test so that we can check implementation...

**Comment by cqx931** [comment]
There is one point that I is not clear for me:
Ex: `http://pixel.rubiconproject.com/tap.php` is an [Easylist allowed] request.
On page `http://lab-lamp.scm.cityu.edu.hk/adntest/dntCookieTest.html`, I am making a request to the above address.
To create this case, should I add `rubiconproject.com` or lab-lamp to DNT allowed domain?

**Comment by dhowe** [comment]
Yes, when a site is whitelisted b/c of DNT, all 3rd parties are also allowed (per the spec)
Lets add rednoise.org (conditionally) to our DNT list whenever the PRODUCTION flag is false

**Comment by dhowe** [comment]
- [ ] Please verify logging for 3rd-party requests which are allowed on a DNT site (should log 'allow')
- [ ] Please verify that no cookies are blocked for same (3rd-party sites found on DNT pages)

**Comment by cqx931** [comment]
This can be closed by now
