### ISSUE TITLE
DNT header still added, even when both clicking and hiding are disabled

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#510]
if both clicking/hiding are disabled, then DNT should not be enabled, and header should not be sent

**Comment by dhowe** [comment]
Similarly, when AdNauseam is paused on a site, I think we don't want to send DNT -- or maybe this is incorrect?

**Comment by cqx931** [comment]
I get the clicking/hiding preferences, but not the pausing... 
How is pauseAdNauseam being handled? I see that users can pause on a whole site or just the current page... I tried to find the corresponding code but failed.

**Comment by dhowe** [comment]
Basically the site (or page) just ends up in your whitelist when you pause adn.

**Comment by cqx931** [comment]
please check https://github.com/dhowe/AdNauseam/pull/517
