### ISSUE TITLE
Test our handling of reddit.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#516]
Make sure that only ads are being hidden/collected...

**Comment by leoneckert** [comment]
so I can see that there is banner link(s) to (i guess) popular subreddits that are hidden. 

to be fair, it's inside the divs with class/id "ad_sponsorshipbox" and "ad_sponsorship". 

...I find that interesting actually; I doubt they do it on purpose, but it's practically an obfuscation strategy against adblockers, labelling more content to be ads than actually is - random thoughts :)

**should I write exceptions for those?**

<img width="752" alt="screen shot 2016-10-19 at 15 48 46" src="https://cloud.githubusercontent.com/assets/14130931/19534879/93f1bb6e-9613-11e6-8d7d-68be14cef18d.png">

**Comment by leoneckert** [comment]
the exception would be `reddit.com#@#.sponsorshipbox`. As of yet unsure, but it does not seem like this would also allow actual ads to show, can pr any time. 

I also noticed there are 'ads' collected and clicked, that seem like they must be links from reddit posts (they link to youtube videos etc.), but the strange thing is I can not even see them on the page when toggling cosmetic filters...

**Comment by dhowe** [comment]
Our baseline should be whatever uBlock does, unless there is a strong reason to do otherwise. Do they block or hide these?

**Comment by leoneckert** [comment]
how can I find out whether something is blocked or hidden?

uBlock also hides/blocks the sub reddit banner 'ad', so i guess that's fine. 

just wondered where those images come that are being collected (screenshot below) and just found out. 
<img width="1335" alt="screen shot 2016-10-19 at 16 40 59" src="https://cloud.githubusercontent.com/assets/14130931/19536655/dc386d94-961a-11e6-8300-c479c3904951.png">

there is always this 'promoted ad' on top of reddit which is rightfully hidden. the little arrows in the same box let the user flick through actual reddit posts. So those posts are the ones that are being collected as ads. uBlock does the same (though they are definitely not ads).

<img width="679" alt="screen shot 2016-10-19 at 16 56 28" src="https://cloud.githubusercontent.com/assets/14130931/19537267/52e570e8-961d-11e6-9803-073f7de761df.png">

**Comment by dhowe** [comment]
> how can I distinguish between something blocked or hidden?

really? use the logger

**Comment by leoneckert** [comment]
my bad, the images I mean are then only hidden. They do not sure up red in the logger.

**Comment by leoneckert** [comment]
okay i understand reading the logger much better now. 

So on reddit there is three elements that are being hidden (all by Easylist rules) but not blocked:
1) one of them is clearly and ad
2) one is never an add, it's a banner inking to a subreddit, uBlock hides it too.
3) the last one is a slider with several elements, all are hidden, but only one is sometimes an ad. 

I can write exceptions, e.g for 3) to not hide the slider itself, but try looking for that one occasional ad inside it. 

However, as I said, uBlock has the same behaviour, so I will leave it the way it is unless you instruct otherwise.

**Comment by dhowe** [comment]
yes, lets leave as is for now, at least until all other 3.4 issues are resolved
