### ISSUE TITLE
Export/Import buttons disappear with more than one notification in dashboard/settings

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#518]
![screen shot 2016-10-13 at 8 08 02 pm](https://cloud.githubusercontent.com/assets/737638/19348501/ca974db0-9180-11e6-925b-caa068fb368a.png)

**Comment by leoneckert** [comment]
Working on this. It's strange, it seems to me that dashboard height is defined as 100% when the page is rendered. Then, when the notification are added through shared.js, the height doesn't update and the buttons are pushed out of it at the bottom. 
I'll see of that assumption is right and I can change it.
