### ISSUE TITLE
Dashboard tab-button problem

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#525]
To recreate:
- open dashboard via menu
- switch to whitelists (or any other tab in dashboard)
- switch to new non-adnauseam tab in browser
- open menu and click settings
- try to click 'settings' tab (fails)

Theory: clicking menu::settings resets some current-tab variable to dashboard::settings, even though you are no longer on that tab when returning to an already open dashboard

**Comment by leoneckert** [comment]
sending PR for two slightly different solutions to that

**Comment by leoneckert** [comment]
SOLUTION 1
**scenario:** 
user opens dashboard
clicks on whitelist
opens new non-adn tab
click menu > settings
the *old* dashboard (chrome-)tab goes active again, but actually changes to the settings (dashboard-)tab (away from the before selected whiteboard tab).

**Comment by leoneckert** [comment]
SOLUTION 2
scenario: 
- user opens dashboard
- clicks on whitelist
- opens new non-adn tab
- click menu > settings
- the old dashboard (chrome-)tab goes active again, the whiteboard (dashboard-)tab is still open, but now the user can actually click on 'Settings'

**Comment by dhowe** [comment]
solution 2 merged
