### ISSUE TITLE
More consistent look/feel for toggle buttons in UI

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#530]
Large toggle buttons have a completely different (modern) look/feel, compared to the smaller HTML1.0 checkboxes circa 1995. Should be more consistent

![screen shot 2016-10-15 at 6 45 00 pm](https://cloud.githubusercontent.com/assets/737638/19409511/87d04300-9307-11e6-9175-d619a825838b.png)

**Comment by mushon** [comment]
@dhowe I just pushed a branch for the custom checkboxes: https://github.com/dhowe/AdNauseam/commit/4ba692ea9e342e447742c5e7c3ad269bf0db0a6a
However please note that this implementation in 3rd party lists doesn’t allow checkboxes for some reason. I added an extra icon link and moved the text to a label. But still the checkbox doesn't switch. Please take a look, as I burned a few hours on this and need a pair of fresh eyes to mull it over (feel free to change whatever). Thanks.

**Comment by mushon** [comment]
ok, I know how to fix it the problem is with the ``for`` attribute on the labels. I'll push a fix soon.

**Comment by dhowe** [comment]
👍

**Comment by mushon** [comment]
also I need to add an SVG for the ✔
