### ISSUE TITLE
Create FAQ entries for each info (i) icon on Dashboard/Settings page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#531]
Please also:
- add an info (i) icon for the 'Block malware and non-visual trackers' text, and then create the corresponding FAQ entry
- add an info (i) icon for the EFF list on the 'Whitelists' pane, and then create the corresponding FAQ entry

![screen shot 2016-10-15 at 6 58 11 pm](https://cloud.githubusercontent.com/assets/737638/19409584/70df298e-9309-11e6-907d-008b7efb124b.png)

**Comment by leoneckert** [comment]
For the hide/click/EFF-whitelist, I would write
one paragraph about DNT mentioning that ADN lets you decide wether or not to hide/click. And then link all three `i` to that entry. 

For the Blocking malware, I would rewrite the [malware paragraph from ABP](https://adblockplus.org/features#malware).

Does that sound good or is there any further information I should include?

**Comment by dhowe** [comment]
So should be 4 separate short paragraphs, each its own FAQ entry.

* How exactly does AdNauseam "hide Ads"?
* How exactly does AdNauseam "click Ads"?
etc.

Give it a try in this ticket, and then I will tweak/update...

**Comment by leoneckert** [comment]
## How does AdNauseam "hide Ads"?

In contrast to other ad blockers, AdNauseam does not block conventional, visual ads, but hides and clicks them instead. This is done as safely as possible, with cookies and other ientifiers disabled.  
Hiding itself does not prevent resources from being downloaded, but only impacts the sites's final rendering in your browser. Therefore, Hiding Ads has no value in regards to your privacy, but simply removes unwanted visual content.

Based on a set of rules ('cosmetic filters') that are constantly hand-adjusted to the ever changing structure of websites, CSS is used to render detected ads invisible. The rules are listed in various filter lists which can be individually de-/activated in AdNauseam's settings/3rd-party-filters panel. In addition to that, the hiding behaviour as a whole can also be toggled in the settings.


## How does AdNauseam "click Ads"?

AdNauseam 'clicks' Ads by following the link attached to them. This is done through a '[XMLHttpRequest](http://www.w3schools.com/xml/xml_http.asp)' request that takes place in the background. The request signals a 'click' on the server responsible for the ad, but takes place without visually opening any additional window or page on the client's computer. AdNauseam's clicking behaviour can be de-/activated in the settings panel.



## How does AdNauseam "block  malware"?

Visual ads are not blocked by AdNauseam, but rather hidden and clicked. However, content detected as malware as well as non-visual trackers can be opted to be blocked from making requests altogether. 
The detection of links to domains that are known to spread malicious content is based on filter lists that can be individually de-/activated in AdNauseam's settings/3rd-party-filters panel. In addition to that, the blocking behaviour as a whole can also be toggled in the settings.

**Comment by leoneckert** [comment]
suggestion for the first three, entry for EFF list on the 'Whitelists' pane still pending.

**Comment by leoneckert** [comment]
## EFF Do Not Track (DNT) Whitelist

DNT is a technology by the Electronic Frontier Foundation (EFF). Most browsers give the option to attach a DNT flag to the header of each request sent, asking the receiving website "to please not track" the client. As of yet, websites do not have to respect this bid ([exact policy](https://www.eff.org/dnt-policy)) and in fact many of them don't. A list of popular ones that claim to do, however, is updated regularly by the EFF. 
AdNauseam allows to whitelist those sites. Options are to (1) either not clicking ads served on DNT listed sites as will as Ads served by those sites as third parties on other sites, (2) not hide ads in the same two cases, (3) or both. 
The current list can be found on [https://www.eff.org/files/effdntlist.txt](https://www.eff.org/files/effdntlist.txt).

**Comment by leoneckert** [comment]
As soon as those texts are approved I can insert the links from the (i) icons. Let me know if I got something wrong or should make any changes

**Comment by leoneckert** [comment]
bringing the info icon for malware into place turned out to be less straight forward than expected because it is technically a different element than the ones holding icons above. 
In https://github.com/dhowe/AdNauseam/pull/559 I suggest a few html, css changes to make it look like this:
<img width="1077" alt="screen shot 2016-10-29 at 16 18 30" src="https://cloud.githubusercontent.com/assets/14130931/19832544/f410b35a-9df3-11e6-926b-fb70ecc930c0.png">

**Comment by leoneckert** [comment]
whitelist icon (as seen below) in PR https://github.com/dhowe/AdNauseam/pull/563 , awaiting approval for linking above FAQ entries
<img width="772" alt="screen shot 2016-11-01 at 19 58 38" src="https://cloud.githubusercontent.com/assets/14130931/19911986/9ffb9b6e-a06d-11e6-8bb4-e1d9aaa66434.png">
