### ISSUE TITLE
Better contact-us icon on website

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#533]
the website is slightly schizophrenic in terms of color, and this icon has always felt a bit retro as well

![screen shot 2016-10-17 at 10 19 10 am](https://cloud.githubusercontent.com/assets/737638/19424293/6ad25b4a-945a-11e6-9c82-e5c158bc95ad.png)

**Comment by cqx931** [comment]
Just the color?

![image](https://cloud.githubusercontent.com/assets/3056154/19594033/e59e2616-97b5-11e6-8ffa-0cf164233a10.png)

**Comment by cqx931** [comment]
closed for now
