### ISSUE TITLE
Don't include old ads in menu when none found in current visit

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#534]
When loading a page for a second time, there are 4 possible cases (after waiting some undetermined amount of time):
1. no ads found
2. new ads found 
3. duplicate ads found (same as previous load of the page)
4. some mix of 2. and 3.

The question is what to show in the menu while the page is loading (before new ads are found). Options, until at least one ad is found, are:
- Nothing from the past 
- Past ads for that page (current)
- Most recent ads from all pages

Related question is what to do with cases 3. and 4. above, when we encounter duplicates. Do we:
- ignore them (as is currently the case)
- update the original's timestamp, then treat it as a new ad, broadcasting the new ad message
- store multiple timestamps for the ad (and treat it how?)

Thoughts?

**Comment by cqx931** [comment]
In general, I would expect to see what adNauseam has found on the current page in the menu.

While the page is loading (before new ads are found), I think the current display is good.

Though for duplicates, I think it makes more sence to show them in menu. 
So this solution sounds good to me:
update the original's timestamp, then treat it as a new ad, broadcasting the new ad message

**Comment by mushon** [comment]
Yes, I started crafting a similar response yesterday.
I think we should keep it simple. We pack duplicates together in the vault, but here the view is more of a feed, so whatever add was identified last should appear in the menu, even if it has already been identified (and possibly visited) on a previous visit. I personally don't think we have to communicate that the ad was identified or visited before, and if we do I would be pretty explicit about it so to not confuse. For example, I would not use the corner count number as it implies a group of ads and does not comply with the feed model used by the menu. We could add to the ad item a note about previous identifications, but I would push it to "possible futures".

**Comment by dhowe** [comment]
The unintuitive, but relatively common case, that @cqx931 and I noticed last week, is when reloading a page, and seeing a number of ads as the page is loading, say 4 (from the previous load), then as soon as the page loads, it drops to 1 or 2, which appeared to suggest that ads were disappearing...

**Comment by mushon** [comment]
I understand, so if I understand correctly that also supports the solution that treats duplicates as new ads. Right?

**Comment by dhowe** [comment]
I'm not sure what you mean

**Comment by mushon** [comment]
I'm suggesting going with option 2 - show new ads
& then show past ads for that page under a header (Previous found ads?) even if it's repeating the ones we find on the current reload.

**Comment by dhowe** [comment]
that would require either keeping duplicates of the same ad in memory (which we don't now do) OR storing multiple timestamps for each ad (which we don't now do)

**Comment by mushon** [comment]
First let’s agree if that’s the way we want to do this.
Then we can discuss implementation. I think it would be ok to save timestamps and then show them on the vault each with its own timestamp. What would be the arguments against that?

**Comment by dhowe** [comment]
The vault is relatively easy... and timestamps are an implementation detail. Can someone want to propose a clear spec for the behavior we want?

**Comment by mushon** [comment]
Scenario / SPEC

1. User visits a page with 4 ads
2. the badge marks 4 ads
3. the menu shows the 4 pending ads and attempts to visit their target URLs.
4. After two targets are visited the user refreshes the page
5. the badge marks 4 ads - same ad spots as before
6. the menu shows the 4 pending ads and attempts to visit their target URLs, under these 4 appears a title: ``← 🌏 page title… / 4 ads identified (30s ago)`` and under it the 4 previous ads. Under them may appear another such heading like ``← 👿 page title… / 9 ads identified (2m ago)`` and under that 9ads. (← arrows are links emojis represent favicons)
7. This can go on for lets say 5 pages and under them a link to the vault: ``browse all 2325 ads in the ad vault``

This spec does not differentiate between new or repeat visits and instead separate the menu by page loads. I think this would serve as a much more straight forward approach to the menu than the one we currently use. What say you?

**Comment by dhowe** [comment]
This makes sense, but is a rather big set of changes. If needed, I would argue for doing this AFTER this release (which is already WAY overdue). 

In fact, I suggest we leave the menu behavior as is for now. Page refreshes are probably a relatively infrequent scenario and the correct data is being shown current anyway (it is only slightly disorienting when an ad count drops on a reload)

**Comment by mushon** [comment]
Couldn't agree more
