### ISSUE TITLE
theatlantic showing 'skip ad' button (not on ublock)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#536]
http://www.theatlantic.com/latest

![screen shot 2016-10-18 at 6 10 38 pm](https://cloud.githubusercontent.com/assets/737638/19473426/342a575a-955e-11e6-9049-a1a3c183ddde.png)

**Comment by cqx931** [comment]
To hide the 'skip ad' button is easy, but I find it hard to get rid of the welcome screen overlay without blocking the js. The inline-welcome screen script will add a class "welcome-screen-open" to the body and use the pseudo selector "after" to cover the whole body with a 0.5 opacity black layer. Later when the welcome-screen is over, it will remove this class from the body.

So in this case, I think we either get hide all the welcome screen content, being able to collect the ad but have a strange black layer showing for 3 seconds, or block the whole thing (inline-script from theatlantic) and sacrifice the ad inside it. The later one makes more sense to me, if there is no better solution.

**Comment by dhowe** [comment]
agreed, option 2

**Comment by cqx931** [comment]
fixed

**Comment by dhowe** [comment]
👍
