### ISSUE TITLE
large popup ad on https://kickass-top.com/

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#540]

**Comment by leoneckert** [comment]
mhm are you getting it consistently/still? For me it doesn't show up, not after clearing my browsing history or even in a profile without any extension.

**Comment by cqx931** [comment]
Same here, I can't recreate the situation as well.

**Comment by dhowe** [comment]
yes, I still see it. it is a full screen pop-under (a separate window)
you need to at least click in the search box, or possibly do a search

**Comment by leoneckert** [comment]
if I clear my browsing data (it only happens once after that) and then go to https://kickass-top.com and click a link, i get a popup window now, but it dissapears before I can even see it, so it seems like it's blocked for me already (I tried a lot of times and never got one that stayed). This is the line in the logger that I assume shows the blocking:

<img width="490" alt="screen shot 2016-10-21 at 19 00 57" src="https://cloud.githubusercontent.com/assets/14130931/19614229/d9bc868e-97c0-11e6-8038-34f398ad6b3c.png">

**Comment by dhowe** [comment]
I still see it every time after clearing cookies, as does @cqx931

**Comment by leoneckert** [comment]
strange, today I don't even get the popup that was blocked yesterday anymore.

**Comment by dhowe** [comment]
![screen shot 2016-10-23 at 5 53 24 am](https://cloud.githubusercontent.com/assets/737638/19622780/1eb4fca6-98e5-11e6-9738-fc1cd023b36e.png)

**Comment by cqx931** [comment]
doesn't seem to be blocked by me 
<img width="1041" alt="screen shot 2016-10-23 at 4 33 30 pm" src="https://cloud.githubusercontent.com/assets/3056154/19625003/9fb2a980-993e-11e6-8d4f-23242563cf10.png">

**Comment by leoneckert** [comment]
so when my Easylist is disabled, I get the popup and a lot of popup lines in the logger:
<img width="1440" alt="screen shot 2016-10-25 at 12 03 43" src="https://cloud.githubusercontent.com/assets/14130931/19693947/79275fae-9aab-11e6-9f30-3e3102f67bb2.png">

with Easylist active, the second popup request (marked above) seems to get blocked and then all th rest doesn't take place. 
<img width="1246" alt="screen shot 2016-10-25 at 12 06 01" src="https://cloud.githubusercontent.com/assets/14130931/19693995/a31e7b08-9aab-11e6-85b9-5cd9e1320f1d.png">

I did get a popup once, just after re-enabling Easylist (though that doesn't sound like a reasonable explanation for it). That looked like this: 

<img width="1247" alt="screen shot 2016-10-25 at 12 04 47" src="https://cloud.githubusercontent.com/assets/14130931/19694126/15e2077c-9aac-11e6-8596-5c4f01c8c9eb.png">

I will try to recreate that one and debug it, though it's not easy if it doesn't come consistently for me...

**Comment by leoneckert** [comment]
here is a solution: https://github.com/dhowe/uAssets/pull/10
As I said I could not recreate the exact problem as for me popups seem to be blocked already by Easylist. However I wrote this universal kickass-top.com thirdparty popup blocker `*$third-party,popup,domain=kickass-top.com` and tested with Easylist disabled.
