### ISSUE TITLE
Make sure all locale files are up-to-date...

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#545]
on crowdin and in the build

**Comment by cqx931** [comment]
@leoneckert Could you please check the German Translation into the latest update? Thanks! https://crowdin.com/translate/adnauseam/12/en-de

**Comment by leoneckert** [comment]
@cqx931 yes, doing it now

**Comment by leoneckert** [comment]
@dhowe general question for translations, in laguages (like German) in which there is two forms to say 'you' (that is 
- formal (dt. 'Sie' / spa. 'Ustedes') and 
- informal/casual (dt. 'du' / spa. 'tu'),
which tone is preferred for ADN? Personally think the informal version fits the purpose and general feel of the extension better, but wanted to make sure.

**Comment by cqx931** [comment]
Thanks! @leoneckert 

Please check here for the latest update: https://github.com/dhowe/AdNauseam/pull/560

**Comment by cqx931** [comment]
https://crowdin.com/translate/adnauseam/12/en-de
Please check the latest change @leoneckert

**Comment by cqx931** [comment]
All up to date and close for now.
