### ISSUE TITLE
Convert HTML entity symbols in menu/vault

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#547]
![screen shot 2016-10-26 at 2 13 55 pm](https://cloud.githubusercontent.com/assets/737638/19715290/b2c6c9a8-9b86-11e6-8eff-f9569c421ca4.png)

**Comment by leoneckert** [comment]
sent a new appraoch to the problem with what seems to be a more secure way to do it. Found on http://stackoverflow.com/a/9609450

**Comment by leoneckert** [comment]
testing on real world examples I notice these show up: 

<img width="227" alt="screen shot 2016-10-29 at 15 03 18" src="https://cloud.githubusercontent.com/assets/14130931/19832102/e6957ee6-9de8-11e6-9bfd-67b3da949580.png">
<img width="229" alt="screen shot 2016-10-29 at 15 02 47" src="https://cloud.githubusercontent.com/assets/14130931/19832103/e91510b4-9de8-11e6-9ed7-6b33d9682c09.png">

I'll deal with them, is this an AdNauseam mechanism?

**Comment by leoneckert** [comment]
this is done

**Comment by dhowe** [comment]
it appears our visits to sites outside of facebook from fb ads are being served a confirmation page ("are you sure you want to leave facebook?" Please verify  by cutting/pasting into the browser, and create a new ticket ('external visits fail on facebook'...)
