### ISSUE TITLE
Generate a benchmark graph for the FAQ page

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#551]
Use only 3 bars:
- no-blocker
- Adnauseam
- AdBlock Plus

**Comment by mushon** [comment]
Also, if you can add more fineprint that will validate the methodology of the benchmark that would be great.

**Comment by cqx931** [comment]
what exactly shall be covered? Similar to the metrics?

Metrics

Number of 3rd-parties contacted
Overall memory footprint (MB)
Total page load time (sec)

**Comment by mushon** [comment]
We only need the total page load

**Comment by cqx931** [comment]
Something like this?
![picture1](https://cloud.githubusercontent.com/assets/3056154/19795755/33d55dda-9d11-11e6-8f22-4b1adf936bb2.png)

**Comment by mushon** [comment]
That looks great! 
Which is actually a problem…

I was thinking of something very dry and direct, coming directly from a spreadsheet, and definitely not-designed (which some may interpret as “doctored") exactly like this one only with the first 3 bars instead of 6:

![image](https://cloud.githubusercontent.com/assets/2461812/17919748/3dcbddc4-6a02-11e6-9d46-72fd194af0ca.png)

The order should be:

1. No Bloker
2. Adblock Plus
3. Adnauseam

Thanks.

**Comment by cqx931** [comment]
![picture1](https://cloud.githubusercontent.com/assets/3056154/19797217/5e69852a-9d1c-11e6-8f14-4356030de5e7.png)

**Comment by mushon** [comment]
Right.
Though we had better stats before, no?
This doesn’t support the claim that we’re more than twice as fast as with no blocker.
Any reason not to use the previous stats?
-- 
Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

**Comment by cqx931** [comment]
Yes, the older stats are different.
The above graph is from the test I did today and I did have all the right settings in my browser. 
There could be performance difference though, since in the current workflow we only run each site for 3 times... without blocker, si.com alone can have a performance difference from 10 seconds to 40 seconds to load( most content are loaded, but you can still see the spinning wheel... )
Or we could replace si.com with another test case...

**Comment by mushon** [comment]
is there some formal set of sites we test on?

**Comment by cqx931** [comment]
This is the current test list:

http://www.si.com
https://search.yahoo.com/search?p=watch
http://news.google.com/
http://www.huffingtonpost.com/
http://www.cnn.com/
http://www.nytimes.com/
http://www.foxnews.com/
http://www.nbcnews.com/
http://www.dailymail.co.uk/
http://www.washingtonpost.com/
http://www.theguardian.com/
https://news.ycombinator.com/

**Comment by mushon** [comment]
Is it based on the 10 most popular sites or something?

-- 
Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

On October 28, 2016 at 10:54:26 AM, cqx931 (notifications@github.com) wrote:

This is the current test list:

http://www.si.com
https://search.yahoo.com/search?p=watch
http://news.google.com/
http://www.huffingtonpost.com/
http://www.cnn.com/
http://www.nytimes.com/
http://www.foxnews.com/
http://www.nbcnews.com/
http://www.dailymail.co.uk/
http://www.washingtonpost.com/
http://www.theguardian.com/
https://news.ycombinator.com/

**Comment by cqx931** [comment]
no I don't think so...they are mainly news sites with many visual ads.

**Comment by mushon** [comment]
I know this is a tricky thing and I know (and kinda like) that this discussion is public, but I wish we could come up with a clear and decent methodology that could still support our (previously supported) claim that using ADN loads pages more than twice faster.

:)

-- 
Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

On October 28, 2016 at 12:15:49 PM, cqx931 (notifications@github.com) wrote:

no I don't think so...they are mainly news sites with many visual ads.

**Comment by cqx931** [comment]
A list based on most popular sites sounds reasonable for me. 
But not all of them have ads, or visual ads. And it is also not reasonable to test this on the homepage of a video sites...
So maybe we can create a new website list based on either alexa topsites global or the country list for US and then pickup those with visual ads? @dhowe 
http://www.alexa.com/topsites/global;0

Another thing that I want to mention about this testing workflow is gmail account... Because many ads are provided by google, you tend to see way more ads from all websites if you once logged in with gmail and the browser remembered that...( that can also be a possible reason why Cyrus has a longer loading time by no blocker) Not sure whether we should include or exclude this in our settings.

**Comment by dhowe** [comment]
can we experiment with different values for these parameters?

**Comment by cqx931** [comment]
Alexa Global top 50 sites

- [ ] 1.Google.com (Text)
- [ ] 2.Youtube.com (Video & Image)
- [ ] 3.Facebook.com(Post & Image)
- [ ] 4.Baidu.com(Text & Image)
- [ ] 5.Wikipedia.org(No Ad)
- [ ] 6.Yahoo.com(Image)
- [ ] 7.Google.co.in
- [ ] 8.Twitter.com(Post & Image)
- [ ] 9.Amazon.com(Image)
- [ ] 10.Qq.com(Image)
- [ ] 11.Google.co.jp
- [ ] 12.Live.com(No Ad)
- [ ] 13.Taobao.com(trackers)
- [ ] 14.Linkedin.com(Image)
- [ ] 15.Vk.com(Russian)
- [ ] 16.Instagram.com(No Ad)
- [ ] 17.Hao123.com(Images & links)
- [ ] 18.Sohu.com()
- [ ] 19.Sina.com.cn(Image)
- [ ] 20.360.cn(no obvious ad on homepage) 
- [ ] 21.Weibo.com(Image)
- [ ] 22.Google.de
- [ ] 23.Tmall.com(Image)
- [ ] 24.Reddit.com(Image)
- [ ] 25.Google.co.uk
- [ ] 26.Google.com.br
- [ ] 27.Yahoo.co.jp
- [ ] 28.Google.fr
- [ ] 29.Yandex.ru(Russian)
- [ ] 30.Google.ru
- [ ] 31.Onclickads.net(Ad company...)
- [ ] 32.T.co
- [ ] 33.Ebay.com(Tracker)
- [ ] 34.Soso.com(Search Section)
- [ ] 35.Wordpress.com
- [ ] 36.Bing.com (Text)
- [ ] 37.Blogspot.com(Tracker)
- [ ] 38.Tumblr.com(Image)
- [ ] 39.Google.it
- [ ] 40.Stackoverflow.com(Image)
- [ ] 41.Google.es
- [ ] 42.Msn.com (Image)
- [ ] 43.Gmw.cn(Image)
- [ ] 44.Microsoft.com(No obvious ad)
- [ ] 45.Aliexpress.com
- [ ] 46.Apple.com (No Ad)
- [ ] 47.Pinterest.com  (No Ad)
- [ ] 48.Google.com.mx
- [ ] 49.Netflix.com
- [ ] 50.Paypal.com

**Comment by dhowe** [comment]
status, @cqx931 ?

**Comment by cqx931** [comment]
I thought we are going trying to agree on "a clear and decent methodology that could still support our (previously supported) claim that using ADN loads pages more than twice faster."...

My opinion is to get rid of http://www.si.com at least, and get a longer test list with more repetitions. And I can see whether my test result still support the claim or not.

**Comment by dhowe** [comment]
sounds good

**Comment by cqx931** [comment]
So here comes a new test result with the top 15 news websites that was also used as an example in sessbench.

![picture1](https://cloud.githubusercontent.com/assets/3056154/20352745/5e0dea12-ac53-11e6-8e5d-90e52aa0148c.png)

When it comes to the number, this still can't support the twice faster statement and it is actually slower than the last test I did.The fix of header for the cookies ticket could potentially influenced the performance.

**Comment by cqx931** [comment]
As for the test procedure I currently used sessbench and borrowed some code from the "Page Load Time" extension to get the load time result. Nightwatch could also be helpful for the automatization of this metric workflow, but I need to check this after the collecting script.

**Comment by dhowe** [comment]
What browser settings are used in the above test? Flash, 3rd-party cookies, etc?

**Comment by cqx931** [comment]
flash and 3rd party cookies are both disabled according to the metric ticket.
Before each test, the browsing history is also cleaned up.

**Comment by dhowe** [comment]
I'm curious how enabling 3rd-party cookies (the browser's default) affects the results?

**Comment by mushon** [comment]
I also think it makes sense to turn on Flash, as some sites may use Flash ads and a huge majority of browsers are still Flash enabled. 

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by dhowe** [comment]
all similar testing by addons are done with flash disabled

**Comment by cqx931** [comment]
3rd-party cookies do have a slight effect on the result, but it is quite tiny on a testing list of 15 websites.
In average, I can see 3 seconds more loading time for no blocker and roughly 1 second more for AdNauseam. 
Flash doesn't really have an influence on this specific testing list.

**Comment by dhowe** [comment]
For the full-set of benchmark comparisons we should also probably include Opera's built-in blocker...

**Comment by dhowe** [comment]
Lets try to get these posted in the FAQ soon

**Comment by mushon** [comment]
I changed the wording in the press release to: "and nearly twice faster than with no ad blocker installed"

**Comment by mushon** [comment]
let's keep benchmarks to the FAQ page

**Comment by cqx931** [comment]
a latest benchmark graph

Date:2017.01.06
AdNauseam Version: 3.0.2
Ad Block Plus Version:1.12.4

Settings: Both Flash and third-party cookies are disabled
List of Website:
http://news.yahoo.com/
http://www.cnn.com/
http://news.google.com/
http://www.nytimes.com/
http://www.foxnews.com/
http://www.theguardian.com/
http://www.nbcnews.com/
http://www.dailymail.co.uk/
http://www.usatoday.com/
http://www.washingtonpost.com/
http://www.wsj.com/
http://www.abcnews.go.com/
http://news.bbc.co.uk/
http://www.latimes.com/

I did this one in school, so in general the total loading time seems to be longer than the one I did at home. But the percentage is very similar to the last one.
![image](https://cloud.githubusercontent.com/assets/3056154/21710848/1f68d22c-d426-11e6-81e8-f7f8fb64ff0d.png)

**Comment by dhowe** [comment]
I don't like how close we are to abp (worse than before) ... is this with flash and 3rd party cookies disabled?

**Comment by cqx931** [comment]
The following sites always take a relative longer time to load, (almost the same or even a bit longer than no blocker)
http://www.abcnews.go.com/
http://www.nbcnews.com/
http://www.cnn.com/
http://www.foxnews.com/

What are the exact things that make adnauseam load faster?
It's quite straight forward for me the uBlock's page load time is shorter, as it blocks many requests...
We do block beacon and some other requests, but at least for these pages, requests are rarely blocked.
Will hiding ads save some rendering time?


For other sites, there could be some max

**Comment by dhowe** [comment]
possibly, but the big time wins comes from blocks... 

Strategy: identify requests that are blocked by ublock but not adn, that don't result in visual ads, then  add rules for these to adnauseam.txt

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/issues/740

**Comment by dhowe** [comment]
how does this affect the metrics?

**Comment by cqx931** [comment]
Quite a lot. This time it looks much better.
![image](https://cloud.githubusercontent.com/assets/3056154/21835312/fb6bbea0-d7f6-11e6-8777-030819723d0e.png)

**Comment by dhowe** [comment]
"Ad Block Plus" should be "Adblock Plus". Can you update and then add the image to the FAQ (with a note about what we are testing) to [this question](https://github.com/dhowe/AdNauseam/wiki/FAQ#what-is-adnauseams-performance-like-will-it-speed-up-or-slow-down-my-browsing).

**Comment by cqx931** [comment]
Added, please check https://github.com/dhowe/AdNauseam/wiki/FAQ#what-is-adnauseams-performance-like-will-it-speed-up-or-slow-down-my-browsing

**Comment by cqx931** [comment]
One more try with uBlock.
I turned off ad clicking this time.It can has a minor influence on the page loading time...
![image](https://cloud.githubusercontent.com/assets/3056154/21926048/15dcc980-d9bb-11e6-9e5c-9ce7e2fa76ba.png)

**Comment by cqx931** [comment]
close for now, reopen when needed.
