### ISSUE TITLE
Test all aspects of DNT handling

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#555]
- [x] helloforos.com -> requests from other server to other server get blocked?
- [x] act.eff.org (domain)
- [x] eff.org (domain:nothing get blocked)
- [x] do-not-tracker.org (domain:nothing get blocked)
- [x] do-not-track.org (domain:nothing get blocked)
- [x] firstpartysimulator.net 
- [x] firstpartysimulator.org (domain)
- [x] meta.discourse.org (domain)
- [x] try.discourse.org (domain:nothing get blocked)
- [x] avatars.discourse.org (3rd party)
- [x] 99designs.community (domain)
- [x] circleforum.squarespace.com (domain)
- [x] safenetforum.org  (domain:nothing get blocked)
- [x] twittercommunity.com (domain:nothing get blocked)
- [x] duckduckgo.com (domain, 3rd party)
- [x] duckduckhack.com (domain:nothing get blocked)
- [x] elyotherm.fr (domain)
- [x] codepoints.net (domain:nothing get blocked)
- [x] geeek.org (domain:nothing get blocked)
- [x] itsgoingdown.org (domain:nothing get blocked)
- [x] medium.com (domain:nothing get blocked)
- [x] redforts.com (domain:nothing get blocked)
- [x] wpstagecoach.com (domain:nothing get blocked)

thefitrv.com -> can't access the site...
movieflix.to
login.persona.org
persona.org
-> These are shutting down

**Comment by cqx931** [comment]
close for now

**Comment by dhowe** [comment]
Please test all aspects of DNT (quite probably there are issues):

- [ ] Hiding when domain is 1st-party
- [ ] Hiding when domain is 3rd-party
- [ ] Clicking when ad domain is on list
- [ ] Blocking when domain is 1st-party
- [ ] Blocking when domain is 3rd-party
- [ ] Enabling/disabling of DNT rules on all permutations of first-run page options

**Comment by cqx931** [comment]
am I suppose to this for the following test items?
- That DNT domains appear in whitelist.html entries when either DNT option is checked
- That DNT domains are removed from whitelist entries when when neither DNT option is checked

![image](https://cloud.githubusercontent.com/assets/3056154/21490733/2e098d90-cc32-11e6-9b89-5308c0a2cb29.png)

The DNTdomains array is always in length 0 for me, did I miss anything to get this working? I am testing with the dnt-dch branch and the most up-to-date uAssets.
![image](https://cloud.githubusercontent.com/assets/3056154/21491004/6339a674-cc34-11e6-81f3-d5cbc371915f.png)

**Comment by cqx931** [comment]
DNT header is not being sent for ad request

**Comment by dhowe** [comment]
create one or more tickets (for related things), then we can fix ...

**Comment by cqx931** [comment]
Question: What about outgoing cookies from a 1st-person DNT-domain? These should be allowed iff disableHidingForDNT is checked... ?

I think this should goes with the setting "Don't send cookies on visits"

**Comment by cqx931** [comment]
when using the "disable cosmetic filter" feature from uDom, ads won't be collected, therefore not able to be clicked as well.
https://github.com/dhowe/AdNauseam/commit/b7dcf66d3c1031d72e4f7a09ca3dab6e8bc2fdbc

**Comment by dhowe** [comment]
This is not about ad visits. This is about cookies sent from a page-load. So we need to verify that no cookies are blocked when the DNT domain is either 1st or 3rd person.

**Comment by cqx931** [comment]
Currently cookies are allowed from DNT sites, no matter what the DNT settings are.

**Comment by dhowe** [comment]
If the request would be blocked by ublock, but is instead allowed by Adn, then the cookie should be blocked as well. You may have to find (or create) a good test case...

**Comment by cqx931** [comment]
close this ticket and move to #507
