### ISSUE TITLE
Remove DNT from version 2.4

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#565]
- [x] comment list in External-Whitelists
- [x] comment dnt-options (2) in settings
- [x] comment dnt-option on firstrun page
- [x] disable auto-sending of DNT header

pending response from EFF

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/commit/3db7ca61c01f575d6f5e6879d180116d32c5475e
