### ISSUE TITLE
Add instructions for installing dev releases for each browser

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#571]
Add instructions for each here: https://github.com/dhowe/AdNauseam/wiki/FAQ#how-do-i-install-a-development-release-of-adnauseam

Then remove the 'coming soon' text

**Comment by leoneckert** [comment]
Is there anything specific I need to know about how to install them, or should I figure it out how to install thse formats (.crx / .xpi / .nex) myself and concisely describe my process?

**Comment by dhowe** [comment]
It should be pretty straight forward:
- download the file
- open extensions page
- drag in the downloaded extension file

the only issue is whether the developer mode must be enabled in chrome/opera, and whether a special build (developer or nightly) is required for firefox...

**Comment by leoneckert** [comment]
Done with this. 
Turns out, dev mode in chrome/opera is not required, while using Developer Edition of Firefox is.

**Comment by dhowe** [comment]
excellent
