### ISSUE TITLE
VAULT: notifications push timeline out of frame

### ISSUE THREAD

**Issue by leoneckert** [dhowe/AdNauseam#577]
1) in settings, disable hide, click and malware, so that the notifications on top of the page appear. 
2) open the vault. The timeline at the bottom is out of frame. Clicking reactivate in the notifications on top bring the timeline back up step by step.

<img width="1078" alt="screen shot 2016-11-04 at 17 25 54" src="https://cloud.githubusercontent.com/assets/14130931/20023034/c4935d0c-a2b3-11e6-8235-009d089f08a4.png">

**Comment by leoneckert** [comment]
fixed in PR https://github.com/dhowe/AdNauseam/pull/580

-> notification now don't push the timeline out of frame, however, the ads still center according to old rules (with notifications visible, the center is offset towards the bottom). It was clearer to do this in to seperate PRs, so we can keep this ticket open and I'll fix that, too.

**Comment by dhowe** [comment]
ok

**Comment by leoneckert** [comment]
this ticket should be done with above PR. This one makes sure the Ads' sizes are adjusted while the notifcations on top change (no need to refresh or resize the window to trigger the resize). 

my confusion came from the fact that the ads are in the exact center of the window, that means slightly off center when only regarding the space between the slider and the top. 

<img width="1165" alt="screen shot 2016-11-16 at 14 25 21" src="https://cloud.githubusercontent.com/assets/14130931/20362430/94b546f4-ac09-11e6-91a9-6f741048de0a.png">

That looks great without notifications, but the effect adds up the smaller the window is (e.g. when notifications are rendered):

<img width="1165" alt="screen shot 2016-11-16 at 14 25 16" src="https://cloud.githubusercontent.com/assets/14130931/20362462/b57e4354-ac09-11e6-885a-417765e1ddea.png">

For now I think it is fine after making sure they always appear in the right scale. If wanted I could make another ticket which positions them always in the center of the space between slider and top rather than the center of the whole window. 

I hope this makes sense, but maybe it's also too much detail that I am looking at here.

**Comment by dhowe** [comment]
@cqx931pls verify this fix...

**Comment by cqx931** [comment]
I think this is fine for now. 

> If wanted I could make another ticket which positions them always in the center of the space between slider and top rather than the center of the whole window.

We could leave what you proposed to the Release 3.0.
