### ISSUE TITLE
BING: ads not hidden

### ISSUE THREAD

**Issue by leoneckert** [dhowe/AdNauseam#578]
for me, ads on bing.com are not hidden:

<img width="1087" alt="screen shot 2016-11-04 at 17 12 18" src="https://cloud.githubusercontent.com/assets/14130931/20023218/0dfd19e6-a2b5-11e6-9bc4-82133407aea5.png">

**Comment by dhowe** [comment]
I don't see this issue (in Opera or Chrome). Please include the output from the ad-parser below

![screen shot 2016-11-05 at 10 52 09 am](https://cloud.githubusercontent.com/assets/737638/20027114/035ef464-a346-11e6-9a60-0a94376adc18.png)

**Comment by dhowe** [comment]
@cqx931, pls check as well

**Comment by cqx931** [comment]
I also can't reproduce this issue in Chrome and Opera. The ads are hidden properly by me.

**Comment by dhowe** [comment]
and collected ?

**Comment by cqx931** [comment]
yes, hidden and collected.

**Comment by dhowe** [comment]
@leoneckert please create a brand new Chrome browser profile, install only AdNauseam (via the release), and test again...

**Comment by leoneckert** [comment]
very strange that I still get these (in a brand new profile). 
<img width="1185" alt="screen shot 2016-11-06 at 19 45 02" src="https://cloud.githubusercontent.com/assets/14130931/20043325/8907e8e6-a459-11e6-9036-6d16b7b54a11.png">

**Comment by leoneckert** [comment]
one pattern I observe -- and maybe one of you can explain what is going on here -- is that `.b_ad` is ALWAYS hidden according to the logger (I am aware that the two yellow Filters in there mean the same thing), however the Ads on the page are ONLY ACTUALLY HIDDEN/not visible if there is a blocked beacon right afterwards (screenshot2).
(screenshot1)
<img width="1307" alt="screen shot 2016-11-06 at 20 42 15" src="https://cloud.githubusercontent.com/assets/14130931/20044013/b510f212-a462-11e6-8852-72560fd49ff2.png">

(screenshot2)
<img width="1268" alt="screen shot 2016-11-06 at 20 41 59" src="https://cloud.githubusercontent.com/assets/14130931/20044010/ac8af6c4-a462-11e6-8694-e2e2c57a286b.png">

**Comment by dhowe** [comment]
First, are you clearing your ads before testing (if not this would explain the fact that the parser is registering a collection, but the interface is not)? Either way, you need to have background.html (the addon console) open as well when you do tests like this.

Second, its a long-shot, but I suppose it is possible that there are location factors at play here... Does anyone have access to an NY-based proxy, so that @cqx931 and I can test?

**Comment by leoneckert** [comment]
@dhowe yes, Ads are collected, but NOT HIDDEN on a completely fresh install of ADN that has never seen or collected any ads before.
Here is a corresponding set of parser and background console:
background:
<img width="1000" alt="screen shot 2016-11-08 at 20 39 44" src="https://cloud.githubusercontent.com/assets/14130931/20124332/aa461ca8-a5f3-11e6-817d-1d8d700de7c6.png">
parser:
<img width="1000" alt="screen shot 2016-11-08 at 20 39 45" src="https://cloud.githubusercontent.com/assets/14130931/20124322/9ca7cee8-a5f3-11e6-986c-a8562b6bb68d.png">

And here is a crop the parser when refreshing the page from within the logger (which consistently DOES HIDE the ads), note the `;display: none !important;` that is successfully appended in this case.

<img width="929" alt="screen shot 2016-11-08 at 20 52 38" src="https://cloud.githubusercontent.com/assets/14130931/20124632/d1b4d3a4-a5f5-11e6-8c04-0ed745525262.png">

**Comment by leoneckert** [comment]
I am not sure if my description makes sense, but I noticed something new:

When I refresh the page with bing open, the cosmetic filter fires (according to the log).... but is then overwritten (I assume) and the Ads will always show up.

When I refresh the page from the logger (with bing actually not 'visible'/not in an active tag), then the cosmetic filter will not fire until I make the bing page active (click the tab), then it immediately fires (in the log) and the site is Ad free. 

From this is seems very obvious that the cosmetic filter fires too early. If it were to fire later,  the Ads would be hidden. 

...this just in case one of you has another idea I could try to solve this.

**Comment by dhowe** [comment]
whenever the DOM changes, our cosmetic filters should be re-applied... sounds like that is not happening?

**Comment by leoneckert** [comment]
yes seems like that is the case

**Comment by dhowe** [comment]
pushed to 3.0

**Comment by cqx931** [comment]
When I use a VPN from the states, I can reproduce this issue.
After comparing the element between what I can see from HK view and the US view, I figure out the following:
So this is how `b_ad` looks like in HK
![image](https://cloud.githubusercontent.com/assets/3056154/21413595/703b04f8-c833-11e6-97e0-7e041b1249cc.png)
And this is in US
![image](https://cloud.githubusercontent.com/assets/3056154/21413614/9a1a8a32-c833-11e6-89f0-267f930d5cc6.png)

So in US, after the hidden attribute is added, a script is triggered and added "visibility:visible !important;"
I was able to find out this script and block it from dynamic filtering.
Though I have some problem blocking it from static filter
`||www.bing.com/rms/BingCore.Bundle/jc,nj/3de0ddf1/0a84f106.js$script,domain=www.bing.com`

**Comment by leoneckert** [comment]
I am in Germany now, so can only verify with a VPN as well. Works great!

Without VPN (German internet access) I got one ad: it's gone with the new rule.
With VPN (American internet access) I got the same ads I got when still in NYC: it's all gone now with the new rule. 

Very cool @cqx931 !
