### ISSUE TITLE
AdBlocker check in Opera is not working

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#582]
1.uBlock and Ad Block Plus have different ID in opera. 
```
//opera
var uBlockId = "kccohkcpppjjkkjppopfnflnebibpida";
var adBlockPlusId = "oidhhegpmlfpoeialbgcdocjalghfpkp";
```

**Comment by cqx931** [comment]
//opera
    var uBlockId = "kccohkcpppjjkkjppopfnflnebibpida";
    var adBlockPlusId = "oidhhegpmlfpoeialbgcdocjalghfpkp";

**Comment by dhowe** [comment]
Lets add the IDs to vAPI-background.js

**Comment by cqx931** [comment]
Do we need a seperate vAPI-background.js for Opera? (all other things stay the same, just have different ID?)

**Comment by dhowe** [comment]
That is fine for now.

**Comment by cqx931** [comment]
yes, you are right. 'opr' doesn't exist when opera-specific APIs are not enabled .  
So I tried to use another method instead:
`navigator.userAgent.indexOf(' OPR/')`
Please check. https://github.com/dhowe/AdNauseam/pull/593/commits

**Comment by dhowe** [comment]
as I say in the ticket, this seems like a dirty/temporary fix...
for example, can the user change that user-agent string?
what about with one of the many user-level extensions for changing user-agents?

**Comment by cqx931** [comment]
I have done a few tests with different extension that can change user-agent settings in different browsers.
Most of these extensions only change the user-agent header sending to the server but don't influence the string locally. In one case I can see the user-agent string changed in the page console as well, but since the opera check is done in the background page, the userAgent String there is not influenced. 

But yes, another more reliable solution I came up with is using  `chrome.runtime.id` to check the ID of AdNauseam and tell whether it is opera or chrome.

**Comment by cqx931** [comment]
fixed now by using name instead of id
