### ISSUE TITLE
New Release Tests [Opera & Firefox]

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#588]
Opera
- [x] Interface
- [x] First-Run
- [x] AdBlocker
     - AdBlocker ID for Opera https://github.com/dhowe/AdNauseam/issues/582
- [x] Menu 
- [x] Vault
- [x] Notifications
     - Layout issue in menu, when AdNauseam is paused https://github.com/dhowe/AdNauseam/issues/589
- [x] Ad Hiding/Parsing
- [x] Dashboard
- [ ] Cookies
   https://github.com/dhowe/AdNauseam/issues/590
- [ ] Ad Visits (cookies)
 
Firefox

- [x]  Interface
- [x]  First-Run
- [x]  Menu
- [x]  Vault
 - Action buttons go off screen #595
- [x]  Notifications
 - Close one notification will cause all notifications disappearing #594
- [x]  Ad Hiding/Parsing
- [x]  Dashboard
 -  get blank settings page, when acessed by link/from menu, setting button #596
- [ ]  Cookies
- [ ]  Ad Visits

**Comment by cqx931** [comment]
- [x] Interface
- [x] First-Run
- [x] AdBlocker
     - AdBlocker ID for Opera https://github.com/dhowe/AdNauseam/issues/582
- [x] Menu 
- [x] Vault
- [ ] Notifications
     - Layout issue in menu, when AdNauseam is paused https://github.com/dhowe/AdNauseam/issues/589
- [x] Ad Hiding/Parsing
- [x] Dashboard
- [ ] Cookies
   https://github.com/dhowe/AdNauseam/issues/589
- [ ] Ad Visits (cookies)

**Comment by dhowe** [comment]
Why is #589 under 'cookies'  above?

**Comment by cqx931** [comment]
sorry, that was a mistake. Just fixed it to #590

**Comment by cqx931** [comment]
2.3.87
Firefox

- [x]  Interface
- [x]  First-Run
- [x]  Menu
- [x]  Vault
 - Action buttons go off screen #595
- [x]  Notifications
 - Close one notification will cause all notifications disappearing #594
- [x]  Ad Hiding/Parsing
- [x]  Dashboard
 -  get blank settings page, when acessed by link/from menu, setting button #596
- [x]  Cookies
- [x]  Ad Visits

**Comment by cqx931** [comment]
2.3.87
Opera

- [x]  Interface
- [x]  First-Run
- [x]  Menu
- [x]  Vault
- [x]  Notifications
- [x]  Ad Hiding/Parsing 
- [x]  Dashboard
- [x]  Cookies
- [x]  Ad Visits

Done. No Opera specific issues.
