### ISSUE TITLE
"AdNauseam is paused on this page" layout issue

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#589]
The black div for "Ad Nauseam is paused on this page" should cover to the bottom of the menu, when notifications are rendered. 
<img width="1070" alt="screen shot 2016-11-06 at 10 03 40 pm" src="https://cloud.githubusercontent.com/assets/3056154/20038338/e6e50332-a46c-11e6-9c90-8e2b948e3178.png">

**Comment by leoneckert** [comment]
@cqx931 can you give more instructions on how to recreate this? For me the notifications ARE also rendered in the menu AND the box reaches the bottom like this:

<img width="1462" alt="screen shot 2016-11-11 at 19 08 14" src="https://cloud.githubusercontent.com/assets/14130931/20233870/76937af8-a842-11e6-8fa2-f20a47b61931.png">

**Comment by cqx931** [comment]
hmm, this is very interesting. I am not sure why this black layer has an opacity of 100% by me.... but if you inspect "AdNauseam is paused on this page", you can see that this element is not covering the very bottom part of the menu( where the buttons are)

**Comment by cqx931** [comment]
correct the issue: What need to be fixed is to bring back the bottom settings button/uBlock button when there are many images in the menu that require the user to scroll down. (currently, setting button will be pushed out of the menu when scrolling is needed)

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/pull/618
