### ISSUE TITLE
Google text ads in Opera dev search

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#591]
https://dev.opera.com/search/?q=credit
(blocked in uBlock)

**Comment by leoneckert** [comment]
double check if above PR also solves this for you

**Comment by dhowe** [comment]
No, apparently not:

![Uploading Screen Shot 2016-11-12 at 6.54.20 pm.png…]()

**Comment by dhowe** [comment]
pushed to 3.0

**Comment by leoneckert** [comment]
Strange, for me it still works. - this one still says Release 2.4, but going from your comment, I'll come back to it post 2.4.

**Comment by dhowe** [comment]
ok

**Comment by dhowe** [comment]
@cqx931 do you still see this bug?

**Comment by cqx931** [comment]
I don't see this anymore.

**Comment by dhowe** [comment]
me too
