### ISSUE TITLE
Question: how to handle duplicate ads on a page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#6]
This comes up most commonly on page-refresh.

Currently, we consider an ad to be new if it is unique or if it is a duplicate that was discovered more than 'repeatVisitInterval' ms ago, currently set to 1 minute.

**Comment by mushon** [comment]
@dhowe currently = in 1.x versions?

**Comment by dhowe** [comment]
I'm still not happy with this. For example, the test page has one ad. By refreshing the page every couple of minutes, you get the result below which is quite confusing in that it seems to be stating that 3 ads were found on that page.

<img width="961" alt="screen shot 2016-03-31 at 7 47 04 pm" src="https://cloud.githubusercontent.com/assets/737638/14174930/570d4ebc-f77a-11e5-85eb-de7132417486.png">

**Comment by mushon** [comment]
well, it’s a bug, right?
It should only show the ads detected since page load, right?

**Comment by yansh** [comment]
I cannot recreate in Chrome. I loaded http://rednoise.org/adntest/simple.html and tried to refresh multiple times with different time intervals. I only see one ad.

**Comment by dhowe** [comment]
this issue is now fixed
