### ISSUE TITLE
Improve Internationalization(i18n)

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#606]
I just did a check on AdNauseam Chinese version and found the following places where internationalization are missing
1.Vault
Export, Import and Clear button. 

2.Settings page
Extra Privacy and Interface need to be added to locale file
<img width="346" alt="2016-11-09 11 55 59" src="https://cloud.githubusercontent.com/assets/3056154/20127031/bd7faece-a675-11e6-95e8-c821f147fddc.png">

3.links.html
Need translation in locale file for "Support" and "Built on"
<img width="412" alt="2016-11-09 11 56 48" src="https://cloud.githubusercontent.com/assets/3056154/20127041/cdac0900-a675-11e6-852d-9a79fbd877a5.png">

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/607

**Comment by dhowe** [comment]
excellent
