### ISSUE TITLE
Check "CHN: CJX's Annoyance List‎" to visual ad blocking

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#608]
If it doesn't block visual ads, we can add it to the list of block-allowed 3rd-party lists

**Comment by cqx931** [comment]
When I check the rules, there are many hiding rules in the list.
<img width="645" alt="2016-11-10 1 07 24" src="https://cloud.githubusercontent.com/assets/3056154/20165266/ae477b54-a746-11e6-9f9f-702b0eca4240.png">

**Comment by dhowe** [comment]
hiding rules are fine -- we are concerned with blocking rules that affect collection of visual ads

**Comment by cqx931** [comment]
Isn't it already in enabledBlockLists?
![image](https://cloud.githubusercontent.com/assets/3056154/20873692/481b6018-bae5-11e6-8bb9-c3162aa1d140.png)

**Comment by dhowe** [comment]
yes, just want to check that it is not blocking visual ads...

**Comment by cqx931** [comment]
Verified on the major Chinese sites, some blocking domains listed in the list. No visual ads are blocked.
