### ISSUE TITLE
external visits fail on facebook

### ISSUE THREAD

**Issue by leoneckert** [dhowe/AdNauseam#613]
I noticed this issue when Ads collected on Facebook resulted to this title:

<img width="276" alt="screen shot 2016-11-11 at 17 01 32" src="https://cloud.githubusercontent.com/assets/14130931/20231530/93c07b24-a830-11e6-9ecf-47ed4604dbe2.png">

Pasting the target url of such an Ad first simply brought me to the Advertiser (routed through doubleclick) as one would expect. 

When pasting the targetUrl into a different Chrome profile, the "Leaving Facebook..." page comes up. It informs that the link pasted comes from a profile currently not logged in... while this is true in the case of the second Chrome Profile, it should be true when visiting facebook and ADN making the requets instantly. 

<img width="1032" alt="screen shot 2016-11-11 at 16 57 08" src="https://cloud.githubusercontent.com/assets/14130931/20231722/db625ece-a831-11e6-9add-5894534ef607.png">

I'll further investigate, in the meantime, this is how such an Ad looks:

```
{
  "https://www.facebook.com/": {
    "facebook.com::https://external-lga3-1.xx.fbcdn.net/safe_image.php?d=AQCTIUa7zuh72LOy&w=284&h=149&url=http%3A%2F%2Fwww.facebook.com%2Fads%2Fimage%2F%3Fd%3DAQJ3wvMfyxCsZGvDdA7F61hFLBwFyVh391HcLjVslfu39C0uXSJtJZG3zc-ngyTEqJBbIcz_Tgd03OQVFuGwfVYY555QLm9A8QOcFH_H73kYPYMkb_AClF7p5M33xhpdvcyImBEMYu9NVYC77mbtRxEU&cfs=1": {
      "id": 1,
      "attempts": 1,
      "visitedTs": 1478899992007,
      "attemptedTs": 0,
      "contentData": {
        "src": "https://external-lga3-1.xx.fbcdn.net/safe_image.php?d=AQCTIUa7zuh72LOy&w=284&h=149&url=http%3A%2F%2Fwww.facebook.com%2Fads%2Fimage%2F%3Fd%3DAQJ3wvMfyxCsZGvDdA7F61hFLBwFyVh391HcLjVslfu39C0uXSJtJZG3zc-ngyTEqJBbIcz_Tgd03OQVFuGwfVYY555QLm9A8QOcFH_H73kYPYMkb_AClF7p5M33xhpdvcyImBEMYu9NVYC77mbtRxEU&cfs=1",
        "width": 284,
        "height": 149
      },
      "contentType": "img",
      "title": "Leaving Facebook...",
      "resolvedTargetUrl": "https://www.facebook.com/l.php?u=AQFaaQMVK2jr4nRJALUTshNXj71KdiDIeZZzvQy60EJiTnR81XVG80kTfrLmLM5nekQb_nGXxosVhAXEaQd3kufl7Ht3M0UGCtmOfPyz7ylQGCai3nuRZ4DSYzejEpYXYzMbPvo69ZwGo7sDGTSDJ8DmI5xRLP4VJRmKicGJT4oYjNHYWtpisDFgf-Wc_9I-BanKimv4naEHbJawYqL3NGw3PC0byxHjdgw_Bd923Xfb7jGZGFrJoOlHqY1oiPssrfuNQmQU7j-vctReB_aS5K7qB9V92EgAE-YYGgXY-Op_VXsh_kLRnkD56tfYmy56zzesGskD2M8DnO4u6GnZkH_cYNHf7kxkicwIjm1UIPaVjfNMw1FvzDmSK9yU-LAyJ1zS-h8W8casgYmH&h=kAQFesL5n&enc=AZN9nLoz0pPQnPcgMi6PziiaPQqLL0e4x5wnf9O-XQ-cuPpNde5XzKqY0MG9Vst-AArC7ILi-_3wzvMhmtdAcyRC7g37gckpx5sZjtS51mJlVI7VQCRMzRZY0RFkzepgd_dk_RiygVJxy38r7sA2gW6WWlAZG0FG_TBll9Vp80AZyuUgGjow_Kv6mR2rMVKkx_X5MGoJxTyVmSbJiRtOIgHx&s=1",
      "foundTs": 1478899972515,
      "targetUrl": "https://www.facebook.com/l.php?u=AQFaaQMVK2jr4nRJALUTshNXj71KdiDIeZZzvQy60EJiTnR81XVG80kTfrLmLM5nekQb_nGXxosVhAXEaQd3kufl7Ht3M0UGCtmOfPyz7ylQGCai3nuRZ4DSYzejEpYXYzMbPvo69ZwGo7sDGTSDJ8DmI5xRLP4VJRmKicGJT4oYjNHYWtpisDFgf-Wc_9I-BanKimv4naEHbJawYqL3NGw3PC0byxHjdgw_Bd923Xfb7jGZGFrJoOlHqY1oiPssrfuNQmQU7j-vctReB_aS5K7qB9V92EgAE-YYGgXY-Op_VXsh_kLRnkD56tfYmy56zzesGskD2M8DnO4u6GnZkH_cYNHf7kxkicwIjm1UIPaVjfNMw1FvzDmSK9yU-LAyJ1zS-h8W8casgYmH&h=kAQFesL5n&enc=AZN9nLoz0pPQnPcgMi6PziiaPQqLL0e4x5wnf9O-XQ-cuPpNde5XzKqY0MG9Vst-AArC7ILi-_3wzvMhmtdAcyRC7g37gckpx5sZjtS51mJlVI7VQCRMzRZY0RFkzepgd_dk_RiygVJxy38r7sA2gW6WWlAZG0FG_TBll9Vp80AZyuUgGjow_Kv6mR2rMVKkx_X5MGoJxTyVmSbJiRtOIgHx&s=1",
      "pageTitle": "Facebook",
      "pageUrl": "https://www.facebook.com/",
      "errors": null,
      "current": true,
      "pageDomain": "facebook.com",
      "version": "2.3.84",
      "targetDomain": "facebook.com",
      "requestId": "7977"
    }
  }
}
```

**Comment by leoneckert** [comment]
only just realised there is a preview option on the network tab in Dev tools. Below are the background.html requests and potentially helps to find a solution to this issue. 

<img width="376" alt="screen shot 2016-11-11 at 17 25 59" src="https://cloud.githubusercontent.com/assets/14130931/20232092/01b7f1fe-a834-11e6-9017-7ee7ba68795e.png">
 

<img width="1771" alt="screen shot 2016-11-11 at 17 23 25" src="https://cloud.githubusercontent.com/assets/14130931/20232046/b4d9c8f8-a833-11e6-9d0f-6169fd2d43c6.png">
<img width="1771" alt="screen shot 2016-11-11 at 17 23 29" src="https://cloud.githubusercontent.com/assets/14130931/20232048/b4e86246-a833-11e6-9234-b1bab7783f4c.png">
<img width="1771" alt="screen shot 2016-11-11 at 17 24 02" src="https://cloud.githubusercontent.com/assets/14130931/20232047/b4e669b4-a833-11e6-9da6-4a73c051f3b3.png">

**Comment by dhowe** [comment]
Can you inspect the request that is sent after you click 'Follow Link'? Perhaps we can spoof this request instead...

**Comment by dhowe** [comment]
pushed to 3.0

**Comment by leoneckert** [comment]
I looked into this again and if I understand correctly the request when clicking the button is simply the original request of the ad that is already baked into the url of the fb request. 

maybe facebook links of this structure could just be resolved to the actual ad link?


![fb_forward](https://cloud.githubusercontent.com/assets/14130931/20737489/07d8a704-b67b-11e6-995f-8f803a735e65.jpg)

**Comment by dhowe** [comment]
Are there any other cases where we do this? I think so (let me check)...

**Comment by dhowe** [comment]
This is a bit more difficult than you guys indicate, as the URL is obfuscated (and only visible AFTER the visit), but please verify 86ff8bf (as a non-facebook-user, I can't test)

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/664
verified with a small tweak
