### ISSUE TITLE
Lists no longer clickable/viewable in 3rd-party filters page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#614]
clicking on checkbox should toggle it, clicking on filter-name should open it in the asset-viewer,
(not sure if we need the arrow-icon) -- many of our user have used uBlock; bad idea to change basic functions people may be accustomed to...

**Comment by leoneckert** [comment]
above PR:
- got rid of the arrow-icons
- list names link to the lists
- checkbox does what it has always done
- looks like:
<img width="603" alt="screen shot 2016-11-12 at 13 03 45" src="https://cloud.githubusercontent.com/assets/14130931/20239851/80544fa4-a8d8-11e6-8376-06e576dab4d9.png">
