### ISSUE TITLE
Update settings to correspond with uBlock's new advanced settings page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#615]
See https://github.com/gorhill/uBlock/releases/tag/1.9.17b7:

> Advanced settings
> 
> A new "Advanced settings" pane, available only to advanced users. It contains settings which are experimental, or which are of interest to advanced users who want more control over how uBO behaves internally. I do not want to bloat the Settings pane in the dashboard with settings which are of interest only to a minority of users or which are experimental: this is where the new "Advanced settings" pane is useful.
> 
> When you enabled "Advanced users" in the Settings pane, a cogs icon will appear next to that setting. Click this cogs icon to access those "hidden" advanced settings:
> 
> the _cogs_ icon
> 
> The UI of the advanced settings page is purposefully stern. Keep in mind that whatever settings you see in there may be experimental and could be removed at any time in the future.
> 
> Experimental advanced setting of interest: suspendTabsUntilReady (default to false), to prevent uBO from establishing any remote connection at launch before all filter lists/settings have been fully loaded (related issue #1327). How well it works will have to be evaluated by users.

**Comment by mushon** [comment]
tag/1.9.17b7 no longer exists. I d/l 1.10.5b0 but couldn't find any "Advanced settings"

**Comment by dhowe** [comment]
closing for now
