### ISSUE TITLE
Script to convert EFF's DNT list to block 1st parties as well

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#616]
can use this while in meantime, before they update...

target rules for each domain listed in list, using duckduckgo.com as example:

1) @@*$domain=duckduckgo.com  

  (allow network requests of any type, whose destination URL is anything, and whose source is duckduckgo.com)

2) @@||duckduckgo.com^third-party

   (allow third-party network requests, with destination duckduckgo.com, from any source)

**Comment by dhowe** [comment]
if _all_ other tickets are completed, either of you might tackle this one (script should be written in either jq, or bash/jq)

**Comment by leoneckert** [comment]
you mean ALL other tickets or just the 2.4 tickets? 
- if it should be done at the very last, isn't the priority then very low...?

**Comment by dhowe** [comment]
It is high priority for version 3.0, but only if you run out of things to work on...

**Comment by leoneckert** [comment]
okay, sorry I could't resist doing this right now because I am trying to get better in bash and regex. I hope that's not all useless that *early*.

This does the job:
```
#!/usr/bin/env bash

regex='@@\|\|([0-9a-zA-Z\.\-_]+)\^.+'

while IFS='' read -r line || [[ -n "$line" ]]; do
    if  [[ $line == @@* ]];
    then
        string=$line
        if [[ $string =~ $regex ]]
        then
          domain="${BASH_REMATCH[1]}"
          echo $domain
          echo '@@*$domain='$domain  >> ./output.txt
          echo '@@||'$domain'^third-party'  >> ./output.txt
        fi
    fi
done < "effdntlist.txt"
```

just noting that back when we experimented (in our telegram) we tested:
```
@@*duckduckgo.com*$third-party
@@*$domain=duckduckgo.com
``` 
which are slightly different from yours above

**Comment by dhowe** [comment]
ok, thats fine -- but next pls figure out what the differences are between the two pairs of rules (I think the ones I included above were generated from uBlock's interface)?  

then pls check #252

**Comment by leoneckert** [comment]
@dhowe I am not sure if I understand, you noted the differences in your brackets above no? 

in Sally's and my tests  `@@*$domain=duckduckgo.com` did:
>(allow network requests of any type, whose destination URL is anything, and whose source is duckduckgo.com)

and `@@*duckduckgo.com*$third-party` did:
>(allow third-party network requests, with destination duckduckgo.com, from any source)

@cqx931 ,correct me if I am wrong please.

**Comment by cqx931** [comment]
from my test, these two shall do the same thing, but with a slight difference in syntax. `@@||duckduckgo.com^$third-party`
`@@*duckduckgo.com*$third-party`

`@@||duckduckgo.com^$third-party` This one was used by EFF before, so we might want to just keep it the same. (This is also used in [adblock's filter introduction](https://adblockplus.org/filters). )

**Comment by dhowe** [comment]
sounds good -- lets adjust the script (if needed) to match

**Comment by leoneckert** [comment]
@dhowe you mean the bash script?

this...
```
#!/usr/bin/env bash

input_text=$1

printf "# 1)\n# allow third-party network requests,\n# with specified destination,\n# from any source\n\n" > ./output.txt
while IFS='' read -r line || [[ -n "$line" ]]; do
    if  [[ $line == @@* ]];
    then
        echo $line >> ./output.txt
    fi
done < $input_text

regex='@@\|\|([0-9a-zA-Z\.\-_]+)\^.+'
printf "\n# 2)\n# allow network requests of any type,\n# whose destination URL is anything,\n# and whose source is specified\n\n" >> ./output.txt
while IFS='' read -r line || [[ -n "$line" ]]; do
    if  [[ $line == @@* ]];
    then
        string=$line
        if [[ $string =~ $regex ]]
        then
          domain="${BASH_REMATCH[1]}"
          echo '@@*$domain='$domain  >> ./output.txt
        fi
    fi
done < $input_text
```
...now outputs:
```
# 1)
# allow third-party network requests,
# with specified destination,
# from any source

@@||99designs.community^$third-party
@@||act.eff.org^$third-party
@@||avatars.discourse.org^$third-party
@@||circleforum.squarespace.com^$third-party
@@||codepoints.net^$third-party
@@||do-not-tracker.org^$third-party
@@||do-not-track.org^$third-party
@@||duckduckgo.com^$third-party
@@||duckduckhack.com^$third-party
@@||eff.org^$third-party
@@||elyotherm.fr^$third-party
@@||firstpartysimulator.net^$third-party
@@||firstpartysimulator.org^$third-party
@@||geeek.org^$third-party
@@||helloforos.com^$third-party
@@||itsgoingdown.org^$third-party
@@||login.persona.org^$third-party
@@||medium.com^$third-party
@@||meta.discourse.org^$third-party
@@||movieflix.to^$third-party
@@||persona.org^$third-party
@@||redforts.com^$third-party
@@||safenetforum.org^$third-party
@@||thefitrv.com^$third-party
@@||try.discourse.org^$third-party
@@||twittercommunity.com^$third-party
@@||wpstagecoach.com^$third-party

# 2)
# allow network requests of any type,
# whose destination URL is anything,
# and whose source is specified

@@*$domain=99designs.community
@@*$domain=act.eff.org
@@*$domain=avatars.discourse.org
@@*$domain=circleforum.squarespace.com
@@*$domain=codepoints.net
@@*$domain=duckduckgo.com
@@*$domain=duckduckhack.com
@@*$domain=eff.org
@@*$domain=elyotherm.fr
@@*$domain=firstpartysimulator.net
@@*$domain=firstpartysimulator.org
@@*$domain=geeek.org
@@*$domain=helloforos.com
@@*$domain=itsgoingdown.org
@@*$domain=login.persona.org
@@*$domain=medium.com
@@*$domain=meta.discourse.org
@@*$domain=movieflix.to
@@*$domain=persona.org
@@*$domain=redforts.com
@@*$domain=safenetforum.org
@@*$domain=thefitrv.com
@@*$domain=try.discourse.org
@@*$domain=twittercommunity.com
@@*$domain=wpstagecoach.com
```

new to bash scripting , any advice appreciated

**Comment by dhowe** [comment]
Looks good, now lets test it...

**Comment by leoneckert** [comment]
is the best practise to test this to construct ads and host them on my own server? If so, is there any template you have? Or is all I do to just create an image tag linking to, for example, a duckduckgo hosted png etc?

**Comment by dhowe** [comment]
here's a simple example: https://rednoise.org/adntest/simple.html

**Comment by leoneckert** [comment]
testing right now. A question, @dhowe and @cqx931 didn't we figure out in Telegram, that we don't have a method to overwrite/whitelist cosmetic filters as they are usually very specific? 

The rules above work well for prevent ads from being BLOCKED.

Daniel suggested in Telegram to put the same mechanism as "pausing adn" in place when the DNT page is the first party, preventing all Blocking and Cosmetic filtering. 

**In my current understanding the best we can do right now is that:**
- pausing adn on DNT listed pages to prevent both blocking and cosmetic filtering
- use a rule of this form `@@*$domain=duckduckgo.com` to make sure DNT listed requests are not BLOCKED when they are 3rd party. However they MIGHT STILL BE HIDDEN. 

does this make sense? or am I missing something?

**Comment by dhowe** [comment]
Can you find the relevant messages from our chat and past them here? The other option is to (politely) post the question on ublock re: overriding cosmetic filters.

Am I correct that the problem is as follows: We need to disable all cosmetic filters for requests from a specific domain when it is a third-party, regardless of whether the rule is specific to that domain?

**Comment by leoneckert** [comment]
Yes the way you say it it's right. The way I understand it is that the cosmetic exception rule _"DONT HIDE ADS TO [DNT SITE]"_ (3rd party) does not have priority over _"HIDE THE DIV WITH ID 'AD'"_, which is more specific as Sally points out in the text I pasted below. 

To me it seems that a mix of dynamic filters (when 3rd party) and plane whitelisting of the whole page (same mechanism as _PAUSE_) (when 1st party) could do the job? 



**relevant messages from out chat below:**

----
**Leon Eckert, [27 Oct 2016 00:05]:** 
this is whitelisting all Blocking in the two cases, but does not actually overwrite cosmetic filters. Is it an option for us to also use uBlock style dynamic filters for DNT listed sites, because that works really well against cosmetic filters

the three rules would than be
``` 
@@*duckduckgo.com*$third-party
@@*$domain=duckduckgo.com
no-cosmetic-filtering: duckduckgo.com true
```

**daniel, [27 Oct 2016 00:06]:** 
we would have to parse the DNT list, which I would like to avoid

**Sally Chen, [27 Oct 2016 01:52]:** 
After a quick briefing from Leon, I have tested the rules on duckduckgo. Both the third-party and first-party one are working well with me.

For the third-party testing I have made a simple webpage requesting a js file from ddg that easylist is blocking.

**daniel, [27 Oct 2016 01:57]:** 
Ok, as I said, it might make sense to add another site with ads to the DNT list, for easier testing
perhaps rednoise.org even

**Sally Chen, [27 Oct 2016 01:59]:** 
As for the cosmetic filter... It is very hard to make exception for the whole site. An exception rule like this won't do anything `duckduckgo.com#@#*` since cosmetic filtering rules are all more specific than this...we either do this through dynamic rules, or we need to write exception filters for all cosmetic selectors that currently would be blocked....

If I understood this correctly..."showing ads from EFF DNT list" is a feature specific to AdNauseam, rather than something written in the EFF list, isn't it?

If that is the case, can we just handle this seperately in our defaultDynamicFilters?

**daniel, [27 Oct 2016 02:39]:** 
isn't it the same case as when a site is whitelisted, and thus we don't hide anything on it?

when a site is whitelisted (via the pause-adnuaseam button), then none of the cosmetic filters are sent to the content-script

we should use this same mechanism for DNT whitelisted sites

**Comment by dhowe** [comment]
So sounds like we need, at least for now, to parse the DNT-list and a) whitelist the page when the domain is on the DNT, and b) use dynamic rules when the site is 3rd party (allow anything from domain)
Make sense?

**Comment by leoneckert** [comment]
Agreed!

**Comment by leoneckert** [comment]
I am now first looking at a). That is making myself familiar where and how exactly whitelisting takes place right now and then how to make sure DNT pages are treated the same.

**Comment by dhowe** [comment]
The whitelist data is stored in µBlock.netWhitelist and is changed in the function µBlock.toggleNetFilteringSwitch. For one example, this happens when you click 'pause-adnauseam' i the menu...

**Comment by leoneckert** [comment]
that's what I am looking at right now. So does it make sense to parse the DNT list and calling this function on the included URLs? That would also include them (visually) into the Whitelist in the dashboard I assume.

**Comment by dhowe** [comment]
sounds right

**Comment by leoneckert** [comment]
and that all happening in core.js? or is there a script that is better suited?

**Comment by dhowe** [comment]
yes, in core for now

**Comment by leoneckert** [comment]
I am struggling right now with understanding the best practise for getting the list data from `assets/thirdparties/www.eff.org/files/effdntlist.txt` into the script in the first place. 

I assume this works somehow with the vAPI messaging, similar to how it is done in 3p-filters.js, but the same function `messaging.send('dashboard', { what: 'getLists' }, onListsReceived);` does not work. - can you give me a hint what I am missing here?

**Comment by dhowe** [comment]
not sure, I'd have to trace it

**Comment by leoneckert** [comment]
okay i thought you might have run into this before. determined to figure it out!

**Comment by leoneckert** [comment]
- [x] whitelist dnt domains a 1st parties

this part seems to work in this branch with two functions added in core.js https://github.com/leoneckert/AdNauseam/tree/whitelistDNTdomains. Could you verify, @dhowe  ?

Right now the function **runs once in core.js** when the extension is first installed. Of course, in the end, it **would need to be triggered whenever the DNT list changes**.
When running it at different points in core.js, I noticed that if it is called too early, the whitelist ends up empty. That is not the case anymore now (for a number of times I tested), but should be noted. 

I had to add a hard coded 'http://' to the domain names in the list for putting them on the whitelist:
`µb.toggleNetFilteringSwitch("http://" + DNTurls[i], "site", false);` , however made sure also 'https://' sites end up _pausing_ AdNauseam. 

<img width="270" alt="screen shot 2016-12-22 at 19 23 06" src="https://cloud.githubusercontent.com/assets/14130931/21436148/5fc1b7bc-c87d-11e6-8757-29978b8a3778.png">
<img width="670" alt="screen shot 2016-12-22 at 19 23 12" src="https://cloud.githubusercontent.com/assets/14130931/21436151/637b4f62-c87d-11e6-9a24-b17e4634db0a.png">

**Comment by dhowe** [comment]
This is a good start. If you like, you can submit a PR (please comment-out line 78 first), or continue working on part b) and do a PR when finished. In addition to b) we will need to determine the best place to load/parse the DNT list in install or update, and also, as you mention, how to rerun this code when the DNT list is updated...

**Comment by leoneckert** [comment]
from our Telegram chat I thought I remembered the dynamic filters to work for whitelisting/un-hiding selected ads when they are third parties (what we were planing to use them for in this thread), however it seems not that easy. 

I think they are actually just an alternative to what is now achieved with the whitelisting (not hiding ads that appear on DNT pages), but still NO SOLUTION to DNT requests as third-party.

I will post a question on uBlock. On the other hand I think it will be extremely rare that DNT pages advertise elsewhere, as 3rd-parties.

**Comment by dhowe** [comment]
That is not my understanding -- what makes you think this?

**Comment by leoneckert** [comment]
You mean the last point? You are right, maybe I thought a little too quick and only considering the sites currently on the list. But especially when assuming the list grows over time, of course they would also advertise elsewhere, too - and should, assuming they don't track, be whitelisted. 

\-- We just still need to find a way to do that. I posted on uBlock.

**Comment by dhowe** [comment]
No, I mean, why do you think dynamic 3rd-party rules don't work?

**Comment by leoneckert** [comment]
I tried to find out how to formulate the rule with no success and checked back with Sally. The format we discussed in Telegram `no-cosmetic-filtering: duckduckgo.com true` disables all cosmetic filtering on duckduckgo.com (it as a 1st party). 
From looking at the dynamic filter docs I think it should be something likes this: `* duckduckgo.com 3p allow` right? but it does not let me add this to test...

**Comment by cqx931** [comment]
Please notice that the test I did is for a js request from duckduckgo. The dynamic 3rd-party rules work for blocking requests but not for hiding cosmetic hiding rules. If the image request is requesting directly to the sites in EFF rules, we can allow the request. But let's say, if there is a cosmetic filter that hide the element, I am not sure the 3rd-party rules will be helpful then?
Please correct me if I am wrong...

And here is the test page that I used for testing the EFF rules. Just some random images and js/css files loading.Hopefully it is helpful.
http://chenqianxun.com/testcases/effTestPage.html

**Comment by dhowe** [comment]
We need to clarify what we are trying to do here. For DNT domains, we want to:
a) disable BLOCKING on that domain (handled by whitelisting)
b) disable HIDING on that domain (handled by whitelisting)
c) disable BLOCKING for requests TO that domain (handled by 3rd-party dynamic filter)

Are there are other cases we need to consider, or is that the full-set?

What does it even mean to disable 3rd-party cosmetic filtering, when cosmetic filters don't have a "home" domain? The only thing I can think of is to not hide, for example, iframes when the source domain is on the DNT list... (but if this were even possible, it would be version 2.0 of the basic functionality above)

**Comment by leoneckert** [comment]
My bad then, I thought it was about un-hiding for the 3. point too! 

The not-blocking works with a dynamic rule like this (used on @cqx931 example page):

<img width="603" alt="screen shot 2016-12-23 at 22 31 13" src="https://cloud.githubusercontent.com/assets/14130931/21462723/a36926f2-c95f-11e6-8865-1f21091be25b.png">

I use the same function I have in place to add those rules to the defaultDynamicFilters array that you've put in place already!

**Comment by leoneckert** [comment]
now that they are added, these questions remain to be solved:

1) when to call this function for the first time
2) how to call it regularly, when the DNT list updates
3) for 2) the functions still needs a mechanism to 'delete' old rules and whitelist entries when specific domains are not part of an updated DNT list anymore - probably the easiest would be to first clean all out (deleting all whitelist entries for domains from outdated DNT list, deleting all dynamicFilterRules for the same ones), then generate all new rules with domains from latest DNT list.

**Comment by leoneckert** [comment]
the thoughts I wrote down in previous comment are included in the PR above. 

The functions in there now make sure that 
- both dynamic filters and whitelist of outdated DNT list are first cleared out, 
- then updated with the domains in the updated DNT list. 

right now this is (commented out) called as an interval in the `initialize()` function (not sure what would speak against that actually), not yet having resolved where it would be better to call it. The functions assume that the local list in the assets/.... folder is updated regularly - another option would be to read them straight from the EFF webpage.
