### ISSUE TITLE
[Firefox/Opera] Disable pause/resume button in menu when the user is on browser's page

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#619]
<img width="572" alt="screen shot 2016-11-13 at 3 48 39 pm" src="https://cloud.githubusercontent.com/assets/3056154/20244348/fdda5686-a9b8-11e6-9aae-18d05be1f91a.png">

The above code doesn't work in the following situations: 
 - Opera: **sometimes** after close and reopen the browser 
 - Firefox: about pages, vault & settings pages (these case is covered in the code, but  #somehow it is not working as expected)
<img width="1221" alt="screen shot 2016-11-13 at 3 55 47 pm" src="https://cloud.githubusercontent.com/assets/3056154/20244379/17b75724-a9ba-11e6-9a25-e10c3f8f4b3a.png">

**Comment by cqx931** [comment]
In Firefox, when click the menu from adnauseam page or firefox page, it can't get the right pageStore object from the tabId, therefore the default pageStore object with tabId -1 is returned, with an empty url.
<img width="884" alt="screen shot 2016-11-13 at 5 40 14 pm" src="https://cloud.githubusercontent.com/assets/3056154/20244741/67a4542c-a9c8-11e6-9411-1fa40ffd7a90.png">

**Comment by mneunomne** [comment]
This issue is not valid anymore to the current UI, closing.
