### ISSUE TITLE
Adblock blockers

### ISSUE THREAD

**Issue by q-l-p** [dhowe/AdNauseam#624]
How can we circumvent  adblock blockers?
For example: [ http://blockadblock.com/](url)

**Comment by dhowe** [comment]
Please include one or more example sites for us to test

**Comment by q-l-p** [comment]
Initially I found out about this adblocker blocking thing when I visited [http://www.criminalcasetools.com/en/](url)

**Comment by dhowe** [comment]
Thanks for the report. I've noticed that this problem also appears on uBlock, which means that it is not AdNauseam specific, and relates instead to the [uAssets repository](https://github.com/uBlockOrigin/uAssets), where problems with specific lists (ised by uBlock, AdNauseam, etc.) are discussed and addressed. Please create a ticket [here](https://github.com/uBlockOrigin/uAssets/issues) instead.

**Comment by IDKwhattoputhere** [comment]
[uBlock Origin](https://github.com/gorhill/uBlock#beware-ublock-origin-is-completely-unrelated-to-the-web-site-ublockorg) or [uBlock](https://github.com/chrisaljoudi/uBlock)? [One hasn't been updated in over a year.](https://en.wikipedia.org/wiki/UBlock_Origin#Release_history) Please clear this up. Furthermore please take a look [here](https://github.com/uBlockOrigin/uAssets/issues/200#issuecomment-261576057).

**Comment by dhowe** [comment]
see https://github.com/uBlockOrigin/uAssets/issues/200
