### ISSUE TITLE
broken link on firstrun page

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#625]
These tiny links on firstrun page seemed to be ignored in the previous tests. (I have just added this as a new point to the wiki page)

Under Block Malware, "customize" is linking to this page `chrome-extension://agfkgplkjhggkedblkcgkdaocppaeimj/dashboard.html#security`,but we don't have #security in dashboard. Should this be "#options.html"?

Currently the 3 links on first-run page will be opened in the same tab. I think it is better to open a new tab for them as the user might just want to check what these links are, but still being able to go back to the first-run page.
![image](https://cloud.githubusercontent.com/assets/3056154/20431650/1d852b52-add6-11e6-974d-b66bcd92881b.png)
![image](https://cloud.githubusercontent.com/assets/3056154/20431769/c92591cc-add6-11e6-8e0a-24f7e224e3ba.png)

**Comment by dhowe** [comment]
yes, good point -- should be a new tab...
