### ISSUE TITLE
[Firefox] links on first-run page don't work

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#626]
<img width="477" alt="screen shot 2016-11-18 at 9 44 31 pm" src="https://cloud.githubusercontent.com/assets/3056154/20432029/3c1d32b0-add8-11e6-9435-a5aec18cbbed.png">

**Comment by dhowe** [comment]
Does this perhaps relate to #531 (or more specifically, the fact that I have not completed #531)?

**Comment by cqx931** [comment]
I didn't check this in detail yet, but I think this looks something related to vapi of firefox. Currently when I click on these links in firefox, there is just no response.

Sally

**Comment by cqx931** [comment]
This is very interesting...the links are currently written in locale file and in firefox, it get rendered to `about:blank`...I am going to check the vAPI for i18n in firefox.
<img width="628" alt="screen shot 2016-11-19 at 12 49 02 am" src="https://cloud.githubusercontent.com/assets/3056154/20438381/65921cea-adf2-11e6-968c-01dcfcbf516a.png">

**Comment by cqx931** [comment]
Because I didn't really figure out a nice way to bypass that vAPI issue in firefox, I tried another approach to solve this by using <span> tag in locale file rather than <a> tag. 

This should solve this and #625.
