### ISSUE TITLE
MENU: Ads zoom out strangely

### ISSUE THREAD

**Issue by leoneckert** [dhowe/AdNauseam#628]
This should be a quick fix:
when hovering the ad (all as it should be here):
<img width="381" alt="screen shot 2016-11-17 at 14 23 35" src="https://cloud.githubusercontent.com/assets/14130931/20448578/b7cc1aaa-adb2-11e6-8603-993bb3cb13e7.png">
when moving the mouse elsewhere, the image sizes down again, but behind the oder objects:
<img width="374" alt="screen shot 2016-11-17 at 14 23 40" src="https://cloud.githubusercontent.com/assets/14130931/20448589/c754e222-adb2-11e6-94bc-c7a91a22c3ba.png">

**Comment by dhowe** [comment]
Good. Please fix...

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/pull/636
