### ISSUE TITLE
VAULT: resizing window conflicts with inspection mode

### ISSUE THREAD

**Issue by leoneckert** [dhowe/AdNauseam#629]
Recreate:
- collect ads
- open the vault and click on any Ad to get into inspection mode
<img width="753" alt="screen shot 2016-11-18 at 17 19 21" src="https://cloud.githubusercontent.com/assets/14130931/20448675/2cc4d2b6-adb3-11e6-92c5-39b0c17e5f1e.png">
- resize the browser window -> the inspected Ad disappears with the background remaining black:
<img width="999" alt="screen shot 2016-11-18 at 17 19 25" src="https://cloud.githubusercontent.com/assets/14130931/20448706/53f97a1c-adb3-11e6-87a3-c8d0d92fde3e.png">

**Comment by dhowe** [comment]
good find -- please fix...
