### ISSUE TITLE
VAULT: hard to notice the option of dragging the date slider smaller

### ISSUE THREAD

**Issue by leoneckert** [dhowe/AdNauseam#630]
I found it not very intuitive to drag the date slider smaller and actually use it to selectively see ads over time. This if course is just my personal experience and I am putting it out there... - wouldn't have realised this feature if I wasn't working on AdN

![slider](https://cloud.githubusercontent.com/assets/14130931/20448934/804cd9e6-adb4-11e6-80fb-c1c461c1daf2.jpg)

**Comment by dhowe** [comment]
Good. Lets revisit this for 3.0

**Comment by mushon** [comment]
@dhowe please check d7073a9
Please note though that I'd rather the brush extent appear under the bars (and the handles above)
and I would also prefer having a class on brushed bars so their colors can be differentiated.

**Comment by mushon** [comment]
this is how it's looking now:
![image](https://cloud.githubusercontent.com/assets/27123/21470921/a111980c-caa5-11e6-8c68-0ad09dd2facb.png)

**Comment by mushon** [comment]
closing (more D3 related issues in #232)
