### ISSUE TITLE
Need German translation of text (for Opera store)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#638]
AdNauseam is a browser extension designed to obfuscate browsing data and protect users from tracking by advertising networks. Like an ad-blocker, AdNauseam blocks malware and hides ads on the pages you visit. But AdNauseam does more, collecting each ad in its AdVault for you to interactively explore. AdNauseam can also be configured to automatically click each blocked ad in the background, polluting your data profile and frustrating the trackers who violate your privacy and facilitate bulk-surveillance agendas.

**Comment by leoneckert** [comment]
AdNauseam is eine Browser-Erweiterung, die dazu entworfen ist, Internet-Surf-Daten zu obfuskieren und damit den Nutzer vor der Überwachung von Werbenetzwerken zu schützen. Wie andere AdBlocker, blockt auch AdNauseam schädliche Skripts und und macht Werbung auf Webseiten unsichtbar. Das ist jedoch nicht alles - AdNauseam sammelt Werbungen in seinem 'AdVault', wo sie interaktiv vom Nutzer inspiziert werden können. Des weiteren kann AdNauseam optional dazu genutzt werden, automatisch jede Werbung unbemerkt um Hintergrund zu klicken und damit dein Daten Profil zu verwirren und entgegen Tracker zu wirken, die deine Privatsphäre verletzen und Überwachungs Agendas nähren.

**Comment by dhowe** [comment]
We need to find a place to store these (for various languages)

**Comment by leoneckert** [comment]
@dhowe would that just be a normal file in a separate folder? I guess they are never accessed programmatically but rather copy pasted when submitted to the store(s)?

**Comment by dhowe** [comment]
For now I've added description.txt files in the language-specific locale folder. @cqx931 can you do a quick check on the two Chinese versions (that they match the text above)?

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pulls  Checked in the improved Chinese description.txt files.
