### ISSUE TITLE
Ads visible on www.jobsnhire.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#652]
Multiple ads -- http://www.jobsnhire.com/articles/50554/20161203/netflix-made-creative-way-promote-black-mirror-avoid-ad-blockers.htm

![screen shot 2016-12-04 at 7 15 42 pm](https://cloud.githubusercontent.com/assets/737638/20865765/40638b00-ba56-11e6-947b-99672b71e889.png)

![screen shot 2016-12-04 at 7 16 07 pm](https://cloud.githubusercontent.com/assets/737638/20865766/42e92fce-ba56-11e6-9b68-eb03b82c22d8.png)

**Comment by cqx931** [comment]
verified.
