### ISSUE TITLE
Interface option (with link to FAQ entry) for "visit some, but not all ads"

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#660]

**Comment by mushon** [comment]
@dhowe you marked this as "needs-design", but we already have design for settings checkboxes with references to FAQ. Shouldn't we simply use the approach we already have? (or am I missing something?)
![image](https://cloud.githubusercontent.com/assets/27123/21305061/0789ca92-c5d2-11e6-84e9-d2418f679b3b.png)

**Comment by dhowe** [comment]
Position on the settings page?, default setting?, how long to wait before declaring the user "idle"?

**Comment by mushon** [comment]
Again I think we should decide that based on testing and impact. I am assuming this feature is both used for hiding the signals and for better performance. Do we have a way to evaluate the effectiveness of this feature so to better inform users who might want to use it?
+
I think we will need a blog post or something for "optimizing your ADN experience"

**Comment by dhowe** [comment]
No, this is only for better network performance.
