### ISSUE TITLE
Add new DevFAQ entries

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#665]
These all have questions already, please fill in the answers:

- [x] What does it mean for AdNauseam to appear as 'paused' in the menu?
- [x] What does it mean when 'DoNotTrack' is enabled?
- [x] What is the data format for Ad imports/exports? (blocked on #668)

**Comment by cqx931** [comment]
I will add this after you implement this ticket: https://github.com/dhowe/AdNauseam/issues/668

**Comment by dhowe** [comment]
I saw your entry on DNT, which was good, but more targeted at users, so I added it as a question in the FAQ itself. For the DEV-FAQ, I've done most of the entry, however we need to list every change internally that happens when DNT is enabled. Please finish the answer here (https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#what-does-it-mean-when-do-not-track-dnt-is-enabled) and then can do item 3 above as well

**Comment by cqx931** [comment]
I have modified the DNT entry above, please double check.
According to my understanding, the two settings should be both set to true in the entry (hidingAds=true, disableHidingForDNT=true)

**Comment by cqx931** [comment]
Item 3:
What exactly need to be written for the ad format? (More on the json format and hash? do I also need to explain what each entry is about?)

What does these two entries mean: visitedTs and attempedTs ?

**Comment by cqx931** [comment]
@dhowe

**Comment by dhowe** [comment]
I think just a sentence or two about the format of the file itself: page-hash -> ad-hash -> ad
and then a very brief comment on any _non-obvious_ field in the Ad object... 
For example, 

`
visitedTs: the timestamp for an ad-visit in milliseconds; is either 0 (the initial-value), a positive-timestamp on a successful visit, or a timestamp * -1 on failure`

**Comment by dhowe** [comment]
no longer blocked

**Comment by cqx931** [comment]
done
