### ISSUE TITLE
Allow single ads to be imported

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#667]

**Comment by dhowe** [comment]
Please verify:

1. Open the vault and select any ad to inspect
2. Press the 'd' key to output its JSON to the console
3. Copy and paste JSON to new file with .json extension
4. Clear-ads (export first if you want to save)
5. Import the new file (with one ad)
6. Check that one Ad is successfully import

ed

**Comment by dhowe** [comment]
@cqx931 please verify and close

**Comment by cqx931** [comment]
verified.
