### ISSUE TITLE
Indicate in menu if a page is paused because it is a DNT site

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#674]

**Comment by mushon** [comment]
How about this:
![popup-notifications-dnt](https://cloud.githubusercontent.com/assets/27123/21517954/a75c310c-cceb-11e6-8ffa-cfb010a263e2.png)

**Comment by dhowe** [comment]
1. Ads will still show up in the menu, they will not be hidden, and they will not be clicked
1. We need to consider 3 cases: no hiding/no clicking, hiding/no clicking, no hiding/clicking
1. We need to link somehow to what 'respects "DO NOT TRACK"' means

**Comment by mushon** [comment]
How about this?
![popup-notifications-dnt](https://cloud.githubusercontent.com/assets/27123/21518931/4a162208-ccf2-11e6-9b01-556266b98771.png)

**Comment by mushon** [comment]
and on hover jump to "settings":
![popup-notifications-dnt](https://cloud.githubusercontent.com/assets/27123/21519054/132e18f8-ccf3-11e6-9099-ed6a8246633c.png)

**Comment by dhowe** [comment]
what is the fourth notification, when neither is enabled?
and does the settings hover come up for all, or just the last?

**Comment by mushon** [comment]
1. yes
2. for all

**Comment by dhowe** [comment]
The 3rd option seems not to make much sense? Shall we post that as a warning?

**Comment by dhowe** [comment]
@cqx931, lets implement these as standard notifications

**Comment by mushon** [comment]
[ ] make a green icon for DNT sites

**Comment by mushon** [comment]
icons added in: https://github.com/dhowe/AdNauseam/commit/98272ff605ed7ab2eb6896afc4fc33010de842b6

css added in: https://github.com/dhowe/AdNauseam/commit/b2f7c393f16b12b9377446a34328605d91730d98

use ``.notification.success.dnt.long``
``.dnt`` ads the DNT icon to success settings
``.long`` makes sure the button only appears on hover

**Comment by dhowe** [comment]
> The 3rd option seems not to make much sense? Shall we post that as a warning?
@mushon

**Comment by mushon** [comment]
Actually, this is something Helen is into - clicking w/o hiding. Not sure it doesn't make sense.

**Comment by mushon** [comment]
but yes, it makes no sense to click on a DNT ad. So maybe a warning or simply disallowing this state is due.

**Comment by dhowe** [comment]
my vote is for the warning...

**Comment by mushon** [comment]
ok

**Comment by cqx931** [comment]
I agree that it doesn't make much sense to do so, but isn't warning a bit too much for this scenario?

**Comment by dhowe** [comment]
I was thinking the same notification, just yellow instead of green

**Comment by cqx931** [comment]
ah, I see, yellow sounds reasonable

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/687
Interface implemented
Todo: 

- [ ] crowdin language update
- [ ] update wiki page for testing before release

**Comment by dhowe** [comment]
Nice work. I see a problem in the design (I think) with the ? and the 'settings' button, namely that the first is impossible to click because it is covered by the button when it slides in. 

Also, the 'settings' button doesn't open the settings page

**Comment by cqx931** [comment]
In the design the "?" is after "DO NOT TRACK",  I think I need to twist renderingNotification a little bit to change the position of '?'.

I will check the issue with 'settings' button

**Comment by dhowe** [comment]
let me do some minor refactors first

**Comment by cqx931** [comment]
I see... nice point, I will work on this after your refactors.

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/pull/688

**Comment by dhowe** [comment]
@cqx931 is this verified?

**Comment by cqx931** [comment]
it used to work... but the whole notification system is not showing up after the Version bump.

**Comment by cqx931** [comment]
verified https://github.com/dhowe/AdNauseam/commit/d276c5297ad389cb45d09f4fe32c4b04c0e947c2
DNT menu notifications done
