### ISSUE TITLE
Bad user experience when you try to click the disabled DNT whitelist on whitelist.html

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#676]
Clicking what looks like a user-configurable checkbox has no effect: 

<img width="808" alt="screen shot 2016-12-26 at 7 16 37 pm" src="https://cloud.githubusercontent.com/assets/737638/21481208/f4d7cd26-cb9f-11e6-8adc-f5584a2d6330.png">

**Comment by mushon** [comment]
This needs to be implemented like [the checkboxes in 3p-filters](https://github.com/dhowe/AdNauseam/blob/master/src/3p-filters.html#L56-L67)

On another note, I cannot see this on my version. This should be shown to users that update version, not only for new users. Right?

**Comment by dhowe** [comment]
1) This is is a disabled checkbox, and there is no case where the 3p-filters are disabled. The only difference between how they are, and the way that  disabled checkboxes appear the 'settings' tab is that the text is linked, so stays blue, even when disabled

2) The DNT list should show up on upgrade as well (to version 2.5.11 or higher). If it does not, then please create a ticket for the issue

**Comment by mushon** [comment]
so the problem here is that the checkbox & label do not seem disabled?
+
added #684

**Comment by dhowe** [comment]
the checkbox is actually disabled -- and we want people to be able to click to get more info
