### ISSUE TITLE
DNT checkbox doesn't appear after upgrade to 2.5.11

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#684]
Note, upgrading users do not go through the firstrun page.

![image](https://cloud.githubusercontent.com/assets/27123/21518494/913a7b64-ccef-11e6-92bd-8bdc76702e47.png)

**Comment by cqx931** [comment]
I tried one update from 2.4.1 to 2.5.11 and I can see the EFF checkbox. 
From which version did you do this update?
![image](https://cloud.githubusercontent.com/assets/3056154/21534843/eb96cf96-cda7-11e6-9e42-7e12a61cf872.png)

**Comment by mushon** [comment]
I don't know…

**Comment by dhowe** [comment]
most important is the last published (2.4.1)

**Comment by mushon** [comment]
Sure thing

-- 
Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

On December 29, 2016 at 11:43:01 AM, dhowe (notifications@github.com) wrote:

most important is the last published (2.4.1)

**Comment by dhowe** [comment]
where do we stand with this? @mushon can you test with a fresh version of 2.3 and 2.4  from the releases page?

**Comment by mushon** [comment]
I have just tried upgrading manually from 2.3 to 2.4 and there seems to be something very worrying. It looks like Chrome disallows the extension's activation:
![image](https://cloud.githubusercontent.com/assets/27123/21585484/d03123bc-d0c9-11e6-9a4e-f719854688df.png)
On the relevant Chrome page it says:
> If you see a message saying "Extensions Disabled," it's because Chrome has turned off one or more of your extensions to keep your data safe while you're browsing the Internet.
They also say the only way to turn it back on is through the web store. If that's the case I'm afraid our instructions won't work. And we've already started to get complaints like this:
https://twitter.com/altagrantla/status/815524065364557824

It looks like they pretty much kicked us out.

**Comment by dhowe** [comment]
Seems like we need a prominent announcement page for users who have this problem.

Question: does that message only come up when you quit the browser and re-open it? This is how it has been for awhile with dev-versions that are installed this way. So what our testers need to do is to keep the file on the desktop, and whenever they restart the browser, delete the old adn version, and re-drag in the new... Which removes the warning until the browser is next quite and restarted, when it re-appears

Can you test that this solves (temporarily at least) the problem for you?

**Comment by mushon** [comment]
I can confirm that deleting the extension and then installing it right after browser restart works.
On January 2, 2017 at 12:05:04 PM, dhowe (notifications@github.com) wrote:

Seems like we need a prominent announcement page for users who have this problem.

Question: does that message only come up when you quit the browser and re-open it? This is how it has been for awhile with dev-versions that are installed this way. So what our testers need to do is to keep the file on the desktop, and whenever they restart the browser, delete the old adn version, and re-drag in the new... Which removes the warning until the browser is next quite and restarted, when it re-appears

Can you test that this solves (temporarily at least) the problem for you?

**Comment by dhowe** [comment]
Shall we update the instructions and the gif to show this?

Also, what do you think about an announcement page (for press, and for users that run into the problem?)

**Comment by mushon** [comment]
This is quite required.
Say, wouldn't this update process delete all previous data?

-- 
Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

On January 2, 2017 at 7:01:53 PM, dhowe (notifications@github.com) wrote:

Shall we update the instructions and the gif to show this?

Also, what do you think about an announcement page (for press, and for users that run into the problem?)

**Comment by dhowe** [comment]
Yes, actually

**Comment by mushon** [comment]
So do we really want people to update ADN and lose their data or do we want to also teach them how to export and import (they won’t do that) or do we want them to hold on until we sort things out with GOOG?

-- 
Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

On January 2, 2017 at 7:27:06 PM, dhowe (notifications@github.com) wrote:

Yes, actually

**Comment by dhowe** [comment]
I don't know

**Comment by dhowe** [comment]
Btw, do we want upgrading users to go through the first run-page?

**Comment by mushon** [comment]
Right now they will be required to go through the firstrun page because of the web store shenanigans. Otherwise I suggest they only go through it if there are fundamental settings changes for them to review.

**Comment by dhowe** [comment]
progress on an announcement page?

**Comment by mushon** [comment]
Either way we need to acknowledge this issue on our site. So let's start with 2 quick wiki pages and link to it from the homepage: 1. acknowledging the removal from the webstore, 2. instructing how to install (including export/import)
Finally, I am not sure what to do about users who cannot access their current ADN, how would they export their content?

**Comment by cqx931** [comment]
Another workaround is to install unpacked extension from developer mode.
Whenever the user quit chrome and restart it, there will be a warning regarding to "Disable Developer Mode Extensions", but users can just click 'cancel' and everything works fine.
With this method,  users at least don’t need to delete and reinstall the extension every time they quit the browser.
![image](https://cloud.githubusercontent.com/assets/3056154/21607591/2a4e6156-d1f2-11e6-8776-b1be4e16a98d.png)

**Comment by mushon** [comment]
this ticket has been diverted by the recent events.
I tried and could not recreate the problem I originally reported. I suggest we close it and revisit later if need be. the installation issue should be tracked separately. what say you @dhowe?

**Comment by dhowe** [comment]
agreed
