### ISSUE TITLE
Icon: should be green when on a DNT site

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#685]

**Comment by mushon** [comment]
icons added in https://github.com/dhowe/AdNauseam/commit/98272ff605ed7ab2eb6896afc4fc33010de842b6
you will see 16px 32px and SVG for all states

**Comment by cqx931** [comment]
is it like how an ad is being visited?
So currently when an ad is being visited, the color is first blue and is marked as purple when finished.
Do you want to change the blue/purple to green or both?

**Comment by dhowe** [comment]
These are actually two different, unrelated items (both low priority):
- [ ] Click animation when an ad is visited (fingers goes down, then back up)
- [ ] Icon turns green when the page is a DoNotTrack Page and either DNT is enabled

**Comment by mushon** [comment]
yes, these are two different items as described above.
I submitted 2 green icons because in some cases there will be clicking in DNT sites.

**Comment by mushon** [comment]
ok, though the clicking animation appears in our video and I would love to get it back in sooner rather than later.

**Comment by cqx931** [comment]
Finish "Icon turns green when the page is a DoNotTrack Page and either DNT is enabled"
Except this issue in Firefox: https://github.com/dhowe/AdNauseam/issues/695

**Comment by cqx931** [comment]
All fixed and done.

**Comment by cqx931** [comment]
New ticket for click animation: https://github.com/dhowe/AdNauseam/issues/692
