### ISSUE TITLE
Notification when locale files have changes (adnauseam.messages) ?

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#689]
If an entry in 'adnauseam.json' is updated, is there some mechanisms for notifying us that new translations will be needed? if not, we may want to add this...

**Comment by dhowe** [comment]
Some mechanism, by which we make sure that all locale files stay in sync with `adnauseam.json`. For example, one developer changes or adds new strings to the file -- how do the other devs, and the translators, know that these strings now needs to be translated/updated?

**Comment by cqx931** [comment]
in make-locales.sh, check adnauseam.json of English with a language from the language list that we are going to include in the output. 
1.If the total length of entries don't match
new entries have been added to the english locale file, the translation need to be updated.
-> Show Warnings
2. If in any entry,  the two descriptions don't match with each other, it means that the translation and english locale file is out of sync.
-> Show Warnings with the key of the entry that is out of sync

**Comment by dhowe** [comment]
sounds good

**Comment by cqx931** [comment]
Please check https://github.com/dhowe/AdNauseam/pull/869
