### ISSUE TITLE
Install Instructions for non-webstore install on Chrome

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#690]
Urgently need clear/easy instructions for install when user clicks 'Install-for-Chrome' icon on the website (perhaps with screenshots, and/or video?):

1. Download the current "Chromium" release (a .crx file) to your computer. You may receive the following prompt:

![screen shot 2017-01-01 at 2 09 21 pm](https://cloud.githubusercontent.com/assets/737638/21580378/35f78f54-d02c-11e6-86a5-8702248b9e73.png)

&nbsp; &nbsp; &nbsp; &nbsp;If so, click 'continue', and the extension will appear in your browser's Downloads folder.

2. Open the Chrome Browser's preferences page (chrome://settings)

3. In the side-bar select "Extensions"  (chrome://extensions)

4. Drag the file you downloaded in and drop it over the open 'Extensions' page. A notification will inform about the permissions AdNauseam requires. Click "Add extension".

5. You should now be presented with AdNauseam's "first-run" page. Select your options, close the settings page, and start browsing!

**Comment by mushon** [comment]
Fixed in https://github.com/dhowe/AdNauseam/commit/fd1d9c7b505025d09fb146985456422624752cc0 with a simple sentence and an animated GIF:
![image](https://cloud.githubusercontent.com/assets/27123/21580689/041359ea-d014-11e6-892b-eb2e06c6e84f.png)

Reassigning to @dhowe to use JS to couple the lightbox opening and the extension download to save the extra click

**Comment by dhowe** [comment]
I'm thinking it might be more clear if people have to click to save the file (rather than it happening automatically, and they perhaps don't notice)

**Comment by cqx931** [comment]
I find it a bit confusing that the lightbox opens a new window rather than an overlay on the same page that you can close with an 'X' button.

**Comment by dhowe** [comment]
Yes, I agree -- my expectation was an overlay as well...

**Comment by mushon** [comment]
But it is an overlay. Or are we talking about something else?
![image](https://cloud.githubusercontent.com/assets/27123/21585380/93d04814-d0c7-11e6-8406-0f04c7f704bd.png)

**Comment by dhowe** [comment]
It is an overlay, but it opens in a new tab, rather than over the current tab:

![screen shot 2017-01-03 at 12 54 30 am](https://cloud.githubusercontent.com/assets/737638/21593188/5991e7b0-d14f-11e6-9197-2161417ee4ac.png)

**Comment by nradov** [comment]
I don't think it's actually fixed. The instructions appear to be for MacOS and don't work correctly on Windows.

**Comment by dhowe** [comment]
You are correct, we are working on a new fix for all platforms -- thanks for the note
cc @mushon

**Comment by mushon** [comment]
Thanks, but we're going to drop this solution either way as we will need to suggest another solution, one that would require more detailed instructions.
