### ISSUE TITLE
Adjust ‘Block Malware’ language to address Google's 'Single Purpose' issue

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#691]

**Comment by mushon** [comment]
I suggest we switch the language to "Block Malicious Ads"

**Comment by dhowe** [comment]
agreed

**Comment by mushon** [comment]
![image](https://cloud.githubusercontent.com/assets/27123/21580656/892843dc-d011-11e6-9c63-3a8d8f623c37.png)
fixed in https://github.com/dhowe/AdNauseam/commit/b4cae736a71139a88a1ee2c7768e4e2721fa7f73
