### ISSUE TITLE
Icon: animate when an ad is being visited

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#692]

**Comment by cqx931** [comment]
Is this clicking animation related to the current tab the user is on? (click only when the ad.pageUrl matches with the current url)
Or is it irrelevant to where the user is and simply animate a clicking icon even if the ad currently being visited is from another page?

**Comment by cqx931** [comment]
Another issue is the default location of the badge in chrome. It covers the right left half of the finger tip, which makes the clicking less observable. 
And using the setBadge API of chrome is doesn't support badge location.
This is ok on firefox as the default there is on top right corner...

Please let me know your opinion on this. @dhowe

**Comment by dhowe** [comment]
I would prefer not to make any non-critical firefox-specific changes until after we start using web-extensions, as some issues may be no longer relevant

**Comment by cqx931** [comment]
There is no firefox-specific changes here.... The badge issue is a chrome issue as the lower right corner default is for chrome.
The badge issue is not that critical...I can first implement the clicking, you and Mushon can check later how you feel about it. 
But I need to confirm this question before I submit my changes:

> Is this clicking animation related to the current tab the user is on? (click only when the ad.pageUrl matches with the current url)
> Or is it irrelevant to where the user is and simply animate a clicking icon even if the ad currently being visited is from another page?

**Comment by dhowe** [comment]
Understood. The clicking action should happen whenever an ad is successfully visited, regardless of the current page

**Comment by cqx931** [comment]
done

**Comment by cqx931** [comment]
On opera, the fingertip is hardly visible...
![image](https://cloud.githubusercontent.com/assets/3056154/22183042/261f9346-e0ef-11e6-839b-2b1413680edb.png)
