### ISSUE TITLE
PageStore doesn't get updated in Firefox when address bar updates within the same tab

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#695]
In firefox, the dnt detection works fine when I first open a tab.
But later, when I go to some other sites within the same tab, the result is wrong and the reason is that the pageStore object doesn't get correctly updated as it is in chrome.

To reproduce:
0.Uncomment this line: https://github.com/dhowe/AdNauseam/blob/master/src/js/tab.js#L910 and rebuild.
1.In Firefox, open a new tab and go to duckduckgo.com, the pageStore info is correct, the icon turns green, everything works fine.
2.Now go to google.com within the same tab, the pageStore info log in the console is still duckduckgo. See Image:
![image](https://cloud.githubusercontent.com/assets/3056154/21586537/2e723bf8-d10d-11e6-842e-238ebbdd3af9.png)

**Comment by dhowe** [comment]
I can't verify this -- @mushon can you try (follow instructions above)?

**Comment by cqx931** [comment]
solved.
