### ISSUE TITLE
Dynamically generated Ads are not rendered with the latest version

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#697]
![image](https://cloud.githubusercontent.com/assets/3056154/21606476/ceec6dbe-d1ea-11e6-80e5-ca973429763d.png)

The logging from background console and uBlock interface looks ok.
![image](https://cloud.githubusercontent.com/assets/3056154/21606468/bf36dbfc-d1ea-11e6-9c87-3b36accff53f.png)

**Comment by cqx931** [comment]
A simple test case: http://chenqianxun.com/testcases/dynamicAd.htm

**Comment by dhowe** [comment]
Commenting out the redirect of that script causes the ad to show up as usual:

![screen shot 2017-01-04 at 12 41 33 am](https://cloud.githubusercontent.com/assets/737638/21614969/9a9a7d86-d216-11e6-8583-66a6ae3c5eb6.png)

Sounds like we need to add special allow rules for such cases?

**Comment by dhowe** [comment]
@cqx931 please verify on your test case and nyt and then close

**Comment by cqx931** [comment]
verified.
