### ISSUE TITLE
Text beneath 'Block Malicious Ads'

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#698]
Currently it reads: 'Block malware and non-visual trackers', but its not clear what this has to do with ads.

Perhaps....

- Block potentially malicious ad-tracking code
- Block Ad beacons, tracking images, and other invisible malware

or...

?

**Comment by mushon** [comment]
I see you used:
> optimize your settings to protect against malicious Ads (customize)

I think it's fine, especially since we describe in more details what we do exactly on the FAQ.
