### ISSUE TITLE
Ad statistics for 10 sites

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#699]
**Step 1**

- [x] Identify 10 pages on different sites that have Ads 
- [x] In a new Chrome browser profile, with no extensions, or other modifications, visit each site
- [x] Allow the page to load to completion and note the # of visual Ads you can find
- [x] Now build/install AdNauseam in Chrome, according to the [DevFAQ](https://github.com/dhowe/AdNauseam/wiki/Building-AdNauseam-from-source-(for-developers)) and enable all options on the first-run-page (hiding, clicking, blocking)
- [x] Revisit each page and note the # of visible ads you can still see
- [x] Also note the # of ads _collected_ by ADN for each page (via the menu button)

Step 2 will be to debug any ads that were not hidden and/or not collected by AdNauseam, but lets talk before you start this. Place your data directly in the ticket below, with pageUrl, and 3 data fields (total, hidden, collected) for each page, then add me to ticket's _Assignees_ on the right so I know to respond.

&nbsp;

**Comment by sindhubr** [comment]
Table with observations(10 pages) have been noted in the following document: https://docs.google.com/document/d/1R-8sgrZD1HMhKtJ4iTrjVHqJK_a2yyzcQmUnzi8KI_o/edit

**Comment by dhowe** [comment]
please post them in the ticket here (or a screenshot at least)

**Comment by sindhubr** [comment]
Retested the following pages using  on firefox:
these are the pages and test results -

- Page 1: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=buy%20gift%20cards%20online
Ads visible: 9 (9 + 4 : 8 + 1(5 ads were repeated but with different cost description))
Ads successfully clicked: 9 (in purple) [clicked 9 / 9 Ads detected = $14.22]
Ads seen with ADN: 0
- Page 2: http://www.health.com/
Ads visible: 1
Ads successfully clicked: 1 (in purple) [clicked 1 / 1 Ads detected = $1.5]
Ads seen with ADN: 0
- Page 3: https://techcrunch.com/
Ads visible: 3
Ads successfully clicked: 3 (in purple) [clicked 3 / 3 Ads detected = $4.74]
Ads seen with ADN: 0
- Page 4: https://www.amazon.com/
 Ads visible: 2 (2 ads by same vendor)
Ads successfully clicked: 1 (in purple) [clicked 1 / 1 Ads detected = $1.58]
 Ads seen with ADN: 0
- Page 5: https://www.google.com/search?q=blue+apron&rlz=1C5CHFA_enUS692US692&oq=bluea&aqs=chrome.1.69i57j0l5.3494j0j4&sourceid=chrome&ie=UTF-8
Ads visible: 7
Ads successfully clicked: 7 (in purple) [clicked 7 / 7 Ads detected = $11.06]
Ads seen with ADN: 0
- Page 6: https://www.google.com/search?q=blue+apron&rlz=1C5CHFA_enUS692US692&oq=bluea&aqs=chrome.1.69i57j0l5.3494j0j4&sourceid=chrome&ie=UTF-8#q=buy+coffee
Ads visible: 15
Ads failed: 1 (Starbucks)
Ads successfully clicked: 14 (in purple) [clicked 14 / 15 Ads detected = $22.12]
Ads seen with ADN: 0
- Page 7: https://www.yahoo.com/
Ads visible: 19 [was a tricky page]
Ads successfully clicked:  19 (in purple) [clicked 19 / 19 Ads detected = $30.02]
Ads seen with ADN: 0
- Page 8: http://www.ebay.com/
Ads visible: 1
Ads failed: 1 
Ads successfully clicked: 0 (in purple) [clicked 0 / 1 Ads detected]
Ads seen with ADN: 0
- Page 9: http://www.imdb.com/
Ads visible: 1
Ads successfully clicked: 1 (in purple) [clicked 1 / 1 Ads detected = $1.58]
Ads seen with ADN: 0
- Page 10: https://www.google.com/search?q=spotify&rlz=1C5CHFA_enUS692US692&oq=spotify&aqs=chrome..69i57j0l5.1870j0j4&sourceid=chrome&ie=UTF-8#q=gym+membership
Ads visible: 7
Ads successfully clicked: 7 (in purple) [clicked 7 / 7 Ads detected = $11.06]
Ads seen with ADN: 0

**There were two failed cases**

**Comment by sindhubr** [comment]
**There were 2 instances, where the ads were by same vendor and ADN counts n number of ads by same vendor as 1**

**Comment by sindhubr** [comment]
Failed Ad visits :
https://github.com/dhowe/AdNauseam/issues/753

**Comment by dhowe** [comment]
- The highest priority case is visible ads, so please create a separate ticket for those with high-priority.
- The medium priority case is when ads are hidding, but not collected by adn (that is they don't show up in the vault. Create a separate ticket for these.
- The low priority case is when visits fails (you've already created a ticket for this).

But I'm confused by your comment above -- ADN should NOT treat multiple ads by the same vendor as 1, UNLESS they are are the exact same image... Please clarify

**Comment by sindhubr** [comment]
In the above tested cases every instance is successful unless the vendor is same.
The image was same but description was different in one page and images were different in another instance but vendor was amazon. I will try running it on same page and create a ticket, running ADN on different pages as well, will update those results here.

**Comment by dhowe** [comment]
In such cases, where different Ads appear to be treated as one, please include both Ad's JSON in the ticket (to do so,open the vault, inspect the Ad in question, then press the 'd' key to output the data to the console) .
