### ISSUE TITLE
DNT links in FAQ page

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#704]
The current link for "Make exceptions for non-tracking Ads" on first-run page and the two options on settings page is the following link:
https://github.com/dhowe/AdNauseam/wiki/FAQ#how-and-why-does-adnauseam-make-exception-for-non-tracking-ads

However, there is no corresponding entry in FAQ, shall I change it to this link instead?
https://github.com/dhowe/AdNauseam/wiki/FAQ#what-is-the-effs-do-not-track-standard-and-how-it-is-supported-in-adnauseam

**Comment by dhowe** [comment]
yes please

**Comment by cqx931** [comment]
fixedhttps://github.com/dhowe/AdNauseam/pulls
