### ISSUE TITLE
uBlock version number

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#705]
According to the commit, the uBlock version we are based on seems like 1.9.7.4.
https://github.com/dhowe/AdNauseam/commit/40a85f8c04840ae5f5875c1e8b5fa17578c5bd1a

The manifest file we have for uBlock is on 1.9.7.100.
Should this be changed to 1.9.7.4? @dhowe

**Comment by dhowe** [comment]
Hmmm, I wonder how those got out of sync...

**Comment by dhowe** [comment]
Please update

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/715/commits/02f98789f334a6cb70a61a0573291c2922de5fd5 fixed
