### ISSUE TITLE
Ad Cost information shows up with a long delay in menu and vault page

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#706]
For both menu and vault, if there is previously no ad collected, the cost information is hidden.
Now what I can observe is that the cost of ads is going to be calculated by each click, and added up gradually. And because the clicking is only going to happen if the extension is idle, I need to wait for quite a long time to be able to see the cost for pages like nytimes.

This performance seems a bit weird for me...should the ad calculation separated from the ad clicking and being displayed immediately when ads are collected?

**Comment by dhowe** [comment]
Well, we need to disable the idle timer as this will not go into v3.0... But its a good question nonetheless. The thinking was that, until the ad is clicked, we haven't actually cost the ad network anything. What about on failed visits? Are these currently calculated in the displayed amount? If not, then things should stay as they are (we only calculate cost for successful clicks, after they happen). Alternatively, we could derive the cost from ALL ads, regardless of whether they are clicked, and this would fix the problem you suggest above, but it is a less accurate representation...

**Comment by cqx931** [comment]
No, if a visit fails, the cost won't be added to the calculated ammount.

I see your points here...I think what bothers me is that this delay tends to be way more longer than necessary.
From the logger I often see this kind of log from IDLER:
![image](https://cloud.githubusercontent.com/assets/3056154/21668955/356ccd6a-d342-11e6-9119-91ccf21cc0c0.png)
For pages like nytimes, the waiting time to see the first click varies from 15 seconds to 2 minutes.  And for the next click it needs wait for the IDLER again... 

Or we could modify the IDLER a bit (shorter waiting time), and keep the cost calculation as it is now.

**Comment by dhowe** [comment]
Is it the case, that the Idler waits 30 seconds for every click, even if you don't use the browser? If so, this is a bug. 

Otherwise, we can discuss the best timeout value when we add the feature (which will be disabled by default) in 3.1

**Comment by cqx931** [comment]
If this is not going to be included in 3.0, I will get back to this later.

**Comment by cqx931** [comment]
close for now
