### ISSUE TITLE
[Firefox] AdVault doesn't automatically refresh when importing/clearing ads

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#709]
In chrome, this refresh happens automatically.
In firefox, when I click 'clear' and 'ok', the ads doesn't go away until I manually refresh the page.

**Comment by dhowe** [comment]
fix this to 3.0 only if there is an easy fix, otherwise push to 3.1

**Comment by cqx931** [comment]
This seems to like another issue influenced by having uBlock & AdBlock Plus installed at the very beginning. Fixed when I disable them before I launch the Firefox Dev.

We might need to verify all the releasing test later on a normal firefox browser and see whether AdNauseam's Performance would be influenced if uBlock/AdBlock Plus are disabled after AdNauseam is installed.

**Comment by dhowe** [comment]
Ok, please create a 3.1 ticket for this
