### ISSUE TITLE
“CAUTION: provisional headers are shown” from successful ad visit

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#717]
Sometimes I see  “CAUTION: provisional headers are shown” when I test the headers of ad visit.
![image](https://cloud.githubusercontent.com/assets/3056154/21676870/8ae6fcf4-d372-11e6-84a9-5a626f522532.png)
http://stackoverflow.com/questions/21177387/caution-provisional-headers-are-shown-in-chrome-debugger
I searched for it and in the above stackoverflow page, it is said that "The message is there because the request to retrieve that resource was never made, so the headers being shown are not the real thing. " But the ad visit of this specific request was successful. So I am a bit confused why we got this.

**Comment by dhowe** [comment]
That is strange -- can you recreate it consistently?

**Comment by cqx931** [comment]
I see this almost on every major site that I used to check for headers.
But what strange is, this is not happening consistently to a specific request.
If I see this on one request and refresh the page, the headers could be normal again.

**Comment by cqx931** [comment]
I can see this on most of the web requests for a page if I use uBlock. But our ad requests shouldn't be influenced by uBlock...

I have checked this issue more in details using this tool: chrome://net-internals/#events, as suggested in the above stackoverflow ticket.

When I check the web request with net-internals, the request headers from what marked as “CAUTION: provisional headers are shown" in the network console seems to be ok. 

I'm not sure why these two interface shows different result... but I find this net-internal really helpful as it shows detailed information about how AdNauseam modified the header step by step...

![image](https://cloud.githubusercontent.com/assets/3056154/21711599/b4a375aa-d42a-11e6-9cdc-c5e48d7b7603.png)

**Comment by dhowe** [comment]
nice

**Comment by cqx931** [comment]
I have added this to 'Tools' section in the wiki page ['Testing New Release Candidates'](https://github.com/dhowe/AdNauseam/wiki/Testing-New-Release-Candidates) and mentioned it when the test is related with network events.

**Comment by cqx931** [comment]
> Please notice that, sometimes there is a “CAUTION: provisional headers are shown” message when you check headers in the console. If you see this message, the headers shown are not reliable. Therefore it should not be considered as a reference when checking the headers during test release/ debugging. Check other requests or use` net-internals` instead.

I have added the above note in the release testing wiki page. This ticket can be closed for now.
