### ISSUE TITLE
Perform release testing on a normal Firefox browser

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#718]
-Install uBlock and AdBlock Plus on Firefox
-Install AdNauseam and go through first-run Page
-Disable uBlock and AdBlock Plus

-Go through tests for a new release and see whether there is anything that does not work.
https://github.com/dhowe/AdNauseam/wiki/Testing-New-Release-Candidates

**Comment by dhowe** [comment]
@sindhubr ?
