### ISSUE TITLE
how do I donate

### ISSUE THREAD

**Issue by jekrb** [dhowe/AdNauseam#723]
I love this.  I want to give some BTC.

**Comment by 12309exp** [comment]
bump. I will donate you 1 bitcoin if you provide an address.

**Comment by 12309exp** [comment]
> https://github.com/dhowe/adnauseam/wiki/FAQ#donations--is-that-your-real-business-model

> If this sounds fair to you and you still want to show your support through a donation, please use the following Bitcoin address: 1NiwkdL8Dm9DiTxp7uxNVDnxESAotg6En2

I've sent you a donation, please continue with providing some good butthurt to Google & friends.

**Comment by dhowe** [comment]
much appreciated @12309exp 
we will do our best :)

**Comment by jekrb** [comment]
Cool @12309exp thanks for posting the info here! I've just sent some Bitcoin over 🎉
