### ISSUE TITLE
Consider AdNauseam for Safari...

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#724]
https://github.com/el1t/uBlock-Safari

**Comment by Chekushkin** [comment]
Safari support is present in release 3.1? Is there a way to install 3.1 or to build extension for safari?

**Comment by dhowe** [comment]
I still don't see any Safari releases [here](https://github.com/gorhill/uBlock/releases). Where do you find 3.1 for Safari?

**Comment by Chekushkin** [comment]
Well I got it from here. https://www.ublock.org/newdl/safari/0.9.5.2 I know it's not source but still =)

**Comment by Chekushkin** [comment]
Also 3.1 release I mentioned was about your releases. 
![screen shot 2017-02-28 at 10 29 46 am](https://cloud.githubusercontent.com/assets/10373339/23397374/ed095190-fda0-11e6-85e3-6d5d60c41450.png)

**Comment by dhowe** [comment]
Correct me if I'm wrong, but that project is [uBlock](https://github.com/chrisaljoudi/uBlock). We are built on [uBlock Origin](https://github.com/gorhill/uBlock), which is a different (though similar) codebase

**Comment by dhowe** [comment]
@cqx931 can you take a look at what's been added to uBlock for safari support ?

**Comment by Chekushkin** [comment]
@dhowe sorry, my fail, I thought it's the same =(

**Comment by dhowe** [comment]
no worries... we will look into the changes in any case

**Comment by DylanLukes** [comment]
Only low priority :(?

**Comment by dhowe** [comment]
We are quite short on coders -- if anyone can help us on this ticket, we will certainly bump the priority up... thanks

**Comment by DylanLukes** [comment]
I'll be more than happy to take a look at how much work is involved this weekend. If possible I'll take a crack at it. uBlock Origin supports Safari so I suspect that it shouldn't be too difficult.

**Comment by dhowe** [comment]
You may want to check out our [DevFAQ](https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ) to see how we build things (from uBlock)

**Comment by RaminBourne** [comment]
I had no idea  and never heard of such a priceless tool! Until now..https://www.fastcompany.com/3068920/google-adnauseum-ad-blocking-war

I am not a coder sadly ... but please support as many browsers as your time and energy allows! :-)

Also, set up some PayPal account if you like, so people like me can show their appreciations for your hard work. :-)

**Comment by dhowe** [comment]
@RaminBourne thanks for the note - we will indeed continue trying to support more browsers...
Please see https://github.com/dhowe/AdNauseam/wiki/FAQ#donations--is-that-your-real-business-model

**Comment by twodayslate** [comment]
Safari now supports [WebExtensions](https://hacks.mozilla.org/2020/06/welcoming-safari-to-the-webextensions-community/)

**Comment by dhowe** [comment]
excellent -- is this only on desktop?

**Comment by twodayslate** [comment]
@dhowe yes, that is my understanding

**Comment by dhowe** [comment]
well it's a start at least...

**Comment by lessless** [comment]
not a strict necessity but will be good to have

**Comment by us** [comment]
I converted with `/Applications/Xcode.app/Contents/Developer/usr/bin/safari-web-extension-converter` then result is <br>
<img width="430" alt="Screen Shot 2020-12-17 at 20 28 28" src="https://user-images.githubusercontent.com/22618852/102521809-6d740180-40a6-11eb-8150-0368ca2c4401.png">

**Comment by theotheroracle** [comment]
looks promising at least . I'm new to the project but willing to contribute, will take a look through the docs tomorrow and see what I can do . ( or let me know if there's anything in particular I should look into )

**Comment by dhowe** [comment]
great @theotheroracle please see this ticket with link to instructions...

**Comment by dhowe** [comment]
Anyone interested in discussing, or... better still, helping to develop, AdNauseam for Safari, see this ticket: https://github.com/dhowe/AdNauseam/issues/1761

**Comment by cootshk** [comment]
just run xcrun safari-web-extension-converter /path/to/extension and then build for Mac

**Comment by cootshk** [comment]
and then allow unsigned extensions in safari settings

**Comment by Alocart** [comment]
> just run xcrun safari-web-extension-converter /path/to/extension and then build for Mac

- downloaded extension for Firefox
- ran `xcrun safari-web-extension-converter ~/Downloads/adnauseam-3.18.0.xpi`
- got an error: `Unable to parse manifest.json at file:///Users/user/Downloads/adnauseam-3.18.0.xpi`

**Comment by cootshk** [comment]
> > just run xcrun safari-web-extension-converter /path/to/extension and then build for Mac
> 
> * downloaded extension for Firefox
> * ran `xcrun safari-web-extension-converter ~/Downloads/adnauseam-3.18.0.xpi`
> * got an error: `Unable to parse manifest.json at file:///Users/user/Downloads/adnauseam-3.18.0.xpi`

Use the chrome one, not the Firefox one when converting to safari

**Comment by Alocart** [comment]
> > > just run xcrun safari-web-extension-converter /path/to/extension and then build for Mac
> > 
> > 
> > 
> > * downloaded extension for Firefox
> > * ran `xcrun safari-web-extension-converter ~/Downloads/adnauseam-3.18.0.xpi`
> > * got an error: `Unable to parse manifest.json at file:///Users/user/Downloads/adnauseam-3.18.0.xpi`
> 
> Use the chrome one, not the Firefox one when converting to safari

have just tried it: same error.
