### ISSUE TITLE
Consider AdNauseam for Edge browser

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#725]
https://github.com/nikrolls/uBlock-Edge

**Comment by LeoNatan** [comment]
Attack on all fronts, including Microsoft's not so inferior but still terrible to use new browser! It's important!

**Comment by siegenthalerroger** [comment]
Is there anything explicitly blocking this or is this up for grabs?

**Comment by dhowe** [comment]
not that I'm away of (go for it)...

**Comment by dhowe** [comment]
I believe this should work now (following the instructions for chrome browser).
Feel free to re-open if problems arise
