### ISSUE TITLE
How to deactivate "AdVault"?

### ISSUE THREAD

**Issue by javra** [dhowe/AdNauseam#726]
I don't really care about which and how many ads were blocked cumulatively. Isn't there a way to deactivate this sort of history?

**Comment by dhowe** [comment]
To click ads, they need to be collected and stored, at least until the visit has finished -- the vault is just a way of viewing them (which, of course, you don't need to open). The only downside of keeping ad-data for viewing in the vault later is that it uses a bit of memory, however this is just text and isn't very large at all. Are you suggesting a sort of click and forget option, and if so, what is the motivation (performance, privacy, or ...) ?

**Comment by javra** [comment]
"Click and forget" is basically what I had in mind. I'm on a slow machine with not much memory, so performance was my main motivation. Somehow I expected that the clicked images are really downloaded. If that is not the case, I'm almost already satisfied ;)

**Comment by dhowe** [comment]
They are not downloaded unless you use the vault -- only the ad meta-data is stored (target-url, img-url, etc)

**Comment by javra** [comment]
Okay, thanks for the clarification :)

**Comment by brmbrmcar** [comment]
I've just started using it for about half an hour, and already it has used 15944623 bytes. This would quickly become a problem. I am worried that very soon my small SSD will fill up. I realise that it is not meant to store images, but it is still using up several megabytes of space in very little time.

**Comment by greysonevins** [comment]
@brmbrmcar for now that isn't an option, however, you can always clear your vault whenever you want by opening the ad vault and clicking the "Clear" option.

**Comment by javra** [comment]
For me the issue led to the deactivation of AdNauseam. If @brmbrmcar needs to clean the "Vault" every few hours I guess he'll do the same.

**Comment by greysonevins** [comment]
@dhowe should we reopen this feature improvement for "Click and Forget"?

**Comment by brmbrmcar** [comment]
I (temporarily) forcibly locked the files controlling the data it uses. Maybe not a good idea, but it's temporary.

**Comment by dhowe** [comment]
@brmbrmcar that seems a very high number -- are you scripting your browser?

**Comment by brmbrmcar** [comment]
No.... I don't think so anyway. Only a few ads were downloaded apparently.

**Comment by dhowe** [comment]
Do you mind posting your exported ad JSON here or sending it to us directly (note that it contains the URLs for pages you visited) ?

**Comment by brmbrmcar** [comment]
It literally just says

`{}`

**Comment by dhowe** [comment]
Again, the ad vault is not activated unless you use it. So if you don't care about it, then simply don't click it. 

If, on the other hand, you are on a device with _highly_ limited storage, an embedded system for example, this is a different case. We may need to open a ticket for a minimum-resource version, though my sense is that the size of this text file is negligible for the vast majority of users.  Another option would be to implement a maximum size for this file, at which point older entries are overwritten.
