### ISSUE TITLE
causes conflict with PrivacyBadger: failed to modify the response header "set-cookie" 

### ISSUE THREAD

**Issue by ericfont** [dhowe/AdNauseam#727]
I have had PrivacyBadger and now just installed AdNauseam.  When I visit http://www.cnn.com/2017/01/05/us/chicago-facebook-live-beating/index.html Chrome reported extension error for PrivacyBadger:

"This extension failed to modify the response header "set-cookie" of a network request because the modification conflicted with another extension (AdNauseam)."

I'm on Chrome Win 10 55.0.2883.87 m (64-bit),  PrivacyBadger  2016.12.15.1, AdNauseam sideload 3.0.4.

Should I report this to privacy badger instead?

**Comment by ericfont** [comment]
I should note that when I use uBlock Origin (v1.10.4) instead of AdNauseam, that I *don't* get the error.  So that leads me to think that AdNauseam is the one who ought to fix this.

I cross posted issue to https://github.com/EFForg/privacybadger/issues/1125 ...whichever one of you is not at fault I suppose can close this issue.

**Comment by ericfont** [comment]
The AdNauseam faq suggests to disable other adblockers, but doesn't say to disable privacybadger...
 <pre>Note: you should always disable other adblockers while using AdNauseam

Can I use AdNauseam with my current adblocker?

It is possible, but since your adblocker will likely block some, or all, of the Ads AdNauseam is collecting, this is NOT recommended. For the best experience, you should disable other adblockers while using AdNauseam.</pre>

**Comment by dhowe** [comment]
Yes, I'll look into the specific error you are talking about (which relates to potentially malicious cookies being blocked by AdNauseam and PrivacyBadger, but not uBlock), but the real answer is not to use more than one of these similar tools at once. Each is basically trying to do the same sort of thing (deciding which  resources should be blocked or hidden, and in the case of AdNauseam, clicked). I will update the FAQ to include PrivacyBadger (of which we are big fans, by the way)...

**Comment by cooperq** [comment]
This is really a case of bad UI on the part of chrome, since this is basically a non issue. These warnings should not be surfaced as readily as they are.
