### ISSUE TITLE
Yandex ads are not blocked

### ISSUE THREAD

**Issue by ojab** [dhowe/AdNauseam#728]
[Here](https://www.overclockers.ru/hardnews/81655/na-sajte-usb-if-obnaruzheny-neizvestnye-nauke-processory-amd-opteron.html), for examples, you can see three yandex banners in Firefox 50.1.0 (and 52.0a2 (2017-01-06), if that matters) with AdNauseam 3.0.4 installed that are not visible with uBlock Origin v1.10.4 installed.
AFAIU it's blocked by either EasyPrivacy list (`||an.yandex.ru^` filter), RUS: Adguard Russian Filter (`||an.yandex.` filter) or RUS: RU AdList (Дополнительная региональная подписка) (`||an.yandex.$third-party` filter).

Hide Ads/Click Ads/Block malicious ads are enabled and all three filters mentioned above are enabled here.

**Comment by Lourens-Rich** [comment]
Use Chromium and have similar problem with Yandex.Direct

**Comment by dhowe** [comment]
thanks -- will look into it...

**Comment by dhowe** [comment]
Fixed. To test, go to settings->3rd-party-filters, purge-all-caches, apply, then click 'update now':

<img width="1154" alt="screen shot 2017-01-07 at 11 43 52 am" src="https://cloud.githubusercontent.com/assets/737638/21739488/19855c70-d4d7-11e6-9738-d40c3df33778.png">

**Comment by dhowe** [comment]
Note: only 2 ads collected -- see #356
