### ISSUE TITLE
Cannot build on ArchLinux

### ISSUE THREAD

**Issue by XuTpuK** [dhowe/AdNauseam#730]
make-chromium.sh produces error:
    *** Generating locale files in bin/build/adnauseam.chromium... sed: can't read s/uBlock?/AdNauseam/g : No such file or directory

Are you sure you debug script properly? That '?' after uBlock is some special character.
And hell... can we avoid that "generating locales"? Not everybody needs tons of localised messages.

**Comment by dhowe** [comment]
Currently [build instructions](https://github.com/dhowe/AdNauseam/wiki/Building-AdNauseam-from-source-(for-developers)) are only for OS X (apologies if this wasn't clear previously)... Linux instructions would be appreciated (changes should be minimal)
