### ISSUE TITLE
Two errors in vault console

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#738]
![screen shot 2017-01-10 at 9 22 17 am](https://cloud.githubusercontent.com/assets/737638/21790310/4e98e882-d716-11e6-871e-0e48667b90dd.png)

1. To recreate: open-vault

`jquery.js:3 GET chrome-extension://jhfefjmfelmdemjekibikhonjjffeflj/css/img/timeline-handle.svg net::ERR_FILE_NOT_FOUND`

2. To recreate, open-vault with console closed, inspect text-ad, open console and see error

`Uncaught TypeError: $ele.offset is not a function`

&nbsp;
---------------------

(Using Current Chromium)

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/pull/743
