### ISSUE TITLE
Add blocking rules to adnauseam.txt to improve the page load time

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#740]
Identify requests that are blocked by ublock but not adn, that don't result in visual ads, then add rules for these to adnauseam.txt

- [x] http://www.abcnews.go.com/
- [x] http://www.cnn.com/
- [x] http://www.foxnews.com/
- [x] http://www.nbcnews.com/
- [x] http://news.yahoo.com/
- [x] http://news.google.com/
- [x] http://www.nytimes.com/
- [x] http://www.theguardian.com/
- [ ] http://www.dailymail.co.uk/
- [ ] http://www.usatoday.com/
- [x] http://www.washingtonpost.com/
- [x] http://www.wsj.com/
- [x] http://news.bbc.co.uk/
- [x] http://www.latimes.com/
- [x] http://www.huffingtonpost.com/

latimes is very slow at the moment...I need to check it more in detail

**Comment by cqx931** [comment]
https://github.com/dhowe/uAssets/pull/20

**Comment by cqx931** [comment]
dailymail is a bit tricky at the moment... I can't see any ads even when no blocker is installed. Therefore it is hard to test whether a specific rule will influence visual ad.
Skip this one at the moment.

**Comment by dhowe** [comment]
Ok... and where did our test list come from? Is it the same that uBlock uses?

**Comment by cqx931** [comment]
yes, the same as uBlock

**Comment by cqx931** [comment]
Reference
![image](https://cloud.githubusercontent.com/assets/3056154/22094360/d9f53c7c-de47-11e6-87e6-9b549df50ab5.png)
