### ISSUE TITLE
Failing Ad Visit with error "200 (OK) undefined"

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#756]
One ad visit failing I see from the page:
http://www.mrfreeat33.com/its-not-about-the-money-rent-versus-buy/
```
 "id":11,
         "attempts":3,
         "visitedTs":-1484223106218,
         "attemptedTs":0,
         "contentData":{
            "src":"https://content.flexlinks.com/sharedimages/products/2026049/1424527.gif",
            "width":300,
            "height":250
         },
         "contentType":"img",
         "title":"Failed",
         "resolvedTargetUrl":null,
         "foundTs":1484223059106,
         "targetUrl":"http://track.flexlinkspro.com/a.ashx?foid=1090824.2026049&foc=2&fot=9999&fos=1",
         "pageTitle":"It’s Not About The Money: Rent Versus Buy – Mr. Free At 33",
         "pageUrl":"http://www.mrfreeat33.com/its-not-about-the-money-rent-versus-buy/",
         "errors":[
            "200 (OK) undefined",
            "200 (OK) undefined",
            "200 (OK) undefined"
         ],
         "current":true,
         "pageDomain":"mrfreeat33.com",
         "version":"3.1.20",
         "targetDomain":"flexlinkspro.com",
         "targetHostname":"track.flexlinkspro.com",
         "requestId":"19250"
```

For the above one, the resolved url I got from clicking the ad is this:http://personalcapital.go2cloud.org/aff_c?offer_id=4&aff_id=1028&url_id=27&aff_sub=2026049FOF50663385421450666
But it is a blank page, which is kind of strange.

![image](https://cloud.githubusercontent.com/assets/3056154/21890191/7df8cc12-d907-11e6-9362-738b8ea1164a.png)

**Comment by cqx931** [comment]
In this case, AdNauseam ad visit is failing because the returned string is empty.
Does this case need to be debugged? 
Or we shouldn't fail the visit if the returned string is empty?
https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L505

**Comment by dhowe** [comment]
If the returned string is empty that means the Ad goes to a blank page, which doesn't really make sense, because they are trying to sell something, not sell nothing...

**Comment by cqx931** [comment]
yes, it is strange... but I also landed in an empty page when I click the ad, so at least AdNauseam works fine in this case.

**Comment by dhowe** [comment]
right, ok... so either the ad went stale, or things worked correctly... either way, it should be a successful visit... I'll change the code

**Comment by dhowe** [comment]
if its possible to verify with this same ad, pls do...

**Comment by cqx931** [comment]
I don't think that the ad went stale, as I tested this live with the real page. Ok will do.

**Comment by cqx931** [comment]
It is still failing because html =this.responseText, and responseText="".

**Comment by dhowe** [comment]
I'm not sure what you mean, but go ahead and fix it if you see a solution...

**Comment by cqx931** [comment]
I just deleted any check on the responseText from the if statement.
So now the visit is successful and it just shows the domain of the link as the target.
![image](https://cloud.githubusercontent.com/assets/3056154/21900626/7fcb29ea-d92f-11e6-9de3-9802c8acbf81.png)

**Comment by dhowe** [comment]
I'm not sure of cases where responseText is null/undefined, but we may want to mark this as a failure
Anyhow, merging for now...
