### ISSUE TITLE
Website setting tracking cookies

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#764]
this is silly -- please address asap (see older #242)

![screen shot 2017-01-13 at 5 55 06 pm](https://cloud.githubusercontent.com/assets/737638/21925720/a233e0fa-d9b9-11e6-8bbd-d027a8a12bc0.png)

![screen shot 2017-01-13 at 5 55 13 pm](https://cloud.githubusercontent.com/assets/737638/21925716/9b8b1fd4-d9b9-11e6-844b-572135402cbb.png)

**Comment by mushon** [comment]
I am assuming these are generated by CloudFlare that manages our https, any ideas what to do about it?

**Comment by dhowe** [comment]
Contact them?

**Comment by dhowe** [comment]
@mushon status?

**Comment by mushon** [comment]
> The __cfduid cookie is used to override any security restrictions based on the IP address the visitor is coming from. For example, if the visitor is in a coffee shop where there are a bunch of infected machines, but the visitor's machine is known trusted, then the cookie can override the security setting. It does not correspond to any userid in the web application, nor does the cookie store any personally identifiable information.

> Note: This cookie is strictly necessary for site security operations and can't be turned off.

https://support.cloudflare.com/hc/en-us/articles/200170156-What-does-the-CloudFlare-cfduid-cookie-do-

**Comment by mushon** [comment]
Maybe we should use Let’s Encrypt instead?
https://letsencrypt.org/privacy/

**Comment by dhowe** [comment]
can you look into how to switch ?

**Comment by mushon** [comment]
Apparently, not very straight forward…
https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8

Truth is this is not my forte, not sure if I'm the right person to take on this. Sorry.

**Comment by dhowe** [comment]
@mneunomne can you check if this is still happening?

**Comment by migueldemoura** [comment]
Hey folks, this cookie has been removed and shouldn't be an issue anymore.

Further information here: https://blog.cloudflare.com/deprecating-cfduid-cookie/.

**Comment by mneunomne** [comment]
@dhowe i checked and couldn't find any of those cookies anymore. I believe this can be closed together with https://github.com/dhowe/AdNauseam/issues/242
