### ISSUE TITLE
Migrate to WebExtensions for Firefox

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#768]
We expect version 3.4 to be ready for WebExtensions. You can test the current release candidate here: https://github.com/dhowe/AdNauseam/releases/tag/v3.4.100

**Comment by bunnybooboo** [comment]
Nice one! Exciting label add. I've missed this in Nightly. You got a vague eta? Firefox 57 rolls to beta/dev edition ~ September 26, then to release November 14.

**Comment by dhowe** [comment]
the next release, hopefully in the next few days (v3.4.x)

**Comment by bunnybooboo** [comment]
Amazing work!! Hey, also a quick fyi that Dev Edition gets 57 (will be known as 'Quantum') from today (Sep 14), a week ahead of schedule. https://groups.google.com/forum/#!topic/firefox-dev/Lcw2YESfO_A

**Comment by dhowe** [comment]
thanks for that... testing with it now

**Comment by dhowe** [comment]
Please install and help test: https://github.com/dhowe/AdNauseam/releases/tag/v3.4.100

**Comment by bunnybooboo** [comment]
FYI @dhowe shows zero issues in 2 days of testing so far. Thanks so much man. I really missed this add-on!

**Comment by dhowe** [comment]
good news -- hopefully it will get approved soon by mozilla
