### ISSUE TITLE
Update listEntries whenever any list is updated

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#772]
call `adnauseam.onListsLoaded(false) `whenever an update happens

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/774 Please check

**Comment by dhowe** [comment]
lets discuss this afternoon

**Comment by dhowe** [comment]
@cqx931, please verify this works on automatic update as well...

**Comment by cqx931** [comment]
verified on automatic update
