### ISSUE TITLE
Whitelist rules are not working

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#775]
After adding a domain in dashboard.html#whitelist.html, adnauseam is not disabled on that domain.
I was trying to add Bertha's own site to the whitelist, and found out that whitelist is not working properly

**Comment by dhowe** [comment]
I can't recreate this... when I add a domain to whitelists (either manually or via the pause button) it shows up, and then ads are not hidden or collected. When I remove it from whitelists (manually or by clicking resume), they are again hidden.

**Comment by cqx931** [comment]
Can't recreate the issue with v3.0.5 on mac. Need to verify this on a PC later.

**Comment by dhowe** [comment]
pls recheck

**Comment by cqx931** [comment]
Rechecked with Bertha, white list is working. Closed.
