### ISSUE TITLE
Images in Facebook widget are parsed as ads

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#776]
`facebook.com##[id^="u_0_"]`

Can you still remember what this rule was supposed to hide?
Was Leon working on it? 

http://curvasian.com/

![image](https://cloud.githubusercontent.com/assets/3056154/22113419/32f864d0-dea1-11e6-92eb-e847d5aa1434.png)

**Comment by dhowe** [comment]
yes, I noticed that problem as well on curveasian

but I dont remember the intent of that rule (ask leon?)

**Comment by cqx931** [comment]
fixed now. The following rules can't be summed up to something like `facebook.com##[id^="u_0_"]`, it will influence other image loading on facebook. Only the following specific ones are for sponsor posts.
`facebook.com###u_0_4y
facebook.com###u_0_50
facebook.com###u_0_d
facebook.com###u_0_e
facebook.com###u_0_9
facebook.com###u_0_a
`
