### ISSUE TITLE
User needs to know when not seeing all ads in vault

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#777]
- We show a max of 300 ads when the vault is first opened to avoid endless loading of images
- Users need to know when they have more than this, and what to do to see them
- Current design is unintuitive (users think the limit is 300 ads)
- Current design minimizes impact, as users see $$$ amount for a max of 300 ads

Suggestions?

- TEXT: “432 Ads clicked of 1043 collected (300 Shown)”
- TEXT: "568 ads clicked of the 603 shown (1442 total?)" -> question-mark leads to instructions
- TEXT: "568 ads clicked of the 603 shown [click to see all]"
?

...

**Comment by cqx931** [comment]
As a user, I have always expected to see some summary numbers in the vault. 
Therefore I would argue for using total ads clicked to go with a total number of ads collected, which is the information that I care about the most.
How many ads are currently displayed could be used as a hint to tell the users that what they are seeing is only a part of the total collection.
And there should be a way to see the whole collection with a simple click (click to see all), except from using the slider.

**Comment by mushon** [comment]
can we maybe represent all ads as frames (using their actual proportions) and then offer to load them incrementally? That way we can separate the mode of display from the stats summery.

**Comment by dhowe** [comment]
Do you mean iFrames (potentially many thousand iFrames on the page)?

**Comment by mushon** [comment]
no, not at all, I mean html elements as placeholders for images which we will load incrementally. That way we show all the data we have and the composition is representative and it is only the images that are loading in their own pace. We can also show dynamic display stats like ``loaded 278/1238 images``

**Comment by dhowe** [comment]
this is not the issue -- the issue is that the display count only shows the total number of ads being shown, rather than the total amount collected (this is easy to see whenever you have more than 300 ads collected and you open the vault)

**Comment by mushon** [comment]
Gotchya.
Then in that case I think option 1 works best. Suggested modification:
``Clicked 432 of the 1043 ads collected (showing 300)``

**Comment by dhowe** [comment]
works for me, pls. make it so...

**Comment by mushon** [comment]
ok, I tried playing with the markup a bit, but what I committed needs some attention from @dhowe as the number needs to be coded in and I'm not sure I used the localization correctly

**Comment by dhowe** [comment]
@cqx931 please check

**Comment by cqx931** [comment]
I have fixed the text to `Clicked 432 of the 1043 ads collected (showing 300)` format
https://github.com/dhowe/AdNauseam/pull/932
But one thing I still need to check is to update the number of ads clicked after the ad is clicked.
Because now, instead of showing how many ads(showing) are clicked we are showing the total number clicked and the total number collected.
I got these two numbers from `gAds`, but it seems like that `gAds` only get updated when I reload the page. Need to check this more in details.

**Comment by cqx931** [comment]
Fixed the above problem here: https://github.com/dhowe/AdNauseam/pull/933

**Comment by mushon** [comment]
Awesome, thanks!

**Comment by dhowe** [comment]
Lets only show the '(x showing)' when it is a different number than the total amount
