### ISSUE TITLE
Menu and vault count agree on 2 ads, but only 1 shows in vault

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#78]
To recreate, clearAds, then visit this page: http://www.pcworld.com/article/2089364/how-to-create-and-manage-multiple-user-profiles-in-chrome.html

![screen shot 2016-03-22 at 8 54 52 pm](https://cloud.githubusercontent.com/assets/737638/13952272/786a9b52-f070-11e5-96fc-fe508cbaa1ba.png)

![screen shot 2016-03-22 at 8 55 06 pm](https://cloud.githubusercontent.com/assets/737638/13952277/7d25d206-f070-11e5-8879-ffc81dd5f0d9.png)

**Comment by CyrusSUEN** [comment]
Works correctly on my PC.
But we have a different ad#2
![1](https://cloud.githubusercontent.com/assets/2461812/14046306/8dca6bae-f2db-11e5-9e0f-eca4fb820ad6.PNG)
![2](https://cloud.githubusercontent.com/assets/2461812/14046307/8f09942c-f2db-11e5-83c7-bc06cf6b56f9.PNG)

attached exported ads as JSON:
```json
{
  "http://www.pcworld.com/article/2089364/how-to-create-and-manage-multiple-user-profiles-in-chrome.html": {
    "http://www.pcworld.com/article/2089364/how-to-create-and-manage-multiple-user-profiles-in-chrome.html::http://zapp0.staticworld.net/images/shared/icons/ad_choices_icon.png": {
      "id": 1,
      "attempts": 1,
      "visitedTs": 1458917093808,
      "attemptedTs": 1458917092498,
      "title": "About AdChoices - PCWorld - IDG Consumer & SMB | Covering All Aspects of Tech Life.",
      "foundTs": 1458917090642,
      "resolvedTargetUrl": "http://idgcsmb.com/about-adchoices-pcworld/",
      "contentType": "img",
      "targetUrl": "http://idgcsmb.com/about-adchoices-pcworld/",
      "pageTitle": "How to create and manage multiple user profiles in Chrome | PCWorld",
      "pageUrl": "http://www.pcworld.com/article/2089364/how-to-create-and-manage-multiple-user-profiles-in-chrome.html",
      "errors": null,
      "contentData": {
        "src": "http://zapp0.staticworld.net/images/shared/icons/ad_choices_icon.png"
      },
      "domain": "www.pcworld.com",
      "version": "2.0.3"
    },
    "http://sin1.g.adnxs.com/if?e=wqT_3QLdCPA8XQQAAAMA1gAFAQjvndW3BRDdpvG-0d7zvFYYgvCp--D28cYjIAEqLQlEF9S3zOnYPxGEkD2MWivXPxkAAAECDPA_IYQNEgApESSgMM3A7QI4tgJAvAlIZVCrtvEUWIztJWAAaKk8eMmUAoABAYoBA1VTRJIFBvTZA5gB2AWgAVqoAQCwAQC4AQLAAQXIAQLQAQDYAQDgAQDwAQDYAi_gAqnbJ-oCZWh0dHA6Ly93d3cucGN3b3JsZC5jb20vYXJ0aWNsZS8yMDg5MzY0L2hvdy10by1jcmVhdGUtYW5kLW1hbmFnZS1tdWx0aXBsZS11c2VyLXByb2ZpbGVzLWluLWNocm9tZS5odG1s8gIMCgpJTV9PQkFfQ1BT8gKWAQobRFlOQU1JQ19DUkVBVElWRV9QSVhFTF9EQVRBEndBUEV1Y05WVS1KVjFraF9ud09adGFJcm9SdEpjU05CQWtYbFNFb3lKQ2hiTG13NmN2alpnVVBoVkx2NzE0c01oSXFpLXR0ZTlHRFNKOW8wV2IybkxmOWJmQXQwVFItaXdTMy02Y2I2Y1FRa2ppdGtpR0l0RXI2NPICxAMKCEJJRF9EQVRBErcDQVBFdWNOVTg4c3FyMFVEaW1hQWcxMUtrZEljSWIwczl2dzZCdUtxMUJlaGVFYmcxbHBpVFprWUNnWVk4U1FweC1DUlRVS3l6UFNDak1YVFNwVWR3Z3VHUWJrQVNoblRPdVNRRV8xMzB4MVFqdlcxVG02cmktMjctdlFfVWc3LWtuQmxMZ0UtZXhFMTRTaUdZNnVWbk95M004R0hoSVowNFg3Y3RyVmh0ZUlweDBocUZ1cGJsVHk3cEtUbmV0eXo1ZUNHVEJYYXYtbl9fT2MtTUFTV1dMa2pwZUFJTFg5VGtUa0VFNTlVb0RBMHF4eTVqdjEzNFpqU3NVWUJiSndiMVplSFd5UUtKcUZRV1NiMWZJcGRwR3h0VzZMYXlGcWc0bWo4ZTktQkJjbnQtd1VmS0ZPZTVjcHBySldGdzJfazZEeWRvUzdaWE02UjlnWWtlaWJHQXpCT0xfSUp1OURoRDBtNlpjMF9RMmFkUDltZmZ5VmJoXzhxczBhaWZ0ZjJaNHc4czZxdHU5YlJJbWdMdklIZ0VuLWhKOGI0YnJXcGhhaEh6VUNGRzV1Q3lHaFZMN3IyQWtyWfICcQoLQkVBQ09OX0RBVEESYkFQRXVjTlh0UGg1TGExdUJwZXVGQ0ttN1pRaS04TDBfYkpCRmRJdlYwVC1NUHRjZzZVMllRTzU3YXBzMm1IY2o5UzNaN1lNRmZwTmRlLWtLQm42YXdjTWwzN0lxaEdCcGJ3gAMAiAMBkAMAmAMAoAMBqgMAsAMAuAMAwAOsAsgDANgDtbEk4AMA6AMA-AMBgAQAkgQEL3R0apgEAKIEDjU4LjE3Ni4xMjAuMTEyqATyQLIECAgAEAAYACAAuAQAwAQAyAQA&s=5b28928ea0574276f2780dbf8aee4d3abeb7bb5a&referrer=http%3A%2F%2Fwww.pcworld.com%2Farticle%2F2089364%2Fhow-to-create-and-manage-multiple-user-profiles-in-chrome.html::https://s0.2mdn.net/viewad/4663420/16-HKG72890TC.jpg": {
      "id": 2,
      "attempts": 1,
      "visitedTs": 1458917099290,
      "attemptedTs": 1458917097498,
      "title": "Mobile Special | HK Express",
      "foundTs": 1458917097437,
      "resolvedTargetUrl": "http://www.hkexpress.com/zh-hk/promo/mobile-special",
      "contentType": "img",
      "targetUrl": "https://adclick.g.doubleclick.net/pcs/click?xai=AKAOjsur_fV7224uwwIXxt52JdyluCQCWg6WHpE2smVV75nyA08GKSgIInuFbx6C1lYYxWnuahzrZgYCrz4-CL69HS2UYf8gsZ34A3DQus8TmDyzSjlue8QpWw&sig=Cg0ArKJSzL9RjKPNl6V0&urlfix=1&adurl=http://www.hkexpress.com/zh-hk/promo/mobile-special",
      "pageTitle": "",
      "pageUrl": "http://www.pcworld.com/article/2089364/how-to-create-and-manage-multiple-user-profiles-in-chrome.html",
      "errors": null,
      "contentData": {
        "src": "https://s0.2mdn.net/viewad/4663420/16-HKG72890TC.jpg"
      },
      "domain": "www.pcworld.com",
      "version": "2.0.3"
    }
  }
}
```

**Comment by yansh** [comment]
From what I see the problem is in the CSS. The image is there, just not displayed due to what seems to be a bug in determining the proper image dimensions.

<img width="989" alt="screen shot 2016-03-25 at 11 03 07 am" src="https://cloud.githubusercontent.com/assets/1371050/14046958/0916c944-f27b-11e5-8271-be63c95aaa91.png">

**Comment by CyrusSUEN** [comment]
> a bug in determining the proper image dimensions

because of svg file type?

**Comment by yansh** [comment]
Looks like a bug, at least in Chrome: https://productforums.google.com/forum/#!topic/chrome/A9Jlj-avUNM

When you explicitly put ```width=```and ```height=```attribute it works.

**Comment by dhowe** [comment]
I believe I've seen this again. To recreate, import the ads below and view the vault.

The html for the invisible item (with size 1/1) is:
```
<div class="item dup-count-1 visited" data-gid="1114172268" data-width="1" data-height="1" style="position: absolute; left: 5000px; top: 4985px;">
  <div class="ad">
    <span class="counter">1</span>
    <span id="index-counter" class="counter counter-index" style="display: none;">1/1</span>
    <img src="https://ad.doubleclick.net/ad/N7439.1044586DAVIDWALSH.NAME/B7043538.109959721;sz=1x1;ord=1459411507?" onerror="this.onerror=null; this.width=80; this.height=40; this.alt='unable to load image'; this.src='img/placeholder.svg'">
  </div>
</div>
```

[AdNauseam-exported-ads_3-31-2016,_5-23-09_PM.json.zip](https://github.com/dhowe/AdNauseam2/files/197322/AdNauseam-exported-ads_3-31-2016._5-23-09_PM.json.zip)

**Comment by yansh** [comment]
Not on my side
<img width="1043" alt="screen shot 2016-03-31 at 5 54 38 am" src="https://cloud.githubusercontent.com/assets/1371050/14172273/4276766a-f705-11e5-85bf-217069b36c50.png">

**Comment by yansh** [comment]
```
<img src="https://ad.doubleclick.net/ad/N7439.1044586DAVIDWALSH.NAME/B7043538.109959721;sz=1x1;ord=1459411507?" onerror="this.onerror=null; this.width=80; this.height=40; this.alt='unable to load image'; this.src='img/placeholder.svg'">
```

The issue  seems to be with the fact that the image size itself  is just 1 x 1. A possible solution can be introducing a placeholder for images with size below a certain threshold.

**Comment by dhowe** [comment]
I would vote for ignoring ads below a certain size, say max(w,h) > 40 pixels ..

**Comment by yansh** [comment]
By ignoring you mean not to display them on the canvas?

**Comment by dhowe** [comment]
I mean to not consider them as ads at all. We basically ignore (and hope to be able to block outright) tracking code, and I would argue for including 1x1 transparent tracking images in this group...

**Comment by mushon** [comment]
Makes sense to me. But let's keep the threshold lower. I would vote fore ignoring ads smaller than 1000px total (for ex 40x25px).

**Comment by dhowe** [comment]
That threshold is actually higher than mine in most cases (I was suggesting that one side had to be 40 px or more). So 40x25 would be ok, as would 40 x10, but not 30x30.

**Comment by dhowe** [comment]
But the real problem is reliably determining the image dimensions...

**Comment by mushon** [comment]
Well, what I am saying is I agree we should use image size as a threshold (and play with it to decide exactly how big/small should we mark it).

**Comment by dhowe** [comment]
As I say, we generally don't have that information when we detect an ad.

**Comment by mushon** [comment]
so how do you suggest we go about filtering these?

**Comment by yansh** [comment]
How about after the fact, once they are loaded? (Snippet from https://css-tricks.com/forums/topic/conditionally-resize-image-based-on-width/)

```
$(document).ready(function(){
  $('div img').each(function(){
        if($(this).width() > 350){
         $(this).css('width', '100%');
     }
   });
});
```

**Comment by dhowe** [comment]
@yansh do you mean after they are loaded in the vault? or on the original page (we would have to add an event listener to every ad image we find, no?) Jquery/JS width returns 0 when we originally discover the ad.

**Comment by yansh** [comment]
> @yansh do you mean after they are loaded in the vault? 

yes, I thought after they are loaded into the vault. Not ideal, but might work.

> Jquery/JS width returns 0 when we originally discover the ad.

Can you point me to the code?

**Comment by dhowe** [comment]
This will make all the vault counts (and filtering) incorrect or else involve lots of awkward bookkeeping... I think that if its important, we need to figure out a way to do it on detection

Unrelatedly I've been experimenting with attaching 'load' listeners to image objects with dynamically generated src tags...  When they finally load and the listener fires, they have both src and sizes, so this might be a place to consider grabbing that data, but I worry about the performance implications of doing that for all images

Lets put this on hold until we have a solution for grabbing sizes on capture (thus they never make it to the menu or vault)
