### ISSUE TITLE
text-ads on YahooHK are not collected

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#781]
https://hk.search.yahoo.com/search?fr=yfp-search-sb&p=credit+card
![image](https://cloud.githubusercontent.com/assets/3056154/22179710/918f0ad4-e096-11e6-93eb-19c051e29e86.png)

**Comment by dhowe** [comment]
can you also check this on master?

**Comment by cqx931** [comment]
Yahoo has different dom structure for Chinese( yahoo TW and yahoo HK). Some other languages also have their unique dom structures ( Ex: yahoo Japan).
I can first fix the Chinese one, as it is one of our major languages.

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/809/commits/147fc272e35dc8a3cd94d930a164e6a7fea9cf1d fixed
