### ISSUE TITLE
[1.9.16] onBeforeSendHeader is never fired

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#787]
DNT, User Agent, Referrer and Cookies are not modified.

**Comment by cqx931** [comment]
Chrome verified. This is also on Opera, please check.

**Comment by dhowe** [comment]
Looks fine now in Opera as well, though I fixed a few other issues I noticed while looking at it (version #s, etc.)

**Comment by cqx931** [comment]
Verified on Opera

**Comment by cqx931** [comment]
All fixed
