### ISSUE TITLE
Ad targetUrl works in the browser but fails inside ADN (as an XMLHttpRequest)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#79]
http://www.googleadservices.com/pagead/aclk?sa=L&ai=ChGxEBkPxVqubMsOM8AW84q6YA4bRzpdEyKuOl8QC5ZeBCwgAEAFg2QKgAbjM9sgDyAEBqQLE_K9540qxPqoEK0_QCqlAmsC8T9EmMlJtePj3hKgWdzLBXwNkUR_ieD1f14NeyWsFoE92FQqIBgGAB7CziTeQBwOoB6a-G9gHAQ&ohost=www.google.com.hk&cid=CAASIORoGY6sAOOHASVECJjRZ6glqFAYtYgqfPEjNxDQOBW9&sig=AOD64_0_tCb_2Axm6H-UE4iI6QJrDzlUzg&clui=0&q=&ved=0ahUKEwjv2_fnrdTLAhVJJZQKHb49CtMQ0QwIGQ&adurl=http://www.chopard.com/jewellery

Should resolve to: http://www.chopard.com/jewellery?gclid=CKjI9Jmy1MsCFYoDvAodbU8NYw

From page: https://www.google.com.hk/search?q=jewellery&oq=jewe&aqs=chrome.2.69i57j69i65j0l4.1678j0j7&sourceid=chrome&ie=UTF-8

**Comment by dhowe** [comment]
Hit this again with:

http://www.googleadservices.com/pagead/aclk?sa=L&ai=CkTuReoT2VvAYhoT2BfjUlyiOpKzACJ6__-KyAqTPm3kQASDI1vUZYNkCoAHig_XLA8gBA-ACAKgDAcgDmQSqBMIBT9CJWdvnW8yT9uSHUoM4h2W8qBDN63tqZruD2S2kYwf2H0oCbmbEbyZ7R9qdsl0hQ4IyF5X6ahsA14uX7kK8LZ6MAsluvz2QMiMxy2M7DkoFVTcRzlc8sDV9-f3B7d7_sOrmdoUzveStuumZ-APsP7rlEkEb4mxf5VnhWeY0Kj49TDU3MatLMEtNlhvAFmGzQUNKsysf_zj05zkU53g5-F7lARSCGrdzom1uXBw1w0LUjIHS9Ty6nHMN43fwpe2PKe7gBAGIBgGgBgOAB76c5DaoB6a-G9gHAQ&num=1&cid=5GiBauU2D8Lu-09rBq4T55PR&sig=AOD64_2RabRNwE01DMDY_g3bzTzjnux2Hg&client=ca-pub-4177862836555934&adurl=https://onlineonly.christies.com/p/christies-watch-shop-home/15%3Fcid%3DEM_SEM%7CACCOUNT:ChristiesWatchShop%7CCAMPAIGN:MPWatchShopHK%7CADGROUP:TWSWatchesNYTimesFlash%7CENGINE:GOOGLE%7CNETWORK:DISPLAY%7CREGION:HK%7CBANNER:728x90%7CIMG:0444101WatchShopJan16anim728x90%7CKEYWORD:%7CMATCHTYPE:%7CSID:18507

Should resolve to:
https://onlineonly.christies.com/p/christies-watch-shop-home/15?cid=EM_SEM|ACCOUNT:ChristiesWatchShop|CAMPAIGN:MPWatchShopHK|ADGROUP:TWSWatchesNYTimesFlash|ENGINE:GOOGLE|NETWORK:DISPLAY|REGION:HK|BANNER:728x90|IMG:0444101WatchShopJan16anim728x90|KEYWORD:|MATCHTYPE:|SID:18507

**Comment by yansh** [comment]
Can you elaborate? What exactly is the issue?

**Comment by dhowe** [comment]
So the redirect from google (to the actual ad page) is timing out when issued as an XMLHttpRequest. The same request works fine when issued in the browser (click on the googleadservices link above to test) so apparently there is some server side detection only allowing browser requests (the usual means of doing this includes user-agent and other headers, cookies, referrer, etc)

**Comment by dhowe** [comment]
Came across another occasion of this, where the browser eventually resolves, but the XML 


core.js:370 TRYING: Ad#8(img) http://yahoosearch.pgpartner.com/rd.php?r=31570&m=1069045269&q=n&rdgt=14572…id%3D613705%26af%5Fplacement%5Fid%3D1&st=feed&mt=~~~~~~~ysearch_pc_dd~y~~~

core.js:210 Unable to parse title from: <?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> <head> <meta name="referrer" content="origin" /> </head> <body> <noscript> <meta http-equiv="refresh" content="1; url=http://rd.connexity.net/rd?mid=205&amp;cat_id=30020100&amp;atom=10724&amp;p…&amp;rf=afp&amp;vsc=dar&amp;rdrSerial=88e61cc6-354a-4c4c-848a-8f2206db56e4" /> </noscript> <input id="targetUrl" type="hidden" value="http://rd.connexity.net/rd?mid=205&amp;cat_id=30020100&amp;atom=10724&amp;p…&amp;rf=afp&amp;vsc=dar&amp;rdrSerial=88e61cc6-354a-4c4c-848a-8f2206db56e4" /> <script type="text/javascript">
	var url = document.getElementById('targetUrl') ? document.getElementById('targetUrl').value : '';
	document.location.replace(url);
</script> </body> </html>

[URL that fails](http://yahoosearch.pgpartner.com/rd.php?r=29774&m=1070190757&q=n&rdgt=1457251200&it=1458028800&et=1458201600&priceret=25.00&pg=~~2&k=470ac4b8eeeca1861ba8bb713bb025d2&source=feed&url=http%3A%2F%2Frd%2Ebizrate%2Ecom%2Frd%3Ft%3Dhttp%253A%252F%252Flink%2Emercent%2Ecom%252Fredirect%2Eashx%253Fmr%253AmerchantID%253DFOSSIL%2526mr%253AtrackingCode%253DDCD1D7DE%2D3710%2DE511%2D8F84%2DBC305BF82162%2526mr%253AtargetUrl%253Dhttps%253A%252F%252Fwww%2Efossil%2Ecom%252Fus%252Fen%252Fproducts%2Dsku%2DS241015P%2Ehtml%25253fcid%25253dcse%253Aconv%253Ashopzilla%253Aevergreen%253AFossil%2DMen%2DWatches%2DConvertible%253Amale%253AS241015%252526cm%5Fmmc%25253dshpzla%2D%5F%2Dfeed%2D%5F%2Dpdp%2D%5F%2Ddly%2526szredirectid%253DSZ%5FREDIRECT%5FID%26mid%3D422%26cat%5Fid%3D100001539%26atom%3D100001541%26prod%5Fid%3D%26oid%3D4613013995%26pos%3D1%26b%5Fid%3D18%26bid%5Ftype%3D1%26bamt%3Da5fedf14fd8fec0d%26cobrand%3D106%26ppr%3D0daa98596012ce40%26mpid%3DS241015%26brandId%3D256264%26rf%3Dafp%26af%5Fassettype%5Fid%3D12%26af%5Fcreative%5Fid%3D2932%26af%5Fid%3D613705%26af%5Fplacement%5Fid%3D1&st=feed&mt=~~~~~~~ysearch_pc_dd~y~~~)

[Correct URL](http://www.saksfifthavenue.com/main/ProductDetail.jsp?PRODUCT%3C%3Eprd_id=845524446212951&site_refer=CSE_BZR002&prod_id=0445412401654&szredirectid=14602184668760494851110080302008005&CA_6C15C=1925466808) (that the browser eventually finds)

**Comment by dhowe** [comment]
these are now 'ad not visited'
