### ISSUE TITLE
Negative dimensions for Google 'info' image ad

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#790]
Ads still returning negative-dimensions (google-ad from nytimes). Our code to fetch this is:

`var iw = img.naturalWidth || -1, ih = img.naturalHeight || -1`

![screen shot 2017-01-23 at 12 35 14 am](https://cloud.githubusercontent.com/assets/737638/22183940/209c3af4-e104-11e6-8f0f-9f1d16f6605d.png)

IMAGE: <img src="https://googleads.g.doubleclick.net/pagead/images/abg/iconx2-000000.png">

Ad: 
```
 {
  "id": 5,
  "attempts": 1,
  "visitedTs": 1485102788171,
  "attemptedTs": 0,
  "contentData": {
    "src": "https://googleads.g.doubleclick.net/pagead/images/abg/iconx2-000000.png",
    "width": -1,
    "height": -1
  },
  "contentType": "img",
  "title": "googleads.g.doubleclick.net",
  "foundTs": 1485102769517,
  "targetUrl": "https://www.google.com/ads/preferences/whythisad/en-US/HfGv3kaBzCjZKxAp/#/A…CDVRWE4l1ezcwRFqpFM-AEAaAGAoAHr6TuY6gHpr4b2AcB0ggFCIBhEAE&sigh=I9TGj6KZrPg",
  "pageTitle": "https://www.nytimes.com/",
  "pageUrl": "https://www.nytimes.com/",
  "current": true,
  "pageDomain": "nytimes.com",
  "version": "3.1.23",
  "targetDomain": "google.com",
  "targetHostname": "www.google.com",
  "requestId": "1571",
  "resolvedTargetUrl": "https://www.google.com/ads/preferences/whythisad/en-US/HfGv3kaBzCjZKxAp/"
}
```

Page-HTML:

`<div id="Box1" class="ad box1-ad nocontent robots-nocontent" data-google-query-id="COb_i6aY1tECFQ0ZvAodV_0Iww"><div id="google_ads_iframe_/29390238/NYT/homepage/us_12__container__" style="border: 0pt none; display: inline-block; width: 301px; height: 250px;"><iframe frameborder="0" src="https://tpc.googlesyndication.com/safeframe/1-0-5/html/container.html#xpc=sf-gdn-exp-1&amp;p=https%3A//www.nytimes.com" id="google_ads_iframe_/29390238/NYT/homepage/us_12" title="3rd party ad content" name="" scrolling="no" marginwidth="0" marginheight="0" width="301" height="250" data-is-safeframe="true" style="border: 0px; vertical-align: bottom;"></iframe></div></div>`

**Comment by cqx931** [comment]
This particular icon is normally hidden by google, and javascript returns 0 for naturalWidth if an element is invisible.

I have tried to block this image in adnauseam.txt, because it is not a valid ad.
Sometimes I see it get blocked but sometimes not, though the src url looks exactly the same. I didn't figure it out why yet...
https://github.com/dhowe/uAssets/blob/master/filters/adnauseam.txt#L264

**Comment by dhowe** [comment]
We have a rule that an ad must be at least 31 pixels in width or height. So this 30x30 'ad' should be ignored. However, in my tests, the size is -1 x -1 so it is incorrectly collected as an Ad

**Comment by cqx931** [comment]
I see your point... Then this should be the main reason why we are still collecting some tiny icons although we have this 31 pixels rule.
Everything with a "display:none;" attribute doesn't have dimension.
In oder to get the image size of a hidden image, we can change the css to "display:block; visibility:hidden;" temporarily.
However, I am not sure whether we want to collect any potential 'ad' that is already hidden.
Can we ignore the element with "display:none;" attribute? Is there any special case that we don't want that?

**Comment by dhowe** [comment]
Don't all hidden ads get 'display:none'?

**Comment by cqx931** [comment]
A latest catch from the info image, positive width and height
```
{
  "a00c5dfe037138665c4363aaadb0c847": {
    "ed376dbe1ccbc3cff0072adff3c999d6": {
      "id": 1,
      "attempts": 1,
      "visitedTs": 1492314943347,
      "attemptedTs": 0,
      "contentData": {
        "src": "https://googleads.g.doubleclick.net/pagead/images/abg/iconx2-000000.png",
        "width": 30,
        "height": 30
      },
      "contentType": "img",
      "title": "googleads.g.doubleclick.net",
      "resolvedTargetUrl": "https://www.google.com/ads/preferences/whythisad/en-US/F6rgORqAxhmfFRqM/",
      "foundTs": 1492314939664,
      "targetUrl": "https://www.google.com/ads/preferences/whythisad/en-US/F6rgORqAxhmfFRqM/#/AB3afGEAAAHseyJpbWFnZV93aHlfdGhpc19hZCI6eyJsYW5kaW5nX3VybCI6Imh0dHA6Ly93d3cuZXNldC5oay8iLCJpbWFnZV91cmwiOiJodHRwczovL3RwYy5nb29nbGVzeW5kaWNhdGlvbi5jb20vc2ltZ2FkLzEzMjMzNzAzMTM5NTAzMzE5NDM3IiwiaW1hZ2Vfd2lkdGgiOjQ2OCwiaW1hZ2VfaGVpZ2h0Ijo2MH0sInRhcmdldGluZ19yZWFzb25zIjp7ImFkX3JlYXNvbiI6WzIsMTBdLCJ2ZXJ0aWNhbF9pZCI6WyI4MDUzMiJdLCJleHBsYW5hdGlvbiI6eyJpbnRyb2R1Y3Rpb24iOiJUaGlzIGlzIGEgbGlzdCBvZiB0aGUgaW5mb3JtYXRpb24gc291cmNlcyB1c2VkIHRvIGRldGVybWluZSB0aGF0IHRoaXMgYWQgYmUgc2hvd24gdG8geW91OiIsIml0ZW0iOlt7ImRlc2NyaXB0aW9uIjoiVGhlIGluZm9ybWF0aW9uIG9uIHRoZSB3ZWJzaXRlIHlvdSB3ZXJlIHZpZXdpbmcuIn0seyJkZXNjcmlwdGlvbiI6Ik91ciBiZXN0IGVzdGltYXRpb24gb2YgeW91ciBpbnRlcmVzdHMuIn1dfX19dougcb8Q2J5-daVb-XMePsGJmDkJI2HBSXrKVfqRU2AfRQZfOS_ffQyJjidqClm9SIKHQANkpodDbqUumNcgZTjFGuxozo-F5ztYdnymduFUUTDSUmh_Qv2LrM8BIfljx-znVl-w0uvxUkTmFC1li4QvaBj3h6lasRw9o6qFHOM6PGpC88fXDdG_gfo7Gn5nGgIJpkX1RHk-4nFKgHPvgbcbMUq9jsTaVfzmFRfcslbBDo_739JzEoakxEWDK7RHKfUjJ78uGZDtJAqnQXLaQDblcIiA0MZDt8VsnESIp86PnM6CA176x5yPbcgLwmbhgzCucYIe1l_aEO4_zc9aNQ,2miTulpNFclJJ7FL8CgJHA&FtWD3kWU768Ik9S4__kEENXg-fACGNreqyoiC3d3dy5lc2V0LmhrMggIBRMY_7sfFEIXY2EtcHViLTc0MzE4NDQzNzMyODcxOTlIBlgCcAE&https://googleads.g.doubleclick.net/pagead/conversion/?ai=Cp7q2O-vyWIzWE8732ASJ67TIAdCQjNhIk9S4__kEjIuFngsQASD_vvUBYNkCoAHWj9_UA8gBAqkC9mr3OHtEgT6oAwHIA8kEqgSFAU_Qf0RagE1ka0Mb0IQy3NvYBIjfEpRaxEiRDI6ab4bZMsnAbf_YWqFTEYwNg20dqcER6fpBK6rQzNnbTSZqwMqFSsGY_38w3RojPmF05cS9ePpTkHItG-p-jHHAkbCOf0ZNu0pJbd1d6lANm8nT2yM9g93EqRDSahMq6NqcXms-DOMYZ1ygBgKAB5LwoCuoB6a-G9gHAdIIBQiAYRAB2BMD&sigh=P9dim_xH2Sw",
      "pageTitle": "http://www.viewdns.info/",
      "pageUrl": "http://www.viewdns.info/",
      "errors": null,
      "current": true,
      "pageDomain": "viewdns.info",
      "version": "3.0.50",
      "targetDomain": "google.com",
      "targetHostname": "www.google.com",
      "requestId": "15205"
    }
  }
}
```

**Comment by cqx931** [comment]
Please see whether you can find any Google 'info' image collected with negative width and height. I can't reproduce this anymore lately. @greysonevins

**Comment by greysonevins** [comment]
@dhowe @cqx931 I can not reproduce this error. The ads that I have that are similar seem to produce the right dimensions.  (Not a product I am buying anytime soon by the way)
![image](https://cloud.githubusercontent.com/assets/11656811/25775608/ef06ec72-3276-11e7-961b-120efb3a6868.png)

**Comment by dhowe** [comment]
closing for now... lets see if it re-appears
