### ISSUE TITLE
adnauseam.io does not support https?

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#8]
Can someone verify that https://adnauseam.io/ does not load in the browser...

**Comment by CyrusSUEN** [comment]
It does not load in all browsers in my computer at the momemnt.

**Comment by dhowe** [comment]
@mushon how can we fix this?

**Comment by mushon** [comment]
This might be something we need to set with the registrar, as https is supported here: https://dhowe.github.io/AdNauseam/ <https://dhowe.github.io/AdNauseam/>
@dhowe, do you have access t the domain registration?

**Comment by dhowe** [comment]
I believe you did the domain registration for adnauseam.io, no?

**Comment by mushon** [comment]
ok, you’re right.
I just filed a support request with NameCheap.com
Will update.

**Comment by mushon** [comment]
Just updating that I haven't heard back from NameCheap and have just submitted another support ticket. Will continue updating

**Comment by mushon** [comment]
Fixed with great success!
