### ISSUE TITLE
WebExt: chrome.management.getAll() not in API

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#801]
Thus we need to wait until it is or (eventually) come up with a different way to detect conflicting addons

See https://bugzilla.mozilla.org/show_bug.cgi?id=1282981

![screen shot 2017-01-23 at 11 44 13 pm](https://cloud.githubusercontent.com/assets/737638/22210799/f123dcec-e1c5-11e6-89a6-0d3f18576131.png)

**Comment by cqx931** [comment]
duplicate for #1035, close this one.
