### ISSUE TITLE
[1.10.0] Duplicate text on About page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#802]
![screen shot 2017-01-23 at 11 47 00 pm](https://cloud.githubusercontent.com/assets/737638/22210913/4c42a022-e1c6-11e6-991e-7e7aa3cbb514.png)

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/pull/809/commits/96ac34893eca9284c71628dc9080d6a714ed1319
