### ISSUE TITLE
[1.10.0] Info buttons are wrong color on 3p-filters.html

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#803]
![screen shot 2017-01-23 at 11 53 37 pm](https://cloud.githubusercontent.com/assets/737638/22211242/6ac4905e-e1c7-11e6-9008-b386948b60ec.png)

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/pull/809/commits/9763981ed9860af0a17a38f5942767ae2c5ad1a0
