### ISSUE TITLE
Ad not collected: UBS ads on homepage of nytimes.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#804]
Dynamically-generated iframe:

`<iframe width="970" height="250" src="javascript:'';" srcdoc="<!DOCTYPE html><title>ad</title><base href='https://s2.adform.net/Banners/Elements/Files/32050/1324566/bvpath_258/'><script>try{parent.AdformWin3c3s6gg5m0g(window)}catch(ex){new Image().src='https://track.adform.net/jslog/?src=htmlcb&amp;msg='+encodeURIComponent(''+(ex.stack||ex))}</script><script src='https://s2.adform.net/Banners/Elements/Files/32050/1324566/1324566.js?ADFassetID=1324566&amp;bv=258' charset='UTF-8'></script>" allowtransparency="true" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>`

![screen shot 2017-01-24 at 12 46 31 am](https://cloud.githubusercontent.com/assets/737638/22213301/a163e496-e1ce-11e6-94b2-25da82f3d013.png)

**Comment by cqx931** [comment]
This ad belongs to the genre "Dynamically-assembled Ads".
It consists of several images and is animated by js.
![image](https://cloud.githubusercontent.com/assets/3056154/22217573/79cd7054-e1de-11e6-8c45-06340a1dd432.png)

**Comment by cqx931** [comment]
This can also be closed.  For "Dynamically-assembled Ads" please see this ticket: https://github.com/dhowe/AdNauseam/issues/765
