### ISSUE TITLE
Failing Ad Visit 

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#807]
> ADSET #766006463
 {
  "id": 12,
  "attempts": 3,
  "visitedTs": -1485198032942,
  "attemptedTs": 1485198032940,
  "contentData": {
    "src": "https://external.fhkg1-1.fna.fbcdn.net/safe_image.php?d=AQDplZJQhRSVdoGR&w=…155691_6245053495456563200_n.png&cfs=1&upscale=1&_nc_hash=AQDFGkiMAUAigq2h",
    "width": 476,
    "height": 248
  },
  "contentType": "img",
  "title": "Failed",
  "foundTs": 1485198022712,
  "targetUrl": "http://l.facebook.com/l.php?u=http%3A%2F%2Fshoo.ly%2F2jE2mGf%3Fks%3D5106%26…hsqQ1J09wYTRPXcGT4OCwBFK1WV4OGiGW1u7T0Iag2YD44PpxW6BqWmip4mewz_0E2fftj&s=1",
  "pageTitle": "Facebook",
  "pageUrl": "https://www.facebook.com/",
  "current": true,
  "pageDomain": "facebook.com",
  "version": "3.1.24",
  "targetDomain": "facebook.com",
  "targetHostname": "l.facebook.com",
  "requestId": "276687",
  "parsedTargetUrl": "https%3A%2F%2Fwww.nytimes.com%2Fsubscriptions%2Finyt%2Flp8U87X.html%3Fcampaignid%3D6K9UJ&…hsqQ1J09wYTRPXcGT4OCwBFK1WV4OGiGW1u7T0Iag2YD44PpxW6BqWmip4mewz_0E2fftj&s=1",
  "errors": [
    "0 () error",
    "0 () error"
  ]
}

**Comment by dhowe** [comment]
why only 2 errors and 3 attempts?

what happens when clicked manually?

**Comment by cqx931** [comment]
normally the parsedTargetUrl looks like this:
`https://www.facebook.com/relaxitsonlyart/?ref=all_category_pyml_rhc`

but this parsedTargetUrl still has URI component in it.
`https%3A%2F%2Fwww.nytimes.com%2Fsubscriptions%2Finyt%2Flp8U87X.html%3Fcampaignid%3D6K9UJ&…hsqQ1J09wYTRPXcGT4OCwBFK1WV4OGiGW1u7T0Iag2YD44PpxW6BqWmip4mewz_0E2fftj&s=1`

I fixed this issue by adding decodeURIComponent to parsedTargetURL as well. 
https://github.com/dhowe/AdNauseam/pull/809/commits/bf7b5f72383e8c4cf422381738a097e4b111a22b
Below is the url after the first decodeURIComponent. It has two redirect and the first decodeURIComponent was only able to parse till the first one.

> http://l.facebook.com/l.php?u=http://shoo.ly/2jE2mGf?ks=5106&prof=644&cid=117001426&url%5B0%5D=https%3A%2F%2Fwww.nytimes.com%2Fsubscriptions%2Finyt%2Flp8U87X.html%3Fcampaignid%3D6K9UJ&h=ATMq_xrfl7Hz2heJwm7Z6AQdeVcaBHWXJzkLRrvThJBvdcPEeDcq8zCGuSkPUI1zLaf3udqM8Ne5fsiGHDhPJ2s59lW-9WsZ7oRW_U1MGjwuReCNNYRj0L38NJpOIz5UPj2Gd8fic85C&enc=AZNwE9w91GIk6u4TB7obHXusl1pnvu19tl4Ezrvphz26w7pEj4yiF4Du1CXm29UN5Pjg119BYDacb_CamQDntX8N_-sG_h6lsANurdKAHDR6AtiGK4NvIuol8pGYz95kXEHjorCqOXO8qFeqBDjwUMco0Mz6ecTMBCuu3UzzwqfVciGRk96XCEfH6wy_lqu4TE4WTUHuH3OK7HUwSufTp2gx0vLw_M_UnAz7cJZ835mCjIhwm0nsAcvBSif7ZxJSv4CKPJ4Q_yiSmRsxHja9CsEAA30I1wPnH8JhcVgGM0W9t0mzMJxVEXKvvXO4vrmTxv78zSTzAXpJG9Btl81surQYGtnpqGz5T5ZdXRjdUChrRSjalNpiRLfjuo6W2YPZlOiyG4ClwlDooYLKyJIZg51r&s=1




![image](https://cloud.githubusercontent.com/assets/3056154/22234016/b712a0a0-e22f-11e6-96d0-f069bb3f2573.png)
