### ISSUE TITLE
Ad visits bypass onBeforeSendHeaders (was onBeforeRequest)

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#808]
I was testing on cookies, headers and DNT requests.
Most of the ad visit and network activity were working well, but I found these two examples when ad visits bypass onBeforeRequest and headers are not processed at all.

> {
    "216ea6045ac39051b9a1e15c5e33d6fc": {
        "d4a6fe0da86fef240c30b92c8856fb22": {
            "id": 21,
            "attempts": 0,
            "visitedTs": 0,
            "attemptedTs": 0,
            "contentData": {
                "src": "https://tpc.googlesyndication.com/simgad/4969371950868605730",
                "width": 728,
                "height": 90
            },
            "contentType": "img",
            "title": "The Largest Serviced Office Network in Hong Kong &raquo; Compass Offices",
            "foundTs": 1485223715449,
            "targetUrl": "https://www.googleadservices.com/pagead/aclk?sa=L&ai=CXL2II7eGWKfbBILj2AS-1oXAAY-V8IBHqb-y7_wDpM-beRABIMjW9Rlg2QKgAd7f5tcDyAECqQLR4_sAvk2BPuACAKgDAcgDmQSqBLYBT9BPX_JAAwuW7UTX1xcLLOTfiYHHG-5dRRC4bE55wvkwvVLwaeIYxIvm5Z3D-sawJ-xWAT8Orc-IFErdKgpbjynk1XWepLBfIFydTKCihjSuIurFnqBHsHN0G-UnOUh1bqUsVFsxkxQ299pC8M2JHcZbT4XnN1ZRRBYjOJnwXvUkDHU6f8dEpplKP5mUKgtM003Vrms7SW11dLIV8hA4ex8HLKWbzgs7dzY8_yWKNeUvAqf6ebTgBAGIBgGgBgKAB4ynlTmoB6a-G9gHAdIIBQiAYRAB&num=1&cid=CAASEuRokkO1X4HdqRiWnlVGfyuZGA&sig=AOD64_3bxQfgx61vz1M_Qj-jtD2_WDIGOw&client=ca-pub-4177862836555934&adurl=http://www.compassoffices.net/serviced_offices/hk_middle_form/sop1/the-largest-serviced-offices-network-in-hong-kong/",
            "pageTitle": "The New York Times - Breaking News, World News & Multimedia",
            "pageUrl": "https://www.nytimes.com/?WT.z_jog=1&hF=t&vS=undefined",
            "version": "3.1.24"
        },
        "d4a6fe0da42eaf240c30b92c8856fb22": {
            "id": 10,
            "attempts": 0,
            "visitedTs": 0,
            "attemptedTs": 0,
            "contentData": {
                "src": "https://tpc.googlesyndication.com/simgad/12561053898772430828",
                "width": 188,
                "height": 194
            },
            "contentType": "img",
            "title": "One Manhattan Square | Lower East Side Condominium Tower",
            "foundTs": 1485225286907,
            "targetUrl": "http://googleads.g.doubleclick.net/pcs/click?xai=AKAOjst5H401EBUod_A8wgdsKx…e%3DNYTimes.com%26utm_medium%3DBanner%26utm_campaign%3DHomepage%2520Module",
            "pageTitle": "https://www.nytimes.com/",
            "pageUrl": "https://www.nytimes.com/",
            "current": true,
            "pageDomain": "nytimes.com",
            "version": "3.1.24",
            "targetDomain": "doubleclick.net",
            "targetHostname": "googleads.g.doubleclick.net"
        }
    }
}

**Comment by cqx931** [comment]
in chrome://net-internals/, if an ad visit works fine, there should be this section before the request is sent. This happens both to the targetUrl, as well as any redirect resolved later.
![image](https://cloud.githubusercontent.com/assets/3056154/22232769/6bc7af86-e226-11e6-95cc-64c5f04dabdf.png)
But for the above two examples, the section for modifying headers is missing.

**Comment by dhowe** [comment]
very interesting -- i will check it out...

**Comment by dhowe** [comment]
Can you give me a step-by-step on how to recreate?

**Comment by cqx931** [comment]
Just rechecked this and it seems like that only the ad below has this bypass issue.

Steps to reproduce:
1. Activate debugging mode, make sure that dnt options and user-agent option are selected 
1. Import the ad
1. check in background console -network.
  No DNT header is attached and user-agent is not modified.

```
{
"216ea6045ac39051b9a1e15c5e33d6fc": {
"d4a6fe0da42eaf240c30b92c8856fb22": {
"id": 10,
"attempts": 0,
"visitedTs": 0,
"attemptedTs": 0,
"contentData": {
"src": "https://tpc.googlesyndication.com/simgad/12561053898772430828",
"width": 188,
"height": 194
},
"contentType": "img",
"title": "One Manhattan Square | Lower East Side Condominium Tower",
"foundTs": 1485225286907,
"targetUrl": "http://googleads.g.doubleclick.net/pcs/click?xai=AKAOjst5H401EBUod_A8wgdsKx…e%3DNYTimes.com%26utm_medium%3DBanner%26utm_campaign%3DHomepage%2520Module",
"pageTitle": "https://www.nytimes.com/",
"pageUrl": "https://www.nytimes.com/",
"current": true,
"pageDomain": "nytimes.com",
"version": "3.1.24",
"targetDomain": "doubleclick.net",
"targetHostname": "googleads.g.doubleclick.net"
}
}
}
```

**Comment by dhowe** [comment]
Should the title be Ad visits bypass **onBeforeSendHeaders** , as this is where the DNT header is added?

In any case, it seems that onBeforeSendHeaders IS called, however, pageStore.getNetFilteringSwitch() returns false (on line 53 of traffic.js), so the DNT header is never added. 

Why don't you give a try at debugging this (low priority) ...

**Comment by cqx931** [comment]
This is not really a valid issue regarding to ad visit, but could be something to pay attention to for shortened url. 
If an ad is exported through console, the url logged would be shortened with "...".
An ad in this format seems to causing this trouble here which leads to both pageStore.getNetFilteringSwitch() to be false and ad as undefined.  
The ad could not be found because `ads[i].targetUrl ` is not equal to  `url`. The string `ads[i].targetUrl ` from json has '...' in it, while 'url' is in its full format.

**Comment by dhowe** [comment]
Do you mean that if ad data is dumped to the console via the 'd' key ?

**Comment by cqx931** [comment]
yes. Because urls are always shortened when doing console.log

**Comment by dhowe** [comment]
there must be some way to output the full url to the console

**Comment by cqx931** [comment]
http://stackoverflow.com/questions/19184313/disable-url-shortening-formatting-in-chromes-console
If only logging the url, the best way to get the full url is to use `console.dir()` instead of `console.log()` in chrome.
The problem is, if I use console.dir() to log the ad info, the whole ad object in one line, the format would be lost.

**Comment by dhowe** [comment]
what about:
     console.dir(JSON.stringify(Ad, null, '  '));

another option (open in browser-tab):

     location.href="data:text/plain,"+escape(JSON.stringify(obj))‌​;

**Comment by cqx931** [comment]
`location.href = "data:text/plain," +  encodeURI(data);`
solved https://github.com/dhowe/AdNauseam/pull/957
