### ISSUE TITLE
Backup of uBlock export not functioning?

### ISSUE THREAD

**Issue by ZaneHannanAU** [dhowe/AdNauseam#810]
I've been using uBlock Origin for a bit, built up a big filter list. Copying them in is not useful.

Pretty much filter list import/export.

**Comment by dhowe** [comment]
Can you be a bit more specific about the problem? You are trying to import your exported uBlock filter list into AdNauseam?

**Comment by ZaneHannanAU** [comment]
Yes.

Chromium 55.0.2883.87 64 bit, if it helps.

Also useful for initial setup, I guess.

**Comment by cqx931** [comment]
I have just tested it on on Chromium 55.0.2883.95 64 bit with the latest 3.0.50 release. 
I was able to import a filter list with one single blocking rule in it, and request was successfully blocked
Could you please tell us more about your situation?
How many rules are you trying to import? Have you tried to import or copy paste one single rule to test?

**Comment by ZaneHannanAU** [comment]
I was trying to add a backup file and I could not find the button to import everything.

It might be that there's a newer release out and I've gotten an issue.  I'll check tomorrow, but close the thread in the meantime.

**Comment by cqx931** [comment]
There is an "Import and Append" button under "My Filter", same as uBlock.
![image](https://cloud.githubusercontent.com/assets/3056154/22247742/4e37c5e6-e276-11e6-8589-128b2c18ac34.png)

**Comment by ZaneHannanAU** [comment]
I meant the settings tab; in uBo there's a backup & restore function. The buttons were replaced with the backup ads and restore; both don't help me.

The file I'm using is ~40kB from a uBo backup & includes all my settings, personal blocklists and 3rd party lists.

Sorry about the communication error. I should probably have taken a screenshot or similar.

**Comment by dhowe** [comment]
Lets add backup and restore buttons below the import/export/clear ads buttons in settings...

We will need to consider possible conflicts in imported uBlock settings (for example, disable-global-cosmetic-filters)

**Comment by dhowe** [comment]
@cqx931 status?

**Comment by cqx931** [comment]
Please check this ticket: https://github.com/dhowe/AdNauseam/issues/813

**Comment by dhowe** [comment]
closed in favor of #813
