### ISSUE TITLE
[1.10.10] "Update Now" doesn't update adnauseam.txt

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#812]
> I'm not sure we should spend too much time on this until the new assets code is finished, however it is appears to be implemented only in 1.10.5rc1, which we have not yet merged, thus the issues is unrelated...
> 
> Is the network request for adnauseam.txt being made?

**Comment by dhowe** [comment]
Please add this to the release testing...

**Comment by cqx931** [comment]
no, network request for adnauseam.txt is not being made at all.
I have added both manual and auto update to release testing checklist.

**Comment by dhowe** [comment]
![screen shot 2017-01-25 at 12 35 31 pm](https://cloud.githubusercontent.com/assets/737638/22278052/52d28d04-e2fb-11e6-9c80-6d669e69978b.png)

**Comment by cqx931** [comment]
verified that "update now" updates adnauseam.txt, need to modify checksum locally to trigger a remote fetch.
