### ISSUE TITLE
Advanced uBlock Settings no longer enabled by default

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#814]
1.10.0:

![screen shot 2017-01-24 at 11 25 48 pm](https://cloud.githubusercontent.com/assets/737638/22254266/0aea7612-e28f-11e6-9049-b40e22f1ce60.png)

1.9.7.4:

![screen shot 2017-01-24 at 11 45 03 pm](https://cloud.githubusercontent.com/assets/737638/22254322/3a08717e-e28f-11e6-8697-b1a24f28c2e0.png)

**Comment by cqx931** [comment]
Isn't this their new default? The left hand side only shows up when user turns on  "I am an advanced user" in Settings. (which I didn't see in our merge)

**Comment by dhowe** [comment]
yes, but we consider all users who click on the ublock icon to be 'advanced'... thus advanced mode has always been enabled by default

**Comment by dhowe** [comment]
Actually, I think the problem is CSS. It seems that even when the 'advancedUser' class is set on the body in popup.html (and the 'off' class is not present), the advanced interface is not shown.

**Comment by cqx931** [comment]
fixed. DynamicFilteringEnabled need to be set to true by default
https://github.com/dhowe/AdNauseam/pull/817

**Comment by DoMiNeLa10** [comment]
It seems there was a regression, as of now there's no way to get access to uBlock's advanced mode, which makes this extension nearly useless (no way to whitelist certain domains and block others).

**Comment by dhowe** [comment]
@cqx931 can you check this?

**Comment by rgamici** [comment]
I could enable the advanced settings by clicking on "request blocks".
After clicking it once, it persist with the advanced pane always open.
I can set customized options to certain domains.

The only problem is that the layout is slightly broken, and some buttons are not placed correctly.
The button to refresh is also misplaced, but I couldn't capture it.

@DoMiNeLa10 , can you check it?

![Screenshot from 2019-04-13 12-44-25](https://user-images.githubusercontent.com/12600046/56082023-4b22de80-5e03-11e9-830f-4c623b057040.png)

**Comment by DoMiNeLa10** [comment]
@rgamici it seems to work when I click on "requests blocked", thanks!
