### ISSUE TITLE
"Block Element" context menu broken

### ISSUE THREAD

**Issue by toriningen** [dhowe/AdNauseam#820]
Right-clicking on any element and selecting "Block Element" does nothing. It should instead show some dialog similar to Adblock Plus Element Hiding Helper that would allow users to craft selector and preview it.

UA: Firefox 51.0.1
OS: macOS 10.11.5
Version: AdNauseam v3.0.50 Built on uBlock Origin v1.9.7.4

**Comment by KarlisZ** [comment]
In addition to this the uBlock picker mode doesn't seem to work on some sites (e.g. www.diena.lv). The actual version of uBlock works fine so this should be solved by updating the base ublock version for adNauseam.

**Comment by dhowe** [comment]
Verified. This seems to be a problem in uBlock v1.10.0, and will require merging in a newer version -- may take a couple of days...

**Comment by dhowe** [comment]
Please verify on https://github.com/dhowe/AdNauseam/releases/tag/v3.1.32

**Comment by cqx931** [comment]
verified with the current version
