### ISSUE TITLE
Hidden audio and video banners should be silenced

### ISSUE THREAD

**Issue by toriningen** [dhowe/AdNauseam#821]
If page contains autoplaying banners with sound, they have to be silenced, because just hiding them does not work.

Few examples:

1. http://radikal.ru/lfp/s019.radikal.ru/i623/1608/e3/622e5cf04089.jpg/htm
2. http://radikal.ru/lfp/s019.radikal.ru/i610/1701/2c/88b411c8860b.jpg/htm

**Comment by dhowe** [comment]
Its difficult for me to tell what is content and what is Ad here. Can you visit the page with adnauseam 'paused' or disabled, then grab a screenshot, noting what is the content, and what are Ads?
