### ISSUE TITLE
Invalid value for path

### ISSUE THREAD

**Issue by a-komarev** [dhowe/AdNauseam#822]
> Uncaught Error: Invalid value for argument 1. Property 'path': Value does not match any valid type choices.

Chromium Version 48.0.2564.82 Ubuntu 15.04 (64-bit).

Right after install:
![selection_226](https://cloud.githubusercontent.com/assets/1849174/22513813/655f6074-e8ae-11e6-835d-3bd8ae3c1baf.png)

**Comment by dhowe** [comment]
This will be difficult to debug without more information. Where does this error show up, and can you recreate it consistently?  What version of AdNauseam? And does the extension still work afterwards?

**Comment by a-komarev** [comment]
AdNauseam v3.0.5. Extension isn't working. Error shows up consistently. No debug infomation. View in Developer Tools won't work. Stack Trace is empty :(

**Comment by a-komarev** [comment]
Settings are working, but it's not blocking or collection any of ads.

**Comment by a-komarev** [comment]
```
var adlist = exports.adlist = function (pageUrl, currentOnly) {

    var result = [], pages = pageUrl ? [ YaMD5.hashStr(pageUrl) ]
      : Object.keys(admap || µb.userSettings.admap);

    for (var i = 0; i < pages.length; i++) {

      if (admap[pages[i]]) {

        var hashes = Object.keys(admap[pages[i]]);

        for (var j = 0; j < hashes.length; j++) {

          var ad = admap[pages[i]][hashes[j]];

          // ignore text-ads according to parseTextAds prefe
          if (ad && (µb.userSettings.parseTextAds || ad.contentType !== 'text')) {

            if (!currentOnly || ad.current) {
              result.push(ad);
            }
          }
        }
      }
    }

    return result;
  };
```

Error is here: `if (admap[pages[i]]) {`

**Comment by dhowe** [comment]
It appears, though I can't say for sure, that you somehow have a corrupt admap in your local storage... I'd love to get a stacktrace if possible. Can you go to settings, and click the 'activate debugging' toggle at the very bottom of the page, then see if you can recreate the error?

If this isn't possible, can you try a new Chromium profile (Settings->Add-Person...)?

Thanks much

**Comment by a-komarev** [comment]
@dhowe I did not created person in chromium, ever :D Will try to get more info tomorrow.

**Comment by a-komarev** [comment]
There is only one additional error I can see in stack trace before the previous one:
![selection_229](https://cloud.githubusercontent.com/assets/1849174/22605025/372a4af4-ea5f-11e6-9e69-bd90ffe8b53e.png)

**Comment by dhowe** [comment]
The 2nd error ([here](https://github.com/dhowe/AdNauseam/issues/835) you mention should not affect the first. Let me know if creating a new 'person' solves the first problem above...

**Comment by dhowe** [comment]
Tracing this a bit more, it _seems_ that it has to do with the sizes of the icon specified in the chrome manifest (what a terrible error message)... However the icon-sizes specified (19 & 38) are correct according to the chromium spec., so I'm not sure what is causing the problem. Another thing to try is to uninstall and reinstall the extension and see if if the error recurs.
