### ISSUE TITLE
Guys! Please make it for Edge!

### ISSUE THREAD

**Issue by alvipeo** [dhowe/AdNauseam#823]
I'd use it, probably lots of people too.

**Comment by dhowe** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/

**Comment by cqx931** [comment]
The repo is here: https://github.com/nikrolls/uBlock-Edge#edge

**Comment by dhowe** [comment]
Dup: https://github.com/dhowe/AdNauseam/issues/725
