### ISSUE TITLE
Ads not detected on tripadvisor.com (dynamic)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#827]
from: zhivenkoff@gmail.com

> plugin cannot detect google ads on tripadvisor.com

**Comment by cqx931** [comment]
I can't see any visual ad when I browse around tripadvisor.com, what does detect mean? Ads not hidden or not collected?

**Comment by dhowe** [comment]
That was the title of the email bug report... However, I also cannot reproduce any longer, though I was able to earlier. Closing for now.
