### ISSUE TITLE
Ads visible on http://finance.ua

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#828]
From: vladimir.brodovy@macom.com
> It seems that AdNauseam completely fails to block ads on http://finance.ua/. AdBlock blocks 11 ads while AdNauseam. Changing of “Don't hide non-tracking Ads” option does not help too.

**Comment by dhowe** [comment]
please check

**Comment by cqx931** [comment]
I don't see any visible ads when I check the page, though some of the ads are not rendered if the outer div is hidden.

**Comment by dhowe** [comment]
ok
