### ISSUE TITLE
It is only google and facebook ads are clicked?

### ISSUE THREAD

**Issue by SeanSilke** [dhowe/AdNauseam#829]
It seems that only google and facebook and are clicked and saved in vault, and visible on addon's  #favicon counter. Is it true?
For example add are successfully blocked on https://habrahabr.ru/ but there is zero on counter and nothing add to vault.

**Comment by dhowe** [comment]
No,  all collected ads are clicked (assuming clicking is enabled). When I visit the link above, I see one ad collected (visible in the menu) and successfully clicked as shown below. If there are other ads not detected, please include a screenshot with the ad marked on the page (you can click 'pause adnauseam' in the menu' to temporarily disable it for the screenshot)

![screen shot 2017-02-03 at 7 50 03 pm](https://cloud.githubusercontent.com/assets/737638/22590405/fc2702c2-ea49-11e6-9c2c-5a5cb41adc1e.png)

**Comment by SeanSilke** [comment]
Yes i see. Some add are collected and clicked. 
But not all. Major part is only become hidden.
<img width="1507" alt="screenshot at feb 03 15-06-48" src="https://cloud.githubusercontent.com/assets/1077074/22590911/d0573eae-ea22-11e6-8348-978aa9510439.png">
<img width="1461" alt="screenshot at feb 03 15-07-29" src="https://cloud.githubusercontent.com/assets/1077074/22590931/f2308c4c-ea22-11e6-8f16-6612e4d73548.png">
There is fixed vertical block on right with five add. And they are huge.

**Comment by SeanSilke** [comment]
Here is filter for uBlock " ||an.yandex.ru^ "

**Comment by dhowe** [comment]
The rule above is a blocking filter, which will not allow us to capture the Ad. We need to create a new filter to parse the text Ad. Follow https://github.com/dhowe/AdNauseam/issues/830 for progress...
