### ISSUE TITLE
Text-ad filters for https://habrahabr.ru/

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#830]
![Image](https://cloud.githubusercontent.com/assets/1077074/22590911/d0573eae-ea22-11e6-8348-978aa9510439.png)

**Comment by cqx931** [comment]
`||an.yandex.ru^` this rule in easyPrivacy will block the ads above, if we want to collect them. We need to first add `@@||an.yandex.ru$domain=habrahabr.ru` to adnauseam.txt

**Comment by cqx931** [comment]
after unblocking the ads from easyPrivacy, ads are hidden if I turn on Russian specific filters. Shall I still hide them in adnauseam.txt?
![image](https://cloud.githubusercontent.com/assets/3056154/22686724/3469e910-ed60-11e6-8918-04b0b1054676.png)

**Comment by dhowe** [comment]
nope, thats fine
