### ISSUE TITLE
Collect iFrame Ad

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#833]
http://radikal.ru/lfp/s019.radikal.ru/i623/1608/e3/622e5cf04089.jpg/htm

iFrames 3-levels deep:

![screen shot 2017-02-04 at 3 36 41 pm](https://cloud.githubusercontent.com/assets/737638/22616808/e9223fb0-eaef-11e6-8c81-9f298f62efd1.png)

**Comment by cqx931** [comment]
With the latest release, I can't see any ad on the page, is it already fixed?
![image](https://cloud.githubusercontent.com/assets/3056154/22685372/0f058bf2-ed5b-11e6-8296-6e88872905a9.png)

**Comment by dhowe** [comment]
Ads are hidden but not collected

**Comment by cqx931** [comment]
I can't reproduce this. When I browse the website without any blocker, I can't see any ad.
