### ISSUE TITLE
Consider $important for blocking rules in adnauseam.txt

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#834]
see [this](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#important) and adnauseam.txt's rule:
```

 # radikal.ru (video)
||laim.tv^$important,third-party

```
then lets discuss

**Comment by dhowe** [comment]
and this?

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/issues/847 could be a case that argues for adding $important to blocking rules. Any other details to discuss here?

**Comment by cqx931** [comment]
> Any downside?


> I don't see any downside for now. If there are some blocking rules in adnauseam.txt but have more specific exception rules in other lists, they will still be blocked. And if we want those unblocking to be triggered, it means that the rule itself need to be written more specifically, not the problem with $important.

**Comment by dhowe** [comment]
@cqx931 pls add to each rule, test, and then close

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/uAssets/pull/36
