### ISSUE TITLE
Check/validate tests here 

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#836]
https://pbtest.org/

specifically: 
- Honor the Cookie Block List
- Replace Social Widgets (with appropriate lists selected)
- Block subdomains of blocked domains (?)

**Comment by cqx931** [comment]
![screen shot 2017-02-09 at 2 47 45 pm](https://cloud.githubusercontent.com/assets/3056154/22772289/c07e4b18-eed6-11e6-97f1-b0d299b04cd7.png)

**Block subdomains of blocked domains**

This one means request from subdomains, such as "https://sub.eviltrack.net/no-tracking-tally?&random=" should also be blocked.

Though adnauseam has passed the second test, it actually didn't block the request from eviltracker.(Might not be related to inline-script, it blocks the request when the type is iframe)

**Canvas Tracker**
a canvas src equal to https://canvastrackersimulator.org/canvas-track?&random=  

**localstorage_status**  
https://localstoragetrackersimulator.org/localstorage-track?&random=489513

**etldp1**(not sure for now)
https://trackersimulator.duckdns.org/tracking-tally?&random=489513

**social status** 
If it can find an element with the class name: privacyBadgerReplacementButton, the result is yes.
