### ISSUE TITLE
Check trailing slash on message urls

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#837]
Please check this line: https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L2013
I remember you removing it ?

**Comment by cqx931** [comment]
not this line. The one that I commented out is this: https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L627

**Comment by dhowe** [comment]
thanks (though isn't someone is supposed to be on holiday?)
