### ISSUE TITLE
Invalid rules in adnauseam.txt

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#838]
`haaretz.co.il##[id^="dclk"]`

does this need an element type or * ?

**Comment by cqx931** [comment]
yes, I think it should be `haaretz.co.il##*[id^="dclk"]`
Though when I go back to [the page](http://www.haaretz.co.il/opinions/editorial-articles/1.3030617) that these rules are supposed to work on and recheck the ublcok logger, none of the following rules are actually fired, and the ad pops up is still there( maybe the webpage has changed)

> haaretz.co.il##.modal-wrapper--dark.modal-wrapper--fixed.modal-wrapper > .modal--subscription-weekly.modal--subscription.modal
haaretz.co.il###top_banners
haaretz.co.il##*[id^="dclk"]

to block the ad popup, I suggest to delete the old rules and add a new one:
haaretz.co.il###maavaronWrapper
