### ISSUE TITLE
Hidden facebook content

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#839]
https://www.facebook.com/timothy.david.snyder/posts/1206636702716110

Compare to uBlock:

![screen shot 2017-02-05 at 7 35 51 pm](https://cloud.githubusercontent.com/assets/737638/22625841/557e04ce-ebda-11e6-88ea-0a743f5c1da2.png)

**Comment by dhowe** [comment]
should be fixed, but please verify...

**Comment by cqx931** [comment]
how do you see that pop up page? (log in or create an account)
for now if I go to the page(no pop up), the content is not hidden. https://www.facebook.com/timothy.david.snyder/posts/1206636702716110

**Comment by dhowe** [comment]
if you are not logged in, and you disable our hiding rules, you will see it... 
But as long as the content is there, lets consider it verified
