### ISSUE TITLE
Badge tab id errors

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#840]
```
Unchecked runtime.lastError while running browserAction.setBadgeText: No tab with id: 295.
    at Object.onIconReady [as callback] (chrome-extension://bgfakkfcmbdaaeifhgdfeodkafhklfef/js/vapi-background.js:624:30)

Unchecked runtime.lastError while running browserAction.setBadgeBackgroundColor: No tab with id: 295.
    at Object.onIconReady [as callback] (chrome-extension://bgfakkfcmbdaaeifhgdfeodkafhklfef/js/vapi-background.js:626:34)
```

this may be a dup of a non-issue occurring when the console is open, not sure...

**Comment by cqx931** [comment]
This case seems like that the returned current tab id does not exist any more when setBadgeText/setBadgeBackgroundColor runs.
It is not the same issue when the console is open and the focus is there. For that case, no tab id will be returned.

When do you see this error?

**Comment by dhowe** [comment]
Just found in the console... will try to recreate

**Comment by dhowe** [comment]
close for now
