### ISSUE TITLE
Missing FAQ entries for 'Activate the AdNauseam/EasyList Filters' Notifications

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#841]
Recreate: deactivate AdNauseam or EasyList filter, click '?' icon on notification

Two parts:
- [x] Write these FAQs ( @dhowe ) - done
- [x] Check all '?' icons in interface for correct/specific links ( @cqx931, please create a new ticket for whatever links are still missing)

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/issues/843
