### ISSUE TITLE
[Firefox] Cookies are not blocked, both for ad visits and normal requests

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#846]
Web Request(Cookie Test)
http://lab-lamp.scm.cityu.edu.hk/adntest/incomingCookies.html
Ad Visit:
http://lab-lamp.scm.cityu.edu.hk/adntest/cookie-setting-ad.html

**Comment by dhowe** [comment]
please re-test with 'ffcookies' branch

**Comment by dhowe** [comment]
I've written this spec to include all of our cookie-handling (for the DevFAQ).
Can you verify that our release tests cover ALL the cases below (except the last):

Incoming  -> vapi-background.js::handleResponseHeaders() -> traffic.js::onHeadersReceived()
-----------------------------------------------------------------------------

Ad-visits:
-----------
if (a response to an ad-visit)
  block cookies


All-requests
-----------
if (in our allowedException list and not an enabled DNT entry) 
  block cookies  // remove set-cookie/set-cookie2 headers



Outgoing  -> vapi-background.js::handleRequestHeaders() -> traffic.js::onBeforeSendHeaders()
-----------------------------------------------------------------------------

Ad-visits:
-----------

  if (noOutgoingCookies) 
    block cookies  // remove set-cookie/set-cookie2 headers

  if (noOutgoingReferer)
    remove referrer header // replace with most-common

  if (noOutgoingUserAgent)
    obfuscate user-agent header // replace with most-common



All-requests (unimplemented)
-----------

  if (in our allowedException list and not an enabled DNT entry) {
    block cookies  	   // remove set-cookie/set-cookie2 headers
    remove referrer header   // replace with most-common
    obfuscate user-agent header // replace with most-common
  }

**Comment by cqx931** [comment]
verified. All the cases except the last one are covered in release testing.

**Comment by cqx931** [comment]
I see that nothing is in vAPI.net.onHeadersReceived for firefox. Therefore, no information about responseHeaders is returned. Is it on hold for web-extensions?

**Comment by dhowe** [comment]
@cqx931 Am I correct that this ticket only applies to incoming cookies?
If so, then please add the spec above to the DevFAQ ...

**Comment by cqx931** [comment]
Yes this ticket only applies to incoming cookies.
But I think I wrongly categorized incoming-cookies from ad-visit to "outgoing" yesterday.
So the 'ffcook2' branch didn't pass this test on firefox:
http://lab-lamp.scm.cityu.edu.hk/adntest/cookie-setting-ad.html
