### ISSUE TITLE
Reactive button in lists doesn't reactive the list in the background

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#850]
To recreate:
1.disable easylist -> apply changes
2.reactive the list through reactive button in notification.
3.go to nytimes.com, ad parsing/hiding seem to not working anymore because easylist is still disabled
4.Refresh the background console (third party filters are reloaded) -> ad parsing/hiding works again.

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/shared.js#L327
ReactivateList doesn't "apply changes".

**Comment by dhowe** [comment]
is this the reason for #793?

**Comment by cqx931** [comment]
yes

**Comment by dhowe** [comment]
excellent

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/pull/851
