### ISSUE TITLE
"BLOCK MALICIOUS ADS" blocks Google Analytics

### ISSUE THREAD

**Issue by aminco** [dhowe/AdNauseam#855]
On Chrome/Windows 7, I notice that AdNauseam's "BLOCK MALICIOUS ADS" feature blocks Google Analytics.

Could this be why Chrome excluded Ad Nauseam from the store? Is Analytics the innocent victim here? On the other hand, if Google Analytics indeed behaves in a "malicious way", this could make headlines.

**Comment by dhowe** [comment]
Google Analytics _is_ likely to be blocked, however not by AdNauseam specifically, but rather by the crowd-sourced EasyPrivacy list, which users may choose to enable or disable in the 3rd-party filters tab in settings. This same list is included by default in uBlock.

However, I would question the assertion that analytics is 'the victim' here, or that it is at all 'innocent'. Google Analytics has been widely recognized as one of the most pervasive tracking architectures on the web. [This article](https://null-byte.wonderhowto.com/how-to/youre-being-tracked-google-inc-spies-your-every-digital-move-0170415/) gives some sense of the scope of Google tracking... Just analytics itself is estimated to be present on 30-50 million websites ([source](http://www.visualcapitalist.com/how-google-tracks-you/))

**Comment by mushon** [comment]
(Hi)
The blocking of Google Analytics is actually handled by the Easy Privacy filter list and can be set on/off in the AdNauseam settings. This is a feature we inherited from the uBlock blocker that we use as the base technology for AdNauseam.
As for the reason for removal from the web store, this is an interesting assumption, but we have no way of really knowing as Google gave us very little details. We have no way of even testing whether that was the reason, but as I mentioned, this is not our block, and if that would have been the real reason for the removal, uBlock and other blockers would have been suffering from it as well.

Let me know if this answers your question.
Thanks!

**Comment by aminco** [comment]
I assumed so.
Basically, what I was saying is that if you filter Google Analytics to
"off" in the next release perhaps the Chrome store will have a second
thought about blocking *you*.

**Comment by nukeop** [comment]
But Google Analytics is a malicious spying network that cooperates withAmerican government, so that's the correct behaviour.

**Comment by aminco** [comment]
Well, in that case we should embrace the exclusion from the malicious
spying network's play store.

**Comment by nukeop** [comment]
They block anything they like, that's the nature of walled gardens. They'd be blocking adnauseam anyway, because it endangers their business (Google is an advertising company first and foremost). This only means that they're afraid of it, giving people like me more reasons to use it.

**Comment by mushon** [comment]
A. Happy to see Zizek responding to Github issues, even if only under pseudonym.
B. Yes, Google might have used this as an excuse to bring up their dubious "single purpose" rule.
C. Not sure there's much we can do about it, but we will be looking into it.
D. Thanks @nukeop, we love you too.
