### ISSUE TITLE
MouseOver and Link (to FAQ) for AdNauseam icon on Menu

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#857]
Also add FAQ link to 'about' page 

And possible some basic information about the project/tool, we have so much space on this page? With a 'Learn More' link at the bottom ? @mushon?

The basic problem this ticket is addressing is that people are not having an easy time getting their questions about the project answered

**Comment by cqx931** [comment]
- [ ] Fixed the link for AdNauseam Icon on Menu

- [ ] Added FAQ Link to 'about' page

The link for adnauseam Icon on Menu was originally linked to press page. Why do we want it link to FAQ?

**Comment by dhowe** [comment]
@mushon?

**Comment by mushon** [comment]
ShouldHow about adding the [?] button to the footer like this:
![popup-new-footer](https://cloud.githubusercontent.com/assets/27123/23798249/6b234a46-05ac-11e7-9d81-201c21e32a90.png)

**Comment by dhowe** [comment]
good for me

**Comment by mushon** [comment]
added in https://github.com/dhowe/AdNauseam/commit/ffd5ca016ecaef3a8c34cfa3b15908ac6fe19b3e please hook in the link

**Comment by dhowe** [comment]
@cqx931 please check

**Comment by cqx931** [comment]
What is the link supposed to be? to [FAQ](https://github.com/dhowe/AdNauseam/wiki/FAQ)?

**Comment by mushon** [comment]
yeap

**Comment by cqx931** [comment]
Link added. Close
