### ISSUE TITLE
Invalid rules in adnauseam.txt

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#859]
- rules starting with http://
- tracking rules not in the tracking section
- commented facebook rules ?

**Comment by cqx931** [comment]
https://github.com/dhowe/uAssets/pull/30
Still need to check facebook rules more in details.

**Comment by cqx931** [comment]
`facebook.com##div[id*="pagelet_ego_pane"]`
`facebook.com##div[class*="ego_unit_container"]`
The above two rules are a bit problematic. Every sub group inside pagelet_ego_pane is inside ego_unit_container. They could be suggested groups, suggested page, but sometimes friend requests/people you may know also appear in that column. Then it is quite strange to collect user profile pics...

![image](https://cloud.githubusercontent.com/assets/3056154/23393179/04ae8c78-fdbc-11e6-8b7d-7057ee75174c.png)

I have replaced the above rules with `facebook.com##.ego_unit:has(div.uiScaledImageContainer)`, which won't block ego_unit that has user profiles in it. 

![image](https://cloud.githubusercontent.com/assets/3056154/23393832/80d69206-fdc0-11e6-99de-1c2c782c0232.png)

**Comment by cqx931** [comment]
What is this rule supposed to do? I didn't see it get fired when I browse Facebook.
`facebook.com##DIV[id^="substream_"] ._5jmm[data-dedupekey][data-cursor][data-xt][data-xt-vimpr="1"][data-ftr="1"][data-fte="1"]`

**Comment by dhowe** [comment]
Not sure -- perhaps Leon added that?
Lets make sure we are still blocking the login nag (a popover that shows when you are not logged in)

**Comment by cqx931** [comment]
Bring back the rule blocking the login nag. 
https://github.com/dhowe/uAssets/pull/34

**Comment by cqx931** [comment]
Close for now
