### ISSUE TITLE
Header comparison for Ad visits

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#862]
Please record the headers sent for a AdNauseam visit in Chrome, then compare these, side-by-side to the same request made manually. Make sure to start with a fresh browser profile for each. 

Note: this should be repeated from time-to-time for all browsers, so please note steps in DevFAQ...

**Comment by cqx931** [comment]
ADNAUSEAM

REQUEST_HEADERS
                        --> :authority: googleads.g.doubleclick.net
                            :method: GET
                            :path: /pcs/click?xai=AKAOjsvWzz2MAUdJT9KjUN64UYMBb6lwgB-YenN1nwZAjjGwPPeq4VaGfVvp0HTWeb6umUVrpRpsGc0gkN0aIyxZVFH4h31FyCFIS_VTAUo7hp4v_wh6sGCTLBhIH7lW4JkqVrg1RA8TEjTLngl4Xeh3mH6lna_R9yE_RZ_i1PpQUT2A48-LDNp1dQQQ_B5LxKdoZKlLbVEQnEBY18TsbHiQru8Bs-t-nPeaUzXpNxBFJfOP&sig=Cg0ArKJSzCyacq__fOdp&adurl=https://www.nytimes.com/subscriptions/inyt/lp87JWF.html%3FcampaignId%3D64LFL
                            :scheme: https
                            accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
                            accept-encoding: gzip, deflate, sdch, br
                            accept-language: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4
                            dnt: 1
                            upgrade-insecure-requests: 1
                            user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.85 Safari/537.36
                            x-client-data: CIu2yQEIpLbJAQjEtskBCKSKygEI+5zKAQipncoB

RESPONSE_HEADERS
                        --> HTTP/1.1 302
                            status: 302
                            p3p: policyref="https://googleads.g.doubleclick.net/pagead/gcn_p3p_.xml", CP="CURa ADMa DEVa TAIo PSAo PSDo OUR IND UNI PUR INT DEM STA PRE COM NAV OTC NOI DSP COR"
                            timing-allow-origin: *
                            cache-control: private
                            location: https://www.nytimes.com/subscriptions/inyt/lp87JWF.html?campaignId=64LFL
                            content-type: text/html; charset=UTF-8
                            x-content-type-options: nosniff
                            date: Thu, 16 Feb 2017 04:35:25 GMT
                            server: cafe
                            content-length: 0
                            x-xss-protection: 1; mode=block
                            set-cookie: [142 bytes were stripped]
                            set-cookie: [144 bytes were stripped]
                            alt-svc: quic=":443"; ma=2592000; v="35,34"
t=23300 [st=113]     -HTTP_TRANSACTION_READ_HEADERS

NO BLOCKER

REQUEST_HEADERS
                       --> :authority: googleads.g.doubleclick.net
                           :method: GET
                           :path: /pcs/click?xai=AKAOjsvWzz2MAUdJT9KjUN64UYMBb6lwgB-YenN1nwZAjjGwPPeq4VaGfVvp0HTWeb6umUVrpRpsGc0gkN0aIyxZVFH4h31FyCFIS_VTAUo7hp4v_wh6sGCTLBhIH7lW4JkqVrg1RA8TEjTLngl4Xeh3mH6lna_R9yE_RZ_i1PpQUT2A48-LDNp1dQQQ_B5LxKdoZKlLbVEQnEBY18TsbHiQru8Bs-t-nPeaUzXpNxBFJfOP&sig=Cg0ArKJSzCyacq__fOdp&adurl=https://www.nytimes.com/subscriptions/inyt/lp87JWF.html%3FcampaignId%3D64LFL
                           :scheme: https
                           accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
                           accept-encoding: gzip, deflate, sdch, br
                           accept-language: en-US,en;q=0.8
                           upgrade-insecure-requests: 1
                           user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

                           x-client-data: CIu2yQEIpLbJAQjEtskBCKSKygEI+5zKAQipncoB

RESPONSE_HEADERS
                       --> HTTP/1.1 302
                           status: 302
                           p3p: policyref="https://googleads.g.doubleclick.net/pagead/gcn_p3p_.xml", CP="CURa ADMa DEVa TAIo PSAo PSDo OUR IND UNI PUR INT DEM STA PRE COM NAV OTC NOI DSP COR"
                           timing-allow-origin: *
                           cache-control: private
                           location: https://www.nytimes.com/subscriptions/inyt/lp87JWF.html?campaignId=64LFL
                           content-type: text/html; charset=UTF-8
                           x-content-type-options: nosniff
                           date: Thu, 16 Feb 2017 04:39:33 GMT
                           server: cafe
                           content-length: 0
                           x-xss-protection: 1; mode=block
                           set-cookie: [142 bytes were stripped]
                           set-cookie: [144 bytes were stripped]

                           alt-svc: quic=":443"; ma=2592000; v="35,34"

**Comment by cqx931** [comment]
`Without AdNauseam
                       --> :authority: www.google.com.hk
                           :method: GET
                           :path: /aclk?sa=l&ai=DChcSEwiy_ty3lpTSAhVNcLwKHRuEAwkYABAA&sig=AOD64_0UdAtBqoBbaUZOb9GTarFPYfqFzg&q=&ved=0ahUKEwj6jNq3lpTSAhWInJQKHT4nAVMQ0QwIGA&adurl=
                           :scheme: https
                           accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
                           accept-encoding: gzip, deflate, sdch, br
                           accept-language: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4
                           cookie: [171 bytes were stripped]
                           referer: https://www.google.com.hk/
                           upgrade-insecure-requests: 1
                           user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
                           x-client-data: CIu2yQEIpLbJAQjEtskBCKSKygEI+5zKAQipncoB
With AdNauseam
                         --> :authority: www.google.com.hk
                            :method: GET
                            :path: /aclk?sa=l&ai=DChcSEwiMv-eMlZTSAhWGlbwKHUIaDkMYABAA&sig=AOD64_2eaL4aBhgq6_q2yoi-aJdofnjBtQ&q=&ved=0ahUKEwjF7-SMlZTSAhWMNpQKHarvDT4Q0QwIGA&adurl=
                            :scheme: https
                            accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
                            accept-encoding: gzip, deflate, sdch, br
                            accept-language: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4
                            cookie: [171 bytes were stripped]
                            referer: https://www.google.com.hk/search?q=credit+card&oq=credit+card&aqs=chrome..69i57j69i65l2j0l3.1919j0j8&sourceid=chrome&ie=UTF-8
                            upgrade-insecure-requests: 1
                            user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
                            x-client-data: CIu2yQEIpLbJAQjEtskBCKSKygEI+5zKAQipncoB`
