### ISSUE TITLE
Legit js file blocked

### ISSUE THREAD

**Issue by thefallman** [dhowe/AdNauseam#864]
Nice try folks, but why should javascript file named loggingService.js be blocked? Logging web page errors is normal business process for online app.
It happens in Chrome only though, so I believe the rules are different for that guy and other browser.

**Comment by ZaneHannanAU** [comment]
EasyPrivacy.

Here's a script to find the indecies:

```javascript
var k = []
document.documentElement.innerText
	.split(/\n\r?/)
	.filter(e=>!!e)
	.forEach((e, i) => /logging-?service/i.test(e) ? k.push({
		tested: e,
		index: i
	}) : false)
console.table(k)
```
|(index)|tested|index|
|-:|:-|-:|
|0|`"/loggingService.js"`|1557|
|1|`"/PlayerDashboardLoggingService.svc/json/StartSession?"`|1921|
|2|`"||loggingservices.tribune.com\^"`|9489|
|3|`"@@||cbc.ca^*/loggingservice.js?"`|11707|
|4|`"@@||latimes.com/hive/javascripts/loggingService.js"`|11923|
|5|`"@@||virtualearth.net/webservices/v1/LoggingService/$script"`|12218|
|6|`"@@||virtualearth.net^*/LoggingService.svc/Log?$script,domain=bing.com|spatialbuzz.com"`|12219|

**Comment by dhowe** [comment]
Correct, thanks @ZaneHannanAU . You can disable EasyPrivacy altogether (in the 3rd-party filters tab), or, better still, add an exception for loggingService.js in the 'My Filters' tab.

**Comment by thefallman** [comment]
Well, Zane, ahowe, thanks a lot! I, myself, can definitely do the stuff. However it's hard to imagine how exactly our Customer service guys could explain that to regular web site user having your excellent (and I mean it, it's really cool!) tool installed. It just won't work. By the way sacrificing EasyPrivacy is not an option too, I'd guess.

**Comment by ZaneHannanAU** [comment]
If it can't be explained by any of

```javascript
console.log(e)
console.info(e)
console.error(e)
```
then you probably don't need it.
