### ISSUE TITLE
Disappearing background image on bing.com

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#865]
![image](https://cloud.githubusercontent.com/assets/3056154/23054667/4ac0c698-f51c-11e6-913c-1d3300b83902.png)

This rule in adnauseam.txt is blocking the big background image in bing.com homepage
www.bing.com/rms/BingCore.Bundle/jc,nj/3de0ddf1/0a84f106.js
`||www.bing.com/rms/bingcore.bundle/jc,nj/3de0ddf1/$script,domain=www.bing.com`

related to bing ad blocking from us server in this ticket:
https://github.com/dhowe/AdNauseam/issues/578

**Comment by cqx931** [comment]
I can still block bing text ad without blocking the background image in homepage if I use this rule
`http://www.bing.com/rms/rms%20answers%20Identity%20SnrWindowsLiveConnectBootstrap/jc,nj/bf587ad6/f1d86b5a.js`

Though I still don't really get why this could add"visibility: visible !important;display:block!important;" 
As nothing more is triggered from enable this script.
```
(function(n, t, i) {
    if (t) {
        var r = !1
          , f = function() {
            r || (r = !0,
            typeof wlc != "undefined" && wlc(sj_evt, sj_cook.set, wlc_t))
        }
          , u = function() {
            setTimeout(f, t)
        };
        n.bind("onP1", function() {
            i ? n.bind("aad:signedout", u) : u()
        }, 1)
    }
})(sj_evt, wlc_d, wlc_wfa)
```

**Comment by dhowe** [comment]
I'm not sure I understand the issue.

**Comment by cqx931** [comment]
The issue was originally disappearing background image from bing.com caused by `||www.bing.com/rms/bingcore.bundle/jc,nj/3de0ddf1/$script,domain=www.bing.com`, which was originally intentioned to block visible text ads from bing search result.(which could be reproduced if visiting the sites from a server in the states.)

I could solve this by replacing the blocking rule with another one( this one is fired after the script above)
`http://www.bing.com/rms/rms%20answers%20Identity%20SnrWindowsLiveConnectBootstrap/jc,nj/bf587ad6/f1d86b5a.js`, but I was just wondering why this script could change the webpage.

The text ad was not blocked because inline-css "visibility: visible !important;display:block!important;" are added to ads divs.
But what the script (87ad6/f1d86b5a.js) does (see code snippet above) is just connecting to bootstrap, and no further script is triggered from this script aftwards...

**Comment by dhowe** [comment]
first, why are we blocking bing text-ads?
second, the script appears to call u(), which calls f(), which calls wlc()
so what does wlc do?

**Comment by cqx931** [comment]
We are not blocking bing text-ads, we are hiding them as we usually do.
The blocking script was meant to block the script that set the ads to visible:visibility!important;display:block!important after we set hide the ad.

**Comment by dhowe** [comment]
I see. So are we OK with simply changing the blocked script URL, or do we need more investigation into this?

**Comment by cqx931** [comment]
The problem itself can be simply solved by changing the blocked script URL (done for now), I was just curious about what exactly is happening here.

**Comment by cqx931** [comment]
close for now
