### ISSUE TITLE
Verify, before each visit, that the URL has not been manually visited by user

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#867]

**Comment by cqx931** [comment]
So the purpose is that if the user has already clicked an ad, we won't do it again, correct?
And here to add new entires? `onPageLoad`
https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L1374

**Comment by dhowe** [comment]
correct, then check before visit

**Comment by cqx931** [comment]
How long do we keep this set of urls? Do we clear them on each start?

**Comment by dhowe** [comment]
Yes, not necessary to keep in local-storage

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/879 Please check
