### ISSUE TITLE
Last script on Cisco.com for downloads does not work.

### ISSUE THREAD

**Issue by ke-mccormick** [dhowe/AdNauseam#870]
Go to URL below.

https://software.cisco.com/download/navigator.html?i=!mmd

Click on Switches.
Click on Campus LAN Switches - Access.
Click on Catalyst 4500 Series Switches.
Click on Catalyst 4510R Switch.

Now try clicking any thing listed such as Software on Chassis.
None of them will work.

**Comment by dhowe** [comment]
Verified

**Comment by cqx931** [comment]
Please update adnauseam.txt with the following steps and the problem should be fixed now.

1.Go to AdNauseam Settings page (from Menu), then open the 3rd-party-filters panel
2.Click 'purge-all-caches' - 'apply changes' - 'update now'
3.Reload the page on which you saw the problem

**Comment by ke-mccormick** [comment]
Verified working. Thanks.
