### ISSUE TITLE
Implement freeadnauseam timer in js

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#871]
we need the time to be 'live' so that increases ever second,
on this branch: https://github.com/dhowe/AdNauseam/tree/gh-pages-countdown

![image](https://cloud.githubusercontent.com/assets/737638/23228648/44b7da1a-f978-11e6-91e9-12e3a936e378.png)

**Comment by dhowe** [comment]
looks great once single digits are padded with 0s

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pulls

**Comment by dhowe** [comment]
Looks good -- shall I push live @mushon?
