### ISSUE TITLE
Add requests for translations to webpage, addon description, etc.

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#877]

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/23397059/c041c26a-fdd1-11e6-82cc-82f7f7382ccb.png)

**Comment by dhowe** [comment]
Nice!
But I wonder if we need to include the crowdin logo (also, we may change to a different service at some point in the future)... so I'd vote for removing -- any input @mushon  ?

**Comment by mushon** [comment]
yeah, I think we don't need the logo there, it's not like everybody knows Crowdin or that it carries any extra value (unlike the browser logos for ex.)

**Comment by cqx931** [comment]
Please check:
![image](https://cloud.githubusercontent.com/assets/3056154/26389959/0b816c12-408f-11e7-9bb9-feda503fc9bd.png)

https://github.com/dhowe/AdNauseam/pull/1055

**Comment by dhowe** [comment]
nice!
