### ISSUE TITLE
Ad not collected

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#878]
on GFW...
![image](https://cloud.githubusercontent.com/assets/737638/23357837/757592be-fd1a-11e6-8313-efd8ff5a648e.png)

**Comment by dhowe** [comment]
This works correctly in 3.0.50 but not in 3.3, apparently because some doubleclick requests are being blocked -- pls. investigate

**Comment by cqx931** [comment]
Fixed: https://github.com/dhowe/uAssets/pull/40
Easylist is now using this cosmetic filters to hide the ad `##.adsbygoogle`, which caused the image within the iframe not to load.
Added an exception filter for this rule, also other rules to help collecting the image.
