### ISSUE TITLE
TODO:Textad collecting on ask.com is not working

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#886]
Just want to bring this up, this TODO has been there for quite a long time.
https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/textads.js#L131

**Comment by cqx931** [comment]
The current method is not working because the generated text ads are inside an iframe:
![image](https://cloud.githubusercontent.com/assets/3056154/23511074/f20fae76-ff96-11e6-8fd0-06656ba22ef7.png)

**Comment by dhowe** [comment]
Is our content-script being injected into the iframe? If so, then it should work as usual. If not, then why not?

**Comment by cqx931** [comment]
https://github.com/dhowe/uAssets/pull/35
Iframe was successfully injected. It didn't work because there was no cosmetic filters from all the lists that matches askText selector. uBlock blocked this entirely by blocking the js.
Fixed by adding a rule to parse `google.com###adBlock > .ad.a_`
