### ISSUE TITLE
Add warning message for AdBlock conflict

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#887]
They have more downloads on chrome store than adblock plus.

**Comment by dhowe** [comment]
Don't we have this already?

**Comment by cqx931** [comment]
There are uBlock, uBlock origin, AdBlock and AdBlock Plus...
uBlock, uBlock origin and AdBlock Plus are currently working, but AdBlock not.
Because we are checking startswith"AdBLock", not "AdBlock". 
It is easy to also include "AdBlock", but do we need different message for these two? Currently the message shows "AdBlock Plus and AdNauseam may conflict!"

**Comment by dhowe** [comment]
Would be best, if possible, to have only one message: 
  "Your adblocker (Adblock, uBlock, etc.) may conflict with AdNauseam"

**Comment by cqx931** [comment]
The sentence would be too long for the menu, I vote for it without parentheses "Your adblocker may conflict with AdNauseam"

**Comment by cqx931** [comment]
Another problem is that if we want to include this in 3.2 release, we need to rely on machine Translation for the phrase "your ad blocker". And I am not sure about the quality of machine translation for "ad blocker...

**Comment by cqx931** [comment]
Fixed and close https://github.com/dhowe/AdNauseam/pull/924/commits/2477f8d62f77a39f869656afc82c02427d8d7ae7
