### ISSUE TITLE
Firstrun page doesn't pop up v.3.0.50 from Firefox (NonDev)

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#888]
I see this when I tested "Block element" today with downloading and installing AdNauseam from addon store. Not sure if it has always been like this for firefox.
The default set up without going through first-run page doesn't check two DNT settings.
The page does pop up in Dev.

**Comment by dhowe** [comment]
Hmm, interesting. I assume this is already on our release testing checklist?

**Comment by cqx931** [comment]
yes, but we always check this in FirefoxDeveloperEdition, and it works there.

**Comment by dhowe** [comment]
Why are we doing tests in developer edition ?

**Comment by cqx931** [comment]
Because I am not able to test AdNauseam with normal firefox browser if the release is not live in the add-on store... Or is there a way to do this that I missed?

**Comment by dhowe** [comment]
We need to figure out how to do this -- can you do some research?  If you can't find a solution pretty quickly, we should write to mozilla people

**Comment by cqx931** [comment]
Ok...so I just verified this issue to be some tricky performance of how firefox store their extensions/extension information...
The good news is, everything works fine in our code.
If I install adnauseam in firefox(no matter normal version or the dev version), remove it, close firefox, reopen firefox, reinstall adnauseam, the firstrun page doesn't shows up because firstrun variable is false.

I found out that when I remove adnauseam from firefox, it does delete the file in extensions folder(~/Library/Application Support/Firefox/Profiles/[profile name]/extensions), but not 
`adnauseam.sqlite` in extension-data. If I delete that file and try to reinstall adnauseam, the firstrun page pop up again.

**Comment by cqx931** [comment]
As for where to test this(Dev version or normal version), according to [mozilla](https://support.mozilla.org/t5/Problems-with-add-ons-plugins-or/Add-on-signing-in-Firefox/ta-p/30262) it is not possible to run an add-on that has not been verified on a normal firefox browser. This is only possible with DevEdition or Nightly. 

But as long as there is no performance difference among these versions, I think it is ok that we test this with DevEdition?

**Comment by dhowe** [comment]
Well, sure... but how did this bug slip in then ?

**Comment by cqx931** [comment]
Because I was trying to reinstall adnauseam on firefox, which I never tried before.
The usual workflow that opens adnauseam from run-ff.sh AdNauseamDev never saves anything to the profile, so the firstrun page is not influenced in this case.

**Comment by dhowe** [comment]
I'm not sure I understand. Is the issue resolved? When we run the release tests, we use the new release (from xpi) on the current Firefox Developer Version, correct? And we test the first-run page...

**Comment by cqx931** [comment]
yes, the issue is resolved.
