### ISSUE TITLE
Wrong number display of valid rules after Adnauseam filters update

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#889]
When I did the testing for adnauseam filters update, I noticed something strange:
1.For the latest adnauseam.txt, the rule display from a normal build is `209 used out of 210`
2.After deleting two rules from adnauseam.txt and changed the checksum locally, I rebuilt AdNauseam, and the valid rules is  `207 used out of 208`
3.However, when I click update now, the number changes to `204 used out of 210`. When I test the blocking rules on webpages, the result shows that the rules did get updated, but this number display is quite confusing...

The same thing happens to Auto-update

**Comment by dhowe** [comment]
Hmmm, that is strange. I think the unused rules refer to duplicates... do you have the same exact lists enabled in both cases? And are they the same version? Is it possible that updating all updates other lists so that they now duplicate adn rules

**Comment by cqx931** [comment]
So for case `209 used out of 210` and case `204 used out of 210`, they are referring to the same file.
The only difference is that `209 used out of 210` shows up if I build it from local, and `204 used out of 210` is the result I get after update all lists.
After doing the update - purge all caches -apply, I got `203 used out of 208`, instead of going back to `207 used out of 208`

**Comment by dhowe** [comment]
Very strange. How do you know that you haven't updated other lists when doing the update-all?

**Comment by cqx931** [comment]
Other lists are definitely updated as well, so what you said is also possible... Though I used to thought that it means there are some invalid rules in the filter if the first number is smaller than the second one.

**Comment by cqx931** [comment]
recheck after ublock merge

**Comment by cqx931** [comment]
This seems to be ok now with the latest version, close for now.
