### ISSUE TITLE
AdBlocker Warning notifications go above "AdNauseam is paused on this page"  layer

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#892]
Normally these notifications should be hidden beneath the "AdNauseam is paused on this page" layer.
![image](https://cloud.githubusercontent.com/assets/3056154/23489517/d20d8d82-ff2d-11e6-8aeb-9fdddc8eafbf.png)
The above situation only happens when enable other adblocker in extension page, and open menu directly from the same tab without going to other tab.
Though this could be a very rare case but it could be a bit confusing if the user clicks "disable" button now. This action will just close the menu because they are already on extension page. If reopen menu after clicking "disable", the notifications are now hidden beneath the disable layer.

**Comment by dhowe** [comment]
Proposed solution?

**Comment by cqx931** [comment]
They should always hidden beneath the paused layer.

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/pull/895
