### ISSUE TITLE
Ads visible on dailymotion.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#897]
http://www.dailymotion.com/video/x44t526_ten-years-hong-kong-movie-2015-pt-2-2_shortfilms

![image](https://cloud.githubusercontent.com/assets/737638/23564296/e0451f5c-0084-11e7-9225-28357f4292a4.png)

![image](https://cloud.githubusercontent.com/assets/737638/23564320/fa1b64ae-0084-11e7-8026-16457aa6e295.png)

![image](https://cloud.githubusercontent.com/assets/737638/23564336/05d91d40-0085-11e7-8317-aaeef5afd211.png)

**Comment by cqx931** [comment]
I don't see any visible ads  on this page.
![image](https://cloud.githubusercontent.com/assets/3056154/23737030/341f5198-04cb-11e7-937f-7370c33057d1.png)

**Comment by dhowe** [comment]
At the moment, I see only a google ad choices image:

![screen shot 2017-03-10 at 12 34 34 pm](https://cloud.githubusercontent.com/assets/737638/23782262/f04d6d92-058d-11e7-9ab1-e54355e4719a.png)

**Comment by dhowe** [comment]
pls double-check and close

**Comment by cqx931** [comment]
I still don't see any ad on that page, but I was able to see some ads on other pages from the same website, please find the fix here:
https://github.com/dhowe/uAssets/pull/39
