### ISSUE TITLE
DNT rules are not loaded successfully 

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#899]
![image](https://cloud.githubusercontent.com/assets/3056154/23595562/ca29b27a-025d-11e7-94ea-0326a619f9fd.png)

**Comment by dhowe** [comment]
Seems we may need to add adnauseam.txt and eff-dnt to api.listKeyAliases in assets.js ?

**Comment by cqx931** [comment]
Just checked what you suggested and tested, but it still doesn't work. Seems to be more things missing.

**Comment by dhowe** [comment]
I will take a look

**Comment by cqx931** [comment]
Fixed and close https://github.com/dhowe/AdNauseam/commit/0f4cbc83590f6a67a89586e2b0d215e205e7e877
