### ISSUE TITLE
FAQ: How to build and install development versions for various browsers

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#9]

**Comment by CyrusSUEN** [comment]
On Chromium / Opera:
build the extension in Terminal
```$ tools/make-chromium-adn.sh```
or 
```$ tools/make-opera-adn.sh```

open browser and go to settings page by the URL ```chrome://extensions/``` (also works on Opera)
Enable Developer mode in the settings page and load extension from ```/dist/build/adnauseam.chromium``` or ```/dist/build/Adnauseam.opera```

On Firefox:
create and a user profile (or use the 'default' profile)
open Firefox and go to ```about:config``` page and toggle ```xpinstall.signatures.required``` to false
```$ tools/run-ff.sh default```

**Comment by dhowe** [comment]
TODO: add to v2 FAQ

**Comment by yansh** [comment]
I tried to follow the Firefox instructions, after running ``` tools/run-ff.sh'' I get the following error.

```error: option `-p, --profile <path>' argument missing''

P.S. I also had to install [jmp](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm).

**Comment by dhowe** [comment]
good point about jpm... 
but strange that you get that error
Does your run-ff.sh looks like this:
````
#!/bin/sh

set -e

tools/make-firefox.sh

cd bin/build/adnauseam.firefox

jpm run --profile ${1:-default}

cd -
````

**Comment by yansh** [comment]
Actually no:

```
#!/bin/sh                                                                       
                                                                                
set -e                                                                          
                                                                                
tools/make-firefox-adn.sh                                                       
                                                                                
cd bin/build/adnauseam.firefox                                                  
                                                                                
jpm run --profile $1                                                            
                                                                                
cd -
```

Strange.

**Comment by dhowe** [comment]
have you been pulling regularly from upstream (I assume you are working on your own fork)?

**Comment by yansh** [comment]
Apparently not regularly enough ;) All good now.

**Comment by yansh** [comment]
@dhowe for some reason, I started to get an error when trying to open the vault in Firefox. 
<img width="1006" alt="screen shot 2016-04-05 at 9 08 37 am" src="https://cloud.githubusercontent.com/assets/1371050/14282862/61c53aee-fb0e-11e5-9fc6-611e41436a6e.png">

**Comment by dhowe** [comment]
Are you using a bookmark? Are you on version 2.0.6 of adn?

**Comment by yansh** [comment]
what bookmark? I run ```tools/run-ff.sh``` and yes it's 2.0.6.

It worked before.

**Comment by dhowe** [comment]
Something appears to be cached, as that file hasn't existed for a while... (and there is no link to adn-vault.html anywhere in the source code)

**Comment by dhowe** [comment]
This is what I get: 
![screen shot 2016-04-05 at 9 22 59 pm](https://cloud.githubusercontent.com/assets/737638/14283150/9b5c77e8-fb74-11e5-9caa-c777905f4496.png)

In any case, if you remove the "adn-" from the link it should be there...

**Comment by yansh** [comment]
yes, without "adn-" it works, but only in Firefox.

This code in menu.js works in Chrome. 

```
  $('#vault-button').click(function () {
    window.open("./adn-vault.html", "AdNauseam").focus();
  });
```

**Comment by dhowe** [comment]
https://github.com/dhowe/AdNauseam2/blob/master/src/js/adn/menu.js#L369

**Comment by yansh** [comment]
Seems so, sorry. I don't use Firefox and the code that I have works on Chrome, so I haven't noticed it.

**Comment by yansh** [comment]
@dhowe just fetched the latest version and tried make-chromium.sh

I get error:

<img width="866" alt="screen shot 2016-06-10 at 9 29 12 am" src="https://cloud.githubusercontent.com/assets/1371050/15965786/f71febd0-2eed-11e6-8edb-0cab540ff403.png">

**Comment by dhowe** [comment]
Ok -- have you installed jq as it suggests?

**Comment by yansh** [comment]
Sure, just wanted to point out the error.

**Comment by dhowe** [comment]
Moving instructions [here](https://github.com/dhowe/AdNauseam/wiki/Building-AdNauseam-from-source-(for-developers)) and closing
