### ISSUE TITLE
Clicking one ad in vault causes a re-visit animation

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#91]
To recreate, import the ads below, then go to vault, then click on the one ad to inspect it

[AdNauseam-exported-ads_3-26-2016,_8-25-37_PM.json.zip](https://github.com/dhowe/AdNauseam2/files/190484/AdNauseam-exported-ads_3-26-2016._8-25-37_PM.json.zip)

**Comment by dhowe** [comment]
I've also seen this problem with multiple ads in the vault, but where only one cause the problem: a successful visit animation (purple slide-over) each time the ad is clicked. Besides being intermittent, using the inspector actually seems to fix the problem, so its doubly-hard to debug...

**Comment by yansh** [comment]
Tried it with Chrome, but wasn't able to recreate the problem. I clicked on the ad multiple times.
<img width="921" alt="screen shot 2016-03-28 at 4 23 20 pm" src="https://cloud.githubusercontent.com/assets/1371050/14089166/77d1c518-f501-11e5-856a-de8159e641c4.png">

**Comment by dhowe** [comment]
Yes, its an intermittent problem -- I guess we wait until someone else sees it and/or I can document it with video. On hold for now...

**Comment by dhowe** [comment]
Documented this with video below. The ad below happens to have failed however I have seen it happen with successful visits as well:

[mutiple-animations.mov.zip](https://github.com/dhowe/AdNauseam2/files/202887/mutiple-animations.mov.zip)

**Comment by CyrusSUEN** [comment]
I can reproduce this problem now.

First set core.js::failAllVisits and core.js::clearVisitData both to 1. Import the ad and then restart Chrome.

After the first failed attempt to visit the ad, you can reproduce the problem by clicking the ad tile.
Problem is that after clicking the ad tile there will instantly be another failed attempt animation and clicking the mouse elsewhere (to exit the inspect mode) the animation happens again.

See the video demonstration:
![animation](https://cloud.githubusercontent.com/assets/2461812/14675074/c5da81f6-0739-11e6-8b86-b4ac3ddb0fe0.gif)

**Comment by dhowe** [comment]
Good. Do you have a fix?

**Comment by CyrusSUEN** [comment]
> I see a PR that looks related

That was fix to one problem mentioned in https://github.com/dhowe/AdNauseam2/issues/81#issuecomment-209952717.

This issue#91 is only happening on Chrome and Firefox is not affected.

The .just-failed animation got triggered in [vault.js:836](https://github.com/dhowe/AdNauseam2/blob/38f6d9b3fb972ff569b06e0c5afa9f97d5313f71/src/js/adn/vault.js#L836) when inspecting the ad.
And it got triggered again when exiting the inspect mode at [vault.js:868](https://github.com/dhowe/AdNauseam2/blob/38f6d9b3fb972ff569b06e0c5afa9f97d5313f71/src/js/adn/vault.js#L836).

**Comment by dhowe** [comment]
Do you have a fix?

**Comment by CyrusSUEN** [comment]
Tried to replace jQuery removeClass() with the following. But the problem is still there.
```js
var item = document.getElementsByClassName('inspected')[0];
item.className = item.className.replace(/\binspected\b/, '');
```

> Do you have a fix?

I have an idea for the fix.
We add a new attribute class '.animated'. Only with the presence of it shall there be the .failed-attempt animation .

**Comment by dhowe** [comment]
work on something else...

**Comment by dhowe** [comment]
Haven't seen this in some time -- closing for now...
