### ISSUE TITLE
Bugs on other locales

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#911]
**Chinese:**(from Release 3.1.30)
1.First-run page, span tag
![image](https://cloud.githubusercontent.com/assets/3056154/23642942/721a73ee-0339-11e7-93a7-c9be35381534.png)

2.DNT Notification, undefined
3.Menu - Text ads layout
![image](https://cloud.githubusercontent.com/assets/3056154/23642921/5820081e-0339-11e7-8642-2250698088dd.png)

**Comment by cqx931** [comment]
4.adnauseam.txt is not loaded when installed with Chinese default locale.
![image](https://cloud.githubusercontent.com/assets/3056154/23643846/2cfb0d36-033f-11e7-892b-7b9d90f0437e.png)

**Comment by dhowe** [comment]
Good notice! Is this related to the merge, or a pre-existing problem? 
We should make sure to test other locales regularly...

**Comment by cqx931** [comment]
The first three problems should be pre-existing problem, starting from 3.1.30 in release versions, if ignoring the version bumps during development.
And the last one is caused by the latest merge.

**Comment by cqx931** [comment]
The layout of the text ad in Chinese language setting seems to be caused by a design decision from chrome browser. 
If the language is set to Chinese, the minimum font size is 12px.
And here we are setting the content of Text-ad to 10px... 
One way to solve it is to set the hight of each text entry to 90px instead of 80px. But I'm not sure whether we want to do this due to this very minor case.
https://productforums.google.com/forum/#!topic/chrome/Q18nyAQimVo

**Comment by dhowe** [comment]
@mushon?

**Comment by cqx931** [comment]
Fixed all above issues except the Chinese text-ad layout one: 
https://github.com/dhowe/AdNauseam/pull/924

**Comment by dhowe** [comment]
Ok, closing (#924 remains open)
