### ISSUE TITLE
3rd-party filters page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#913]
Basically we want to follow the layout of the old 3p-filters page:

- [x]  AdNauseam.txt not showing (should be first entry)
- [x]  Remove irrelevant options: 'Parse and enforce cosmetic filters', 'Ignore generic cosmetic filters'
- [x]  Move Auto-update to left of 'update now' button (as in previous version)
- [x]  'Languages' menu should be collapsed by default
- [x]  +/- before network filters count is confusing
- [x]  Need to remove non-applicable lists  (peter-lowe, experimental, malvertising, etc.) - DH

![screen shot 2017-03-07 at 4 06 35 pm](https://cloud.githubusercontent.com/assets/737638/23647387/8b7b5684-0350-11e7-9362-d67f6b8a5c71.png)

**Comment by cqx931** [comment]
If you remove the previous version and reload the latest adnauseam, adnauseam.txt should be there.

**Comment by cqx931** [comment]
> +/- before network filters count is confusing

That is exactly how ublock implement this right now. Although I won't know that it can collapse unchecked filters if I didn't read their release notes. I find it ok that "+"/"-" indicate "show more"/"collapse"

**Comment by cqx931** [comment]
> 'Languages' menu should be collapsed by default
Isn't it already collapsed?

**Comment by dhowe** [comment]
Yes, languages are collapsed, the other points above still need to be addressed

**Comment by dhowe** [comment]
Re: the +/- Perhaps we change the 2nd plus on that line to a slash /

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/AdNauseam/pull/915

**Comment by dhowe** [comment]
The problem is that when it + or - is used to separate the two counts, it looks like an equation:

![image](https://cloud.githubusercontent.com/assets/737638/23668443/10735a3a-039c-11e7-983d-962fb3cacbc0.png)

Lets try either slash '/' or two colons '::'

**Comment by cqx931** [comment]
I prefer slash than two colons:
https://github.com/dhowe/AdNauseam/pull/918/commits/42be316a6fefbdee5647845a1c1dee93bb561ee4
