### ISSUE TITLE
The page hovers

### ISSUE THREAD

**Issue by rdbox** [dhowe/AdNauseam#922]
I can not understand why this happens when I have AdNouseuse enabled, the page hangs at the bottom of the Chrome browser.
It is written - the application is expected to be downloaded AdNauseam
why is that ? 
Here is a screenshot http://prntscr.com/eil6yq

**Comment by dhowe** [comment]
What is the page?
Also, Chrome version, and AdNauseam version?

**Comment by rdbox** [comment]
Version of AdNauseam v3.1.34
The browser version is 56.0.2924.87

**Comment by dhowe** [comment]
Exactly when does the problem happen?

**Comment by rdbox** [comment]
A few days ago, maybe a week ago.

**Comment by dhowe** [comment]
I mean, how do we recreate the problem? What steps cause it to occur?

**Comment by rdbox** [comment]
Well, here's an example:
There is a site https://news.mail.ru on it there is news I passed on these news to read different articles posts.
And after that, the browser and the pages were hanging. Once I unplug the AdNauseam application everything starts working

**Comment by dhowe** [comment]
Please add a screenshot. Thanks

**Comment by dhowe** [comment]
@cqx931 I can't recreate this on my system -- can you try?

**Comment by rdbox** [comment]
I updated the app to version v3.2.02 
Problems no more
