### ISSUE TITLE
Chinese text-ad layout problem

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#925]
The layout of the text ad in Chinese language setting seems to be caused by a design decision from chrome browser. 

If the language is set to Chinese, the minimum font size is 12px. Even though the text is actually in English.
And here we are setting the content of Text-ad to 10px... 

One way to solve it is to set the hight of each text entry to 90px instead of 80px. But I'm not sure whether we want to do this due to this very minor case.

https://productforums.google.com/forum/#!topic/chrome/Q18nyAQimVo

![image](https://cloud.githubusercontent.com/assets/3056154/23642921/5820081e-0339-11e7-8642-2250698088dd.png)

**Comment by mushon** [comment]
I added rules to avoid these overflows but I'm not sure what to do about the long text. Is that something we can try to edit down? or provide the full text on hover?

**Comment by cqx931** [comment]
What did you use to avoid the overflows?
If it is by adding overflow:hidden to `#ad-list li`, it will cause troubles to the hover image effect.

Since this is case only happens to text-ad in chrome with Chinese language setting, I think it is better to find a minimal solution.

**Comment by mushon** [comment]
yes, I used ``overflow:hidden`` why should that be a problem?
+ Either way I agree we should find a minimal solution.

**Comment by cqx931** [comment]
When an image is hovered and being enlarged, the parts that overflows the div will be hidden.
But if we do "overflow:hidden" only on text-ad div, image ads won't be influenced.

**Comment by mushon** [comment]
Right. Let's do that. 

Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon
