### ISSUE TITLE
AdNauseam install on non-google chromium browsers

### ISSUE THREAD

**Issue by maluethi** [dhowe/AdNauseam#926]
I am using the Vivaldi browser and was wondering if there was a way to install AdNauseam other than using the developer mode?

**Comment by dhowe** [comment]
Seems [this post](https://forum.vivaldi.net/topic/1532/extensions-from-opera-add-ons-the-easy-way) suggest that it is possible to install addons from the Opera store. Can you give a try and report back?

**Comment by maluethi** [comment]
I have followed the posted link, it seems to work ok although after adding it by hand Vivaldi was complaining (I guess due to the fact that I downloaded an Opera extension):
> There were warnings when trying to install this extension:
> Unrecognized manifest key 'developer'.

Note that I have not done any extensive testing.

Anyway this does not seem to be any different from the usual Chromium installation procedure, which I was hoping for. But I am happy to use AdNauseam this way...
