### ISSUE TITLE
Dev-FAQ entry on creating a new release

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#936]
1. make sure 'webext' is installed
2. run tools/git-tag.sh VERSION (first make sure there is small change, eg the version number)
3. run tools/make-artifacts.sh
4. go to github and create new release from tag, then added release notes, and drag 5 files from artifacts into window
5. when approved for production, update chromium links on the website, then submit to opera and ff stores

**Comment by cqx931** [comment]
1. make sure 'webext' is installed
2. run `tools/git-tag.sh` VERSION (first make sure there is small change, eg the version number)
3. run `tools/make-artifacts.sh`
4. make a new PR and add a note for new release tag
5. After the PR is accepted and new release tag is created in the dhowe/AdNauseam/master. Go to release, and edit the release tag by adding information about changes and upload the five files generated from `tools/make-artifacts.sh`
5. When approved for production, update chromium links on the website, then submit to opera and firefox stores
*** Please remember to also include the source code when uploading to firefox store.

<hr>
I am not sure about step 2 though,  `tools/git-tag.sh` is not necessary here, as it only goes to the forked branch...But maybe it is better to keep this step?

**Comment by cqx931** [comment]
@dhowe

**Comment by dhowe** [comment]
I think step 2 can be removed for now

**Comment by cqx931** [comment]
Added here: https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#how-do-i-create-a-new-release
