### ISSUE TITLE
[Firefox] AdNauseam button is not updated correctly after switching to other tabs

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#950]
To reproduce:
1. Go to 'duckduckgo.com'
2. Open a new tab, and go to any page
3. Switch back to duckduckgo.com tab, the icon is still grey.

**Comment by dhowe** [comment]
this is strange... when did this bug appear?

**Comment by cqx931** [comment]
I tested on 3.0.50 and the bug already appears then.

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/blob/master/platform/firefox/vapi-background.js#L1365
This is called whenever a tab switch is detected, and the arguments that get passed in does not consider dnt situation.

**Comment by dhowe** [comment]
I'm not sure I understand, however, if you have a fix, go ahead...

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/952/commits/2c975ff6d465607d57888730060f9d2506fa7358 fixed
