### ISSUE TITLE
[Firefox]Incoming cookies are allowed from ad visit

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#951]
[Testcase](http://lab-lamp.scm.cityu.edu.hk/adntest/cookie-setting-ad.html)

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/blob/master/platform/firefox/vapi-background.js#L2294
adn.lookupAd(URI.asciiSpec, requestId) is undefined for this testcase.

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/blob/master/platform/firefox/vapi-background.js#L2278
Result is undefined

**Comment by dhowe** [comment]
result can be undefined, that is not a problem necessarily..

**Comment by cqx931** [comment]
For a valid ad that has a successful ad visit, the result got from onHeadersReceived should not be  undefined, right?
Currently the result is undefined, so nothing would be processed for the headers received and incoming cookies get in.
This worked when we test ffcook2, not sure what has changed lately that causes troubles again.

**Comment by dhowe** [comment]
in my debugging, I haven't been able to 'see' existing cookie-setting headers (set-cookie, or setCookie2) in the responseHeaders array on FF

**Comment by cqx931** [comment]
I have no problem in 'seeing' set-cookie header in the array
![image](https://cloud.githubusercontent.com/assets/3056154/24182297/d8784a12-0efb-11e7-882a-501723c25f82.png)

**Comment by dhowe** [comment]
is this in the debugger? where is your breakpoint?

**Comment by cqx931** [comment]
This is not the debugger, I'm not very familiar with debugging in firefox...
https://github.com/dhowe/AdNauseam/blob/master/platform/firefox/vapi-background.js#L2269
I just logged responseHeaders after the above line

**Comment by dhowe** [comment]
https://developer.mozilla.org/en-US/Add-ons/Add-on_Debugger

**Comment by cqx931** [comment]
It need to be the one that is xmlhttprequest.
![image](https://cloud.githubusercontent.com/assets/3056154/24188457/6594aa06-0f1c-11e7-9238-4c285881d653.png)

**Comment by cqx931** [comment]
If I remove vAPI.chrome from the if statement in onHeadersReceived in traffic.js, the result could be then successfully returned and everything works.
https://github.com/dhowe/AdNauseam/blob/master/src/js/traffic.js#L565

Or in ffcook2, we did this: https://github.com/dhowe/AdNauseam/blob/ffcook2/src/js/traffic.js#L437

But I think we can simply remove vAPI.chrome as we are now considering firefox as well?

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/commit/faa540cf3e1652041dc2c7b6fada30a0bdeb7c06
