### ISSUE TITLE
Please check bug report

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#953]
![image](https://cloud.githubusercontent.com/assets/737638/24162892/e6cfd696-0ea3-11e7-96a7-ff19ef2cb3d3.png)

send poster a question if necessary

**Comment by greysonevins** [comment]
@dhowe cannot reproduce this issue, so I am trying to reach out to dave.

**Comment by dhowe** [comment]
@greysonevins please update

**Comment by dhowe** [comment]
also cannot recreate
