### ISSUE TITLE
Investigate how PB are running their unit tests

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#954]
https://github.com/EFForg/privacybadger/pull/1250/files/631d8d1db82d42388a5e9511d9716f4fe56aacc1..16a9261ea784d9f0d3c8ebb687a60b901b25f713

**Comment by cqx931** [comment]
From what I see they are doing qunit module tests on Privacy Badger.
If we do similar things for adnauseam, that would be for core.js, dnt.js, things that happen in the background... not sure about the scripts that are not inside the adn folder.

**Comment by dhowe** [comment]
do they involve visiting urls?

**Comment by cqx931** [comment]
no, I don't think so. In their tests folder they do have some selenium related files, but those files seem to still be in TODO stage and I don't see any test cases there.
