### ISSUE TITLE
Visual representation of ads that will not be visited 

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#958]
either b/c of click-probability or if they were manually visited

-- currently we have 3 colors for (unvisited, visited, and failed)

**Comment by dhowe** [comment]
works for me... though maybe we need a mouse-over for each of the states ?

**Comment by mushon** [comment]
In the menu? the vault? both?

**Comment by dhowe** [comment]
the color should be both... the mouse-over is just an idea, not sure if it is or isnt necessary in either

**Comment by dhowe** [comment]
see also #1168

**Comment by cqx931** [comment]
close this, move to #1168
