### ISSUE TITLE
Please check-in .psd/.ai/sketch files for the project to github

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#959]
We need to have these in a central/backed-up location

**Comment by mushon** [comment]
Will do tomorrow, Though I use Sketch, not Psd or AI.

**Comment by dhowe** [comment]
@mushon ?

**Comment by mushon** [comment]
better late than never… https://github.com/dhowe/AdNauseam/commit/1d0a43aea6ac312c04af2ba5dd36bd55da6fdb83

**Comment by dhowe** [comment]
what resources are included?

**Comment by mushon** [comment]
The sketch file

**Comment by dhowe** [comment]
for which of the dozens of images in the project?

**Comment by mushon** [comment]
All of them, I think. If anything is missing I will add it. I will also add a version to explore without Sketch.

**Comment by cqx931** [comment]
I am also using Sketch but I got the error message "The document “ad_view.sketch” could not be opened. ". Which version are you using? @mushon

**Comment by mushon** [comment]
I'm using the latest version. I will try to save and resubmit later. Hopefully it will do the trick. 

Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

**Comment by dhowe** [comment]
@mushon ??

**Comment by mushon** [comment]
I sent all assets a few days ago. Anything missing there?https://github.com/dhowe/AdNauseam/commit/2b755cb97f153f786c2b91a9f656f606b6f3bf87

**Comment by dhowe** [comment]
better to do a pr, so we are aware

**Comment by mushon** [comment]
Sure thing. Will do.

**Comment by dhowe** [comment]
Please add website resources as well

**Comment by mushon** [comment]
@dhowe it's all there in the file:
![image](https://user-images.githubusercontent.com/27123/27423849-bb7db5fe-573b-11e7-8cc5-04a1d86ed135.png)

Though do take into account that some of the design changes have been made directly in code.
