### ISSUE TITLE
Easier Install Procedure

### ISSUE THREAD

**Issue by nikhiljha** [dhowe/AdNauseam#960]
Download the .crx then drag + drop it onto extensions. Takes 30 seconds and can be done entirely from Chrome. It also doesn't require enabling developer mode **so no annoying pop up!**

Is there any reason why this isn't the way the guide says how to install it?

**Comment by dhowe** [comment]
Have you tried restarting Chrome after using this method?

**Comment by nikhiljha** [comment]
My chrome is never fully closed, but I did close and reopen the chrome user I was using.

Does it delete itself on restart? Aww.

**Comment by dhowe** [comment]
It disables the extension on restart -- thanks for the suggestion though
