### ISSUE TITLE
Visible ad overlay on vice.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#962]
https://creators.vice.com/en_uk/article/pratt-surveillance-art-and-ethics

![image](https://cloud.githubusercontent.com/assets/737638/24389619/91ece8aa-13b5-11e7-9125-3aa549dbd58e.png)

**Comment by cqx931** [comment]
I can't reproduce this ad even with no ad blocker.

**Comment by greysonevins** [comment]
Same as @cqx931 I cannot duplicate

**Comment by greysonevins** [comment]
@dhowe I have not been able to duplicate this popup.

**Comment by dhowe** [comment]
closed: cannot recreate
