### ISSUE TITLE
Video ad plays on CNN

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#965]
But not with uBlock
http://edition.cnn.com/videos/us/2017/03/27/ted-koppel-sean-hannity-cbs-sje-mobile-orig.cnn

![image](https://cloud.githubusercontent.com/assets/737638/24438937/988b26cc-147d-11e7-861f-02c0a88ceaa1.png)

NOTE: I can no longer recreate this

**Comment by dhowe** [comment]
![image](https://cloud.githubusercontent.com/assets/737638/24438937/988b26cc-147d-11e7-861f-02c0a88ceaa1.png)

**Comment by cqx931** [comment]
On my computer, I can only see this 14 seconds black screen sometimes, it doesn't play and will disappear after a few seconds for me.
![image](https://cloud.githubusercontent.com/assets/3056154/24941068/2384074c-1f7a-11e7-975a-ca70ddc10f84.png)
