### ISSUE TITLE
Add indication of ADN-allowed request to uBlock log

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#966]

**Comment by dhowe** [comment]
@cqx931 how to test this?

**Comment by cqx931** [comment]
To test: 
1. Comment out [this line ](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L1195) and rebuild
1. Turn on debugging mode and open background page, 
1. Open uBlock Logger
1. Go to page such as nytimes.com and the adnauseamAllowed requests that are logged into adnauseam background page should appear in the uBlock logger as purple entries
