### ISSUE TITLE
Don't reccommend Maxthon, it's literally spying on users

### ISSUE THREAD

**Issue by Senthe** [dhowe/AdNauseam#967]
On this page you recommend Maxthon instead of Chrome:
https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission

Maxthon became known for spying on people and sending their sensitive data to Chinese servers.

Article: http://www.securityweek.com/maxthon-browser-sends-sensitive-data-china
Source document: https://regmedia.co.uk/2016/07/18/exatel_maxthon_report.pdf

Please remove Maxthon from recommendations, it's not secure and can't be trusted.

**Comment by dhowe** [comment]
thanks @Senthe !
