### ISSUE TITLE
App on chrome is causing it to "run out of memory"

### ISSUE THREAD

**Issue by kevansevans** [dhowe/AdNauseam#968]
Been using adnauseam on chrome and it's been causing difficulties for me casually browse the internet. Pages would load half way before receiving the error, or I would scroll and get the error, or I would simply click anywhere on the page and get the crash. I restarted chrome, and it "automatically" disabled it for me and would not allow me to turn it back on, but after it did so, I stopped having these problems. Ublock was disabled during it's use. Extensions I currently have:

BetterTTV 7.1
Chrome Remote Desktop 57.0.2987.84
Chromium Wheel Smooth Scroller 1.4.2
Enhanced Steam 9.2
Google Mail Checker 4.4.0
Reddit Enhancement Suite 5.4.3
TrackMeNot 0.8.4
uBlock 0.9.5.0 (disabled to prevent conflicts)

**Comment by dhowe** [comment]
Thanks for the report. I wonder if there is a conflict with one of those other extensions... Can you tell us the version of AdNauseam you are using and your OS? Also, if you have time to enable debugging at the bottom of AdNauseam's settings, that would be great. Then we can check the debug log (in Chrome's extension page, under AdNauseam, click 'background.html') for any errors that might have occurred.

**Comment by kevansevans** [comment]
Windows 10 Pro
AdNauseam Release v3.3.32

Also I had to reinstall it. After chrome disabled it without my permission, it wouldn't let me turn it back on, so I am not sure if I can provide any full logs.

**Comment by dhowe** [comment]
Google will continue trying to disable extensions installed from anywhere other than their own store. However, for a workaround, see [these instructions](https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission).

**Comment by kevansevans** [comment]
I was not presented with the option to cancel chrome from disabling the app when it had shown.

**Comment by dhowe** [comment]
I believe that you need to a) enable developer mode, and b)  install from the .zip, not the .crx file on our [Releases](https://github.com/dhowe/AdNauseam/releases/latest) page 

Google doesn't make it easy

**Comment by kevansevans** [comment]
That was the way I had done it previously.

**Comment by dhowe** [comment]
Hmmm, strange -- ill re-check it a bit later
thanks

**Comment by cqx931** [comment]
In our testing we only see the message in your screenshot if adnauseam is installed through a crx file.

Could you double check that your adnauseam is loaded from a folder?
Go to  `chrome://extensions`, you should be able to see "Loaded from:" with the path of the folder
<img width="795" alt="screen shot 2017-03-31 at 3 29 57 pm" src="https://cloud.githubusercontent.com/assets/3056154/24540736/1e419c2e-1627-11e7-9393-fd9ee95952b5.png">

If it is loaded from crx file, the message would like this:
<img width="768" alt="screen shot 2017-03-31 at 3 30 09 pm" src="https://cloud.githubusercontent.com/assets/3056154/24540778/41115eba-1627-11e7-8fa6-be4d1c45f854.png">

**Comment by kevansevans** [comment]
![screenshot 2017-03-31 09 07 32](https://cloud.githubusercontent.com/assets/10257965/24557284/6628b5dc-15f4-11e7-9165-54047333a786.png)

**Comment by dhowe** [comment]
And can you show us the message you get, after restarting chrome (in our testing, it is a warning that can be cancelled)?

Thanks (and sorry for all the requests, but it is quite important we figure out what is happening here)

**Comment by kevansevans** [comment]
The earlier dropbox link is the error I get. I will add though that I'm no longer getting any out of memory errors.
