### ISSUE TITLE
Change discrete frequency setting to continuous slider

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#969]
with snap-to-tick marks for our current settings

**Comment by greysonevins** [comment]
@dhowe 
![image](https://cloud.githubusercontent.com/assets/11656811/25645534/fdf075f2-2f7c-11e7-9fad-3346d298c74e.png)

Was this what you were looking for? I didn't touch the css for it, but the slider works.

**Comment by cqx931** [comment]
Yes, this looks like the right direction to go.
Please make sure that the slider goes from 'OCCASIONAL' to 'ALL' and keep the text for the choices in between('MOST', 'SOME').

**Comment by dhowe** [comment]
and should be able to select values _in between_ the tick marks

**Comment by greysonevins** [comment]
@cqx931 pull request above

**Comment by cqx931** [comment]
As for the css style I think a slider like this would be a good match for the current design. No grey border for the outer div and the text for all markers are always visible.
Any comment on the design? @dhowe 
![image](https://cloud.githubusercontent.com/assets/3056154/25769418/c3fbe5b2-324b-11e7-9fb5-dc4728298d37.png)

**Comment by cqx931** [comment]
@dhowe

**Comment by dhowe** [comment]
Looks good to me, though make sure the labels are spelled correctly.
@cqx931  ?

**Comment by cqx931** [comment]
Fixed the spelling in the above image.
@greysonevins Please implement the style above for the slider.

**Comment by greysonevins** [comment]
@cqx931 can you send me the CSS when you get a chance?

**Comment by cqx931** [comment]
I don't have the css, the above image is just a mock up image.

**Comment by greysonevins** [comment]
<img width="388" alt="screen shot 2017-05-25 at 5 34 15 pm" src="https://cloud.githubusercontent.com/assets/11656811/26531083/a7367242-43af-11e7-9146-f3502d70edf2.png">
<img width="424" alt="screen shot 2017-05-28 at 2 11 32 pm" src="https://cloud.githubusercontent.com/assets/11656811/26531084/a9914d3c-43af-11e7-8153-5e9000807e24.png">

**Comment by greysonevins** [comment]
<img width="345" alt="screen shot 2017-05-28 at 2 11 26 pm" src="https://cloud.githubusercontent.com/assets/11656811/26531087/b36c4866-43af-11e7-84cf-58e2d360c116.png">

Not a lot of documentation on dynamic range sliders. This is the best solution I could find.

**Comment by cqx931** [comment]
Please check this example: http://jsfiddle.net/ezanker/TL7M2/8/.
It needs some javascript, but it shouldn't be too hard to achieve.

**Comment by greysonevins** [comment]
![image](https://cloud.githubusercontent.com/assets/11656811/26650288/ec9c569e-4616-11e7-9887-2ab127346014.png)
Style edits and commit made. @cqx931

**Comment by greysonevins** [comment]
![image](https://cloud.githubusercontent.com/assets/11656811/26650452/7abf2bc2-4617-11e7-992a-0edf33e42157.png)
FF looks a bit different (different css ability), but works the same

**Comment by cqx931** [comment]
I have modified the css to match with the design. 
The slider in firefox should also look the same as the one in chrome by now

https://github.com/dhowe/AdNauseam/pull/1058

Chrome
<img src="https://cloud.githubusercontent.com/assets/3056154/26676692/6ee98754-46fb-11e7-95f4-011058de4cf8.png" width="500">
Firefox
<img src="https://cloud.githubusercontent.com/assets/3056154/26676696/714e5cf4-46fb-11e7-8270-7d8b5196c7bf.png" width="500">

**Comment by cqx931** [comment]
please verify and close @greysonevins

**Comment by greysonevins** [comment]
@cqx931 Looks great! Thanks for the changes!

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/26706473/547d8076-4770-11e7-86a8-ff76c93ea536.png)
In the latest update, I modified the width of the slider so that it matches with the width of the text above.
@greysonevins noticed that in this case, 'some' is around 50%, instead of the 30%.

@dhowe Do you still want to maintain the old percentage value for each text mark?
This seems to be less important for a continuous slider.

Also, we might want to change 'all' to 'click all' to show some hint here.

**Comment by dhowe** [comment]
Lets try with 3 options: Rarely, Sometimes, Always

and note that when finished, these needed to be localized

**Comment by dhowe** [comment]
We also need a ? icon for this, leading to the FAQ question

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/26815622/e87aac48-4abf-11e7-83a5-e64ab508f61c.png)

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/26815729/89f24f0e-4ac0-11e7-9050-5874431be645.png)

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/AdNauseam/pull/1064

**Comment by dhowe** [comment]
[ ] - check frequency
[ ] - check localization
[ ] - check 2 info buttons

**Comment by cqx931** [comment]
Minor tweaks for other languages: https://github.com/dhowe/AdNauseam/pull/1086

**Comment by dhowe** [comment]
@cqx931 can this be closed ?

**Comment by cqx931** [comment]
all done and close
