### ISSUE TITLE
music.google.com audio ads are not being blocked

### ISSUE THREAD

**Issue by 2c2c** [dhowe/AdNauseam#972]
These were being blocked with ublock. Note: the ads all seem to be charity oriented.

http://music.google.com/ this will require playing music until an ad rolls, no specific URL I can give, sorry.

**Comment by greysonevins** [comment]
Hi @2c2c, I am having trouble recreating this. 
 @dhowe

**Comment by dhowe** [comment]
@2c2c from what geographical location did you see this issue? @cqx931 have you been able to recreate this?

**Comment by cqx931** [comment]
Google music is not in service in Hong Kong. So I tried it a few times with vpn from the states but was not able to recreate this.

**Comment by 2c2c** [comment]
Southern California

i incidentally have a recording i made for other purposes that shows it happening

https://www.youtube.com/watch?v=rwyWa_5-TRI&feature=youtu.be&t=2190


note: only happens once in a 45min video

**Comment by 2c2c** [comment]
an ad for kiva played thru audio and had an ad overlay on the player for the duration

https://pubads.g.doubleclick.net/pcs/click?xai=AKAOjsvbAQWBintNLas8lLrk-zrV4verfrb62pf3uZwWFPlEYGmzy_Zoz7rgrVXz3_HKUYSCB-ETZKS6_fxvlP7BOomthR57APoYGpcZEcZ3exxIXOt2HUL3-k7Cb10-dGdw48_mA4ocqjlAXl78OJgHSrNKI7B8KNq9xjXJ7JFwnwwPSGXLdqHdE0dXd2FHOwIuQjrTIFObPDwQDLcK_2CFcTzHQXuZeGXBNbbnboYIfylNT5jU9rBd-gioeA&sig=Cg0ArKJSzBg3skuBaxXq&adurl=https://www.kiva.org/about%3Futm_source%3DGooglePlay%26utm_medium%3DAudioAd%26utm_campaign%3DKiva_audio_psa

**Comment by mneunomne** [comment]
music.google.com doesn't exist anylonger. Closing
