### ISSUE TITLE
Site survey

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#977]
Visit your favorite 10 sites with ads using Chrome. First with no extensions, then with AdNauseam.

For each:

1. Note the number of visible ads (with no blocker)
2. The number of visible ads with AdNauseam
3. The number of collected ads (in menu) with AdNauseam

**Comment by greysonevins** [comment]
1. motherboard.vice.com  [Link To Article Here](https://motherboard.vice.com/en_us/article/the-islamic-states-tech-support-is-worried-about-cia-hacking-tools)

   * Without AdNauseam: Seeing 2 Ads
      * 1 Header ad
      * 1 mid article ad
   * With AdNauseam:
      * Both articles were collected by AdNauseam

2. inc.com [Link To Article Here](https://www.inc.com/travis-bradberry/11-ways-to-beat-procrastination.html)

      * Without AdNauseam: Seeing 3 Ads on articles
           * 1 header ad on article
           * 2 side ads
      * With AdNauseam:
           * All ads were collected in AdNasueam. 

3. vice.com [Link To Article Here](https://www.vice.com/en_us/article/travel-has-always-been-deadly-for-people-of-color)

   * Without AdNauseam: Seeing 1 Ad
      * 1 Header ad
   * With AdNauseam:
      * AdNauseam collected the ad

4. stackoverflow.com [Link to Post Here](http://stackoverflow.com/questions/22876978/loop-inside-react-jsx)

   * Without AdNauseam:
      * 1 Header ad
   * With AdNauseam:
      * Ad was not collected but hidden

5. youtube.com [Link To Video Here](https://www.youtube.com/watch?v=Xv1Yx3eFnEg)
   
   * Without AdNauseam: 2 Ads
      * 1 side ad for Wix
      * 1 video ad for Wix
   * With AdNauseam:
      * Could not duplicate ad with reloading on AdNauseam--none seen and none collected

6. google.com [Link To Search Here](https://www.google.com/search?q=react+stuff&oq=react+stuff&aqs=chrome..69i64j5l5.5552j0j4&sourceid=chrome&ie=UTF-8#q=where+to+buy+t+shirts)

   * Without AdNauseam: Seeing 10 Ads
      * 2 plain text ad options at the top of the search
      * 6 sidebar sponsored links
      * 2 plain text ad options at the bottom of the search 
   * With AdNauseam:
      * AdNauseam collected all ads plus 2 I didn't see on the page on the first load.

7. foreignpolicy.com [Link to Page Here](http://foreignpolicy.com/)

   * Without AdNauseam: Seeing 3 Ads on page
   * With AdNauseam
      *All Three collected

8. fastcompany.com [Link To Article Here](https://www.fastcompany.com/3038286/why-you-dont-need-to-know-how-to-code-to-start-a-tech-company?utm_source=facebook)

   * Without AdNauseam: Seeing 3 Ads on articles
      * 2 side scrolling ads when reading article 
      * 1 video ad in article ad midpoint 
   * With AdNauseam:
      * The 2 side ads were collected
      * 2 other ads were collected that I didn't see in the original load of page
      * The video ad at the midpoint was not collected:
         

         ![image](https://cloud.githubusercontent.com/assets/11656811/25015473/f17dc7da-2049-11e7-9bba-f74d2732788d.png)

9. Forbes.com [Link To Article Here](https://www.forbes.com/sites/darrentristano/2017/04/13/growth-of-ghost-restaurant-concepts-proves-delivery-only-trend-has-legs/#348203893e32)

      * Without AdNauseam: Seeing 3 Ads on articles
           * 1 header ad on article
           * 2 side ads
       * With AdNauseam:
           * All ads were collected in AdNasueam. 


10. Fortune.com          [Link To Article Here](http://fortune.com/2017/04/13/tomi-lahren-glenn-beck-theblaze/)

       * Without AdNauseam: Seeing 3 Ads on articles.
           * 1 main side ad
           * 1 side "sponsored" articles ad
           * 1 ad in related articles labeled "sponsored financial content"
       *With AdNauseam:
           * 2 Ads Blocked 0 collected
                * Main side ad was hidden but not collected by AdNauseam 
                * Side sponsored articles hidden but not collected
           *  1 "sponsored financial content" ad left on page
       * With and without AdNauseam, I am seeing an Ad appear at the bottom of an article


         ![image](https://cloud.githubusercontent.com/assets/11656811/25014471/e337b518-2045-11e7-8d07-d9661752ea56.png)

**Comment by dhowe** [comment]
Good -- now pls create a ticket for each site on which there were visible ads (use the label 'ads visible'), and one for each site where ads were not collected ad (use 'ads not collected' label), including the url and a screencap. 

Then we can discuss how to go about fixing these issues. Note also that we don't (at least for now) collect video ads...

**Comment by dhowe** [comment]
Thanks, Greyson (the general workflow is to close only those tickets that are assigned to you with the 'needs-verification' and are successfully verified)

**Comment by greysonevins** [comment]
Thank you @dhowe! I will make sure to do this going forward!
