### ISSUE TITLE
Duplicates in vault

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#98]
![screen shot 2016-04-01 at 10 50 00 pm](https://cloud.githubusercontent.com/assets/737638/14210580/38f5595a-f85c-11e5-929a-a34c9d60dda6.png)

**Comment by yansh** [comment]
How to reproduce this?

**Comment by dhowe** [comment]
Not sure -- perhaps refreshing pages after 60 seconds..

**Comment by yansh** [comment]
Can it be a case of two ads from the same provider?

**Comment by dhowe** [comment]
In the vault we use the concept of AdSets to determine layout. An adset is a group of ads that are considered duplicates (determined by checking a hash of their data, specifically the found-on page and their contentData). For image ads, the contentData consists only of the image's src attribute. Thus, the hash is pageUrl + imgSrc for image-ads. If these match, then they should appear as part of the same AdSet, visually represented as a single Ad with a purple number representing the number of actual ads in the set. So the above case should be impossible unless the same ad is found on multiple pages. 

The only caveat here is that the URL for a single page can vary each time according to query-string data. So we may need to change the hash to only use the domain of the pageUrl on which the Ad was found, or alternatively, to only consider the contentData.

**Comment by dhowe** [comment]
Can't reproduce so far.

**Comment by dhowe** [comment]
Re-opening...
Need to check properties we are comparing when creating adsets (should, I think, be page/image/target-host only)

**Comment by dhowe** [comment]
Should be fixed in fbccac000a7c3fb1f3aa9b45d741aee9d9deb1ff
Please keep an eye on this (@leoneckert @mushon @cqx931) and re-open if/as needed
