### ISSUE TITLE
Creating an issue template

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#980]
https://help.github.com/articles/creating-an-issue-template-for-your-repository/
uBlock has this in their repository, it makes sense to have one for AdNauseam as well to save some effort in asking OS, browser version etc...

I can try to create one first according to what uBlock has, and you can edit it after that.

**Comment by dhowe** [comment]
Sure, a minimal version would be good (the uBlock one seems too detailed/unfriendly)

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/AdNauseam/blob/master/issue_template.md

**Comment by dhowe** [comment]
Looks good...
