### ISSUE TITLE
Add simple tests for firefox android

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#982]

**Comment by cqx931** [comment]
Tests for Firefox Android

## Interface
&nbsp;&nbsp;&nbsp;&nbsp;<b>First-Run</b>
- Remove and reinstall AdNauseam to trigger this page 
- Test selection of various options (click-ads, block-malware, hide-ads, DNT)
- Check the layout

&nbsp;&nbsp;&nbsp;&nbsp;<b>Menu</b>
- Check all buttons and information (including number of Ads and $$ cost, hidden if no ads)
- Check the layout when adnauseam is paused
- Check there is no text overlap in the menu for text ads

&nbsp;&nbsp;&nbsp;&nbsp;<b>Vault</b>
- Verify loading animation, and centering/scaling of Ads on load
- Zoom in/out using gesture and buttons in top-left corner 
- Check function/layout of Inspector (for both image and text ads)
- Check correct function of date-filter slider at bottom
- Test import/export/clear functions

&nbsp;&nbsp;&nbsp;&nbsp;<b>Dashboard</b>
- Check layout of buttons, check-boxes, and links in each tab
- Test import/export/clear ads functions

------------------

## Basic Functions
- Blocking [here](http://lab-lamp.scm.cityu.edu.hk/adntest/block.html)
- Hiding [here](http://lab-lamp.scm.cityu.edu.hk/adntest/simple.html)
- Clicking
------------------

## Test Update
- Test Manual Update by clicking "Update Now" in settings page
  1.  Change the local uAsset and run tools/update-ublock0.sh to generate a new checksum
  1.  Rebuild AdNauseam
  1.  Click "Update Now" in Settings Page and check 
    - All out-dated filters are updated (background.html console)
    - The total rules of adnauseam has been updated
    - The rules are functioning when test on webpage.
- Test "Update" button for adnauseam.txt


Current Issues:
1.Vault never loads(loading animation)
2.Settings page layout is messy
3.Menu: 
- it works great when it shows AdNauseam(x) in the toolbar. Sometimes it shows AdNauseam(Off) even though I didn't whitelist the site. Need to investigate into this issue later.
-The menu is very small when first open, but can be enlarged with gesture

**Comment by dhowe** [comment]
Good. Can you add separate issues for each of these (besides the repeating background)?

**Comment by cqx931** [comment]
moved the tests to [wiki](https://github.com/dhowe/AdNauseam/wiki/Testing-New-Release-Candidates), close
