### ISSUE TITLE
Ads visible on fortune.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#983]
### Describe the issue

2 sets of ads visible (the first correctly blocked by ublock, the 2nd not)

### One or more specific URLs where the issue occurs

http://fortune.com/2017/04/13/tomi-lahren-glenn-beck-theblaze/

### Screenshot in which the issue can be seen

![image](https://cloud.githubusercontent.com/assets/737638/25041334/fa5d1ba0-2141-11e7-9332-452c255c8733.png)

![image](https://cloud.githubusercontent.com/assets/737638/25041450/a6658c0c-2142-11e7-9272-21e4b082538f.png)

**Comment by greysonevins** [comment]
https://github.com/dhowe/uAssets/pull/41

**Comment by greysonevins** [comment]
https://github.com/dhowe/uAssets/pull/42

**Comment by greysonevins** [comment]
https://github.com/dhowe/uAssets/pull/43
