### ISSUE TITLE
Test updated cookie policy

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#986]
Please make sure cookies are now handled correctly according to our [DevFAQ entry](https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#how-does-adnauseam-handle-incoming-and-outgoing-cookies), and that release tests are updated accordingly.

**Comment by cqx931** [comment]
Just want to make sure that I understood this correctly, do you mean: 

Incoming cookies are blocked if the response is from an
- Ad-visit
- AdNauseam Allowed requests

Incoming cookies are not blocked if the response is from
- a DNT entry ( How about DNT 3rd party cookies?)

**Comment by dhowe** [comment]
> Incoming cookies are blocked if the response is from an
> - Ad-visit
> - AdNauseam Allowed requests

Correct

> Incoming cookies are not blocked if the response is from
> - a DNT entry ( How about DNT 3rd party cookies?)

Correct, assuming DNT-exceptions are enabled (this should only apply to case 2 above, as we don't do visits to DNT-sites if so)

**Comment by cqx931** [comment]
- [x] Cookies from dnt sites won't be blocked
