### ISSUE TITLE
Google banner ads not collected on fortune.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#988]
### Describe the issue

Google banner ads not collected on fortune.com (see top of image below)

Also iframe not collapsed when hidden

### One or more specific URLs where the issue occurs
http://fortune.com/2017/04/15/private-telecom-chattanooga-gig/ 

### Screenshot in which the issue can be seen
![image](https://cloud.githubusercontent.com/assets/737638/25071104/bc69a70e-22e1-11e7-9d08-5db9c88579f9.png)

### Your settings

location: Hong Kong

**Comment by dhowe** [comment]
we need to make sure we are getting common ad types like this

**Comment by cqx931** [comment]
There are many different kinds of ads showing up at this location. And there is one case that could be a very interesting case for further improvements of ad collection:

This case is categorized under dynamic assembled ads.
For this particular case, the a tag does not wrap any element.
The clickable overlay is achieved with css.
So even if adnauseam identified an image within the div, it can't find a clickableParent for the image.

![screen shot 2017-04-18 at 4 41 55 pm](https://cloud.githubusercontent.com/assets/3056154/25122595/0fa6b174-2458-11e7-8868-bade72a61368.png)
![screen shot 2017-04-18 at 4 56 34 pm](https://cloud.githubusercontent.com/assets/3056154/25122597/1379f2f2-2458-11e7-9f20-d1b58212d35d.png)

**Comment by dhowe** [comment]
Are you suggesting that we grab the image which is only part of this ad (and pull the target from a sibling)?

In any case, I am much less worried about this case than the google iframe case, which is *very* common and we still miss (as above)

**Comment by cqx931** [comment]
They are all google iframes...What inside changes for each refresh.
If you could reproduce the above ad and take a screenshot of the dom structure that would be helpful.
Since I can't see the exact same ad, it's hard for me to tell which case it is only from the image.

I did find out one case when there is only an image and an a tag wrapping around, but I'm not sure whether it is the same case as you have above.

**Comment by dhowe** [comment]
> This case is categorized under dynamic assembled ads.
> For this particular case, the a tag does not wrap any element.
> The clickable overlay is achieved with css.

If (and I"m not sure about this) we can consistently identify such 'composite ads', and also parse the target, then perhaps we can grab a screenshot of the entire DOM element

**Comment by cqx931** [comment]
After the latest changes in uAssets, I have verified that ads on fortune content page could be collected, if they are normal image ads.

Please refer to this new ticket for dynamic Ads: https://github.com/dhowe/AdNauseam/issues/765
