### ISSUE TITLE
Add simple go button to first-run page on "chrome-store" branch

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#989]
Need to replace the current fancy button with a simple go button (always visible),
for the chrome-store build (branch: "chrome-store") that does not include blocking functionality...

**Comment by cqx931** [comment]
Removed the changing text and toggle, though I kept the "let's go" text for the button:
https://github.com/dhowe/AdNauseam/pull/990

**Comment by dhowe** [comment]
submitted to chrome-store
