### ISSUE TITLE
Failed to load extension Chrome

### ISSUE THREAD

**Issue by carolinaliz** [dhowe/AdNauseam#993]
### Describe the issue
I followed the manual install instructions for Chrome Version 57.0.2987.133, and got this error message:  Failed to load extension from: ~\Downloads\adnauseam-3.3.32.chromium

Help?
### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version: 
- Browser/version: 
- AdNauseam version: 
- Other extensions you have installed:

**Comment by greysonevins** [comment]
Sorry to hear the problem @carolinaliz. Can I ask, did you download the .crx or .zip file from https://github.com/dhowe/AdNauseam/releases/

**Comment by carolinaliz** [comment]
I tried both.  Got a different error for each.  For the .crx file it said "Apps, extensions, and user scripts cannot be added from this website."  For the .zip file, I extracted it, tried loading it in extensions following the instructions, and got the above error message.

**Comment by dhowe** [comment]
I just tested this and cannot recreate the problem (see below). Did you enable 'developer-mode'?

![image](https://cloud.githubusercontent.com/assets/737638/25162342/8df8e4ba-24f4-11e7-8b1a-1526a4da432a.png)
