### ISSUE TITLE
[Firefox Android] Mobile optimization for firstrun page and menu

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#997]
-bigger font size
-full page menu

**Comment by greysonevins** [comment]
For this issue, I do not have an Android to test with. Do recommend any other ways of testing this @dhowe

**Comment by greysonevins** [comment]
@dhowe Should I be assigned for this one? I cannot test Android.

**Comment by cqx931** [comment]
Finished https://github.com/dhowe/AdNauseam/pull/1090

**Comment by mneunomne** [comment]
> Finished https://github.com/dhowe/AdNauseam/pull/1090

This was already implemented, the interface is looking fine on mobile. closing.
