### ISSUE TITLE
The url of effdntlist preview is broken

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#998]
chrome-extension://jflohihlppclmnhmjghiljidceocbbce/asset-viewer.html?url=https://www.eff.org/files/effdntlist.txt

Nothing is shown.

**Comment by dhowe** [comment]
Looks ok for me (at least the link above does)

**Comment by cqx931** [comment]
Fixed https://github.com/dhowe/AdNauseam/pull/1009/commits/5772374029c1e24555f036a87f6a914a1d572044
